<?php

namespace Gerardojbaez\GeoData\Seeders;

use Illuminate\Database\Seeder;
use Gerardojbaez\GeoData\Models\Country;
use Gerardojbaez\GeoData\Models\Region;
use Gerardojbaez\GeoData\Models\City;

class AfghanistanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Country::create($this->country());
        Region::insert($this->regions());

        if ($this->cities() > 4000)
        {
            foreach (array_chunk($this->cities(), 3500) as $chunk)
                City::insert($chunk);
        }
        else
        {
            City::insert($this->cities());
        }
    }

        /**
     * Get country.
     *
     * @return array
     */
    public function country()
    {
    	return ['code' => 'AF', 'name' => 'Afghanistan', 'slug' => 'afghanistan'];
    }

    /**
     * Get country regions.
     *
     * @return array
     */
    public function regions()
    {
    	return [
            ['id' => 781063, 'country_code' => 'AF', 'name' => 'Badahsan', 'active' => 1, 'slug' => 'badahsan'],
            ['id' => 781092, 'country_code' => 'AF', 'name' => 'Badgis', 'active' => 1, 'slug' => 'badgis'],
            ['id' => 781100, 'country_code' => 'AF', 'name' => 'Baglan', 'active' => 1, 'slug' => 'baglan'],
            ['id' => 781113, 'country_code' => 'AF', 'name' => 'Balh', 'active' => 1, 'slug' => 'balh'],
            ['id' => 781128, 'country_code' => 'AF', 'name' => 'Bamiyan', 'active' => 1, 'slug' => 'bamiyan'],
            ['id' => 781134, 'country_code' => 'AF', 'name' => 'Daikondi', 'active' => 1, 'slug' => 'daikondi'],
            ['id' => 781144, 'country_code' => 'AF', 'name' => 'Farah', 'active' => 1, 'slug' => 'farah'],
            ['id' => 781155, 'country_code' => 'AF', 'name' => 'Faryab', 'active' => 1, 'slug' => 'faryab'],
            ['id' => 781168, 'country_code' => 'AF', 'name' => 'Gawr', 'active' => 1, 'slug' => 'gawr'],
            ['id' => 781175, 'country_code' => 'AF', 'name' => 'Gazni', 'active' => 1, 'slug' => 'gazni'],
            ['id' => 781192, 'country_code' => 'AF', 'name' => 'Hawst', 'active' => 1, 'slug' => 'hawst'],
            ['id' => 781205, 'country_code' => 'AF', 'name' => 'Herat', 'active' => 1, 'slug' => 'herat'],
            ['id' => 781222, 'country_code' => 'AF', 'name' => 'Hilmand', 'active' => 1, 'slug' => 'hilmand'],
            ['id' => 781236, 'country_code' => 'AF', 'name' => 'Jawzjan', 'active' => 1, 'slug' => 'jawzjan'],
            ['id' => 781246, 'country_code' => 'AF', 'name' => 'Kabul', 'active' => 1, 'slug' => 'kabul'],
            ['id' => 781261, 'country_code' => 'AF', 'name' => 'Kapisa', 'active' => 1, 'slug' => 'kapisa'],
            ['id' => 781268, 'country_code' => 'AF', 'name' => 'Kunar', 'active' => 1, 'slug' => 'kunar'],
            ['id' => 781284, 'country_code' => 'AF', 'name' => 'Lagman', 'active' => 1, 'slug' => 'lagman'],
            ['id' => 781290, 'country_code' => 'AF', 'name' => 'Lawgar', 'active' => 1, 'slug' => 'lawgar'],
            ['id' => 781298, 'country_code' => 'AF', 'name' => 'Nangarhar', 'active' => 1, 'slug' => 'nangarhar'],
            ['id' => 781321, 'country_code' => 'AF', 'name' => 'Nimruz', 'active' => 1, 'slug' => 'nimruz'],
            ['id' => 781327, 'country_code' => 'AF', 'name' => 'Nuristan', 'active' => 1, 'slug' => 'nuristan'],
            ['id' => 781334, 'country_code' => 'AF', 'name' => 'Paktika', 'active' => 1, 'slug' => 'paktika'],
            ['id' => 781350, 'country_code' => 'AF', 'name' => 'Paktiya', 'active' => 1, 'slug' => 'paktiya'],
            ['id' => 781364, 'country_code' => 'AF', 'name' => 'Panjshir', 'active' => 1, 'slug' => 'panjshir'],
            ['id' => 781369, 'country_code' => 'AF', 'name' => 'Parwan', 'active' => 1, 'slug' => 'parwan'],
            ['id' => 781378, 'country_code' => 'AF', 'name' => 'Qandahar', 'active' => 1, 'slug' => 'qandahar'],
            ['id' => 781396, 'country_code' => 'AF', 'name' => 'Qunduz', 'active' => 1, 'slug' => 'qunduz'],
            ['id' => 781404, 'country_code' => 'AF', 'name' => 'Samangan', 'active' => 1, 'slug' => 'samangan'],
            ['id' => 781410, 'country_code' => 'AF', 'name' => 'Sar-e Pul', 'active' => 1, 'slug' => 'sar-e-pul'],
            ['id' => 781417, 'country_code' => 'AF', 'name' => 'Tahar', 'active' => 1, 'slug' => 'tahar'],
            ['id' => 781429, 'country_code' => 'AF', 'name' => 'Uruzgan', 'active' => 1, 'slug' => 'uruzgan'],
            ['id' => 781437, 'country_code' => 'AF', 'name' => 'Vardak', 'active' => 1, 'slug' => 'vardak'],
            ['id' => 781447, 'country_code' => 'AF', 'name' => 'Zabul', 'active' => 1, 'slug' => 'zabul']
    	];
    }

    /**
     * Get region cities.
     *
     * @return array
     */
    public function cities()
    {
    	return [
            ['id' => 44398, 'region_id' => 781063, 'country_code' => 'AF', 'name' => 'Arghanj Khwa', 'active' => 1, 'slug' => 'arghanj-khwa'],
            ['id' => 44399, 'region_id' => 781063, 'country_code' => 'AF', 'name' => 'Argo', 'active' => 1, 'slug' => 'argo'],
            ['id' => 44400, 'region_id' => 781063, 'country_code' => 'AF', 'name' => 'Baharak', 'active' => 1, 'slug' => 'baharak'],
            ['id' => 44401, 'region_id' => 781063, 'country_code' => 'AF', 'name' => 'Darayim', 'active' => 1, 'slug' => 'darayim'],
            ['id' => 44402, 'region_id' => 781063, 'country_code' => 'AF', 'name' => 'Darwaz', 'active' => 1, 'slug' => 'darwaz'],
            ['id' => 44403, 'region_id' => 781063, 'country_code' => 'AF', 'name' => 'Darwazi Bala', 'active' => 1, 'slug' => 'darwazi-bala'],
            ['id' => 44404, 'region_id' => 781063, 'country_code' => 'AF', 'name' => 'Fayzabad', 'active' => 1, 'slug' => 'fayzabad'],
            ['id' => 44405, 'region_id' => 781063, 'country_code' => 'AF', 'name' => 'Ishkashim', 'active' => 1, 'slug' => 'ishkashim'],
            ['id' => 44406, 'region_id' => 781063, 'country_code' => 'AF', 'name' => 'Jurm', 'active' => 1, 'slug' => 'jurm'],
            ['id' => 44407, 'region_id' => 781063, 'country_code' => 'AF', 'name' => 'Khash', 'active' => 1, 'slug' => 'khash'],
            ['id' => 44408, 'region_id' => 781063, 'country_code' => 'AF', 'name' => 'Khwakan', 'active' => 1, 'slug' => 'khwakan'],
            ['id' => 44409, 'region_id' => 781063, 'country_code' => 'AF', 'name' => 'Kishim', 'active' => 1, 'slug' => 'kishim'],
            ['id' => 44410, 'region_id' => 781063, 'country_code' => 'AF', 'name' => 'Kohistan', 'active' => 1, 'slug' => 'kohistan'],
            ['id' => 44411, 'region_id' => 781063, 'country_code' => 'AF', 'name' => 'Kuf ab', 'active' => 1, 'slug' => 'kuf-ab'],
            ['id' => 44412, 'region_id' => 781063, 'country_code' => 'AF', 'name' => 'Kuran Wa Munjan', 'active' => 1, 'slug' => 'kuran-wa-munjan'],
            ['id' => 44413, 'region_id' => 781063, 'country_code' => 'AF', 'name' => 'Ragh', 'active' => 1, 'slug' => 'ragh'],
            ['id' => 44414, 'region_id' => 781063, 'country_code' => 'AF', 'name' => 'Shar-i-buzurg', 'active' => 1, 'slug' => 'shar-i-buzurg'],
            ['id' => 44415, 'region_id' => 781063, 'country_code' => 'AF', 'name' => 'Shigman', 'active' => 1, 'slug' => 'shigman'],
            ['id' => 44416, 'region_id' => 781063, 'country_code' => 'AF', 'name' => 'Shiki', 'active' => 1, 'slug' => 'shiki'],
            ['id' => 44417, 'region_id' => 781063, 'country_code' => 'AF', 'name' => 'Shuhada', 'active' => 1, 'slug' => 'shuhada'],
            ['id' => 44418, 'region_id' => 781063, 'country_code' => 'AF', 'name' => 'Tagab', 'active' => 1, 'slug' => 'tagab'],
            ['id' => 44419, 'region_id' => 781063, 'country_code' => 'AF', 'name' => 'Tishkan', 'active' => 1, 'slug' => 'tishkan'],
            ['id' => 44420, 'region_id' => 781063, 'country_code' => 'AF', 'name' => 'Wakhan', 'active' => 1, 'slug' => 'wakhan'],
            ['id' => 44421, 'region_id' => 781063, 'country_code' => 'AF', 'name' => 'Wurduj', 'active' => 1, 'slug' => 'wurduj'],
            ['id' => 44422, 'region_id' => 781063, 'country_code' => 'AF', 'name' => 'Yaftali Sufka', 'active' => 1, 'slug' => 'yaftali-sufka'],
            ['id' => 44423, 'region_id' => 781063, 'country_code' => 'AF', 'name' => 'Yamgan', 'active' => 1, 'slug' => 'yamgan'],
            ['id' => 44424, 'region_id' => 781063, 'country_code' => 'AF', 'name' => 'Yawan', 'active' => 1, 'slug' => 'yawan'],
            ['id' => 44425, 'region_id' => 781063, 'country_code' => 'AF', 'name' => 'Zebak', 'active' => 1, 'slug' => 'zebak'],
            ['id' => 44426, 'region_id' => 781092, 'country_code' => 'AF', 'name' => 'Ab Kamari', 'active' => 1, 'slug' => 'ab-kamari'],
            ['id' => 44427, 'region_id' => 781092, 'country_code' => 'AF', 'name' => 'Ghormach', 'active' => 1, 'slug' => 'ghormach'],
            ['id' => 44428, 'region_id' => 781092, 'country_code' => 'AF', 'name' => 'Jawand', 'active' => 1, 'slug' => 'jawand'],
            ['id' => 44429, 'region_id' => 781092, 'country_code' => 'AF', 'name' => 'Muqur', 'active' => 1, 'slug' => 'muqur'],
            ['id' => 44430, 'region_id' => 781092, 'country_code' => 'AF', 'name' => 'Murghab', 'active' => 1, 'slug' => 'murghab'],
            ['id' => 44431, 'region_id' => 781092, 'country_code' => 'AF', 'name' => 'Qadis', 'active' => 1, 'slug' => 'qadis'],
            ['id' => 44432, 'region_id' => 781092, 'country_code' => 'AF', 'name' => 'Qala-i-naw', 'active' => 1, 'slug' => 'qala-i-naw'],
            ['id' => 44433, 'region_id' => 781100, 'country_code' => 'AF', 'name' => 'Andarab', 'active' => 1, 'slug' => 'andarab'],
            ['id' => 44434, 'region_id' => 781100, 'country_code' => 'AF', 'name' => 'Baghlan', 'active' => 1, 'slug' => 'baghlan'],
            ['id' => 44435, 'region_id' => 781100, 'country_code' => 'AF', 'name' => 'Baghlani Jadid', 'active' => 1, 'slug' => 'baghlani-jadid'],
            ['id' => 44436, 'region_id' => 781100, 'country_code' => 'AF', 'name' => 'Burka', 'active' => 1, 'slug' => 'burka'],
            ['id' => 44437, 'region_id' => 781100, 'country_code' => 'AF', 'name' => 'Dahana-i-ghori', 'active' => 1, 'slug' => 'dahana-i-ghori'],
            ['id' => 44438, 'region_id' => 781100, 'country_code' => 'AF', 'name' => 'Dushi', 'active' => 1, 'slug' => 'dushi'],
            ['id' => 44439, 'region_id' => 781100, 'country_code' => 'AF', 'name' => 'Kahmard', 'active' => 1, 'slug' => 'kahmard'],
            ['id' => 44440, 'region_id' => 781100, 'country_code' => 'AF', 'name' => 'Khinjan', 'active' => 1, 'slug' => 'khinjan'],
            ['id' => 44441, 'region_id' => 781100, 'country_code' => 'AF', 'name' => 'Khost Wa Firing', 'active' => 1, 'slug' => 'khost-wa-firing'],
            ['id' => 44442, 'region_id' => 781100, 'country_code' => 'AF', 'name' => 'Nahrin', 'active' => 1, 'slug' => 'nahrin'],
            ['id' => 44443, 'region_id' => 781100, 'country_code' => 'AF', 'name' => 'Puli Khumri', 'active' => 1, 'slug' => 'puli-khumri'],
            ['id' => 44444, 'region_id' => 781100, 'country_code' => 'AF', 'name' => 'Tala Wa Barfak', 'active' => 1, 'slug' => 'tala-wa-barfak'],
            ['id' => 44445, 'region_id' => 781113, 'country_code' => 'AF', 'name' => 'Balk', 'active' => 1, 'slug' => 'balk'],
            ['id' => 44446, 'region_id' => 781113, 'country_code' => 'AF', 'name' => 'Chahar Bolak', 'active' => 1, 'slug' => 'chahar-bolak'],
            ['id' => 44447, 'region_id' => 781113, 'country_code' => 'AF', 'name' => 'Chahar Kint', 'active' => 1, 'slug' => 'chahar-kint'],
            ['id' => 44448, 'region_id' => 781113, 'country_code' => 'AF', 'name' => 'Chimtal', 'active' => 1, 'slug' => 'chimtal'],
            ['id' => 44449, 'region_id' => 781113, 'country_code' => 'AF', 'name' => 'Dawlatabad', 'active' => 1, 'slug' => 'dawlatabad'],
            ['id' => 44450, 'region_id' => 781113, 'country_code' => 'AF', 'name' => 'Dihdadi', 'active' => 1, 'slug' => 'dihdadi'],
            ['id' => 44451, 'region_id' => 781113, 'country_code' => 'AF', 'name' => 'Kaldar', 'active' => 1, 'slug' => 'kaldar'],
            ['id' => 44452, 'region_id' => 781113, 'country_code' => 'AF', 'name' => 'Khulm', 'active' => 1, 'slug' => 'khulm'],
            ['id' => 44453, 'region_id' => 781113, 'country_code' => 'AF', 'name' => 'Kishindih', 'active' => 1, 'slug' => 'kishindih'],
            ['id' => 44454, 'region_id' => 781113, 'country_code' => 'AF', 'name' => 'Marmul', 'active' => 1, 'slug' => 'marmul'],
            ['id' => 44455, 'region_id' => 781113, 'country_code' => 'AF', 'name' => 'Mazari Sharif', 'active' => 1, 'slug' => 'mazari-sharif'],
            ['id' => 44456, 'region_id' => 781113, 'country_code' => 'AF', 'name' => 'Nahri Shahi', 'active' => 1, 'slug' => 'nahri-shahi'],
            ['id' => 44457, 'region_id' => 781113, 'country_code' => 'AF', 'name' => 'Sholgara', 'active' => 1, 'slug' => 'sholgara'],
            ['id' => 44458, 'region_id' => 781113, 'country_code' => 'AF', 'name' => 'Shortepa', 'active' => 1, 'slug' => 'shortepa'],
            ['id' => 44459, 'region_id' => 781128, 'country_code' => 'AF', 'name' => 'Bamiyan', 'active' => 1, 'slug' => 'bamiyan'],
            ['id' => 44460, 'region_id' => 781128, 'country_code' => 'AF', 'name' => 'Panjab', 'active' => 1, 'slug' => 'panjab'],
            ['id' => 44461, 'region_id' => 781128, 'country_code' => 'AF', 'name' => 'Shibar', 'active' => 1, 'slug' => 'shibar'],
            ['id' => 44462, 'region_id' => 781128, 'country_code' => 'AF', 'name' => 'Waras', 'active' => 1, 'slug' => 'waras'],
            ['id' => 44463, 'region_id' => 781128, 'country_code' => 'AF', 'name' => 'Yakawlang', 'active' => 1, 'slug' => 'yakawlang'],
            ['id' => 44464, 'region_id' => 781134, 'country_code' => 'AF', 'name' => 'Gizab', 'active' => 1, 'slug' => 'gizab'],
            ['id' => 44465, 'region_id' => 781134, 'country_code' => 'AF', 'name' => 'Ishtarlay', 'active' => 1, 'slug' => 'ishtarlay'],
            ['id' => 44466, 'region_id' => 781134, 'country_code' => 'AF', 'name' => 'Kajran', 'active' => 1, 'slug' => 'kajran'],
            ['id' => 44467, 'region_id' => 781134, 'country_code' => 'AF', 'name' => 'Khadir', 'active' => 1, 'slug' => 'khadir'],
            ['id' => 44468, 'region_id' => 781134, 'country_code' => 'AF', 'name' => 'Kiti', 'active' => 1, 'slug' => 'kiti'],
            ['id' => 44469, 'region_id' => 781134, 'country_code' => 'AF', 'name' => 'Miramor', 'active' => 1, 'slug' => 'miramor'],
            ['id' => 44470, 'region_id' => 781134, 'country_code' => 'AF', 'name' => 'Nili', 'active' => 1, 'slug' => 'nili'],
            ['id' => 44471, 'region_id' => 781134, 'country_code' => 'AF', 'name' => 'Sangi Takht', 'active' => 1, 'slug' => 'sangi-takht'],
            ['id' => 44472, 'region_id' => 781134, 'country_code' => 'AF', 'name' => 'Shahristan', 'active' => 1, 'slug' => 'shahristan'],
            ['id' => 44473, 'region_id' => 781144, 'country_code' => 'AF', 'name' => 'Anar Dara', 'active' => 1, 'slug' => 'anar-dara'],
            ['id' => 44474, 'region_id' => 781144, 'country_code' => 'AF', 'name' => 'Bakwa', 'active' => 1, 'slug' => 'bakwa'],
            ['id' => 44475, 'region_id' => 781144, 'country_code' => 'AF', 'name' => 'Bala Buluk', 'active' => 1, 'slug' => 'bala-buluk'],
            ['id' => 44476, 'region_id' => 781144, 'country_code' => 'AF', 'name' => 'Farah', 'active' => 1, 'slug' => 'farah'],
            ['id' => 44477, 'region_id' => 781144, 'country_code' => 'AF', 'name' => 'Gulistan', 'active' => 1, 'slug' => 'gulistan'],
            ['id' => 44478, 'region_id' => 781144, 'country_code' => 'AF', 'name' => 'Khaki Safed', 'active' => 1, 'slug' => 'khaki-safed'],
            ['id' => 44479, 'region_id' => 781144, 'country_code' => 'AF', 'name' => 'Lash Wa Juwayn', 'active' => 1, 'slug' => 'lash-wa-juwayn'],
            ['id' => 44480, 'region_id' => 781144, 'country_code' => 'AF', 'name' => 'Pur Chaman', 'active' => 1, 'slug' => 'pur-chaman'],
            ['id' => 44481, 'region_id' => 781144, 'country_code' => 'AF', 'name' => 'Pusht Rod', 'active' => 1, 'slug' => 'pusht-rod'],
            ['id' => 44482, 'region_id' => 781144, 'country_code' => 'AF', 'name' => 'Shib Koh', 'active' => 1, 'slug' => 'shib-koh'],
            ['id' => 44483, 'region_id' => 781155, 'country_code' => 'AF', 'name' => 'Almar', 'active' => 1, 'slug' => 'almar'],
            ['id' => 44484, 'region_id' => 781155, 'country_code' => 'AF', 'name' => 'Andkhoy', 'active' => 1, 'slug' => 'andkhoy'],
            ['id' => 44485, 'region_id' => 781155, 'country_code' => 'AF', 'name' => 'Bilchiragh', 'active' => 1, 'slug' => 'bilchiragh'],
            ['id' => 44486, 'region_id' => 781155, 'country_code' => 'AF', 'name' => 'Dawlatabad', 'active' => 1, 'slug' => 'dawlatabad'],
            ['id' => 44487, 'region_id' => 781155, 'country_code' => 'AF', 'name' => 'Khani Chahar Bagh', 'active' => 1, 'slug' => 'khani-chahar-bagh'],
            ['id' => 44488, 'region_id' => 781155, 'country_code' => 'AF', 'name' => 'Khwaja Sabz Posh', 'active' => 1, 'slug' => 'khwaja-sabz-posh'],
            ['id' => 44489, 'region_id' => 781155, 'country_code' => 'AF', 'name' => 'Kohistan', 'active' => 1, 'slug' => 'kohistan'],
            ['id' => 44490, 'region_id' => 781155, 'country_code' => 'AF', 'name' => 'Maymana', 'active' => 1, 'slug' => 'maymana'],
            ['id' => 44491, 'region_id' => 781155, 'country_code' => 'AF', 'name' => 'Pashtun Kot', 'active' => 1, 'slug' => 'pashtun-kot'],
            ['id' => 44492, 'region_id' => 781155, 'country_code' => 'AF', 'name' => 'Qaramqol', 'active' => 1, 'slug' => 'qaramqol'],
            ['id' => 44493, 'region_id' => 781155, 'country_code' => 'AF', 'name' => 'Qaysar', 'active' => 1, 'slug' => 'qaysar'],
            ['id' => 44494, 'region_id' => 781155, 'country_code' => 'AF', 'name' => 'Shirin Tagab', 'active' => 1, 'slug' => 'shirin-tagab'],
            ['id' => 44495, 'region_id' => 781168, 'country_code' => 'AF', 'name' => 'Chaghcharan', 'active' => 1, 'slug' => 'chaghcharan'],
            ['id' => 44496, 'region_id' => 781168, 'country_code' => 'AF', 'name' => 'Lal Wa Sarjangal', 'active' => 1, 'slug' => 'lal-wa-sarjangal'],
            ['id' => 44497, 'region_id' => 781168, 'country_code' => 'AF', 'name' => 'Pasaband', 'active' => 1, 'slug' => 'pasaband'],
            ['id' => 44498, 'region_id' => 781168, 'country_code' => 'AF', 'name' => 'Shahrak', 'active' => 1, 'slug' => 'shahrak'],
            ['id' => 44499, 'region_id' => 781168, 'country_code' => 'AF', 'name' => 'Taywara', 'active' => 1, 'slug' => 'taywara'],
            ['id' => 44500, 'region_id' => 781168, 'country_code' => 'AF', 'name' => 'Tulak', 'active' => 1, 'slug' => 'tulak'],
            ['id' => 44501, 'region_id' => 781175, 'country_code' => 'AF', 'name' => 'Ab Band', 'active' => 1, 'slug' => 'ab-band'],
            ['id' => 44502, 'region_id' => 781175, 'country_code' => 'AF', 'name' => 'Ajristan', 'active' => 1, 'slug' => 'ajristan'],
            ['id' => 44503, 'region_id' => 781175, 'country_code' => 'AF', 'name' => 'Bahrami Shahid', 'active' => 1, 'slug' => 'bahrami-shahid'],
            ['id' => 44504, 'region_id' => 781175, 'country_code' => 'AF', 'name' => 'Dih Yak', 'active' => 1, 'slug' => 'dih-yak'],
            ['id' => 44505, 'region_id' => 781175, 'country_code' => 'AF', 'name' => 'Gelan', 'active' => 1, 'slug' => 'gelan'],
            ['id' => 44506, 'region_id' => 781175, 'country_code' => 'AF', 'name' => 'Ghazni', 'active' => 1, 'slug' => 'ghazni'],
            ['id' => 44507, 'region_id' => 781175, 'country_code' => 'AF', 'name' => 'Giro', 'active' => 1, 'slug' => 'giro'],
            ['id' => 44508, 'region_id' => 781175, 'country_code' => 'AF', 'name' => 'Jaghatu', 'active' => 1, 'slug' => 'jaghatu'],
            ['id' => 44509, 'region_id' => 781175, 'country_code' => 'AF', 'name' => 'Jaghuri', 'active' => 1, 'slug' => 'jaghuri'],
            ['id' => 44510, 'region_id' => 781175, 'country_code' => 'AF', 'name' => 'Malistan', 'active' => 1, 'slug' => 'malistan'],
            ['id' => 44511, 'region_id' => 781175, 'country_code' => 'AF', 'name' => 'Miri', 'active' => 1, 'slug' => 'miri'],
            ['id' => 44512, 'region_id' => 781175, 'country_code' => 'AF', 'name' => 'Muqur', 'active' => 1, 'slug' => 'muqur'],
            ['id' => 44513, 'region_id' => 781175, 'country_code' => 'AF', 'name' => 'Nawa', 'active' => 1, 'slug' => 'nawa'],
            ['id' => 44514, 'region_id' => 781175, 'country_code' => 'AF', 'name' => 'Nawur', 'active' => 1, 'slug' => 'nawur'],
            ['id' => 44515, 'region_id' => 781175, 'country_code' => 'AF', 'name' => 'Qarabagh', 'active' => 1, 'slug' => 'qarabagh'],
            ['id' => 44516, 'region_id' => 781175, 'country_code' => 'AF', 'name' => 'Zana Khan', 'active' => 1, 'slug' => 'zana-khan'],
            ['id' => 44517, 'region_id' => 781192, 'country_code' => 'AF', 'name' => 'Bak', 'active' => 1, 'slug' => 'bak'],
            ['id' => 44518, 'region_id' => 781192, 'country_code' => 'AF', 'name' => 'Gurbuz', 'active' => 1, 'slug' => 'gurbuz'],
            ['id' => 44519, 'region_id' => 781192, 'country_code' => 'AF', 'name' => 'Jaji Maydan', 'active' => 1, 'slug' => 'jaji-maydan'],
            ['id' => 44520, 'region_id' => 781192, 'country_code' => 'AF', 'name' => 'Khost', 'active' => 1, 'slug' => 'khost'],
            ['id' => 44521, 'region_id' => 781192, 'country_code' => 'AF', 'name' => 'Mando Zayi', 'active' => 1, 'slug' => 'mando-zayi'],
            ['id' => 44522, 'region_id' => 781192, 'country_code' => 'AF', 'name' => 'Musa Khel', 'active' => 1, 'slug' => 'musa-khel'],
            ['id' => 44523, 'region_id' => 781192, 'country_code' => 'AF', 'name' => 'Nadir Shah Kot', 'active' => 1, 'slug' => 'nadir-shah-kot'],
            ['id' => 44524, 'region_id' => 781192, 'country_code' => 'AF', 'name' => 'Qalandar', 'active' => 1, 'slug' => 'qalandar'],
            ['id' => 44525, 'region_id' => 781192, 'country_code' => 'AF', 'name' => 'Sabari', 'active' => 1, 'slug' => 'sabari'],
            ['id' => 44526, 'region_id' => 781192, 'country_code' => 'AF', 'name' => 'Spera', 'active' => 1, 'slug' => 'spera'],
            ['id' => 44527, 'region_id' => 781192, 'country_code' => 'AF', 'name' => 'Tani', 'active' => 1, 'slug' => 'tani'],
            ['id' => 44528, 'region_id' => 781192, 'country_code' => 'AF', 'name' => 'Tere Zayi', 'active' => 1, 'slug' => 'tere-zayi'],
            ['id' => 44529, 'region_id' => 781205, 'country_code' => 'AF', 'name' => 'Adraskan', 'active' => 1, 'slug' => 'adraskan'],
            ['id' => 44530, 'region_id' => 781205, 'country_code' => 'AF', 'name' => 'Chishti Sharif', 'active' => 1, 'slug' => 'chishti-sharif'],
            ['id' => 44531, 'region_id' => 781205, 'country_code' => 'AF', 'name' => 'Farsi', 'active' => 1, 'slug' => 'farsi'],
            ['id' => 44532, 'region_id' => 781205, 'country_code' => 'AF', 'name' => 'Ghoryan', 'active' => 1, 'slug' => 'ghoryan'],
            ['id' => 44533, 'region_id' => 781205, 'country_code' => 'AF', 'name' => 'Gulran', 'active' => 1, 'slug' => 'gulran'],
            ['id' => 44534, 'region_id' => 781205, 'country_code' => 'AF', 'name' => 'Guzara', 'active' => 1, 'slug' => 'guzara'],
            ['id' => 44535, 'region_id' => 781205, 'country_code' => 'AF', 'name' => 'Hirat', 'active' => 1, 'slug' => 'hirat'],
            ['id' => 44536, 'region_id' => 781205, 'country_code' => 'AF', 'name' => 'Injil', 'active' => 1, 'slug' => 'injil'],
            ['id' => 44537, 'region_id' => 781205, 'country_code' => 'AF', 'name' => 'Karukh', 'active' => 1, 'slug' => 'karukh'],
            ['id' => 44538, 'region_id' => 781205, 'country_code' => 'AF', 'name' => 'Kohsan', 'active' => 1, 'slug' => 'kohsan'],
            ['id' => 44539, 'region_id' => 781205, 'country_code' => 'AF', 'name' => 'Kushk', 'active' => 1, 'slug' => 'kushk'],
            ['id' => 44540, 'region_id' => 781205, 'country_code' => 'AF', 'name' => 'Kushki Kuhma', 'active' => 1, 'slug' => 'kushki-kuhma'],
            ['id' => 44541, 'region_id' => 781205, 'country_code' => 'AF', 'name' => 'Obe', 'active' => 1, 'slug' => 'obe'],
            ['id' => 44542, 'region_id' => 781205, 'country_code' => 'AF', 'name' => 'Pashtun Zarghun', 'active' => 1, 'slug' => 'pashtun-zarghun'],
            ['id' => 44543, 'region_id' => 781205, 'country_code' => 'AF', 'name' => 'Shindad', 'active' => 1, 'slug' => 'shindad'],
            ['id' => 44544, 'region_id' => 781205, 'country_code' => 'AF', 'name' => 'Zinda Jan', 'active' => 1, 'slug' => 'zinda-jan'],
            ['id' => 44545, 'region_id' => 781222, 'country_code' => 'AF', 'name' => 'Baghran', 'active' => 1, 'slug' => 'baghran'],
            ['id' => 44546, 'region_id' => 781222, 'country_code' => 'AF', 'name' => 'Dishu', 'active' => 1, 'slug' => 'dishu'],
            ['id' => 44547, 'region_id' => 781222, 'country_code' => 'AF', 'name' => 'Garmser', 'active' => 1, 'slug' => 'garmser'],
            ['id' => 44548, 'region_id' => 781222, 'country_code' => 'AF', 'name' => 'Kajaki', 'active' => 1, 'slug' => 'kajaki'],
            ['id' => 44549, 'region_id' => 781222, 'country_code' => 'AF', 'name' => 'Lashkar Gah', 'active' => 1, 'slug' => 'lashkar-gah'],
            ['id' => 44550, 'region_id' => 781222, 'country_code' => 'AF', 'name' => 'Musa Qala', 'active' => 1, 'slug' => 'musa-qala'],
            ['id' => 44551, 'region_id' => 781222, 'country_code' => 'AF', 'name' => 'Nad Ali', 'active' => 1, 'slug' => 'nad-ali'],
            ['id' => 44552, 'region_id' => 781222, 'country_code' => 'AF', 'name' => 'Nahri Sarraj', 'active' => 1, 'slug' => 'nahri-sarraj'],
            ['id' => 44553, 'region_id' => 781222, 'country_code' => 'AF', 'name' => 'Naw Zad', 'active' => 1, 'slug' => 'naw-zad'],
            ['id' => 44554, 'region_id' => 781222, 'country_code' => 'AF', 'name' => 'Nawa-i-barakzayi', 'active' => 1, 'slug' => 'nawa-i-barakzayi'],
            ['id' => 44555, 'region_id' => 781222, 'country_code' => 'AF', 'name' => 'Reg', 'active' => 1, 'slug' => 'reg'],
            ['id' => 44556, 'region_id' => 781222, 'country_code' => 'AF', 'name' => 'Sangin', 'active' => 1, 'slug' => 'sangin'],
            ['id' => 44557, 'region_id' => 781222, 'country_code' => 'AF', 'name' => 'Washer', 'active' => 1, 'slug' => 'washer'],
            ['id' => 44558, 'region_id' => 781236, 'country_code' => 'AF', 'name' => 'Aqcha', 'active' => 1, 'slug' => 'aqcha'],
            ['id' => 44559, 'region_id' => 781236, 'country_code' => 'AF', 'name' => 'Darzab', 'active' => 1, 'slug' => 'darzab'],
            ['id' => 44560, 'region_id' => 781236, 'country_code' => 'AF', 'name' => 'Fayzabad', 'active' => 1, 'slug' => 'fayzabad'],
            ['id' => 44561, 'region_id' => 781236, 'country_code' => 'AF', 'name' => 'Khamyab', 'active' => 1, 'slug' => 'khamyab'],
            ['id' => 44562, 'region_id' => 781236, 'country_code' => 'AF', 'name' => 'Khwaja Du Koh', 'active' => 1, 'slug' => 'khwaja-du-koh'],
            ['id' => 44563, 'region_id' => 781236, 'country_code' => 'AF', 'name' => 'Mardyan', 'active' => 1, 'slug' => 'mardyan'],
            ['id' => 44564, 'region_id' => 781236, 'country_code' => 'AF', 'name' => 'Mingajik', 'active' => 1, 'slug' => 'mingajik'],
            ['id' => 44565, 'region_id' => 781236, 'country_code' => 'AF', 'name' => 'Qarqin', 'active' => 1, 'slug' => 'qarqin'],
            ['id' => 44566, 'region_id' => 781236, 'country_code' => 'AF', 'name' => 'Shibirghan', 'active' => 1, 'slug' => 'shibirghan'],
            ['id' => 44567, 'region_id' => 781246, 'country_code' => 'AF', 'name' => 'Bagrami', 'active' => 1, 'slug' => 'bagrami'],
            ['id' => 44568, 'region_id' => 781246, 'country_code' => 'AF', 'name' => 'Chahar Asyab', 'active' => 1, 'slug' => 'chahar-asyab'],
            ['id' => 44569, 'region_id' => 781246, 'country_code' => 'AF', 'name' => 'Dih Sabz', 'active' => 1, 'slug' => 'dih-sabz'],
            ['id' => 44570, 'region_id' => 781246, 'country_code' => 'AF', 'name' => 'Guldara', 'active' => 1, 'slug' => 'guldara'],
            ['id' => 44571, 'region_id' => 781246, 'country_code' => 'AF', 'name' => 'Istalif', 'active' => 1, 'slug' => 'istalif'],
            ['id' => 44572, 'region_id' => 781246, 'country_code' => 'AF', 'name' => 'Kabul', 'active' => 1, 'slug' => 'kabul'],
            ['id' => 44573, 'region_id' => 781246, 'country_code' => 'AF', 'name' => 'Kalakan', 'active' => 1, 'slug' => 'kalakan'],
            ['id' => 44574, 'region_id' => 781246, 'country_code' => 'AF', 'name' => 'Khaki Jabbar', 'active' => 1, 'slug' => 'khaki-jabbar'],
            ['id' => 44575, 'region_id' => 781246, 'country_code' => 'AF', 'name' => 'Mir Bacha Kot', 'active' => 1, 'slug' => 'mir-bacha-kot'],
            ['id' => 44576, 'region_id' => 781246, 'country_code' => 'AF', 'name' => 'Musayi', 'active' => 1, 'slug' => 'musayi'],
            ['id' => 44577, 'region_id' => 781246, 'country_code' => 'AF', 'name' => 'Paghman', 'active' => 1, 'slug' => 'paghman'],
            ['id' => 44578, 'region_id' => 781246, 'country_code' => 'AF', 'name' => 'Qarabagh', 'active' => 1, 'slug' => 'qarabagh'],
            ['id' => 44579, 'region_id' => 781246, 'country_code' => 'AF', 'name' => 'Shakardara', 'active' => 1, 'slug' => 'shakardara'],
            ['id' => 44580, 'region_id' => 781246, 'country_code' => 'AF', 'name' => 'Surobi', 'active' => 1, 'slug' => 'surobi'],
            ['id' => 44581, 'region_id' => 781261, 'country_code' => 'AF', 'name' => 'Alasay', 'active' => 1, 'slug' => 'alasay'],
            ['id' => 44582, 'region_id' => 781261, 'country_code' => 'AF', 'name' => 'Koh Band', 'active' => 1, 'slug' => 'koh-band'],
            ['id' => 44583, 'region_id' => 781261, 'country_code' => 'AF', 'name' => 'Kohistan', 'active' => 1, 'slug' => 'kohistan'],
            ['id' => 44584, 'region_id' => 781261, 'country_code' => 'AF', 'name' => 'Mahmud Raqi', 'active' => 1, 'slug' => 'mahmud-raqi'],
            ['id' => 44585, 'region_id' => 781261, 'country_code' => 'AF', 'name' => 'Nijrab', 'active' => 1, 'slug' => 'nijrab'],
            ['id' => 44586, 'region_id' => 781261, 'country_code' => 'AF', 'name' => 'Tagab', 'active' => 1, 'slug' => 'tagab'],
            ['id' => 44587, 'region_id' => 781268, 'country_code' => 'AF', 'name' => 'Asadabad', 'active' => 1, 'slug' => 'asadabad'],
            ['id' => 44588, 'region_id' => 781268, 'country_code' => 'AF', 'name' => 'Marawara', 'active' => 1, 'slug' => 'marawara'],
            ['id' => 44589, 'region_id' => 781268, 'country_code' => 'AF', 'name' => 'Bar Kunar', 'active' => 1, 'slug' => 'bar-kunar'],
            ['id' => 44590, 'region_id' => 781268, 'country_code' => 'AF', 'name' => 'Dangam', 'active' => 1, 'slug' => 'dangam'],
            ['id' => 44591, 'region_id' => 781268, 'country_code' => 'AF', 'name' => 'Nari', 'active' => 1, 'slug' => 'nari'],
            ['id' => 44592, 'region_id' => 781268, 'country_code' => 'AF', 'name' => 'Ghaziabad', 'active' => 1, 'slug' => 'ghaziabad'],
            ['id' => 44593, 'region_id' => 781268, 'country_code' => 'AF', 'name' => 'Shaygal Wa Shiltan', 'active' => 1, 'slug' => 'shaygal-wa-shiltan'],
            ['id' => 44594, 'region_id' => 781268, 'country_code' => 'AF', 'name' => 'Wata Pur', 'active' => 1, 'slug' => 'wata-pur'],
            ['id' => 44595, 'region_id' => 781268, 'country_code' => 'AF', 'name' => 'Chapa Dara', 'active' => 1, 'slug' => 'chapa-dara'],
            ['id' => 44596, 'region_id' => 781268, 'country_code' => 'AF', 'name' => 'Dara-i-pech', 'active' => 1, 'slug' => 'dara-i-pech'],
            ['id' => 44597, 'region_id' => 781268, 'country_code' => 'AF', 'name' => 'Narang', 'active' => 1, 'slug' => 'narang'],
            ['id' => 44598, 'region_id' => 781268, 'country_code' => 'AF', 'name' => 'Chawkay', 'active' => 1, 'slug' => 'chawkay'],
            ['id' => 44599, 'region_id' => 781268, 'country_code' => 'AF', 'name' => 'Nurgal', 'active' => 1, 'slug' => 'nurgal'],
            ['id' => 44600, 'region_id' => 781268, 'country_code' => 'AF', 'name' => 'Khas Kunar', 'active' => 1, 'slug' => 'khas-kunar'],
            ['id' => 44601, 'region_id' => 781268, 'country_code' => 'AF', 'name' => 'Sirkanay', 'active' => 1, 'slug' => 'sirkanay'],
            ['id' => 44602, 'region_id' => 781284, 'country_code' => 'AF', 'name' => 'Alingar', 'active' => 1, 'slug' => 'alingar'],
            ['id' => 44603, 'region_id' => 781284, 'country_code' => 'AF', 'name' => 'Alishing', 'active' => 1, 'slug' => 'alishing'],
            ['id' => 44604, 'region_id' => 781284, 'country_code' => 'AF', 'name' => 'Dawlat Shah', 'active' => 1, 'slug' => 'dawlat-shah'],
            ['id' => 44605, 'region_id' => 781284, 'country_code' => 'AF', 'name' => 'Mihtarlam', 'active' => 1, 'slug' => 'mihtarlam'],
            ['id' => 44606, 'region_id' => 781284, 'country_code' => 'AF', 'name' => 'Qarghayi', 'active' => 1, 'slug' => 'qarghayi'],
            ['id' => 44607, 'region_id' => 781290, 'country_code' => 'AF', 'name' => 'Baraki Barak', 'active' => 1, 'slug' => 'baraki-barak'],
            ['id' => 44608, 'region_id' => 781290, 'country_code' => 'AF', 'name' => 'Charkh', 'active' => 1, 'slug' => 'charkh'],
            ['id' => 44609, 'region_id' => 781290, 'country_code' => 'AF', 'name' => 'Khushi', 'active' => 1, 'slug' => 'khushi'],
            ['id' => 44610, 'region_id' => 781290, 'country_code' => 'AF', 'name' => 'Mohamad Agha', 'active' => 1, 'slug' => 'mohamad-agha'],
            ['id' => 44611, 'region_id' => 781290, 'country_code' => 'AF', 'name' => 'Kharwar', 'active' => 1, 'slug' => 'kharwar'],
            ['id' => 44612, 'region_id' => 781290, 'country_code' => 'AF', 'name' => 'Azra', 'active' => 1, 'slug' => 'azra'],
            ['id' => 44613, 'region_id' => 781290, 'country_code' => 'AF', 'name' => 'Pul-i-alam', 'active' => 1, 'slug' => 'pul-i-alam'],
            ['id' => 44614, 'region_id' => 781298, 'country_code' => 'AF', 'name' => 'Achin', 'active' => 1, 'slug' => 'achin'],
            ['id' => 44615, 'region_id' => 781298, 'country_code' => 'AF', 'name' => 'Bati Kot', 'active' => 1, 'slug' => 'bati-kot'],
            ['id' => 44616, 'region_id' => 781298, 'country_code' => 'AF', 'name' => 'Bihsud', 'active' => 1, 'slug' => 'bihsud'],
            ['id' => 44617, 'region_id' => 781298, 'country_code' => 'AF', 'name' => 'Chaparhar', 'active' => 1, 'slug' => 'chaparhar'],
            ['id' => 44618, 'region_id' => 781298, 'country_code' => 'AF', 'name' => 'Dara-i-nur', 'active' => 1, 'slug' => 'dara-i-nur'],
            ['id' => 44619, 'region_id' => 781298, 'country_code' => 'AF', 'name' => 'Dih Bala', 'active' => 1, 'slug' => 'dih-bala'],
            ['id' => 44620, 'region_id' => 781298, 'country_code' => 'AF', 'name' => 'Dur Baba', 'active' => 1, 'slug' => 'dur-baba'],
            ['id' => 44621, 'region_id' => 781298, 'country_code' => 'AF', 'name' => 'Goshta', 'active' => 1, 'slug' => 'goshta'],
            ['id' => 44622, 'region_id' => 781298, 'country_code' => 'AF', 'name' => 'Hisarak', 'active' => 1, 'slug' => 'hisarak'],
            ['id' => 44623, 'region_id' => 781298, 'country_code' => 'AF', 'name' => 'Jalalabad', 'active' => 1, 'slug' => 'jalalabad'],
            ['id' => 44624, 'region_id' => 781298, 'country_code' => 'AF', 'name' => 'Kama', 'active' => 1, 'slug' => 'kama'],
            ['id' => 44625, 'region_id' => 781298, 'country_code' => 'AF', 'name' => 'Khogyani', 'active' => 1, 'slug' => 'khogyani'],
            ['id' => 44626, 'region_id' => 781298, 'country_code' => 'AF', 'name' => 'Kot', 'active' => 1, 'slug' => 'kot'],
            ['id' => 44627, 'region_id' => 781298, 'country_code' => 'AF', 'name' => 'Kuz Kunar', 'active' => 1, 'slug' => 'kuz-kunar'],
            ['id' => 44628, 'region_id' => 781298, 'country_code' => 'AF', 'name' => 'Lal Pur', 'active' => 1, 'slug' => 'lal-pur'],
            ['id' => 44629, 'region_id' => 781298, 'country_code' => 'AF', 'name' => 'Muhmand Dara', 'active' => 1, 'slug' => 'muhmand-dara'],
            ['id' => 44630, 'region_id' => 781298, 'country_code' => 'AF', 'name' => 'Nazyan', 'active' => 1, 'slug' => 'nazyan'],
            ['id' => 44631, 'region_id' => 781298, 'country_code' => 'AF', 'name' => 'Pachir Wa Agam', 'active' => 1, 'slug' => 'pachir-wa-agam'],
            ['id' => 44632, 'region_id' => 781298, 'country_code' => 'AF', 'name' => 'Rodat', 'active' => 1, 'slug' => 'rodat'],
            ['id' => 44633, 'region_id' => 781298, 'country_code' => 'AF', 'name' => 'Sherzad', 'active' => 1, 'slug' => 'sherzad'],
            ['id' => 44634, 'region_id' => 781298, 'country_code' => 'AF', 'name' => 'Shinwar', 'active' => 1, 'slug' => 'shinwar'],
            ['id' => 44635, 'region_id' => 781298, 'country_code' => 'AF', 'name' => 'Surkh Rod', 'active' => 1, 'slug' => 'surkh-rod'],
            ['id' => 44636, 'region_id' => 781321, 'country_code' => 'AF', 'name' => 'Chahar Burjak', 'active' => 1, 'slug' => 'chahar-burjak'],
            ['id' => 44637, 'region_id' => 781321, 'country_code' => 'AF', 'name' => 'Chakhansur', 'active' => 1, 'slug' => 'chakhansur'],
            ['id' => 44638, 'region_id' => 781321, 'country_code' => 'AF', 'name' => 'Kang', 'active' => 1, 'slug' => 'kang'],
            ['id' => 44639, 'region_id' => 781321, 'country_code' => 'AF', 'name' => 'Khash Rod', 'active' => 1, 'slug' => 'khash-rod'],
            ['id' => 44640, 'region_id' => 781321, 'country_code' => 'AF', 'name' => 'Zaranj', 'active' => 1, 'slug' => 'zaranj'],
            ['id' => 44641, 'region_id' => 781327, 'country_code' => 'AF', 'name' => 'Bargi Matal', 'active' => 1, 'slug' => 'bargi-matal'],
            ['id' => 44642, 'region_id' => 781327, 'country_code' => 'AF', 'name' => 'Kamdesh', 'active' => 1, 'slug' => 'kamdesh'],
            ['id' => 44643, 'region_id' => 781327, 'country_code' => 'AF', 'name' => 'Mandol', 'active' => 1, 'slug' => 'mandol'],
            ['id' => 44644, 'region_id' => 781327, 'country_code' => 'AF', 'name' => 'Nuristan', 'active' => 1, 'slug' => 'nuristan'],
            ['id' => 44645, 'region_id' => 781327, 'country_code' => 'AF', 'name' => 'Wama', 'active' => 1, 'slug' => 'wama'],
            ['id' => 44646, 'region_id' => 781327, 'country_code' => 'AF', 'name' => 'Waygal', 'active' => 1, 'slug' => 'waygal'],
            ['id' => 44647, 'region_id' => 781334, 'country_code' => 'AF', 'name' => 'Barmal', 'active' => 1, 'slug' => 'barmal'],
            ['id' => 44648, 'region_id' => 781334, 'country_code' => 'AF', 'name' => 'Dila', 'active' => 1, 'slug' => 'dila'],
            ['id' => 44649, 'region_id' => 781334, 'country_code' => 'AF', 'name' => 'Gayan', 'active' => 1, 'slug' => 'gayan'],
            ['id' => 44650, 'region_id' => 781334, 'country_code' => 'AF', 'name' => 'Gomal', 'active' => 1, 'slug' => 'gomal'],
            ['id' => 44651, 'region_id' => 781334, 'country_code' => 'AF', 'name' => 'Mata Khan', 'active' => 1, 'slug' => 'mata-khan'],
            ['id' => 44652, 'region_id' => 781334, 'country_code' => 'AF', 'name' => 'Nika (distrito)', 'active' => 1, 'slug' => 'nika-distrito'],
            ['id' => 44653, 'region_id' => 781334, 'country_code' => 'AF', 'name' => 'Omna', 'active' => 1, 'slug' => 'omna'],
            ['id' => 44654, 'region_id' => 781334, 'country_code' => 'AF', 'name' => 'Sar Hawza', 'active' => 1, 'slug' => 'sar-hawza'],
            ['id' => 44655, 'region_id' => 781334, 'country_code' => 'AF', 'name' => 'Sarobi', 'active' => 1, 'slug' => 'sarobi'],
            ['id' => 44656, 'region_id' => 781334, 'country_code' => 'AF', 'name' => 'Sharan', 'active' => 1, 'slug' => 'sharan'],
            ['id' => 44657, 'region_id' => 781334, 'country_code' => 'AF', 'name' => 'Urgun', 'active' => 1, 'slug' => 'urgun'],
            ['id' => 44658, 'region_id' => 781334, 'country_code' => 'AF', 'name' => 'Waza Khwa', 'active' => 1, 'slug' => 'waza-khwa'],
            ['id' => 44659, 'region_id' => 781334, 'country_code' => 'AF', 'name' => 'Wor Mamay', 'active' => 1, 'slug' => 'wor-mamay'],
            ['id' => 44660, 'region_id' => 781334, 'country_code' => 'AF', 'name' => 'Zarghun Shahr', 'active' => 1, 'slug' => 'zarghun-shahr'],
            ['id' => 44661, 'region_id' => 781334, 'country_code' => 'AF', 'name' => 'Ziruk', 'active' => 1, 'slug' => 'ziruk'],
            ['id' => 44662, 'region_id' => 781350, 'country_code' => 'AF', 'name' => 'Azra', 'active' => 1, 'slug' => 'azra'],
            ['id' => 44663, 'region_id' => 781350, 'country_code' => 'AF', 'name' => 'Tsamkani', 'active' => 1, 'slug' => 'tsamkani'],
            ['id' => 44664, 'region_id' => 781350, 'country_code' => 'AF', 'name' => 'Dand Wa Patan', 'active' => 1, 'slug' => 'dand-wa-patan'],
            ['id' => 44665, 'region_id' => 781350, 'country_code' => 'AF', 'name' => 'Gardez', 'active' => 1, 'slug' => 'gardez'],
            ['id' => 44666, 'region_id' => 781350, 'country_code' => 'AF', 'name' => 'Zadran', 'active' => 1, 'slug' => 'zadran'],
            ['id' => 44667, 'region_id' => 781350, 'country_code' => 'AF', 'name' => 'Zazi', 'active' => 1, 'slug' => 'zazi'],
            ['id' => 44668, 'region_id' => 781350, 'country_code' => 'AF', 'name' => 'Jani Khel', 'active' => 1, 'slug' => 'jani-khel'],
            ['id' => 44669, 'region_id' => 781350, 'country_code' => 'AF', 'name' => 'Lazha Mangal', 'active' => 1, 'slug' => 'lazha-mangal'],
            ['id' => 44670, 'region_id' => 781350, 'country_code' => 'AF', 'name' => 'Sayed Karam', 'active' => 1, 'slug' => 'sayed-karam'],
            ['id' => 44671, 'region_id' => 781350, 'country_code' => 'AF', 'name' => 'Shamal', 'active' => 1, 'slug' => 'shamal'],
            ['id' => 44672, 'region_id' => 781350, 'country_code' => 'AF', 'name' => 'Shwak', 'active' => 1, 'slug' => 'shwak'],
            ['id' => 44673, 'region_id' => 781350, 'country_code' => 'AF', 'name' => 'Zurmat', 'active' => 1, 'slug' => 'zurmat'],
            ['id' => 44674, 'region_id' => 781350, 'country_code' => 'AF', 'name' => 'Ahmadzai', 'active' => 1, 'slug' => 'ahmadzai'],
            ['id' => 44675, 'region_id' => 781364, 'country_code' => 'AF', 'name' => 'Salang', 'active' => 1, 'slug' => 'salang'],
            ['id' => 44676, 'region_id' => 781364, 'country_code' => 'AF', 'name' => 'Panjsher', 'active' => 1, 'slug' => 'panjsher'],
            ['id' => 44677, 'region_id' => 781364, 'country_code' => 'AF', 'name' => 'Hisa-i-duwumi Panjsher', 'active' => 1, 'slug' => 'hisa-i-duwumi-panjsher'],
            ['id' => 44678, 'region_id' => 781364, 'country_code' => 'AF', 'name' => 'Hisa-i-awali Panjsher', 'active' => 1, 'slug' => 'hisa-i-awali-panjsher'],
            ['id' => 44679, 'region_id' => 781369, 'country_code' => 'AF', 'name' => 'Shekj Ali', 'active' => 1, 'slug' => 'shekj-ali'],
            ['id' => 44680, 'region_id' => 781369, 'country_code' => 'AF', 'name' => 'Surkhi Parsa', 'active' => 1, 'slug' => 'surkhi-parsa'],
            ['id' => 44681, 'region_id' => 781369, 'country_code' => 'AF', 'name' => 'Ghorband', 'active' => 1, 'slug' => 'ghorband'],
            ['id' => 44682, 'region_id' => 781369, 'country_code' => 'AF', 'name' => 'Shinwari', 'active' => 1, 'slug' => 'shinwari'],
            ['id' => 44683, 'region_id' => 781369, 'country_code' => 'AF', 'name' => 'Kohi Safi', 'active' => 1, 'slug' => 'kohi-safi'],
            ['id' => 44684, 'region_id' => 781369, 'country_code' => 'AF', 'name' => 'Bagram', 'active' => 1, 'slug' => 'bagram'],
            ['id' => 44685, 'region_id' => 781369, 'country_code' => 'AF', 'name' => 'Chaharikar', 'active' => 1, 'slug' => 'chaharikar'],
            ['id' => 44686, 'region_id' => 781369, 'country_code' => 'AF', 'name' => 'Jabalussaraj', 'active' => 1, 'slug' => 'jabalussaraj'],
            ['id' => 44687, 'region_id' => 781378, 'country_code' => 'AF', 'name' => 'Arghandab', 'active' => 1, 'slug' => 'arghandab'],
            ['id' => 44688, 'region_id' => 781378, 'country_code' => 'AF', 'name' => 'Arghistan', 'active' => 1, 'slug' => 'arghistan'],
            ['id' => 44689, 'region_id' => 781378, 'country_code' => 'AF', 'name' => 'Daman', 'active' => 1, 'slug' => 'daman'],
            ['id' => 44690, 'region_id' => 781378, 'country_code' => 'AF', 'name' => 'Ghorak', 'active' => 1, 'slug' => 'ghorak'],
            ['id' => 44691, 'region_id' => 781378, 'country_code' => 'AF', 'name' => 'Khakrez', 'active' => 1, 'slug' => 'khakrez'],
            ['id' => 44692, 'region_id' => 781378, 'country_code' => 'AF', 'name' => 'Maruf', 'active' => 1, 'slug' => 'maruf'],
            ['id' => 44693, 'region_id' => 781378, 'country_code' => 'AF', 'name' => 'Maywand', 'active' => 1, 'slug' => 'maywand'],
            ['id' => 44694, 'region_id' => 781378, 'country_code' => 'AF', 'name' => 'Panjwai', 'active' => 1, 'slug' => 'panjwai'],
            ['id' => 44695, 'region_id' => 781378, 'country_code' => 'AF', 'name' => 'Raigistan', 'active' => 1, 'slug' => 'raigistan'],
            ['id' => 44696, 'region_id' => 781378, 'country_code' => 'AF', 'name' => 'Shah Wali Kot', 'active' => 1, 'slug' => 'shah-wali-kot'],
            ['id' => 44697, 'region_id' => 781378, 'country_code' => 'AF', 'name' => 'Shorabak', 'active' => 1, 'slug' => 'shorabak'],
            ['id' => 44698, 'region_id' => 781378, 'country_code' => 'AF', 'name' => 'Spin Boldak', 'active' => 1, 'slug' => 'spin-boldak'],
            ['id' => 44699, 'region_id' => 781378, 'country_code' => 'AF', 'name' => 'Dand', 'active' => 1, 'slug' => 'dand'],
            ['id' => 44700, 'region_id' => 781378, 'country_code' => 'AF', 'name' => 'Miyannasheen', 'active' => 1, 'slug' => 'miyannasheen'],
            ['id' => 44701, 'region_id' => 781378, 'country_code' => 'AF', 'name' => 'Takhtapool', 'active' => 1, 'slug' => 'takhtapool'],
            ['id' => 44702, 'region_id' => 781378, 'country_code' => 'AF', 'name' => 'Zhari', 'active' => 1, 'slug' => 'zhari'],
            ['id' => 44703, 'region_id' => 781378, 'country_code' => 'AF', 'name' => 'Naish', 'active' => 1, 'slug' => 'naish'],
            ['id' => 44704, 'region_id' => 781396, 'country_code' => 'AF', 'name' => 'Ali Abad', 'active' => 1, 'slug' => 'ali-abad'],
            ['id' => 44705, 'region_id' => 781396, 'country_code' => 'AF', 'name' => 'Archi', 'active' => 1, 'slug' => 'archi'],
            ['id' => 44706, 'region_id' => 781396, 'country_code' => 'AF', 'name' => 'Chahar Dara', 'active' => 1, 'slug' => 'chahar-dara'],
            ['id' => 44707, 'region_id' => 781396, 'country_code' => 'AF', 'name' => 'Imam Sahib', 'active' => 1, 'slug' => 'imam-sahib'],
            ['id' => 44708, 'region_id' => 781396, 'country_code' => 'AF', 'name' => 'Khan Abad', 'active' => 1, 'slug' => 'khan-abad'],
            ['id' => 44709, 'region_id' => 781396, 'country_code' => 'AF', 'name' => 'Qunduz', 'active' => 1, 'slug' => 'qunduz'],
            ['id' => 44710, 'region_id' => 781396, 'country_code' => 'AF', 'name' => 'Qalay-i-zal', 'active' => 1, 'slug' => 'qalay-i-zal'],
            ['id' => 44711, 'region_id' => 781404, 'country_code' => 'AF', 'name' => 'Hazrati Sultan', 'active' => 1, 'slug' => 'hazrati-sultan'],
            ['id' => 44712, 'region_id' => 781404, 'country_code' => 'AF', 'name' => 'Aybak', 'active' => 1, 'slug' => 'aybak'],
            ['id' => 44713, 'region_id' => 781404, 'country_code' => 'AF', 'name' => 'Khuram Wa Sarbagh', 'active' => 1, 'slug' => 'khuram-wa-sarbagh'],
            ['id' => 44714, 'region_id' => 781404, 'country_code' => 'AF', 'name' => 'Ruyi du ab', 'active' => 1, 'slug' => 'ruyi-du-ab'],
            ['id' => 44715, 'region_id' => 781404, 'country_code' => 'AF', 'name' => 'Dara-i- Suf', 'active' => 1, 'slug' => 'dara-i-suf'],
            ['id' => 44716, 'region_id' => 781410, 'country_code' => 'AF', 'name' => 'Sayyad', 'active' => 1, 'slug' => 'sayyad'],
            ['id' => 44717, 'region_id' => 781410, 'country_code' => 'AF', 'name' => 'Sari Pul', 'active' => 1, 'slug' => 'sari-pul'],
            ['id' => 44718, 'region_id' => 781410, 'country_code' => 'AF', 'name' => 'Sazma Qala', 'active' => 1, 'slug' => 'sazma-qala'],
            ['id' => 44719, 'region_id' => 781410, 'country_code' => 'AF', 'name' => 'Sangcharak', 'active' => 1, 'slug' => 'sangcharak'],
            ['id' => 44720, 'region_id' => 781410, 'country_code' => 'AF', 'name' => 'Kohistanat', 'active' => 1, 'slug' => 'kohistanat'],
            ['id' => 44721, 'region_id' => 781410, 'country_code' => 'AF', 'name' => 'Balkhab', 'active' => 1, 'slug' => 'balkhab'],
            ['id' => 44722, 'region_id' => 781417, 'country_code' => 'AF', 'name' => 'Darqad', 'active' => 1, 'slug' => 'darqad'],
            ['id' => 44723, 'region_id' => 781417, 'country_code' => 'AF', 'name' => 'Chah ab', 'active' => 1, 'slug' => 'chah-ab'],
            ['id' => 44724, 'region_id' => 781417, 'country_code' => 'AF', 'name' => 'Yangi Qala', 'active' => 1, 'slug' => 'yangi-qala'],
            ['id' => 44725, 'region_id' => 781417, 'country_code' => 'AF', 'name' => 'Rustaq', 'active' => 1, 'slug' => 'rustaq'],
            ['id' => 44726, 'region_id' => 781417, 'country_code' => 'AF', 'name' => 'Khwaja Ghar', 'active' => 1, 'slug' => 'khwaja-ghar'],
            ['id' => 44727, 'region_id' => 781417, 'country_code' => 'AF', 'name' => 'Kalafgan', 'active' => 1, 'slug' => 'kalafgan'],
            ['id' => 44728, 'region_id' => 781417, 'country_code' => 'AF', 'name' => 'Taluqan', 'active' => 1, 'slug' => 'taluqan'],
            ['id' => 44729, 'region_id' => 781417, 'country_code' => 'AF', 'name' => 'Bangi', 'active' => 1, 'slug' => 'bangi'],
            ['id' => 44730, 'region_id' => 781417, 'country_code' => 'AF', 'name' => 'Farkhar', 'active' => 1, 'slug' => 'farkhar'],
            ['id' => 44731, 'region_id' => 781417, 'country_code' => 'AF', 'name' => 'Chal', 'active' => 1, 'slug' => 'chal'],
            ['id' => 44732, 'region_id' => 781417, 'country_code' => 'AF', 'name' => 'Ishkamish', 'active' => 1, 'slug' => 'ishkamish'],
            ['id' => 44733, 'region_id' => 781429, 'country_code' => 'AF', 'name' => 'Chora', 'active' => 1, 'slug' => 'chora'],
            ['id' => 44734, 'region_id' => 781429, 'country_code' => 'AF', 'name' => 'Dihrawud', 'active' => 1, 'slug' => 'dihrawud'],
            ['id' => 44735, 'region_id' => 781429, 'country_code' => 'AF', 'name' => 'Gizab', 'active' => 1, 'slug' => 'gizab'],
            ['id' => 44736, 'region_id' => 781429, 'country_code' => 'AF', 'name' => 'Khas Uruzgan', 'active' => 1, 'slug' => 'khas-uruzgan'],
            ['id' => 44737, 'region_id' => 781429, 'country_code' => 'AF', 'name' => 'Nesh', 'active' => 1, 'slug' => 'nesh'],
            ['id' => 44738, 'region_id' => 781429, 'country_code' => 'AF', 'name' => 'Shahidi Hassas', 'active' => 1, 'slug' => 'shahidi-hassas'],
            ['id' => 44739, 'region_id' => 781429, 'country_code' => 'AF', 'name' => 'Tirin Kot', 'active' => 1, 'slug' => 'tirin-kot'],
            ['id' => 44740, 'region_id' => 781437, 'country_code' => 'AF', 'name' => 'Maydan Shahr', 'active' => 1, 'slug' => 'maydan-shahr'],
            ['id' => 44741, 'region_id' => 781437, 'country_code' => 'AF', 'name' => 'Jalrez', 'active' => 1, 'slug' => 'jalrez'],
            ['id' => 44742, 'region_id' => 781437, 'country_code' => 'AF', 'name' => 'Hisa-i- Awali Bihsud', 'active' => 1, 'slug' => 'hisa-i-awali-bihsud'],
            ['id' => 44743, 'region_id' => 781437, 'country_code' => 'AF', 'name' => 'Markazi Bihsud', 'active' => 1, 'slug' => 'markazi-bihsud'],
            ['id' => 44744, 'region_id' => 781437, 'country_code' => 'AF', 'name' => 'Day Mirdad', 'active' => 1, 'slug' => 'day-mirdad'],
            ['id' => 44745, 'region_id' => 781437, 'country_code' => 'AF', 'name' => 'Chaki Wardak', 'active' => 1, 'slug' => 'chaki-wardak'],
            ['id' => 44746, 'region_id' => 781437, 'country_code' => 'AF', 'name' => 'Saydabad', 'active' => 1, 'slug' => 'saydabad'],
            ['id' => 44747, 'region_id' => 781437, 'country_code' => 'AF', 'name' => 'Nirkh', 'active' => 1, 'slug' => 'nirkh'],
            ['id' => 44748, 'region_id' => 781437, 'country_code' => 'AF', 'name' => 'Jaghatu', 'active' => 1, 'slug' => 'jaghatu'],
            ['id' => 44749, 'region_id' => 781447, 'country_code' => 'AF', 'name' => 'Arghandab', 'active' => 1, 'slug' => 'arghandab'],
            ['id' => 44750, 'region_id' => 781447, 'country_code' => 'AF', 'name' => 'Atghar', 'active' => 1, 'slug' => 'atghar'],
            ['id' => 44751, 'region_id' => 781447, 'country_code' => 'AF', 'name' => 'Daychopan', 'active' => 1, 'slug' => 'daychopan'],
            ['id' => 44752, 'region_id' => 781447, 'country_code' => 'AF', 'name' => 'Mizan', 'active' => 1, 'slug' => 'mizan'],
            ['id' => 44753, 'region_id' => 781447, 'country_code' => 'AF', 'name' => 'Qalat-i-ghilzai', 'active' => 1, 'slug' => 'qalat-i-ghilzai'],
            ['id' => 44754, 'region_id' => 781447, 'country_code' => 'AF', 'name' => 'Shahjoy', 'active' => 1, 'slug' => 'shahjoy'],
            ['id' => 44755, 'region_id' => 781447, 'country_code' => 'AF', 'name' => 'Shamulzayi', 'active' => 1, 'slug' => 'shamulzayi'],
            ['id' => 44756, 'region_id' => 781447, 'country_code' => 'AF', 'name' => 'Shinkay', 'active' => 1, 'slug' => 'shinkay'],
            ['id' => 44757, 'region_id' => 781447, 'country_code' => 'AF', 'name' => 'Tarnak Wa Jaldak', 'active' => 1, 'slug' => 'tarnak-wa-jaldak']
    	];
    }
}
