<?php

namespace Gerardojbaez\GeoData\Seeders;

use Illuminate\Database\Seeder;
use Gerardojbaez\GeoData\Models\Country;
use Gerardojbaez\GeoData\Models\Region;
use Gerardojbaez\GeoData\Models\City;

class ChileSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Country::create($this->country());
        Region::insert($this->regions());

        if ($this->cities() > 4000)
        {
            foreach (array_chunk($this->cities(), 3500) as $chunk)
                City::insert($chunk);
        }
        else
        {
            City::insert($this->cities());
        }
    }

        /**
     * Get country.
     *
     * @return array
     */
    public function country()
    {
    	return ['code' => 'CL', 'name' => 'Chile', 'slug' => 'chile'];
    }

    /**
     * Get country regions.
     *
     * @return array
     */
    public function regions()
    {
    	return [
            ['id' => 783071, 'country_code' => 'CL', 'name' => 'Parinacota', 'active' => 1, 'slug' => 'parinacota'],
            ['id' => 783072, 'country_code' => 'CL', 'name' => 'Arica', 'active' => 1, 'slug' => 'arica'],
            ['id' => 783073, 'country_code' => 'CL', 'name' => 'Tamarugal', 'active' => 1, 'slug' => 'tamarugal'],
            ['id' => 783074, 'country_code' => 'CL', 'name' => 'Iquique', 'active' => 1, 'slug' => 'iquique'],
            ['id' => 783075, 'country_code' => 'CL', 'name' => 'Antofagasta', 'active' => 1, 'slug' => 'antofagasta'],
            ['id' => 783076, 'country_code' => 'CL', 'name' => 'Chañaral', 'active' => 1, 'slug' => 'chanaral'],
            ['id' => 783077, 'country_code' => 'CL', 'name' => 'Copiapó', 'active' => 1, 'slug' => 'copiapo'],
            ['id' => 783078, 'country_code' => 'CL', 'name' => 'Huasco', 'active' => 1, 'slug' => 'huasco'],
            ['id' => 783079, 'country_code' => 'CL', 'name' => 'Elqui', 'active' => 1, 'slug' => 'elqui'],
            ['id' => 783080, 'country_code' => 'CL', 'name' => 'Limarí', 'active' => 1, 'slug' => 'limari'],
            ['id' => 783081, 'country_code' => 'CL', 'name' => 'Choapa', 'active' => 1, 'slug' => 'choapa'],
            ['id' => 783082, 'country_code' => 'CL', 'name' => 'Petorca', 'active' => 1, 'slug' => 'petorca'],
            ['id' => 783083, 'country_code' => 'CL', 'name' => 'Los Andes', 'active' => 1, 'slug' => 'los-andes'],
            ['id' => 783084, 'country_code' => 'CL', 'name' => 'San Felipe de Aconcagua', 'active' => 1, 'slug' => 'san-felipe-de-aconcagua'],
            ['id' => 783085, 'country_code' => 'CL', 'name' => 'Quillota', 'active' => 1, 'slug' => 'quillota'],
            ['id' => 783086, 'country_code' => 'CL', 'name' => 'Valparaíso', 'active' => 1, 'slug' => 'valparaiso'],
            ['id' => 783087, 'country_code' => 'CL', 'name' => 'Marga Marga', 'active' => 1, 'slug' => 'marga-marga'],
            ['id' => 783088, 'country_code' => 'CL', 'name' => 'San Antonio', 'active' => 1, 'slug' => 'san-antonio'],
            ['id' => 783089, 'country_code' => 'CL', 'name' => 'Isla de Pascua', 'active' => 1, 'slug' => 'isla-de-pascua'],
            ['id' => 783090, 'country_code' => 'CL', 'name' => 'Cachapoal', 'active' => 1, 'slug' => 'cachapoal'],
            ['id' => 783091, 'country_code' => 'CL', 'name' => 'Curicó', 'active' => 1, 'slug' => 'curico'],
            ['id' => 783092, 'country_code' => 'CL', 'name' => 'Talca', 'active' => 1, 'slug' => 'talca'],
            ['id' => 783093, 'country_code' => 'CL', 'name' => 'Linares', 'active' => 1, 'slug' => 'linares'],
            ['id' => 783094, 'country_code' => 'CL', 'name' => 'Cauquenes', 'active' => 1, 'slug' => 'cauquenes'],
            ['id' => 783095, 'country_code' => 'CL', 'name' => 'Ñuble', 'active' => 1, 'slug' => 'nuble'],
            ['id' => 783096, 'country_code' => 'CL', 'name' => 'Biobío', 'active' => 1, 'slug' => 'biobio'],
            ['id' => 783097, 'country_code' => 'CL', 'name' => 'Concepción', 'active' => 1, 'slug' => 'concepcion'],
            ['id' => 783098, 'country_code' => 'CL', 'name' => 'Arauco', 'active' => 1, 'slug' => 'arauco'],
            ['id' => 783099, 'country_code' => 'CL', 'name' => 'Malleco', 'active' => 1, 'slug' => 'malleco'],
            ['id' => 783100, 'country_code' => 'CL', 'name' => 'Cautín', 'active' => 1, 'slug' => 'cautin'],
            ['id' => 783101, 'country_code' => 'CL', 'name' => 'Valdivia', 'active' => 1, 'slug' => 'valdivia'],
            ['id' => 783102, 'country_code' => 'CL', 'name' => 'Ranco', 'active' => 1, 'slug' => 'ranco'],
            ['id' => 783103, 'country_code' => 'CL', 'name' => 'Osorno', 'active' => 1, 'slug' => 'osorno'],
            ['id' => 783104, 'country_code' => 'CL', 'name' => 'Puerto Montt', 'active' => 1, 'slug' => 'puerto-montt'],
            ['id' => 783105, 'country_code' => 'CL', 'name' => 'Chiloé', 'active' => 1, 'slug' => 'chiloe'],
            ['id' => 783106, 'country_code' => 'CL', 'name' => 'Palena', 'active' => 1, 'slug' => 'palena'],
            ['id' => 783107, 'country_code' => 'CL', 'name' => 'Coyhaique', 'active' => 1, 'slug' => 'coyhaique'],
            ['id' => 783108, 'country_code' => 'CL', 'name' => 'Aysén', 'active' => 1, 'slug' => 'aysen'],
            ['id' => 783109, 'country_code' => 'CL', 'name' => 'General Carrera', 'active' => 1, 'slug' => 'general-carrera'],
            ['id' => 783110, 'country_code' => 'CL', 'name' => 'Capitán Prat', 'active' => 1, 'slug' => 'capitan-prat'],
            ['id' => 783111, 'country_code' => 'CL', 'name' => 'Última Esperanza', 'active' => 1, 'slug' => 'ultima-esperanza'],
            ['id' => 783112, 'country_code' => 'CL', 'name' => 'Magallanes', 'active' => 1, 'slug' => 'magallanes'],
            ['id' => 783113, 'country_code' => 'CL', 'name' => 'Tierra del Fuego', 'active' => 1, 'slug' => 'tierra-del-fuego'],
            ['id' => 783114, 'country_code' => 'CL', 'name' => 'Antártica Chilena', 'active' => 1, 'slug' => 'antartica-chilena'],
            ['id' => 783115, 'country_code' => 'CL', 'name' => 'Chacabuco', 'active' => 1, 'slug' => 'chacabuco'],
            ['id' => 783116, 'country_code' => 'CL', 'name' => 'Cordillera', 'active' => 1, 'slug' => 'cordillera'],
            ['id' => 783117, 'country_code' => 'CL', 'name' => 'Maipo', 'active' => 1, 'slug' => 'maipo'],
            ['id' => 783118, 'country_code' => 'CL', 'name' => 'Talagante', 'active' => 1, 'slug' => 'talagante'],
            ['id' => 783119, 'country_code' => 'CL', 'name' => 'Melipilla', 'active' => 1, 'slug' => 'melipilla'],
            ['id' => 783120, 'country_code' => 'CL', 'name' => 'Santiago', 'active' => 1, 'slug' => 'santiago']
    	];
    }

    /**
     * Get region cities.
     *
     * @return array
     */
    public function cities()
    {
    	return [
            ['id' => 498540, 'region_id' => 783071, 'country_code' => 'CL', 'name' => 'General Lagos', 'active' => 1, 'slug' => 'general-lagos'],
            ['id' => 498541, 'region_id' => 783071, 'country_code' => 'CL', 'name' => 'Putre', 'active' => 1, 'slug' => 'putre'],
            ['id' => 498543, 'region_id' => 783072, 'country_code' => 'CL', 'name' => 'Arica', 'active' => 1, 'slug' => 'arica'],
            ['id' => 498542, 'region_id' => 783072, 'country_code' => 'CL', 'name' => 'Camarones', 'active' => 1, 'slug' => 'camarones'],
            ['id' => 498544, 'region_id' => 783073, 'country_code' => 'CL', 'name' => 'Camiña', 'active' => 1, 'slug' => 'camina'],
            ['id' => 498545, 'region_id' => 783073, 'country_code' => 'CL', 'name' => 'Colchane', 'active' => 1, 'slug' => 'colchane'],
            ['id' => 498546, 'region_id' => 783073, 'country_code' => 'CL', 'name' => 'Huara', 'active' => 1, 'slug' => 'huara'],
            ['id' => 498547, 'region_id' => 783073, 'country_code' => 'CL', 'name' => 'Pica', 'active' => 1, 'slug' => 'pica'],
            ['id' => 498548, 'region_id' => 783073, 'country_code' => 'CL', 'name' => 'Pozo Almonte', 'active' => 1, 'slug' => 'pozo-almonte'],
            ['id' => 498549, 'region_id' => 783074, 'country_code' => 'CL', 'name' => 'Alto Hospicio', 'active' => 1, 'slug' => 'alto-hospicio'],
            ['id' => 498550, 'region_id' => 783074, 'country_code' => 'CL', 'name' => 'Iquique', 'active' => 1, 'slug' => 'iquique'],
            ['id' => 498551, 'region_id' => 783075, 'country_code' => 'CL', 'name' => 'María Elena', 'active' => 1, 'slug' => 'maria-elena'],
            ['id' => 498552, 'region_id' => 783075, 'country_code' => 'CL', 'name' => 'Mejillones', 'active' => 1, 'slug' => 'mejillones'],
            ['id' => 498553, 'region_id' => 783075, 'country_code' => 'CL', 'name' => 'Ollagüe', 'active' => 1, 'slug' => 'ollague'],
            ['id' => 498554, 'region_id' => 783075, 'country_code' => 'CL', 'name' => 'Sierra Gorda', 'active' => 1, 'slug' => 'sierra-gorda'],
            ['id' => 498555, 'region_id' => 783075, 'country_code' => 'CL', 'name' => 'San Pedro de Atacama', 'active' => 1, 'slug' => 'san-pedro-de-atacama'],
            ['id' => 498556, 'region_id' => 783075, 'country_code' => 'CL', 'name' => 'Taltal', 'active' => 1, 'slug' => 'taltal'],
            ['id' => 498557, 'region_id' => 783075, 'country_code' => 'CL', 'name' => 'Tocopilla', 'active' => 1, 'slug' => 'tocopilla'],
            ['id' => 498558, 'region_id' => 783075, 'country_code' => 'CL', 'name' => 'Calama', 'active' => 1, 'slug' => 'calama'],
            ['id' => 498559, 'region_id' => 783075, 'country_code' => 'CL', 'name' => 'Antofagasta', 'active' => 1, 'slug' => 'antofagasta'],
            ['id' => 498560, 'region_id' => 783076, 'country_code' => 'CL', 'name' => 'Chañaral', 'active' => 1, 'slug' => 'chanaral'],
            ['id' => 498561, 'region_id' => 783076, 'country_code' => 'CL', 'name' => 'Diego de Almagro', 'active' => 1, 'slug' => 'diego-de-almagro'],
            ['id' => 498562, 'region_id' => 783077, 'country_code' => 'CL', 'name' => 'Caldera', 'active' => 1, 'slug' => 'caldera'],
            ['id' => 498563, 'region_id' => 783077, 'country_code' => 'CL', 'name' => 'Tierra Amarilla', 'active' => 1, 'slug' => 'tierra-amarilla'],
            ['id' => 498564, 'region_id' => 783077, 'country_code' => 'CL', 'name' => 'Copiapó', 'active' => 1, 'slug' => 'copiapo'],
            ['id' => 498565, 'region_id' => 783078, 'country_code' => 'CL', 'name' => 'Alto del Carmen', 'active' => 1, 'slug' => 'alto-del-carmen'],
            ['id' => 498566, 'region_id' => 783078, 'country_code' => 'CL', 'name' => 'Freirina', 'active' => 1, 'slug' => 'freirina'],
            ['id' => 498567, 'region_id' => 783078, 'country_code' => 'CL', 'name' => 'Huasco', 'active' => 1, 'slug' => 'huasco'],
            ['id' => 498568, 'region_id' => 783078, 'country_code' => 'CL', 'name' => 'Vallenar', 'active' => 1, 'slug' => 'vallenar'],
            ['id' => 498569, 'region_id' => 783079, 'country_code' => 'CL', 'name' => 'Andacollo', 'active' => 1, 'slug' => 'andacollo'],
            ['id' => 498570, 'region_id' => 783079, 'country_code' => 'CL', 'name' => 'La Higuera', 'active' => 1, 'slug' => 'la-higuera'],
            ['id' => 498571, 'region_id' => 783079, 'country_code' => 'CL', 'name' => 'Paihuano', 'active' => 1, 'slug' => 'paihuano'],
            ['id' => 498572, 'region_id' => 783079, 'country_code' => 'CL', 'name' => 'Vicuña', 'active' => 1, 'slug' => 'vicuna'],
            ['id' => 498573, 'region_id' => 783079, 'country_code' => 'CL', 'name' => 'La Serena', 'active' => 1, 'slug' => 'la-serena'],
            ['id' => 498574, 'region_id' => 783079, 'country_code' => 'CL', 'name' => 'Coquimbo', 'active' => 1, 'slug' => 'coquimbo'],
            ['id' => 498575, 'region_id' => 783080, 'country_code' => 'CL', 'name' => 'Combarbalá', 'active' => 1, 'slug' => 'combarbala'],
            ['id' => 498576, 'region_id' => 783080, 'country_code' => 'CL', 'name' => 'Punitaqui', 'active' => 1, 'slug' => 'punitaqui'],
            ['id' => 498577, 'region_id' => 783080, 'country_code' => 'CL', 'name' => 'Río Hurtado', 'active' => 1, 'slug' => 'rio-hurtado'],
            ['id' => 498578, 'region_id' => 783080, 'country_code' => 'CL', 'name' => 'Monte Patria', 'active' => 1, 'slug' => 'monte-patria'],
            ['id' => 498579, 'region_id' => 783080, 'country_code' => 'CL', 'name' => 'Ovalle', 'active' => 1, 'slug' => 'ovalle'],
            ['id' => 498580, 'region_id' => 783081, 'country_code' => 'CL', 'name' => 'Canela', 'active' => 1, 'slug' => 'canela'],
            ['id' => 498581, 'region_id' => 783081, 'country_code' => 'CL', 'name' => 'Los Vilos', 'active' => 1, 'slug' => 'los-vilos'],
            ['id' => 498582, 'region_id' => 783081, 'country_code' => 'CL', 'name' => 'Salamanca', 'active' => 1, 'slug' => 'salamanca'],
            ['id' => 498583, 'region_id' => 783081, 'country_code' => 'CL', 'name' => 'Illapel', 'active' => 1, 'slug' => 'illapel'],
            ['id' => 498584, 'region_id' => 783082, 'country_code' => 'CL', 'name' => 'Cabildo', 'active' => 1, 'slug' => 'cabildo'],
            ['id' => 498585, 'region_id' => 783082, 'country_code' => 'CL', 'name' => 'La Ligua', 'active' => 1, 'slug' => 'la-ligua'],
            ['id' => 498586, 'region_id' => 783082, 'country_code' => 'CL', 'name' => 'Papudo', 'active' => 1, 'slug' => 'papudo'],
            ['id' => 498587, 'region_id' => 783082, 'country_code' => 'CL', 'name' => 'Petorca', 'active' => 1, 'slug' => 'petorca'],
            ['id' => 498588, 'region_id' => 783082, 'country_code' => 'CL', 'name' => 'Zapallar', 'active' => 1, 'slug' => 'zapallar'],
            ['id' => 498589, 'region_id' => 783083, 'country_code' => 'CL', 'name' => 'Calle Larga', 'active' => 1, 'slug' => 'calle-larga'],
            ['id' => 498590, 'region_id' => 783083, 'country_code' => 'CL', 'name' => 'Rinconada', 'active' => 1, 'slug' => 'rinconada'],
            ['id' => 498591, 'region_id' => 783083, 'country_code' => 'CL', 'name' => 'San Esteban', 'active' => 1, 'slug' => 'san-esteban'],
            ['id' => 498592, 'region_id' => 783083, 'country_code' => 'CL', 'name' => 'Los Andes', 'active' => 1, 'slug' => 'los-andes'],
            ['id' => 498593, 'region_id' => 783084, 'country_code' => 'CL', 'name' => 'Catemu', 'active' => 1, 'slug' => 'catemu'],
            ['id' => 498594, 'region_id' => 783084, 'country_code' => 'CL', 'name' => 'Panquehue', 'active' => 1, 'slug' => 'panquehue'],
            ['id' => 498595, 'region_id' => 783084, 'country_code' => 'CL', 'name' => 'Putaendo', 'active' => 1, 'slug' => 'putaendo'],
            ['id' => 498596, 'region_id' => 783084, 'country_code' => 'CL', 'name' => 'Santa María', 'active' => 1, 'slug' => 'santa-maria'],
            ['id' => 498597, 'region_id' => 783084, 'country_code' => 'CL', 'name' => 'Llaillay', 'active' => 1, 'slug' => 'llaillay'],
            ['id' => 498598, 'region_id' => 783084, 'country_code' => 'CL', 'name' => 'San Felipe', 'active' => 1, 'slug' => 'san-felipe'],
            ['id' => 498599, 'region_id' => 783085, 'country_code' => 'CL', 'name' => 'Hijuelas', 'active' => 1, 'slug' => 'hijuelas'],
            ['id' => 498600, 'region_id' => 783085, 'country_code' => 'CL', 'name' => 'La Calera', 'active' => 1, 'slug' => 'la-calera'],
            ['id' => 498601, 'region_id' => 783085, 'country_code' => 'CL', 'name' => 'La Cruz', 'active' => 1, 'slug' => 'la-cruz'],
            ['id' => 498602, 'region_id' => 783085, 'country_code' => 'CL', 'name' => 'Nogales', 'active' => 1, 'slug' => 'nogales'],
            ['id' => 498603, 'region_id' => 783085, 'country_code' => 'CL', 'name' => 'Quillota', 'active' => 1, 'slug' => 'quillota'],
            ['id' => 498604, 'region_id' => 783086, 'country_code' => 'CL', 'name' => 'Casablanca', 'active' => 1, 'slug' => 'casablanca'],
            ['id' => 498605, 'region_id' => 783086, 'country_code' => 'CL', 'name' => 'Concón', 'active' => 1, 'slug' => 'concon'],
            ['id' => 498606, 'region_id' => 783086, 'country_code' => 'CL', 'name' => 'Juan Fernández', 'active' => 1, 'slug' => 'juan-fernandez'],
            ['id' => 498607, 'region_id' => 783086, 'country_code' => 'CL', 'name' => 'Puchuncaví', 'active' => 1, 'slug' => 'puchuncavi'],
            ['id' => 498608, 'region_id' => 783086, 'country_code' => 'CL', 'name' => 'Quintero', 'active' => 1, 'slug' => 'quintero'],
            ['id' => 498609, 'region_id' => 783086, 'country_code' => 'CL', 'name' => 'Valparaíso', 'active' => 1, 'slug' => 'valparaiso'],
            ['id' => 498610, 'region_id' => 783086, 'country_code' => 'CL', 'name' => 'Viña del Mar', 'active' => 1, 'slug' => 'vina-del-mar'],
            ['id' => 498611, 'region_id' => 783087, 'country_code' => 'CL', 'name' => 'Olmué', 'active' => 1, 'slug' => 'olmue'],
            ['id' => 498612, 'region_id' => 783087, 'country_code' => 'CL', 'name' => 'Limache', 'active' => 1, 'slug' => 'limache'],
            ['id' => 498613, 'region_id' => 783087, 'country_code' => 'CL', 'name' => 'Villa Alemana', 'active' => 1, 'slug' => 'villa-alemana'],
            ['id' => 498614, 'region_id' => 783087, 'country_code' => 'CL', 'name' => 'Quilpué', 'active' => 1, 'slug' => 'quilpue'],
            ['id' => 498615, 'region_id' => 783088, 'country_code' => 'CL', 'name' => 'Algarrobo', 'active' => 1, 'slug' => 'algarrobo'],
            ['id' => 498616, 'region_id' => 783088, 'country_code' => 'CL', 'name' => 'Cartagena', 'active' => 1, 'slug' => 'cartagena'],
            ['id' => 498617, 'region_id' => 783088, 'country_code' => 'CL', 'name' => 'El Quisco', 'active' => 1, 'slug' => 'el-quisco'],
            ['id' => 498618, 'region_id' => 783088, 'country_code' => 'CL', 'name' => 'El Tabo', 'active' => 1, 'slug' => 'el-tabo'],
            ['id' => 498619, 'region_id' => 783088, 'country_code' => 'CL', 'name' => 'San Antonio', 'active' => 1, 'slug' => 'san-antonio'],
            ['id' => 498620, 'region_id' => 783088, 'country_code' => 'CL', 'name' => 'Santo Domingo', 'active' => 1, 'slug' => 'santo-domingo'],
            ['id' => 498621, 'region_id' => 783089, 'country_code' => 'CL', 'name' => 'Isla de Pascua', 'active' => 1, 'slug' => 'isla-de-pascua'],
            ['id' => 498622, 'region_id' => 783090, 'country_code' => 'CL', 'name' => 'Codegua', 'active' => 1, 'slug' => 'codegua'],
            ['id' => 498623, 'region_id' => 783090, 'country_code' => 'CL', 'name' => 'Coltauco', 'active' => 1, 'slug' => 'coltauco'],
            ['id' => 498624, 'region_id' => 783090, 'country_code' => 'CL', 'name' => 'Coínco', 'active' => 1, 'slug' => 'coinco'],
            ['id' => 498625, 'region_id' => 783090, 'country_code' => 'CL', 'name' => 'Doñihue', 'active' => 1, 'slug' => 'donihue'],
            ['id' => 498626, 'region_id' => 783090, 'country_code' => 'CL', 'name' => 'Graneros', 'active' => 1, 'slug' => 'graneros'],
            ['id' => 498627, 'region_id' => 783090, 'country_code' => 'CL', 'name' => 'Las Cabras', 'active' => 1, 'slug' => 'las-cabras'],
            ['id' => 498628, 'region_id' => 783090, 'country_code' => 'CL', 'name' => 'Malloa', 'active' => 1, 'slug' => 'malloa'],
            ['id' => 498629, 'region_id' => 783090, 'country_code' => 'CL', 'name' => 'Mostazal', 'active' => 1, 'slug' => 'mostazal'],
            ['id' => 498630, 'region_id' => 783090, 'country_code' => 'CL', 'name' => 'Olivar', 'active' => 1, 'slug' => 'olivar'],
            ['id' => 498631, 'region_id' => 783090, 'country_code' => 'CL', 'name' => 'Peumo', 'active' => 1, 'slug' => 'peumo'],
            ['id' => 498632, 'region_id' => 783090, 'country_code' => 'CL', 'name' => 'Pichidegua', 'active' => 1, 'slug' => 'pichidegua'],
            ['id' => 498633, 'region_id' => 783090, 'country_code' => 'CL', 'name' => 'Quinta de Tilcoco', 'active' => 1, 'slug' => 'quinta-de-tilcoco'],
            ['id' => 498634, 'region_id' => 783090, 'country_code' => 'CL', 'name' => 'Requínoa', 'active' => 1, 'slug' => 'requinoa'],
            ['id' => 498635, 'region_id' => 783090, 'country_code' => 'CL', 'name' => 'San Vicente de Tagua Tagua', 'active' => 1, 'slug' => 'san-vicente-de-tagua-tagua'],
            ['id' => 498636, 'region_id' => 783090, 'country_code' => 'CL', 'name' => 'Machalí', 'active' => 1, 'slug' => 'machali'],
            ['id' => 498637, 'region_id' => 783090, 'country_code' => 'CL', 'name' => 'Rengo', 'active' => 1, 'slug' => 'rengo'],
            ['id' => 498638, 'region_id' => 783090, 'country_code' => 'CL', 'name' => 'Rancagua', 'active' => 1, 'slug' => 'rancagua'],
            ['id' => 498639, 'region_id' => 783091, 'country_code' => 'CL', 'name' => 'Hualañé', 'active' => 1, 'slug' => 'hualane'],
            ['id' => 498640, 'region_id' => 783091, 'country_code' => 'CL', 'name' => 'Licantén', 'active' => 1, 'slug' => 'licanten'],
            ['id' => 498641, 'region_id' => 783091, 'country_code' => 'CL', 'name' => 'Rauco', 'active' => 1, 'slug' => 'rauco'],
            ['id' => 498642, 'region_id' => 783091, 'country_code' => 'CL', 'name' => 'Romeral', 'active' => 1, 'slug' => 'romeral'],
            ['id' => 498643, 'region_id' => 783091, 'country_code' => 'CL', 'name' => 'Sagrada Familia', 'active' => 1, 'slug' => 'sagrada-familia'],
            ['id' => 498644, 'region_id' => 783091, 'country_code' => 'CL', 'name' => 'Vichuquén', 'active' => 1, 'slug' => 'vichuquen'],
            ['id' => 498645, 'region_id' => 783091, 'country_code' => 'CL', 'name' => 'Teno', 'active' => 1, 'slug' => 'teno'],
            ['id' => 498646, 'region_id' => 783091, 'country_code' => 'CL', 'name' => 'Molina', 'active' => 1, 'slug' => 'molina'],
            ['id' => 498647, 'region_id' => 783091, 'country_code' => 'CL', 'name' => 'Curicó', 'active' => 1, 'slug' => 'curico'],
            ['id' => 498648, 'region_id' => 783092, 'country_code' => 'CL', 'name' => 'Curepto', 'active' => 1, 'slug' => 'curepto'],
            ['id' => 498649, 'region_id' => 783092, 'country_code' => 'CL', 'name' => 'Empedrado', 'active' => 1, 'slug' => 'empedrado'],
            ['id' => 498650, 'region_id' => 783092, 'country_code' => 'CL', 'name' => 'Maule', 'active' => 1, 'slug' => 'maule'],
            ['id' => 498651, 'region_id' => 783092, 'country_code' => 'CL', 'name' => 'Pelarco', 'active' => 1, 'slug' => 'pelarco'],
            ['id' => 498652, 'region_id' => 783092, 'country_code' => 'CL', 'name' => 'Pencahue', 'active' => 1, 'slug' => 'pencahue'],
            ['id' => 498653, 'region_id' => 783092, 'country_code' => 'CL', 'name' => 'Río Claro', 'active' => 1, 'slug' => 'rio-claro'],
            ['id' => 498654, 'region_id' => 783092, 'country_code' => 'CL', 'name' => 'San Rafael', 'active' => 1, 'slug' => 'san-rafael'],
            ['id' => 498655, 'region_id' => 783092, 'country_code' => 'CL', 'name' => 'Talca', 'active' => 1, 'slug' => 'talca'],
            ['id' => 498656, 'region_id' => 783092, 'country_code' => 'CL', 'name' => 'San Clemente', 'active' => 1, 'slug' => 'san-clemente'],
            ['id' => 498657, 'region_id' => 783092, 'country_code' => 'CL', 'name' => 'Constitución', 'active' => 1, 'slug' => 'constitucion'],
            ['id' => 498658, 'region_id' => 783093, 'country_code' => 'CL', 'name' => 'Colbún', 'active' => 1, 'slug' => 'colbun'],
            ['id' => 498659, 'region_id' => 783093, 'country_code' => 'CL', 'name' => 'Parral', 'active' => 1, 'slug' => 'parral'],
            ['id' => 498660, 'region_id' => 783093, 'country_code' => 'CL', 'name' => 'Retiro', 'active' => 1, 'slug' => 'retiro'],
            ['id' => 498661, 'region_id' => 783093, 'country_code' => 'CL', 'name' => 'San Javier de Loncomilla', 'active' => 1, 'slug' => 'san-javier-de-loncomilla'],
            ['id' => 498662, 'region_id' => 783093, 'country_code' => 'CL', 'name' => 'Villa Alegre', 'active' => 1, 'slug' => 'villa-alegre'],
            ['id' => 498663, 'region_id' => 783093, 'country_code' => 'CL', 'name' => 'Yerbas Buenas', 'active' => 1, 'slug' => 'yerbas-buenas'],
            ['id' => 498664, 'region_id' => 783093, 'country_code' => 'CL', 'name' => 'Longaví', 'active' => 1, 'slug' => 'longavi'],
            ['id' => 498665, 'region_id' => 783093, 'country_code' => 'CL', 'name' => 'Linares', 'active' => 1, 'slug' => 'linares'],
            ['id' => 498666, 'region_id' => 783094, 'country_code' => 'CL', 'name' => 'Chanco', 'active' => 1, 'slug' => 'chanco'],
            ['id' => 498667, 'region_id' => 783094, 'country_code' => 'CL', 'name' => 'Pelluhue', 'active' => 1, 'slug' => 'pelluhue'],
            ['id' => 498668, 'region_id' => 783094, 'country_code' => 'CL', 'name' => 'Cauquenes', 'active' => 1, 'slug' => 'cauquenes'],
            ['id' => 498669, 'region_id' => 783095, 'country_code' => 'CL', 'name' => 'Chillán Viejo', 'active' => 1, 'slug' => 'chillan-viejo'],
            ['id' => 498670, 'region_id' => 783095, 'country_code' => 'CL', 'name' => 'Cobquecura', 'active' => 1, 'slug' => 'cobquecura'],
            ['id' => 498671, 'region_id' => 783095, 'country_code' => 'CL', 'name' => 'Coelemu', 'active' => 1, 'slug' => 'coelemu'],
            ['id' => 498672, 'region_id' => 783095, 'country_code' => 'CL', 'name' => 'Coihueco', 'active' => 1, 'slug' => 'coihueco'],
            ['id' => 498673, 'region_id' => 783095, 'country_code' => 'CL', 'name' => 'El Carmen', 'active' => 1, 'slug' => 'el-carmen'],
            ['id' => 498674, 'region_id' => 783095, 'country_code' => 'CL', 'name' => 'Ninhue', 'active' => 1, 'slug' => 'ninhue'],
            ['id' => 498675, 'region_id' => 783095, 'country_code' => 'CL', 'name' => 'Pemuco', 'active' => 1, 'slug' => 'pemuco'],
            ['id' => 498676, 'region_id' => 783095, 'country_code' => 'CL', 'name' => 'Pinto', 'active' => 1, 'slug' => 'pinto'],
            ['id' => 498677, 'region_id' => 783095, 'country_code' => 'CL', 'name' => 'Portezuelo', 'active' => 1, 'slug' => 'portezuelo'],
            ['id' => 498678, 'region_id' => 783095, 'country_code' => 'CL', 'name' => 'Quillón', 'active' => 1, 'slug' => 'quillon'],
            ['id' => 498679, 'region_id' => 783095, 'country_code' => 'CL', 'name' => 'Quirihue', 'active' => 1, 'slug' => 'quirihue'],
            ['id' => 498680, 'region_id' => 783095, 'country_code' => 'CL', 'name' => 'Ránquil', 'active' => 1, 'slug' => 'ranquil'],
            ['id' => 498681, 'region_id' => 783095, 'country_code' => 'CL', 'name' => 'San Carlos', 'active' => 1, 'slug' => 'san-carlos'],
            ['id' => 498682, 'region_id' => 783095, 'country_code' => 'CL', 'name' => 'San Fabián', 'active' => 1, 'slug' => 'san-fabian'],
            ['id' => 498683, 'region_id' => 783095, 'country_code' => 'CL', 'name' => 'San Ignacio', 'active' => 1, 'slug' => 'san-ignacio'],
            ['id' => 498684, 'region_id' => 783095, 'country_code' => 'CL', 'name' => 'San Nicolás', 'active' => 1, 'slug' => 'san-nicolas'],
            ['id' => 498685, 'region_id' => 783095, 'country_code' => 'CL', 'name' => 'Treguaco', 'active' => 1, 'slug' => 'treguaco'],
            ['id' => 498686, 'region_id' => 783095, 'country_code' => 'CL', 'name' => 'Yungay', 'active' => 1, 'slug' => 'yungay'],
            ['id' => 498687, 'region_id' => 783095, 'country_code' => 'CL', 'name' => 'Ñiquén', 'active' => 1, 'slug' => 'niquen'],
            ['id' => 498688, 'region_id' => 783095, 'country_code' => 'CL', 'name' => 'Bulnes', 'active' => 1, 'slug' => 'bulnes'],
            ['id' => 498689, 'region_id' => 783095, 'country_code' => 'CL', 'name' => 'Chillán', 'active' => 1, 'slug' => 'chillan'],
            ['id' => 498690, 'region_id' => 783096, 'country_code' => 'CL', 'name' => 'Alto Biobío', 'active' => 1, 'slug' => 'alto-biobio'],
            ['id' => 498691, 'region_id' => 783096, 'country_code' => 'CL', 'name' => 'Antuco', 'active' => 1, 'slug' => 'antuco'],
            ['id' => 498692, 'region_id' => 783096, 'country_code' => 'CL', 'name' => 'Los Ángeles', 'active' => 1, 'slug' => 'los-angeles'],
            ['id' => 498693, 'region_id' => 783096, 'country_code' => 'CL', 'name' => 'Negrete', 'active' => 1, 'slug' => 'negrete'],
            ['id' => 498694, 'region_id' => 783096, 'country_code' => 'CL', 'name' => 'Quilaco', 'active' => 1, 'slug' => 'quilaco'],
            ['id' => 498695, 'region_id' => 783096, 'country_code' => 'CL', 'name' => 'Quilleco', 'active' => 1, 'slug' => 'quilleco'],
            ['id' => 498696, 'region_id' => 783096, 'country_code' => 'CL', 'name' => 'San Rosendo', 'active' => 1, 'slug' => 'san-rosendo'],
            ['id' => 498697, 'region_id' => 783096, 'country_code' => 'CL', 'name' => 'Santa Bárbara', 'active' => 1, 'slug' => 'santa-barbara'],
            ['id' => 498698, 'region_id' => 783096, 'country_code' => 'CL', 'name' => 'Tucapel', 'active' => 1, 'slug' => 'tucapel'],
            ['id' => 498699, 'region_id' => 783096, 'country_code' => 'CL', 'name' => 'Yumbel', 'active' => 1, 'slug' => 'yumbel'],
            ['id' => 498700, 'region_id' => 783096, 'country_code' => 'CL', 'name' => 'Laja', 'active' => 1, 'slug' => 'laja'],
            ['id' => 498701, 'region_id' => 783096, 'country_code' => 'CL', 'name' => 'Cabrero', 'active' => 1, 'slug' => 'cabrero'],
            ['id' => 498702, 'region_id' => 783096, 'country_code' => 'CL', 'name' => 'Nacimiento', 'active' => 1, 'slug' => 'nacimiento'],
            ['id' => 498703, 'region_id' => 783096, 'country_code' => 'CL', 'name' => 'Mulchén', 'active' => 1, 'slug' => 'mulchen'],
            ['id' => 498704, 'region_id' => 783097, 'country_code' => 'CL', 'name' => 'Coronel', 'active' => 1, 'slug' => 'coronel'],
            ['id' => 498705, 'region_id' => 783097, 'country_code' => 'CL', 'name' => 'Florida', 'active' => 1, 'slug' => 'florida'],
            ['id' => 498706, 'region_id' => 783097, 'country_code' => 'CL', 'name' => 'Hualpén', 'active' => 1, 'slug' => 'hualpen'],
            ['id' => 498707, 'region_id' => 783097, 'country_code' => 'CL', 'name' => 'Hualqui', 'active' => 1, 'slug' => 'hualqui'],
            ['id' => 498708, 'region_id' => 783097, 'country_code' => 'CL', 'name' => 'San Pedro de la Paz', 'active' => 1, 'slug' => 'san-pedro-de-la-paz'],
            ['id' => 498709, 'region_id' => 783097, 'country_code' => 'CL', 'name' => 'Santa Juana', 'active' => 1, 'slug' => 'santa-juana'],
            ['id' => 498710, 'region_id' => 783097, 'country_code' => 'CL', 'name' => 'Penco', 'active' => 1, 'slug' => 'penco'],
            ['id' => 498711, 'region_id' => 783097, 'country_code' => 'CL', 'name' => 'Tomé', 'active' => 1, 'slug' => 'tome'],
            ['id' => 498712, 'region_id' => 783097, 'country_code' => 'CL', 'name' => 'Lota', 'active' => 1, 'slug' => 'lota'],
            ['id' => 498713, 'region_id' => 783097, 'country_code' => 'CL', 'name' => 'Chiguayante', 'active' => 1, 'slug' => 'chiguayante'],
            ['id' => 498714, 'region_id' => 783097, 'country_code' => 'CL', 'name' => 'Concepción', 'active' => 1, 'slug' => 'concepcion'],
            ['id' => 498715, 'region_id' => 783097, 'country_code' => 'CL', 'name' => 'Talcahuano', 'active' => 1, 'slug' => 'talcahuano'],
            ['id' => 498716, 'region_id' => 783098, 'country_code' => 'CL', 'name' => 'Cañete', 'active' => 1, 'slug' => 'canete'],
            ['id' => 498717, 'region_id' => 783098, 'country_code' => 'CL', 'name' => 'Contulmo', 'active' => 1, 'slug' => 'contulmo'],
            ['id' => 498718, 'region_id' => 783098, 'country_code' => 'CL', 'name' => 'Los Álamos', 'active' => 1, 'slug' => 'los-alamos'],
            ['id' => 498719, 'region_id' => 783098, 'country_code' => 'CL', 'name' => 'Tirúa', 'active' => 1, 'slug' => 'tirua'],
            ['id' => 498720, 'region_id' => 783098, 'country_code' => 'CL', 'name' => 'Lebu', 'active' => 1, 'slug' => 'lebu'],
            ['id' => 498721, 'region_id' => 783098, 'country_code' => 'CL', 'name' => 'Arauco', 'active' => 1, 'slug' => 'arauco'],
            ['id' => 498722, 'region_id' => 783098, 'country_code' => 'CL', 'name' => 'Curanilahue', 'active' => 1, 'slug' => 'curanilahue'],
            ['id' => 498723, 'region_id' => 783099, 'country_code' => 'CL', 'name' => 'Curacautín', 'active' => 1, 'slug' => 'curacautin'],
            ['id' => 498724, 'region_id' => 783099, 'country_code' => 'CL', 'name' => 'Ercilla', 'active' => 1, 'slug' => 'ercilla'],
            ['id' => 498725, 'region_id' => 783099, 'country_code' => 'CL', 'name' => 'Lonquimay', 'active' => 1, 'slug' => 'lonquimay'],
            ['id' => 498726, 'region_id' => 783099, 'country_code' => 'CL', 'name' => 'Los Sauces', 'active' => 1, 'slug' => 'los-sauces'],
            ['id' => 498727, 'region_id' => 783099, 'country_code' => 'CL', 'name' => 'Lumaco', 'active' => 1, 'slug' => 'lumaco'],
            ['id' => 498728, 'region_id' => 783099, 'country_code' => 'CL', 'name' => 'Purén', 'active' => 1, 'slug' => 'puren'],
            ['id' => 498729, 'region_id' => 783099, 'country_code' => 'CL', 'name' => 'Renaico', 'active' => 1, 'slug' => 'renaico'],
            ['id' => 498730, 'region_id' => 783099, 'country_code' => 'CL', 'name' => 'Traiguén', 'active' => 1, 'slug' => 'traiguen'],
            ['id' => 498731, 'region_id' => 783099, 'country_code' => 'CL', 'name' => 'Collipulli', 'active' => 1, 'slug' => 'collipulli'],
            ['id' => 498732, 'region_id' => 783099, 'country_code' => 'CL', 'name' => 'Victoria', 'active' => 1, 'slug' => 'victoria'],
            ['id' => 498733, 'region_id' => 783099, 'country_code' => 'CL', 'name' => 'Angol', 'active' => 1, 'slug' => 'angol'],
            ['id' => 498734, 'region_id' => 783100, 'country_code' => 'CL', 'name' => 'Cholchol', 'active' => 1, 'slug' => 'cholchol'],
            ['id' => 498735, 'region_id' => 783100, 'country_code' => 'CL', 'name' => 'Cunco', 'active' => 1, 'slug' => 'cunco'],
            ['id' => 498736, 'region_id' => 783100, 'country_code' => 'CL', 'name' => 'Curarrehue', 'active' => 1, 'slug' => 'curarrehue'],
            ['id' => 498737, 'region_id' => 783100, 'country_code' => 'CL', 'name' => 'Galvarino', 'active' => 1, 'slug' => 'galvarino'],
            ['id' => 498738, 'region_id' => 783100, 'country_code' => 'CL', 'name' => 'Gorbea', 'active' => 1, 'slug' => 'gorbea'],
            ['id' => 498739, 'region_id' => 783100, 'country_code' => 'CL', 'name' => 'Melipeuco', 'active' => 1, 'slug' => 'melipeuco'],
            ['id' => 498740, 'region_id' => 783100, 'country_code' => 'CL', 'name' => 'Padre Las Casas', 'active' => 1, 'slug' => 'padre-las-casas'],
            ['id' => 498741, 'region_id' => 783100, 'country_code' => 'CL', 'name' => 'Perquenco', 'active' => 1, 'slug' => 'perquenco'],
            ['id' => 498742, 'region_id' => 783100, 'country_code' => 'CL', 'name' => 'Saavedra', 'active' => 1, 'slug' => 'saavedra'],
            ['id' => 498743, 'region_id' => 783100, 'country_code' => 'CL', 'name' => 'Temuco', 'active' => 1, 'slug' => 'temuco'],
            ['id' => 498744, 'region_id' => 783100, 'country_code' => 'CL', 'name' => 'Teodoro Schmidt', 'active' => 1, 'slug' => 'teodoro-schmidt'],
            ['id' => 498745, 'region_id' => 783100, 'country_code' => 'CL', 'name' => 'Toltén', 'active' => 1, 'slug' => 'tolten'],
            ['id' => 498746, 'region_id' => 783100, 'country_code' => 'CL', 'name' => 'Freire', 'active' => 1, 'slug' => 'freire'],
            ['id' => 498747, 'region_id' => 783100, 'country_code' => 'CL', 'name' => 'Vilcún', 'active' => 1, 'slug' => 'vilcun'],
            ['id' => 498748, 'region_id' => 783100, 'country_code' => 'CL', 'name' => 'Carahue', 'active' => 1, 'slug' => 'carahue'],
            ['id' => 498749, 'region_id' => 783100, 'country_code' => 'CL', 'name' => 'Pitrufquén', 'active' => 1, 'slug' => 'pitrufquen'],
            ['id' => 498750, 'region_id' => 783100, 'country_code' => 'CL', 'name' => 'Loncoche', 'active' => 1, 'slug' => 'loncoche'],
            ['id' => 498751, 'region_id' => 783100, 'country_code' => 'CL', 'name' => 'Nueva Imperial', 'active' => 1, 'slug' => 'nueva-imperial'],
            ['id' => 498752, 'region_id' => 783100, 'country_code' => 'CL', 'name' => 'Lautaro', 'active' => 1, 'slug' => 'lautaro'],
            ['id' => 498753, 'region_id' => 783100, 'country_code' => 'CL', 'name' => 'Pucón', 'active' => 1, 'slug' => 'pucon'],
            ['id' => 498754, 'region_id' => 783100, 'country_code' => 'CL', 'name' => 'Villarrica', 'active' => 1, 'slug' => 'villarrica'],
            ['id' => 498755, 'region_id' => 783101, 'country_code' => 'CL', 'name' => 'Lanco', 'active' => 1, 'slug' => 'lanco'],
            ['id' => 498756, 'region_id' => 783101, 'country_code' => 'CL', 'name' => 'Los Lagos', 'active' => 1, 'slug' => 'los-lagos'],
            ['id' => 498757, 'region_id' => 783101, 'country_code' => 'CL', 'name' => 'Mariquina', 'active' => 1, 'slug' => 'mariquina'],
            ['id' => 498758, 'region_id' => 783101, 'country_code' => 'CL', 'name' => 'Máfil', 'active' => 1, 'slug' => 'mafil'],
            ['id' => 498759, 'region_id' => 783101, 'country_code' => 'CL', 'name' => 'Paillaco', 'active' => 1, 'slug' => 'paillaco'],
            ['id' => 498760, 'region_id' => 783101, 'country_code' => 'CL', 'name' => 'Valdivia', 'active' => 1, 'slug' => 'valdivia'],
            ['id' => 498761, 'region_id' => 783101, 'country_code' => 'CL', 'name' => 'Corral', 'active' => 1, 'slug' => 'corral'],
            ['id' => 498762, 'region_id' => 783101, 'country_code' => 'CL', 'name' => 'Panguipulli', 'active' => 1, 'slug' => 'panguipulli'],
            ['id' => 498763, 'region_id' => 783102, 'country_code' => 'CL', 'name' => 'Futrono', 'active' => 1, 'slug' => 'futrono'],
            ['id' => 498764, 'region_id' => 783102, 'country_code' => 'CL', 'name' => 'La Unión', 'active' => 1, 'slug' => 'la-union'],
            ['id' => 498765, 'region_id' => 783102, 'country_code' => 'CL', 'name' => 'Lago Ranco', 'active' => 1, 'slug' => 'lago-ranco'],
            ['id' => 498766, 'region_id' => 783102, 'country_code' => 'CL', 'name' => 'Río Bueno', 'active' => 1, 'slug' => 'rio-bueno'],
            ['id' => 498767, 'region_id' => 783103, 'country_code' => 'CL', 'name' => 'Puerto Octay', 'active' => 1, 'slug' => 'puerto-octay'],
            ['id' => 498768, 'region_id' => 783103, 'country_code' => 'CL', 'name' => 'Puyehue', 'active' => 1, 'slug' => 'puyehue'],
            ['id' => 498769, 'region_id' => 783103, 'country_code' => 'CL', 'name' => 'Río Negro', 'active' => 1, 'slug' => 'rio-negro'],
            ['id' => 498770, 'region_id' => 783103, 'country_code' => 'CL', 'name' => 'San Juan de la Costa', 'active' => 1, 'slug' => 'san-juan-de-la-costa'],
            ['id' => 498771, 'region_id' => 783103, 'country_code' => 'CL', 'name' => 'San Pablo', 'active' => 1, 'slug' => 'san-pablo'],
            ['id' => 498772, 'region_id' => 783103, 'country_code' => 'CL', 'name' => 'Purranque', 'active' => 1, 'slug' => 'purranque'],
            ['id' => 498773, 'region_id' => 783103, 'country_code' => 'CL', 'name' => 'Osorno', 'active' => 1, 'slug' => 'osorno'],
            ['id' => 498774, 'region_id' => 783104, 'country_code' => 'CL', 'name' => 'Cochamó', 'active' => 1, 'slug' => 'cochamo'],
            ['id' => 498775, 'region_id' => 783104, 'country_code' => 'CL', 'name' => 'Fresia', 'active' => 1, 'slug' => 'fresia'],
            ['id' => 498776, 'region_id' => 783104, 'country_code' => 'CL', 'name' => 'Frutillar', 'active' => 1, 'slug' => 'frutillar'],
            ['id' => 498777, 'region_id' => 783104, 'country_code' => 'CL', 'name' => 'Llanquihue', 'active' => 1, 'slug' => 'llanquihue'],
            ['id' => 498778, 'region_id' => 783104, 'country_code' => 'CL', 'name' => 'Los Muermos', 'active' => 1, 'slug' => 'los-muermos'],
            ['id' => 498779, 'region_id' => 783104, 'country_code' => 'CL', 'name' => 'Maullín', 'active' => 1, 'slug' => 'maullin'],
            ['id' => 498780, 'region_id' => 783104, 'country_code' => 'CL', 'name' => 'Calbuco', 'active' => 1, 'slug' => 'calbuco'],
            ['id' => 498781, 'region_id' => 783104, 'country_code' => 'CL', 'name' => 'Puerto Varas', 'active' => 1, 'slug' => 'puerto-varas'],
            ['id' => 498782, 'region_id' => 783104, 'country_code' => 'CL', 'name' => 'Puerto Montt', 'active' => 1, 'slug' => 'puerto-montt'],
            ['id' => 498783, 'region_id' => 783105, 'country_code' => 'CL', 'name' => 'Curaco de Vélez', 'active' => 1, 'slug' => 'curaco-de-velez'],
            ['id' => 498784, 'region_id' => 783105, 'country_code' => 'CL', 'name' => 'Dalcahue', 'active' => 1, 'slug' => 'dalcahue'],
            ['id' => 498785, 'region_id' => 783105, 'country_code' => 'CL', 'name' => 'Puqueldón', 'active' => 1, 'slug' => 'puqueldon'],
            ['id' => 498786, 'region_id' => 783105, 'country_code' => 'CL', 'name' => 'Queilén', 'active' => 1, 'slug' => 'queilen'],
            ['id' => 498787, 'region_id' => 783105, 'country_code' => 'CL', 'name' => 'Quellón', 'active' => 1, 'slug' => 'quellon'],
            ['id' => 498788, 'region_id' => 783105, 'country_code' => 'CL', 'name' => 'Quemchi', 'active' => 1, 'slug' => 'quemchi'],
            ['id' => 498789, 'region_id' => 783105, 'country_code' => 'CL', 'name' => 'Quinchao', 'active' => 1, 'slug' => 'quinchao'],
            ['id' => 498790, 'region_id' => 783105, 'country_code' => 'CL', 'name' => 'Chonchi', 'active' => 1, 'slug' => 'chonchi'],
            ['id' => 498791, 'region_id' => 783105, 'country_code' => 'CL', 'name' => 'Ancud', 'active' => 1, 'slug' => 'ancud'],
            ['id' => 498792, 'region_id' => 783105, 'country_code' => 'CL', 'name' => 'Castro', 'active' => 1, 'slug' => 'castro'],
            ['id' => 498793, 'region_id' => 783106, 'country_code' => 'CL', 'name' => 'Hualaihué', 'active' => 1, 'slug' => 'hualaihue'],
            ['id' => 498794, 'region_id' => 783106, 'country_code' => 'CL', 'name' => 'Palena', 'active' => 1, 'slug' => 'palena'],
            ['id' => 498795, 'region_id' => 783106, 'country_code' => 'CL', 'name' => 'Futaleufú', 'active' => 1, 'slug' => 'futaleufu'],
            ['id' => 498796, 'region_id' => 783106, 'country_code' => 'CL', 'name' => 'Chaitén', 'active' => 1, 'slug' => 'chaiten'],
            ['id' => 498798, 'region_id' => 783107, 'country_code' => 'CL', 'name' => 'Coyhaique', 'active' => 1, 'slug' => 'coyhaique'],
            ['id' => 498797, 'region_id' => 783107, 'country_code' => 'CL', 'name' => 'Lago Verde', 'active' => 1, 'slug' => 'lago-verde'],
            ['id' => 498799, 'region_id' => 783108, 'country_code' => 'CL', 'name' => 'Cisnes', 'active' => 1, 'slug' => 'cisnes'],
            ['id' => 498800, 'region_id' => 783108, 'country_code' => 'CL', 'name' => 'Guaitecas', 'active' => 1, 'slug' => 'guaitecas'],
            ['id' => 498801, 'region_id' => 783108, 'country_code' => 'CL', 'name' => 'Aysén', 'active' => 1, 'slug' => 'aysen'],
            ['id' => 498803, 'region_id' => 783109, 'country_code' => 'CL', 'name' => 'Chile Chico', 'active' => 1, 'slug' => 'chile-chico'],
            ['id' => 498802, 'region_id' => 783109, 'country_code' => 'CL', 'name' => 'Río Ibáñez', 'active' => 1, 'slug' => 'rio-ibanez'],
            ['id' => 498804, 'region_id' => 783110, 'country_code' => 'CL', 'name' => 'O\'Higgins', 'active' => 1, 'slug' => 'ohiggins'],
            ['id' => 498805, 'region_id' => 783110, 'country_code' => 'CL', 'name' => 'Tortel', 'active' => 1, 'slug' => 'tortel'],
            ['id' => 498806, 'region_id' => 783110, 'country_code' => 'CL', 'name' => 'Cochrane', 'active' => 1, 'slug' => 'cochrane'],
            ['id' => 498808, 'region_id' => 783111, 'country_code' => 'CL', 'name' => 'Natales', 'active' => 1, 'slug' => 'natales'],
            ['id' => 498807, 'region_id' => 783111, 'country_code' => 'CL', 'name' => 'Torres del Paine', 'active' => 1, 'slug' => 'torres-del-paine'],
            ['id' => 498809, 'region_id' => 783112, 'country_code' => 'CL', 'name' => 'Laguna Blanca', 'active' => 1, 'slug' => 'laguna-blanca'],
            ['id' => 498810, 'region_id' => 783112, 'country_code' => 'CL', 'name' => 'Río Verde', 'active' => 1, 'slug' => 'rio-verde'],
            ['id' => 498811, 'region_id' => 783112, 'country_code' => 'CL', 'name' => 'San Gregorio', 'active' => 1, 'slug' => 'san-gregorio'],
            ['id' => 498812, 'region_id' => 783112, 'country_code' => 'CL', 'name' => 'Punta Arenas', 'active' => 1, 'slug' => 'punta-arenas'],
            ['id' => 498813, 'region_id' => 783113, 'country_code' => 'CL', 'name' => 'Porvenir', 'active' => 1, 'slug' => 'porvenir'],
            ['id' => 498814, 'region_id' => 783113, 'country_code' => 'CL', 'name' => 'Primavera', 'active' => 1, 'slug' => 'primavera'],
            ['id' => 498815, 'region_id' => 783113, 'country_code' => 'CL', 'name' => 'Timaukel', 'active' => 1, 'slug' => 'timaukel'],
            ['id' => 498816, 'region_id' => 783114, 'country_code' => 'CL', 'name' => 'Antártica', 'active' => 1, 'slug' => 'antartica'],
            ['id' => 498817, 'region_id' => 783114, 'country_code' => 'CL', 'name' => 'Cabo de Hornos', 'active' => 1, 'slug' => 'cabo-de-hornos'],
            ['id' => 498818, 'region_id' => 783115, 'country_code' => 'CL', 'name' => 'Colina', 'active' => 1, 'slug' => 'colina'],
            ['id' => 498819, 'region_id' => 783115, 'country_code' => 'CL', 'name' => 'Tiltil', 'active' => 1, 'slug' => 'tiltil'],
            ['id' => 498820, 'region_id' => 783115, 'country_code' => 'CL', 'name' => 'Lampa', 'active' => 1, 'slug' => 'lampa'],
            ['id' => 498821, 'region_id' => 783116, 'country_code' => 'CL', 'name' => 'Pirque', 'active' => 1, 'slug' => 'pirque'],
            ['id' => 498822, 'region_id' => 783116, 'country_code' => 'CL', 'name' => 'San José de Maipo', 'active' => 1, 'slug' => 'san-jose-de-maipo'],
            ['id' => 498823, 'region_id' => 783116, 'country_code' => 'CL', 'name' => 'Puente Alto', 'active' => 1, 'slug' => 'puente-alto'],
            ['id' => 498824, 'region_id' => 783117, 'country_code' => 'CL', 'name' => 'Calera de Tango', 'active' => 1, 'slug' => 'calera-de-tango'],
            ['id' => 498825, 'region_id' => 783117, 'country_code' => 'CL', 'name' => 'San Bernardo', 'active' => 1, 'slug' => 'san-bernardo'],
            ['id' => 498826, 'region_id' => 783117, 'country_code' => 'CL', 'name' => 'Paine', 'active' => 1, 'slug' => 'paine'],
            ['id' => 498827, 'region_id' => 783117, 'country_code' => 'CL', 'name' => 'Buin', 'active' => 1, 'slug' => 'buin'],
            ['id' => 498828, 'region_id' => 783118, 'country_code' => 'CL', 'name' => 'Isla de Maipo', 'active' => 1, 'slug' => 'isla-de-maipo'],
            ['id' => 498829, 'region_id' => 783118, 'country_code' => 'CL', 'name' => 'Padre Hurtado', 'active' => 1, 'slug' => 'padre-hurtado'],
            ['id' => 498830, 'region_id' => 783118, 'country_code' => 'CL', 'name' => 'Peñaflor', 'active' => 1, 'slug' => 'penaflor'],
            ['id' => 498831, 'region_id' => 783118, 'country_code' => 'CL', 'name' => 'El Monte', 'active' => 1, 'slug' => 'el-monte'],
            ['id' => 498832, 'region_id' => 783118, 'country_code' => 'CL', 'name' => 'Talagante', 'active' => 1, 'slug' => 'talagante'],
            ['id' => 498833, 'region_id' => 783119, 'country_code' => 'CL', 'name' => 'Alhué', 'active' => 1, 'slug' => 'alhue'],
            ['id' => 498834, 'region_id' => 783119, 'country_code' => 'CL', 'name' => 'Curacaví', 'active' => 1, 'slug' => 'curacavi'],
            ['id' => 498835, 'region_id' => 783119, 'country_code' => 'CL', 'name' => 'María Pinto', 'active' => 1, 'slug' => 'maria-pinto'],
            ['id' => 498836, 'region_id' => 783119, 'country_code' => 'CL', 'name' => 'San Pedro', 'active' => 1, 'slug' => 'san-pedro'],
            ['id' => 498837, 'region_id' => 783119, 'country_code' => 'CL', 'name' => 'Melipilla', 'active' => 1, 'slug' => 'melipilla'],
            ['id' => 498838, 'region_id' => 783120, 'country_code' => 'CL', 'name' => 'Cerrillos', 'active' => 1, 'slug' => 'cerrillos'],
            ['id' => 498839, 'region_id' => 783120, 'country_code' => 'CL', 'name' => 'Cerro Navia', 'active' => 1, 'slug' => 'cerro-navia'],
            ['id' => 498840, 'region_id' => 783120, 'country_code' => 'CL', 'name' => 'Conchalí', 'active' => 1, 'slug' => 'conchali'],
            ['id' => 498841, 'region_id' => 783120, 'country_code' => 'CL', 'name' => 'El Bosque', 'active' => 1, 'slug' => 'el-bosque'],
            ['id' => 498842, 'region_id' => 783120, 'country_code' => 'CL', 'name' => 'Estación Central', 'active' => 1, 'slug' => 'estacion-central'],
            ['id' => 498843, 'region_id' => 783120, 'country_code' => 'CL', 'name' => 'Huechuraba', 'active' => 1, 'slug' => 'huechuraba'],
            ['id' => 498844, 'region_id' => 783120, 'country_code' => 'CL', 'name' => 'Independencia', 'active' => 1, 'slug' => 'independencia'],
            ['id' => 498845, 'region_id' => 783120, 'country_code' => 'CL', 'name' => 'La Cisterna', 'active' => 1, 'slug' => 'la-cisterna'],
            ['id' => 498846, 'region_id' => 783120, 'country_code' => 'CL', 'name' => 'La Florida', 'active' => 1, 'slug' => 'la-florida'],
            ['id' => 498847, 'region_id' => 783120, 'country_code' => 'CL', 'name' => 'La Granja', 'active' => 1, 'slug' => 'la-granja'],
            ['id' => 498848, 'region_id' => 783120, 'country_code' => 'CL', 'name' => 'La Reina', 'active' => 1, 'slug' => 'la-reina'],
            ['id' => 498849, 'region_id' => 783120, 'country_code' => 'CL', 'name' => 'Las Condes', 'active' => 1, 'slug' => 'las-condes'],
            ['id' => 498850, 'region_id' => 783120, 'country_code' => 'CL', 'name' => 'Lo Barnechea', 'active' => 1, 'slug' => 'lo-barnechea'],
            ['id' => 498851, 'region_id' => 783120, 'country_code' => 'CL', 'name' => 'Lo Espejo', 'active' => 1, 'slug' => 'lo-espejo'],
            ['id' => 498852, 'region_id' => 783120, 'country_code' => 'CL', 'name' => 'Macul', 'active' => 1, 'slug' => 'macul'],
            ['id' => 498853, 'region_id' => 783120, 'country_code' => 'CL', 'name' => 'Maipú', 'active' => 1, 'slug' => 'maipu'],
            ['id' => 498854, 'region_id' => 783120, 'country_code' => 'CL', 'name' => 'Pedro Aguirre Cerda', 'active' => 1, 'slug' => 'pedro-aguirre-cerda'],
            ['id' => 498855, 'region_id' => 783120, 'country_code' => 'CL', 'name' => 'Peñalolén', 'active' => 1, 'slug' => 'penalolen'],
            ['id' => 498856, 'region_id' => 783120, 'country_code' => 'CL', 'name' => 'Providencia', 'active' => 1, 'slug' => 'providencia'],
            ['id' => 498857, 'region_id' => 783120, 'country_code' => 'CL', 'name' => 'Pudahuel', 'active' => 1, 'slug' => 'pudahuel'],
            ['id' => 498858, 'region_id' => 783120, 'country_code' => 'CL', 'name' => 'Quilicura', 'active' => 1, 'slug' => 'quilicura'],
            ['id' => 498859, 'region_id' => 783120, 'country_code' => 'CL', 'name' => 'Quinta Normal', 'active' => 1, 'slug' => 'quinta-normal'],
            ['id' => 498860, 'region_id' => 783120, 'country_code' => 'CL', 'name' => 'Recoleta', 'active' => 1, 'slug' => 'recoleta'],
            ['id' => 498861, 'region_id' => 783120, 'country_code' => 'CL', 'name' => 'Renca', 'active' => 1, 'slug' => 'renca'],
            ['id' => 498862, 'region_id' => 783120, 'country_code' => 'CL', 'name' => 'San Joaquín', 'active' => 1, 'slug' => 'san-joaquin'],
            ['id' => 498863, 'region_id' => 783120, 'country_code' => 'CL', 'name' => 'San Miguel', 'active' => 1, 'slug' => 'san-miguel'],
            ['id' => 498864, 'region_id' => 783120, 'country_code' => 'CL', 'name' => 'San Ramón', 'active' => 1, 'slug' => 'san-ramon'],
            ['id' => 498865, 'region_id' => 783120, 'country_code' => 'CL', 'name' => 'Vitacura', 'active' => 1, 'slug' => 'vitacura'],
            ['id' => 498866, 'region_id' => 783120, 'country_code' => 'CL', 'name' => 'Ñuñoa', 'active' => 1, 'slug' => 'nunoa'],
            ['id' => 498867, 'region_id' => 783120, 'country_code' => 'CL', 'name' => 'Lo Prado', 'active' => 1, 'slug' => 'lo-prado'],
            ['id' => 498868, 'region_id' => 783120, 'country_code' => 'CL', 'name' => 'La Pintana', 'active' => 1, 'slug' => 'la-pintana'],
            ['id' => 498869, 'region_id' => 783120, 'country_code' => 'CL', 'name' => 'Santiago', 'active' => 1, 'slug' => 'santiago']
    	];
    }
}
