<?php

namespace Gerardojbaez\GeoData\Seeders;

use Illuminate\Database\Seeder;
use Gerardojbaez\GeoData\Models\Country;
use Gerardojbaez\GeoData\Models\Region;
use Gerardojbaez\GeoData\Models\City;

class DominicanRepublicSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Country::create($this->country());
        Region::insert($this->regions());

        if ($this->cities() > 4000)
        {
            foreach (array_chunk($this->cities(), 3500) as $chunk)
                City::insert($chunk);
        }
        else
        {
            City::insert($this->cities());
        }
    }

        /**
     * Get country.
     *
     * @return array
     */
    public function country()
    {
    	return ['code' => 'DO', 'name' => 'Dominican Republic', 'slug' => 'dominican-republic'];
    }

    /**
     * Get country regions.
     *
     * @return array
     */
    public function regions()
    {
    	return [
            ['id' => 863, 'country_code' => 'DO', 'name' => 'Santo Domingo', 'active' => 1, 'slug' => 'santo-domingo'],
            ['id' => 709847, 'country_code' => 'DO', 'name' => 'Azua', 'active' => 1, 'slug' => 'azua'],
            ['id' => 709872, 'country_code' => 'DO', 'name' => 'Bahoruco', 'active' => 1, 'slug' => 'bahoruco'],
            ['id' => 709884, 'country_code' => 'DO', 'name' => 'Barahona', 'active' => 1, 'slug' => 'barahona'],
            ['id' => 709904, 'country_code' => 'DO', 'name' => 'Dajabón', 'active' => 1, 'slug' => 'dajabon'],
            ['id' => 709911, 'country_code' => 'DO', 'name' => 'Distrito Nacional', 'active' => 1, 'slug' => 'distrito-nacional'],
            ['id' => 709913, 'country_code' => 'DO', 'name' => 'Duarte', 'active' => 1, 'slug' => 'duarte'],
            ['id' => 709929, 'country_code' => 'DO', 'name' => 'Elías Piña', 'active' => 1, 'slug' => 'elias-pina'],
            ['id' => 709939, 'country_code' => 'DO', 'name' => 'El Seibo', 'active' => 1, 'slug' => 'el-seibo'],
            ['id' => 709944, 'country_code' => 'DO', 'name' => 'Espaillat', 'active' => 1, 'slug' => 'espaillat'],
            ['id' => 709960, 'country_code' => 'DO', 'name' => 'Hato Mayor', 'active' => 1, 'slug' => 'hato-mayor'],
            ['id' => 709968, 'country_code' => 'DO', 'name' => 'Independencia', 'active' => 1, 'slug' => 'independencia'],
            ['id' => 709978, 'country_code' => 'DO', 'name' => 'La Altagracia', 'active' => 1, 'slug' => 'la-altagracia'],
            ['id' => 709987, 'country_code' => 'DO', 'name' => 'La Romana', 'active' => 1, 'slug' => 'la-romana'],
            ['id' => 709992, 'country_code' => 'DO', 'name' => 'La Vega', 'active' => 1, 'slug' => 'la-vega'],
            ['id' => 710004, 'country_code' => 'DO', 'name' => 'María Trinidad Sánchez', 'active' => 1, 'slug' => 'maria-trinidad-sanchez'],
            ['id' => 710015, 'country_code' => 'DO', 'name' => 'Monseñor Nouel', 'active' => 1, 'slug' => 'monsenor-nouel'],
            ['id' => 710024, 'country_code' => 'DO', 'name' => 'Monte Cristi', 'active' => 1, 'slug' => 'monte-cristi'],
            ['id' => 710036, 'country_code' => 'DO', 'name' => 'Monte Plata', 'active' => 1, 'slug' => 'monte-plata'],
            ['id' => 710049, 'country_code' => 'DO', 'name' => 'Peravia', 'active' => 1, 'slug' => 'peravia'],
            ['id' => 710065, 'country_code' => 'DO', 'name' => 'Pedernales', 'active' => 1, 'slug' => 'pedernales'],
            ['id' => 710069, 'country_code' => 'DO', 'name' => 'Puerto Plata', 'active' => 1, 'slug' => 'puerto-plata'],
            ['id' => 710087, 'country_code' => 'DO', 'name' => 'Salcedo', 'active' => 1, 'slug' => 'salcedo'],
            ['id' => 710090, 'country_code' => 'DO', 'name' => 'Samaná', 'active' => 1, 'slug' => 'samana'],
            ['id' => 710097, 'country_code' => 'DO', 'name' => 'San Cristóbal', 'active' => 1, 'slug' => 'san-cristobal'],
            ['id' => 710111, 'country_code' => 'DO', 'name' => 'San José de Ocoa', 'active' => 1, 'slug' => 'san-jose-de-ocoa'],
            ['id' => 710118, 'country_code' => 'DO', 'name' => 'San Juan', 'active' => 1, 'slug' => 'san-juan'],
            ['id' => 710131, 'country_code' => 'DO', 'name' => 'San Pedro de Macorís', 'active' => 1, 'slug' => 'san-pedro-de-macoris'],
            ['id' => 710141, 'country_code' => 'DO', 'name' => 'Sánchez Ramírez', 'active' => 1, 'slug' => 'sanchez-ramirez'],
            ['id' => 710150, 'country_code' => 'DO', 'name' => 'Santiago', 'active' => 1, 'slug' => 'santiago'],
            ['id' => 710171, 'country_code' => 'DO', 'name' => 'Santiago Rodríguez', 'active' => 1, 'slug' => 'santiago-rodriguez'],
            ['id' => 710188, 'country_code' => 'DO', 'name' => 'Valverde', 'active' => 1, 'slug' => 'valverde']
    	];
    }

    /**
     * Get region cities.
     *
     * @return array
     */
    public function cities()
    {
    	return [
            ['id' => 24247, 'region_id' => 863, 'country_code' => 'DO', 'name' => 'Boca Chica Informacion Gral', 'active' => 1, 'slug' => 'boca-chica-informacion-gral'],
            ['id' => 24248, 'region_id' => 863, 'country_code' => 'DO', 'name' => 'Hato Viejo', 'active' => 1, 'slug' => 'hato-viejo'],
            ['id' => 24249, 'region_id' => 863, 'country_code' => 'DO', 'name' => 'La Caleta', 'active' => 1, 'slug' => 'la-caleta'],
            ['id' => 24250, 'region_id' => 863, 'country_code' => 'DO', 'name' => 'La Victoria', 'active' => 1, 'slug' => 'la-victoria'],
            ['id' => 24251, 'region_id' => 863, 'country_code' => 'DO', 'name' => 'Los Alcarrizos', 'active' => 1, 'slug' => 'los-alcarrizos'],
            ['id' => 24252, 'region_id' => 863, 'country_code' => 'DO', 'name' => 'Pedro Brand', 'active' => 1, 'slug' => 'pedro-brand'],
            ['id' => 24253, 'region_id' => 863, 'country_code' => 'DO', 'name' => 'San Antonio de Guerra', 'active' => 1, 'slug' => 'san-antonio-de-guerra'],
            ['id' => 24254, 'region_id' => 863, 'country_code' => 'DO', 'name' => 'San Luis', 'active' => 1, 'slug' => 'san-luis'],
            ['id' => 24255, 'region_id' => 863, 'country_code' => 'DO', 'name' => 'Santo Domingo', 'active' => 1, 'slug' => 'santo-domingo'],
            ['id' => 24256, 'region_id' => 863, 'country_code' => 'DO', 'name' => 'Santo Domingo Este', 'active' => 1, 'slug' => 'santo-domingo-este'],
            ['id' => 24257, 'region_id' => 863, 'country_code' => 'DO', 'name' => 'Santo Domingo Norte', 'active' => 1, 'slug' => 'santo-domingo-norte'],
            ['id' => 24258, 'region_id' => 863, 'country_code' => 'DO', 'name' => 'Santo Domingo Oeste', 'active' => 1, 'slug' => 'santo-domingo-oeste'],
            ['id' => 23948, 'region_id' => 709847, 'country_code' => 'DO', 'name' => 'Amiama Gómez', 'active' => 1, 'slug' => 'amiama-gomez'],
            ['id' => 23949, 'region_id' => 709847, 'country_code' => 'DO', 'name' => 'Azua', 'active' => 1, 'slug' => 'azua'],
            ['id' => 23950, 'region_id' => 709847, 'country_code' => 'DO', 'name' => 'Azua de Compostela', 'active' => 1, 'slug' => 'azua-de-compostela'],
            ['id' => 23951, 'region_id' => 709847, 'country_code' => 'DO', 'name' => 'Barro Arriba', 'active' => 1, 'slug' => 'barro-arriba'],
            ['id' => 23952, 'region_id' => 709847, 'country_code' => 'DO', 'name' => 'El Rosario', 'active' => 1, 'slug' => 'el-rosario'],
            ['id' => 23953, 'region_id' => 709847, 'country_code' => 'DO', 'name' => 'Estebania', 'active' => 1, 'slug' => 'estebania'],
            ['id' => 23954, 'region_id' => 709847, 'country_code' => 'DO', 'name' => 'Guayabal', 'active' => 1, 'slug' => 'guayabal'],
            ['id' => 23955, 'region_id' => 709847, 'country_code' => 'DO', 'name' => 'La Siembra', 'active' => 1, 'slug' => 'la-siembra'],
            ['id' => 23956, 'region_id' => 709847, 'country_code' => 'DO', 'name' => 'Las Barías-la Estancia', 'active' => 1, 'slug' => 'las-barias-la-estancia'],
            ['id' => 23957, 'region_id' => 709847, 'country_code' => 'DO', 'name' => 'Las Charcas', 'active' => 1, 'slug' => 'las-charcas'],
            ['id' => 23958, 'region_id' => 709847, 'country_code' => 'DO', 'name' => 'Las Lagunas', 'active' => 1, 'slug' => 'las-lagunas'],
            ['id' => 23959, 'region_id' => 709847, 'country_code' => 'DO', 'name' => 'Las Yayas de Viajama', 'active' => 1, 'slug' => 'las-yayas-de-viajama'],
            ['id' => 23960, 'region_id' => 709847, 'country_code' => 'DO', 'name' => 'Los Jovillos', 'active' => 1, 'slug' => 'los-jovillos'],
            ['id' => 23961, 'region_id' => 709847, 'country_code' => 'DO', 'name' => 'Los Toros', 'active' => 1, 'slug' => 'los-toros'],
            ['id' => 23962, 'region_id' => 709847, 'country_code' => 'DO', 'name' => 'Padre Las Casas', 'active' => 1, 'slug' => 'padre-las-casas'],
            ['id' => 23963, 'region_id' => 709847, 'country_code' => 'DO', 'name' => 'Palmar de Ocoa', 'active' => 1, 'slug' => 'palmar-de-ocoa'],
            ['id' => 23964, 'region_id' => 709847, 'country_code' => 'DO', 'name' => 'Peralta', 'active' => 1, 'slug' => 'peralta'],
            ['id' => 23965, 'region_id' => 709847, 'country_code' => 'DO', 'name' => 'Proyecto 4', 'active' => 1, 'slug' => 'proyecto-4'],
            ['id' => 23966, 'region_id' => 709847, 'country_code' => 'DO', 'name' => 'Proyecto Ganadero 2c', 'active' => 1, 'slug' => 'proyecto-ganadero-2c'],
            ['id' => 23967, 'region_id' => 709847, 'country_code' => 'DO', 'name' => 'Pueblo Viejo', 'active' => 1, 'slug' => 'pueblo-viejo'],
            ['id' => 23968, 'region_id' => 709847, 'country_code' => 'DO', 'name' => 'Sabana Yegua', 'active' => 1, 'slug' => 'sabana-yegua'],
            ['id' => 23969, 'region_id' => 709847, 'country_code' => 'DO', 'name' => 'Tábara Abajo', 'active' => 1, 'slug' => 'tabara-abajo'],
            ['id' => 23970, 'region_id' => 709847, 'country_code' => 'DO', 'name' => 'Villa Tabara Arriba', 'active' => 1, 'slug' => 'villa-tabara-arriba'],
            ['id' => 23971, 'region_id' => 709847, 'country_code' => 'DO', 'name' => 'Villarpando', 'active' => 1, 'slug' => 'villarpando'],
            ['id' => 23972, 'region_id' => 709872, 'country_code' => 'DO', 'name' => 'Bahoruco', 'active' => 1, 'slug' => 'bahoruco'],
            ['id' => 23973, 'region_id' => 709872, 'country_code' => 'DO', 'name' => 'El Palmar', 'active' => 1, 'slug' => 'el-palmar'],
            ['id' => 23974, 'region_id' => 709872, 'country_code' => 'DO', 'name' => 'Galvan', 'active' => 1, 'slug' => 'galvan'],
            ['id' => 23975, 'region_id' => 709872, 'country_code' => 'DO', 'name' => 'Las Clavellinas', 'active' => 1, 'slug' => 'las-clavellinas'],
            ['id' => 23976, 'region_id' => 709872, 'country_code' => 'DO', 'name' => 'Los Rios', 'active' => 1, 'slug' => 'los-rios'],
            ['id' => 23977, 'region_id' => 709872, 'country_code' => 'DO', 'name' => 'Monserrat', 'active' => 1, 'slug' => 'monserrat'],
            ['id' => 23978, 'region_id' => 709872, 'country_code' => 'DO', 'name' => 'Neyba', 'active' => 1, 'slug' => 'neyba'],
            ['id' => 23979, 'region_id' => 709872, 'country_code' => 'DO', 'name' => 'Santana', 'active' => 1, 'slug' => 'santana'],
            ['id' => 23980, 'region_id' => 709872, 'country_code' => 'DO', 'name' => 'Tamayo', 'active' => 1, 'slug' => 'tamayo'],
            ['id' => 23981, 'region_id' => 709872, 'country_code' => 'DO', 'name' => 'Uvilla', 'active' => 1, 'slug' => 'uvilla'],
            ['id' => 23982, 'region_id' => 709872, 'country_code' => 'DO', 'name' => 'Villa Jaragua', 'active' => 1, 'slug' => 'villa-jaragua'],
            ['id' => 23983, 'region_id' => 709884, 'country_code' => 'DO', 'name' => 'Arroyo Dulce', 'active' => 1, 'slug' => 'arroyo-dulce'],
            ['id' => 23984, 'region_id' => 709884, 'country_code' => 'DO', 'name' => 'Bahoruco', 'active' => 1, 'slug' => 'bahoruco'],
            ['id' => 23985, 'region_id' => 709884, 'country_code' => 'DO', 'name' => 'Barahona', 'active' => 1, 'slug' => 'barahona'],
            ['id' => 23986, 'region_id' => 709884, 'country_code' => 'DO', 'name' => 'Cabral', 'active' => 1, 'slug' => 'cabral'],
            ['id' => 23987, 'region_id' => 709884, 'country_code' => 'DO', 'name' => 'Canoa', 'active' => 1, 'slug' => 'canoa'],
            ['id' => 23988, 'region_id' => 709884, 'country_code' => 'DO', 'name' => 'El Cachón', 'active' => 1, 'slug' => 'el-cachon'],
            ['id' => 23989, 'region_id' => 709884, 'country_code' => 'DO', 'name' => 'El Peñón', 'active' => 1, 'slug' => 'el-penon'],
            ['id' => 23990, 'region_id' => 709884, 'country_code' => 'DO', 'name' => 'Enriquillo', 'active' => 1, 'slug' => 'enriquillo'],
            ['id' => 23991, 'region_id' => 709884, 'country_code' => 'DO', 'name' => 'Fondo Negro', 'active' => 1, 'slug' => 'fondo-negro'],
            ['id' => 23992, 'region_id' => 709884, 'country_code' => 'DO', 'name' => 'Fundación', 'active' => 1, 'slug' => 'fundacion'],
            ['id' => 23993, 'region_id' => 709884, 'country_code' => 'DO', 'name' => 'Jaquimeyes', 'active' => 1, 'slug' => 'jaquimeyes'],
            ['id' => 23994, 'region_id' => 709884, 'country_code' => 'DO', 'name' => 'La Cienaga', 'active' => 1, 'slug' => 'la-cienaga'],
            ['id' => 23995, 'region_id' => 709884, 'country_code' => 'DO', 'name' => 'Las Salinas', 'active' => 1, 'slug' => 'las-salinas'],
            ['id' => 23996, 'region_id' => 709884, 'country_code' => 'DO', 'name' => 'Los Patos', 'active' => 1, 'slug' => 'los-patos'],
            ['id' => 23997, 'region_id' => 709884, 'country_code' => 'DO', 'name' => 'Paraíso', 'active' => 1, 'slug' => 'paraiso'],
            ['id' => 23998, 'region_id' => 709884, 'country_code' => 'DO', 'name' => 'Pescadería', 'active' => 1, 'slug' => 'pescaderia'],
            ['id' => 23999, 'region_id' => 709884, 'country_code' => 'DO', 'name' => 'Polo', 'active' => 1, 'slug' => 'polo'],
            ['id' => 24000, 'region_id' => 709884, 'country_code' => 'DO', 'name' => 'Quita Coraza', 'active' => 1, 'slug' => 'quita-coraza'],
            ['id' => 24001, 'region_id' => 709884, 'country_code' => 'DO', 'name' => 'Vicente Noble', 'active' => 1, 'slug' => 'vicente-noble'],
            ['id' => 24002, 'region_id' => 709904, 'country_code' => 'DO', 'name' => 'Dajabón', 'active' => 1, 'slug' => 'dajabon'],
            ['id' => 24003, 'region_id' => 709904, 'country_code' => 'DO', 'name' => 'El Pino', 'active' => 1, 'slug' => 'el-pino'],
            ['id' => 24004, 'region_id' => 709904, 'country_code' => 'DO', 'name' => 'Loma de Cabrera', 'active' => 1, 'slug' => 'loma-de-cabrera'],
            ['id' => 24005, 'region_id' => 709904, 'country_code' => 'DO', 'name' => 'Manuel Bueno', 'active' => 1, 'slug' => 'manuel-bueno'],
            ['id' => 24006, 'region_id' => 709904, 'country_code' => 'DO', 'name' => 'Partido', 'active' => 1, 'slug' => 'partido'],
            ['id' => 24007, 'region_id' => 709904, 'country_code' => 'DO', 'name' => 'Restauración', 'active' => 1, 'slug' => 'restauracion'],
            ['id' => 24008, 'region_id' => 709911, 'country_code' => 'DO', 'name' => 'Distrito Nacional', 'active' => 1, 'slug' => 'distrito-nacional'],
            ['id' => 24009, 'region_id' => 709913, 'country_code' => 'DO', 'name' => 'Agua Santa Del Yuna', 'active' => 1, 'slug' => 'agua-santa-del-yuna'],
            ['id' => 24010, 'region_id' => 709913, 'country_code' => 'DO', 'name' => 'Arenoso', 'active' => 1, 'slug' => 'arenoso'],
            ['id' => 24011, 'region_id' => 709913, 'country_code' => 'DO', 'name' => 'Castillo', 'active' => 1, 'slug' => 'castillo'],
            ['id' => 24012, 'region_id' => 709913, 'country_code' => 'DO', 'name' => 'Cenoví', 'active' => 1, 'slug' => 'cenovi'],
            ['id' => 24013, 'region_id' => 709913, 'country_code' => 'DO', 'name' => 'Cristo Rey de Guaraguao', 'active' => 1, 'slug' => 'cristo-rey-de-guaraguao'],
            ['id' => 24014, 'region_id' => 709913, 'country_code' => 'DO', 'name' => 'Duarte', 'active' => 1, 'slug' => 'duarte'],
            ['id' => 24015, 'region_id' => 709913, 'country_code' => 'DO', 'name' => 'Hostos', 'active' => 1, 'slug' => 'hostos'],
            ['id' => 24016, 'region_id' => 709913, 'country_code' => 'DO', 'name' => 'La Peña', 'active' => 1, 'slug' => 'la-pena'],
            ['id' => 24017, 'region_id' => 709913, 'country_code' => 'DO', 'name' => 'Las Coles', 'active' => 1, 'slug' => 'las-coles'],
            ['id' => 24018, 'region_id' => 709913, 'country_code' => 'DO', 'name' => 'Las Guaranas', 'active' => 1, 'slug' => 'las-guaranas'],
            ['id' => 24019, 'region_id' => 709913, 'country_code' => 'DO', 'name' => 'Las Táranas', 'active' => 1, 'slug' => 'las-taranas'],
            ['id' => 24020, 'region_id' => 709913, 'country_code' => 'DO', 'name' => 'Pimentel', 'active' => 1, 'slug' => 'pimentel'],
            ['id' => 24021, 'region_id' => 709913, 'country_code' => 'DO', 'name' => 'Sabana Grande de Hostos', 'active' => 1, 'slug' => 'sabana-grande-de-hostos'],
            ['id' => 24022, 'region_id' => 709913, 'country_code' => 'DO', 'name' => 'San Francisco de Macorís', 'active' => 1, 'slug' => 'san-francisco-de-macoris'],
            ['id' => 24023, 'region_id' => 709913, 'country_code' => 'DO', 'name' => 'Villa Riva', 'active' => 1, 'slug' => 'villa-riva'],
            ['id' => 24024, 'region_id' => 709929, 'country_code' => 'DO', 'name' => 'Bánica', 'active' => 1, 'slug' => 'banica'],
            ['id' => 24025, 'region_id' => 709929, 'country_code' => 'DO', 'name' => 'Comendador', 'active' => 1, 'slug' => 'comendador'],
            ['id' => 24026, 'region_id' => 709929, 'country_code' => 'DO', 'name' => 'El Llano', 'active' => 1, 'slug' => 'el-llano'],
            ['id' => 24027, 'region_id' => 709929, 'country_code' => 'DO', 'name' => 'Elías Piña', 'active' => 1, 'slug' => 'elias-pina'],
            ['id' => 24028, 'region_id' => 709929, 'country_code' => 'DO', 'name' => 'Hondo Valle', 'active' => 1, 'slug' => 'hondo-valle'],
            ['id' => 24029, 'region_id' => 709929, 'country_code' => 'DO', 'name' => 'Juan Santiago', 'active' => 1, 'slug' => 'juan-santiago'],
            ['id' => 24030, 'region_id' => 709929, 'country_code' => 'DO', 'name' => 'Pedro Santana', 'active' => 1, 'slug' => 'pedro-santana'],
            ['id' => 24031, 'region_id' => 709929, 'country_code' => 'DO', 'name' => 'Río Limpio', 'active' => 1, 'slug' => 'rio-limpio'],
            ['id' => 24032, 'region_id' => 709929, 'country_code' => 'DO', 'name' => 'Sabana Larga', 'active' => 1, 'slug' => 'sabana-larga'],
            ['id' => 24033, 'region_id' => 709939, 'country_code' => 'DO', 'name' => 'El Cedro', 'active' => 1, 'slug' => 'el-cedro'],
            ['id' => 24034, 'region_id' => 709939, 'country_code' => 'DO', 'name' => 'El Seibo', 'active' => 1, 'slug' => 'el-seibo'],
            ['id' => 24035, 'region_id' => 709939, 'country_code' => 'DO', 'name' => 'Miches', 'active' => 1, 'slug' => 'miches'],
            ['id' => 24036, 'region_id' => 709939, 'country_code' => 'DO', 'name' => 'Pedro Sánchez', 'active' => 1, 'slug' => 'pedro-sanchez'],
            ['id' => 24037, 'region_id' => 709944, 'country_code' => 'DO', 'name' => 'Canca la Reyna', 'active' => 1, 'slug' => 'canca-la-reyna'],
            ['id' => 24038, 'region_id' => 709944, 'country_code' => 'DO', 'name' => 'Cayetano Germosén', 'active' => 1, 'slug' => 'cayetano-germosen'],
            ['id' => 24039, 'region_id' => 709944, 'country_code' => 'DO', 'name' => 'El Higüerito', 'active' => 1, 'slug' => 'el-higuerito'],
            ['id' => 24040, 'region_id' => 709944, 'country_code' => 'DO', 'name' => 'Espaillat', 'active' => 1, 'slug' => 'espaillat'],
            ['id' => 24041, 'region_id' => 709944, 'country_code' => 'DO', 'name' => 'Gaspar Hernández', 'active' => 1, 'slug' => 'gaspar-hernandez'],
            ['id' => 24042, 'region_id' => 709944, 'country_code' => 'DO', 'name' => 'Jamao Al Norte', 'active' => 1, 'slug' => 'jamao-al-norte'],
            ['id' => 24043, 'region_id' => 709944, 'country_code' => 'DO', 'name' => 'Joba Arriba', 'active' => 1, 'slug' => 'joba-arriba'],
            ['id' => 24044, 'region_id' => 709944, 'country_code' => 'DO', 'name' => 'José Contreras', 'active' => 1, 'slug' => 'jose-contreras'],
            ['id' => 24045, 'region_id' => 709944, 'country_code' => 'DO', 'name' => 'Juan López', 'active' => 1, 'slug' => 'juan-lopez'],
            ['id' => 24046, 'region_id' => 709944, 'country_code' => 'DO', 'name' => 'La Ortega', 'active' => 1, 'slug' => 'la-ortega'],
            ['id' => 24047, 'region_id' => 709944, 'country_code' => 'DO', 'name' => 'Las Lagunas Abajo', 'active' => 1, 'slug' => 'las-lagunas-abajo'],
            ['id' => 24048, 'region_id' => 709944, 'country_code' => 'DO', 'name' => 'Moca', 'active' => 1, 'slug' => 'moca'],
            ['id' => 24049, 'region_id' => 709944, 'country_code' => 'DO', 'name' => 'Monte de la Jagua', 'active' => 1, 'slug' => 'monte-de-la-jagua'],
            ['id' => 24050, 'region_id' => 709944, 'country_code' => 'DO', 'name' => 'San Víctor', 'active' => 1, 'slug' => 'san-victor'],
            ['id' => 24051, 'region_id' => 709944, 'country_code' => 'DO', 'name' => 'Veragua', 'active' => 1, 'slug' => 'veragua'],
            ['id' => 24052, 'region_id' => 709960, 'country_code' => 'DO', 'name' => 'El Valle', 'active' => 1, 'slug' => 'el-valle'],
            ['id' => 24053, 'region_id' => 709960, 'country_code' => 'DO', 'name' => 'Elupina Cordero de las Cañitas', 'active' => 1, 'slug' => 'elupina-cordero-de-las-canitas'],
            ['id' => 24054, 'region_id' => 709960, 'country_code' => 'DO', 'name' => 'Guayabo Dulce', 'active' => 1, 'slug' => 'guayabo-dulce'],
            ['id' => 24055, 'region_id' => 709960, 'country_code' => 'DO', 'name' => 'Hato Mayor', 'active' => 1, 'slug' => 'hato-mayor'],
            ['id' => 24056, 'region_id' => 709960, 'country_code' => 'DO', 'name' => 'Mata Palacio', 'active' => 1, 'slug' => 'mata-palacio'],
            ['id' => 24057, 'region_id' => 709960, 'country_code' => 'DO', 'name' => 'Sabana de la Mar', 'active' => 1, 'slug' => 'sabana-de-la-mar'],
            ['id' => 24058, 'region_id' => 709960, 'country_code' => 'DO', 'name' => 'Yerba Buena', 'active' => 1, 'slug' => 'yerba-buena'],
            ['id' => 24059, 'region_id' => 709968, 'country_code' => 'DO', 'name' => 'Cristóbal', 'active' => 1, 'slug' => 'cristobal'],
            ['id' => 24060, 'region_id' => 709968, 'country_code' => 'DO', 'name' => 'El Limón', 'active' => 1, 'slug' => 'el-limon'],
            ['id' => 24061, 'region_id' => 709968, 'country_code' => 'DO', 'name' => 'Guayabal', 'active' => 1, 'slug' => 'guayabal'],
            ['id' => 24062, 'region_id' => 709968, 'country_code' => 'DO', 'name' => 'Independencia', 'active' => 1, 'slug' => 'independencia'],
            ['id' => 24063, 'region_id' => 709968, 'country_code' => 'DO', 'name' => 'Jimaní', 'active' => 1, 'slug' => 'jimani'],
            ['id' => 24064, 'region_id' => 709968, 'country_code' => 'DO', 'name' => 'La Colonia Mixta', 'active' => 1, 'slug' => 'la-colonia-mixta'],
            ['id' => 24065, 'region_id' => 709968, 'country_code' => 'DO', 'name' => 'La Descubierta', 'active' => 1, 'slug' => 'la-descubierta'],
            ['id' => 24066, 'region_id' => 709968, 'country_code' => 'DO', 'name' => 'Mella', 'active' => 1, 'slug' => 'mella'],
            ['id' => 24067, 'region_id' => 709968, 'country_code' => 'DO', 'name' => 'Postrer Río', 'active' => 1, 'slug' => 'postrer-rio'],
            ['id' => 24068, 'region_id' => 709978, 'country_code' => 'DO', 'name' => 'Bayahibe', 'active' => 1, 'slug' => 'bayahibe'],
            ['id' => 24069, 'region_id' => 709978, 'country_code' => 'DO', 'name' => 'Boca de Yuma', 'active' => 1, 'slug' => 'boca-de-yuma'],
            ['id' => 24070, 'region_id' => 709978, 'country_code' => 'DO', 'name' => 'Higüey', 'active' => 1, 'slug' => 'higuey'],
            ['id' => 24071, 'region_id' => 709978, 'country_code' => 'DO', 'name' => 'La Altagracia', 'active' => 1, 'slug' => 'la-altagracia'],
            ['id' => 24072, 'region_id' => 709978, 'country_code' => 'DO', 'name' => 'La Laguna de Nisibon', 'active' => 1, 'slug' => 'la-laguna-de-nisibon'],
            ['id' => 24073, 'region_id' => 709978, 'country_code' => 'DO', 'name' => 'La Otra Banda', 'active' => 1, 'slug' => 'la-otra-banda'],
            ['id' => 24074, 'region_id' => 709978, 'country_code' => 'DO', 'name' => 'Salvaleon de Higuey', 'active' => 1, 'slug' => 'salvaleon-de-higuey'],
            ['id' => 24075, 'region_id' => 709978, 'country_code' => 'DO', 'name' => 'San Rafael Del Yuma', 'active' => 1, 'slug' => 'san-rafael-del-yuma'],
            ['id' => 24076, 'region_id' => 709987, 'country_code' => 'DO', 'name' => 'Cumayasa', 'active' => 1, 'slug' => 'cumayasa'],
            ['id' => 24077, 'region_id' => 709987, 'country_code' => 'DO', 'name' => 'Guaymate', 'active' => 1, 'slug' => 'guaymate'],
            ['id' => 24078, 'region_id' => 709987, 'country_code' => 'DO', 'name' => 'La Romana', 'active' => 1, 'slug' => 'la-romana'],
            ['id' => 24079, 'region_id' => 709987, 'country_code' => 'DO', 'name' => 'Villa Hermosa', 'active' => 1, 'slug' => 'villa-hermosa'],
            ['id' => 24080, 'region_id' => 709992, 'country_code' => 'DO', 'name' => 'Buena Vista', 'active' => 1, 'slug' => 'buena-vista'],
            ['id' => 24081, 'region_id' => 709992, 'country_code' => 'DO', 'name' => 'Constanza', 'active' => 1, 'slug' => 'constanza'],
            ['id' => 24082, 'region_id' => 709992, 'country_code' => 'DO', 'name' => 'El Ranchito', 'active' => 1, 'slug' => 'el-ranchito'],
            ['id' => 24083, 'region_id' => 709992, 'country_code' => 'DO', 'name' => 'Jarabacoa', 'active' => 1, 'slug' => 'jarabacoa'],
            ['id' => 24084, 'region_id' => 709992, 'country_code' => 'DO', 'name' => 'Jima Abajo', 'active' => 1, 'slug' => 'jima-abajo'],
            ['id' => 24085, 'region_id' => 709992, 'country_code' => 'DO', 'name' => 'La Concepción de la Vega', 'active' => 1, 'slug' => 'la-concepcion-de-la-vega'],
            ['id' => 24086, 'region_id' => 709992, 'country_code' => 'DO', 'name' => 'La Vega', 'active' => 1, 'slug' => 'la-vega'],
            ['id' => 24087, 'region_id' => 709992, 'country_code' => 'DO', 'name' => 'Rincón', 'active' => 1, 'slug' => 'rincon'],
            ['id' => 24088, 'region_id' => 709992, 'country_code' => 'DO', 'name' => 'Río Verde Arriba', 'active' => 1, 'slug' => 'rio-verde-arriba'],
            ['id' => 24089, 'region_id' => 709992, 'country_code' => 'DO', 'name' => 'Sabina', 'active' => 1, 'slug' => 'sabina'],
            ['id' => 24090, 'region_id' => 709992, 'country_code' => 'DO', 'name' => 'Tireo Arriba', 'active' => 1, 'slug' => 'tireo-arriba'],
            ['id' => 24091, 'region_id' => 710004, 'country_code' => 'DO', 'name' => 'Arroyo Salado', 'active' => 1, 'slug' => 'arroyo-salado'],
            ['id' => 24092, 'region_id' => 710004, 'country_code' => 'DO', 'name' => 'Cabrera', 'active' => 1, 'slug' => 'cabrera'],
            ['id' => 24093, 'region_id' => 710004, 'country_code' => 'DO', 'name' => 'El Factor', 'active' => 1, 'slug' => 'el-factor'],
            ['id' => 24094, 'region_id' => 710004, 'country_code' => 'DO', 'name' => 'El Pozo', 'active' => 1, 'slug' => 'el-pozo'],
            ['id' => 24095, 'region_id' => 710004, 'country_code' => 'DO', 'name' => 'La Entrada', 'active' => 1, 'slug' => 'la-entrada'],
            ['id' => 24096, 'region_id' => 710004, 'country_code' => 'DO', 'name' => 'Las Gordas', 'active' => 1, 'slug' => 'las-gordas'],
            ['id' => 24097, 'region_id' => 710004, 'country_code' => 'DO', 'name' => 'María Trinidad Sánchez', 'active' => 1, 'slug' => 'maria-trinidad-sanchez'],
            ['id' => 24098, 'region_id' => 710004, 'country_code' => 'DO', 'name' => 'Nagua', 'active' => 1, 'slug' => 'nagua'],
            ['id' => 24099, 'region_id' => 710004, 'country_code' => 'DO', 'name' => 'Rio San Juan', 'active' => 1, 'slug' => 'rio-san-juan'],
            ['id' => 24100, 'region_id' => 710004, 'country_code' => 'DO', 'name' => 'San José de Matanzas', 'active' => 1, 'slug' => 'san-jose-de-matanzas'],
            ['id' => 24101, 'region_id' => 710015, 'country_code' => 'DO', 'name' => 'Bonao', 'active' => 1, 'slug' => 'bonao'],
            ['id' => 24102, 'region_id' => 710015, 'country_code' => 'DO', 'name' => 'Juan Aldián', 'active' => 1, 'slug' => 'juan-aldian'],
            ['id' => 24103, 'region_id' => 710015, 'country_code' => 'DO', 'name' => 'Juma Bejucal', 'active' => 1, 'slug' => 'juma-bejucal'],
            ['id' => 24104, 'region_id' => 710015, 'country_code' => 'DO', 'name' => 'Maimon', 'active' => 1, 'slug' => 'maimon'],
            ['id' => 24105, 'region_id' => 710015, 'country_code' => 'DO', 'name' => 'Monseñor Nouel', 'active' => 1, 'slug' => 'monsenor-nouel'],
            ['id' => 24106, 'region_id' => 710015, 'country_code' => 'DO', 'name' => 'Piedra Blanca', 'active' => 1, 'slug' => 'piedra-blanca'],
            ['id' => 24107, 'region_id' => 710015, 'country_code' => 'DO', 'name' => 'Sabana Del Puerto', 'active' => 1, 'slug' => 'sabana-del-puerto'],
            ['id' => 24108, 'region_id' => 710015, 'country_code' => 'DO', 'name' => 'Sonador', 'active' => 1, 'slug' => 'sonador'],
            ['id' => 24109, 'region_id' => 710024, 'country_code' => 'DO', 'name' => 'Cana Chapetón', 'active' => 1, 'slug' => 'cana-chapeton'],
            ['id' => 24110, 'region_id' => 710024, 'country_code' => 'DO', 'name' => 'Castañuelas', 'active' => 1, 'slug' => 'castanuelas'],
            ['id' => 24111, 'region_id' => 710024, 'country_code' => 'DO', 'name' => 'Guayubin', 'active' => 1, 'slug' => 'guayubin'],
            ['id' => 24112, 'region_id' => 710024, 'country_code' => 'DO', 'name' => 'Hatillo Palma', 'active' => 1, 'slug' => 'hatillo-palma'],
            ['id' => 24113, 'region_id' => 710024, 'country_code' => 'DO', 'name' => 'Las Matas de Santa Cruz', 'active' => 1, 'slug' => 'las-matas-de-santa-cruz'],
            ['id' => 24114, 'region_id' => 710024, 'country_code' => 'DO', 'name' => 'Monte Cristi', 'active' => 1, 'slug' => 'monte-cristi'],
            ['id' => 24115, 'region_id' => 710024, 'country_code' => 'DO', 'name' => 'Palo Verde', 'active' => 1, 'slug' => 'palo-verde'],
            ['id' => 24116, 'region_id' => 710024, 'country_code' => 'DO', 'name' => 'Pepillo Salcedo', 'active' => 1, 'slug' => 'pepillo-salcedo'],
            ['id' => 24117, 'region_id' => 710024, 'country_code' => 'DO', 'name' => 'San Fernando de Montecristi', 'active' => 1, 'slug' => 'san-fernando-de-montecristi'],
            ['id' => 24118, 'region_id' => 710024, 'country_code' => 'DO', 'name' => 'Villa Elisa', 'active' => 1, 'slug' => 'villa-elisa'],
            ['id' => 24119, 'region_id' => 710024, 'country_code' => 'DO', 'name' => 'Villa Vazquez', 'active' => 1, 'slug' => 'villa-vazquez'],
            ['id' => 24120, 'region_id' => 710036, 'country_code' => 'DO', 'name' => 'Bayaguana', 'active' => 1, 'slug' => 'bayaguana'],
            ['id' => 24121, 'region_id' => 710036, 'country_code' => 'DO', 'name' => 'Boyá', 'active' => 1, 'slug' => 'boya'],
            ['id' => 24122, 'region_id' => 710036, 'country_code' => 'DO', 'name' => 'Chirino', 'active' => 1, 'slug' => 'chirino'],
            ['id' => 24123, 'region_id' => 710036, 'country_code' => 'DO', 'name' => 'Don Juan', 'active' => 1, 'slug' => 'don-juan'],
            ['id' => 24124, 'region_id' => 710036, 'country_code' => 'DO', 'name' => 'Esperalvillo', 'active' => 1, 'slug' => 'esperalvillo'],
            ['id' => 24125, 'region_id' => 710036, 'country_code' => 'DO', 'name' => 'Gonzalo', 'active' => 1, 'slug' => 'gonzalo'],
            ['id' => 24126, 'region_id' => 710036, 'country_code' => 'DO', 'name' => 'Los Botados', 'active' => 1, 'slug' => 'los-botados'],
            ['id' => 24127, 'region_id' => 710036, 'country_code' => 'DO', 'name' => 'Majagual', 'active' => 1, 'slug' => 'majagual'],
            ['id' => 24128, 'region_id' => 710036, 'country_code' => 'DO', 'name' => 'Monte Plata', 'active' => 1, 'slug' => 'monte-plata'],
            ['id' => 24129, 'region_id' => 710036, 'country_code' => 'DO', 'name' => 'Sabana Grande de Boyá', 'active' => 1, 'slug' => 'sabana-grande-de-boya'],
            ['id' => 24130, 'region_id' => 710036, 'country_code' => 'DO', 'name' => 'San Francisco', 'active' => 1, 'slug' => 'san-francisco'],
            ['id' => 24131, 'region_id' => 710036, 'country_code' => 'DO', 'name' => 'Yamasa', 'active' => 1, 'slug' => 'yamasa'],
            ['id' => 24132, 'region_id' => 710049, 'country_code' => 'DO', 'name' => 'Bani', 'active' => 1, 'slug' => 'bani'],
            ['id' => 24133, 'region_id' => 710049, 'country_code' => 'DO', 'name' => 'Catalina', 'active' => 1, 'slug' => 'catalina'],
            ['id' => 24134, 'region_id' => 710049, 'country_code' => 'DO', 'name' => 'El Carretón', 'active' => 1, 'slug' => 'el-carreton'],
            ['id' => 24135, 'region_id' => 710049, 'country_code' => 'DO', 'name' => 'Matanzas', 'active' => 1, 'slug' => 'matanzas'],
            ['id' => 24136, 'region_id' => 710049, 'country_code' => 'DO', 'name' => 'Nizao', 'active' => 1, 'slug' => 'nizao'],
            ['id' => 24137, 'region_id' => 710049, 'country_code' => 'DO', 'name' => 'Paya', 'active' => 1, 'slug' => 'paya'],
            ['id' => 24138, 'region_id' => 710049, 'country_code' => 'DO', 'name' => 'Peravia', 'active' => 1, 'slug' => 'peravia'],
            ['id' => 24139, 'region_id' => 710049, 'country_code' => 'DO', 'name' => 'Pizarrete', 'active' => 1, 'slug' => 'pizarrete'],
            ['id' => 24140, 'region_id' => 710049, 'country_code' => 'DO', 'name' => 'Rancho Arriba', 'active' => 1, 'slug' => 'rancho-arriba'],
            ['id' => 24141, 'region_id' => 710049, 'country_code' => 'DO', 'name' => 'Sabana Buey', 'active' => 1, 'slug' => 'sabana-buey'],
            ['id' => 24142, 'region_id' => 710049, 'country_code' => 'DO', 'name' => 'Sabana Larga', 'active' => 1, 'slug' => 'sabana-larga'],
            ['id' => 24143, 'region_id' => 710049, 'country_code' => 'DO', 'name' => 'San José de Ocoa', 'active' => 1, 'slug' => 'san-jose-de-ocoa'],
            ['id' => 24144, 'region_id' => 710049, 'country_code' => 'DO', 'name' => 'Santana', 'active' => 1, 'slug' => 'santana'],
            ['id' => 24145, 'region_id' => 710049, 'country_code' => 'DO', 'name' => 'Villa Funcación Baní', 'active' => 1, 'slug' => 'villa-funcacion-bani'],
            ['id' => 24146, 'region_id' => 710049, 'country_code' => 'DO', 'name' => 'Villa Sombrero', 'active' => 1, 'slug' => 'villa-sombrero'],
            ['id' => 24147, 'region_id' => 710065, 'country_code' => 'DO', 'name' => 'Juancho', 'active' => 1, 'slug' => 'juancho'],
            ['id' => 24148, 'region_id' => 710065, 'country_code' => 'DO', 'name' => 'Oviedo', 'active' => 1, 'slug' => 'oviedo'],
            ['id' => 24149, 'region_id' => 710065, 'country_code' => 'DO', 'name' => 'Pedernales', 'active' => 1, 'slug' => 'pedernales'],
            ['id' => 24150, 'region_id' => 710069, 'country_code' => 'DO', 'name' => 'Altamira', 'active' => 1, 'slug' => 'altamira'],
            ['id' => 24151, 'region_id' => 710069, 'country_code' => 'DO', 'name' => 'Belloso', 'active' => 1, 'slug' => 'belloso'],
            ['id' => 24152, 'region_id' => 710069, 'country_code' => 'DO', 'name' => 'Cabarete Infromacion Gral', 'active' => 1, 'slug' => 'cabarete-infromacion-gral'],
            ['id' => 24153, 'region_id' => 710069, 'country_code' => 'DO', 'name' => 'Estero Hondo', 'active' => 1, 'slug' => 'estero-hondo'],
            ['id' => 24154, 'region_id' => 710069, 'country_code' => 'DO', 'name' => 'Guanico', 'active' => 1, 'slug' => 'guanico'],
            ['id' => 24155, 'region_id' => 710069, 'country_code' => 'DO', 'name' => 'Imbert', 'active' => 1, 'slug' => 'imbert'],
            ['id' => 24156, 'region_id' => 710069, 'country_code' => 'DO', 'name' => 'La Isabela', 'active' => 1, 'slug' => 'la-isabela'],
            ['id' => 24157, 'region_id' => 710069, 'country_code' => 'DO', 'name' => 'La Jaiba', 'active' => 1, 'slug' => 'la-jaiba'],
            ['id' => 24158, 'region_id' => 710069, 'country_code' => 'DO', 'name' => 'Los Hidalgos', 'active' => 1, 'slug' => 'los-hidalgos'],
            ['id' => 24159, 'region_id' => 710069, 'country_code' => 'DO', 'name' => 'Luperon', 'active' => 1, 'slug' => 'luperon'],
            ['id' => 24160, 'region_id' => 710069, 'country_code' => 'DO', 'name' => 'Puerto Plata', 'active' => 1, 'slug' => 'puerto-plata'],
            ['id' => 24161, 'region_id' => 710069, 'country_code' => 'DO', 'name' => 'Puerto Plata Infromacion Gral', 'active' => 1, 'slug' => 'puerto-plata-infromacion-gral'],
            ['id' => 24162, 'region_id' => 710069, 'country_code' => 'DO', 'name' => 'Sabaneta de Básica', 'active' => 1, 'slug' => 'sabaneta-de-basica'],
            ['id' => 24163, 'region_id' => 710069, 'country_code' => 'DO', 'name' => 'San Felipe de Puerto Plata', 'active' => 1, 'slug' => 'san-felipe-de-puerto-plata'],
            ['id' => 24164, 'region_id' => 710069, 'country_code' => 'DO', 'name' => 'Sosua', 'active' => 1, 'slug' => 'sosua'],
            ['id' => 24165, 'region_id' => 710069, 'country_code' => 'DO', 'name' => 'Villa Isabela', 'active' => 1, 'slug' => 'villa-isabela'],
            ['id' => 24166, 'region_id' => 710069, 'country_code' => 'DO', 'name' => 'Villa Montellano', 'active' => 1, 'slug' => 'villa-montellano'],
            ['id' => 24167, 'region_id' => 710087, 'country_code' => 'DO', 'name' => 'Blanco', 'active' => 1, 'slug' => 'blanco'],
            ['id' => 24168, 'region_id' => 710087, 'country_code' => 'DO', 'name' => 'Jamao Afuera', 'active' => 1, 'slug' => 'jamao-afuera'],
            ['id' => 24169, 'region_id' => 710090, 'country_code' => 'DO', 'name' => 'Arroyo Barril', 'active' => 1, 'slug' => 'arroyo-barril'],
            ['id' => 24170, 'region_id' => 710090, 'country_code' => 'DO', 'name' => 'El Limón', 'active' => 1, 'slug' => 'el-limon'],
            ['id' => 24171, 'region_id' => 710090, 'country_code' => 'DO', 'name' => 'Las Terrenas', 'active' => 1, 'slug' => 'las-terrenas'],
            ['id' => 24172, 'region_id' => 710090, 'country_code' => 'DO', 'name' => 'Samaná', 'active' => 1, 'slug' => 'samana'],
            ['id' => 24173, 'region_id' => 710090, 'country_code' => 'DO', 'name' => 'Sánchez', 'active' => 1, 'slug' => 'sanchez'],
            ['id' => 24174, 'region_id' => 710090, 'country_code' => 'DO', 'name' => 'Santa Barbara de Samana', 'active' => 1, 'slug' => 'santa-barbara-de-samana'],
            ['id' => 24175, 'region_id' => 710097, 'country_code' => 'DO', 'name' => 'Bajos de Haina', 'active' => 1, 'slug' => 'bajos-de-haina'],
            ['id' => 24176, 'region_id' => 710097, 'country_code' => 'DO', 'name' => 'Cambita Garabitos', 'active' => 1, 'slug' => 'cambita-garabitos'],
            ['id' => 24177, 'region_id' => 710097, 'country_code' => 'DO', 'name' => 'El Cacao', 'active' => 1, 'slug' => 'el-cacao'],
            ['id' => 24178, 'region_id' => 710097, 'country_code' => 'DO', 'name' => 'El Carril', 'active' => 1, 'slug' => 'el-carril'],
            ['id' => 24179, 'region_id' => 710097, 'country_code' => 'DO', 'name' => 'El Puerto', 'active' => 1, 'slug' => 'el-puerto'],
            ['id' => 24180, 'region_id' => 710097, 'country_code' => 'DO', 'name' => 'La Cuchilla', 'active' => 1, 'slug' => 'la-cuchilla'],
            ['id' => 24181, 'region_id' => 710097, 'country_code' => 'DO', 'name' => 'Medina', 'active' => 1, 'slug' => 'medina'],
            ['id' => 24182, 'region_id' => 710097, 'country_code' => 'DO', 'name' => 'Nigua', 'active' => 1, 'slug' => 'nigua'],
            ['id' => 24183, 'region_id' => 710097, 'country_code' => 'DO', 'name' => 'Sabana Grande de Palenque', 'active' => 1, 'slug' => 'sabana-grande-de-palenque'],
            ['id' => 24184, 'region_id' => 710097, 'country_code' => 'DO', 'name' => 'San Cristóbal', 'active' => 1, 'slug' => 'san-cristobal'],
            ['id' => 24185, 'region_id' => 710097, 'country_code' => 'DO', 'name' => 'San Gregorio de Yaguate', 'active' => 1, 'slug' => 'san-gregorio-de-yaguate'],
            ['id' => 24186, 'region_id' => 710097, 'country_code' => 'DO', 'name' => 'Villa Altagracia', 'active' => 1, 'slug' => 'villa-altagracia'],
            ['id' => 24187, 'region_id' => 710097, 'country_code' => 'DO', 'name' => 'Yaguate', 'active' => 1, 'slug' => 'yaguate'],
            ['id' => 24188, 'region_id' => 710111, 'country_code' => 'DO', 'name' => 'El Pinar', 'active' => 1, 'slug' => 'el-pinar'],
            ['id' => 24189, 'region_id' => 710111, 'country_code' => 'DO', 'name' => 'La Ciénaga', 'active' => 1, 'slug' => 'la-cienaga'],
            ['id' => 24190, 'region_id' => 710111, 'country_code' => 'DO', 'name' => 'Nizao-las Auyamas', 'active' => 1, 'slug' => 'nizao-las-auyamas'],
            ['id' => 24191, 'region_id' => 710111, 'country_code' => 'DO', 'name' => 'Rancho Arriba', 'active' => 1, 'slug' => 'rancho-arriba'],
            ['id' => 24192, 'region_id' => 710111, 'country_code' => 'DO', 'name' => 'Sabana Larga', 'active' => 1, 'slug' => 'sabana-larga'],
            ['id' => 24193, 'region_id' => 710111, 'country_code' => 'DO', 'name' => 'San José de Ocoa', 'active' => 1, 'slug' => 'san-jose-de-ocoa'],
            ['id' => 24194, 'region_id' => 710118, 'country_code' => 'DO', 'name' => 'Arroyo Cano', 'active' => 1, 'slug' => 'arroyo-cano'],
            ['id' => 24195, 'region_id' => 710118, 'country_code' => 'DO', 'name' => 'Boechio', 'active' => 1, 'slug' => 'boechio'],
            ['id' => 24196, 'region_id' => 710118, 'country_code' => 'DO', 'name' => 'El Cercado', 'active' => 1, 'slug' => 'el-cercado'],
            ['id' => 24197, 'region_id' => 710118, 'country_code' => 'DO', 'name' => 'Juan de Herrera', 'active' => 1, 'slug' => 'juan-de-herrera'],
            ['id' => 24198, 'region_id' => 710118, 'country_code' => 'DO', 'name' => 'Las Matas de Farfan', 'active' => 1, 'slug' => 'las-matas-de-farfan'],
            ['id' => 24199, 'region_id' => 710118, 'country_code' => 'DO', 'name' => 'Matayaya', 'active' => 1, 'slug' => 'matayaya'],
            ['id' => 24200, 'region_id' => 710118, 'country_code' => 'DO', 'name' => 'Pedro Corto', 'active' => 1, 'slug' => 'pedro-corto'],
            ['id' => 24201, 'region_id' => 710118, 'country_code' => 'DO', 'name' => 'Sabaneta', 'active' => 1, 'slug' => 'sabaneta'],
            ['id' => 24202, 'region_id' => 710118, 'country_code' => 'DO', 'name' => 'San Juan', 'active' => 1, 'slug' => 'san-juan'],
            ['id' => 24203, 'region_id' => 710118, 'country_code' => 'DO', 'name' => 'San Juan de la Maguana', 'active' => 1, 'slug' => 'san-juan-de-la-maguana'],
            ['id' => 24204, 'region_id' => 710118, 'country_code' => 'DO', 'name' => 'Vallejuelo', 'active' => 1, 'slug' => 'vallejuelo'],
            ['id' => 24205, 'region_id' => 710118, 'country_code' => 'DO', 'name' => 'Yaque', 'active' => 1, 'slug' => 'yaque'],
            ['id' => 24206, 'region_id' => 710131, 'country_code' => 'DO', 'name' => 'Consuelo', 'active' => 1, 'slug' => 'consuelo'],
            ['id' => 24207, 'region_id' => 710131, 'country_code' => 'DO', 'name' => 'El Puerto', 'active' => 1, 'slug' => 'el-puerto'],
            ['id' => 24208, 'region_id' => 710131, 'country_code' => 'DO', 'name' => 'Gautier', 'active' => 1, 'slug' => 'gautier'],
            ['id' => 24209, 'region_id' => 710131, 'country_code' => 'DO', 'name' => 'Ingenio Quisqueya', 'active' => 1, 'slug' => 'ingenio-quisqueya'],
            ['id' => 24210, 'region_id' => 710131, 'country_code' => 'DO', 'name' => 'Los Llanos', 'active' => 1, 'slug' => 'los-llanos'],
            ['id' => 24211, 'region_id' => 710131, 'country_code' => 'DO', 'name' => 'Quisqueya', 'active' => 1, 'slug' => 'quisqueya'],
            ['id' => 24212, 'region_id' => 710131, 'country_code' => 'DO', 'name' => 'Ramon Santana', 'active' => 1, 'slug' => 'ramon-santana'],
            ['id' => 24213, 'region_id' => 710131, 'country_code' => 'DO', 'name' => 'San José de los Llanos', 'active' => 1, 'slug' => 'san-jose-de-los-llanos'],
            ['id' => 24214, 'region_id' => 710131, 'country_code' => 'DO', 'name' => 'San Pedro de Macorís', 'active' => 1, 'slug' => 'san-pedro-de-macoris'],
            ['id' => 24215, 'region_id' => 710141, 'country_code' => 'DO', 'name' => 'Angelina', 'active' => 1, 'slug' => 'angelina'],
            ['id' => 24216, 'region_id' => 710141, 'country_code' => 'DO', 'name' => 'Cevicos', 'active' => 1, 'slug' => 'cevicos'],
            ['id' => 24217, 'region_id' => 710141, 'country_code' => 'DO', 'name' => 'Cotui', 'active' => 1, 'slug' => 'cotui'],
            ['id' => 24218, 'region_id' => 710141, 'country_code' => 'DO', 'name' => 'Fantino', 'active' => 1, 'slug' => 'fantino'],
            ['id' => 24219, 'region_id' => 710141, 'country_code' => 'DO', 'name' => 'La Bija', 'active' => 1, 'slug' => 'la-bija'],
            ['id' => 24220, 'region_id' => 710141, 'country_code' => 'DO', 'name' => 'Las Cuevas', 'active' => 1, 'slug' => 'las-cuevas'],
            ['id' => 24221, 'region_id' => 710141, 'country_code' => 'DO', 'name' => 'Las Matas', 'active' => 1, 'slug' => 'las-matas'],
            ['id' => 24222, 'region_id' => 710141, 'country_code' => 'DO', 'name' => 'Sanchez Ramirez', 'active' => 1, 'slug' => 'sanchez-ramirez'],
            ['id' => 24223, 'region_id' => 710150, 'country_code' => 'DO', 'name' => 'Baitoa', 'active' => 1, 'slug' => 'baitoa'],
            ['id' => 24224, 'region_id' => 710150, 'country_code' => 'DO', 'name' => 'El Limón', 'active' => 1, 'slug' => 'el-limon'],
            ['id' => 24225, 'region_id' => 710150, 'country_code' => 'DO', 'name' => 'El Rubio', 'active' => 1, 'slug' => 'el-rubio'],
            ['id' => 24226, 'region_id' => 710150, 'country_code' => 'DO', 'name' => 'Hato Del Yaque', 'active' => 1, 'slug' => 'hato-del-yaque'],
            ['id' => 24227, 'region_id' => 710150, 'country_code' => 'DO', 'name' => 'Janico', 'active' => 1, 'slug' => 'janico'],
            ['id' => 24228, 'region_id' => 710150, 'country_code' => 'DO', 'name' => 'Juncalito', 'active' => 1, 'slug' => 'juncalito'],
            ['id' => 24229, 'region_id' => 710150, 'country_code' => 'DO', 'name' => 'La Canela', 'active' => 1, 'slug' => 'la-canela'],
            ['id' => 24230, 'region_id' => 710150, 'country_code' => 'DO', 'name' => 'La Cuesta', 'active' => 1, 'slug' => 'la-cuesta'],
            ['id' => 24231, 'region_id' => 710150, 'country_code' => 'DO', 'name' => 'Las Placetas', 'active' => 1, 'slug' => 'las-placetas'],
            ['id' => 24232, 'region_id' => 710150, 'country_code' => 'DO', 'name' => 'Licey Al Medio', 'active' => 1, 'slug' => 'licey-al-medio'],
            ['id' => 24233, 'region_id' => 710150, 'country_code' => 'DO', 'name' => 'Palmar Arriba', 'active' => 1, 'slug' => 'palmar-arriba'],
            ['id' => 24234, 'region_id' => 710150, 'country_code' => 'DO', 'name' => 'Pedro Garcia', 'active' => 1, 'slug' => 'pedro-garcia'],
            ['id' => 24235, 'region_id' => 710150, 'country_code' => 'DO', 'name' => 'Sabana Iglesia', 'active' => 1, 'slug' => 'sabana-iglesia'],
            ['id' => 24236, 'region_id' => 710150, 'country_code' => 'DO', 'name' => 'San Francisco de Jacagua', 'active' => 1, 'slug' => 'san-francisco-de-jacagua'],
            ['id' => 24237, 'region_id' => 710150, 'country_code' => 'DO', 'name' => 'San José de las Matas', 'active' => 1, 'slug' => 'san-jose-de-las-matas'],
            ['id' => 24238, 'region_id' => 710150, 'country_code' => 'DO', 'name' => 'Santiago', 'active' => 1, 'slug' => 'santiago'],
            ['id' => 24239, 'region_id' => 710150, 'country_code' => 'DO', 'name' => 'Santiago de los Caballeros', 'active' => 1, 'slug' => 'santiago-de-los-caballeros'],
            ['id' => 24240, 'region_id' => 710150, 'country_code' => 'DO', 'name' => 'Tamboril', 'active' => 1, 'slug' => 'tamboril'],
            ['id' => 24241, 'region_id' => 710150, 'country_code' => 'DO', 'name' => 'Villa Bisono', 'active' => 1, 'slug' => 'villa-bisono'],
            ['id' => 24242, 'region_id' => 710150, 'country_code' => 'DO', 'name' => 'Villa González', 'active' => 1, 'slug' => 'villa-gonzalez'],
            ['id' => 24243, 'region_id' => 710171, 'country_code' => 'DO', 'name' => 'Los Almacigos', 'active' => 1, 'slug' => 'los-almacigos'],
            ['id' => 24244, 'region_id' => 710171, 'country_code' => 'DO', 'name' => 'Moncion', 'active' => 1, 'slug' => 'moncion'],
            ['id' => 24245, 'region_id' => 710171, 'country_code' => 'DO', 'name' => 'San Ignacio de Sabaneta', 'active' => 1, 'slug' => 'san-ignacio-de-sabaneta'],
            ['id' => 24246, 'region_id' => 710171, 'country_code' => 'DO', 'name' => 'Santiago Rodriguez', 'active' => 1, 'slug' => 'santiago-rodriguez'],
            ['id' => 24259, 'region_id' => 710188, 'country_code' => 'DO', 'name' => 'Ámina', 'active' => 1, 'slug' => 'amina'],
            ['id' => 24260, 'region_id' => 710188, 'country_code' => 'DO', 'name' => 'Cruce de Guayacanes', 'active' => 1, 'slug' => 'cruce-de-guayacanes'],
            ['id' => 24261, 'region_id' => 710188, 'country_code' => 'DO', 'name' => 'Esperanza', 'active' => 1, 'slug' => 'esperanza'],
            ['id' => 24262, 'region_id' => 710188, 'country_code' => 'DO', 'name' => 'Guatapanal', 'active' => 1, 'slug' => 'guatapanal'],
            ['id' => 24263, 'region_id' => 710188, 'country_code' => 'DO', 'name' => 'Jaibón', 'active' => 1, 'slug' => 'jaibon'],
            ['id' => 24264, 'region_id' => 710188, 'country_code' => 'DO', 'name' => 'Jicomé', 'active' => 1, 'slug' => 'jicome'],
            ['id' => 24265, 'region_id' => 710188, 'country_code' => 'DO', 'name' => 'La Caya', 'active' => 1, 'slug' => 'la-caya'],
            ['id' => 24266, 'region_id' => 710188, 'country_code' => 'DO', 'name' => 'Laguna Salada', 'active' => 1, 'slug' => 'laguna-salada'],
            ['id' => 24267, 'region_id' => 710188, 'country_code' => 'DO', 'name' => 'Maizal', 'active' => 1, 'slug' => 'maizal'],
            ['id' => 24268, 'region_id' => 710188, 'country_code' => 'DO', 'name' => 'Mao', 'active' => 1, 'slug' => 'mao'],
            ['id' => 24269, 'region_id' => 710188, 'country_code' => 'DO', 'name' => 'Valverde', 'active' => 1, 'slug' => 'valverde']
    	];
    }
}
