<?php

namespace Gerardojbaez\GeoData\Seeders;

use Illuminate\Database\Seeder;
use Gerardojbaez\GeoData\Models\Country;
use Gerardojbaez\GeoData\Models\Region;
use Gerardojbaez\GeoData\Models\City;

class GuatemalaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Country::create($this->country());
        Region::insert($this->regions());

        if ($this->cities() > 4000)
        {
            foreach (array_chunk($this->cities(), 3500) as $chunk)
                City::insert($chunk);
        }
        else
        {
            City::insert($this->cities());
        }
    }

        /**
     * Get country.
     *
     * @return array
     */
    public function country()
    {
    	return ['code' => 'GT', 'name' => 'Guatemala', 'slug' => 'guatemala'];
    }

    /**
     * Get country regions.
     *
     * @return array
     */
    public function regions()
    {
    	return [
            ['id' => 707158, 'country_code' => 'GT', 'name' => 'Jalapa', 'active' => 1, 'slug' => 'jalapa'],
            ['id' => 707159, 'country_code' => 'GT', 'name' => 'Jutiapa', 'active' => 1, 'slug' => 'jutiapa'],
            ['id' => 707160, 'country_code' => 'GT', 'name' => 'Quetzaltenango', 'active' => 1, 'slug' => 'quetzaltenango'],
            ['id' => 707161, 'country_code' => 'GT', 'name' => 'Retalhuleu', 'active' => 1, 'slug' => 'retalhuleu'],
            ['id' => 707162, 'country_code' => 'GT', 'name' => 'Sacatepéquez', 'active' => 1, 'slug' => 'sacatepequez'],
            ['id' => 707165, 'country_code' => 'GT', 'name' => 'Sololá', 'active' => 1, 'slug' => 'solola'],
            ['id' => 707166, 'country_code' => 'GT', 'name' => 'Suchitepéquez', 'active' => 1, 'slug' => 'suchitepequez'],
            ['id' => 707167, 'country_code' => 'GT', 'name' => 'Totonicapán', 'active' => 1, 'slug' => 'totonicapan'],
            ['id' => 707168, 'country_code' => 'GT', 'name' => 'Zacapa', 'active' => 1, 'slug' => 'zacapa'],
            ['id' => 707169, 'country_code' => 'GT', 'name' => 'Alta Verapaz', 'active' => 1, 'slug' => 'alta-verapaz'],
            ['id' => 707170, 'country_code' => 'GT', 'name' => 'Baja Verapaz', 'active' => 1, 'slug' => 'baja-verapaz'],
            ['id' => 707171, 'country_code' => 'GT', 'name' => 'Chimaltenango', 'active' => 1, 'slug' => 'chimaltenango'],
            ['id' => 707172, 'country_code' => 'GT', 'name' => 'Chiquimula', 'active' => 1, 'slug' => 'chiquimula'],
            ['id' => 707173, 'country_code' => 'GT', 'name' => 'Petén', 'active' => 1, 'slug' => 'peten'],
            ['id' => 707174, 'country_code' => 'GT', 'name' => 'El Progreso', 'active' => 1, 'slug' => 'el-progreso'],
            ['id' => 707175, 'country_code' => 'GT', 'name' => 'Quiché', 'active' => 1, 'slug' => 'quiche'],
            ['id' => 707176, 'country_code' => 'GT', 'name' => 'Escuintla', 'active' => 1, 'slug' => 'escuintla'],
            ['id' => 707178, 'country_code' => 'GT', 'name' => 'Huehuetenango', 'active' => 1, 'slug' => 'huehuetenango'],
            ['id' => 707179, 'country_code' => 'GT', 'name' => 'Izabal', 'active' => 1, 'slug' => 'izabal'],
            ['id' => 712100, 'country_code' => 'GT', 'name' => 'Guatemala', 'active' => 1, 'slug' => 'guatemala'],
            ['id' => 712101, 'country_code' => 'GT', 'name' => 'San Marcos', 'active' => 1, 'slug' => 'san-marcos'],
            ['id' => 712102, 'country_code' => 'GT', 'name' => 'Santa Rosa', 'active' => 1, 'slug' => 'santa-rosa']
    	];
    }

    /**
     * Get region cities.
     *
     * @return array
     */
    public function cities()
    {
    	return [
            ['id' => 25176, 'region_id' => 707158, 'country_code' => 'GT', 'name' => 'Jalapa', 'active' => 1, 'slug' => 'jalapa'],
            ['id' => 25177, 'region_id' => 707158, 'country_code' => 'GT', 'name' => 'San Pedro Pinula', 'active' => 1, 'slug' => 'san-pedro-pinula'],
            ['id' => 25178, 'region_id' => 707158, 'country_code' => 'GT', 'name' => 'San Luis Jilotepeque', 'active' => 1, 'slug' => 'san-luis-jilotepeque'],
            ['id' => 25179, 'region_id' => 707158, 'country_code' => 'GT', 'name' => 'San Manuel Chaparrón', 'active' => 1, 'slug' => 'san-manuel-chaparron'],
            ['id' => 25180, 'region_id' => 707158, 'country_code' => 'GT', 'name' => 'San Carlos Alzatate', 'active' => 1, 'slug' => 'san-carlos-alzatate'],
            ['id' => 25181, 'region_id' => 707158, 'country_code' => 'GT', 'name' => 'Monjas', 'active' => 1, 'slug' => 'monjas'],
            ['id' => 25182, 'region_id' => 707158, 'country_code' => 'GT', 'name' => 'Mataquescuintla', 'active' => 1, 'slug' => 'mataquescuintla'],
            ['id' => 25183, 'region_id' => 707159, 'country_code' => 'GT', 'name' => 'Agua Blanca', 'active' => 1, 'slug' => 'agua-blanca'],
            ['id' => 25184, 'region_id' => 707159, 'country_code' => 'GT', 'name' => 'Asunción Mita', 'active' => 1, 'slug' => 'asuncion-mita'],
            ['id' => 25185, 'region_id' => 707159, 'country_code' => 'GT', 'name' => 'Atescatempa', 'active' => 1, 'slug' => 'atescatempa'],
            ['id' => 25186, 'region_id' => 707159, 'country_code' => 'GT', 'name' => 'Comapa', 'active' => 1, 'slug' => 'comapa'],
            ['id' => 25187, 'region_id' => 707159, 'country_code' => 'GT', 'name' => 'Conguaco', 'active' => 1, 'slug' => 'conguaco'],
            ['id' => 25188, 'region_id' => 707159, 'country_code' => 'GT', 'name' => 'El Adelanto', 'active' => 1, 'slug' => 'el-adelanto'],
            ['id' => 25189, 'region_id' => 707159, 'country_code' => 'GT', 'name' => 'El Progreso', 'active' => 1, 'slug' => 'el-progreso'],
            ['id' => 25190, 'region_id' => 707159, 'country_code' => 'GT', 'name' => 'Jalpatagua', 'active' => 1, 'slug' => 'jalpatagua'],
            ['id' => 25191, 'region_id' => 707159, 'country_code' => 'GT', 'name' => 'Jerez', 'active' => 1, 'slug' => 'jerez'],
            ['id' => 25192, 'region_id' => 707159, 'country_code' => 'GT', 'name' => 'Jutiapa', 'active' => 1, 'slug' => 'jutiapa'],
            ['id' => 25193, 'region_id' => 707159, 'country_code' => 'GT', 'name' => 'Moyuta', 'active' => 1, 'slug' => 'moyuta'],
            ['id' => 25194, 'region_id' => 707159, 'country_code' => 'GT', 'name' => 'Pasaco', 'active' => 1, 'slug' => 'pasaco'],
            ['id' => 25195, 'region_id' => 707159, 'country_code' => 'GT', 'name' => 'Quesada', 'active' => 1, 'slug' => 'quesada'],
            ['id' => 25196, 'region_id' => 707159, 'country_code' => 'GT', 'name' => 'San José Acatempa', 'active' => 1, 'slug' => 'san-jose-acatempa'],
            ['id' => 25197, 'region_id' => 707159, 'country_code' => 'GT', 'name' => 'Santa Catarina Mita', 'active' => 1, 'slug' => 'santa-catarina-mita'],
            ['id' => 25198, 'region_id' => 707159, 'country_code' => 'GT', 'name' => 'Yupiltepeque', 'active' => 1, 'slug' => 'yupiltepeque'],
            ['id' => 25199, 'region_id' => 707159, 'country_code' => 'GT', 'name' => 'Zapotitlán', 'active' => 1, 'slug' => 'zapotitlan'],
            ['id' => 25200, 'region_id' => 707160, 'country_code' => 'GT', 'name' => 'Almolonga', 'active' => 1, 'slug' => 'almolonga'],
            ['id' => 25201, 'region_id' => 707160, 'country_code' => 'GT', 'name' => 'Cabricán', 'active' => 1, 'slug' => 'cabrican'],
            ['id' => 25202, 'region_id' => 707160, 'country_code' => 'GT', 'name' => 'Cajolá', 'active' => 1, 'slug' => 'cajola'],
            ['id' => 25203, 'region_id' => 707160, 'country_code' => 'GT', 'name' => 'Cantel', 'active' => 1, 'slug' => 'cantel'],
            ['id' => 25204, 'region_id' => 707160, 'country_code' => 'GT', 'name' => 'Coatepeque', 'active' => 1, 'slug' => 'coatepeque'],
            ['id' => 25205, 'region_id' => 707160, 'country_code' => 'GT', 'name' => 'Colomba', 'active' => 1, 'slug' => 'colomba'],
            ['id' => 25206, 'region_id' => 707160, 'country_code' => 'GT', 'name' => 'Concepción Chiquirichapa', 'active' => 1, 'slug' => 'concepcion-chiquirichapa'],
            ['id' => 25207, 'region_id' => 707160, 'country_code' => 'GT', 'name' => 'El Palmar', 'active' => 1, 'slug' => 'el-palmar'],
            ['id' => 25208, 'region_id' => 707160, 'country_code' => 'GT', 'name' => 'Flores Costa Cuca', 'active' => 1, 'slug' => 'flores-costa-cuca'],
            ['id' => 25209, 'region_id' => 707160, 'country_code' => 'GT', 'name' => 'Génova', 'active' => 1, 'slug' => 'genova'],
            ['id' => 25210, 'region_id' => 707160, 'country_code' => 'GT', 'name' => 'Huitán', 'active' => 1, 'slug' => 'huitan'],
            ['id' => 25211, 'region_id' => 707160, 'country_code' => 'GT', 'name' => 'La Esperanza', 'active' => 1, 'slug' => 'la-esperanza'],
            ['id' => 25212, 'region_id' => 707160, 'country_code' => 'GT', 'name' => 'Olintepeque', 'active' => 1, 'slug' => 'olintepeque'],
            ['id' => 25213, 'region_id' => 707160, 'country_code' => 'GT', 'name' => 'Ostuncalco', 'active' => 1, 'slug' => 'ostuncalco'],
            ['id' => 25214, 'region_id' => 707160, 'country_code' => 'GT', 'name' => 'Palestina de Los Altos', 'active' => 1, 'slug' => 'palestina-de-los-altos'],
            ['id' => 25215, 'region_id' => 707160, 'country_code' => 'GT', 'name' => 'Quetzaltenango', 'active' => 1, 'slug' => 'quetzaltenango'],
            ['id' => 25216, 'region_id' => 707160, 'country_code' => 'GT', 'name' => 'Salcajá', 'active' => 1, 'slug' => 'salcaja'],
            ['id' => 25217, 'region_id' => 707160, 'country_code' => 'GT', 'name' => 'San Carlos Sija', 'active' => 1, 'slug' => 'san-carlos-sija'],
            ['id' => 25218, 'region_id' => 707160, 'country_code' => 'GT', 'name' => 'San Francisco la Unión', 'active' => 1, 'slug' => 'san-francisco-la-union'],
            ['id' => 25219, 'region_id' => 707160, 'country_code' => 'GT', 'name' => 'San Martín Sacatepéquez', 'active' => 1, 'slug' => 'san-martin-sacatepequez'],
            ['id' => 25220, 'region_id' => 707160, 'country_code' => 'GT', 'name' => 'San Mateo', 'active' => 1, 'slug' => 'san-mateo'],
            ['id' => 25221, 'region_id' => 707160, 'country_code' => 'GT', 'name' => 'San Miguel Sigüilá', 'active' => 1, 'slug' => 'san-miguel-siguila'],
            ['id' => 25222, 'region_id' => 707160, 'country_code' => 'GT', 'name' => 'Sibilia', 'active' => 1, 'slug' => 'sibilia'],
            ['id' => 25223, 'region_id' => 707160, 'country_code' => 'GT', 'name' => 'Zuni', 'active' => 1, 'slug' => 'zuni'],
            ['id' => 25224, 'region_id' => 707161, 'country_code' => 'GT', 'name' => 'Champerico', 'active' => 1, 'slug' => 'champerico'],
            ['id' => 25225, 'region_id' => 707161, 'country_code' => 'GT', 'name' => 'El Asintal.', 'active' => 1, 'slug' => 'el-asintal'],
            ['id' => 25226, 'region_id' => 707161, 'country_code' => 'GT', 'name' => 'Nuevo San Carlos', 'active' => 1, 'slug' => 'nuevo-san-carlos'],
            ['id' => 25227, 'region_id' => 707161, 'country_code' => 'GT', 'name' => 'Retalhuleu', 'active' => 1, 'slug' => 'retalhuleu'],
            ['id' => 25228, 'region_id' => 707161, 'country_code' => 'GT', 'name' => 'San Andrés Villa Seca', 'active' => 1, 'slug' => 'san-andres-villa-seca'],
            ['id' => 25229, 'region_id' => 707161, 'country_code' => 'GT', 'name' => 'San Martín Zapotitlán', 'active' => 1, 'slug' => 'san-martin-zapotitlan'],
            ['id' => 25230, 'region_id' => 707161, 'country_code' => 'GT', 'name' => 'San Felipe', 'active' => 1, 'slug' => 'san-felipe'],
            ['id' => 25231, 'region_id' => 707161, 'country_code' => 'GT', 'name' => 'San Sebastián', 'active' => 1, 'slug' => 'san-sebastian'],
            ['id' => 25232, 'region_id' => 707161, 'country_code' => 'GT', 'name' => 'Santa Cruz Muluá', 'active' => 1, 'slug' => 'santa-cruz-mulua'],
            ['id' => 25233, 'region_id' => 707162, 'country_code' => 'GT', 'name' => 'Alotenango', 'active' => 1, 'slug' => 'alotenango'],
            ['id' => 25234, 'region_id' => 707162, 'country_code' => 'GT', 'name' => 'Antigua Guatemala', 'active' => 1, 'slug' => 'antigua-guatemala'],
            ['id' => 25235, 'region_id' => 707162, 'country_code' => 'GT', 'name' => 'Ciudad Vieja', 'active' => 1, 'slug' => 'ciudad-vieja'],
            ['id' => 25236, 'region_id' => 707162, 'country_code' => 'GT', 'name' => 'Jocotenango', 'active' => 1, 'slug' => 'jocotenango'],
            ['id' => 25237, 'region_id' => 707162, 'country_code' => 'GT', 'name' => 'Magdalena Milpas Altas', 'active' => 1, 'slug' => 'magdalena-milpas-altas'],
            ['id' => 25238, 'region_id' => 707162, 'country_code' => 'GT', 'name' => 'Pastores', 'active' => 1, 'slug' => 'pastores'],
            ['id' => 25239, 'region_id' => 707162, 'country_code' => 'GT', 'name' => 'San Antonio Aguas Calientes', 'active' => 1, 'slug' => 'san-antonio-aguas-calientes'],
            ['id' => 25240, 'region_id' => 707162, 'country_code' => 'GT', 'name' => 'San Bartolomé Milpas Altas', 'active' => 1, 'slug' => 'san-bartolome-milpas-altas'],
            ['id' => 25241, 'region_id' => 707162, 'country_code' => 'GT', 'name' => 'San Lucas Sacatepéquez', 'active' => 1, 'slug' => 'san-lucas-sacatepequez'],
            ['id' => 25242, 'region_id' => 707162, 'country_code' => 'GT', 'name' => 'San Miguel Dueñas', 'active' => 1, 'slug' => 'san-miguel-duenas'],
            ['id' => 25243, 'region_id' => 707162, 'country_code' => 'GT', 'name' => 'Santa Catarina Barahona', 'active' => 1, 'slug' => 'santa-catarina-barahona'],
            ['id' => 25244, 'region_id' => 707162, 'country_code' => 'GT', 'name' => 'Santa Lucía Milpas Altas', 'active' => 1, 'slug' => 'santa-lucia-milpas-altas'],
            ['id' => 25245, 'region_id' => 707162, 'country_code' => 'GT', 'name' => 'Santa María de Jesús', 'active' => 1, 'slug' => 'santa-maria-de-jesus'],
            ['id' => 25246, 'region_id' => 707162, 'country_code' => 'GT', 'name' => 'Santiago Sacatepéquez', 'active' => 1, 'slug' => 'santiago-sacatepequez'],
            ['id' => 25247, 'region_id' => 707162, 'country_code' => 'GT', 'name' => 'Santo Domingo Xenacoj', 'active' => 1, 'slug' => 'santo-domingo-xenacoj'],
            ['id' => 25248, 'region_id' => 707162, 'country_code' => 'GT', 'name' => 'Sumpango', 'active' => 1, 'slug' => 'sumpango'],
            ['id' => 25292, 'region_id' => 707165, 'country_code' => 'GT', 'name' => 'Concepción', 'active' => 1, 'slug' => 'concepcion'],
            ['id' => 25293, 'region_id' => 707165, 'country_code' => 'GT', 'name' => 'Nahualá', 'active' => 1, 'slug' => 'nahuala'],
            ['id' => 25294, 'region_id' => 707165, 'country_code' => 'GT', 'name' => 'Panajachel', 'active' => 1, 'slug' => 'panajachel'],
            ['id' => 25295, 'region_id' => 707165, 'country_code' => 'GT', 'name' => 'San Andrés Semetabaj', 'active' => 1, 'slug' => 'san-andres-semetabaj'],
            ['id' => 25296, 'region_id' => 707165, 'country_code' => 'GT', 'name' => 'San Antonio Palopó', 'active' => 1, 'slug' => 'san-antonio-palopo'],
            ['id' => 25297, 'region_id' => 707165, 'country_code' => 'GT', 'name' => 'San José Chacayá', 'active' => 1, 'slug' => 'san-jose-chacaya'],
            ['id' => 25298, 'region_id' => 707165, 'country_code' => 'GT', 'name' => 'San Juan la Laguna', 'active' => 1, 'slug' => 'san-juan-la-laguna'],
            ['id' => 25299, 'region_id' => 707165, 'country_code' => 'GT', 'name' => 'San Lucas Tolimán', 'active' => 1, 'slug' => 'san-lucas-toliman'],
            ['id' => 25300, 'region_id' => 707165, 'country_code' => 'GT', 'name' => 'San Marcos la Laguna', 'active' => 1, 'slug' => 'san-marcos-la-laguna'],
            ['id' => 25301, 'region_id' => 707165, 'country_code' => 'GT', 'name' => 'San Pablo la Laguna', 'active' => 1, 'slug' => 'san-pablo-la-laguna'],
            ['id' => 25302, 'region_id' => 707165, 'country_code' => 'GT', 'name' => 'San Pedro la Laguna', 'active' => 1, 'slug' => 'san-pedro-la-laguna'],
            ['id' => 25303, 'region_id' => 707165, 'country_code' => 'GT', 'name' => 'Santa Catarina Ixtahuacan', 'active' => 1, 'slug' => 'santa-catarina-ixtahuacan'],
            ['id' => 25304, 'region_id' => 707165, 'country_code' => 'GT', 'name' => 'Santa Catarina Palopó', 'active' => 1, 'slug' => 'santa-catarina-palopo'],
            ['id' => 25305, 'region_id' => 707165, 'country_code' => 'GT', 'name' => 'Santa Clara la Laguna', 'active' => 1, 'slug' => 'santa-clara-la-laguna'],
            ['id' => 25306, 'region_id' => 707165, 'country_code' => 'GT', 'name' => 'Santa Cruz la Laguna', 'active' => 1, 'slug' => 'santa-cruz-la-laguna'],
            ['id' => 25307, 'region_id' => 707165, 'country_code' => 'GT', 'name' => 'Santa Lucía Utatlán', 'active' => 1, 'slug' => 'santa-lucia-utatlan'],
            ['id' => 25308, 'region_id' => 707165, 'country_code' => 'GT', 'name' => 'Santa María Visitación', 'active' => 1, 'slug' => 'santa-maria-visitacion'],
            ['id' => 25309, 'region_id' => 707165, 'country_code' => 'GT', 'name' => 'Santiago Atitlán.', 'active' => 1, 'slug' => 'santiago-atitlan'],
            ['id' => 25310, 'region_id' => 707165, 'country_code' => 'GT', 'name' => 'Sololá', 'active' => 1, 'slug' => 'solola'],
            ['id' => 25311, 'region_id' => 707166, 'country_code' => 'GT', 'name' => 'Chicacao', 'active' => 1, 'slug' => 'chicacao'],
            ['id' => 25312, 'region_id' => 707166, 'country_code' => 'GT', 'name' => 'Cuyotenango', 'active' => 1, 'slug' => 'cuyotenango'],
            ['id' => 25313, 'region_id' => 707166, 'country_code' => 'GT', 'name' => 'Mazatenango', 'active' => 1, 'slug' => 'mazatenango'],
            ['id' => 25314, 'region_id' => 707166, 'country_code' => 'GT', 'name' => 'Patulul', 'active' => 1, 'slug' => 'patulul'],
            ['id' => 25315, 'region_id' => 707166, 'country_code' => 'GT', 'name' => 'Pueblo Nuevo', 'active' => 1, 'slug' => 'pueblo-nuevo'],
            ['id' => 25316, 'region_id' => 707166, 'country_code' => 'GT', 'name' => 'Río Bravo', 'active' => 1, 'slug' => 'rio-bravo'],
            ['id' => 25317, 'region_id' => 707166, 'country_code' => 'GT', 'name' => 'Samayac', 'active' => 1, 'slug' => 'samayac'],
            ['id' => 25318, 'region_id' => 707166, 'country_code' => 'GT', 'name' => 'San Antonio Suchitepéquez', 'active' => 1, 'slug' => 'san-antonio-suchitepequez'],
            ['id' => 25319, 'region_id' => 707166, 'country_code' => 'GT', 'name' => 'San Bernardino', 'active' => 1, 'slug' => 'san-bernardino'],
            ['id' => 25320, 'region_id' => 707166, 'country_code' => 'GT', 'name' => 'San José el Ídolo', 'active' => 1, 'slug' => 'san-jose-el-idolo'],
            ['id' => 25321, 'region_id' => 707166, 'country_code' => 'GT', 'name' => 'San Francisco Zapotitlán', 'active' => 1, 'slug' => 'san-francisco-zapotitlan'],
            ['id' => 25322, 'region_id' => 707166, 'country_code' => 'GT', 'name' => 'San Gabriel', 'active' => 1, 'slug' => 'san-gabriel'],
            ['id' => 25323, 'region_id' => 707166, 'country_code' => 'GT', 'name' => 'San Juan Bautista', 'active' => 1, 'slug' => 'san-juan-bautista'],
            ['id' => 25324, 'region_id' => 707166, 'country_code' => 'GT', 'name' => 'San Lorenzo', 'active' => 1, 'slug' => 'san-lorenzo'],
            ['id' => 25325, 'region_id' => 707166, 'country_code' => 'GT', 'name' => 'San Miguel Panán', 'active' => 1, 'slug' => 'san-miguel-panan'],
            ['id' => 25326, 'region_id' => 707166, 'country_code' => 'GT', 'name' => 'San Pablo Jocopilas', 'active' => 1, 'slug' => 'san-pablo-jocopilas'],
            ['id' => 25327, 'region_id' => 707166, 'country_code' => 'GT', 'name' => 'Santa Barbara', 'active' => 1, 'slug' => 'santa-barbara'],
            ['id' => 25328, 'region_id' => 707166, 'country_code' => 'GT', 'name' => 'Santo Domingo Suchitepequez', 'active' => 1, 'slug' => 'santo-domingo-suchitepequez'],
            ['id' => 25329, 'region_id' => 707166, 'country_code' => 'GT', 'name' => 'Santo Tomas la Unión', 'active' => 1, 'slug' => 'santo-tomas-la-union'],
            ['id' => 25330, 'region_id' => 707166, 'country_code' => 'GT', 'name' => 'Zunilito', 'active' => 1, 'slug' => 'zunilito'],
            ['id' => 25331, 'region_id' => 707167, 'country_code' => 'GT', 'name' => 'Momostenango', 'active' => 1, 'slug' => 'momostenango'],
            ['id' => 25332, 'region_id' => 707167, 'country_code' => 'GT', 'name' => 'San Andrés Xecul', 'active' => 1, 'slug' => 'san-andres-xecul'],
            ['id' => 25333, 'region_id' => 707167, 'country_code' => 'GT', 'name' => 'San Bartolo.', 'active' => 1, 'slug' => 'san-bartolo'],
            ['id' => 25334, 'region_id' => 707167, 'country_code' => 'GT', 'name' => 'San Cristóbal Totonicapán', 'active' => 1, 'slug' => 'san-cristobal-totonicapan'],
            ['id' => 25335, 'region_id' => 707167, 'country_code' => 'GT', 'name' => 'San Francisco el Alto', 'active' => 1, 'slug' => 'san-francisco-el-alto'],
            ['id' => 25336, 'region_id' => 707167, 'country_code' => 'GT', 'name' => 'Santa Lucía la Reforma', 'active' => 1, 'slug' => 'santa-lucia-la-reforma'],
            ['id' => 25337, 'region_id' => 707167, 'country_code' => 'GT', 'name' => 'Santa María Chiquimula', 'active' => 1, 'slug' => 'santa-maria-chiquimula'],
            ['id' => 25338, 'region_id' => 707167, 'country_code' => 'GT', 'name' => 'Totonicapán', 'active' => 1, 'slug' => 'totonicapan'],
            ['id' => 25339, 'region_id' => 707168, 'country_code' => 'GT', 'name' => 'Cabañas', 'active' => 1, 'slug' => 'cabanas'],
            ['id' => 25340, 'region_id' => 707168, 'country_code' => 'GT', 'name' => 'Estanzuela', 'active' => 1, 'slug' => 'estanzuela'],
            ['id' => 25341, 'region_id' => 707168, 'country_code' => 'GT', 'name' => 'Gualán', 'active' => 1, 'slug' => 'gualan'],
            ['id' => 25342, 'region_id' => 707168, 'country_code' => 'GT', 'name' => 'Huité', 'active' => 1, 'slug' => 'huite'],
            ['id' => 25343, 'region_id' => 707168, 'country_code' => 'GT', 'name' => 'La Unión', 'active' => 1, 'slug' => 'la-union'],
            ['id' => 25344, 'region_id' => 707168, 'country_code' => 'GT', 'name' => 'Río Hondo', 'active' => 1, 'slug' => 'rio-hondo'],
            ['id' => 25345, 'region_id' => 707168, 'country_code' => 'GT', 'name' => 'San Diego', 'active' => 1, 'slug' => 'san-diego'],
            ['id' => 25346, 'region_id' => 707168, 'country_code' => 'GT', 'name' => 'Teculután', 'active' => 1, 'slug' => 'teculutan'],
            ['id' => 25347, 'region_id' => 707168, 'country_code' => 'GT', 'name' => 'Usumatlán', 'active' => 1, 'slug' => 'usumatlan'],
            ['id' => 25348, 'region_id' => 707168, 'country_code' => 'GT', 'name' => 'Zacapa', 'active' => 1, 'slug' => 'zacapa'],
            ['id' => 25015, 'region_id' => 707169, 'country_code' => 'GT', 'name' => 'Cobán', 'active' => 1, 'slug' => 'coban'],
            ['id' => 25016, 'region_id' => 707169, 'country_code' => 'GT', 'name' => 'San Pedro Carchá', 'active' => 1, 'slug' => 'san-pedro-carcha'],
            ['id' => 25017, 'region_id' => 707169, 'country_code' => 'GT', 'name' => 'San Juan Chamelco', 'active' => 1, 'slug' => 'san-juan-chamelco'],
            ['id' => 25018, 'region_id' => 707169, 'country_code' => 'GT', 'name' => 'San Cristóbal Verapaz', 'active' => 1, 'slug' => 'san-cristobal-verapaz'],
            ['id' => 25019, 'region_id' => 707169, 'country_code' => 'GT', 'name' => 'Tactic', 'active' => 1, 'slug' => 'tactic'],
            ['id' => 25020, 'region_id' => 707169, 'country_code' => 'GT', 'name' => 'Tucurú', 'active' => 1, 'slug' => 'tucuru'],
            ['id' => 25021, 'region_id' => 707169, 'country_code' => 'GT', 'name' => 'Tamahú', 'active' => 1, 'slug' => 'tamahu'],
            ['id' => 25022, 'region_id' => 707169, 'country_code' => 'GT', 'name' => 'San Miguel Tucurú', 'active' => 1, 'slug' => 'san-miguel-tucuru'],
            ['id' => 25023, 'region_id' => 707169, 'country_code' => 'GT', 'name' => 'Santa María Cahabón', 'active' => 1, 'slug' => 'santa-maria-cahabon'],
            ['id' => 25024, 'region_id' => 707169, 'country_code' => 'GT', 'name' => 'Panzós', 'active' => 1, 'slug' => 'panzos'],
            ['id' => 25025, 'region_id' => 707169, 'country_code' => 'GT', 'name' => 'Senahú', 'active' => 1, 'slug' => 'senahu'],
            ['id' => 25026, 'region_id' => 707169, 'country_code' => 'GT', 'name' => 'Cahabón', 'active' => 1, 'slug' => 'cahabon'],
            ['id' => 25027, 'region_id' => 707169, 'country_code' => 'GT', 'name' => 'Lanquin', 'active' => 1, 'slug' => 'lanquin'],
            ['id' => 25028, 'region_id' => 707169, 'country_code' => 'GT', 'name' => 'Chahal', 'active' => 1, 'slug' => 'chahal'],
            ['id' => 25029, 'region_id' => 707169, 'country_code' => 'GT', 'name' => 'Fray Bartolomé de las Casas', 'active' => 1, 'slug' => 'fray-bartolome-de-las-casas'],
            ['id' => 25030, 'region_id' => 707169, 'country_code' => 'GT', 'name' => 'Chisec', 'active' => 1, 'slug' => 'chisec'],
            ['id' => 25031, 'region_id' => 707169, 'country_code' => 'GT', 'name' => 'Santa Cruz Verapaz', 'active' => 1, 'slug' => 'santa-cruz-verapaz'],
            ['id' => 25032, 'region_id' => 707169, 'country_code' => 'GT', 'name' => 'Santa Catalina la Tinta', 'active' => 1, 'slug' => 'santa-catalina-la-tinta'],
            ['id' => 25033, 'region_id' => 707170, 'country_code' => 'GT', 'name' => 'Cubulco', 'active' => 1, 'slug' => 'cubulco'],
            ['id' => 25034, 'region_id' => 707170, 'country_code' => 'GT', 'name' => 'Santa Cruz el Chol', 'active' => 1, 'slug' => 'santa-cruz-el-chol'],
            ['id' => 25035, 'region_id' => 707170, 'country_code' => 'GT', 'name' => 'Granados', 'active' => 1, 'slug' => 'granados'],
            ['id' => 25036, 'region_id' => 707170, 'country_code' => 'GT', 'name' => 'Purulhá', 'active' => 1, 'slug' => 'purulha'],
            ['id' => 25037, 'region_id' => 707170, 'country_code' => 'GT', 'name' => 'Rabinal', 'active' => 1, 'slug' => 'rabinal'],
            ['id' => 25038, 'region_id' => 707170, 'country_code' => 'GT', 'name' => 'Salamá', 'active' => 1, 'slug' => 'salama'],
            ['id' => 25039, 'region_id' => 707170, 'country_code' => 'GT', 'name' => 'San Miguel Chicaj', 'active' => 1, 'slug' => 'san-miguel-chicaj'],
            ['id' => 25040, 'region_id' => 707170, 'country_code' => 'GT', 'name' => 'San Jerónimo', 'active' => 1, 'slug' => 'san-jeronimo'],
            ['id' => 25041, 'region_id' => 707171, 'country_code' => 'GT', 'name' => 'Chimaltenango', 'active' => 1, 'slug' => 'chimaltenango'],
            ['id' => 25042, 'region_id' => 707171, 'country_code' => 'GT', 'name' => 'San José Poaquíl', 'active' => 1, 'slug' => 'san-jose-poaquil'],
            ['id' => 25043, 'region_id' => 707171, 'country_code' => 'GT', 'name' => 'San Martín Jilotepeque', 'active' => 1, 'slug' => 'san-martin-jilotepeque'],
            ['id' => 25044, 'region_id' => 707171, 'country_code' => 'GT', 'name' => 'San Pedro Yepocapa', 'active' => 1, 'slug' => 'san-pedro-yepocapa'],
            ['id' => 25045, 'region_id' => 707171, 'country_code' => 'GT', 'name' => 'Santa Apolonia', 'active' => 1, 'slug' => 'santa-apolonia'],
            ['id' => 25046, 'region_id' => 707171, 'country_code' => 'GT', 'name' => 'Tecpán Guatemala', 'active' => 1, 'slug' => 'tecpan-guatemala'],
            ['id' => 25047, 'region_id' => 707171, 'country_code' => 'GT', 'name' => 'Patzún', 'active' => 1, 'slug' => 'patzun'],
            ['id' => 25048, 'region_id' => 707171, 'country_code' => 'GT', 'name' => 'Pochuta', 'active' => 1, 'slug' => 'pochuta'],
            ['id' => 25049, 'region_id' => 707171, 'country_code' => 'GT', 'name' => 'Patzicía', 'active' => 1, 'slug' => 'patzicia'],
            ['id' => 25050, 'region_id' => 707171, 'country_code' => 'GT', 'name' => 'Santa Cruz Balanyá', 'active' => 1, 'slug' => 'santa-cruz-balanya'],
            ['id' => 25051, 'region_id' => 707171, 'country_code' => 'GT', 'name' => 'Acatenango', 'active' => 1, 'slug' => 'acatenango'],
            ['id' => 25052, 'region_id' => 707171, 'country_code' => 'GT', 'name' => 'Yepocapa', 'active' => 1, 'slug' => 'yepocapa'],
            ['id' => 25053, 'region_id' => 707171, 'country_code' => 'GT', 'name' => 'San Andrés Itzapa', 'active' => 1, 'slug' => 'san-andres-itzapa'],
            ['id' => 25054, 'region_id' => 707171, 'country_code' => 'GT', 'name' => 'Parramos', 'active' => 1, 'slug' => 'parramos'],
            ['id' => 25055, 'region_id' => 707171, 'country_code' => 'GT', 'name' => 'Zaragoza', 'active' => 1, 'slug' => 'zaragoza'],
            ['id' => 25056, 'region_id' => 707171, 'country_code' => 'GT', 'name' => 'El Tejar', 'active' => 1, 'slug' => 'el-tejar'],
            ['id' => 25057, 'region_id' => 707172, 'country_code' => 'GT', 'name' => 'Camotán', 'active' => 1, 'slug' => 'camotan'],
            ['id' => 25058, 'region_id' => 707172, 'country_code' => 'GT', 'name' => 'Chiquimula', 'active' => 1, 'slug' => 'chiquimula'],
            ['id' => 25059, 'region_id' => 707172, 'country_code' => 'GT', 'name' => 'Concepción Las Minas', 'active' => 1, 'slug' => 'concepcion-las-minas'],
            ['id' => 25060, 'region_id' => 707172, 'country_code' => 'GT', 'name' => 'Esquipulas', 'active' => 1, 'slug' => 'esquipulas'],
            ['id' => 25061, 'region_id' => 707172, 'country_code' => 'GT', 'name' => 'Ipala', 'active' => 1, 'slug' => 'ipala'],
            ['id' => 25062, 'region_id' => 707172, 'country_code' => 'GT', 'name' => 'Jocotán', 'active' => 1, 'slug' => 'jocotan'],
            ['id' => 25063, 'region_id' => 707172, 'country_code' => 'GT', 'name' => 'Olopa', 'active' => 1, 'slug' => 'olopa'],
            ['id' => 25064, 'region_id' => 707172, 'country_code' => 'GT', 'name' => 'Quezaltepeque', 'active' => 1, 'slug' => 'quezaltepeque'],
            ['id' => 25065, 'region_id' => 707172, 'country_code' => 'GT', 'name' => 'San José la Arada', 'active' => 1, 'slug' => 'san-jose-la-arada'],
            ['id' => 25066, 'region_id' => 707172, 'country_code' => 'GT', 'name' => 'San Juan Ermita', 'active' => 1, 'slug' => 'san-juan-ermita'],
            ['id' => 25067, 'region_id' => 707172, 'country_code' => 'GT', 'name' => 'San Jacinto', 'active' => 1, 'slug' => 'san-jacinto'],
            ['id' => 25068, 'region_id' => 707173, 'country_code' => 'GT', 'name' => 'Dolores', 'active' => 1, 'slug' => 'dolores'],
            ['id' => 25069, 'region_id' => 707173, 'country_code' => 'GT', 'name' => 'La Libertad', 'active' => 1, 'slug' => 'la-libertad'],
            ['id' => 25070, 'region_id' => 707173, 'country_code' => 'GT', 'name' => 'Flores', 'active' => 1, 'slug' => 'flores'],
            ['id' => 25071, 'region_id' => 707173, 'country_code' => 'GT', 'name' => 'Melchor de Mencos', 'active' => 1, 'slug' => 'melchor-de-mencos'],
            ['id' => 25072, 'region_id' => 707173, 'country_code' => 'GT', 'name' => 'Poptún', 'active' => 1, 'slug' => 'poptun'],
            ['id' => 25073, 'region_id' => 707173, 'country_code' => 'GT', 'name' => 'San Andrés', 'active' => 1, 'slug' => 'san-andres'],
            ['id' => 25074, 'region_id' => 707173, 'country_code' => 'GT', 'name' => 'San Benito', 'active' => 1, 'slug' => 'san-benito'],
            ['id' => 25075, 'region_id' => 707173, 'country_code' => 'GT', 'name' => 'San Francisco', 'active' => 1, 'slug' => 'san-francisco'],
            ['id' => 25076, 'region_id' => 707173, 'country_code' => 'GT', 'name' => 'San José', 'active' => 1, 'slug' => 'san-jose'],
            ['id' => 25077, 'region_id' => 707173, 'country_code' => 'GT', 'name' => 'San Luis', 'active' => 1, 'slug' => 'san-luis'],
            ['id' => 25078, 'region_id' => 707173, 'country_code' => 'GT', 'name' => 'Santa Ana', 'active' => 1, 'slug' => 'santa-ana'],
            ['id' => 25079, 'region_id' => 707173, 'country_code' => 'GT', 'name' => 'Sayaxché', 'active' => 1, 'slug' => 'sayaxche'],
            ['id' => 25080, 'region_id' => 707174, 'country_code' => 'GT', 'name' => 'Guastatoya', 'active' => 1, 'slug' => 'guastatoya'],
            ['id' => 25081, 'region_id' => 707174, 'country_code' => 'GT', 'name' => 'Morazán', 'active' => 1, 'slug' => 'morazan'],
            ['id' => 25082, 'region_id' => 707174, 'country_code' => 'GT', 'name' => 'San Agustín Acasaguastlán', 'active' => 1, 'slug' => 'san-agustin-acasaguastlan'],
            ['id' => 25083, 'region_id' => 707174, 'country_code' => 'GT', 'name' => 'San Cristóbal Acasaguastlán', 'active' => 1, 'slug' => 'san-cristobal-acasaguastlan'],
            ['id' => 25084, 'region_id' => 707174, 'country_code' => 'GT', 'name' => 'El Jícaro', 'active' => 1, 'slug' => 'el-jicaro'],
            ['id' => 25085, 'region_id' => 707174, 'country_code' => 'GT', 'name' => 'Sansare', 'active' => 1, 'slug' => 'sansare'],
            ['id' => 25086, 'region_id' => 707174, 'country_code' => 'GT', 'name' => 'Sanarate', 'active' => 1, 'slug' => 'sanarate'],
            ['id' => 25087, 'region_id' => 707174, 'country_code' => 'GT', 'name' => 'San Antonio la Paz', 'active' => 1, 'slug' => 'san-antonio-la-paz'],
            ['id' => 25088, 'region_id' => 707175, 'country_code' => 'GT', 'name' => 'Canillá', 'active' => 1, 'slug' => 'canilla'],
            ['id' => 25089, 'region_id' => 707175, 'country_code' => 'GT', 'name' => 'Chajul', 'active' => 1, 'slug' => 'chajul'],
            ['id' => 25090, 'region_id' => 707175, 'country_code' => 'GT', 'name' => 'Chicamán', 'active' => 1, 'slug' => 'chicaman'],
            ['id' => 25091, 'region_id' => 707175, 'country_code' => 'GT', 'name' => 'Chiché', 'active' => 1, 'slug' => 'chiche'],
            ['id' => 25092, 'region_id' => 707175, 'country_code' => 'GT', 'name' => 'Chichicastenango', 'active' => 1, 'slug' => 'chichicastenango'],
            ['id' => 25093, 'region_id' => 707175, 'country_code' => 'GT', 'name' => 'Chinique', 'active' => 1, 'slug' => 'chinique'],
            ['id' => 25094, 'region_id' => 707175, 'country_code' => 'GT', 'name' => 'Cunén', 'active' => 1, 'slug' => 'cunen'],
            ['id' => 25095, 'region_id' => 707175, 'country_code' => 'GT', 'name' => 'Ixcán', 'active' => 1, 'slug' => 'ixcan'],
            ['id' => 25096, 'region_id' => 707175, 'country_code' => 'GT', 'name' => 'Joyabaj', 'active' => 1, 'slug' => 'joyabaj'],
            ['id' => 25097, 'region_id' => 707175, 'country_code' => 'GT', 'name' => 'Nebaj', 'active' => 1, 'slug' => 'nebaj'],
            ['id' => 25098, 'region_id' => 707175, 'country_code' => 'GT', 'name' => 'Pachalum', 'active' => 1, 'slug' => 'pachalum'],
            ['id' => 25099, 'region_id' => 707175, 'country_code' => 'GT', 'name' => 'Patzité', 'active' => 1, 'slug' => 'patzite'],
            ['id' => 25100, 'region_id' => 707175, 'country_code' => 'GT', 'name' => 'Sacapulas', 'active' => 1, 'slug' => 'sacapulas'],
            ['id' => 25101, 'region_id' => 707175, 'country_code' => 'GT', 'name' => 'San Andrés Sajcabajá', 'active' => 1, 'slug' => 'san-andres-sajcabaja'],
            ['id' => 25102, 'region_id' => 707175, 'country_code' => 'GT', 'name' => 'San Antonio Ilotenango', 'active' => 1, 'slug' => 'san-antonio-ilotenango'],
            ['id' => 25103, 'region_id' => 707175, 'country_code' => 'GT', 'name' => 'San Bartolomé Jocotenango', 'active' => 1, 'slug' => 'san-bartolome-jocotenango'],
            ['id' => 25104, 'region_id' => 707175, 'country_code' => 'GT', 'name' => 'San Juan Cotzal', 'active' => 1, 'slug' => 'san-juan-cotzal'],
            ['id' => 25105, 'region_id' => 707175, 'country_code' => 'GT', 'name' => 'San Pedro Jocopilas', 'active' => 1, 'slug' => 'san-pedro-jocopilas'],
            ['id' => 25106, 'region_id' => 707175, 'country_code' => 'GT', 'name' => 'Santa Cruz del Quiché', 'active' => 1, 'slug' => 'santa-cruz-del-quiche'],
            ['id' => 25107, 'region_id' => 707175, 'country_code' => 'GT', 'name' => 'Uspantán', 'active' => 1, 'slug' => 'uspantan'],
            ['id' => 25108, 'region_id' => 707175, 'country_code' => 'GT', 'name' => 'Zacualpa', 'active' => 1, 'slug' => 'zacualpa'],
            ['id' => 25109, 'region_id' => 707176, 'country_code' => 'GT', 'name' => 'Escuintla', 'active' => 1, 'slug' => 'escuintla'],
            ['id' => 25110, 'region_id' => 707176, 'country_code' => 'GT', 'name' => 'Guanazapa', 'active' => 1, 'slug' => 'guanazapa'],
            ['id' => 25111, 'region_id' => 707176, 'country_code' => 'GT', 'name' => 'Iztapa', 'active' => 1, 'slug' => 'iztapa'],
            ['id' => 25112, 'region_id' => 707176, 'country_code' => 'GT', 'name' => 'La Democracia', 'active' => 1, 'slug' => 'la-democracia'],
            ['id' => 25113, 'region_id' => 707176, 'country_code' => 'GT', 'name' => 'La Gomera', 'active' => 1, 'slug' => 'la-gomera'],
            ['id' => 25114, 'region_id' => 707176, 'country_code' => 'GT', 'name' => 'Masagua', 'active' => 1, 'slug' => 'masagua'],
            ['id' => 25115, 'region_id' => 707176, 'country_code' => 'GT', 'name' => 'Nueva Concepción', 'active' => 1, 'slug' => 'nueva-concepcion'],
            ['id' => 25116, 'region_id' => 707176, 'country_code' => 'GT', 'name' => 'Palín', 'active' => 1, 'slug' => 'palin'],
            ['id' => 25117, 'region_id' => 707176, 'country_code' => 'GT', 'name' => 'San José', 'active' => 1, 'slug' => 'san-jose'],
            ['id' => 25118, 'region_id' => 707176, 'country_code' => 'GT', 'name' => 'San Vicente Pacaya', 'active' => 1, 'slug' => 'san-vicente-pacaya'],
            ['id' => 25119, 'region_id' => 707176, 'country_code' => 'GT', 'name' => 'Santa Lucía Cotzumalguapa', 'active' => 1, 'slug' => 'santa-lucia-cotzumalguapa'],
            ['id' => 25120, 'region_id' => 707176, 'country_code' => 'GT', 'name' => 'Siquinalá', 'active' => 1, 'slug' => 'siquinala'],
            ['id' => 25121, 'region_id' => 707176, 'country_code' => 'GT', 'name' => 'Tiquizate', 'active' => 1, 'slug' => 'tiquizate'],
            ['id' => 25139, 'region_id' => 707178, 'country_code' => 'GT', 'name' => 'Aguacatán', 'active' => 1, 'slug' => 'aguacatan'],
            ['id' => 25140, 'region_id' => 707178, 'country_code' => 'GT', 'name' => 'Chiantla', 'active' => 1, 'slug' => 'chiantla'],
            ['id' => 25141, 'region_id' => 707178, 'country_code' => 'GT', 'name' => 'Colotenango', 'active' => 1, 'slug' => 'colotenango'],
            ['id' => 25142, 'region_id' => 707178, 'country_code' => 'GT', 'name' => 'Concepción Huista', 'active' => 1, 'slug' => 'concepcion-huista'],
            ['id' => 25143, 'region_id' => 707178, 'country_code' => 'GT', 'name' => 'Cuilco', 'active' => 1, 'slug' => 'cuilco'],
            ['id' => 25144, 'region_id' => 707178, 'country_code' => 'GT', 'name' => 'Huehuetenango', 'active' => 1, 'slug' => 'huehuetenango'],
            ['id' => 25145, 'region_id' => 707178, 'country_code' => 'GT', 'name' => 'Ixtahuacán', 'active' => 1, 'slug' => 'ixtahuacan'],
            ['id' => 25146, 'region_id' => 707178, 'country_code' => 'GT', 'name' => 'Jacaltenango', 'active' => 1, 'slug' => 'jacaltenango'],
            ['id' => 25147, 'region_id' => 707178, 'country_code' => 'GT', 'name' => 'La Democracia', 'active' => 1, 'slug' => 'la-democracia'],
            ['id' => 25148, 'region_id' => 707178, 'country_code' => 'GT', 'name' => 'La Libertad', 'active' => 1, 'slug' => 'la-libertad'],
            ['id' => 25149, 'region_id' => 707178, 'country_code' => 'GT', 'name' => 'Malacatancito', 'active' => 1, 'slug' => 'malacatancito'],
            ['id' => 25150, 'region_id' => 707178, 'country_code' => 'GT', 'name' => 'Nentón', 'active' => 1, 'slug' => 'nenton'],
            ['id' => 25151, 'region_id' => 707178, 'country_code' => 'GT', 'name' => 'San Antonio Huista', 'active' => 1, 'slug' => 'san-antonio-huista'],
            ['id' => 25152, 'region_id' => 707178, 'country_code' => 'GT', 'name' => 'San Gaspar Ixchil', 'active' => 1, 'slug' => 'san-gaspar-ixchil'],
            ['id' => 25153, 'region_id' => 707178, 'country_code' => 'GT', 'name' => 'San Juan Atitán', 'active' => 1, 'slug' => 'san-juan-atitan'],
            ['id' => 25154, 'region_id' => 707178, 'country_code' => 'GT', 'name' => 'San Juan Ixcoy', 'active' => 1, 'slug' => 'san-juan-ixcoy'],
            ['id' => 25155, 'region_id' => 707178, 'country_code' => 'GT', 'name' => 'San Mateo Ixtatán', 'active' => 1, 'slug' => 'san-mateo-ixtatan'],
            ['id' => 25156, 'region_id' => 707178, 'country_code' => 'GT', 'name' => 'San Miguel Acatán', 'active' => 1, 'slug' => 'san-miguel-acatan'],
            ['id' => 25157, 'region_id' => 707178, 'country_code' => 'GT', 'name' => 'San Pedro Necta', 'active' => 1, 'slug' => 'san-pedro-necta'],
            ['id' => 25158, 'region_id' => 707178, 'country_code' => 'GT', 'name' => 'San Rafael la Independencia', 'active' => 1, 'slug' => 'san-rafael-la-independencia'],
            ['id' => 25159, 'region_id' => 707178, 'country_code' => 'GT', 'name' => 'San Rafael Petzal', 'active' => 1, 'slug' => 'san-rafael-petzal'],
            ['id' => 25160, 'region_id' => 707178, 'country_code' => 'GT', 'name' => 'San Sebastián Coatán', 'active' => 1, 'slug' => 'san-sebastian-coatan'],
            ['id' => 25161, 'region_id' => 707178, 'country_code' => 'GT', 'name' => 'San Sebastián Huehuetenango', 'active' => 1, 'slug' => 'san-sebastian-huehuetenango'],
            ['id' => 25162, 'region_id' => 707178, 'country_code' => 'GT', 'name' => 'Santa Ana Huista.', 'active' => 1, 'slug' => 'santa-ana-huista'],
            ['id' => 25163, 'region_id' => 707178, 'country_code' => 'GT', 'name' => 'Santa Bárbara', 'active' => 1, 'slug' => 'santa-barbara'],
            ['id' => 25164, 'region_id' => 707178, 'country_code' => 'GT', 'name' => 'Santa Cruz Barillas', 'active' => 1, 'slug' => 'santa-cruz-barillas'],
            ['id' => 25165, 'region_id' => 707178, 'country_code' => 'GT', 'name' => 'Santa Eulalia', 'active' => 1, 'slug' => 'santa-eulalia'],
            ['id' => 25166, 'region_id' => 707178, 'country_code' => 'GT', 'name' => 'Santiago Chimaltenango', 'active' => 1, 'slug' => 'santiago-chimaltenango'],
            ['id' => 25167, 'region_id' => 707178, 'country_code' => 'GT', 'name' => 'Soloma', 'active' => 1, 'slug' => 'soloma'],
            ['id' => 25168, 'region_id' => 707178, 'country_code' => 'GT', 'name' => 'Tectitán', 'active' => 1, 'slug' => 'tectitan'],
            ['id' => 25169, 'region_id' => 707178, 'country_code' => 'GT', 'name' => 'Todos Santos Cuchumatán', 'active' => 1, 'slug' => 'todos-santos-cuchumatan'],
            ['id' => 25170, 'region_id' => 707178, 'country_code' => 'GT', 'name' => 'Unión Cantinil', 'active' => 1, 'slug' => 'union-cantinil'],
            ['id' => 25171, 'region_id' => 707179, 'country_code' => 'GT', 'name' => 'El Estor', 'active' => 1, 'slug' => 'el-estor'],
            ['id' => 25172, 'region_id' => 707179, 'country_code' => 'GT', 'name' => 'Livingston', 'active' => 1, 'slug' => 'livingston'],
            ['id' => 25173, 'region_id' => 707179, 'country_code' => 'GT', 'name' => 'Los Amates', 'active' => 1, 'slug' => 'los-amates'],
            ['id' => 25174, 'region_id' => 707179, 'country_code' => 'GT', 'name' => 'Morales', 'active' => 1, 'slug' => 'morales'],
            ['id' => 25175, 'region_id' => 707179, 'country_code' => 'GT', 'name' => 'Puerto Barrios', 'active' => 1, 'slug' => 'puerto-barrios'],
            ['id' => 25122, 'region_id' => 712100, 'country_code' => 'GT', 'name' => 'Ciudad de Guatemala', 'active' => 1, 'slug' => 'ciudad-de-guatemala'],
            ['id' => 25123, 'region_id' => 712100, 'country_code' => 'GT', 'name' => 'Santa Catarina Pinula', 'active' => 1, 'slug' => 'santa-catarina-pinula'],
            ['id' => 25124, 'region_id' => 712100, 'country_code' => 'GT', 'name' => 'San José Pinula', 'active' => 1, 'slug' => 'san-jose-pinula'],
            ['id' => 25125, 'region_id' => 712100, 'country_code' => 'GT', 'name' => 'San José del Golfo', 'active' => 1, 'slug' => 'san-jose-del-golfo'],
            ['id' => 25126, 'region_id' => 712100, 'country_code' => 'GT', 'name' => 'Palencia', 'active' => 1, 'slug' => 'palencia'],
            ['id' => 25127, 'region_id' => 712100, 'country_code' => 'GT', 'name' => 'Chinautla,', 'active' => 1, 'slug' => 'chinautla'],
            ['id' => 25128, 'region_id' => 712100, 'country_code' => 'GT', 'name' => 'San Pedro Ayampuc', 'active' => 1, 'slug' => 'san-pedro-ayampuc'],
            ['id' => 25129, 'region_id' => 712100, 'country_code' => 'GT', 'name' => 'Mixco', 'active' => 1, 'slug' => 'mixco'],
            ['id' => 25130, 'region_id' => 712100, 'country_code' => 'GT', 'name' => 'San Pedro Sacatepéquez', 'active' => 1, 'slug' => 'san-pedro-sacatepequez'],
            ['id' => 25131, 'region_id' => 712100, 'country_code' => 'GT', 'name' => 'San Juan Sacatepéquez', 'active' => 1, 'slug' => 'san-juan-sacatepequez'],
            ['id' => 25132, 'region_id' => 712100, 'country_code' => 'GT', 'name' => 'San Raimundo', 'active' => 1, 'slug' => 'san-raimundo'],
            ['id' => 25133, 'region_id' => 712100, 'country_code' => 'GT', 'name' => 'Chuarrancho', 'active' => 1, 'slug' => 'chuarrancho'],
            ['id' => 25134, 'region_id' => 712100, 'country_code' => 'GT', 'name' => 'Fraijanes', 'active' => 1, 'slug' => 'fraijanes'],
            ['id' => 25135, 'region_id' => 712100, 'country_code' => 'GT', 'name' => 'Amatitlán', 'active' => 1, 'slug' => 'amatitlan'],
            ['id' => 25136, 'region_id' => 712100, 'country_code' => 'GT', 'name' => 'Villa Nueva', 'active' => 1, 'slug' => 'villa-nueva'],
            ['id' => 25137, 'region_id' => 712100, 'country_code' => 'GT', 'name' => 'Villa Canales', 'active' => 1, 'slug' => 'villa-canales'],
            ['id' => 25138, 'region_id' => 712100, 'country_code' => 'GT', 'name' => 'San Miguel Petapa', 'active' => 1, 'slug' => 'san-miguel-petapa'],
            ['id' => 25249, 'region_id' => 712101, 'country_code' => 'GT', 'name' => 'Ayutla', 'active' => 1, 'slug' => 'ayutla'],
            ['id' => 25250, 'region_id' => 712101, 'country_code' => 'GT', 'name' => 'Catarina', 'active' => 1, 'slug' => 'catarina'],
            ['id' => 25251, 'region_id' => 712101, 'country_code' => 'GT', 'name' => 'Comitancillo', 'active' => 1, 'slug' => 'comitancillo'],
            ['id' => 25252, 'region_id' => 712101, 'country_code' => 'GT', 'name' => 'Concepción Tutuapa', 'active' => 1, 'slug' => 'concepcion-tutuapa'],
            ['id' => 25253, 'region_id' => 712101, 'country_code' => 'GT', 'name' => 'El Quetzal', 'active' => 1, 'slug' => 'el-quetzal'],
            ['id' => 25254, 'region_id' => 712101, 'country_code' => 'GT', 'name' => 'El Rodeo', 'active' => 1, 'slug' => 'el-rodeo'],
            ['id' => 25255, 'region_id' => 712101, 'country_code' => 'GT', 'name' => 'El Tumbador', 'active' => 1, 'slug' => 'el-tumbador'],
            ['id' => 25256, 'region_id' => 712101, 'country_code' => 'GT', 'name' => 'Esquipulas Palo Gordo', 'active' => 1, 'slug' => 'esquipulas-palo-gordo'],
            ['id' => 25257, 'region_id' => 712101, 'country_code' => 'GT', 'name' => 'Ixchiguan', 'active' => 1, 'slug' => 'ixchiguan'],
            ['id' => 25258, 'region_id' => 712101, 'country_code' => 'GT', 'name' => 'La Reforma', 'active' => 1, 'slug' => 'la-reforma'],
            ['id' => 25259, 'region_id' => 712101, 'country_code' => 'GT', 'name' => 'Malacatán', 'active' => 1, 'slug' => 'malacatan'],
            ['id' => 25260, 'region_id' => 712101, 'country_code' => 'GT', 'name' => 'Nuevo Progreso', 'active' => 1, 'slug' => 'nuevo-progreso'],
            ['id' => 25261, 'region_id' => 712101, 'country_code' => 'GT', 'name' => 'Ocós', 'active' => 1, 'slug' => 'ocos'],
            ['id' => 25262, 'region_id' => 712101, 'country_code' => 'GT', 'name' => 'Pajapita', 'active' => 1, 'slug' => 'pajapita'],
            ['id' => 25263, 'region_id' => 712101, 'country_code' => 'GT', 'name' => 'Río Blanco', 'active' => 1, 'slug' => 'rio-blanco'],
            ['id' => 25264, 'region_id' => 712101, 'country_code' => 'GT', 'name' => 'San Antonio Sacatepéquez', 'active' => 1, 'slug' => 'san-antonio-sacatepequez'],
            ['id' => 25265, 'region_id' => 712101, 'country_code' => 'GT', 'name' => 'San Cristóbal Cucho', 'active' => 1, 'slug' => 'san-cristobal-cucho'],
            ['id' => 25266, 'region_id' => 712101, 'country_code' => 'GT', 'name' => 'San José Ojetenam', 'active' => 1, 'slug' => 'san-jose-ojetenam'],
            ['id' => 25267, 'region_id' => 712101, 'country_code' => 'GT', 'name' => 'San Lorenzo', 'active' => 1, 'slug' => 'san-lorenzo'],
            ['id' => 25268, 'region_id' => 712101, 'country_code' => 'GT', 'name' => 'San Marcos', 'active' => 1, 'slug' => 'san-marcos'],
            ['id' => 25269, 'region_id' => 712101, 'country_code' => 'GT', 'name' => 'San Miguel Ixtahuacán', 'active' => 1, 'slug' => 'san-miguel-ixtahuacan'],
            ['id' => 25270, 'region_id' => 712101, 'country_code' => 'GT', 'name' => 'San Pablo', 'active' => 1, 'slug' => 'san-pablo'],
            ['id' => 25271, 'region_id' => 712101, 'country_code' => 'GT', 'name' => 'San Pedro Sacatepéquez', 'active' => 1, 'slug' => 'san-pedro-sacatepequez'],
            ['id' => 25272, 'region_id' => 712101, 'country_code' => 'GT', 'name' => 'San Rafaél Pie de la Cuesta', 'active' => 1, 'slug' => 'san-rafael-pie-de-la-cuesta'],
            ['id' => 25273, 'region_id' => 712101, 'country_code' => 'GT', 'name' => 'Sibinal', 'active' => 1, 'slug' => 'sibinal'],
            ['id' => 25274, 'region_id' => 712101, 'country_code' => 'GT', 'name' => 'Sipacapa', 'active' => 1, 'slug' => 'sipacapa'],
            ['id' => 25275, 'region_id' => 712101, 'country_code' => 'GT', 'name' => 'Tacaná', 'active' => 1, 'slug' => 'tacana'],
            ['id' => 25276, 'region_id' => 712101, 'country_code' => 'GT', 'name' => 'Tajumulco', 'active' => 1, 'slug' => 'tajumulco'],
            ['id' => 25277, 'region_id' => 712101, 'country_code' => 'GT', 'name' => 'Tejutla', 'active' => 1, 'slug' => 'tejutla'],
            ['id' => 25278, 'region_id' => 712102, 'country_code' => 'GT', 'name' => 'Barberena', 'active' => 1, 'slug' => 'barberena'],
            ['id' => 25279, 'region_id' => 712102, 'country_code' => 'GT', 'name' => 'Casillas', 'active' => 1, 'slug' => 'casillas'],
            ['id' => 25280, 'region_id' => 712102, 'country_code' => 'GT', 'name' => 'Chiquimulilla', 'active' => 1, 'slug' => 'chiquimulilla'],
            ['id' => 25281, 'region_id' => 712102, 'country_code' => 'GT', 'name' => 'Cuilapa', 'active' => 1, 'slug' => 'cuilapa'],
            ['id' => 25282, 'region_id' => 712102, 'country_code' => 'GT', 'name' => 'Guazacapán', 'active' => 1, 'slug' => 'guazacapan'],
            ['id' => 25283, 'region_id' => 712102, 'country_code' => 'GT', 'name' => 'Nueva Santa Rosa', 'active' => 1, 'slug' => 'nueva-santa-rosa'],
            ['id' => 25284, 'region_id' => 712102, 'country_code' => 'GT', 'name' => 'Oratorio', 'active' => 1, 'slug' => 'oratorio'],
            ['id' => 25285, 'region_id' => 712102, 'country_code' => 'GT', 'name' => 'Pueblo Nuevo Viñas', 'active' => 1, 'slug' => 'pueblo-nuevo-vinas'],
            ['id' => 25286, 'region_id' => 712102, 'country_code' => 'GT', 'name' => 'San Juan Tecuaco', 'active' => 1, 'slug' => 'san-juan-tecuaco'],
            ['id' => 25287, 'region_id' => 712102, 'country_code' => 'GT', 'name' => 'San Rafaél Las Flores', 'active' => 1, 'slug' => 'san-rafael-las-flores'],
            ['id' => 25288, 'region_id' => 712102, 'country_code' => 'GT', 'name' => 'Santa Cruz Naranjo', 'active' => 1, 'slug' => 'santa-cruz-naranjo'],
            ['id' => 25289, 'region_id' => 712102, 'country_code' => 'GT', 'name' => 'Santa María Ixhuatán', 'active' => 1, 'slug' => 'santa-maria-ixhuatan'],
            ['id' => 25290, 'region_id' => 712102, 'country_code' => 'GT', 'name' => 'Santa Rosa de Lima', 'active' => 1, 'slug' => 'santa-rosa-de-lima'],
            ['id' => 25291, 'region_id' => 712102, 'country_code' => 'GT', 'name' => 'Taxisco', 'active' => 1, 'slug' => 'taxisco']
    	];
    }
}
