<?php

namespace Gerardojbaez\GeoData\Seeders;

use Illuminate\Database\Seeder;
use Gerardojbaez\GeoData\Models\Country;
use Gerardojbaez\GeoData\Models\Region;
use Gerardojbaez\GeoData\Models\City;

class HondurasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Country::create($this->country());
        Region::insert($this->regions());

        if ($this->cities() > 4000)
        {
            foreach (array_chunk($this->cities(), 3500) as $chunk)
                City::insert($chunk);
        }
        else
        {
            City::insert($this->cities());
        }
    }

        /**
     * Get country.
     *
     * @return array
     */
    public function country()
    {
    	return ['code' => 'HN', 'name' => 'Honduras', 'slug' => 'honduras'];
    }

    /**
     * Get country regions.
     *
     * @return array
     */
    public function regions()
    {
    	return [
            ['id' => 707180, 'country_code' => 'HN', 'name' => 'Intibucá', 'active' => 1, 'slug' => 'intibuca'],
            ['id' => 707181, 'country_code' => 'HN', 'name' => 'Islas de la Bahía', 'active' => 1, 'slug' => 'islas-de-la-bahia'],
            ['id' => 707183, 'country_code' => 'HN', 'name' => 'Lempira', 'active' => 1, 'slug' => 'lempira'],
            ['id' => 707184, 'country_code' => 'HN', 'name' => 'Ocotepeque', 'active' => 1, 'slug' => 'ocotepeque'],
            ['id' => 707185, 'country_code' => 'HN', 'name' => 'Olancho', 'active' => 1, 'slug' => 'olancho'],
            ['id' => 707186, 'country_code' => 'HN', 'name' => 'Santa Bárbara', 'active' => 1, 'slug' => 'santa-barbara'],
            ['id' => 707187, 'country_code' => 'HN', 'name' => 'Valle', 'active' => 1, 'slug' => 'valle'],
            ['id' => 707188, 'country_code' => 'HN', 'name' => 'Yoro', 'active' => 1, 'slug' => 'yoro'],
            ['id' => 707189, 'country_code' => 'HN', 'name' => 'Atlántida', 'active' => 1, 'slug' => 'atlantida'],
            ['id' => 707190, 'country_code' => 'HN', 'name' => 'Choluteca', 'active' => 1, 'slug' => 'choluteca'],
            ['id' => 707192, 'country_code' => 'HN', 'name' => 'Comayagua', 'active' => 1, 'slug' => 'comayagua'],
            ['id' => 707193, 'country_code' => 'HN', 'name' => 'Copán', 'active' => 1, 'slug' => 'copan'],
            ['id' => 707195, 'country_code' => 'HN', 'name' => 'El Paraíso', 'active' => 1, 'slug' => 'el-paraiso'],
            ['id' => 707196, 'country_code' => 'HN', 'name' => 'Francisco Morazán', 'active' => 1, 'slug' => 'francisco-morazan'],
            ['id' => 707197, 'country_code' => 'HN', 'name' => 'Gracias a Dios', 'active' => 1, 'slug' => 'gracias-a-dios'],
            ['id' => 717201, 'country_code' => 'HN', 'name' => 'Colón', 'active' => 1, 'slug' => 'colon'],
            ['id' => 717263, 'country_code' => 'HN', 'name' => 'Cortés', 'active' => 1, 'slug' => 'cortes'],
            ['id' => 717355, 'country_code' => 'HN', 'name' => 'La Paz', 'active' => 1, 'slug' => 'la-paz']
    	];
    }

    /**
     * Get region cities.
     *
     * @return array
     */
    public function cities()
    {
    	return [
            ['id' => 31285, 'region_id' => 707180, 'country_code' => 'HN', 'name' => 'Camasca', 'active' => 1, 'slug' => 'camasca'],
            ['id' => 31286, 'region_id' => 707180, 'country_code' => 'HN', 'name' => 'Colomoncagua', 'active' => 1, 'slug' => 'colomoncagua'],
            ['id' => 31287, 'region_id' => 707180, 'country_code' => 'HN', 'name' => 'Concepción', 'active' => 1, 'slug' => 'concepcion'],
            ['id' => 31288, 'region_id' => 707180, 'country_code' => 'HN', 'name' => 'Dolores', 'active' => 1, 'slug' => 'dolores'],
            ['id' => 31289, 'region_id' => 707180, 'country_code' => 'HN', 'name' => 'Intibucá', 'active' => 1, 'slug' => 'intibuca'],
            ['id' => 31290, 'region_id' => 707180, 'country_code' => 'HN', 'name' => 'Jesús de Otoro', 'active' => 1, 'slug' => 'jesus-de-otoro'],
            ['id' => 31291, 'region_id' => 707180, 'country_code' => 'HN', 'name' => 'La Esperanza', 'active' => 1, 'slug' => 'la-esperanza'],
            ['id' => 31292, 'region_id' => 707180, 'country_code' => 'HN', 'name' => 'Magdalena', 'active' => 1, 'slug' => 'magdalena'],
            ['id' => 31293, 'region_id' => 707180, 'country_code' => 'HN', 'name' => 'Masaguara', 'active' => 1, 'slug' => 'masaguara'],
            ['id' => 31294, 'region_id' => 707180, 'country_code' => 'HN', 'name' => 'San Antonio', 'active' => 1, 'slug' => 'san-antonio'],
            ['id' => 31295, 'region_id' => 707180, 'country_code' => 'HN', 'name' => 'San Francisco de Opalaca', 'active' => 1, 'slug' => 'san-francisco-de-opalaca'],
            ['id' => 31296, 'region_id' => 707180, 'country_code' => 'HN', 'name' => 'San Isidro', 'active' => 1, 'slug' => 'san-isidro'],
            ['id' => 31297, 'region_id' => 707180, 'country_code' => 'HN', 'name' => 'San Juan', 'active' => 1, 'slug' => 'san-juan'],
            ['id' => 31298, 'region_id' => 707180, 'country_code' => 'HN', 'name' => 'San Marco de Sierra', 'active' => 1, 'slug' => 'san-marco-de-sierra'],
            ['id' => 31299, 'region_id' => 707180, 'country_code' => 'HN', 'name' => 'San Miguelito', 'active' => 1, 'slug' => 'san-miguelito'],
            ['id' => 31300, 'region_id' => 707180, 'country_code' => 'HN', 'name' => 'Santa Lucía', 'active' => 1, 'slug' => 'santa-lucia'],
            ['id' => 31301, 'region_id' => 707180, 'country_code' => 'HN', 'name' => 'Yamaranguila', 'active' => 1, 'slug' => 'yamaranguila'],
            ['id' => 31302, 'region_id' => 707181, 'country_code' => 'HN', 'name' => 'Guanaja', 'active' => 1, 'slug' => 'guanaja'],
            ['id' => 31303, 'region_id' => 707181, 'country_code' => 'HN', 'name' => 'José Santos Guardiola', 'active' => 1, 'slug' => 'jose-santos-guardiola'],
            ['id' => 31304, 'region_id' => 707181, 'country_code' => 'HN', 'name' => 'Roatán', 'active' => 1, 'slug' => 'roatan'],
            ['id' => 31305, 'region_id' => 707181, 'country_code' => 'HN', 'name' => 'Útila', 'active' => 1, 'slug' => 'utila'],
            ['id' => 31325, 'region_id' => 707183, 'country_code' => 'HN', 'name' => 'Belén', 'active' => 1, 'slug' => 'belen'],
            ['id' => 31326, 'region_id' => 707183, 'country_code' => 'HN', 'name' => 'Candelaria', 'active' => 1, 'slug' => 'candelaria'],
            ['id' => 31327, 'region_id' => 707183, 'country_code' => 'HN', 'name' => 'Cololaca', 'active' => 1, 'slug' => 'cololaca'],
            ['id' => 31328, 'region_id' => 707183, 'country_code' => 'HN', 'name' => 'Erandique', 'active' => 1, 'slug' => 'erandique'],
            ['id' => 31329, 'region_id' => 707183, 'country_code' => 'HN', 'name' => 'Gracias', 'active' => 1, 'slug' => 'gracias'],
            ['id' => 31330, 'region_id' => 707183, 'country_code' => 'HN', 'name' => 'Gualcince', 'active' => 1, 'slug' => 'gualcince'],
            ['id' => 31331, 'region_id' => 707183, 'country_code' => 'HN', 'name' => 'Guarita', 'active' => 1, 'slug' => 'guarita'],
            ['id' => 31332, 'region_id' => 707183, 'country_code' => 'HN', 'name' => 'La Campa', 'active' => 1, 'slug' => 'la-campa'],
            ['id' => 31333, 'region_id' => 707183, 'country_code' => 'HN', 'name' => 'La Iguala', 'active' => 1, 'slug' => 'la-iguala'],
            ['id' => 31334, 'region_id' => 707183, 'country_code' => 'HN', 'name' => 'Las Flores', 'active' => 1, 'slug' => 'las-flores'],
            ['id' => 31335, 'region_id' => 707183, 'country_code' => 'HN', 'name' => 'La Unión', 'active' => 1, 'slug' => 'la-union'],
            ['id' => 31336, 'region_id' => 707183, 'country_code' => 'HN', 'name' => 'La Virtud', 'active' => 1, 'slug' => 'la-virtud'],
            ['id' => 31337, 'region_id' => 707183, 'country_code' => 'HN', 'name' => 'Lepaera', 'active' => 1, 'slug' => 'lepaera'],
            ['id' => 31338, 'region_id' => 707183, 'country_code' => 'HN', 'name' => 'Mapulaca', 'active' => 1, 'slug' => 'mapulaca'],
            ['id' => 31339, 'region_id' => 707183, 'country_code' => 'HN', 'name' => 'Piraera', 'active' => 1, 'slug' => 'piraera'],
            ['id' => 31340, 'region_id' => 707183, 'country_code' => 'HN', 'name' => 'San Andrés', 'active' => 1, 'slug' => 'san-andres'],
            ['id' => 31341, 'region_id' => 707183, 'country_code' => 'HN', 'name' => 'San Francisco', 'active' => 1, 'slug' => 'san-francisco'],
            ['id' => 31342, 'region_id' => 707183, 'country_code' => 'HN', 'name' => 'San Juan Guarita', 'active' => 1, 'slug' => 'san-juan-guarita'],
            ['id' => 31343, 'region_id' => 707183, 'country_code' => 'HN', 'name' => 'San Manuel Colohete', 'active' => 1, 'slug' => 'san-manuel-colohete'],
            ['id' => 31344, 'region_id' => 707183, 'country_code' => 'HN', 'name' => 'San Marcos de Caiquín', 'active' => 1, 'slug' => 'san-marcos-de-caiquin'],
            ['id' => 31345, 'region_id' => 707183, 'country_code' => 'HN', 'name' => 'San Rafael', 'active' => 1, 'slug' => 'san-rafael'],
            ['id' => 31346, 'region_id' => 707183, 'country_code' => 'HN', 'name' => 'San Sebastian', 'active' => 1, 'slug' => 'san-sebastian'],
            ['id' => 31347, 'region_id' => 707183, 'country_code' => 'HN', 'name' => 'Santa Cruz', 'active' => 1, 'slug' => 'santa-cruz'],
            ['id' => 31348, 'region_id' => 707183, 'country_code' => 'HN', 'name' => 'Talgua', 'active' => 1, 'slug' => 'talgua'],
            ['id' => 31349, 'region_id' => 707183, 'country_code' => 'HN', 'name' => 'Tambla', 'active' => 1, 'slug' => 'tambla'],
            ['id' => 31350, 'region_id' => 707183, 'country_code' => 'HN', 'name' => 'Tomalá', 'active' => 1, 'slug' => 'tomala'],
            ['id' => 31351, 'region_id' => 707183, 'country_code' => 'HN', 'name' => 'Valladolid', 'active' => 1, 'slug' => 'valladolid'],
            ['id' => 31352, 'region_id' => 707183, 'country_code' => 'HN', 'name' => 'Virginia', 'active' => 1, 'slug' => 'virginia'],
            ['id' => 31353, 'region_id' => 707184, 'country_code' => 'HN', 'name' => 'Belén Gualcho', 'active' => 1, 'slug' => 'belen-gualcho'],
            ['id' => 31354, 'region_id' => 707184, 'country_code' => 'HN', 'name' => 'Concepción', 'active' => 1, 'slug' => 'concepcion'],
            ['id' => 31355, 'region_id' => 707184, 'country_code' => 'HN', 'name' => 'Dolores Merendon', 'active' => 1, 'slug' => 'dolores-merendon'],
            ['id' => 31356, 'region_id' => 707184, 'country_code' => 'HN', 'name' => 'Fraternidad', 'active' => 1, 'slug' => 'fraternidad'],
            ['id' => 31357, 'region_id' => 707184, 'country_code' => 'HN', 'name' => 'La Encarnación', 'active' => 1, 'slug' => 'la-encarnacion'],
            ['id' => 31358, 'region_id' => 707184, 'country_code' => 'HN', 'name' => 'La Labor', 'active' => 1, 'slug' => 'la-labor'],
            ['id' => 31359, 'region_id' => 707184, 'country_code' => 'HN', 'name' => 'Lucerna', 'active' => 1, 'slug' => 'lucerna'],
            ['id' => 31360, 'region_id' => 707184, 'country_code' => 'HN', 'name' => 'Mercedes', 'active' => 1, 'slug' => 'mercedes'],
            ['id' => 31361, 'region_id' => 707184, 'country_code' => 'HN', 'name' => 'Ocotepeque', 'active' => 1, 'slug' => 'ocotepeque'],
            ['id' => 31362, 'region_id' => 707184, 'country_code' => 'HN', 'name' => 'San Fernando', 'active' => 1, 'slug' => 'san-fernando'],
            ['id' => 31363, 'region_id' => 707184, 'country_code' => 'HN', 'name' => 'San Francisco del Valle', 'active' => 1, 'slug' => 'san-francisco-del-valle'],
            ['id' => 31364, 'region_id' => 707184, 'country_code' => 'HN', 'name' => 'San Jorge', 'active' => 1, 'slug' => 'san-jorge'],
            ['id' => 31365, 'region_id' => 707184, 'country_code' => 'HN', 'name' => 'San Marcos', 'active' => 1, 'slug' => 'san-marcos'],
            ['id' => 31366, 'region_id' => 707184, 'country_code' => 'HN', 'name' => 'Santa Fé', 'active' => 1, 'slug' => 'santa-fe'],
            ['id' => 31367, 'region_id' => 707184, 'country_code' => 'HN', 'name' => 'Sensenti', 'active' => 1, 'slug' => 'sensenti'],
            ['id' => 31368, 'region_id' => 707184, 'country_code' => 'HN', 'name' => 'Sinuapa', 'active' => 1, 'slug' => 'sinuapa'],
            ['id' => 31369, 'region_id' => 707185, 'country_code' => 'HN', 'name' => 'Catacamas', 'active' => 1, 'slug' => 'catacamas'],
            ['id' => 31370, 'region_id' => 707185, 'country_code' => 'HN', 'name' => 'Campamento', 'active' => 1, 'slug' => 'campamento'],
            ['id' => 31371, 'region_id' => 707185, 'country_code' => 'HN', 'name' => 'Concordia', 'active' => 1, 'slug' => 'concordia'],
            ['id' => 31372, 'region_id' => 707185, 'country_code' => 'HN', 'name' => 'Dulce Nombre de Culmí', 'active' => 1, 'slug' => 'dulce-nombre-de-culmi'],
            ['id' => 31373, 'region_id' => 707185, 'country_code' => 'HN', 'name' => 'El Rosario', 'active' => 1, 'slug' => 'el-rosario'],
            ['id' => 31374, 'region_id' => 707185, 'country_code' => 'HN', 'name' => 'Esquipulas del Norte', 'active' => 1, 'slug' => 'esquipulas-del-norte'],
            ['id' => 31375, 'region_id' => 707185, 'country_code' => 'HN', 'name' => 'Gualaco', 'active' => 1, 'slug' => 'gualaco'],
            ['id' => 31376, 'region_id' => 707185, 'country_code' => 'HN', 'name' => 'Guarizama', 'active' => 1, 'slug' => 'guarizama'],
            ['id' => 31377, 'region_id' => 707185, 'country_code' => 'HN', 'name' => 'Guata', 'active' => 1, 'slug' => 'guata'],
            ['id' => 31378, 'region_id' => 707185, 'country_code' => 'HN', 'name' => 'Guayape', 'active' => 1, 'slug' => 'guayape'],
            ['id' => 31379, 'region_id' => 707185, 'country_code' => 'HN', 'name' => 'Jano', 'active' => 1, 'slug' => 'jano'],
            ['id' => 31380, 'region_id' => 707185, 'country_code' => 'HN', 'name' => 'Juticalpa', 'active' => 1, 'slug' => 'juticalpa'],
            ['id' => 31381, 'region_id' => 707185, 'country_code' => 'HN', 'name' => 'La Unión', 'active' => 1, 'slug' => 'la-union'],
            ['id' => 31382, 'region_id' => 707185, 'country_code' => 'HN', 'name' => 'Mangulile', 'active' => 1, 'slug' => 'mangulile'],
            ['id' => 31383, 'region_id' => 707185, 'country_code' => 'HN', 'name' => 'Manto', 'active' => 1, 'slug' => 'manto'],
            ['id' => 31384, 'region_id' => 707185, 'country_code' => 'HN', 'name' => 'Patuca', 'active' => 1, 'slug' => 'patuca'],
            ['id' => 31385, 'region_id' => 707185, 'country_code' => 'HN', 'name' => 'Salamá', 'active' => 1, 'slug' => 'salama'],
            ['id' => 31386, 'region_id' => 707185, 'country_code' => 'HN', 'name' => 'San Esteban', 'active' => 1, 'slug' => 'san-esteban'],
            ['id' => 31387, 'region_id' => 707185, 'country_code' => 'HN', 'name' => 'San Francisco de Becerra', 'active' => 1, 'slug' => 'san-francisco-de-becerra'],
            ['id' => 31388, 'region_id' => 707185, 'country_code' => 'HN', 'name' => 'San Francisco de la Paz', 'active' => 1, 'slug' => 'san-francisco-de-la-paz'],
            ['id' => 31389, 'region_id' => 707185, 'country_code' => 'HN', 'name' => 'Santa Maria del Real', 'active' => 1, 'slug' => 'santa-maria-del-real'],
            ['id' => 31390, 'region_id' => 707185, 'country_code' => 'HN', 'name' => 'Silca', 'active' => 1, 'slug' => 'silca'],
            ['id' => 31391, 'region_id' => 707185, 'country_code' => 'HN', 'name' => 'Yocón', 'active' => 1, 'slug' => 'yocon'],
            ['id' => 31392, 'region_id' => 707186, 'country_code' => 'HN', 'name' => 'Arada', 'active' => 1, 'slug' => 'arada'],
            ['id' => 31393, 'region_id' => 707186, 'country_code' => 'HN', 'name' => 'Atima', 'active' => 1, 'slug' => 'atima'],
            ['id' => 31394, 'region_id' => 707186, 'country_code' => 'HN', 'name' => 'Azacualpa', 'active' => 1, 'slug' => 'azacualpa'],
            ['id' => 31395, 'region_id' => 707186, 'country_code' => 'HN', 'name' => 'Ceguaca', 'active' => 1, 'slug' => 'ceguaca'],
            ['id' => 31396, 'region_id' => 707186, 'country_code' => 'HN', 'name' => 'Chinda', 'active' => 1, 'slug' => 'chinda'],
            ['id' => 31397, 'region_id' => 707186, 'country_code' => 'HN', 'name' => 'Concepción del Norte', 'active' => 1, 'slug' => 'concepcion-del-norte'],
            ['id' => 31398, 'region_id' => 707186, 'country_code' => 'HN', 'name' => 'Concepción del Sur', 'active' => 1, 'slug' => 'concepcion-del-sur'],
            ['id' => 31399, 'region_id' => 707186, 'country_code' => 'HN', 'name' => 'El Nispero', 'active' => 1, 'slug' => 'el-nispero'],
            ['id' => 31400, 'region_id' => 707186, 'country_code' => 'HN', 'name' => 'Gualala', 'active' => 1, 'slug' => 'gualala'],
            ['id' => 31401, 'region_id' => 707186, 'country_code' => 'HN', 'name' => 'Ilama', 'active' => 1, 'slug' => 'ilama'],
            ['id' => 31402, 'region_id' => 707186, 'country_code' => 'HN', 'name' => 'Las Vegas', 'active' => 1, 'slug' => 'las-vegas'],
            ['id' => 31403, 'region_id' => 707186, 'country_code' => 'HN', 'name' => 'Macuelizo', 'active' => 1, 'slug' => 'macuelizo'],
            ['id' => 31404, 'region_id' => 707186, 'country_code' => 'HN', 'name' => 'Naranjito', 'active' => 1, 'slug' => 'naranjito'],
            ['id' => 31405, 'region_id' => 707186, 'country_code' => 'HN', 'name' => 'Nueva Frontera', 'active' => 1, 'slug' => 'nueva-frontera'],
            ['id' => 31406, 'region_id' => 707186, 'country_code' => 'HN', 'name' => 'Nuevo Celilac', 'active' => 1, 'slug' => 'nuevo-celilac'],
            ['id' => 31407, 'region_id' => 707186, 'country_code' => 'HN', 'name' => 'Petoa', 'active' => 1, 'slug' => 'petoa'],
            ['id' => 31408, 'region_id' => 707186, 'country_code' => 'HN', 'name' => 'Protección', 'active' => 1, 'slug' => 'proteccion'],
            ['id' => 31409, 'region_id' => 707186, 'country_code' => 'HN', 'name' => 'Quimistán', 'active' => 1, 'slug' => 'quimistan'],
            ['id' => 31410, 'region_id' => 707186, 'country_code' => 'HN', 'name' => 'San Francisco de Ojuera', 'active' => 1, 'slug' => 'san-francisco-de-ojuera'],
            ['id' => 31411, 'region_id' => 707186, 'country_code' => 'HN', 'name' => 'San José de Colinas', 'active' => 1, 'slug' => 'san-jose-de-colinas'],
            ['id' => 31412, 'region_id' => 707186, 'country_code' => 'HN', 'name' => 'San Luis', 'active' => 1, 'slug' => 'san-luis'],
            ['id' => 31413, 'region_id' => 707186, 'country_code' => 'HN', 'name' => 'San Marcos', 'active' => 1, 'slug' => 'san-marcos'],
            ['id' => 31414, 'region_id' => 707186, 'country_code' => 'HN', 'name' => 'San Nicolás', 'active' => 1, 'slug' => 'san-nicolas'],
            ['id' => 31415, 'region_id' => 707186, 'country_code' => 'HN', 'name' => 'San Pedro Zacapa', 'active' => 1, 'slug' => 'san-pedro-zacapa'],
            ['id' => 31416, 'region_id' => 707186, 'country_code' => 'HN', 'name' => 'Santa Bárbara', 'active' => 1, 'slug' => 'santa-barbara'],
            ['id' => 31417, 'region_id' => 707186, 'country_code' => 'HN', 'name' => 'Santa Rita', 'active' => 1, 'slug' => 'santa-rita'],
            ['id' => 31418, 'region_id' => 707186, 'country_code' => 'HN', 'name' => 'San Vicente Centenario', 'active' => 1, 'slug' => 'san-vicente-centenario'],
            ['id' => 31419, 'region_id' => 707186, 'country_code' => 'HN', 'name' => 'Trinidad', 'active' => 1, 'slug' => 'trinidad'],
            ['id' => 31420, 'region_id' => 707187, 'country_code' => 'HN', 'name' => 'Alianza', 'active' => 1, 'slug' => 'alianza'],
            ['id' => 31421, 'region_id' => 707187, 'country_code' => 'HN', 'name' => 'Amapala', 'active' => 1, 'slug' => 'amapala'],
            ['id' => 31422, 'region_id' => 707187, 'country_code' => 'HN', 'name' => 'Aramecina', 'active' => 1, 'slug' => 'aramecina'],
            ['id' => 31423, 'region_id' => 707187, 'country_code' => 'HN', 'name' => 'Caridad', 'active' => 1, 'slug' => 'caridad'],
            ['id' => 31424, 'region_id' => 707187, 'country_code' => 'HN', 'name' => 'Goascorán', 'active' => 1, 'slug' => 'goascoran'],
            ['id' => 31425, 'region_id' => 707187, 'country_code' => 'HN', 'name' => 'Langue', 'active' => 1, 'slug' => 'langue'],
            ['id' => 31426, 'region_id' => 707187, 'country_code' => 'HN', 'name' => 'Nacaome', 'active' => 1, 'slug' => 'nacaome'],
            ['id' => 31427, 'region_id' => 707187, 'country_code' => 'HN', 'name' => 'San Francisco de Coray', 'active' => 1, 'slug' => 'san-francisco-de-coray'],
            ['id' => 31428, 'region_id' => 707187, 'country_code' => 'HN', 'name' => 'San Lorenzo', 'active' => 1, 'slug' => 'san-lorenzo'],
            ['id' => 31429, 'region_id' => 707188, 'country_code' => 'HN', 'name' => 'Arenal', 'active' => 1, 'slug' => 'arenal'],
            ['id' => 31430, 'region_id' => 707188, 'country_code' => 'HN', 'name' => 'El Negrito', 'active' => 1, 'slug' => 'el-negrito'],
            ['id' => 31431, 'region_id' => 707188, 'country_code' => 'HN', 'name' => 'El Progreso,', 'active' => 1, 'slug' => 'el-progreso'],
            ['id' => 31432, 'region_id' => 707188, 'country_code' => 'HN', 'name' => 'Jocón', 'active' => 1, 'slug' => 'jocon'],
            ['id' => 31433, 'region_id' => 707188, 'country_code' => 'HN', 'name' => 'Morazán', 'active' => 1, 'slug' => 'morazan'],
            ['id' => 31434, 'region_id' => 707188, 'country_code' => 'HN', 'name' => 'Olanchito', 'active' => 1, 'slug' => 'olanchito'],
            ['id' => 31435, 'region_id' => 707188, 'country_code' => 'HN', 'name' => 'Santa Rita', 'active' => 1, 'slug' => 'santa-rita'],
            ['id' => 31436, 'region_id' => 707188, 'country_code' => 'HN', 'name' => 'Sulaco, Yoro', 'active' => 1, 'slug' => 'sulaco-yoro'],
            ['id' => 31437, 'region_id' => 707188, 'country_code' => 'HN', 'name' => 'Victoria', 'active' => 1, 'slug' => 'victoria'],
            ['id' => 31438, 'region_id' => 707188, 'country_code' => 'HN', 'name' => 'Yorito', 'active' => 1, 'slug' => 'yorito'],
            ['id' => 31439, 'region_id' => 707188, 'country_code' => 'HN', 'name' => 'Yoro', 'active' => 1, 'slug' => 'yoro'],
            ['id' => 31137, 'region_id' => 707189, 'country_code' => 'HN', 'name' => 'Arizona', 'active' => 1, 'slug' => 'arizona'],
            ['id' => 31138, 'region_id' => 707189, 'country_code' => 'HN', 'name' => 'El Porvenir', 'active' => 1, 'slug' => 'el-porvenir'],
            ['id' => 31139, 'region_id' => 707189, 'country_code' => 'HN', 'name' => 'Esparta', 'active' => 1, 'slug' => 'esparta'],
            ['id' => 31140, 'region_id' => 707189, 'country_code' => 'HN', 'name' => 'Jutiapa', 'active' => 1, 'slug' => 'jutiapa'],
            ['id' => 31141, 'region_id' => 707189, 'country_code' => 'HN', 'name' => 'La Ceiba', 'active' => 1, 'slug' => 'la-ceiba'],
            ['id' => 31142, 'region_id' => 707189, 'country_code' => 'HN', 'name' => 'La Masica', 'active' => 1, 'slug' => 'la-masica'],
            ['id' => 31143, 'region_id' => 707189, 'country_code' => 'HN', 'name' => 'San Francisco', 'active' => 1, 'slug' => 'san-francisco'],
            ['id' => 31144, 'region_id' => 707189, 'country_code' => 'HN', 'name' => 'Tela', 'active' => 1, 'slug' => 'tela'],
            ['id' => 31145, 'region_id' => 707190, 'country_code' => 'HN', 'name' => 'Apacilagua', 'active' => 1, 'slug' => 'apacilagua'],
            ['id' => 31146, 'region_id' => 707190, 'country_code' => 'HN', 'name' => 'Choluteca', 'active' => 1, 'slug' => 'choluteca'],
            ['id' => 31147, 'region_id' => 707190, 'country_code' => 'HN', 'name' => 'Concepción de María', 'active' => 1, 'slug' => 'concepcion-de-maria'],
            ['id' => 31148, 'region_id' => 707190, 'country_code' => 'HN', 'name' => 'Duyure', 'active' => 1, 'slug' => 'duyure'],
            ['id' => 31149, 'region_id' => 707190, 'country_code' => 'HN', 'name' => 'El Corpus', 'active' => 1, 'slug' => 'el-corpus'],
            ['id' => 31150, 'region_id' => 707190, 'country_code' => 'HN', 'name' => 'El Triunfo', 'active' => 1, 'slug' => 'el-triunfo'],
            ['id' => 31151, 'region_id' => 707190, 'country_code' => 'HN', 'name' => 'Marcovia', 'active' => 1, 'slug' => 'marcovia'],
            ['id' => 31152, 'region_id' => 707190, 'country_code' => 'HN', 'name' => 'Morolica', 'active' => 1, 'slug' => 'morolica'],
            ['id' => 31153, 'region_id' => 707190, 'country_code' => 'HN', 'name' => 'Namasigue', 'active' => 1, 'slug' => 'namasigue'],
            ['id' => 31154, 'region_id' => 707190, 'country_code' => 'HN', 'name' => 'Orocuina', 'active' => 1, 'slug' => 'orocuina'],
            ['id' => 31155, 'region_id' => 707190, 'country_code' => 'HN', 'name' => 'Pespire', 'active' => 1, 'slug' => 'pespire'],
            ['id' => 31156, 'region_id' => 707190, 'country_code' => 'HN', 'name' => 'San Antonio de Flores', 'active' => 1, 'slug' => 'san-antonio-de-flores'],
            ['id' => 31157, 'region_id' => 707190, 'country_code' => 'HN', 'name' => 'San Isidro', 'active' => 1, 'slug' => 'san-isidro'],
            ['id' => 31158, 'region_id' => 707190, 'country_code' => 'HN', 'name' => 'San José', 'active' => 1, 'slug' => 'san-jose'],
            ['id' => 31159, 'region_id' => 707190, 'country_code' => 'HN', 'name' => 'San Marcos de Colón', 'active' => 1, 'slug' => 'san-marcos-de-colon'],
            ['id' => 31160, 'region_id' => 707190, 'country_code' => 'HN', 'name' => 'Santa Ana de Yusguare', 'active' => 1, 'slug' => 'santa-ana-de-yusguare'],
            ['id' => 31176, 'region_id' => 707192, 'country_code' => 'HN', 'name' => 'Ajuterique', 'active' => 1, 'slug' => 'ajuterique'],
            ['id' => 31177, 'region_id' => 707192, 'country_code' => 'HN', 'name' => 'Comayagua', 'active' => 1, 'slug' => 'comayagua'],
            ['id' => 31178, 'region_id' => 707192, 'country_code' => 'HN', 'name' => 'El Rosario', 'active' => 1, 'slug' => 'el-rosario'],
            ['id' => 31179, 'region_id' => 707192, 'country_code' => 'HN', 'name' => 'Esquías', 'active' => 1, 'slug' => 'esquias'],
            ['id' => 31180, 'region_id' => 707192, 'country_code' => 'HN', 'name' => 'Humuya', 'active' => 1, 'slug' => 'humuya'],
            ['id' => 31181, 'region_id' => 707192, 'country_code' => 'HN', 'name' => 'La Libertad', 'active' => 1, 'slug' => 'la-libertad'],
            ['id' => 31182, 'region_id' => 707192, 'country_code' => 'HN', 'name' => 'Lamaní', 'active' => 1, 'slug' => 'lamani'],
            ['id' => 31183, 'region_id' => 707192, 'country_code' => 'HN', 'name' => 'Las Lajas', 'active' => 1, 'slug' => 'las-lajas'],
            ['id' => 31184, 'region_id' => 707192, 'country_code' => 'HN', 'name' => 'La Trinidad', 'active' => 1, 'slug' => 'la-trinidad'],
            ['id' => 31185, 'region_id' => 707192, 'country_code' => 'HN', 'name' => 'Lejamaní', 'active' => 1, 'slug' => 'lejamani'],
            ['id' => 31186, 'region_id' => 707192, 'country_code' => 'HN', 'name' => 'Meámbar', 'active' => 1, 'slug' => 'meambar'],
            ['id' => 31187, 'region_id' => 707192, 'country_code' => 'HN', 'name' => 'Minas de Oro', 'active' => 1, 'slug' => 'minas-de-oro'],
            ['id' => 31188, 'region_id' => 707192, 'country_code' => 'HN', 'name' => 'Ojo de Agua', 'active' => 1, 'slug' => 'ojo-de-agua'],
            ['id' => 31189, 'region_id' => 707192, 'country_code' => 'HN', 'name' => 'San Jerónimo', 'active' => 1, 'slug' => 'san-jeronimo'],
            ['id' => 31190, 'region_id' => 707192, 'country_code' => 'HN', 'name' => 'San José de Comayagua', 'active' => 1, 'slug' => 'san-jose-de-comayagua'],
            ['id' => 31191, 'region_id' => 707192, 'country_code' => 'HN', 'name' => 'San José del Potrero', 'active' => 1, 'slug' => 'san-jose-del-potrero'],
            ['id' => 31192, 'region_id' => 707192, 'country_code' => 'HN', 'name' => 'San Luis', 'active' => 1, 'slug' => 'san-luis'],
            ['id' => 31193, 'region_id' => 707192, 'country_code' => 'HN', 'name' => 'San Sebastián', 'active' => 1, 'slug' => 'san-sebastian'],
            ['id' => 31194, 'region_id' => 707192, 'country_code' => 'HN', 'name' => 'Siguatepeque', 'active' => 1, 'slug' => 'siguatepeque'],
            ['id' => 31195, 'region_id' => 707192, 'country_code' => 'HN', 'name' => 'Taulabe', 'active' => 1, 'slug' => 'taulabe'],
            ['id' => 31196, 'region_id' => 707192, 'country_code' => 'HN', 'name' => 'Villa de San Antonio', 'active' => 1, 'slug' => 'villa-de-san-antonio'],
            ['id' => 31197, 'region_id' => 707193, 'country_code' => 'HN', 'name' => 'Cabañas', 'active' => 1, 'slug' => 'cabanas'],
            ['id' => 31198, 'region_id' => 707193, 'country_code' => 'HN', 'name' => 'Concepción', 'active' => 1, 'slug' => 'concepcion'],
            ['id' => 31199, 'region_id' => 707193, 'country_code' => 'HN', 'name' => 'Copán Ruinas', 'active' => 1, 'slug' => 'copan-ruinas'],
            ['id' => 31200, 'region_id' => 707193, 'country_code' => 'HN', 'name' => 'Corquín', 'active' => 1, 'slug' => 'corquin'],
            ['id' => 31201, 'region_id' => 707193, 'country_code' => 'HN', 'name' => 'Cucuyagua', 'active' => 1, 'slug' => 'cucuyagua'],
            ['id' => 31202, 'region_id' => 707193, 'country_code' => 'HN', 'name' => 'Dolores', 'active' => 1, 'slug' => 'dolores'],
            ['id' => 31203, 'region_id' => 707193, 'country_code' => 'HN', 'name' => 'Dulce Nombre', 'active' => 1, 'slug' => 'dulce-nombre'],
            ['id' => 31204, 'region_id' => 707193, 'country_code' => 'HN', 'name' => 'El Paraíso', 'active' => 1, 'slug' => 'el-paraiso'],
            ['id' => 31205, 'region_id' => 707193, 'country_code' => 'HN', 'name' => 'Florida', 'active' => 1, 'slug' => 'florida'],
            ['id' => 31206, 'region_id' => 707193, 'country_code' => 'HN', 'name' => 'La Jigua', 'active' => 1, 'slug' => 'la-jigua'],
            ['id' => 31207, 'region_id' => 707193, 'country_code' => 'HN', 'name' => 'La Unión', 'active' => 1, 'slug' => 'la-union'],
            ['id' => 31208, 'region_id' => 707193, 'country_code' => 'HN', 'name' => 'Nueva Arcadia', 'active' => 1, 'slug' => 'nueva-arcadia'],
            ['id' => 31209, 'region_id' => 707193, 'country_code' => 'HN', 'name' => 'San Agustín', 'active' => 1, 'slug' => 'san-agustin'],
            ['id' => 31210, 'region_id' => 707193, 'country_code' => 'HN', 'name' => 'San Antonio', 'active' => 1, 'slug' => 'san-antonio'],
            ['id' => 31211, 'region_id' => 707193, 'country_code' => 'HN', 'name' => 'San Jerónimo', 'active' => 1, 'slug' => 'san-jeronimo'],
            ['id' => 31212, 'region_id' => 707193, 'country_code' => 'HN', 'name' => 'San José', 'active' => 1, 'slug' => 'san-jose'],
            ['id' => 31213, 'region_id' => 707193, 'country_code' => 'HN', 'name' => 'San Juan de Opoa', 'active' => 1, 'slug' => 'san-juan-de-opoa'],
            ['id' => 31214, 'region_id' => 707193, 'country_code' => 'HN', 'name' => 'San Nicolás', 'active' => 1, 'slug' => 'san-nicolas'],
            ['id' => 31215, 'region_id' => 707193, 'country_code' => 'HN', 'name' => 'San Pedro de Copán', 'active' => 1, 'slug' => 'san-pedro-de-copan'],
            ['id' => 31216, 'region_id' => 707193, 'country_code' => 'HN', 'name' => 'Santa Rita', 'active' => 1, 'slug' => 'santa-rita'],
            ['id' => 31217, 'region_id' => 707193, 'country_code' => 'HN', 'name' => 'Santa Rosa de Copán', 'active' => 1, 'slug' => 'santa-rosa-de-copan'],
            ['id' => 31218, 'region_id' => 707193, 'country_code' => 'HN', 'name' => 'Trinidad de Copán', 'active' => 1, 'slug' => 'trinidad-de-copan'],
            ['id' => 31219, 'region_id' => 707193, 'country_code' => 'HN', 'name' => 'Veracruz', 'active' => 1, 'slug' => 'veracruz'],
            ['id' => 31232, 'region_id' => 707195, 'country_code' => 'HN', 'name' => 'Alauca', 'active' => 1, 'slug' => 'alauca'],
            ['id' => 31233, 'region_id' => 707195, 'country_code' => 'HN', 'name' => 'Danlí', 'active' => 1, 'slug' => 'danli'],
            ['id' => 31234, 'region_id' => 707195, 'country_code' => 'HN', 'name' => 'El Paraíso', 'active' => 1, 'slug' => 'el-paraiso'],
            ['id' => 31235, 'region_id' => 707195, 'country_code' => 'HN', 'name' => 'Guinope', 'active' => 1, 'slug' => 'guinope'],
            ['id' => 31236, 'region_id' => 707195, 'country_code' => 'HN', 'name' => 'Jacaleapa', 'active' => 1, 'slug' => 'jacaleapa'],
            ['id' => 31237, 'region_id' => 707195, 'country_code' => 'HN', 'name' => 'Liure', 'active' => 1, 'slug' => 'liure'],
            ['id' => 31238, 'region_id' => 707195, 'country_code' => 'HN', 'name' => 'Morocelí', 'active' => 1, 'slug' => 'moroceli'],
            ['id' => 31239, 'region_id' => 707195, 'country_code' => 'HN', 'name' => 'Oropolí', 'active' => 1, 'slug' => 'oropoli'],
            ['id' => 31240, 'region_id' => 707195, 'country_code' => 'HN', 'name' => 'Potrerillos', 'active' => 1, 'slug' => 'potrerillos'],
            ['id' => 31241, 'region_id' => 707195, 'country_code' => 'HN', 'name' => 'San Antonio de Flores', 'active' => 1, 'slug' => 'san-antonio-de-flores'],
            ['id' => 31242, 'region_id' => 707195, 'country_code' => 'HN', 'name' => 'San Lucas', 'active' => 1, 'slug' => 'san-lucas'],
            ['id' => 31243, 'region_id' => 707195, 'country_code' => 'HN', 'name' => 'San Matías', 'active' => 1, 'slug' => 'san-matias'],
            ['id' => 31244, 'region_id' => 707195, 'country_code' => 'HN', 'name' => 'Soledad', 'active' => 1, 'slug' => 'soledad'],
            ['id' => 31245, 'region_id' => 707195, 'country_code' => 'HN', 'name' => 'Teupasenti', 'active' => 1, 'slug' => 'teupasenti'],
            ['id' => 31246, 'region_id' => 707195, 'country_code' => 'HN', 'name' => 'Texiguat', 'active' => 1, 'slug' => 'texiguat'],
            ['id' => 31247, 'region_id' => 707195, 'country_code' => 'HN', 'name' => 'Trojes', 'active' => 1, 'slug' => 'trojes'],
            ['id' => 31248, 'region_id' => 707195, 'country_code' => 'HN', 'name' => 'Vado Ancho', 'active' => 1, 'slug' => 'vado-ancho'],
            ['id' => 31249, 'region_id' => 707195, 'country_code' => 'HN', 'name' => 'Yauyupe', 'active' => 1, 'slug' => 'yauyupe'],
            ['id' => 31250, 'region_id' => 707195, 'country_code' => 'HN', 'name' => 'Yuscarán', 'active' => 1, 'slug' => 'yuscaran'],
            ['id' => 31251, 'region_id' => 707196, 'country_code' => 'HN', 'name' => 'Alubarén', 'active' => 1, 'slug' => 'alubaren'],
            ['id' => 31252, 'region_id' => 707196, 'country_code' => 'HN', 'name' => 'Cedros', 'active' => 1, 'slug' => 'cedros'],
            ['id' => 31253, 'region_id' => 707196, 'country_code' => 'HN', 'name' => 'Curarén', 'active' => 1, 'slug' => 'curaren'],
            ['id' => 31254, 'region_id' => 707196, 'country_code' => 'HN', 'name' => 'Distrito Central', 'active' => 1, 'slug' => 'distrito-central'],
            ['id' => 31255, 'region_id' => 707196, 'country_code' => 'HN', 'name' => 'El Porvenir', 'active' => 1, 'slug' => 'el-porvenir'],
            ['id' => 31256, 'region_id' => 707196, 'country_code' => 'HN', 'name' => 'Guaimaca', 'active' => 1, 'slug' => 'guaimaca'],
            ['id' => 31257, 'region_id' => 707196, 'country_code' => 'HN', 'name' => 'La Libertad', 'active' => 1, 'slug' => 'la-libertad'],
            ['id' => 31258, 'region_id' => 707196, 'country_code' => 'HN', 'name' => 'La Venta', 'active' => 1, 'slug' => 'la-venta'],
            ['id' => 31259, 'region_id' => 707196, 'country_code' => 'HN', 'name' => 'Lepaterique', 'active' => 1, 'slug' => 'lepaterique'],
            ['id' => 31260, 'region_id' => 707196, 'country_code' => 'HN', 'name' => 'Maraita', 'active' => 1, 'slug' => 'maraita'],
            ['id' => 31261, 'region_id' => 707196, 'country_code' => 'HN', 'name' => 'Marale', 'active' => 1, 'slug' => 'marale'],
            ['id' => 31262, 'region_id' => 707196, 'country_code' => 'HN', 'name' => 'Nueva Armenia', 'active' => 1, 'slug' => 'nueva-armenia'],
            ['id' => 31263, 'region_id' => 707196, 'country_code' => 'HN', 'name' => 'Ojojona', 'active' => 1, 'slug' => 'ojojona'],
            ['id' => 31264, 'region_id' => 707196, 'country_code' => 'HN', 'name' => 'Orica', 'active' => 1, 'slug' => 'orica'],
            ['id' => 31265, 'region_id' => 707196, 'country_code' => 'HN', 'name' => 'Reitoca', 'active' => 1, 'slug' => 'reitoca'],
            ['id' => 31266, 'region_id' => 707196, 'country_code' => 'HN', 'name' => 'Sabanagrande', 'active' => 1, 'slug' => 'sabanagrande'],
            ['id' => 31267, 'region_id' => 707196, 'country_code' => 'HN', 'name' => 'San Antonio de Oriente', 'active' => 1, 'slug' => 'san-antonio-de-oriente'],
            ['id' => 31268, 'region_id' => 707196, 'country_code' => 'HN', 'name' => 'San Buenaventura', 'active' => 1, 'slug' => 'san-buenaventura'],
            ['id' => 31269, 'region_id' => 707196, 'country_code' => 'HN', 'name' => 'San Ignacio', 'active' => 1, 'slug' => 'san-ignacio'],
            ['id' => 31270, 'region_id' => 707196, 'country_code' => 'HN', 'name' => 'San Juan de Flores', 'active' => 1, 'slug' => 'san-juan-de-flores'],
            ['id' => 31271, 'region_id' => 707196, 'country_code' => 'HN', 'name' => 'San Miguelito', 'active' => 1, 'slug' => 'san-miguelito'],
            ['id' => 31272, 'region_id' => 707196, 'country_code' => 'HN', 'name' => 'Santa Ana', 'active' => 1, 'slug' => 'santa-ana'],
            ['id' => 31273, 'region_id' => 707196, 'country_code' => 'HN', 'name' => 'Santa Lucía', 'active' => 1, 'slug' => 'santa-lucia'],
            ['id' => 31274, 'region_id' => 707196, 'country_code' => 'HN', 'name' => 'Talanga', 'active' => 1, 'slug' => 'talanga'],
            ['id' => 31275, 'region_id' => 707196, 'country_code' => 'HN', 'name' => 'Tatumbla', 'active' => 1, 'slug' => 'tatumbla'],
            ['id' => 31276, 'region_id' => 707196, 'country_code' => 'HN', 'name' => 'Valle deÁngeles', 'active' => 1, 'slug' => 'valle-deangeles'],
            ['id' => 31277, 'region_id' => 707196, 'country_code' => 'HN', 'name' => 'Vallecillo', 'active' => 1, 'slug' => 'vallecillo'],
            ['id' => 31278, 'region_id' => 707196, 'country_code' => 'HN', 'name' => 'Villa de San Francisco', 'active' => 1, 'slug' => 'villa-de-san-francisco'],
            ['id' => 31279, 'region_id' => 707197, 'country_code' => 'HN', 'name' => 'Ahuas', 'active' => 1, 'slug' => 'ahuas'],
            ['id' => 31280, 'region_id' => 707197, 'country_code' => 'HN', 'name' => 'Brus Laguna', 'active' => 1, 'slug' => 'brus-laguna'],
            ['id' => 31281, 'region_id' => 707197, 'country_code' => 'HN', 'name' => 'Juan Francisco Bulnes', 'active' => 1, 'slug' => 'juan-francisco-bulnes'],
            ['id' => 31282, 'region_id' => 707197, 'country_code' => 'HN', 'name' => 'Puerto Lempira', 'active' => 1, 'slug' => 'puerto-lempira'],
            ['id' => 31283, 'region_id' => 707197, 'country_code' => 'HN', 'name' => 'Ramón Villeda Morales', 'active' => 1, 'slug' => 'ramon-villeda-morales'],
            ['id' => 31284, 'region_id' => 707197, 'country_code' => 'HN', 'name' => 'Wampusirpi', 'active' => 1, 'slug' => 'wampusirpi'],
            ['id' => 31161, 'region_id' => 717201, 'country_code' => 'HN', 'name' => 'Balfate', 'active' => 1, 'slug' => 'balfate'],
            ['id' => 31162, 'region_id' => 717201, 'country_code' => 'HN', 'name' => 'Bonito Oriental', 'active' => 1, 'slug' => 'bonito-oriental'],
            ['id' => 31163, 'region_id' => 717201, 'country_code' => 'HN', 'name' => 'Iriona', 'active' => 1, 'slug' => 'iriona'],
            ['id' => 31164, 'region_id' => 717201, 'country_code' => 'HN', 'name' => 'Limón', 'active' => 1, 'slug' => 'limon'],
            ['id' => 31165, 'region_id' => 717201, 'country_code' => 'HN', 'name' => 'Sabá', 'active' => 1, 'slug' => 'saba'],
            ['id' => 31166, 'region_id' => 717201, 'country_code' => 'HN', 'name' => 'Santa Fé', 'active' => 1, 'slug' => 'santa-fe'],
            ['id' => 31167, 'region_id' => 717201, 'country_code' => 'HN', 'name' => 'Santa Rosa de Aguán', 'active' => 1, 'slug' => 'santa-rosa-de-aguan'],
            ['id' => 31168, 'region_id' => 717201, 'country_code' => 'HN', 'name' => 'Sonaguera', 'active' => 1, 'slug' => 'sonaguera'],
            ['id' => 31169, 'region_id' => 717201, 'country_code' => 'HN', 'name' => 'Tocoa', 'active' => 1, 'slug' => 'tocoa'],
            ['id' => 31170, 'region_id' => 717201, 'country_code' => 'HN', 'name' => 'Trujillo', 'active' => 1, 'slug' => 'trujillo'],
            ['id' => 31171, 'region_id' => 717201, 'country_code' => 'HN', 'name' => 'Colón', 'active' => 1, 'slug' => 'colon'],
            ['id' => 31172, 'region_id' => 717201, 'country_code' => 'HN', 'name' => 'Chagres', 'active' => 1, 'slug' => 'chagres'],
            ['id' => 31173, 'region_id' => 717201, 'country_code' => 'HN', 'name' => 'Donoso', 'active' => 1, 'slug' => 'donoso'],
            ['id' => 31174, 'region_id' => 717201, 'country_code' => 'HN', 'name' => 'Portobelo', 'active' => 1, 'slug' => 'portobelo'],
            ['id' => 31175, 'region_id' => 717201, 'country_code' => 'HN', 'name' => 'Santa Isabel', 'active' => 1, 'slug' => 'santa-isabel'],
            ['id' => 31220, 'region_id' => 717263, 'country_code' => 'HN', 'name' => 'Choloma', 'active' => 1, 'slug' => 'choloma'],
            ['id' => 31221, 'region_id' => 717263, 'country_code' => 'HN', 'name' => 'La Lima', 'active' => 1, 'slug' => 'la-lima'],
            ['id' => 31222, 'region_id' => 717263, 'country_code' => 'HN', 'name' => 'Omoa', 'active' => 1, 'slug' => 'omoa'],
            ['id' => 31223, 'region_id' => 717263, 'country_code' => 'HN', 'name' => 'Pimienta', 'active' => 1, 'slug' => 'pimienta'],
            ['id' => 31224, 'region_id' => 717263, 'country_code' => 'HN', 'name' => 'Potrerillos', 'active' => 1, 'slug' => 'potrerillos'],
            ['id' => 31225, 'region_id' => 717263, 'country_code' => 'HN', 'name' => 'Puerto Cortés', 'active' => 1, 'slug' => 'puerto-cortes'],
            ['id' => 31226, 'region_id' => 717263, 'country_code' => 'HN', 'name' => 'San Antonio de Cortés', 'active' => 1, 'slug' => 'san-antonio-de-cortes'],
            ['id' => 31227, 'region_id' => 717263, 'country_code' => 'HN', 'name' => 'San Francisco de Yojoa', 'active' => 1, 'slug' => 'san-francisco-de-yojoa'],
            ['id' => 31228, 'region_id' => 717263, 'country_code' => 'HN', 'name' => 'San Manuel', 'active' => 1, 'slug' => 'san-manuel'],
            ['id' => 31229, 'region_id' => 717263, 'country_code' => 'HN', 'name' => 'San Pedro Sula, Cortés', 'active' => 1, 'slug' => 'san-pedro-sula-cortes'],
            ['id' => 31230, 'region_id' => 717263, 'country_code' => 'HN', 'name' => 'Santa Cruz de Yojoa', 'active' => 1, 'slug' => 'santa-cruz-de-yojoa'],
            ['id' => 31231, 'region_id' => 717263, 'country_code' => 'HN', 'name' => 'Villanueva', 'active' => 1, 'slug' => 'villanueva'],
            ['id' => 31306, 'region_id' => 717355, 'country_code' => 'HN', 'name' => 'Aguaqueterique', 'active' => 1, 'slug' => 'aguaqueterique'],
            ['id' => 31307, 'region_id' => 717355, 'country_code' => 'HN', 'name' => 'Cabañas', 'active' => 1, 'slug' => 'cabanas'],
            ['id' => 31308, 'region_id' => 717355, 'country_code' => 'HN', 'name' => 'Cane', 'active' => 1, 'slug' => 'cane'],
            ['id' => 31309, 'region_id' => 717355, 'country_code' => 'HN', 'name' => 'Chinacla', 'active' => 1, 'slug' => 'chinacla'],
            ['id' => 31310, 'region_id' => 717355, 'country_code' => 'HN', 'name' => 'Guajiquiro', 'active' => 1, 'slug' => 'guajiquiro'],
            ['id' => 31311, 'region_id' => 717355, 'country_code' => 'HN', 'name' => 'La Paz', 'active' => 1, 'slug' => 'la-paz'],
            ['id' => 31312, 'region_id' => 717355, 'country_code' => 'HN', 'name' => 'Lauterique', 'active' => 1, 'slug' => 'lauterique'],
            ['id' => 31313, 'region_id' => 717355, 'country_code' => 'HN', 'name' => 'Marcala', 'active' => 1, 'slug' => 'marcala'],
            ['id' => 31314, 'region_id' => 717355, 'country_code' => 'HN', 'name' => 'Mercedes de Oriente', 'active' => 1, 'slug' => 'mercedes-de-oriente'],
            ['id' => 31315, 'region_id' => 717355, 'country_code' => 'HN', 'name' => 'Opatoro', 'active' => 1, 'slug' => 'opatoro'],
            ['id' => 31316, 'region_id' => 717355, 'country_code' => 'HN', 'name' => 'San Antonio del Norte', 'active' => 1, 'slug' => 'san-antonio-del-norte'],
            ['id' => 31317, 'region_id' => 717355, 'country_code' => 'HN', 'name' => 'San José', 'active' => 1, 'slug' => 'san-jose'],
            ['id' => 31318, 'region_id' => 717355, 'country_code' => 'HN', 'name' => 'San Juan', 'active' => 1, 'slug' => 'san-juan'],
            ['id' => 31319, 'region_id' => 717355, 'country_code' => 'HN', 'name' => 'San Pedro de Tutule', 'active' => 1, 'slug' => 'san-pedro-de-tutule'],
            ['id' => 31320, 'region_id' => 717355, 'country_code' => 'HN', 'name' => 'Santa Ana', 'active' => 1, 'slug' => 'santa-ana'],
            ['id' => 31321, 'region_id' => 717355, 'country_code' => 'HN', 'name' => 'Santa Elena', 'active' => 1, 'slug' => 'santa-elena'],
            ['id' => 31322, 'region_id' => 717355, 'country_code' => 'HN', 'name' => 'Santa María', 'active' => 1, 'slug' => 'santa-maria'],
            ['id' => 31323, 'region_id' => 717355, 'country_code' => 'HN', 'name' => 'Santiago de Puringla', 'active' => 1, 'slug' => 'santiago-de-puringla'],
            ['id' => 31324, 'region_id' => 717355, 'country_code' => 'HN', 'name' => 'Yarula', 'active' => 1, 'slug' => 'yarula']
    	];
    }
}
