<?php

namespace Gerardojbaez\GeoData\Seeders;

use Illuminate\Database\Seeder;
use Gerardojbaez\GeoData\Models\Country;
use Gerardojbaez\GeoData\Models\Region;
use Gerardojbaez\GeoData\Models\City;

class IndonesiaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Country::create($this->country());
        Region::insert($this->regions());

        if ($this->cities() > 4000)
        {
            foreach (array_chunk($this->cities(), 3500) as $chunk)
                City::insert($chunk);
        }
        else
        {
            City::insert($this->cities());
        }
    }

        /**
     * Get country.
     *
     * @return array
     */
    public function country()
    {
    	return ['code' => 'ID', 'name' => 'Indonesia', 'slug' => 'indonesia'];
    }

    /**
     * Get country regions.
     *
     * @return array
     */
    public function regions()
    {
    	return [
            ['id' => 781986, 'country_code' => 'ID', 'name' => 'Aceh', 'active' => 1, 'slug' => 'aceh'],
            ['id' => 781987, 'country_code' => 'ID', 'name' => 'Bali', 'active' => 1, 'slug' => 'bali'],
            ['id' => 781988, 'country_code' => 'ID', 'name' => 'Bangka Belitung Islands', 'active' => 1, 'slug' => 'bangka-belitung-islands'],
            ['id' => 781989, 'country_code' => 'ID', 'name' => 'Banten', 'active' => 1, 'slug' => 'banten'],
            ['id' => 781990, 'country_code' => 'ID', 'name' => 'Bengkulu', 'active' => 1, 'slug' => 'bengkulu'],
            ['id' => 781991, 'country_code' => 'ID', 'name' => 'Central Java', 'active' => 1, 'slug' => 'central-java'],
            ['id' => 781992, 'country_code' => 'ID', 'name' => 'Central Kalimantan', 'active' => 1, 'slug' => 'central-kalimantan'],
            ['id' => 781993, 'country_code' => 'ID', 'name' => 'Central Sulawesi', 'active' => 1, 'slug' => 'central-sulawesi'],
            ['id' => 781994, 'country_code' => 'ID', 'name' => 'East Java', 'active' => 1, 'slug' => 'east-java'],
            ['id' => 781995, 'country_code' => 'ID', 'name' => 'East Kalimantan', 'active' => 1, 'slug' => 'east-kalimantan'],
            ['id' => 781996, 'country_code' => 'ID', 'name' => 'East Nusa Tenggara', 'active' => 1, 'slug' => 'east-nusa-tenggara'],
            ['id' => 781997, 'country_code' => 'ID', 'name' => 'Gorontalo', 'active' => 1, 'slug' => 'gorontalo'],
            ['id' => 781998, 'country_code' => 'ID', 'name' => 'Jakarta', 'active' => 1, 'slug' => 'jakarta'],
            ['id' => 781999, 'country_code' => 'ID', 'name' => 'Jambi', 'active' => 1, 'slug' => 'jambi'],
            ['id' => 782000, 'country_code' => 'ID', 'name' => 'Lampung', 'active' => 1, 'slug' => 'lampung'],
            ['id' => 782001, 'country_code' => 'ID', 'name' => 'Maluku', 'active' => 1, 'slug' => 'maluku'],
            ['id' => 782002, 'country_code' => 'ID', 'name' => 'North Maluku', 'active' => 1, 'slug' => 'north-maluku'],
            ['id' => 782003, 'country_code' => 'ID', 'name' => 'North Sulawesi', 'active' => 1, 'slug' => 'north-sulawesi'],
            ['id' => 782004, 'country_code' => 'ID', 'name' => 'North Sumatra', 'active' => 1, 'slug' => 'north-sumatra'],
            ['id' => 782005, 'country_code' => 'ID', 'name' => 'Papua', 'active' => 1, 'slug' => 'papua'],
            ['id' => 782006, 'country_code' => 'ID', 'name' => 'Riau', 'active' => 1, 'slug' => 'riau'],
            ['id' => 782007, 'country_code' => 'ID', 'name' => 'Riau Islands', 'active' => 1, 'slug' => 'riau-islands'],
            ['id' => 782008, 'country_code' => 'ID', 'name' => 'South East Sulawesi', 'active' => 1, 'slug' => 'south-east-sulawesi'],
            ['id' => 782009, 'country_code' => 'ID', 'name' => 'South Kalimantan', 'active' => 1, 'slug' => 'south-kalimantan'],
            ['id' => 782010, 'country_code' => 'ID', 'name' => 'South Sulawesi', 'active' => 1, 'slug' => 'south-sulawesi'],
            ['id' => 782011, 'country_code' => 'ID', 'name' => 'South Sumatra', 'active' => 1, 'slug' => 'south-sumatra'],
            ['id' => 782012, 'country_code' => 'ID', 'name' => 'West Java', 'active' => 1, 'slug' => 'west-java'],
            ['id' => 782013, 'country_code' => 'ID', 'name' => 'West Kalimantan', 'active' => 1, 'slug' => 'west-kalimantan'],
            ['id' => 782014, 'country_code' => 'ID', 'name' => 'West Nusa Tenggara', 'active' => 1, 'slug' => 'west-nusa-tenggara'],
            ['id' => 782015, 'country_code' => 'ID', 'name' => 'West Papua', 'active' => 1, 'slug' => 'west-papua'],
            ['id' => 782016, 'country_code' => 'ID', 'name' => 'West Sulawesi', 'active' => 1, 'slug' => 'west-sulawesi'],
            ['id' => 782017, 'country_code' => 'ID', 'name' => 'West Sumatra', 'active' => 1, 'slug' => 'west-sumatra'],
            ['id' => 782018, 'country_code' => 'ID', 'name' => 'Yogyakarta', 'active' => 1, 'slug' => 'yogyakarta']
    	];
    }

    /**
     * Get region cities.
     *
     * @return array
     */
    public function cities()
    {
    	return [
            ['id' => 274720, 'region_id' => 781986, 'country_code' => 'ID', 'name' => 'Aceh Besar', 'active' => 1, 'slug' => 'aceh-besar'],
            ['id' => 274721, 'region_id' => 781986, 'country_code' => 'ID', 'name' => 'Aceh Jaya', 'active' => 1, 'slug' => 'aceh-jaya'],
            ['id' => 274722, 'region_id' => 781986, 'country_code' => 'ID', 'name' => 'Aceh Singkil', 'active' => 1, 'slug' => 'aceh-singkil'],
            ['id' => 274723, 'region_id' => 781986, 'country_code' => 'ID', 'name' => 'Aceh Tamiang', 'active' => 1, 'slug' => 'aceh-tamiang'],
            ['id' => 274724, 'region_id' => 781986, 'country_code' => 'ID', 'name' => 'Bener Meriah', 'active' => 1, 'slug' => 'bener-meriah'],
            ['id' => 274725, 'region_id' => 781986, 'country_code' => 'ID', 'name' => 'Bireuën', 'active' => 1, 'slug' => 'bireuen'],
            ['id' => 274726, 'region_id' => 781986, 'country_code' => 'ID', 'name' => 'Central Aceh', 'active' => 1, 'slug' => 'central-aceh'],
            ['id' => 274727, 'region_id' => 781986, 'country_code' => 'ID', 'name' => 'East Aceh', 'active' => 1, 'slug' => 'east-aceh'],
            ['id' => 274728, 'region_id' => 781986, 'country_code' => 'ID', 'name' => 'Gayo Lues', 'active' => 1, 'slug' => 'gayo-lues'],
            ['id' => 274729, 'region_id' => 781986, 'country_code' => 'ID', 'name' => 'Nagan Raya', 'active' => 1, 'slug' => 'nagan-raya'],
            ['id' => 274730, 'region_id' => 781986, 'country_code' => 'ID', 'name' => 'North Aceh', 'active' => 1, 'slug' => 'north-aceh'],
            ['id' => 274731, 'region_id' => 781986, 'country_code' => 'ID', 'name' => 'Pidie', 'active' => 1, 'slug' => 'pidie'],
            ['id' => 274732, 'region_id' => 781986, 'country_code' => 'ID', 'name' => 'Pidie Jaya', 'active' => 1, 'slug' => 'pidie-jaya'],
            ['id' => 274733, 'region_id' => 781986, 'country_code' => 'ID', 'name' => 'Simeulue', 'active' => 1, 'slug' => 'simeulue'],
            ['id' => 274734, 'region_id' => 781986, 'country_code' => 'ID', 'name' => 'South Aceh', 'active' => 1, 'slug' => 'south-aceh'],
            ['id' => 274735, 'region_id' => 781986, 'country_code' => 'ID', 'name' => 'Southeast Aceh', 'active' => 1, 'slug' => 'southeast-aceh'],
            ['id' => 274736, 'region_id' => 781986, 'country_code' => 'ID', 'name' => 'Southwest Aceh', 'active' => 1, 'slug' => 'southwest-aceh'],
            ['id' => 274737, 'region_id' => 781986, 'country_code' => 'ID', 'name' => 'West Aceh', 'active' => 1, 'slug' => 'west-aceh'],
            ['id' => 274738, 'region_id' => 781986, 'country_code' => 'ID', 'name' => 'Banda Aceh', 'active' => 1, 'slug' => 'banda-aceh'],
            ['id' => 274739, 'region_id' => 781986, 'country_code' => 'ID', 'name' => 'Langsa', 'active' => 1, 'slug' => 'langsa'],
            ['id' => 274740, 'region_id' => 781986, 'country_code' => 'ID', 'name' => 'Lhokseumawe', 'active' => 1, 'slug' => 'lhokseumawe'],
            ['id' => 274741, 'region_id' => 781986, 'country_code' => 'ID', 'name' => 'Sabang', 'active' => 1, 'slug' => 'sabang'],
            ['id' => 274742, 'region_id' => 781986, 'country_code' => 'ID', 'name' => 'Subulussalam', 'active' => 1, 'slug' => 'subulussalam'],
            ['id' => 274743, 'region_id' => 781987, 'country_code' => 'ID', 'name' => 'Badung', 'active' => 1, 'slug' => 'badung'],
            ['id' => 274744, 'region_id' => 781987, 'country_code' => 'ID', 'name' => 'Bangli', 'active' => 1, 'slug' => 'bangli'],
            ['id' => 274745, 'region_id' => 781987, 'country_code' => 'ID', 'name' => 'Buleleng', 'active' => 1, 'slug' => 'buleleng'],
            ['id' => 274746, 'region_id' => 781987, 'country_code' => 'ID', 'name' => 'Gianyar', 'active' => 1, 'slug' => 'gianyar'],
            ['id' => 274747, 'region_id' => 781987, 'country_code' => 'ID', 'name' => 'Jembrana', 'active' => 1, 'slug' => 'jembrana'],
            ['id' => 274748, 'region_id' => 781987, 'country_code' => 'ID', 'name' => 'Karangasem', 'active' => 1, 'slug' => 'karangasem'],
            ['id' => 274749, 'region_id' => 781987, 'country_code' => 'ID', 'name' => 'Klungkung', 'active' => 1, 'slug' => 'klungkung'],
            ['id' => 274750, 'region_id' => 781987, 'country_code' => 'ID', 'name' => 'Tabanan', 'active' => 1, 'slug' => 'tabanan'],
            ['id' => 274751, 'region_id' => 781987, 'country_code' => 'ID', 'name' => 'Denpasar', 'active' => 1, 'slug' => 'denpasar'],
            ['id' => 274752, 'region_id' => 781988, 'country_code' => 'ID', 'name' => 'Bangka', 'active' => 1, 'slug' => 'bangka'],
            ['id' => 274753, 'region_id' => 781988, 'country_code' => 'ID', 'name' => 'Belitung', 'active' => 1, 'slug' => 'belitung'],
            ['id' => 274754, 'region_id' => 781988, 'country_code' => 'ID', 'name' => 'Central Bangka', 'active' => 1, 'slug' => 'central-bangka'],
            ['id' => 274755, 'region_id' => 781988, 'country_code' => 'ID', 'name' => 'East Belitung', 'active' => 1, 'slug' => 'east-belitung'],
            ['id' => 274756, 'region_id' => 781988, 'country_code' => 'ID', 'name' => 'South Bangka', 'active' => 1, 'slug' => 'south-bangka'],
            ['id' => 274757, 'region_id' => 781988, 'country_code' => 'ID', 'name' => 'West Bangka', 'active' => 1, 'slug' => 'west-bangka'],
            ['id' => 274758, 'region_id' => 781988, 'country_code' => 'ID', 'name' => 'Pangkal Pinang', 'active' => 1, 'slug' => 'pangkal-pinang'],
            ['id' => 274759, 'region_id' => 781989, 'country_code' => 'ID', 'name' => 'Lebak', 'active' => 1, 'slug' => 'lebak'],
            ['id' => 274760, 'region_id' => 781989, 'country_code' => 'ID', 'name' => 'Pandeglang', 'active' => 1, 'slug' => 'pandeglang'],
            ['id' => 274761, 'region_id' => 781989, 'country_code' => 'ID', 'name' => 'Serang', 'active' => 1, 'slug' => 'serang'],
            ['id' => 274762, 'region_id' => 781989, 'country_code' => 'ID', 'name' => 'Cilegon', 'active' => 1, 'slug' => 'cilegon'],
            ['id' => 274763, 'region_id' => 781989, 'country_code' => 'ID', 'name' => 'South Tangerang', 'active' => 1, 'slug' => 'south-tangerang'],
            ['id' => 274764, 'region_id' => 781989, 'country_code' => 'ID', 'name' => 'Tangerang', 'active' => 1, 'slug' => 'tangerang'],
            ['id' => 274765, 'region_id' => 781990, 'country_code' => 'ID', 'name' => 'Central Bengkulu', 'active' => 1, 'slug' => 'central-bengkulu'],
            ['id' => 274766, 'region_id' => 781990, 'country_code' => 'ID', 'name' => 'Kaur', 'active' => 1, 'slug' => 'kaur'],
            ['id' => 274767, 'region_id' => 781990, 'country_code' => 'ID', 'name' => 'Kepahiang', 'active' => 1, 'slug' => 'kepahiang'],
            ['id' => 274768, 'region_id' => 781990, 'country_code' => 'ID', 'name' => 'Lebong', 'active' => 1, 'slug' => 'lebong'],
            ['id' => 274769, 'region_id' => 781990, 'country_code' => 'ID', 'name' => 'Muko-Muko', 'active' => 1, 'slug' => 'muko-muko'],
            ['id' => 274770, 'region_id' => 781990, 'country_code' => 'ID', 'name' => 'North Bengkulu', 'active' => 1, 'slug' => 'north-bengkulu'],
            ['id' => 274771, 'region_id' => 781990, 'country_code' => 'ID', 'name' => 'Rejang Lebong', 'active' => 1, 'slug' => 'rejang-lebong'],
            ['id' => 274772, 'region_id' => 781990, 'country_code' => 'ID', 'name' => 'Seluma', 'active' => 1, 'slug' => 'seluma'],
            ['id' => 274773, 'region_id' => 781990, 'country_code' => 'ID', 'name' => 'South Bengkulu', 'active' => 1, 'slug' => 'south-bengkulu'],
            ['id' => 274774, 'region_id' => 781990, 'country_code' => 'ID', 'name' => 'Bengkulu', 'active' => 1, 'slug' => 'bengkulu'],
            ['id' => 274775, 'region_id' => 781991, 'country_code' => 'ID', 'name' => 'Banjarnegara', 'active' => 1, 'slug' => 'banjarnegara'],
            ['id' => 274776, 'region_id' => 781991, 'country_code' => 'ID', 'name' => 'Banyumas', 'active' => 1, 'slug' => 'banyumas'],
            ['id' => 274777, 'region_id' => 781991, 'country_code' => 'ID', 'name' => 'Batang', 'active' => 1, 'slug' => 'batang'],
            ['id' => 274778, 'region_id' => 781991, 'country_code' => 'ID', 'name' => 'Blora Regency', 'active' => 1, 'slug' => 'blora-regency'],
            ['id' => 274779, 'region_id' => 781991, 'country_code' => 'ID', 'name' => 'Boyolali', 'active' => 1, 'slug' => 'boyolali'],
            ['id' => 274780, 'region_id' => 781991, 'country_code' => 'ID', 'name' => 'Brebes', 'active' => 1, 'slug' => 'brebes'],
            ['id' => 274781, 'region_id' => 781991, 'country_code' => 'ID', 'name' => 'Cilacap', 'active' => 1, 'slug' => 'cilacap'],
            ['id' => 274782, 'region_id' => 781991, 'country_code' => 'ID', 'name' => 'Demak', 'active' => 1, 'slug' => 'demak'],
            ['id' => 274783, 'region_id' => 781991, 'country_code' => 'ID', 'name' => 'Grobogan', 'active' => 1, 'slug' => 'grobogan'],
            ['id' => 274784, 'region_id' => 781991, 'country_code' => 'ID', 'name' => 'Jepara', 'active' => 1, 'slug' => 'jepara'],
            ['id' => 274785, 'region_id' => 781991, 'country_code' => 'ID', 'name' => 'Karanganyar', 'active' => 1, 'slug' => 'karanganyar'],
            ['id' => 274786, 'region_id' => 781991, 'country_code' => 'ID', 'name' => 'Kebumen', 'active' => 1, 'slug' => 'kebumen'],
            ['id' => 274787, 'region_id' => 781991, 'country_code' => 'ID', 'name' => 'Kendal', 'active' => 1, 'slug' => 'kendal'],
            ['id' => 274788, 'region_id' => 781991, 'country_code' => 'ID', 'name' => 'Klaten', 'active' => 1, 'slug' => 'klaten'],
            ['id' => 274789, 'region_id' => 781991, 'country_code' => 'ID', 'name' => 'Magelang', 'active' => 1, 'slug' => 'magelang'],
            ['id' => 274790, 'region_id' => 781991, 'country_code' => 'ID', 'name' => 'Pati', 'active' => 1, 'slug' => 'pati'],
            ['id' => 274791, 'region_id' => 781991, 'country_code' => 'ID', 'name' => 'Pekalongan', 'active' => 1, 'slug' => 'pekalongan'],
            ['id' => 274792, 'region_id' => 781991, 'country_code' => 'ID', 'name' => 'Pemalang', 'active' => 1, 'slug' => 'pemalang'],
            ['id' => 274793, 'region_id' => 781991, 'country_code' => 'ID', 'name' => 'Purbalingga', 'active' => 1, 'slug' => 'purbalingga'],
            ['id' => 274794, 'region_id' => 781991, 'country_code' => 'ID', 'name' => 'Purworejo', 'active' => 1, 'slug' => 'purworejo'],
            ['id' => 274795, 'region_id' => 781991, 'country_code' => 'ID', 'name' => 'Rembang', 'active' => 1, 'slug' => 'rembang'],
            ['id' => 274796, 'region_id' => 781991, 'country_code' => 'ID', 'name' => 'Semarang', 'active' => 1, 'slug' => 'semarang'],
            ['id' => 274797, 'region_id' => 781991, 'country_code' => 'ID', 'name' => 'Sragen', 'active' => 1, 'slug' => 'sragen'],
            ['id' => 274798, 'region_id' => 781991, 'country_code' => 'ID', 'name' => 'Sukoharjo', 'active' => 1, 'slug' => 'sukoharjo'],
            ['id' => 274799, 'region_id' => 781991, 'country_code' => 'ID', 'name' => 'Tegal', 'active' => 1, 'slug' => 'tegal'],
            ['id' => 274800, 'region_id' => 781991, 'country_code' => 'ID', 'name' => 'Temanggung', 'active' => 1, 'slug' => 'temanggung'],
            ['id' => 274801, 'region_id' => 781991, 'country_code' => 'ID', 'name' => 'Wonogiri', 'active' => 1, 'slug' => 'wonogiri'],
            ['id' => 274802, 'region_id' => 781991, 'country_code' => 'ID', 'name' => 'Wonosobo', 'active' => 1, 'slug' => 'wonosobo'],
            ['id' => 274803, 'region_id' => 781991, 'country_code' => 'ID', 'name' => 'Surakarta', 'active' => 1, 'slug' => 'surakarta'],
            ['id' => 274804, 'region_id' => 781991, 'country_code' => 'ID', 'name' => 'Salatiga', 'active' => 1, 'slug' => 'salatiga'],
            ['id' => 274805, 'region_id' => 781991, 'country_code' => 'ID', 'name' => 'Kudus', 'active' => 1, 'slug' => 'kudus'],
            ['id' => 274806, 'region_id' => 781992, 'country_code' => 'ID', 'name' => 'East Barito', 'active' => 1, 'slug' => 'east-barito'],
            ['id' => 274807, 'region_id' => 781992, 'country_code' => 'ID', 'name' => 'East Kotawaringin', 'active' => 1, 'slug' => 'east-kotawaringin'],
            ['id' => 274808, 'region_id' => 781992, 'country_code' => 'ID', 'name' => 'Gunung Mas', 'active' => 1, 'slug' => 'gunung-mas'],
            ['id' => 274809, 'region_id' => 781992, 'country_code' => 'ID', 'name' => 'Kapuas', 'active' => 1, 'slug' => 'kapuas'],
            ['id' => 274810, 'region_id' => 781992, 'country_code' => 'ID', 'name' => 'Katingan', 'active' => 1, 'slug' => 'katingan'],
            ['id' => 274811, 'region_id' => 781992, 'country_code' => 'ID', 'name' => 'Lamandau', 'active' => 1, 'slug' => 'lamandau'],
            ['id' => 274812, 'region_id' => 781992, 'country_code' => 'ID', 'name' => 'Murung Raya', 'active' => 1, 'slug' => 'murung-raya'],
            ['id' => 274813, 'region_id' => 781992, 'country_code' => 'ID', 'name' => 'North Barito', 'active' => 1, 'slug' => 'north-barito'],
            ['id' => 274814, 'region_id' => 781992, 'country_code' => 'ID', 'name' => 'Pulang Pisang', 'active' => 1, 'slug' => 'pulang-pisang'],
            ['id' => 274815, 'region_id' => 781992, 'country_code' => 'ID', 'name' => 'Sukamara', 'active' => 1, 'slug' => 'sukamara'],
            ['id' => 274816, 'region_id' => 781992, 'country_code' => 'ID', 'name' => 'Seruyan', 'active' => 1, 'slug' => 'seruyan'],
            ['id' => 274817, 'region_id' => 781992, 'country_code' => 'ID', 'name' => 'South Barito', 'active' => 1, 'slug' => 'south-barito'],
            ['id' => 274818, 'region_id' => 781992, 'country_code' => 'ID', 'name' => 'West Kotawaringin', 'active' => 1, 'slug' => 'west-kotawaringin'],
            ['id' => 274819, 'region_id' => 781992, 'country_code' => 'ID', 'name' => 'Palangkaraya', 'active' => 1, 'slug' => 'palangkaraya'],
            ['id' => 274820, 'region_id' => 781993, 'country_code' => 'ID', 'name' => 'Banggai', 'active' => 1, 'slug' => 'banggai'],
            ['id' => 274821, 'region_id' => 781993, 'country_code' => 'ID', 'name' => 'Banggai Islands', 'active' => 1, 'slug' => 'banggai-islands'],
            ['id' => 274822, 'region_id' => 781993, 'country_code' => 'ID', 'name' => 'Buol', 'active' => 1, 'slug' => 'buol'],
            ['id' => 274823, 'region_id' => 781993, 'country_code' => 'ID', 'name' => 'Donggala', 'active' => 1, 'slug' => 'donggala'],
            ['id' => 274824, 'region_id' => 781993, 'country_code' => 'ID', 'name' => 'Morowali', 'active' => 1, 'slug' => 'morowali'],
            ['id' => 274825, 'region_id' => 781993, 'country_code' => 'ID', 'name' => 'Parigi Moutong', 'active' => 1, 'slug' => 'parigi-moutong'],
            ['id' => 274826, 'region_id' => 781993, 'country_code' => 'ID', 'name' => 'Poso', 'active' => 1, 'slug' => 'poso'],
            ['id' => 274827, 'region_id' => 781993, 'country_code' => 'ID', 'name' => 'Sigi', 'active' => 1, 'slug' => 'sigi'],
            ['id' => 274828, 'region_id' => 781993, 'country_code' => 'ID', 'name' => 'Tojo Una-Una', 'active' => 1, 'slug' => 'tojo-una-una'],
            ['id' => 274829, 'region_id' => 781993, 'country_code' => 'ID', 'name' => 'Toli-Toli', 'active' => 1, 'slug' => 'toli-toli'],
            ['id' => 274830, 'region_id' => 781993, 'country_code' => 'ID', 'name' => 'Palu', 'active' => 1, 'slug' => 'palu'],
            ['id' => 274831, 'region_id' => 781994, 'country_code' => 'ID', 'name' => 'Bangkalan Regency', 'active' => 1, 'slug' => 'bangkalan-regency'],
            ['id' => 274832, 'region_id' => 781994, 'country_code' => 'ID', 'name' => 'Banyuwangi', 'active' => 1, 'slug' => 'banyuwangi'],
            ['id' => 274833, 'region_id' => 781994, 'country_code' => 'ID', 'name' => 'Blitar', 'active' => 1, 'slug' => 'blitar'],
            ['id' => 274834, 'region_id' => 781994, 'country_code' => 'ID', 'name' => 'Bojonegoro', 'active' => 1, 'slug' => 'bojonegoro'],
            ['id' => 274835, 'region_id' => 781994, 'country_code' => 'ID', 'name' => 'Bondowoso', 'active' => 1, 'slug' => 'bondowoso'],
            ['id' => 274836, 'region_id' => 781994, 'country_code' => 'ID', 'name' => 'Gresik', 'active' => 1, 'slug' => 'gresik'],
            ['id' => 274837, 'region_id' => 781994, 'country_code' => 'ID', 'name' => 'Jember', 'active' => 1, 'slug' => 'jember'],
            ['id' => 274838, 'region_id' => 781994, 'country_code' => 'ID', 'name' => 'Jombang', 'active' => 1, 'slug' => 'jombang'],
            ['id' => 274839, 'region_id' => 781994, 'country_code' => 'ID', 'name' => 'Kediri', 'active' => 1, 'slug' => 'kediri'],
            ['id' => 274840, 'region_id' => 781994, 'country_code' => 'ID', 'name' => 'Lamongan', 'active' => 1, 'slug' => 'lamongan'],
            ['id' => 274841, 'region_id' => 781994, 'country_code' => 'ID', 'name' => 'Lumajang', 'active' => 1, 'slug' => 'lumajang'],
            ['id' => 274842, 'region_id' => 781994, 'country_code' => 'ID', 'name' => 'Madiun', 'active' => 1, 'slug' => 'madiun'],
            ['id' => 274843, 'region_id' => 781994, 'country_code' => 'ID', 'name' => 'Magetan', 'active' => 1, 'slug' => 'magetan'],
            ['id' => 274844, 'region_id' => 781994, 'country_code' => 'ID', 'name' => 'Malang', 'active' => 1, 'slug' => 'malang'],
            ['id' => 274845, 'region_id' => 781994, 'country_code' => 'ID', 'name' => 'Mojokerto', 'active' => 1, 'slug' => 'mojokerto'],
            ['id' => 274846, 'region_id' => 781994, 'country_code' => 'ID', 'name' => 'Ngawi Regency', 'active' => 1, 'slug' => 'ngawi-regency'],
            ['id' => 274847, 'region_id' => 781994, 'country_code' => 'ID', 'name' => 'Pacitan', 'active' => 1, 'slug' => 'pacitan'],
            ['id' => 274848, 'region_id' => 781994, 'country_code' => 'ID', 'name' => 'Pasuruan', 'active' => 1, 'slug' => 'pasuruan'],
            ['id' => 274849, 'region_id' => 781994, 'country_code' => 'ID', 'name' => 'Ponorogo', 'active' => 1, 'slug' => 'ponorogo'],
            ['id' => 274850, 'region_id' => 781994, 'country_code' => 'ID', 'name' => 'Probolinggo', 'active' => 1, 'slug' => 'probolinggo'],
            ['id' => 274851, 'region_id' => 781994, 'country_code' => 'ID', 'name' => 'Sampang', 'active' => 1, 'slug' => 'sampang'],
            ['id' => 274852, 'region_id' => 781994, 'country_code' => 'ID', 'name' => 'Sidoarjo', 'active' => 1, 'slug' => 'sidoarjo'],
            ['id' => 274853, 'region_id' => 781994, 'country_code' => 'ID', 'name' => 'Situbondo', 'active' => 1, 'slug' => 'situbondo'],
            ['id' => 274854, 'region_id' => 781994, 'country_code' => 'ID', 'name' => 'Sumenep', 'active' => 1, 'slug' => 'sumenep'],
            ['id' => 274855, 'region_id' => 781994, 'country_code' => 'ID', 'name' => 'Trenggalek', 'active' => 1, 'slug' => 'trenggalek'],
            ['id' => 274856, 'region_id' => 781994, 'country_code' => 'ID', 'name' => 'Tuban', 'active' => 1, 'slug' => 'tuban'],
            ['id' => 274857, 'region_id' => 781994, 'country_code' => 'ID', 'name' => 'Tulungagung', 'active' => 1, 'slug' => 'tulungagung'],
            ['id' => 274858, 'region_id' => 781994, 'country_code' => 'ID', 'name' => 'Batu', 'active' => 1, 'slug' => 'batu'],
            ['id' => 274859, 'region_id' => 781994, 'country_code' => 'ID', 'name' => 'Surabaya', 'active' => 1, 'slug' => 'surabaya'],
            ['id' => 274860, 'region_id' => 781994, 'country_code' => 'ID', 'name' => 'Nganjuk', 'active' => 1, 'slug' => 'nganjuk'],
            ['id' => 274861, 'region_id' => 781994, 'country_code' => 'ID', 'name' => 'Pamekasan', 'active' => 1, 'slug' => 'pamekasan'],
            ['id' => 274862, 'region_id' => 781995, 'country_code' => 'ID', 'name' => 'Berau', 'active' => 1, 'slug' => 'berau'],
            ['id' => 274863, 'region_id' => 781995, 'country_code' => 'ID', 'name' => 'Bulungan', 'active' => 1, 'slug' => 'bulungan'],
            ['id' => 274864, 'region_id' => 781995, 'country_code' => 'ID', 'name' => 'East Kutai', 'active' => 1, 'slug' => 'east-kutai'],
            ['id' => 274865, 'region_id' => 781995, 'country_code' => 'ID', 'name' => 'Kutai Kartanegara', 'active' => 1, 'slug' => 'kutai-kartanegara'],
            ['id' => 274866, 'region_id' => 781995, 'country_code' => 'ID', 'name' => 'Malinau', 'active' => 1, 'slug' => 'malinau'],
            ['id' => 274867, 'region_id' => 781995, 'country_code' => 'ID', 'name' => 'North Penajam Paser', 'active' => 1, 'slug' => 'north-penajam-paser'],
            ['id' => 274868, 'region_id' => 781995, 'country_code' => 'ID', 'name' => 'Nunukan', 'active' => 1, 'slug' => 'nunukan'],
            ['id' => 274869, 'region_id' => 781995, 'country_code' => 'ID', 'name' => 'Paser', 'active' => 1, 'slug' => 'paser'],
            ['id' => 274870, 'region_id' => 781995, 'country_code' => 'ID', 'name' => 'Tana Tidung', 'active' => 1, 'slug' => 'tana-tidung'],
            ['id' => 274871, 'region_id' => 781995, 'country_code' => 'ID', 'name' => 'West Kutai', 'active' => 1, 'slug' => 'west-kutai'],
            ['id' => 274872, 'region_id' => 781995, 'country_code' => 'ID', 'name' => 'Tarakan', 'active' => 1, 'slug' => 'tarakan'],
            ['id' => 274873, 'region_id' => 781995, 'country_code' => 'ID', 'name' => 'Bontang', 'active' => 1, 'slug' => 'bontang'],
            ['id' => 274874, 'region_id' => 781995, 'country_code' => 'ID', 'name' => 'Samarinda', 'active' => 1, 'slug' => 'samarinda'],
            ['id' => 274875, 'region_id' => 781995, 'country_code' => 'ID', 'name' => 'Balikpapan', 'active' => 1, 'slug' => 'balikpapan'],
            ['id' => 274876, 'region_id' => 781996, 'country_code' => 'ID', 'name' => 'Alor', 'active' => 1, 'slug' => 'alor'],
            ['id' => 274877, 'region_id' => 781996, 'country_code' => 'ID', 'name' => 'Belu', 'active' => 1, 'slug' => 'belu'],
            ['id' => 274878, 'region_id' => 781996, 'country_code' => 'ID', 'name' => 'Central Sumba', 'active' => 1, 'slug' => 'central-sumba'],
            ['id' => 274879, 'region_id' => 781996, 'country_code' => 'ID', 'name' => 'East Flores', 'active' => 1, 'slug' => 'east-flores'],
            ['id' => 274880, 'region_id' => 781996, 'country_code' => 'ID', 'name' => 'East Manggarai', 'active' => 1, 'slug' => 'east-manggarai'],
            ['id' => 274881, 'region_id' => 781996, 'country_code' => 'ID', 'name' => 'East Sumba', 'active' => 1, 'slug' => 'east-sumba'],
            ['id' => 274882, 'region_id' => 781996, 'country_code' => 'ID', 'name' => 'Ende', 'active' => 1, 'slug' => 'ende'],
            ['id' => 274883, 'region_id' => 781996, 'country_code' => 'ID', 'name' => 'Kupang', 'active' => 1, 'slug' => 'kupang'],
            ['id' => 274884, 'region_id' => 781996, 'country_code' => 'ID', 'name' => 'Lembata', 'active' => 1, 'slug' => 'lembata'],
            ['id' => 274885, 'region_id' => 781996, 'country_code' => 'ID', 'name' => 'Manggarai', 'active' => 1, 'slug' => 'manggarai'],
            ['id' => 274886, 'region_id' => 781996, 'country_code' => 'ID', 'name' => 'Nagekeo', 'active' => 1, 'slug' => 'nagekeo'],
            ['id' => 274887, 'region_id' => 781996, 'country_code' => 'ID', 'name' => 'Ngada', 'active' => 1, 'slug' => 'ngada'],
            ['id' => 274888, 'region_id' => 781996, 'country_code' => 'ID', 'name' => 'North Central Timor', 'active' => 1, 'slug' => 'north-central-timor'],
            ['id' => 274889, 'region_id' => 781996, 'country_code' => 'ID', 'name' => 'Rote Ndao', 'active' => 1, 'slug' => 'rote-ndao'],
            ['id' => 274890, 'region_id' => 781996, 'country_code' => 'ID', 'name' => 'Sabu Raijua', 'active' => 1, 'slug' => 'sabu-raijua'],
            ['id' => 274891, 'region_id' => 781996, 'country_code' => 'ID', 'name' => 'Sikka', 'active' => 1, 'slug' => 'sikka'],
            ['id' => 274892, 'region_id' => 781996, 'country_code' => 'ID', 'name' => 'South Central Timor', 'active' => 1, 'slug' => 'south-central-timor'],
            ['id' => 274893, 'region_id' => 781996, 'country_code' => 'ID', 'name' => 'Southwest Sumba', 'active' => 1, 'slug' => 'southwest-sumba'],
            ['id' => 274894, 'region_id' => 781996, 'country_code' => 'ID', 'name' => 'West Manggarai', 'active' => 1, 'slug' => 'west-manggarai'],
            ['id' => 274895, 'region_id' => 781996, 'country_code' => 'ID', 'name' => 'West Sumba', 'active' => 1, 'slug' => 'west-sumba'],
            ['id' => 274896, 'region_id' => 781997, 'country_code' => 'ID', 'name' => 'Boalemo', 'active' => 1, 'slug' => 'boalemo'],
            ['id' => 274897, 'region_id' => 781997, 'country_code' => 'ID', 'name' => 'Bone Bolango', 'active' => 1, 'slug' => 'bone-bolango'],
            ['id' => 274898, 'region_id' => 781997, 'country_code' => 'ID', 'name' => 'Gorontalo', 'active' => 1, 'slug' => 'gorontalo'],
            ['id' => 274899, 'region_id' => 781997, 'country_code' => 'ID', 'name' => 'North Gorontalo', 'active' => 1, 'slug' => 'north-gorontalo'],
            ['id' => 274900, 'region_id' => 781997, 'country_code' => 'ID', 'name' => 'Pahuwato', 'active' => 1, 'slug' => 'pahuwato'],
            ['id' => 274902, 'region_id' => 781998, 'country_code' => 'ID', 'name' => 'Jakarta', 'active' => 1, 'slug' => 'jakarta'],
            ['id' => 274901, 'region_id' => 781998, 'country_code' => 'ID', 'name' => 'Seribu Islands', 'active' => 1, 'slug' => 'seribu-islands'],
            ['id' => 274903, 'region_id' => 781999, 'country_code' => 'ID', 'name' => 'Batang Hari', 'active' => 1, 'slug' => 'batang-hari'],
            ['id' => 274904, 'region_id' => 781999, 'country_code' => 'ID', 'name' => 'Bungo', 'active' => 1, 'slug' => 'bungo'],
            ['id' => 274905, 'region_id' => 781999, 'country_code' => 'ID', 'name' => 'Kerinci', 'active' => 1, 'slug' => 'kerinci'],
            ['id' => 274906, 'region_id' => 781999, 'country_code' => 'ID', 'name' => 'Merangin', 'active' => 1, 'slug' => 'merangin'],
            ['id' => 274907, 'region_id' => 781999, 'country_code' => 'ID', 'name' => 'Muaro Jambi', 'active' => 1, 'slug' => 'muaro-jambi'],
            ['id' => 274908, 'region_id' => 781999, 'country_code' => 'ID', 'name' => 'Sarolangun', 'active' => 1, 'slug' => 'sarolangun'],
            ['id' => 274909, 'region_id' => 781999, 'country_code' => 'ID', 'name' => 'East Tanjung Jabung', 'active' => 1, 'slug' => 'east-tanjung-jabung'],
            ['id' => 274910, 'region_id' => 781999, 'country_code' => 'ID', 'name' => 'West Tanjung Jabung', 'active' => 1, 'slug' => 'west-tanjung-jabung'],
            ['id' => 274911, 'region_id' => 781999, 'country_code' => 'ID', 'name' => 'Tebo', 'active' => 1, 'slug' => 'tebo'],
            ['id' => 274912, 'region_id' => 781999, 'country_code' => 'ID', 'name' => 'Jambi', 'active' => 1, 'slug' => 'jambi'],
            ['id' => 274913, 'region_id' => 781999, 'country_code' => 'ID', 'name' => 'Sungai Penuh', 'active' => 1, 'slug' => 'sungai-penuh'],
            ['id' => 274914, 'region_id' => 782000, 'country_code' => 'ID', 'name' => 'Central Lampung', 'active' => 1, 'slug' => 'central-lampung'],
            ['id' => 274915, 'region_id' => 782000, 'country_code' => 'ID', 'name' => 'East Lampung', 'active' => 1, 'slug' => 'east-lampung'],
            ['id' => 274916, 'region_id' => 782000, 'country_code' => 'ID', 'name' => 'Mesuji', 'active' => 1, 'slug' => 'mesuji'],
            ['id' => 274917, 'region_id' => 782000, 'country_code' => 'ID', 'name' => 'North Lampung', 'active' => 1, 'slug' => 'north-lampung'],
            ['id' => 274918, 'region_id' => 782000, 'country_code' => 'ID', 'name' => 'Pesawaran', 'active' => 1, 'slug' => 'pesawaran'],
            ['id' => 274919, 'region_id' => 782000, 'country_code' => 'ID', 'name' => 'Pringsewu', 'active' => 1, 'slug' => 'pringsewu'],
            ['id' => 274920, 'region_id' => 782000, 'country_code' => 'ID', 'name' => 'South Lampung', 'active' => 1, 'slug' => 'south-lampung'],
            ['id' => 274921, 'region_id' => 782000, 'country_code' => 'ID', 'name' => 'Tanggamus', 'active' => 1, 'slug' => 'tanggamus'],
            ['id' => 274922, 'region_id' => 782000, 'country_code' => 'ID', 'name' => 'Tulang Bawang', 'active' => 1, 'slug' => 'tulang-bawang'],
            ['id' => 274923, 'region_id' => 782000, 'country_code' => 'ID', 'name' => 'Way Kanan', 'active' => 1, 'slug' => 'way-kanan'],
            ['id' => 274924, 'region_id' => 782000, 'country_code' => 'ID', 'name' => 'West Lampung', 'active' => 1, 'slug' => 'west-lampung'],
            ['id' => 274925, 'region_id' => 782000, 'country_code' => 'ID', 'name' => 'West Tulang Bawang', 'active' => 1, 'slug' => 'west-tulang-bawang'],
            ['id' => 274926, 'region_id' => 782000, 'country_code' => 'ID', 'name' => 'Metro', 'active' => 1, 'slug' => 'metro'],
            ['id' => 274927, 'region_id' => 782000, 'country_code' => 'ID', 'name' => 'Bandar Lampung', 'active' => 1, 'slug' => 'bandar-lampung'],
            ['id' => 274928, 'region_id' => 782001, 'country_code' => 'ID', 'name' => 'Aru Islands', 'active' => 1, 'slug' => 'aru-islands'],
            ['id' => 274929, 'region_id' => 782001, 'country_code' => 'ID', 'name' => 'Buru', 'active' => 1, 'slug' => 'buru'],
            ['id' => 274930, 'region_id' => 782001, 'country_code' => 'ID', 'name' => 'Central Maluku', 'active' => 1, 'slug' => 'central-maluku'],
            ['id' => 274931, 'region_id' => 782001, 'country_code' => 'ID', 'name' => 'Eastern Seram', 'active' => 1, 'slug' => 'eastern-seram'],
            ['id' => 274932, 'region_id' => 782001, 'country_code' => 'ID', 'name' => 'South Buru', 'active' => 1, 'slug' => 'south-buru'],
            ['id' => 274933, 'region_id' => 782001, 'country_code' => 'ID', 'name' => 'Southeast Maluku', 'active' => 1, 'slug' => 'southeast-maluku'],
            ['id' => 274934, 'region_id' => 782001, 'country_code' => 'ID', 'name' => 'Southwest Maluku', 'active' => 1, 'slug' => 'southwest-maluku'],
            ['id' => 274935, 'region_id' => 782001, 'country_code' => 'ID', 'name' => 'Western Seram', 'active' => 1, 'slug' => 'western-seram'],
            ['id' => 274936, 'region_id' => 782001, 'country_code' => 'ID', 'name' => 'Western Southeast Maluku', 'active' => 1, 'slug' => 'western-southeast-maluku'],
            ['id' => 274937, 'region_id' => 782001, 'country_code' => 'ID', 'name' => 'Ambon', 'active' => 1, 'slug' => 'ambon'],
            ['id' => 274938, 'region_id' => 782001, 'country_code' => 'ID', 'name' => 'Tual', 'active' => 1, 'slug' => 'tual'],
            ['id' => 274939, 'region_id' => 782002, 'country_code' => 'ID', 'name' => 'Central Halmahera', 'active' => 1, 'slug' => 'central-halmahera'],
            ['id' => 274940, 'region_id' => 782002, 'country_code' => 'ID', 'name' => 'East Halmahera', 'active' => 1, 'slug' => 'east-halmahera'],
            ['id' => 274941, 'region_id' => 782002, 'country_code' => 'ID', 'name' => 'Morotai Islands', 'active' => 1, 'slug' => 'morotai-islands'],
            ['id' => 274942, 'region_id' => 782002, 'country_code' => 'ID', 'name' => 'North Halmahera', 'active' => 1, 'slug' => 'north-halmahera'],
            ['id' => 274943, 'region_id' => 782002, 'country_code' => 'ID', 'name' => 'South Halmahera', 'active' => 1, 'slug' => 'south-halmahera'],
            ['id' => 274944, 'region_id' => 782002, 'country_code' => 'ID', 'name' => 'Sula Islands', 'active' => 1, 'slug' => 'sula-islands'],
            ['id' => 274945, 'region_id' => 782002, 'country_code' => 'ID', 'name' => 'West Halmahera', 'active' => 1, 'slug' => 'west-halmahera'],
            ['id' => 274946, 'region_id' => 782002, 'country_code' => 'ID', 'name' => 'Ternate', 'active' => 1, 'slug' => 'ternate'],
            ['id' => 274947, 'region_id' => 782002, 'country_code' => 'ID', 'name' => 'Tidore Islands', 'active' => 1, 'slug' => 'tidore-islands'],
            ['id' => 274948, 'region_id' => 782003, 'country_code' => 'ID', 'name' => 'Bolaang Mongondow Regency', 'active' => 1, 'slug' => 'bolaang-mongondow-regency'],
            ['id' => 274949, 'region_id' => 782003, 'country_code' => 'ID', 'name' => 'East Bolaang Mongondow Regency', 'active' => 1, 'slug' => 'east-bolaang-mongondow-regency'],
            ['id' => 274950, 'region_id' => 782003, 'country_code' => 'ID', 'name' => 'Minahasa Regency', 'active' => 1, 'slug' => 'minahasa-regency'],
            ['id' => 274951, 'region_id' => 782003, 'country_code' => 'ID', 'name' => 'North Bolaang Mongondow Regency', 'active' => 1, 'slug' => 'north-bolaang-mongondow-regency'],
            ['id' => 274952, 'region_id' => 782003, 'country_code' => 'ID', 'name' => 'North Minahasa Regency', 'active' => 1, 'slug' => 'north-minahasa-regency'],
            ['id' => 274953, 'region_id' => 782003, 'country_code' => 'ID', 'name' => 'Sangihe Islands Regency', 'active' => 1, 'slug' => 'sangihe-islands-regency'],
            ['id' => 274954, 'region_id' => 782003, 'country_code' => 'ID', 'name' => 'Sitaro Islands Regency', 'active' => 1, 'slug' => 'sitaro-islands-regency'],
            ['id' => 274955, 'region_id' => 782003, 'country_code' => 'ID', 'name' => 'South Bolaang Mongondow Regency', 'active' => 1, 'slug' => 'south-bolaang-mongondow-regency'],
            ['id' => 274956, 'region_id' => 782003, 'country_code' => 'ID', 'name' => 'South Minahasa Regency', 'active' => 1, 'slug' => 'south-minahasa-regency'],
            ['id' => 274957, 'region_id' => 782003, 'country_code' => 'ID', 'name' => 'Southeast Minahasa Regency', 'active' => 1, 'slug' => 'southeast-minahasa-regency'],
            ['id' => 274958, 'region_id' => 782003, 'country_code' => 'ID', 'name' => 'Talaud Islands Regency', 'active' => 1, 'slug' => 'talaud-islands-regency'],
            ['id' => 274959, 'region_id' => 782003, 'country_code' => 'ID', 'name' => 'Bitung', 'active' => 1, 'slug' => 'bitung'],
            ['id' => 274960, 'region_id' => 782003, 'country_code' => 'ID', 'name' => 'Kotamobagu', 'active' => 1, 'slug' => 'kotamobagu'],
            ['id' => 274961, 'region_id' => 782003, 'country_code' => 'ID', 'name' => 'Tomohon', 'active' => 1, 'slug' => 'tomohon'],
            ['id' => 274962, 'region_id' => 782003, 'country_code' => 'ID', 'name' => 'Manado', 'active' => 1, 'slug' => 'manado'],
            ['id' => 274963, 'region_id' => 782004, 'country_code' => 'ID', 'name' => 'Asahan', 'active' => 1, 'slug' => 'asahan'],
            ['id' => 274964, 'region_id' => 782004, 'country_code' => 'ID', 'name' => 'Batubara', 'active' => 1, 'slug' => 'batubara'],
            ['id' => 274965, 'region_id' => 782004, 'country_code' => 'ID', 'name' => 'Central Tapanuli', 'active' => 1, 'slug' => 'central-tapanuli'],
            ['id' => 274966, 'region_id' => 782004, 'country_code' => 'ID', 'name' => 'Dairi', 'active' => 1, 'slug' => 'dairi'],
            ['id' => 274967, 'region_id' => 782004, 'country_code' => 'ID', 'name' => 'Humbang Hasundutan', 'active' => 1, 'slug' => 'humbang-hasundutan'],
            ['id' => 274968, 'region_id' => 782004, 'country_code' => 'ID', 'name' => 'Karo', 'active' => 1, 'slug' => 'karo'],
            ['id' => 274969, 'region_id' => 782004, 'country_code' => 'ID', 'name' => 'Labuhan Batu', 'active' => 1, 'slug' => 'labuhan-batu'],
            ['id' => 274970, 'region_id' => 782004, 'country_code' => 'ID', 'name' => 'Langkat', 'active' => 1, 'slug' => 'langkat'],
            ['id' => 274971, 'region_id' => 782004, 'country_code' => 'ID', 'name' => 'Mandailing Natal', 'active' => 1, 'slug' => 'mandailing-natal'],
            ['id' => 274972, 'region_id' => 782004, 'country_code' => 'ID', 'name' => 'Nias', 'active' => 1, 'slug' => 'nias'],
            ['id' => 274973, 'region_id' => 782004, 'country_code' => 'ID', 'name' => 'North Labuhan Batu', 'active' => 1, 'slug' => 'north-labuhan-batu'],
            ['id' => 274974, 'region_id' => 782004, 'country_code' => 'ID', 'name' => 'North Nias', 'active' => 1, 'slug' => 'north-nias'],
            ['id' => 274975, 'region_id' => 782004, 'country_code' => 'ID', 'name' => 'North Padang Lawas', 'active' => 1, 'slug' => 'north-padang-lawas'],
            ['id' => 274976, 'region_id' => 782004, 'country_code' => 'ID', 'name' => 'North Tapanuli', 'active' => 1, 'slug' => 'north-tapanuli'],
            ['id' => 274977, 'region_id' => 782004, 'country_code' => 'ID', 'name' => 'Padang Lawas', 'active' => 1, 'slug' => 'padang-lawas'],
            ['id' => 274978, 'region_id' => 782004, 'country_code' => 'ID', 'name' => 'Pakpak Bharat', 'active' => 1, 'slug' => 'pakpak-bharat'],
            ['id' => 274979, 'region_id' => 782004, 'country_code' => 'ID', 'name' => 'Samosir', 'active' => 1, 'slug' => 'samosir'],
            ['id' => 274980, 'region_id' => 782004, 'country_code' => 'ID', 'name' => 'Serdang Bedagai', 'active' => 1, 'slug' => 'serdang-bedagai'],
            ['id' => 274981, 'region_id' => 782004, 'country_code' => 'ID', 'name' => 'Simalungun', 'active' => 1, 'slug' => 'simalungun'],
            ['id' => 274982, 'region_id' => 782004, 'country_code' => 'ID', 'name' => 'South Labuhan Batu', 'active' => 1, 'slug' => 'south-labuhan-batu'],
            ['id' => 274983, 'region_id' => 782004, 'country_code' => 'ID', 'name' => 'South Nias', 'active' => 1, 'slug' => 'south-nias'],
            ['id' => 274984, 'region_id' => 782004, 'country_code' => 'ID', 'name' => 'South Tapanuli', 'active' => 1, 'slug' => 'south-tapanuli'],
            ['id' => 274985, 'region_id' => 782004, 'country_code' => 'ID', 'name' => 'Toba Samosir', 'active' => 1, 'slug' => 'toba-samosir'],
            ['id' => 274986, 'region_id' => 782004, 'country_code' => 'ID', 'name' => 'West Nias', 'active' => 1, 'slug' => 'west-nias'],
            ['id' => 274987, 'region_id' => 782004, 'country_code' => 'ID', 'name' => 'Binjai', 'active' => 1, 'slug' => 'binjai'],
            ['id' => 274988, 'region_id' => 782004, 'country_code' => 'ID', 'name' => 'Gunungsitoli', 'active' => 1, 'slug' => 'gunungsitoli'],
            ['id' => 274989, 'region_id' => 782004, 'country_code' => 'ID', 'name' => 'Medan', 'active' => 1, 'slug' => 'medan'],
            ['id' => 274990, 'region_id' => 782004, 'country_code' => 'ID', 'name' => 'Padang Sidempuan', 'active' => 1, 'slug' => 'padang-sidempuan'],
            ['id' => 274991, 'region_id' => 782004, 'country_code' => 'ID', 'name' => 'Sibolga', 'active' => 1, 'slug' => 'sibolga'],
            ['id' => 274992, 'region_id' => 782004, 'country_code' => 'ID', 'name' => 'Tanjung Balai', 'active' => 1, 'slug' => 'tanjung-balai'],
            ['id' => 274993, 'region_id' => 782004, 'country_code' => 'ID', 'name' => 'Tebing Tinggi', 'active' => 1, 'slug' => 'tebing-tinggi'],
            ['id' => 274994, 'region_id' => 782004, 'country_code' => 'ID', 'name' => 'Pematangsiantar', 'active' => 1, 'slug' => 'pematangsiantar'],
            ['id' => 274995, 'region_id' => 782004, 'country_code' => 'ID', 'name' => 'Deli Serdang', 'active' => 1, 'slug' => 'deli-serdang'],
            ['id' => 274996, 'region_id' => 782005, 'country_code' => 'ID', 'name' => 'Asmat', 'active' => 1, 'slug' => 'asmat'],
            ['id' => 274997, 'region_id' => 782005, 'country_code' => 'ID', 'name' => 'Biak Numfor', 'active' => 1, 'slug' => 'biak-numfor'],
            ['id' => 274998, 'region_id' => 782005, 'country_code' => 'ID', 'name' => 'Boven Digoel', 'active' => 1, 'slug' => 'boven-digoel'],
            ['id' => 274999, 'region_id' => 782005, 'country_code' => 'ID', 'name' => 'Central Mamberamo', 'active' => 1, 'slug' => 'central-mamberamo'],
            ['id' => 275000, 'region_id' => 782005, 'country_code' => 'ID', 'name' => 'Deiyai', 'active' => 1, 'slug' => 'deiyai'],
            ['id' => 275001, 'region_id' => 782005, 'country_code' => 'ID', 'name' => 'Dogiyai', 'active' => 1, 'slug' => 'dogiyai'],
            ['id' => 275002, 'region_id' => 782005, 'country_code' => 'ID', 'name' => 'Intan Jaya', 'active' => 1, 'slug' => 'intan-jaya'],
            ['id' => 275003, 'region_id' => 782005, 'country_code' => 'ID', 'name' => 'Jayawijaya', 'active' => 1, 'slug' => 'jayawijaya'],
            ['id' => 275004, 'region_id' => 782005, 'country_code' => 'ID', 'name' => 'Keerom', 'active' => 1, 'slug' => 'keerom'],
            ['id' => 275005, 'region_id' => 782005, 'country_code' => 'ID', 'name' => 'Lanny Jaya', 'active' => 1, 'slug' => 'lanny-jaya'],
            ['id' => 275006, 'region_id' => 782005, 'country_code' => 'ID', 'name' => 'Mamberamo Jaya', 'active' => 1, 'slug' => 'mamberamo-jaya'],
            ['id' => 275007, 'region_id' => 782005, 'country_code' => 'ID', 'name' => 'Mappi', 'active' => 1, 'slug' => 'mappi'],
            ['id' => 275008, 'region_id' => 782005, 'country_code' => 'ID', 'name' => 'Merauke', 'active' => 1, 'slug' => 'merauke'],
            ['id' => 275009, 'region_id' => 782005, 'country_code' => 'ID', 'name' => 'Mimika', 'active' => 1, 'slug' => 'mimika'],
            ['id' => 275010, 'region_id' => 782005, 'country_code' => 'ID', 'name' => 'Nabire', 'active' => 1, 'slug' => 'nabire'],
            ['id' => 275011, 'region_id' => 782005, 'country_code' => 'ID', 'name' => 'Nduga', 'active' => 1, 'slug' => 'nduga'],
            ['id' => 275012, 'region_id' => 782005, 'country_code' => 'ID', 'name' => 'Paniai', 'active' => 1, 'slug' => 'paniai'],
            ['id' => 275013, 'region_id' => 782005, 'country_code' => 'ID', 'name' => 'Bintang Mountains', 'active' => 1, 'slug' => 'bintang-mountains'],
            ['id' => 275014, 'region_id' => 782005, 'country_code' => 'ID', 'name' => 'Puncak', 'active' => 1, 'slug' => 'puncak'],
            ['id' => 275015, 'region_id' => 782005, 'country_code' => 'ID', 'name' => 'Puncak Jaya', 'active' => 1, 'slug' => 'puncak-jaya'],
            ['id' => 275016, 'region_id' => 782005, 'country_code' => 'ID', 'name' => 'Sarmi', 'active' => 1, 'slug' => 'sarmi'],
            ['id' => 275017, 'region_id' => 782005, 'country_code' => 'ID', 'name' => 'Supiori', 'active' => 1, 'slug' => 'supiori'],
            ['id' => 275018, 'region_id' => 782005, 'country_code' => 'ID', 'name' => 'Tolikara', 'active' => 1, 'slug' => 'tolikara'],
            ['id' => 275019, 'region_id' => 782005, 'country_code' => 'ID', 'name' => 'Waropen', 'active' => 1, 'slug' => 'waropen'],
            ['id' => 275020, 'region_id' => 782005, 'country_code' => 'ID', 'name' => 'Yahukimo', 'active' => 1, 'slug' => 'yahukimo'],
            ['id' => 275021, 'region_id' => 782005, 'country_code' => 'ID', 'name' => 'Yalimo', 'active' => 1, 'slug' => 'yalimo'],
            ['id' => 275022, 'region_id' => 782005, 'country_code' => 'ID', 'name' => 'Yapen Islands', 'active' => 1, 'slug' => 'yapen-islands'],
            ['id' => 275023, 'region_id' => 782005, 'country_code' => 'ID', 'name' => 'Jayapura', 'active' => 1, 'slug' => 'jayapura'],
            ['id' => 275024, 'region_id' => 782006, 'country_code' => 'ID', 'name' => 'Bengkalis Regency', 'active' => 1, 'slug' => 'bengkalis-regency'],
            ['id' => 275025, 'region_id' => 782006, 'country_code' => 'ID', 'name' => 'Indragiri Hilir', 'active' => 1, 'slug' => 'indragiri-hilir'],
            ['id' => 275026, 'region_id' => 782006, 'country_code' => 'ID', 'name' => 'Indragiri Hulu Regency', 'active' => 1, 'slug' => 'indragiri-hulu-regency'],
            ['id' => 275027, 'region_id' => 782006, 'country_code' => 'ID', 'name' => 'Kampar Regency', 'active' => 1, 'slug' => 'kampar-regency'],
            ['id' => 275028, 'region_id' => 782006, 'country_code' => 'ID', 'name' => 'Kuantan Singingi', 'active' => 1, 'slug' => 'kuantan-singingi'],
            ['id' => 275029, 'region_id' => 782006, 'country_code' => 'ID', 'name' => 'Meranti Islands', 'active' => 1, 'slug' => 'meranti-islands'],
            ['id' => 275030, 'region_id' => 782006, 'country_code' => 'ID', 'name' => 'Pelalawan', 'active' => 1, 'slug' => 'pelalawan'],
            ['id' => 275031, 'region_id' => 782006, 'country_code' => 'ID', 'name' => 'Rokan Hulu', 'active' => 1, 'slug' => 'rokan-hulu'],
            ['id' => 275032, 'region_id' => 782006, 'country_code' => 'ID', 'name' => 'Rokan Hilir', 'active' => 1, 'slug' => 'rokan-hilir'],
            ['id' => 275033, 'region_id' => 782006, 'country_code' => 'ID', 'name' => 'Siak Regency', 'active' => 1, 'slug' => 'siak-regency'],
            ['id' => 275034, 'region_id' => 782006, 'country_code' => 'ID', 'name' => 'Dumai', 'active' => 1, 'slug' => 'dumai'],
            ['id' => 275035, 'region_id' => 782006, 'country_code' => 'ID', 'name' => 'Pekanbaru', 'active' => 1, 'slug' => 'pekanbaru'],
            ['id' => 275036, 'region_id' => 782007, 'country_code' => 'ID', 'name' => 'Anambas Islands', 'active' => 1, 'slug' => 'anambas-islands'],
            ['id' => 275037, 'region_id' => 782007, 'country_code' => 'ID', 'name' => 'Bintan', 'active' => 1, 'slug' => 'bintan'],
            ['id' => 275038, 'region_id' => 782007, 'country_code' => 'ID', 'name' => 'Karimun', 'active' => 1, 'slug' => 'karimun'],
            ['id' => 275039, 'region_id' => 782007, 'country_code' => 'ID', 'name' => 'Lingga', 'active' => 1, 'slug' => 'lingga'],
            ['id' => 275040, 'region_id' => 782007, 'country_code' => 'ID', 'name' => 'Natuna', 'active' => 1, 'slug' => 'natuna'],
            ['id' => 275041, 'region_id' => 782007, 'country_code' => 'ID', 'name' => 'Batam', 'active' => 1, 'slug' => 'batam'],
            ['id' => 275042, 'region_id' => 782007, 'country_code' => 'ID', 'name' => 'Tanjung Pinang', 'active' => 1, 'slug' => 'tanjung-pinang'],
            ['id' => 275043, 'region_id' => 782008, 'country_code' => 'ID', 'name' => 'Bombana', 'active' => 1, 'slug' => 'bombana'],
            ['id' => 275044, 'region_id' => 782008, 'country_code' => 'ID', 'name' => 'Buton', 'active' => 1, 'slug' => 'buton'],
            ['id' => 275045, 'region_id' => 782008, 'country_code' => 'ID', 'name' => 'Kolaka', 'active' => 1, 'slug' => 'kolaka'],
            ['id' => 275046, 'region_id' => 782008, 'country_code' => 'ID', 'name' => 'Konawe', 'active' => 1, 'slug' => 'konawe'],
            ['id' => 275047, 'region_id' => 782008, 'country_code' => 'ID', 'name' => 'Muna', 'active' => 1, 'slug' => 'muna'],
            ['id' => 275048, 'region_id' => 782008, 'country_code' => 'ID', 'name' => 'North Buton', 'active' => 1, 'slug' => 'north-buton'],
            ['id' => 275049, 'region_id' => 782008, 'country_code' => 'ID', 'name' => 'North Kolaka', 'active' => 1, 'slug' => 'north-kolaka'],
            ['id' => 275050, 'region_id' => 782008, 'country_code' => 'ID', 'name' => 'North Konawe', 'active' => 1, 'slug' => 'north-konawe'],
            ['id' => 275051, 'region_id' => 782008, 'country_code' => 'ID', 'name' => 'South Konawe', 'active' => 1, 'slug' => 'south-konawe'],
            ['id' => 275052, 'region_id' => 782008, 'country_code' => 'ID', 'name' => 'Wakatobi', 'active' => 1, 'slug' => 'wakatobi'],
            ['id' => 275053, 'region_id' => 782008, 'country_code' => 'ID', 'name' => 'Bau-Bau', 'active' => 1, 'slug' => 'bau-bau'],
            ['id' => 275054, 'region_id' => 782008, 'country_code' => 'ID', 'name' => 'Kendari', 'active' => 1, 'slug' => 'kendari'],
            ['id' => 275055, 'region_id' => 782009, 'country_code' => 'ID', 'name' => 'Balangan', 'active' => 1, 'slug' => 'balangan'],
            ['id' => 275056, 'region_id' => 782009, 'country_code' => 'ID', 'name' => 'Banjar', 'active' => 1, 'slug' => 'banjar'],
            ['id' => 275057, 'region_id' => 782009, 'country_code' => 'ID', 'name' => 'Barito Kuala', 'active' => 1, 'slug' => 'barito-kuala'],
            ['id' => 275058, 'region_id' => 782009, 'country_code' => 'ID', 'name' => 'Central Hulu Sungai', 'active' => 1, 'slug' => 'central-hulu-sungai'],
            ['id' => 275059, 'region_id' => 782009, 'country_code' => 'ID', 'name' => 'Kotabaru', 'active' => 1, 'slug' => 'kotabaru'],
            ['id' => 275060, 'region_id' => 782009, 'country_code' => 'ID', 'name' => 'North Hulu Sungai', 'active' => 1, 'slug' => 'north-hulu-sungai'],
            ['id' => 275061, 'region_id' => 782009, 'country_code' => 'ID', 'name' => 'South Hulu Sungai', 'active' => 1, 'slug' => 'south-hulu-sungai'],
            ['id' => 275062, 'region_id' => 782009, 'country_code' => 'ID', 'name' => 'Tabalong', 'active' => 1, 'slug' => 'tabalong'],
            ['id' => 275063, 'region_id' => 782009, 'country_code' => 'ID', 'name' => 'Tanah Laut', 'active' => 1, 'slug' => 'tanah-laut'],
            ['id' => 275064, 'region_id' => 782009, 'country_code' => 'ID', 'name' => 'Tanah Bumbu', 'active' => 1, 'slug' => 'tanah-bumbu'],
            ['id' => 275065, 'region_id' => 782009, 'country_code' => 'ID', 'name' => 'Tapin', 'active' => 1, 'slug' => 'tapin'],
            ['id' => 275066, 'region_id' => 782009, 'country_code' => 'ID', 'name' => 'Banjarbaru', 'active' => 1, 'slug' => 'banjarbaru'],
            ['id' => 275067, 'region_id' => 782009, 'country_code' => 'ID', 'name' => 'Banjarmasin', 'active' => 1, 'slug' => 'banjarmasin'],
            ['id' => 275068, 'region_id' => 782010, 'country_code' => 'ID', 'name' => 'Bantaeng', 'active' => 1, 'slug' => 'bantaeng'],
            ['id' => 275069, 'region_id' => 782010, 'country_code' => 'ID', 'name' => 'Barru', 'active' => 1, 'slug' => 'barru'],
            ['id' => 275070, 'region_id' => 782010, 'country_code' => 'ID', 'name' => 'Bone', 'active' => 1, 'slug' => 'bone'],
            ['id' => 275071, 'region_id' => 782010, 'country_code' => 'ID', 'name' => 'Bulukumba', 'active' => 1, 'slug' => 'bulukumba'],
            ['id' => 275072, 'region_id' => 782010, 'country_code' => 'ID', 'name' => 'East Luwu', 'active' => 1, 'slug' => 'east-luwu'],
            ['id' => 275073, 'region_id' => 782010, 'country_code' => 'ID', 'name' => 'Enrekang', 'active' => 1, 'slug' => 'enrekang'],
            ['id' => 275074, 'region_id' => 782010, 'country_code' => 'ID', 'name' => 'Gowa', 'active' => 1, 'slug' => 'gowa'],
            ['id' => 275075, 'region_id' => 782010, 'country_code' => 'ID', 'name' => 'Jeneponto', 'active' => 1, 'slug' => 'jeneponto'],
            ['id' => 275076, 'region_id' => 782010, 'country_code' => 'ID', 'name' => 'Luwu', 'active' => 1, 'slug' => 'luwu'],
            ['id' => 275077, 'region_id' => 782010, 'country_code' => 'ID', 'name' => 'North Luwu', 'active' => 1, 'slug' => 'north-luwu'],
            ['id' => 275078, 'region_id' => 782010, 'country_code' => 'ID', 'name' => 'Maros', 'active' => 1, 'slug' => 'maros'],
            ['id' => 275079, 'region_id' => 782010, 'country_code' => 'ID', 'name' => 'Pangkajene Islands', 'active' => 1, 'slug' => 'pangkajene-islands'],
            ['id' => 275080, 'region_id' => 782010, 'country_code' => 'ID', 'name' => 'Pinrang', 'active' => 1, 'slug' => 'pinrang'],
            ['id' => 275081, 'region_id' => 782010, 'country_code' => 'ID', 'name' => 'Selayar Islands', 'active' => 1, 'slug' => 'selayar-islands'],
            ['id' => 275082, 'region_id' => 782010, 'country_code' => 'ID', 'name' => 'Sidenreng Rappang', 'active' => 1, 'slug' => 'sidenreng-rappang'],
            ['id' => 275083, 'region_id' => 782010, 'country_code' => 'ID', 'name' => 'Soppeng', 'active' => 1, 'slug' => 'soppeng'],
            ['id' => 275084, 'region_id' => 782010, 'country_code' => 'ID', 'name' => 'Takalar', 'active' => 1, 'slug' => 'takalar'],
            ['id' => 275085, 'region_id' => 782010, 'country_code' => 'ID', 'name' => 'Tana Toraja', 'active' => 1, 'slug' => 'tana-toraja'],
            ['id' => 275086, 'region_id' => 782010, 'country_code' => 'ID', 'name' => 'Wajo', 'active' => 1, 'slug' => 'wajo'],
            ['id' => 275087, 'region_id' => 782010, 'country_code' => 'ID', 'name' => 'Palopo', 'active' => 1, 'slug' => 'palopo'],
            ['id' => 275088, 'region_id' => 782010, 'country_code' => 'ID', 'name' => 'Pare-Pare', 'active' => 1, 'slug' => 'pare-pare'],
            ['id' => 275089, 'region_id' => 782010, 'country_code' => 'ID', 'name' => 'Sinjai', 'active' => 1, 'slug' => 'sinjai'],
            ['id' => 275090, 'region_id' => 782010, 'country_code' => 'ID', 'name' => 'Makassar', 'active' => 1, 'slug' => 'makassar'],
            ['id' => 275091, 'region_id' => 782011, 'country_code' => 'ID', 'name' => 'Banyuasin', 'active' => 1, 'slug' => 'banyuasin'],
            ['id' => 275092, 'region_id' => 782011, 'country_code' => 'ID', 'name' => 'East Ogan Komering Ulu', 'active' => 1, 'slug' => 'east-ogan-komering-ulu'],
            ['id' => 275093, 'region_id' => 782011, 'country_code' => 'ID', 'name' => 'Empat Lawang', 'active' => 1, 'slug' => 'empat-lawang'],
            ['id' => 275094, 'region_id' => 782011, 'country_code' => 'ID', 'name' => 'Muarama Enim', 'active' => 1, 'slug' => 'muarama-enim'],
            ['id' => 275095, 'region_id' => 782011, 'country_code' => 'ID', 'name' => 'Musi Banyuasin', 'active' => 1, 'slug' => 'musi-banyuasin'],
            ['id' => 275096, 'region_id' => 782011, 'country_code' => 'ID', 'name' => 'Musi Rawas', 'active' => 1, 'slug' => 'musi-rawas'],
            ['id' => 275097, 'region_id' => 782011, 'country_code' => 'ID', 'name' => 'Ogan Ilir', 'active' => 1, 'slug' => 'ogan-ilir'],
            ['id' => 275098, 'region_id' => 782011, 'country_code' => 'ID', 'name' => 'Ogan Komering Ilir', 'active' => 1, 'slug' => 'ogan-komering-ilir'],
            ['id' => 275099, 'region_id' => 782011, 'country_code' => 'ID', 'name' => 'Ogan Komering Ulu', 'active' => 1, 'slug' => 'ogan-komering-ulu'],
            ['id' => 275100, 'region_id' => 782011, 'country_code' => 'ID', 'name' => 'South Ogan Komering Ulu', 'active' => 1, 'slug' => 'south-ogan-komering-ulu'],
            ['id' => 275101, 'region_id' => 782011, 'country_code' => 'ID', 'name' => 'Pagar Alam', 'active' => 1, 'slug' => 'pagar-alam'],
            ['id' => 275102, 'region_id' => 782011, 'country_code' => 'ID', 'name' => 'Palembang', 'active' => 1, 'slug' => 'palembang'],
            ['id' => 275103, 'region_id' => 782011, 'country_code' => 'ID', 'name' => 'Lahat', 'active' => 1, 'slug' => 'lahat'],
            ['id' => 275104, 'region_id' => 782011, 'country_code' => 'ID', 'name' => 'Prabumulih', 'active' => 1, 'slug' => 'prabumulih'],
            ['id' => 275105, 'region_id' => 782011, 'country_code' => 'ID', 'name' => 'Lubuklinggau', 'active' => 1, 'slug' => 'lubuklinggau'],
            ['id' => 275106, 'region_id' => 782012, 'country_code' => 'ID', 'name' => 'Bandung', 'active' => 1, 'slug' => 'bandung'],
            ['id' => 275107, 'region_id' => 782012, 'country_code' => 'ID', 'name' => 'Bekasi', 'active' => 1, 'slug' => 'bekasi'],
            ['id' => 275108, 'region_id' => 782012, 'country_code' => 'ID', 'name' => 'Bogor', 'active' => 1, 'slug' => 'bogor'],
            ['id' => 275109, 'region_id' => 782012, 'country_code' => 'ID', 'name' => 'Ciamis', 'active' => 1, 'slug' => 'ciamis'],
            ['id' => 275110, 'region_id' => 782012, 'country_code' => 'ID', 'name' => 'Cianjur', 'active' => 1, 'slug' => 'cianjur'],
            ['id' => 275111, 'region_id' => 782012, 'country_code' => 'ID', 'name' => 'Cirebon', 'active' => 1, 'slug' => 'cirebon'],
            ['id' => 275112, 'region_id' => 782012, 'country_code' => 'ID', 'name' => 'Garut', 'active' => 1, 'slug' => 'garut'],
            ['id' => 275113, 'region_id' => 782012, 'country_code' => 'ID', 'name' => 'Karawang', 'active' => 1, 'slug' => 'karawang'],
            ['id' => 275114, 'region_id' => 782012, 'country_code' => 'ID', 'name' => 'Kuningan', 'active' => 1, 'slug' => 'kuningan'],
            ['id' => 275115, 'region_id' => 782012, 'country_code' => 'ID', 'name' => 'Subang', 'active' => 1, 'slug' => 'subang'],
            ['id' => 275116, 'region_id' => 782012, 'country_code' => 'ID', 'name' => 'Sukabumi', 'active' => 1, 'slug' => 'sukabumi'],
            ['id' => 275117, 'region_id' => 782012, 'country_code' => 'ID', 'name' => 'Sumedang', 'active' => 1, 'slug' => 'sumedang'],
            ['id' => 275118, 'region_id' => 782012, 'country_code' => 'ID', 'name' => 'West Bandung', 'active' => 1, 'slug' => 'west-bandung'],
            ['id' => 275119, 'region_id' => 782012, 'country_code' => 'ID', 'name' => 'Banjar', 'active' => 1, 'slug' => 'banjar'],
            ['id' => 275120, 'region_id' => 782012, 'country_code' => 'ID', 'name' => 'Cimahi', 'active' => 1, 'slug' => 'cimahi'],
            ['id' => 275121, 'region_id' => 782012, 'country_code' => 'ID', 'name' => 'Depok', 'active' => 1, 'slug' => 'depok'],
            ['id' => 275122, 'region_id' => 782012, 'country_code' => 'ID', 'name' => 'Majalengka', 'active' => 1, 'slug' => 'majalengka'],
            ['id' => 275123, 'region_id' => 782012, 'country_code' => 'ID', 'name' => 'Indramayu', 'active' => 1, 'slug' => 'indramayu'],
            ['id' => 275124, 'region_id' => 782012, 'country_code' => 'ID', 'name' => 'Purwakarta', 'active' => 1, 'slug' => 'purwakarta'],
            ['id' => 275125, 'region_id' => 782012, 'country_code' => 'ID', 'name' => 'Tasikmalaya', 'active' => 1, 'slug' => 'tasikmalaya'],
            ['id' => 275126, 'region_id' => 782013, 'country_code' => 'ID', 'name' => 'Bengkayang Regency', 'active' => 1, 'slug' => 'bengkayang-regency'],
            ['id' => 275127, 'region_id' => 782013, 'country_code' => 'ID', 'name' => 'Kapuas Hulu Regency', 'active' => 1, 'slug' => 'kapuas-hulu-regency'],
            ['id' => 275128, 'region_id' => 782013, 'country_code' => 'ID', 'name' => 'North Kayong Regency', 'active' => 1, 'slug' => 'north-kayong-regency'],
            ['id' => 275129, 'region_id' => 782013, 'country_code' => 'ID', 'name' => 'Ketapang Regency', 'active' => 1, 'slug' => 'ketapang-regency'],
            ['id' => 275130, 'region_id' => 782013, 'country_code' => 'ID', 'name' => 'Kubu Raya Regency', 'active' => 1, 'slug' => 'kubu-raya-regency'],
            ['id' => 275131, 'region_id' => 782013, 'country_code' => 'ID', 'name' => 'Landak Regency', 'active' => 1, 'slug' => 'landak-regency'],
            ['id' => 275132, 'region_id' => 782013, 'country_code' => 'ID', 'name' => 'Melawi Regency', 'active' => 1, 'slug' => 'melawi-regency'],
            ['id' => 275133, 'region_id' => 782013, 'country_code' => 'ID', 'name' => 'Sambas Regency', 'active' => 1, 'slug' => 'sambas-regency'],
            ['id' => 275134, 'region_id' => 782013, 'country_code' => 'ID', 'name' => 'Sanggau Regency', 'active' => 1, 'slug' => 'sanggau-regency'],
            ['id' => 275135, 'region_id' => 782013, 'country_code' => 'ID', 'name' => 'Sekadau Regency', 'active' => 1, 'slug' => 'sekadau-regency'],
            ['id' => 275136, 'region_id' => 782013, 'country_code' => 'ID', 'name' => 'Sintang Regency', 'active' => 1, 'slug' => 'sintang-regency'],
            ['id' => 275137, 'region_id' => 782013, 'country_code' => 'ID', 'name' => 'Singkawang', 'active' => 1, 'slug' => 'singkawang'],
            ['id' => 275138, 'region_id' => 782013, 'country_code' => 'ID', 'name' => 'Pontianak', 'active' => 1, 'slug' => 'pontianak'],
            ['id' => 275139, 'region_id' => 782014, 'country_code' => 'ID', 'name' => 'Bima', 'active' => 1, 'slug' => 'bima'],
            ['id' => 275140, 'region_id' => 782014, 'country_code' => 'ID', 'name' => 'Central Lombok', 'active' => 1, 'slug' => 'central-lombok'],
            ['id' => 275141, 'region_id' => 782014, 'country_code' => 'ID', 'name' => 'Dompu', 'active' => 1, 'slug' => 'dompu'],
            ['id' => 275142, 'region_id' => 782014, 'country_code' => 'ID', 'name' => 'East Lombok', 'active' => 1, 'slug' => 'east-lombok'],
            ['id' => 275143, 'region_id' => 782014, 'country_code' => 'ID', 'name' => 'North Lombok', 'active' => 1, 'slug' => 'north-lombok'],
            ['id' => 275144, 'region_id' => 782014, 'country_code' => 'ID', 'name' => 'Sumbawa', 'active' => 1, 'slug' => 'sumbawa'],
            ['id' => 275145, 'region_id' => 782014, 'country_code' => 'ID', 'name' => 'West Lombok', 'active' => 1, 'slug' => 'west-lombok'],
            ['id' => 275146, 'region_id' => 782014, 'country_code' => 'ID', 'name' => 'West Sumbawa', 'active' => 1, 'slug' => 'west-sumbawa'],
            ['id' => 275147, 'region_id' => 782014, 'country_code' => 'ID', 'name' => 'Mataram', 'active' => 1, 'slug' => 'mataram'],
            ['id' => 275148, 'region_id' => 782015, 'country_code' => 'ID', 'name' => 'Fak-Fak', 'active' => 1, 'slug' => 'fak-fak'],
            ['id' => 275149, 'region_id' => 782015, 'country_code' => 'ID', 'name' => 'Kaimana', 'active' => 1, 'slug' => 'kaimana'],
            ['id' => 275150, 'region_id' => 782015, 'country_code' => 'ID', 'name' => 'Maybrat', 'active' => 1, 'slug' => 'maybrat'],
            ['id' => 275151, 'region_id' => 782015, 'country_code' => 'ID', 'name' => 'Raja Ampat', 'active' => 1, 'slug' => 'raja-ampat'],
            ['id' => 275152, 'region_id' => 782015, 'country_code' => 'ID', 'name' => 'Sorong', 'active' => 1, 'slug' => 'sorong'],
            ['id' => 275153, 'region_id' => 782015, 'country_code' => 'ID', 'name' => 'South Sorong', 'active' => 1, 'slug' => 'south-sorong'],
            ['id' => 275154, 'region_id' => 782015, 'country_code' => 'ID', 'name' => 'Tambrauw', 'active' => 1, 'slug' => 'tambrauw'],
            ['id' => 275155, 'region_id' => 782015, 'country_code' => 'ID', 'name' => 'Teluk Bintuni', 'active' => 1, 'slug' => 'teluk-bintuni'],
            ['id' => 275156, 'region_id' => 782015, 'country_code' => 'ID', 'name' => 'Teluk Wondama', 'active' => 1, 'slug' => 'teluk-wondama'],
            ['id' => 275157, 'region_id' => 782015, 'country_code' => 'ID', 'name' => 'Manokwari', 'active' => 1, 'slug' => 'manokwari'],
            ['id' => 275158, 'region_id' => 782016, 'country_code' => 'ID', 'name' => 'Majene', 'active' => 1, 'slug' => 'majene'],
            ['id' => 275159, 'region_id' => 782016, 'country_code' => 'ID', 'name' => 'Mamasa', 'active' => 1, 'slug' => 'mamasa'],
            ['id' => 275160, 'region_id' => 782016, 'country_code' => 'ID', 'name' => 'Mamuju', 'active' => 1, 'slug' => 'mamuju'],
            ['id' => 275161, 'region_id' => 782016, 'country_code' => 'ID', 'name' => 'North Mamuju', 'active' => 1, 'slug' => 'north-mamuju'],
            ['id' => 275162, 'region_id' => 782016, 'country_code' => 'ID', 'name' => 'Polewali Mandar', 'active' => 1, 'slug' => 'polewali-mandar'],
            ['id' => 275163, 'region_id' => 782017, 'country_code' => 'ID', 'name' => 'Agam', 'active' => 1, 'slug' => 'agam'],
            ['id' => 275164, 'region_id' => 782017, 'country_code' => 'ID', 'name' => 'Dharmasraya', 'active' => 1, 'slug' => 'dharmasraya'],
            ['id' => 275165, 'region_id' => 782017, 'country_code' => 'ID', 'name' => 'Lima Puluh Kota', 'active' => 1, 'slug' => 'lima-puluh-kota'],
            ['id' => 275166, 'region_id' => 782017, 'country_code' => 'ID', 'name' => 'Mentawai Islands', 'active' => 1, 'slug' => 'mentawai-islands'],
            ['id' => 275167, 'region_id' => 782017, 'country_code' => 'ID', 'name' => 'Padang Pariaman', 'active' => 1, 'slug' => 'padang-pariaman'],
            ['id' => 275168, 'region_id' => 782017, 'country_code' => 'ID', 'name' => 'Pasaman', 'active' => 1, 'slug' => 'pasaman'],
            ['id' => 275169, 'region_id' => 782017, 'country_code' => 'ID', 'name' => 'Sawahlunto Sijunjung', 'active' => 1, 'slug' => 'sawahlunto-sijunjung'],
            ['id' => 275170, 'region_id' => 782017, 'country_code' => 'ID', 'name' => 'Solok', 'active' => 1, 'slug' => 'solok'],
            ['id' => 275171, 'region_id' => 782017, 'country_code' => 'ID', 'name' => 'South Pesisir', 'active' => 1, 'slug' => 'south-pesisir'],
            ['id' => 275172, 'region_id' => 782017, 'country_code' => 'ID', 'name' => 'South Solok', 'active' => 1, 'slug' => 'south-solok'],
            ['id' => 275173, 'region_id' => 782017, 'country_code' => 'ID', 'name' => 'Tanah Datar', 'active' => 1, 'slug' => 'tanah-datar'],
            ['id' => 275174, 'region_id' => 782017, 'country_code' => 'ID', 'name' => 'West Pasaman', 'active' => 1, 'slug' => 'west-pasaman'],
            ['id' => 275175, 'region_id' => 782017, 'country_code' => 'ID', 'name' => 'Bukittinggi', 'active' => 1, 'slug' => 'bukittinggi'],
            ['id' => 275176, 'region_id' => 782017, 'country_code' => 'ID', 'name' => 'Padang', 'active' => 1, 'slug' => 'padang'],
            ['id' => 275177, 'region_id' => 782017, 'country_code' => 'ID', 'name' => 'Padang Panjang', 'active' => 1, 'slug' => 'padang-panjang'],
            ['id' => 275178, 'region_id' => 782017, 'country_code' => 'ID', 'name' => 'Pariaman', 'active' => 1, 'slug' => 'pariaman'],
            ['id' => 275179, 'region_id' => 782017, 'country_code' => 'ID', 'name' => 'Payakumbuh', 'active' => 1, 'slug' => 'payakumbuh'],
            ['id' => 275180, 'region_id' => 782017, 'country_code' => 'ID', 'name' => 'Sawahlunto', 'active' => 1, 'slug' => 'sawahlunto'],
            ['id' => 275181, 'region_id' => 782018, 'country_code' => 'ID', 'name' => 'Bantul', 'active' => 1, 'slug' => 'bantul'],
            ['id' => 275182, 'region_id' => 782018, 'country_code' => 'ID', 'name' => 'Gunung Kidul', 'active' => 1, 'slug' => 'gunung-kidul'],
            ['id' => 275183, 'region_id' => 782018, 'country_code' => 'ID', 'name' => 'Kulon Progo', 'active' => 1, 'slug' => 'kulon-progo'],
            ['id' => 275184, 'region_id' => 782018, 'country_code' => 'ID', 'name' => 'Sleman', 'active' => 1, 'slug' => 'sleman'],
            ['id' => 275185, 'region_id' => 782018, 'country_code' => 'ID', 'name' => 'Yogyakarta', 'active' => 1, 'slug' => 'yogyakarta']
    	];
    }
}
