<?php

namespace Gerardojbaez\GeoData\Seeders;

use Illuminate\Database\Seeder;
use Gerardojbaez\GeoData\Models\Country;
use Gerardojbaez\GeoData\Models\Region;
use Gerardojbaez\GeoData\Models\City;

class LatviaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Country::create($this->country());
        Region::insert($this->regions());

        if ($this->cities() > 4000)
        {
            foreach (array_chunk($this->cities(), 3500) as $chunk)
                City::insert($chunk);
        }
        else
        {
            City::insert($this->cities());
        }
    }

        /**
     * Get country.
     *
     * @return array
     */
    public function country()
    {
    	return ['code' => 'LV', 'name' => 'Latvia', 'slug' => 'latvia'];
    }

    /**
     * Get country regions.
     *
     * @return array
     */
    public function regions()
    {
    	return [
            ['id' => 782750, 'country_code' => 'LV', 'name' => 'Rīga', 'active' => 1, 'slug' => 'riga'],
            ['id' => 782751, 'country_code' => 'LV', 'name' => 'Daugavpils', 'active' => 1, 'slug' => 'daugavpils'],
            ['id' => 782752, 'country_code' => 'LV', 'name' => 'Jelgava', 'active' => 1, 'slug' => 'jelgava'],
            ['id' => 782753, 'country_code' => 'LV', 'name' => 'Jēkabpils', 'active' => 1, 'slug' => 'jekabpils'],
            ['id' => 782754, 'country_code' => 'LV', 'name' => 'Jūrmala', 'active' => 1, 'slug' => 'jurmala'],
            ['id' => 782755, 'country_code' => 'LV', 'name' => 'Liepāja', 'active' => 1, 'slug' => 'liepaja'],
            ['id' => 782756, 'country_code' => 'LV', 'name' => 'Rēzekne', 'active' => 1, 'slug' => 'rezekne'],
            ['id' => 782757, 'country_code' => 'LV', 'name' => 'Valmiera', 'active' => 1, 'slug' => 'valmiera'],
            ['id' => 782758, 'country_code' => 'LV', 'name' => 'Ventspils', 'active' => 1, 'slug' => 'ventspils'],
            ['id' => 782759, 'country_code' => 'LV', 'name' => 'Aizkraukles novads', 'active' => 1, 'slug' => 'aizkraukles-novads'],
            ['id' => 782760, 'country_code' => 'LV', 'name' => 'Jaunjelgavas novads', 'active' => 1, 'slug' => 'jaunjelgavas-novads'],
            ['id' => 782761, 'country_code' => 'LV', 'name' => 'Pļaviņu novads', 'active' => 1, 'slug' => 'plavinu-novads'],
            ['id' => 782762, 'country_code' => 'LV', 'name' => 'Kokneses novads', 'active' => 1, 'slug' => 'kokneses-novads'],
            ['id' => 782763, 'country_code' => 'LV', 'name' => 'Neretas novads', 'active' => 1, 'slug' => 'neretas-novads'],
            ['id' => 782764, 'country_code' => 'LV', 'name' => 'Skrīveru novads', 'active' => 1, 'slug' => 'skriveru-novads'],
            ['id' => 782765, 'country_code' => 'LV', 'name' => 'Alūksnes novads', 'active' => 1, 'slug' => 'aluksnes-novads'],
            ['id' => 782766, 'country_code' => 'LV', 'name' => 'Apes novads', 'active' => 1, 'slug' => 'apes-novads'],
            ['id' => 782767, 'country_code' => 'LV', 'name' => 'Balvu novads', 'active' => 1, 'slug' => 'balvu-novads'],
            ['id' => 782768, 'country_code' => 'LV', 'name' => 'Viļakas novads', 'active' => 1, 'slug' => 'vilakas-novads'],
            ['id' => 782769, 'country_code' => 'LV', 'name' => 'Baltinavas novads', 'active' => 1, 'slug' => 'baltinavas-novads'],
            ['id' => 782770, 'country_code' => 'LV', 'name' => 'Rugāju novads', 'active' => 1, 'slug' => 'rugaju-novads'],
            ['id' => 782771, 'country_code' => 'LV', 'name' => 'Bauskas novads', 'active' => 1, 'slug' => 'bauskas-novads'],
            ['id' => 782772, 'country_code' => 'LV', 'name' => 'Iecavas novads', 'active' => 1, 'slug' => 'iecavas-novads'],
            ['id' => 782773, 'country_code' => 'LV', 'name' => 'Rundāles novads', 'active' => 1, 'slug' => 'rundales-novads'],
            ['id' => 782774, 'country_code' => 'LV', 'name' => 'Vecumnieku novads', 'active' => 1, 'slug' => 'vecumnieku-novads'],
            ['id' => 782775, 'country_code' => 'LV', 'name' => 'Cēsu novads', 'active' => 1, 'slug' => 'cesu-novads'],
            ['id' => 782776, 'country_code' => 'LV', 'name' => 'Līgatnes novads', 'active' => 1, 'slug' => 'ligatnes-novads'],
            ['id' => 782777, 'country_code' => 'LV', 'name' => 'Amatas novads', 'active' => 1, 'slug' => 'amatas-novads'],
            ['id' => 782778, 'country_code' => 'LV', 'name' => 'Jaunpiebalgas novads', 'active' => 1, 'slug' => 'jaunpiebalgas-novads'],
            ['id' => 782779, 'country_code' => 'LV', 'name' => 'Priekuļu novads', 'active' => 1, 'slug' => 'priekulu-novads'],
            ['id' => 782780, 'country_code' => 'LV', 'name' => 'Pārgaujas novads', 'active' => 1, 'slug' => 'pargaujas-novads'],
            ['id' => 782781, 'country_code' => 'LV', 'name' => 'Raunas novads', 'active' => 1, 'slug' => 'raunas-novads'],
            ['id' => 782782, 'country_code' => 'LV', 'name' => 'Vecpiebalgas novads', 'active' => 1, 'slug' => 'vecpiebalgas-novads'],
            ['id' => 782783, 'country_code' => 'LV', 'name' => 'Daugavpils novads', 'active' => 1, 'slug' => 'daugavpils-novads'],
            ['id' => 782784, 'country_code' => 'LV', 'name' => 'Ilūkstes novads', 'active' => 1, 'slug' => 'ilukstes-novads'],
            ['id' => 782785, 'country_code' => 'LV', 'name' => 'Dobeles novads', 'active' => 1, 'slug' => 'dobeles-novads'],
            ['id' => 782786, 'country_code' => 'LV', 'name' => 'Auces novads', 'active' => 1, 'slug' => 'auces-novads'],
            ['id' => 782787, 'country_code' => 'LV', 'name' => 'Tērvetes novads', 'active' => 1, 'slug' => 'tervetes-novads'],
            ['id' => 782788, 'country_code' => 'LV', 'name' => 'Gulbenes novads', 'active' => 1, 'slug' => 'gulbenes-novads'],
            ['id' => 782789, 'country_code' => 'LV', 'name' => 'Jelgavas novads', 'active' => 1, 'slug' => 'jelgavas-novads'],
            ['id' => 782790, 'country_code' => 'LV', 'name' => 'Ozolnieku novads', 'active' => 1, 'slug' => 'ozolnieku-novads'],
            ['id' => 782791, 'country_code' => 'LV', 'name' => 'Jēkabpils novads', 'active' => 1, 'slug' => 'jekabpils-novads'],
            ['id' => 782792, 'country_code' => 'LV', 'name' => 'Aknīstes novads', 'active' => 1, 'slug' => 'aknistes-novads'],
            ['id' => 782793, 'country_code' => 'LV', 'name' => 'Viesītes novads', 'active' => 1, 'slug' => 'viesites-novads'],
            ['id' => 782794, 'country_code' => 'LV', 'name' => 'Krustpils novads', 'active' => 1, 'slug' => 'krustpils-novads'],
            ['id' => 782795, 'country_code' => 'LV', 'name' => 'Salas novads', 'active' => 1, 'slug' => 'salas-novads'],
            ['id' => 782796, 'country_code' => 'LV', 'name' => 'Krāslavas novads', 'active' => 1, 'slug' => 'kraslavas-novads'],
            ['id' => 782797, 'country_code' => 'LV', 'name' => 'Dagdas novads', 'active' => 1, 'slug' => 'dagdas-novads'],
            ['id' => 782798, 'country_code' => 'LV', 'name' => 'Aglonas novads', 'active' => 1, 'slug' => 'aglonas-novads'],
            ['id' => 782799, 'country_code' => 'LV', 'name' => 'Kuldīgas novads', 'active' => 1, 'slug' => 'kuldigas-novads'],
            ['id' => 782800, 'country_code' => 'LV', 'name' => 'Skrundas novads', 'active' => 1, 'slug' => 'skrundas-novads'],
            ['id' => 782801, 'country_code' => 'LV', 'name' => 'Alsungas novads', 'active' => 1, 'slug' => 'alsungas-novads'],
            ['id' => 782802, 'country_code' => 'LV', 'name' => 'Aizputes novads', 'active' => 1, 'slug' => 'aizputes-novads'],
            ['id' => 782803, 'country_code' => 'LV', 'name' => 'Durbes novads', 'active' => 1, 'slug' => 'durbes-novads'],
            ['id' => 782804, 'country_code' => 'LV', 'name' => 'Grobiņas novads', 'active' => 1, 'slug' => 'grobinas-novads'],
            ['id' => 782805, 'country_code' => 'LV', 'name' => 'Pāvilostas novads', 'active' => 1, 'slug' => 'pavilostas-novads'],
            ['id' => 782806, 'country_code' => 'LV', 'name' => 'Priekules novads', 'active' => 1, 'slug' => 'priekules-novads'],
            ['id' => 782807, 'country_code' => 'LV', 'name' => 'Nīcas novads', 'active' => 1, 'slug' => 'nicas-novads'],
            ['id' => 782808, 'country_code' => 'LV', 'name' => 'Rucavas novads', 'active' => 1, 'slug' => 'rucavas-novads'],
            ['id' => 782809, 'country_code' => 'LV', 'name' => 'Vaiņodes novads', 'active' => 1, 'slug' => 'vainodes-novads'],
            ['id' => 782810, 'country_code' => 'LV', 'name' => 'Limbažu novads', 'active' => 1, 'slug' => 'limbazu-novads'],
            ['id' => 782811, 'country_code' => 'LV', 'name' => 'Alojas novads', 'active' => 1, 'slug' => 'alojas-novads'],
            ['id' => 782812, 'country_code' => 'LV', 'name' => 'Salacgrīvas novads', 'active' => 1, 'slug' => 'salacgrivas-novads'],
            ['id' => 782813, 'country_code' => 'LV', 'name' => 'Ludzas novads', 'active' => 1, 'slug' => 'ludzas-novads'],
            ['id' => 782814, 'country_code' => 'LV', 'name' => 'Kārsavas novads', 'active' => 1, 'slug' => 'karsavas-novads'],
            ['id' => 782815, 'country_code' => 'LV', 'name' => 'Zilupes novads', 'active' => 1, 'slug' => 'zilupes-novads'],
            ['id' => 782816, 'country_code' => 'LV', 'name' => 'Ciblas novads', 'active' => 1, 'slug' => 'ciblas-novads'],
            ['id' => 782817, 'country_code' => 'LV', 'name' => 'Madonas novads', 'active' => 1, 'slug' => 'madonas-novads'],
            ['id' => 782818, 'country_code' => 'LV', 'name' => 'Cesvaines novads', 'active' => 1, 'slug' => 'cesvaines-novads'],
            ['id' => 782819, 'country_code' => 'LV', 'name' => 'Lubānas novads', 'active' => 1, 'slug' => 'lubanas-novads'],
            ['id' => 782820, 'country_code' => 'LV', 'name' => 'Varakļānu novads', 'active' => 1, 'slug' => 'varaklanu-novads'],
            ['id' => 782821, 'country_code' => 'LV', 'name' => 'Ērgļu novads', 'active' => 1, 'slug' => 'erglu-novads'],
            ['id' => 782822, 'country_code' => 'LV', 'name' => 'Ogres novads', 'active' => 1, 'slug' => 'ogres-novads'],
            ['id' => 782823, 'country_code' => 'LV', 'name' => 'Ikšķiles novads', 'active' => 1, 'slug' => 'ikskiles-novads'],
            ['id' => 782824, 'country_code' => 'LV', 'name' => 'Ķeguma novads', 'active' => 1, 'slug' => 'keguma-novads'],
            ['id' => 782825, 'country_code' => 'LV', 'name' => 'Lielvārdes novads', 'active' => 1, 'slug' => 'lielvardes-novads'],
            ['id' => 782826, 'country_code' => 'LV', 'name' => 'Preiļu novads', 'active' => 1, 'slug' => 'preilu-novads'],
            ['id' => 782827, 'country_code' => 'LV', 'name' => 'Līvānu novads', 'active' => 1, 'slug' => 'livanu-novads'],
            ['id' => 782828, 'country_code' => 'LV', 'name' => 'Riebiņu novads', 'active' => 1, 'slug' => 'riebinu-novads'],
            ['id' => 782829, 'country_code' => 'LV', 'name' => 'Vārkavas novads', 'active' => 1, 'slug' => 'varkavas-novads'],
            ['id' => 782830, 'country_code' => 'LV', 'name' => 'Rēzeknes novads', 'active' => 1, 'slug' => 'rezeknes-novads'],
            ['id' => 782831, 'country_code' => 'LV', 'name' => 'Viļānu novads', 'active' => 1, 'slug' => 'vilanu-novads'],
            ['id' => 782832, 'country_code' => 'LV', 'name' => 'Baldones novads', 'active' => 1, 'slug' => 'baldones-novads'],
            ['id' => 782833, 'country_code' => 'LV', 'name' => 'Ķekavas novads', 'active' => 1, 'slug' => 'kekavas-novads'],
            ['id' => 782834, 'country_code' => 'LV', 'name' => 'Olaines novads', 'active' => 1, 'slug' => 'olaines-novads'],
            ['id' => 782835, 'country_code' => 'LV', 'name' => 'Salaspils novads', 'active' => 1, 'slug' => 'salaspils-novads'],
            ['id' => 782836, 'country_code' => 'LV', 'name' => 'Saulkrastu novads', 'active' => 1, 'slug' => 'saulkrastu-novads'],
            ['id' => 782837, 'country_code' => 'LV', 'name' => 'Siguldas novads', 'active' => 1, 'slug' => 'siguldas-novads'],
            ['id' => 782838, 'country_code' => 'LV', 'name' => 'Inčukalna novads', 'active' => 1, 'slug' => 'incukalna-novads'],
            ['id' => 782839, 'country_code' => 'LV', 'name' => 'Ādažu novads', 'active' => 1, 'slug' => 'adazu-novads'],
            ['id' => 782840, 'country_code' => 'LV', 'name' => 'Babītes novads', 'active' => 1, 'slug' => 'babites-novads'],
            ['id' => 782841, 'country_code' => 'LV', 'name' => 'Carnikavas novads', 'active' => 1, 'slug' => 'carnikavas-novads'],
            ['id' => 782842, 'country_code' => 'LV', 'name' => 'Garkalnes novads', 'active' => 1, 'slug' => 'garkalnes-novads'],
            ['id' => 782843, 'country_code' => 'LV', 'name' => 'Krimuldas novads', 'active' => 1, 'slug' => 'krimuldas-novads'],
            ['id' => 782844, 'country_code' => 'LV', 'name' => 'Mālpils novads', 'active' => 1, 'slug' => 'malpils-novads'],
            ['id' => 782845, 'country_code' => 'LV', 'name' => 'Mārupes novads', 'active' => 1, 'slug' => 'marupes-novads'],
            ['id' => 782846, 'country_code' => 'LV', 'name' => 'Ropažu novads', 'active' => 1, 'slug' => 'ropazu-novads'],
            ['id' => 782847, 'country_code' => 'LV', 'name' => 'Sējas novads', 'active' => 1, 'slug' => 'sejas-novads'],
            ['id' => 782848, 'country_code' => 'LV', 'name' => 'Stopiņu novads', 'active' => 1, 'slug' => 'stopinu-novads'],
            ['id' => 782849, 'country_code' => 'LV', 'name' => 'Saldus novads', 'active' => 1, 'slug' => 'saldus-novads'],
            ['id' => 782850, 'country_code' => 'LV', 'name' => 'Brocēnu novads', 'active' => 1, 'slug' => 'brocenu-novads'],
            ['id' => 782851, 'country_code' => 'LV', 'name' => 'Talsu novads', 'active' => 1, 'slug' => 'talsu-novads'],
            ['id' => 782852, 'country_code' => 'LV', 'name' => 'Dundagas novads', 'active' => 1, 'slug' => 'dundagas-novads'],
            ['id' => 782853, 'country_code' => 'LV', 'name' => 'Mērsraga novads', 'active' => 1, 'slug' => 'mersraga-novads'],
            ['id' => 782854, 'country_code' => 'LV', 'name' => 'Rojas novads', 'active' => 1, 'slug' => 'rojas-novads'],
            ['id' => 782855, 'country_code' => 'LV', 'name' => 'Tukuma novads', 'active' => 1, 'slug' => 'tukuma-novads'],
            ['id' => 782856, 'country_code' => 'LV', 'name' => 'Kandavas novads', 'active' => 1, 'slug' => 'kandavas-novads'],
            ['id' => 782857, 'country_code' => 'LV', 'name' => 'Engures novads', 'active' => 1, 'slug' => 'engures-novads'],
            ['id' => 782858, 'country_code' => 'LV', 'name' => 'Jaunpils novads', 'active' => 1, 'slug' => 'jaunpils-novads'],
            ['id' => 782859, 'country_code' => 'LV', 'name' => 'Valkas novads', 'active' => 1, 'slug' => 'valkas-novads'],
            ['id' => 782860, 'country_code' => 'LV', 'name' => 'Smiltenes novads', 'active' => 1, 'slug' => 'smiltenes-novads'],
            ['id' => 782861, 'country_code' => 'LV', 'name' => 'Strenču novads', 'active' => 1, 'slug' => 'strencu-novads'],
            ['id' => 782862, 'country_code' => 'LV', 'name' => 'Kocēnu novads', 'active' => 1, 'slug' => 'kocenu-novads'],
            ['id' => 782863, 'country_code' => 'LV', 'name' => 'Mazsalacas novads', 'active' => 1, 'slug' => 'mazsalacas-novads'],
            ['id' => 782864, 'country_code' => 'LV', 'name' => 'Rūjienas novads', 'active' => 1, 'slug' => 'rujienas-novads'],
            ['id' => 782865, 'country_code' => 'LV', 'name' => 'Beverīnas novads', 'active' => 1, 'slug' => 'beverinas-novads'],
            ['id' => 782866, 'country_code' => 'LV', 'name' => 'Burtnieku novads', 'active' => 1, 'slug' => 'burtnieku-novads'],
            ['id' => 782867, 'country_code' => 'LV', 'name' => 'Naukšēnu novads', 'active' => 1, 'slug' => 'nauksenu-novads'],
            ['id' => 782868, 'country_code' => 'LV', 'name' => 'Ventspils novads', 'active' => 1, 'slug' => 'ventspils-novads']
    	];
    }

    /**
     * Get region cities.
     *
     * @return array
     */
    public function cities()
    {
    	return [
            ['id' => 466357, 'region_id' => 782759, 'country_code' => 'LV', 'name' => 'Aizkraukles pagasts', 'active' => 1, 'slug' => 'aizkraukles-pagasts'],
            ['id' => 466358, 'region_id' => 782760, 'country_code' => 'LV', 'name' => 'Daudzeses pagasts', 'active' => 1, 'slug' => 'daudzeses-pagasts'],
            ['id' => 466359, 'region_id' => 782760, 'country_code' => 'LV', 'name' => 'Seces pagasts', 'active' => 1, 'slug' => 'seces-pagasts'],
            ['id' => 466360, 'region_id' => 782760, 'country_code' => 'LV', 'name' => 'Sērenes pagasts', 'active' => 1, 'slug' => 'serenes-pagasts'],
            ['id' => 466361, 'region_id' => 782760, 'country_code' => 'LV', 'name' => 'Staburaga pagasts', 'active' => 1, 'slug' => 'staburaga-pagasts'],
            ['id' => 466362, 'region_id' => 782760, 'country_code' => 'LV', 'name' => 'Sunākstes pagasts', 'active' => 1, 'slug' => 'sunakstes-pagasts'],
            ['id' => 466363, 'region_id' => 782761, 'country_code' => 'LV', 'name' => 'Aiviekstes pagasts', 'active' => 1, 'slug' => 'aiviekstes-pagasts'],
            ['id' => 466364, 'region_id' => 782761, 'country_code' => 'LV', 'name' => 'Klintaines pagasts', 'active' => 1, 'slug' => 'klintaines-pagasts'],
            ['id' => 466365, 'region_id' => 782761, 'country_code' => 'LV', 'name' => 'Vietalvas pagasts', 'active' => 1, 'slug' => 'vietalvas-pagasts'],
            ['id' => 466366, 'region_id' => 782762, 'country_code' => 'LV', 'name' => 'Bebru pagasts', 'active' => 1, 'slug' => 'bebru-pagasts'],
            ['id' => 466367, 'region_id' => 782762, 'country_code' => 'LV', 'name' => 'Iršu pagasts', 'active' => 1, 'slug' => 'irsu-pagasts'],
            ['id' => 466368, 'region_id' => 782762, 'country_code' => 'LV', 'name' => 'Kokneses pagasts', 'active' => 1, 'slug' => 'kokneses-pagasts'],
            ['id' => 466369, 'region_id' => 782763, 'country_code' => 'LV', 'name' => 'Mazzalves pagasts', 'active' => 1, 'slug' => 'mazzalves-pagasts'],
            ['id' => 466370, 'region_id' => 782763, 'country_code' => 'LV', 'name' => 'Neretas pagasts', 'active' => 1, 'slug' => 'neretas-pagasts'],
            ['id' => 466371, 'region_id' => 782763, 'country_code' => 'LV', 'name' => 'Pilskalnes pagasts', 'active' => 1, 'slug' => 'pilskalnes-pagasts'],
            ['id' => 466372, 'region_id' => 782763, 'country_code' => 'LV', 'name' => 'Zalves pagasts', 'active' => 1, 'slug' => 'zalves-pagasts'],
            ['id' => 466373, 'region_id' => 782765, 'country_code' => 'LV', 'name' => 'Alsviķu pagasts', 'active' => 1, 'slug' => 'alsviku-pagasts'],
            ['id' => 466374, 'region_id' => 782765, 'country_code' => 'LV', 'name' => 'Annas pagasts', 'active' => 1, 'slug' => 'annas-pagasts'],
            ['id' => 466375, 'region_id' => 782765, 'country_code' => 'LV', 'name' => 'Ilzenes pagasts', 'active' => 1, 'slug' => 'ilzenes-pagasts'],
            ['id' => 466376, 'region_id' => 782765, 'country_code' => 'LV', 'name' => 'Jaunalūksnes pagasts', 'active' => 1, 'slug' => 'jaunaluksnes-pagasts'],
            ['id' => 466377, 'region_id' => 782765, 'country_code' => 'LV', 'name' => 'Jaunannas pagasts', 'active' => 1, 'slug' => 'jaunannas-pagasts'],
            ['id' => 466378, 'region_id' => 782765, 'country_code' => 'LV', 'name' => 'Jaunlaicenes pagasts', 'active' => 1, 'slug' => 'jaunlaicenes-pagasts'],
            ['id' => 466379, 'region_id' => 782765, 'country_code' => 'LV', 'name' => 'Kalncempju pagasts', 'active' => 1, 'slug' => 'kalncempju-pagasts'],
            ['id' => 466380, 'region_id' => 782765, 'country_code' => 'LV', 'name' => 'Liepnas pagasts', 'active' => 1, 'slug' => 'liepnas-pagasts'],
            ['id' => 466381, 'region_id' => 782765, 'country_code' => 'LV', 'name' => 'Malienas pagasts', 'active' => 1, 'slug' => 'malienas-pagasts'],
            ['id' => 466382, 'region_id' => 782765, 'country_code' => 'LV', 'name' => 'Mālupes pagasts', 'active' => 1, 'slug' => 'malupes-pagasts'],
            ['id' => 466383, 'region_id' => 782765, 'country_code' => 'LV', 'name' => 'Mārkalnes pagasts', 'active' => 1, 'slug' => 'markalnes-pagasts'],
            ['id' => 466384, 'region_id' => 782765, 'country_code' => 'LV', 'name' => 'Pededzes pagasts', 'active' => 1, 'slug' => 'pededzes-pagasts'],
            ['id' => 466385, 'region_id' => 782765, 'country_code' => 'LV', 'name' => 'Veclaicenes pagasts', 'active' => 1, 'slug' => 'veclaicenes-pagasts'],
            ['id' => 466386, 'region_id' => 782765, 'country_code' => 'LV', 'name' => 'Zeltiņu pagasts', 'active' => 1, 'slug' => 'zeltinu-pagasts'],
            ['id' => 466387, 'region_id' => 782765, 'country_code' => 'LV', 'name' => 'Ziemera pagasts', 'active' => 1, 'slug' => 'ziemera-pagasts'],
            ['id' => 466388, 'region_id' => 782766, 'country_code' => 'LV', 'name' => 'Gaujienas pagasts', 'active' => 1, 'slug' => 'gaujienas-pagasts'],
            ['id' => 466389, 'region_id' => 782766, 'country_code' => 'LV', 'name' => 'Trapenes pagasts', 'active' => 1, 'slug' => 'trapenes-pagasts'],
            ['id' => 466390, 'region_id' => 782766, 'country_code' => 'LV', 'name' => 'Virešu pagasts', 'active' => 1, 'slug' => 'viresu-pagasts'],
            ['id' => 466391, 'region_id' => 782767, 'country_code' => 'LV', 'name' => 'Balvu pagasts', 'active' => 1, 'slug' => 'balvu-pagasts'],
            ['id' => 466392, 'region_id' => 782767, 'country_code' => 'LV', 'name' => 'Bērzkalnes pagasts', 'active' => 1, 'slug' => 'berzkalnes-pagasts'],
            ['id' => 466393, 'region_id' => 782767, 'country_code' => 'LV', 'name' => 'Bērzpils pagasts', 'active' => 1, 'slug' => 'berzpils-pagasts'],
            ['id' => 466394, 'region_id' => 782767, 'country_code' => 'LV', 'name' => 'Briežuciema pagasts', 'active' => 1, 'slug' => 'briezuciema-pagasts'],
            ['id' => 466395, 'region_id' => 782767, 'country_code' => 'LV', 'name' => 'Krišjāņu pagasts', 'active' => 1, 'slug' => 'krisjanu-pagasts'],
            ['id' => 466396, 'region_id' => 782767, 'country_code' => 'LV', 'name' => 'Kubuļu pagasts', 'active' => 1, 'slug' => 'kubulu-pagasts'],
            ['id' => 466397, 'region_id' => 782767, 'country_code' => 'LV', 'name' => 'Lazdulejas pagasts', 'active' => 1, 'slug' => 'lazdulejas-pagasts'],
            ['id' => 466398, 'region_id' => 782767, 'country_code' => 'LV', 'name' => 'Tilžas pagasts', 'active' => 1, 'slug' => 'tilzas-pagasts'],
            ['id' => 466399, 'region_id' => 782767, 'country_code' => 'LV', 'name' => 'Vectilžas pagasts', 'active' => 1, 'slug' => 'vectilzas-pagasts'],
            ['id' => 466400, 'region_id' => 782767, 'country_code' => 'LV', 'name' => 'Vīksnas pagasts', 'active' => 1, 'slug' => 'viksnas-pagasts'],
            ['id' => 466401, 'region_id' => 782768, 'country_code' => 'LV', 'name' => 'Kupravas pagasts', 'active' => 1, 'slug' => 'kupravas-pagasts'],
            ['id' => 466402, 'region_id' => 782768, 'country_code' => 'LV', 'name' => 'Medņevas pagasts', 'active' => 1, 'slug' => 'mednevas-pagasts'],
            ['id' => 466403, 'region_id' => 782768, 'country_code' => 'LV', 'name' => 'Susāju pagasts', 'active' => 1, 'slug' => 'susaju-pagasts'],
            ['id' => 466404, 'region_id' => 782768, 'country_code' => 'LV', 'name' => 'Šķilbēnu pagasts', 'active' => 1, 'slug' => 'skilbenu-pagasts'],
            ['id' => 466405, 'region_id' => 782768, 'country_code' => 'LV', 'name' => 'Vecumu pagasts', 'active' => 1, 'slug' => 'vecumu-pagasts'],
            ['id' => 466406, 'region_id' => 782768, 'country_code' => 'LV', 'name' => 'Žīguru pagasts', 'active' => 1, 'slug' => 'ziguru-pagasts'],
            ['id' => 466407, 'region_id' => 782770, 'country_code' => 'LV', 'name' => 'Lazdukalna pagasts', 'active' => 1, 'slug' => 'lazdukalna-pagasts'],
            ['id' => 466408, 'region_id' => 782770, 'country_code' => 'LV', 'name' => 'Rugāju pagasts', 'active' => 1, 'slug' => 'rugaju-pagasts'],
            ['id' => 466409, 'region_id' => 782771, 'country_code' => 'LV', 'name' => 'Brunavas pagasts', 'active' => 1, 'slug' => 'brunavas-pagasts'],
            ['id' => 466410, 'region_id' => 782771, 'country_code' => 'LV', 'name' => 'Ceraukstes pagasts', 'active' => 1, 'slug' => 'ceraukstes-pagasts'],
            ['id' => 466411, 'region_id' => 782771, 'country_code' => 'LV', 'name' => 'Codes pagasts', 'active' => 1, 'slug' => 'codes-pagasts'],
            ['id' => 466412, 'region_id' => 782771, 'country_code' => 'LV', 'name' => 'Dāviņu pagasts', 'active' => 1, 'slug' => 'davinu-pagasts'],
            ['id' => 466413, 'region_id' => 782771, 'country_code' => 'LV', 'name' => 'Gailīšu pagasts', 'active' => 1, 'slug' => 'gailisu-pagasts'],
            ['id' => 466414, 'region_id' => 782771, 'country_code' => 'LV', 'name' => 'Īslīces pagasts', 'active' => 1, 'slug' => 'islices-pagasts'],
            ['id' => 466415, 'region_id' => 782771, 'country_code' => 'LV', 'name' => 'Mežotnes pagasts', 'active' => 1, 'slug' => 'mezotnes-pagasts'],
            ['id' => 466416, 'region_id' => 782771, 'country_code' => 'LV', 'name' => 'Vecsaules pagasts', 'active' => 1, 'slug' => 'vecsaules-pagasts'],
            ['id' => 466417, 'region_id' => 782773, 'country_code' => 'LV', 'name' => 'Rundāles pagasts', 'active' => 1, 'slug' => 'rundales-pagasts'],
            ['id' => 466418, 'region_id' => 782773, 'country_code' => 'LV', 'name' => 'Svitenes pagasts', 'active' => 1, 'slug' => 'svitenes-pagasts'],
            ['id' => 466419, 'region_id' => 782773, 'country_code' => 'LV', 'name' => 'Viesturu pagasts', 'active' => 1, 'slug' => 'viesturu-pagasts'],
            ['id' => 466420, 'region_id' => 782774, 'country_code' => 'LV', 'name' => 'Bārbeles pagasts', 'active' => 1, 'slug' => 'barbeles-pagasts'],
            ['id' => 466421, 'region_id' => 782774, 'country_code' => 'LV', 'name' => 'Kurmenes pagasts', 'active' => 1, 'slug' => 'kurmenes-pagasts'],
            ['id' => 466422, 'region_id' => 782774, 'country_code' => 'LV', 'name' => 'Skaistkalnes pagasts', 'active' => 1, 'slug' => 'skaistkalnes-pagasts'],
            ['id' => 466423, 'region_id' => 782774, 'country_code' => 'LV', 'name' => 'Stelpes pagasts', 'active' => 1, 'slug' => 'stelpes-pagasts'],
            ['id' => 466424, 'region_id' => 782774, 'country_code' => 'LV', 'name' => 'Valles pagasts', 'active' => 1, 'slug' => 'valles-pagasts'],
            ['id' => 466425, 'region_id' => 782774, 'country_code' => 'LV', 'name' => 'Vecumnieku pagasts', 'active' => 1, 'slug' => 'vecumnieku-pagasts'],
            ['id' => 466426, 'region_id' => 782775, 'country_code' => 'LV', 'name' => 'Vaives pagasts', 'active' => 1, 'slug' => 'vaives-pagasts'],
            ['id' => 466427, 'region_id' => 782776, 'country_code' => 'LV', 'name' => 'Līgatnes pagasts', 'active' => 1, 'slug' => 'ligatnes-pagasts'],
            ['id' => 466428, 'region_id' => 782777, 'country_code' => 'LV', 'name' => 'Amatas pagasts', 'active' => 1, 'slug' => 'amatas-pagasts'],
            ['id' => 466429, 'region_id' => 782777, 'country_code' => 'LV', 'name' => 'Drabešu pagasts', 'active' => 1, 'slug' => 'drabesu-pagasts'],
            ['id' => 466430, 'region_id' => 782777, 'country_code' => 'LV', 'name' => 'Nītaures pagasts', 'active' => 1, 'slug' => 'nitaures-pagasts'],
            ['id' => 466431, 'region_id' => 782777, 'country_code' => 'LV', 'name' => 'Skujenes pagasts', 'active' => 1, 'slug' => 'skujenes-pagasts'],
            ['id' => 466432, 'region_id' => 782777, 'country_code' => 'LV', 'name' => 'Zaubes pagasts', 'active' => 1, 'slug' => 'zaubes-pagasts'],
            ['id' => 466433, 'region_id' => 782778, 'country_code' => 'LV', 'name' => 'Jaunpiebalgas pagasts', 'active' => 1, 'slug' => 'jaunpiebalgas-pagasts'],
            ['id' => 466434, 'region_id' => 782778, 'country_code' => 'LV', 'name' => 'Zosēnu pagasts', 'active' => 1, 'slug' => 'zosenu-pagasts'],
            ['id' => 466435, 'region_id' => 782779, 'country_code' => 'LV', 'name' => 'Liepas pagasts', 'active' => 1, 'slug' => 'liepas-pagasts'],
            ['id' => 466436, 'region_id' => 782779, 'country_code' => 'LV', 'name' => 'Mārsnēnu pagasts', 'active' => 1, 'slug' => 'marsnenu-pagasts'],
            ['id' => 466437, 'region_id' => 782779, 'country_code' => 'LV', 'name' => 'Priekuļu pagasts', 'active' => 1, 'slug' => 'priekulu-pagasts'],
            ['id' => 466438, 'region_id' => 782779, 'country_code' => 'LV', 'name' => 'Veselavas pagasts', 'active' => 1, 'slug' => 'veselavas-pagasts'],
            ['id' => 466439, 'region_id' => 782780, 'country_code' => 'LV', 'name' => 'Raiskuma pagasts', 'active' => 1, 'slug' => 'raiskuma-pagasts'],
            ['id' => 466440, 'region_id' => 782780, 'country_code' => 'LV', 'name' => 'Stalbes pagasts', 'active' => 1, 'slug' => 'stalbes-pagasts'],
            ['id' => 466441, 'region_id' => 782780, 'country_code' => 'LV', 'name' => 'Straupes pagasts', 'active' => 1, 'slug' => 'straupes-pagasts'],
            ['id' => 466442, 'region_id' => 782781, 'country_code' => 'LV', 'name' => 'Drustu pagasts', 'active' => 1, 'slug' => 'drustu-pagasts'],
            ['id' => 466443, 'region_id' => 782781, 'country_code' => 'LV', 'name' => 'Raunas pagasts', 'active' => 1, 'slug' => 'raunas-pagasts'],
            ['id' => 466444, 'region_id' => 782782, 'country_code' => 'LV', 'name' => 'Dzērbenes pagasts', 'active' => 1, 'slug' => 'dzerbenes-pagasts'],
            ['id' => 466445, 'region_id' => 782782, 'country_code' => 'LV', 'name' => 'Inešu pagasts', 'active' => 1, 'slug' => 'inesu-pagasts'],
            ['id' => 466446, 'region_id' => 782782, 'country_code' => 'LV', 'name' => 'Kaives pagasts', 'active' => 1, 'slug' => 'kaives-pagasts'],
            ['id' => 466447, 'region_id' => 782782, 'country_code' => 'LV', 'name' => 'Taurenes pagasts', 'active' => 1, 'slug' => 'taurenes-pagasts'],
            ['id' => 466448, 'region_id' => 782782, 'country_code' => 'LV', 'name' => 'Vecpiebalgas pagasts', 'active' => 1, 'slug' => 'vecpiebalgas-pagasts'],
            ['id' => 466449, 'region_id' => 782783, 'country_code' => 'LV', 'name' => 'Ambeļu pagasts', 'active' => 1, 'slug' => 'ambelu-pagasts'],
            ['id' => 466450, 'region_id' => 782783, 'country_code' => 'LV', 'name' => 'Biķernieku pagasts', 'active' => 1, 'slug' => 'bikernieku-pagasts'],
            ['id' => 466451, 'region_id' => 782783, 'country_code' => 'LV', 'name' => 'Demenes pagasts', 'active' => 1, 'slug' => 'demenes-pagasts'],
            ['id' => 466452, 'region_id' => 782783, 'country_code' => 'LV', 'name' => 'Dubnas pagasts', 'active' => 1, 'slug' => 'dubnas-pagasts'],
            ['id' => 466453, 'region_id' => 782783, 'country_code' => 'LV', 'name' => 'Kalkūnes pagasts', 'active' => 1, 'slug' => 'kalkunes-pagasts'],
            ['id' => 466454, 'region_id' => 782783, 'country_code' => 'LV', 'name' => 'Kalupes pagasts', 'active' => 1, 'slug' => 'kalupes-pagasts'],
            ['id' => 466455, 'region_id' => 782783, 'country_code' => 'LV', 'name' => 'Laucesas pagasts', 'active' => 1, 'slug' => 'laucesas-pagasts'],
            ['id' => 466456, 'region_id' => 782783, 'country_code' => 'LV', 'name' => 'Līksnas pagasts', 'active' => 1, 'slug' => 'liksnas-pagasts'],
            ['id' => 466457, 'region_id' => 782783, 'country_code' => 'LV', 'name' => 'Maļinovas pagasts', 'active' => 1, 'slug' => 'malinovas-pagasts'],
            ['id' => 466458, 'region_id' => 782783, 'country_code' => 'LV', 'name' => 'Medumu pagasts', 'active' => 1, 'slug' => 'medumu-pagasts'],
            ['id' => 466459, 'region_id' => 782783, 'country_code' => 'LV', 'name' => 'Naujenes pagasts', 'active' => 1, 'slug' => 'naujenes-pagasts'],
            ['id' => 466460, 'region_id' => 782783, 'country_code' => 'LV', 'name' => 'Nīcgales pagasts', 'active' => 1, 'slug' => 'nicgales-pagasts'],
            ['id' => 466461, 'region_id' => 782783, 'country_code' => 'LV', 'name' => 'Salienas pagasts', 'active' => 1, 'slug' => 'salienas-pagasts'],
            ['id' => 466462, 'region_id' => 782783, 'country_code' => 'LV', 'name' => 'Skrudalienas pagasts', 'active' => 1, 'slug' => 'skrudalienas-pagasts'],
            ['id' => 466463, 'region_id' => 782783, 'country_code' => 'LV', 'name' => 'Sventes pagasts', 'active' => 1, 'slug' => 'sventes-pagasts'],
            ['id' => 466464, 'region_id' => 782783, 'country_code' => 'LV', 'name' => 'Tabores pagasts', 'active' => 1, 'slug' => 'tabores-pagasts'],
            ['id' => 466465, 'region_id' => 782783, 'country_code' => 'LV', 'name' => 'Vaboles pagasts', 'active' => 1, 'slug' => 'vaboles-pagasts'],
            ['id' => 466466, 'region_id' => 782783, 'country_code' => 'LV', 'name' => 'Vecsalienas pagasts', 'active' => 1, 'slug' => 'vecsalienas-pagasts'],
            ['id' => 466467, 'region_id' => 782783, 'country_code' => 'LV', 'name' => 'Višķu pagasts', 'active' => 1, 'slug' => 'visku-pagasts'],
            ['id' => 466468, 'region_id' => 782784, 'country_code' => 'LV', 'name' => 'Bebrenes pagasts', 'active' => 1, 'slug' => 'bebrenes-pagasts'],
            ['id' => 466469, 'region_id' => 782784, 'country_code' => 'LV', 'name' => 'Dvietes pagasts', 'active' => 1, 'slug' => 'dvietes-pagasts'],
            ['id' => 466470, 'region_id' => 782784, 'country_code' => 'LV', 'name' => 'Eglaines pagasts', 'active' => 1, 'slug' => 'eglaines-pagasts'],
            ['id' => 466471, 'region_id' => 782784, 'country_code' => 'LV', 'name' => 'Pilskalnes pagasts', 'active' => 1, 'slug' => 'pilskalnes-pagasts'],
            ['id' => 466472, 'region_id' => 782784, 'country_code' => 'LV', 'name' => 'Šēderes pagasts', 'active' => 1, 'slug' => 'sederes-pagasts'],
            ['id' => 466473, 'region_id' => 782785, 'country_code' => 'LV', 'name' => 'Annenieku pagasts', 'active' => 1, 'slug' => 'annenieku-pagasts'],
            ['id' => 466474, 'region_id' => 782785, 'country_code' => 'LV', 'name' => 'Auru pagasts', 'active' => 1, 'slug' => 'auru-pagasts'],
            ['id' => 466475, 'region_id' => 782785, 'country_code' => 'LV', 'name' => 'Bērzes pagasts', 'active' => 1, 'slug' => 'berzes-pagasts'],
            ['id' => 466476, 'region_id' => 782785, 'country_code' => 'LV', 'name' => 'Bikstu pagasts', 'active' => 1, 'slug' => 'bikstu-pagasts'],
            ['id' => 466477, 'region_id' => 782785, 'country_code' => 'LV', 'name' => 'Dobeles pagasts', 'active' => 1, 'slug' => 'dobeles-pagasts'],
            ['id' => 466478, 'region_id' => 782785, 'country_code' => 'LV', 'name' => 'Jaunbērzes pagasts', 'active' => 1, 'slug' => 'jaunberzes-pagasts'],
            ['id' => 466479, 'region_id' => 782785, 'country_code' => 'LV', 'name' => 'Krimūnu pagasts', 'active' => 1, 'slug' => 'krimunu-pagasts'],
            ['id' => 466480, 'region_id' => 782785, 'country_code' => 'LV', 'name' => 'Naudītes pagasts', 'active' => 1, 'slug' => 'naudites-pagasts'],
            ['id' => 466481, 'region_id' => 782785, 'country_code' => 'LV', 'name' => 'Penkules pagasts', 'active' => 1, 'slug' => 'penkules-pagasts'],
            ['id' => 466482, 'region_id' => 782785, 'country_code' => 'LV', 'name' => 'Zebrenes pagasts', 'active' => 1, 'slug' => 'zebrenes-pagasts'],
            ['id' => 466483, 'region_id' => 782786, 'country_code' => 'LV', 'name' => 'Bēnes pagasts', 'active' => 1, 'slug' => 'benes-pagasts'],
            ['id' => 466484, 'region_id' => 782786, 'country_code' => 'LV', 'name' => 'Īles pagasts', 'active' => 1, 'slug' => 'iles-pagasts'],
            ['id' => 466485, 'region_id' => 782786, 'country_code' => 'LV', 'name' => 'Lielauces pagasts', 'active' => 1, 'slug' => 'lielauces-pagasts'],
            ['id' => 466486, 'region_id' => 782786, 'country_code' => 'LV', 'name' => 'Ukru pagasts', 'active' => 1, 'slug' => 'ukru-pagasts'],
            ['id' => 466487, 'region_id' => 782786, 'country_code' => 'LV', 'name' => 'Vītiņu pagasts', 'active' => 1, 'slug' => 'vitinu-pagasts'],
            ['id' => 466488, 'region_id' => 782787, 'country_code' => 'LV', 'name' => 'Augstkalnes pagasts', 'active' => 1, 'slug' => 'augstkalnes-pagasts'],
            ['id' => 466489, 'region_id' => 782787, 'country_code' => 'LV', 'name' => 'Bukaišu pagasts', 'active' => 1, 'slug' => 'bukaisu-pagasts'],
            ['id' => 466490, 'region_id' => 782787, 'country_code' => 'LV', 'name' => 'Tērvetes pagasts', 'active' => 1, 'slug' => 'tervetes-pagasts'],
            ['id' => 466491, 'region_id' => 782788, 'country_code' => 'LV', 'name' => 'Beļavas pagasts', 'active' => 1, 'slug' => 'belavas-pagasts'],
            ['id' => 466492, 'region_id' => 782788, 'country_code' => 'LV', 'name' => 'Daukstu pagasts', 'active' => 1, 'slug' => 'daukstu-pagasts'],
            ['id' => 466493, 'region_id' => 782788, 'country_code' => 'LV', 'name' => 'Druvienas pagasts', 'active' => 1, 'slug' => 'druvienas-pagasts'],
            ['id' => 466494, 'region_id' => 782788, 'country_code' => 'LV', 'name' => 'Galgauskas pagasts', 'active' => 1, 'slug' => 'galgauskas-pagasts'],
            ['id' => 466495, 'region_id' => 782788, 'country_code' => 'LV', 'name' => 'Jaungulbenes pagasts', 'active' => 1, 'slug' => 'jaungulbenes-pagasts'],
            ['id' => 466496, 'region_id' => 782788, 'country_code' => 'LV', 'name' => 'Lejasciema pagasts', 'active' => 1, 'slug' => 'lejasciema-pagasts'],
            ['id' => 466497, 'region_id' => 782788, 'country_code' => 'LV', 'name' => 'Litenes pagasts', 'active' => 1, 'slug' => 'litenes-pagasts'],
            ['id' => 466498, 'region_id' => 782788, 'country_code' => 'LV', 'name' => 'Lizuma pagasts', 'active' => 1, 'slug' => 'lizuma-pagasts'],
            ['id' => 466499, 'region_id' => 782788, 'country_code' => 'LV', 'name' => 'Līgo pagasts', 'active' => 1, 'slug' => 'ligo-pagasts'],
            ['id' => 466500, 'region_id' => 782788, 'country_code' => 'LV', 'name' => 'Rankas pagasts', 'active' => 1, 'slug' => 'rankas-pagasts'],
            ['id' => 466501, 'region_id' => 782788, 'country_code' => 'LV', 'name' => 'Stāmerienas pagasts', 'active' => 1, 'slug' => 'stamerienas-pagasts'],
            ['id' => 466502, 'region_id' => 782788, 'country_code' => 'LV', 'name' => 'Stradu pagasts', 'active' => 1, 'slug' => 'stradu-pagasts'],
            ['id' => 466503, 'region_id' => 782788, 'country_code' => 'LV', 'name' => 'Tirzas pagasts', 'active' => 1, 'slug' => 'tirzas-pagasts'],
            ['id' => 466504, 'region_id' => 782789, 'country_code' => 'LV', 'name' => 'Elejas pagasts', 'active' => 1, 'slug' => 'elejas-pagasts'],
            ['id' => 466505, 'region_id' => 782789, 'country_code' => 'LV', 'name' => 'Glūdas pagasts', 'active' => 1, 'slug' => 'gludas-pagasts'],
            ['id' => 466506, 'region_id' => 782789, 'country_code' => 'LV', 'name' => 'Jaunsvirlaukas pagasts', 'active' => 1, 'slug' => 'jaunsvirlaukas-pagasts'],
            ['id' => 466507, 'region_id' => 782789, 'country_code' => 'LV', 'name' => 'Lielplatones pagasts', 'active' => 1, 'slug' => 'lielplatones-pagasts'],
            ['id' => 466508, 'region_id' => 782789, 'country_code' => 'LV', 'name' => 'Līvbērzes pagasts', 'active' => 1, 'slug' => 'livberzes-pagasts'],
            ['id' => 466509, 'region_id' => 782789, 'country_code' => 'LV', 'name' => 'Platones pagasts', 'active' => 1, 'slug' => 'platones-pagasts'],
            ['id' => 466510, 'region_id' => 782789, 'country_code' => 'LV', 'name' => 'Sesavas pagasts', 'active' => 1, 'slug' => 'sesavas-pagasts'],
            ['id' => 466511, 'region_id' => 782789, 'country_code' => 'LV', 'name' => 'Svētes pagasts', 'active' => 1, 'slug' => 'svetes-pagasts'],
            ['id' => 466512, 'region_id' => 782789, 'country_code' => 'LV', 'name' => 'Valgundes pagasts', 'active' => 1, 'slug' => 'valgundes-pagasts'],
            ['id' => 466513, 'region_id' => 782789, 'country_code' => 'LV', 'name' => 'Vilces pagasts', 'active' => 1, 'slug' => 'vilces-pagasts'],
            ['id' => 466514, 'region_id' => 782789, 'country_code' => 'LV', 'name' => 'Vircavas pagasts', 'active' => 1, 'slug' => 'vircavas-pagasts'],
            ['id' => 466515, 'region_id' => 782789, 'country_code' => 'LV', 'name' => 'Zaļenieku pagasts', 'active' => 1, 'slug' => 'zalenieku-pagasts'],
            ['id' => 466516, 'region_id' => 782790, 'country_code' => 'LV', 'name' => 'Cenu pagasts', 'active' => 1, 'slug' => 'cenu-pagasts'],
            ['id' => 466517, 'region_id' => 782790, 'country_code' => 'LV', 'name' => 'Ozolnieku pagasts', 'active' => 1, 'slug' => 'ozolnieku-pagasts'],
            ['id' => 466518, 'region_id' => 782790, 'country_code' => 'LV', 'name' => 'Sidrabenes pagasts', 'active' => 1, 'slug' => 'sidrabenes-pagasts'],
            ['id' => 466519, 'region_id' => 782791, 'country_code' => 'LV', 'name' => 'Ābeļu pagasts', 'active' => 1, 'slug' => 'abelu-pagasts'],
            ['id' => 466520, 'region_id' => 782791, 'country_code' => 'LV', 'name' => 'Dignājas pagasts', 'active' => 1, 'slug' => 'dignajas-pagasts'],
            ['id' => 466521, 'region_id' => 782791, 'country_code' => 'LV', 'name' => 'Dunavas pagasts', 'active' => 1, 'slug' => 'dunavas-pagasts'],
            ['id' => 466522, 'region_id' => 782791, 'country_code' => 'LV', 'name' => 'Kalna pagasts', 'active' => 1, 'slug' => 'kalna-pagasts'],
            ['id' => 466523, 'region_id' => 782791, 'country_code' => 'LV', 'name' => 'Leimaņu pagasts', 'active' => 1, 'slug' => 'leimanu-pagasts'],
            ['id' => 466524, 'region_id' => 782791, 'country_code' => 'LV', 'name' => 'Rubenes pagasts', 'active' => 1, 'slug' => 'rubenes-pagasts'],
            ['id' => 466525, 'region_id' => 782791, 'country_code' => 'LV', 'name' => 'Zasas pagasts', 'active' => 1, 'slug' => 'zasas-pagasts'],
            ['id' => 466526, 'region_id' => 782792, 'country_code' => 'LV', 'name' => 'Asares pagasts', 'active' => 1, 'slug' => 'asares-pagasts'],
            ['id' => 466527, 'region_id' => 782792, 'country_code' => 'LV', 'name' => 'Gārsenes pagasts', 'active' => 1, 'slug' => 'garsenes-pagasts'],
            ['id' => 466528, 'region_id' => 782793, 'country_code' => 'LV', 'name' => 'Elkšņu pagasts', 'active' => 1, 'slug' => 'elksnu-pagasts'],
            ['id' => 466529, 'region_id' => 782793, 'country_code' => 'LV', 'name' => 'Rites pagasts', 'active' => 1, 'slug' => 'rites-pagasts'],
            ['id' => 466530, 'region_id' => 782793, 'country_code' => 'LV', 'name' => 'Saukas pagasts', 'active' => 1, 'slug' => 'saukas-pagasts'],
            ['id' => 466531, 'region_id' => 782794, 'country_code' => 'LV', 'name' => 'Atašienes pagasts', 'active' => 1, 'slug' => 'atasienes-pagasts'],
            ['id' => 466532, 'region_id' => 782794, 'country_code' => 'LV', 'name' => 'Krustpils pagasts', 'active' => 1, 'slug' => 'krustpils-pagasts'],
            ['id' => 466533, 'region_id' => 782794, 'country_code' => 'LV', 'name' => 'Kūku pagasts', 'active' => 1, 'slug' => 'kuku-pagasts'],
            ['id' => 466534, 'region_id' => 782794, 'country_code' => 'LV', 'name' => 'Mežāres pagasts', 'active' => 1, 'slug' => 'mezares-pagasts'],
            ['id' => 466535, 'region_id' => 782794, 'country_code' => 'LV', 'name' => 'Variešu pagasts', 'active' => 1, 'slug' => 'variesu-pagasts'],
            ['id' => 466536, 'region_id' => 782794, 'country_code' => 'LV', 'name' => 'Vīpes pagasts', 'active' => 1, 'slug' => 'vipes-pagasts'],
            ['id' => 466537, 'region_id' => 782795, 'country_code' => 'LV', 'name' => 'Salas pagasts', 'active' => 1, 'slug' => 'salas-pagasts'],
            ['id' => 466538, 'region_id' => 782795, 'country_code' => 'LV', 'name' => 'Sēlpils pagasts', 'active' => 1, 'slug' => 'selpils-pagasts'],
            ['id' => 466539, 'region_id' => 782796, 'country_code' => 'LV', 'name' => 'Aulejas pagasts', 'active' => 1, 'slug' => 'aulejas-pagasts'],
            ['id' => 466540, 'region_id' => 782796, 'country_code' => 'LV', 'name' => 'Indras pagasts', 'active' => 1, 'slug' => 'indras-pagasts'],
            ['id' => 466541, 'region_id' => 782796, 'country_code' => 'LV', 'name' => 'Izvaltas pagasts', 'active' => 1, 'slug' => 'izvaltas-pagasts'],
            ['id' => 466542, 'region_id' => 782796, 'country_code' => 'LV', 'name' => 'Kalniešu pagasts', 'active' => 1, 'slug' => 'kalniesu-pagasts'],
            ['id' => 466543, 'region_id' => 782796, 'country_code' => 'LV', 'name' => 'Kaplavas pagasts', 'active' => 1, 'slug' => 'kaplavas-pagasts'],
            ['id' => 466544, 'region_id' => 782796, 'country_code' => 'LV', 'name' => 'Kombuļu pagasts', 'active' => 1, 'slug' => 'kombulu-pagasts'],
            ['id' => 466545, 'region_id' => 782796, 'country_code' => 'LV', 'name' => 'Krāslavas pagasts', 'active' => 1, 'slug' => 'kraslavas-pagasts'],
            ['id' => 466546, 'region_id' => 782796, 'country_code' => 'LV', 'name' => 'Piedrujas pagasts', 'active' => 1, 'slug' => 'piedrujas-pagasts'],
            ['id' => 466547, 'region_id' => 782796, 'country_code' => 'LV', 'name' => 'Robežnieku pagasts', 'active' => 1, 'slug' => 'robeznieku-pagasts'],
            ['id' => 466548, 'region_id' => 782796, 'country_code' => 'LV', 'name' => 'Skaistas pagasts', 'active' => 1, 'slug' => 'skaistas-pagasts'],
            ['id' => 466549, 'region_id' => 782796, 'country_code' => 'LV', 'name' => 'Ūdrīšu pagasts', 'active' => 1, 'slug' => 'udrisu-pagasts'],
            ['id' => 466550, 'region_id' => 782797, 'country_code' => 'LV', 'name' => 'Andrupenes pagasts', 'active' => 1, 'slug' => 'andrupenes-pagasts'],
            ['id' => 466551, 'region_id' => 782797, 'country_code' => 'LV', 'name' => 'Andzeļu pagasts', 'active' => 1, 'slug' => 'andzelu-pagasts'],
            ['id' => 466552, 'region_id' => 782797, 'country_code' => 'LV', 'name' => 'Asūnes pagasts', 'active' => 1, 'slug' => 'asunes-pagasts'],
            ['id' => 466553, 'region_id' => 782797, 'country_code' => 'LV', 'name' => 'Bērziņu pagasts', 'active' => 1, 'slug' => 'berzinu-pagasts'],
            ['id' => 466554, 'region_id' => 782797, 'country_code' => 'LV', 'name' => 'Dagdas pagasts', 'active' => 1, 'slug' => 'dagdas-pagasts'],
            ['id' => 466555, 'region_id' => 782797, 'country_code' => 'LV', 'name' => 'Ezernieku pagasts', 'active' => 1, 'slug' => 'ezernieku-pagasts'],
            ['id' => 466556, 'region_id' => 782797, 'country_code' => 'LV', 'name' => 'Konstantinovas pagasts', 'active' => 1, 'slug' => 'konstantinovas-pagasts'],
            ['id' => 466557, 'region_id' => 782797, 'country_code' => 'LV', 'name' => 'Ķepovas pagasts', 'active' => 1, 'slug' => 'kepovas-pagasts'],
            ['id' => 466558, 'region_id' => 782797, 'country_code' => 'LV', 'name' => 'Svariņu pagasts', 'active' => 1, 'slug' => 'svarinu-pagasts'],
            ['id' => 466559, 'region_id' => 782797, 'country_code' => 'LV', 'name' => 'Šķaunes pagasts', 'active' => 1, 'slug' => 'skaunes-pagasts'],
            ['id' => 466560, 'region_id' => 782798, 'country_code' => 'LV', 'name' => 'Aglonas pagasts', 'active' => 1, 'slug' => 'aglonas-pagasts'],
            ['id' => 466561, 'region_id' => 782798, 'country_code' => 'LV', 'name' => 'Grāveru pagasts', 'active' => 1, 'slug' => 'graveru-pagasts'],
            ['id' => 466562, 'region_id' => 782798, 'country_code' => 'LV', 'name' => 'Kastuļinas pagasts', 'active' => 1, 'slug' => 'kastulinas-pagasts'],
            ['id' => 466563, 'region_id' => 782798, 'country_code' => 'LV', 'name' => 'Šķeltovas pagasts', 'active' => 1, 'slug' => 'skeltovas-pagasts'],
            ['id' => 466564, 'region_id' => 782799, 'country_code' => 'LV', 'name' => 'Ēdoles pagasts', 'active' => 1, 'slug' => 'edoles-pagasts'],
            ['id' => 466565, 'region_id' => 782799, 'country_code' => 'LV', 'name' => 'Gudenieku pagasts', 'active' => 1, 'slug' => 'gudenieku-pagasts'],
            ['id' => 466566, 'region_id' => 782799, 'country_code' => 'LV', 'name' => 'Īvandes pagasts', 'active' => 1, 'slug' => 'ivandes-pagasts'],
            ['id' => 466567, 'region_id' => 782799, 'country_code' => 'LV', 'name' => 'Kabiles pagasts', 'active' => 1, 'slug' => 'kabiles-pagasts'],
            ['id' => 466568, 'region_id' => 782799, 'country_code' => 'LV', 'name' => 'Kurmāles pagasts', 'active' => 1, 'slug' => 'kurmales-pagasts'],
            ['id' => 466569, 'region_id' => 782799, 'country_code' => 'LV', 'name' => 'Laidu pagasts', 'active' => 1, 'slug' => 'laidu-pagasts'],
            ['id' => 466570, 'region_id' => 782799, 'country_code' => 'LV', 'name' => 'Padures pagasts', 'active' => 1, 'slug' => 'padures-pagasts'],
            ['id' => 466571, 'region_id' => 782799, 'country_code' => 'LV', 'name' => 'Pelču pagasts', 'active' => 1, 'slug' => 'pelcu-pagasts'],
            ['id' => 466572, 'region_id' => 782799, 'country_code' => 'LV', 'name' => 'Rendas pagasts', 'active' => 1, 'slug' => 'rendas-pagasts'],
            ['id' => 466573, 'region_id' => 782799, 'country_code' => 'LV', 'name' => 'Rumbas pagasts', 'active' => 1, 'slug' => 'rumbas-pagasts'],
            ['id' => 466574, 'region_id' => 782799, 'country_code' => 'LV', 'name' => 'Snēpeles pagasts', 'active' => 1, 'slug' => 'snepeles-pagasts'],
            ['id' => 466575, 'region_id' => 782799, 'country_code' => 'LV', 'name' => 'Turlavas pagasts', 'active' => 1, 'slug' => 'turlavas-pagasts'],
            ['id' => 466576, 'region_id' => 782799, 'country_code' => 'LV', 'name' => 'Vārmes pagasts', 'active' => 1, 'slug' => 'varmes-pagasts'],
            ['id' => 466577, 'region_id' => 782800, 'country_code' => 'LV', 'name' => 'Nīkrāces pagasts', 'active' => 1, 'slug' => 'nikraces-pagasts'],
            ['id' => 466578, 'region_id' => 782800, 'country_code' => 'LV', 'name' => 'Raņķu pagasts', 'active' => 1, 'slug' => 'ranku-pagasts'],
            ['id' => 466579, 'region_id' => 782800, 'country_code' => 'LV', 'name' => 'Rudbāržu pagasts', 'active' => 1, 'slug' => 'rudbarzu-pagasts'],
            ['id' => 466580, 'region_id' => 782802, 'country_code' => 'LV', 'name' => 'Aizputes pagasts', 'active' => 1, 'slug' => 'aizputes-pagasts'],
            ['id' => 466581, 'region_id' => 782802, 'country_code' => 'LV', 'name' => 'Cīravas pagasts', 'active' => 1, 'slug' => 'ciravas-pagasts'],
            ['id' => 466582, 'region_id' => 782802, 'country_code' => 'LV', 'name' => 'Kalvenes pagasts', 'active' => 1, 'slug' => 'kalvenes-pagasts'],
            ['id' => 466583, 'region_id' => 782802, 'country_code' => 'LV', 'name' => 'Kazdangas pagasts', 'active' => 1, 'slug' => 'kazdangas-pagasts'],
            ['id' => 466584, 'region_id' => 782802, 'country_code' => 'LV', 'name' => 'Lažas pagasts', 'active' => 1, 'slug' => 'lazas-pagasts'],
            ['id' => 466585, 'region_id' => 782803, 'country_code' => 'LV', 'name' => 'Dunalkas pagasts', 'active' => 1, 'slug' => 'dunalkas-pagasts'],
            ['id' => 466586, 'region_id' => 782803, 'country_code' => 'LV', 'name' => 'Tadaiķu pagasts', 'active' => 1, 'slug' => 'tadaiku-pagasts'],
            ['id' => 466587, 'region_id' => 782803, 'country_code' => 'LV', 'name' => 'Vecpils pagasts', 'active' => 1, 'slug' => 'vecpils-pagasts'],
            ['id' => 466588, 'region_id' => 782804, 'country_code' => 'LV', 'name' => 'Bārtas pagasts', 'active' => 1, 'slug' => 'bartas-pagasts'],
            ['id' => 466589, 'region_id' => 782804, 'country_code' => 'LV', 'name' => 'Gaviezes pagasts', 'active' => 1, 'slug' => 'gaviezes-pagasts'],
            ['id' => 466590, 'region_id' => 782804, 'country_code' => 'LV', 'name' => 'Grobiņas pagasts', 'active' => 1, 'slug' => 'grobinas-pagasts'],
            ['id' => 466591, 'region_id' => 782804, 'country_code' => 'LV', 'name' => 'Medzes pagasts', 'active' => 1, 'slug' => 'medzes-pagasts'],
            ['id' => 466592, 'region_id' => 782805, 'country_code' => 'LV', 'name' => 'Sakas pagasts', 'active' => 1, 'slug' => 'sakas-pagasts'],
            ['id' => 466593, 'region_id' => 782805, 'country_code' => 'LV', 'name' => 'Vērgales pagasts', 'active' => 1, 'slug' => 'vergales-pagasts'],
            ['id' => 466594, 'region_id' => 782806, 'country_code' => 'LV', 'name' => 'Bunkas pagasts', 'active' => 1, 'slug' => 'bunkas-pagasts'],
            ['id' => 466595, 'region_id' => 782806, 'country_code' => 'LV', 'name' => 'Gramzdas pagasts', 'active' => 1, 'slug' => 'gramzdas-pagasts'],
            ['id' => 466596, 'region_id' => 782806, 'country_code' => 'LV', 'name' => 'Kalētu pagasts', 'active' => 1, 'slug' => 'kaletu-pagasts'],
            ['id' => 466597, 'region_id' => 782806, 'country_code' => 'LV', 'name' => 'Priekules pagasts', 'active' => 1, 'slug' => 'priekules-pagasts'],
            ['id' => 466598, 'region_id' => 782806, 'country_code' => 'LV', 'name' => 'Virgas pagasts', 'active' => 1, 'slug' => 'virgas-pagasts'],
            ['id' => 466599, 'region_id' => 782807, 'country_code' => 'LV', 'name' => 'Nīcas pagasts', 'active' => 1, 'slug' => 'nicas-pagasts'],
            ['id' => 466600, 'region_id' => 782807, 'country_code' => 'LV', 'name' => 'Otaņķu pagasts', 'active' => 1, 'slug' => 'otanku-pagasts'],
            ['id' => 466601, 'region_id' => 782808, 'country_code' => 'LV', 'name' => 'Dunikas pagasts', 'active' => 1, 'slug' => 'dunikas-pagasts'],
            ['id' => 466602, 'region_id' => 782808, 'country_code' => 'LV', 'name' => 'Rucavas pagasts', 'active' => 1, 'slug' => 'rucavas-pagasts'],
            ['id' => 466603, 'region_id' => 782809, 'country_code' => 'LV', 'name' => 'Embūtes pagasts', 'active' => 1, 'slug' => 'embutes-pagasts'],
            ['id' => 466604, 'region_id' => 782809, 'country_code' => 'LV', 'name' => 'Vaiņodes pagasts', 'active' => 1, 'slug' => 'vainodes-pagasts'],
            ['id' => 466605, 'region_id' => 782810, 'country_code' => 'LV', 'name' => 'Katvaru pagasts', 'active' => 1, 'slug' => 'katvaru-pagasts'],
            ['id' => 466606, 'region_id' => 782810, 'country_code' => 'LV', 'name' => 'Limbažu pagasts', 'active' => 1, 'slug' => 'limbazu-pagasts'],
            ['id' => 466607, 'region_id' => 782810, 'country_code' => 'LV', 'name' => 'Pāles pagasts', 'active' => 1, 'slug' => 'pales-pagasts'],
            ['id' => 466608, 'region_id' => 782810, 'country_code' => 'LV', 'name' => 'Skultes pagasts', 'active' => 1, 'slug' => 'skultes-pagasts'],
            ['id' => 466609, 'region_id' => 782810, 'country_code' => 'LV', 'name' => 'Umurgas pagasts', 'active' => 1, 'slug' => 'umurgas-pagasts'],
            ['id' => 466610, 'region_id' => 782810, 'country_code' => 'LV', 'name' => 'Vidrižu pagasts', 'active' => 1, 'slug' => 'vidrizu-pagasts'],
            ['id' => 466611, 'region_id' => 782810, 'country_code' => 'LV', 'name' => 'Viļķenes pagasts', 'active' => 1, 'slug' => 'vilkenes-pagasts'],
            ['id' => 466612, 'region_id' => 782811, 'country_code' => 'LV', 'name' => 'Braslavas pagasts', 'active' => 1, 'slug' => 'braslavas-pagasts'],
            ['id' => 466613, 'region_id' => 782811, 'country_code' => 'LV', 'name' => 'Brīvzemnieku pagasts', 'active' => 1, 'slug' => 'brivzemnieku-pagasts'],
            ['id' => 466614, 'region_id' => 782812, 'country_code' => 'LV', 'name' => 'Liepupes pagasts', 'active' => 1, 'slug' => 'liepupes-pagasts'],
            ['id' => 466615, 'region_id' => 782813, 'country_code' => 'LV', 'name' => 'Briģu pagasts', 'active' => 1, 'slug' => 'brigu-pagasts'],
            ['id' => 466616, 'region_id' => 782813, 'country_code' => 'LV', 'name' => 'Cirmas pagasts', 'active' => 1, 'slug' => 'cirmas-pagasts'],
            ['id' => 466617, 'region_id' => 782813, 'country_code' => 'LV', 'name' => 'Isnaudas pagasts', 'active' => 1, 'slug' => 'isnaudas-pagasts'],
            ['id' => 466618, 'region_id' => 782813, 'country_code' => 'LV', 'name' => 'Istras pagasts', 'active' => 1, 'slug' => 'istras-pagasts'],
            ['id' => 466619, 'region_id' => 782813, 'country_code' => 'LV', 'name' => 'Nirzas pagasts', 'active' => 1, 'slug' => 'nirzas-pagasts'],
            ['id' => 466620, 'region_id' => 782813, 'country_code' => 'LV', 'name' => 'Ņukšu pagasts', 'active' => 1, 'slug' => 'nuksu-pagasts'],
            ['id' => 466621, 'region_id' => 782813, 'country_code' => 'LV', 'name' => 'Pildas pagasts', 'active' => 1, 'slug' => 'pildas-pagasts'],
            ['id' => 466622, 'region_id' => 782813, 'country_code' => 'LV', 'name' => 'Pureņu pagasts', 'active' => 1, 'slug' => 'purenu-pagasts'],
            ['id' => 466623, 'region_id' => 782813, 'country_code' => 'LV', 'name' => 'Rundēnu pagasts', 'active' => 1, 'slug' => 'rundenu-pagasts'],
            ['id' => 466624, 'region_id' => 782814, 'country_code' => 'LV', 'name' => 'Goliševas pagasts', 'active' => 1, 'slug' => 'golisevas-pagasts'],
            ['id' => 466625, 'region_id' => 782814, 'country_code' => 'LV', 'name' => 'Malnavas pagasts', 'active' => 1, 'slug' => 'malnavas-pagasts'],
            ['id' => 466626, 'region_id' => 782814, 'country_code' => 'LV', 'name' => 'Mežvidu pagasts', 'active' => 1, 'slug' => 'mezvidu-pagasts'],
            ['id' => 466627, 'region_id' => 782814, 'country_code' => 'LV', 'name' => 'Mērdzenes pagasts', 'active' => 1, 'slug' => 'merdzenes-pagasts'],
            ['id' => 466628, 'region_id' => 782814, 'country_code' => 'LV', 'name' => 'Salnavas pagasts', 'active' => 1, 'slug' => 'salnavas-pagasts'],
            ['id' => 466629, 'region_id' => 782815, 'country_code' => 'LV', 'name' => 'Lauderu pagasts', 'active' => 1, 'slug' => 'lauderu-pagasts'],
            ['id' => 466630, 'region_id' => 782815, 'country_code' => 'LV', 'name' => 'Pasienes pagasts', 'active' => 1, 'slug' => 'pasienes-pagasts'],
            ['id' => 466631, 'region_id' => 782815, 'country_code' => 'LV', 'name' => 'Zaļesjes pagasts', 'active' => 1, 'slug' => 'zalesjes-pagasts'],
            ['id' => 466632, 'region_id' => 782816, 'country_code' => 'LV', 'name' => 'Blontu pagasts', 'active' => 1, 'slug' => 'blontu-pagasts'],
            ['id' => 466633, 'region_id' => 782816, 'country_code' => 'LV', 'name' => 'Ciblas pagasts', 'active' => 1, 'slug' => 'ciblas-pagasts'],
            ['id' => 466634, 'region_id' => 782816, 'country_code' => 'LV', 'name' => 'Līdumnieku pagasts', 'active' => 1, 'slug' => 'lidumnieku-pagasts'],
            ['id' => 466635, 'region_id' => 782816, 'country_code' => 'LV', 'name' => 'Pušmucovas pagasts', 'active' => 1, 'slug' => 'pusmucovas-pagasts'],
            ['id' => 466636, 'region_id' => 782816, 'country_code' => 'LV', 'name' => 'Zvirgzdenes pagasts', 'active' => 1, 'slug' => 'zvirgzdenes-pagasts'],
            ['id' => 466637, 'region_id' => 782817, 'country_code' => 'LV', 'name' => 'Aronas pagasts', 'active' => 1, 'slug' => 'aronas-pagasts'],
            ['id' => 466638, 'region_id' => 782817, 'country_code' => 'LV', 'name' => 'Barkavas pagasts', 'active' => 1, 'slug' => 'barkavas-pagasts'],
            ['id' => 466639, 'region_id' => 782817, 'country_code' => 'LV', 'name' => 'Bērzaunes pagasts', 'active' => 1, 'slug' => 'berzaunes-pagasts'],
            ['id' => 466640, 'region_id' => 782817, 'country_code' => 'LV', 'name' => 'Dzelzavas pagasts', 'active' => 1, 'slug' => 'dzelzavas-pagasts'],
            ['id' => 466641, 'region_id' => 782817, 'country_code' => 'LV', 'name' => 'Kalsnavas pagasts', 'active' => 1, 'slug' => 'kalsnavas-pagasts'],
            ['id' => 466642, 'region_id' => 782817, 'country_code' => 'LV', 'name' => 'Lazdonas pagasts', 'active' => 1, 'slug' => 'lazdonas-pagasts'],
            ['id' => 466643, 'region_id' => 782817, 'country_code' => 'LV', 'name' => 'Liezēres pagasts', 'active' => 1, 'slug' => 'liezeres-pagasts'],
            ['id' => 466644, 'region_id' => 782817, 'country_code' => 'LV', 'name' => 'Ļaudonas pagasts', 'active' => 1, 'slug' => 'laudonas-pagasts'],
            ['id' => 466645, 'region_id' => 782817, 'country_code' => 'LV', 'name' => 'Mārcienas pagasts', 'active' => 1, 'slug' => 'marcienas-pagasts'],
            ['id' => 466646, 'region_id' => 782817, 'country_code' => 'LV', 'name' => 'Mētrienas pagasts', 'active' => 1, 'slug' => 'metrienas-pagasts'],
            ['id' => 466647, 'region_id' => 782817, 'country_code' => 'LV', 'name' => 'Ošupes pagasts', 'active' => 1, 'slug' => 'osupes-pagasts'],
            ['id' => 466648, 'region_id' => 782817, 'country_code' => 'LV', 'name' => 'Praulienas pagasts', 'active' => 1, 'slug' => 'praulienas-pagasts'],
            ['id' => 466649, 'region_id' => 782817, 'country_code' => 'LV', 'name' => 'Sarkaņu pagasts', 'active' => 1, 'slug' => 'sarkanu-pagasts'],
            ['id' => 466650, 'region_id' => 782817, 'country_code' => 'LV', 'name' => 'Vestienas pagasts', 'active' => 1, 'slug' => 'vestienas-pagasts'],
            ['id' => 466651, 'region_id' => 782819, 'country_code' => 'LV', 'name' => 'Indrānu pagasts', 'active' => 1, 'slug' => 'indranu-pagasts'],
            ['id' => 466652, 'region_id' => 782820, 'country_code' => 'LV', 'name' => 'Murmastienes pagasts', 'active' => 1, 'slug' => 'murmastienes-pagasts'],
            ['id' => 466653, 'region_id' => 782820, 'country_code' => 'LV', 'name' => 'Varakļānu pagasts', 'active' => 1, 'slug' => 'varaklanu-pagasts'],
            ['id' => 466654, 'region_id' => 782821, 'country_code' => 'LV', 'name' => 'Ērgļu pagasts', 'active' => 1, 'slug' => 'erglu-pagasts'],
            ['id' => 466655, 'region_id' => 782821, 'country_code' => 'LV', 'name' => 'Jumurdas pagasts', 'active' => 1, 'slug' => 'jumurdas-pagasts'],
            ['id' => 466656, 'region_id' => 782821, 'country_code' => 'LV', 'name' => 'Sausnējas pagasts', 'active' => 1, 'slug' => 'sausnejas-pagasts'],
            ['id' => 466657, 'region_id' => 782822, 'country_code' => 'LV', 'name' => 'Krapes pagasts', 'active' => 1, 'slug' => 'krapes-pagasts'],
            ['id' => 466658, 'region_id' => 782822, 'country_code' => 'LV', 'name' => 'Ķeipenes pagasts', 'active' => 1, 'slug' => 'keipenes-pagasts'],
            ['id' => 466659, 'region_id' => 782822, 'country_code' => 'LV', 'name' => 'Lauberes pagasts', 'active' => 1, 'slug' => 'lauberes-pagasts'],
            ['id' => 466660, 'region_id' => 782822, 'country_code' => 'LV', 'name' => 'Madlienas pagasts', 'active' => 1, 'slug' => 'madlienas-pagasts'],
            ['id' => 466661, 'region_id' => 782822, 'country_code' => 'LV', 'name' => 'Mazozolu pagasts', 'active' => 1, 'slug' => 'mazozolu-pagasts'],
            ['id' => 466662, 'region_id' => 782822, 'country_code' => 'LV', 'name' => 'Meņģeles pagasts', 'active' => 1, 'slug' => 'mengeles-pagasts'],
            ['id' => 466663, 'region_id' => 782822, 'country_code' => 'LV', 'name' => 'Ogresgala pagasts', 'active' => 1, 'slug' => 'ogresgala-pagasts'],
            ['id' => 466664, 'region_id' => 782822, 'country_code' => 'LV', 'name' => 'Suntažu pagasts', 'active' => 1, 'slug' => 'suntazu-pagasts'],
            ['id' => 466665, 'region_id' => 782822, 'country_code' => 'LV', 'name' => 'Taurupes pagasts', 'active' => 1, 'slug' => 'taurupes-pagasts'],
            ['id' => 466666, 'region_id' => 782824, 'country_code' => 'LV', 'name' => 'Birzgales pagasts', 'active' => 1, 'slug' => 'birzgales-pagasts'],
            ['id' => 466667, 'region_id' => 782824, 'country_code' => 'LV', 'name' => 'Rembates pagasts', 'active' => 1, 'slug' => 'rembates-pagasts'],
            ['id' => 466668, 'region_id' => 782825, 'country_code' => 'LV', 'name' => 'Jumpravas pagasts', 'active' => 1, 'slug' => 'jumpravas-pagasts'],
            ['id' => 466669, 'region_id' => 782825, 'country_code' => 'LV', 'name' => 'Lēdmanes pagasts', 'active' => 1, 'slug' => 'ledmanes-pagasts'],
            ['id' => 466670, 'region_id' => 782826, 'country_code' => 'LV', 'name' => 'Aizkalnes pagasts', 'active' => 1, 'slug' => 'aizkalnes-pagasts'],
            ['id' => 466671, 'region_id' => 782826, 'country_code' => 'LV', 'name' => 'Pelēču pagasts', 'active' => 1, 'slug' => 'pelecu-pagasts'],
            ['id' => 466672, 'region_id' => 782826, 'country_code' => 'LV', 'name' => 'Preiļu pagasts', 'active' => 1, 'slug' => 'preilu-pagasts'],
            ['id' => 466673, 'region_id' => 782826, 'country_code' => 'LV', 'name' => 'Saunas pagasts', 'active' => 1, 'slug' => 'saunas-pagasts'],
            ['id' => 466674, 'region_id' => 782827, 'country_code' => 'LV', 'name' => 'Jersikas pagasts', 'active' => 1, 'slug' => 'jersikas-pagasts'],
            ['id' => 466675, 'region_id' => 782827, 'country_code' => 'LV', 'name' => 'Rožupes pagasts', 'active' => 1, 'slug' => 'rozupes-pagasts'],
            ['id' => 466676, 'region_id' => 782827, 'country_code' => 'LV', 'name' => 'Rudzātu pagasts', 'active' => 1, 'slug' => 'rudzatu-pagasts'],
            ['id' => 466677, 'region_id' => 782827, 'country_code' => 'LV', 'name' => 'Sutru pagasts', 'active' => 1, 'slug' => 'sutru-pagasts'],
            ['id' => 466678, 'region_id' => 782827, 'country_code' => 'LV', 'name' => 'Turku pagasts', 'active' => 1, 'slug' => 'turku-pagasts'],
            ['id' => 466679, 'region_id' => 782828, 'country_code' => 'LV', 'name' => 'Galēnu pagasts', 'active' => 1, 'slug' => 'galenu-pagasts'],
            ['id' => 466680, 'region_id' => 782828, 'country_code' => 'LV', 'name' => 'Riebiņu pagasts', 'active' => 1, 'slug' => 'riebinu-pagasts'],
            ['id' => 466681, 'region_id' => 782828, 'country_code' => 'LV', 'name' => 'Rušonas pagasts', 'active' => 1, 'slug' => 'rusonas-pagasts'],
            ['id' => 466682, 'region_id' => 782828, 'country_code' => 'LV', 'name' => 'Silajāņu pagasts', 'active' => 1, 'slug' => 'silajanu-pagasts'],
            ['id' => 466683, 'region_id' => 782828, 'country_code' => 'LV', 'name' => 'Sīļukalna pagasts', 'active' => 1, 'slug' => 'silukalna-pagasts'],
            ['id' => 466684, 'region_id' => 782828, 'country_code' => 'LV', 'name' => 'Stabulnieku pagasts', 'active' => 1, 'slug' => 'stabulnieku-pagasts'],
            ['id' => 466685, 'region_id' => 782829, 'country_code' => 'LV', 'name' => 'Rožkalnu pagasts', 'active' => 1, 'slug' => 'rozkalnu-pagasts'],
            ['id' => 466686, 'region_id' => 782829, 'country_code' => 'LV', 'name' => 'Upmalas pagasts', 'active' => 1, 'slug' => 'upmalas-pagasts'],
            ['id' => 466687, 'region_id' => 782829, 'country_code' => 'LV', 'name' => 'Vārkavas pagasts', 'active' => 1, 'slug' => 'varkavas-pagasts'],
            ['id' => 466688, 'region_id' => 782830, 'country_code' => 'LV', 'name' => 'Audriņu pagasts', 'active' => 1, 'slug' => 'audrinu-pagasts'],
            ['id' => 466689, 'region_id' => 782830, 'country_code' => 'LV', 'name' => 'Bērzgales pagasts', 'active' => 1, 'slug' => 'berzgales-pagasts'],
            ['id' => 466690, 'region_id' => 782830, 'country_code' => 'LV', 'name' => 'Čornajas pagasts', 'active' => 1, 'slug' => 'cornajas-pagasts'],
            ['id' => 466691, 'region_id' => 782830, 'country_code' => 'LV', 'name' => 'Dricānu pagasts', 'active' => 1, 'slug' => 'dricanu-pagasts'],
            ['id' => 466692, 'region_id' => 782830, 'country_code' => 'LV', 'name' => 'Feimaņu pagasts', 'active' => 1, 'slug' => 'feimanu-pagasts'],
            ['id' => 466693, 'region_id' => 782830, 'country_code' => 'LV', 'name' => 'Gaigalavas pagasts', 'active' => 1, 'slug' => 'gaigalavas-pagasts'],
            ['id' => 466694, 'region_id' => 782830, 'country_code' => 'LV', 'name' => 'Griškānu pagasts', 'active' => 1, 'slug' => 'griskanu-pagasts'],
            ['id' => 466695, 'region_id' => 782830, 'country_code' => 'LV', 'name' => 'Ilzeskalna pagasts', 'active' => 1, 'slug' => 'ilzeskalna-pagasts'],
            ['id' => 466696, 'region_id' => 782830, 'country_code' => 'LV', 'name' => 'Kantinieku pagasts', 'active' => 1, 'slug' => 'kantinieku-pagasts'],
            ['id' => 466697, 'region_id' => 782830, 'country_code' => 'LV', 'name' => 'Kaunatas pagasts', 'active' => 1, 'slug' => 'kaunatas-pagasts'],
            ['id' => 466698, 'region_id' => 782830, 'country_code' => 'LV', 'name' => 'Lendžu pagasts', 'active' => 1, 'slug' => 'lendzu-pagasts'],
            ['id' => 466699, 'region_id' => 782830, 'country_code' => 'LV', 'name' => 'Lūznavas pagasts', 'active' => 1, 'slug' => 'luznavas-pagasts'],
            ['id' => 466700, 'region_id' => 782830, 'country_code' => 'LV', 'name' => 'Maltas pagasts', 'active' => 1, 'slug' => 'maltas-pagasts'],
            ['id' => 466701, 'region_id' => 782830, 'country_code' => 'LV', 'name' => 'Mākoņkalna pagasts', 'active' => 1, 'slug' => 'makonkalna-pagasts'],
            ['id' => 466702, 'region_id' => 782830, 'country_code' => 'LV', 'name' => 'Nagļu pagasts', 'active' => 1, 'slug' => 'naglu-pagasts'],
            ['id' => 466703, 'region_id' => 782830, 'country_code' => 'LV', 'name' => 'Ozolaines pagasts', 'active' => 1, 'slug' => 'ozolaines-pagasts'],
            ['id' => 466704, 'region_id' => 782830, 'country_code' => 'LV', 'name' => 'Ozolmuižas pagasts', 'active' => 1, 'slug' => 'ozolmuizas-pagasts'],
            ['id' => 466705, 'region_id' => 782830, 'country_code' => 'LV', 'name' => 'Pušas pagasts', 'active' => 1, 'slug' => 'pusas-pagasts'],
            ['id' => 466706, 'region_id' => 782830, 'country_code' => 'LV', 'name' => 'Rikavas pagasts', 'active' => 1, 'slug' => 'rikavas-pagasts'],
            ['id' => 466707, 'region_id' => 782830, 'country_code' => 'LV', 'name' => 'Nautrēnu pagasts', 'active' => 1, 'slug' => 'nautrenu-pagasts'],
            ['id' => 466708, 'region_id' => 782830, 'country_code' => 'LV', 'name' => 'Sakstagala pagasts', 'active' => 1, 'slug' => 'sakstagala-pagasts'],
            ['id' => 466709, 'region_id' => 782830, 'country_code' => 'LV', 'name' => 'Silmalas pagasts', 'active' => 1, 'slug' => 'silmalas-pagasts'],
            ['id' => 466710, 'region_id' => 782830, 'country_code' => 'LV', 'name' => 'Stoļerovas pagasts', 'active' => 1, 'slug' => 'stolerovas-pagasts'],
            ['id' => 466711, 'region_id' => 782830, 'country_code' => 'LV', 'name' => 'Stružānu pagasts', 'active' => 1, 'slug' => 'struzanu-pagasts'],
            ['id' => 466712, 'region_id' => 782830, 'country_code' => 'LV', 'name' => 'Vērēmu pagasts', 'active' => 1, 'slug' => 'veremu-pagasts'],
            ['id' => 466713, 'region_id' => 782831, 'country_code' => 'LV', 'name' => 'Dekšāres pagasts', 'active' => 1, 'slug' => 'deksares-pagasts'],
            ['id' => 466714, 'region_id' => 782831, 'country_code' => 'LV', 'name' => 'Sokolku pagasts', 'active' => 1, 'slug' => 'sokolku-pagasts'],
            ['id' => 466715, 'region_id' => 782831, 'country_code' => 'LV', 'name' => 'Viļānu pagasts', 'active' => 1, 'slug' => 'vilanu-pagasts'],
            ['id' => 466716, 'region_id' => 782833, 'country_code' => 'LV', 'name' => 'Daugmales pagasts', 'active' => 1, 'slug' => 'daugmales-pagasts'],
            ['id' => 466717, 'region_id' => 782833, 'country_code' => 'LV', 'name' => 'Ķekavas pagasts', 'active' => 1, 'slug' => 'kekavas-pagasts'],
            ['id' => 466718, 'region_id' => 782834, 'country_code' => 'LV', 'name' => 'Olaines pagasts', 'active' => 1, 'slug' => 'olaines-pagasts'],
            ['id' => 466719, 'region_id' => 782837, 'country_code' => 'LV', 'name' => 'Allažu pagasts', 'active' => 1, 'slug' => 'allazu-pagasts'],
            ['id' => 466720, 'region_id' => 782837, 'country_code' => 'LV', 'name' => 'Mores pagasts', 'active' => 1, 'slug' => 'mores-pagasts'],
            ['id' => 466721, 'region_id' => 782837, 'country_code' => 'LV', 'name' => 'Siguldas pagasts', 'active' => 1, 'slug' => 'siguldas-pagasts'],
            ['id' => 466722, 'region_id' => 782838, 'country_code' => 'LV', 'name' => 'Inčukalna pagasts', 'active' => 1, 'slug' => 'incukalna-pagasts'],
            ['id' => 466723, 'region_id' => 782840, 'country_code' => 'LV', 'name' => 'Babītes pagasts', 'active' => 1, 'slug' => 'babites-pagasts'],
            ['id' => 466724, 'region_id' => 782840, 'country_code' => 'LV', 'name' => 'Salas pagasts', 'active' => 1, 'slug' => 'salas-pagasts'],
            ['id' => 466726, 'region_id' => 782843, 'country_code' => 'LV', 'name' => 'Krimuldas pagasts', 'active' => 1, 'slug' => 'krimuldas-pagasts'],
            ['id' => 466725, 'region_id' => 782843, 'country_code' => 'LV', 'name' => 'Lēdurgas pagasts', 'active' => 1, 'slug' => 'ledurgas-pagasts'],
            ['id' => 466727, 'region_id' => 782849, 'country_code' => 'LV', 'name' => 'Ezeres pagasts', 'active' => 1, 'slug' => 'ezeres-pagasts'],
            ['id' => 466728, 'region_id' => 782849, 'country_code' => 'LV', 'name' => 'Jaunauces pagasts', 'active' => 1, 'slug' => 'jaunauces-pagasts'],
            ['id' => 466729, 'region_id' => 782849, 'country_code' => 'LV', 'name' => 'Jaunlutriņu pagasts', 'active' => 1, 'slug' => 'jaunlutrinu-pagasts'],
            ['id' => 466730, 'region_id' => 782849, 'country_code' => 'LV', 'name' => 'Kursīšu pagasts', 'active' => 1, 'slug' => 'kursisu-pagasts'],
            ['id' => 466731, 'region_id' => 782849, 'country_code' => 'LV', 'name' => 'Lutriņu pagasts', 'active' => 1, 'slug' => 'lutrinu-pagasts'],
            ['id' => 466732, 'region_id' => 782849, 'country_code' => 'LV', 'name' => 'Nīgrandes pagasts', 'active' => 1, 'slug' => 'nigrandes-pagasts'],
            ['id' => 466733, 'region_id' => 782849, 'country_code' => 'LV', 'name' => 'Novadnieku pagasts', 'active' => 1, 'slug' => 'novadnieku-pagasts'],
            ['id' => 466734, 'region_id' => 782849, 'country_code' => 'LV', 'name' => 'Pampāļu pagasts', 'active' => 1, 'slug' => 'pampalu-pagasts'],
            ['id' => 466735, 'region_id' => 782849, 'country_code' => 'LV', 'name' => 'Rubas pagasts', 'active' => 1, 'slug' => 'rubas-pagasts'],
            ['id' => 466736, 'region_id' => 782849, 'country_code' => 'LV', 'name' => 'Saldus pagasts', 'active' => 1, 'slug' => 'saldus-pagasts'],
            ['id' => 466737, 'region_id' => 782849, 'country_code' => 'LV', 'name' => 'Šķēdes pagasts', 'active' => 1, 'slug' => 'skedes-pagasts'],
            ['id' => 466738, 'region_id' => 782849, 'country_code' => 'LV', 'name' => 'Vadakstes pagasts', 'active' => 1, 'slug' => 'vadakstes-pagasts'],
            ['id' => 466739, 'region_id' => 782849, 'country_code' => 'LV', 'name' => 'Zaņas pagasts', 'active' => 1, 'slug' => 'zanas-pagasts'],
            ['id' => 466740, 'region_id' => 782849, 'country_code' => 'LV', 'name' => 'Zirņu pagasts', 'active' => 1, 'slug' => 'zirnu-pagasts'],
            ['id' => 466741, 'region_id' => 782849, 'country_code' => 'LV', 'name' => 'Zvārdes pagasts', 'active' => 1, 'slug' => 'zvardes-pagasts'],
            ['id' => 466742, 'region_id' => 782850, 'country_code' => 'LV', 'name' => 'Blīdenes pagasts', 'active' => 1, 'slug' => 'blidenes-pagasts'],
            ['id' => 466743, 'region_id' => 782850, 'country_code' => 'LV', 'name' => 'Gaiķu pagasts', 'active' => 1, 'slug' => 'gaiku-pagasts'],
            ['id' => 466744, 'region_id' => 782850, 'country_code' => 'LV', 'name' => 'Remtes pagasts', 'active' => 1, 'slug' => 'remtes-pagasts'],
            ['id' => 466745, 'region_id' => 782851, 'country_code' => 'LV', 'name' => 'Abavas pagasts', 'active' => 1, 'slug' => 'abavas-pagasts'],
            ['id' => 466746, 'region_id' => 782851, 'country_code' => 'LV', 'name' => 'Balgales pagasts', 'active' => 1, 'slug' => 'balgales-pagasts'],
            ['id' => 466747, 'region_id' => 782851, 'country_code' => 'LV', 'name' => 'Ģibuļu pagasts', 'active' => 1, 'slug' => 'gibulu-pagasts'],
            ['id' => 466748, 'region_id' => 782851, 'country_code' => 'LV', 'name' => 'Īves pagasts', 'active' => 1, 'slug' => 'ives-pagasts'],
            ['id' => 466749, 'region_id' => 782851, 'country_code' => 'LV', 'name' => 'Ķūļciema pagasts', 'active' => 1, 'slug' => 'kulciema-pagasts'],
            ['id' => 466750, 'region_id' => 782851, 'country_code' => 'LV', 'name' => 'Laidzes pagasts', 'active' => 1, 'slug' => 'laidzes-pagasts'],
            ['id' => 466751, 'region_id' => 782851, 'country_code' => 'LV', 'name' => 'Laucienes pagasts', 'active' => 1, 'slug' => 'laucienes-pagasts'],
            ['id' => 466752, 'region_id' => 782851, 'country_code' => 'LV', 'name' => 'Lībagu pagasts', 'active' => 1, 'slug' => 'libagu-pagasts'],
            ['id' => 466753, 'region_id' => 782851, 'country_code' => 'LV', 'name' => 'Lubes pagasts', 'active' => 1, 'slug' => 'lubes-pagasts'],
            ['id' => 466754, 'region_id' => 782851, 'country_code' => 'LV', 'name' => 'Strazdes pagasts', 'active' => 1, 'slug' => 'strazdes-pagasts'],
            ['id' => 466755, 'region_id' => 782851, 'country_code' => 'LV', 'name' => 'Valdgales pagasts', 'active' => 1, 'slug' => 'valdgales-pagasts'],
            ['id' => 466756, 'region_id' => 782851, 'country_code' => 'LV', 'name' => 'Vandzenes pagasts', 'active' => 1, 'slug' => 'vandzenes-pagasts'],
            ['id' => 466757, 'region_id' => 782851, 'country_code' => 'LV', 'name' => 'Virbu pagasts', 'active' => 1, 'slug' => 'virbu-pagasts'],
            ['id' => 466758, 'region_id' => 782852, 'country_code' => 'LV', 'name' => 'Dundagas pagasts', 'active' => 1, 'slug' => 'dundagas-pagasts'],
            ['id' => 466759, 'region_id' => 782852, 'country_code' => 'LV', 'name' => 'Kolkas pagasts', 'active' => 1, 'slug' => 'kolkas-pagasts'],
            ['id' => 466760, 'region_id' => 782854, 'country_code' => 'LV', 'name' => 'Rojas pagasts', 'active' => 1, 'slug' => 'rojas-pagasts'],
            ['id' => 466761, 'region_id' => 782855, 'country_code' => 'LV', 'name' => 'Degoles pagasts', 'active' => 1, 'slug' => 'degoles-pagasts'],
            ['id' => 466762, 'region_id' => 782855, 'country_code' => 'LV', 'name' => 'Džūkstes pagasts', 'active' => 1, 'slug' => 'dzukstes-pagasts'],
            ['id' => 466763, 'region_id' => 782855, 'country_code' => 'LV', 'name' => 'Irlavas pagasts', 'active' => 1, 'slug' => 'irlavas-pagasts'],
            ['id' => 466764, 'region_id' => 782855, 'country_code' => 'LV', 'name' => 'Jaunsātu pagasts', 'active' => 1, 'slug' => 'jaunsatu-pagasts'],
            ['id' => 466765, 'region_id' => 782855, 'country_code' => 'LV', 'name' => 'Lestenes pagasts', 'active' => 1, 'slug' => 'lestenes-pagasts'],
            ['id' => 466766, 'region_id' => 782855, 'country_code' => 'LV', 'name' => 'Pūres pagasts', 'active' => 1, 'slug' => 'pures-pagasts'],
            ['id' => 466767, 'region_id' => 782855, 'country_code' => 'LV', 'name' => 'Sēmes pagasts', 'active' => 1, 'slug' => 'semes-pagasts'],
            ['id' => 466768, 'region_id' => 782855, 'country_code' => 'LV', 'name' => 'Slampes pagasts', 'active' => 1, 'slug' => 'slampes-pagasts'],
            ['id' => 466769, 'region_id' => 782855, 'country_code' => 'LV', 'name' => 'Tumes pagasts', 'active' => 1, 'slug' => 'tumes-pagasts'],
            ['id' => 466770, 'region_id' => 782855, 'country_code' => 'LV', 'name' => 'Zentenes pagasts', 'active' => 1, 'slug' => 'zentenes-pagasts'],
            ['id' => 466771, 'region_id' => 782856, 'country_code' => 'LV', 'name' => 'Cēres pagasts', 'active' => 1, 'slug' => 'ceres-pagasts'],
            ['id' => 466772, 'region_id' => 782856, 'country_code' => 'LV', 'name' => 'Kandavas pagasts', 'active' => 1, 'slug' => 'kandavas-pagasts'],
            ['id' => 466773, 'region_id' => 782856, 'country_code' => 'LV', 'name' => 'Matkules pagasts', 'active' => 1, 'slug' => 'matkules-pagasts'],
            ['id' => 466774, 'region_id' => 782856, 'country_code' => 'LV', 'name' => 'Vānes pagasts', 'active' => 1, 'slug' => 'vanes-pagasts'],
            ['id' => 466775, 'region_id' => 782856, 'country_code' => 'LV', 'name' => 'Zantes pagasts', 'active' => 1, 'slug' => 'zantes-pagasts'],
            ['id' => 466776, 'region_id' => 782856, 'country_code' => 'LV', 'name' => 'Zemītes pagasts', 'active' => 1, 'slug' => 'zemites-pagasts'],
            ['id' => 466777, 'region_id' => 782857, 'country_code' => 'LV', 'name' => 'Engures pagasts', 'active' => 1, 'slug' => 'engures-pagasts'],
            ['id' => 466778, 'region_id' => 782857, 'country_code' => 'LV', 'name' => 'Lapmežciema pagasts', 'active' => 1, 'slug' => 'lapmezciema-pagasts'],
            ['id' => 466779, 'region_id' => 782857, 'country_code' => 'LV', 'name' => 'Smārdes pagasts', 'active' => 1, 'slug' => 'smardes-pagasts'],
            ['id' => 466780, 'region_id' => 782858, 'country_code' => 'LV', 'name' => 'Jaunpils pagasts', 'active' => 1, 'slug' => 'jaunpils-pagasts'],
            ['id' => 466781, 'region_id' => 782858, 'country_code' => 'LV', 'name' => 'Viesatu pagasts', 'active' => 1, 'slug' => 'viesatu-pagasts'],
            ['id' => 466782, 'region_id' => 782859, 'country_code' => 'LV', 'name' => 'Ērģemes pagasts', 'active' => 1, 'slug' => 'ergemes-pagasts'],
            ['id' => 466783, 'region_id' => 782859, 'country_code' => 'LV', 'name' => 'Kārķu pagasts', 'active' => 1, 'slug' => 'karku-pagasts'],
            ['id' => 466784, 'region_id' => 782859, 'country_code' => 'LV', 'name' => 'Valkas pagasts', 'active' => 1, 'slug' => 'valkas-pagasts'],
            ['id' => 466785, 'region_id' => 782859, 'country_code' => 'LV', 'name' => 'Vijciema pagasts', 'active' => 1, 'slug' => 'vijciema-pagasts'],
            ['id' => 466786, 'region_id' => 782859, 'country_code' => 'LV', 'name' => 'Zvārtavas pagasts', 'active' => 1, 'slug' => 'zvartavas-pagasts'],
            ['id' => 466787, 'region_id' => 782860, 'country_code' => 'LV', 'name' => 'Bilskas pagasts', 'active' => 1, 'slug' => 'bilskas-pagasts'],
            ['id' => 466788, 'region_id' => 782860, 'country_code' => 'LV', 'name' => 'Blomes pagasts', 'active' => 1, 'slug' => 'blomes-pagasts'],
            ['id' => 466789, 'region_id' => 782860, 'country_code' => 'LV', 'name' => 'Brantu pagasts', 'active' => 1, 'slug' => 'brantu-pagasts'],
            ['id' => 466790, 'region_id' => 782860, 'country_code' => 'LV', 'name' => 'Grundzāles pagasts', 'active' => 1, 'slug' => 'grundzales-pagasts'],
            ['id' => 466791, 'region_id' => 782860, 'country_code' => 'LV', 'name' => 'Launkalnes pagasts', 'active' => 1, 'slug' => 'launkalnes-pagasts'],
            ['id' => 466792, 'region_id' => 782860, 'country_code' => 'LV', 'name' => 'Palsmanes pagasts', 'active' => 1, 'slug' => 'palsmanes-pagasts'],
            ['id' => 466793, 'region_id' => 782860, 'country_code' => 'LV', 'name' => 'Smiltenes pagasts', 'active' => 1, 'slug' => 'smiltenes-pagasts'],
            ['id' => 466794, 'region_id' => 782860, 'country_code' => 'LV', 'name' => 'Variņu pagasts', 'active' => 1, 'slug' => 'varinu-pagasts'],
            ['id' => 466795, 'region_id' => 782861, 'country_code' => 'LV', 'name' => 'Jērcēnu pagasts', 'active' => 1, 'slug' => 'jercenu-pagasts'],
            ['id' => 466796, 'region_id' => 782861, 'country_code' => 'LV', 'name' => 'Plāņu pagasts', 'active' => 1, 'slug' => 'planu-pagasts'],
            ['id' => 466797, 'region_id' => 782862, 'country_code' => 'LV', 'name' => 'Bērzaines pagasts', 'active' => 1, 'slug' => 'berzaines-pagasts'],
            ['id' => 466798, 'region_id' => 782862, 'country_code' => 'LV', 'name' => 'Dikļu pagasts', 'active' => 1, 'slug' => 'diklu-pagasts'],
            ['id' => 466799, 'region_id' => 782862, 'country_code' => 'LV', 'name' => 'Kocēnu pagasts', 'active' => 1, 'slug' => 'kocenu-pagasts'],
            ['id' => 466800, 'region_id' => 782862, 'country_code' => 'LV', 'name' => 'Vaidavas pagasts', 'active' => 1, 'slug' => 'vaidavas-pagasts'],
            ['id' => 466801, 'region_id' => 782862, 'country_code' => 'LV', 'name' => 'Zilākalna pagasts', 'active' => 1, 'slug' => 'zilakalna-pagasts'],
            ['id' => 466802, 'region_id' => 782863, 'country_code' => 'LV', 'name' => 'Ramatas pagasts', 'active' => 1, 'slug' => 'ramatas-pagasts'],
            ['id' => 466803, 'region_id' => 782863, 'country_code' => 'LV', 'name' => 'Sēļu pagasts', 'active' => 1, 'slug' => 'selu-pagasts'],
            ['id' => 466804, 'region_id' => 782863, 'country_code' => 'LV', 'name' => 'Skaņkalnes pagasts', 'active' => 1, 'slug' => 'skankalnes-pagasts'],
            ['id' => 466805, 'region_id' => 782864, 'country_code' => 'LV', 'name' => 'Ipiķu pagasts', 'active' => 1, 'slug' => 'ipiku-pagasts'],
            ['id' => 466806, 'region_id' => 782864, 'country_code' => 'LV', 'name' => 'Jeru pagasts', 'active' => 1, 'slug' => 'jeru-pagasts'],
            ['id' => 466807, 'region_id' => 782864, 'country_code' => 'LV', 'name' => 'Lodes pagasts', 'active' => 1, 'slug' => 'lodes-pagasts'],
            ['id' => 466808, 'region_id' => 782864, 'country_code' => 'LV', 'name' => 'Vilpulkas pagasts', 'active' => 1, 'slug' => 'vilpulkas-pagasts'],
            ['id' => 466809, 'region_id' => 782865, 'country_code' => 'LV', 'name' => 'Brenguļu pagasts', 'active' => 1, 'slug' => 'brengulu-pagasts'],
            ['id' => 466810, 'region_id' => 782865, 'country_code' => 'LV', 'name' => 'Kauguru pagasts', 'active' => 1, 'slug' => 'kauguru-pagasts'],
            ['id' => 466811, 'region_id' => 782865, 'country_code' => 'LV', 'name' => 'Trikātas pagasts', 'active' => 1, 'slug' => 'trikatas-pagasts'],
            ['id' => 466812, 'region_id' => 782866, 'country_code' => 'LV', 'name' => 'Burtnieku pagasts', 'active' => 1, 'slug' => 'burtnieku-pagasts'],
            ['id' => 466813, 'region_id' => 782866, 'country_code' => 'LV', 'name' => 'Ēveles pagasts', 'active' => 1, 'slug' => 'eveles-pagasts'],
            ['id' => 466814, 'region_id' => 782866, 'country_code' => 'LV', 'name' => 'Matīšu pagasts', 'active' => 1, 'slug' => 'matisu-pagasts'],
            ['id' => 466815, 'region_id' => 782866, 'country_code' => 'LV', 'name' => 'Rencēnu pagasts', 'active' => 1, 'slug' => 'rencenu-pagasts'],
            ['id' => 466816, 'region_id' => 782866, 'country_code' => 'LV', 'name' => 'Valmieras pagasts', 'active' => 1, 'slug' => 'valmieras-pagasts'],
            ['id' => 466817, 'region_id' => 782866, 'country_code' => 'LV', 'name' => 'Vecates pagasts', 'active' => 1, 'slug' => 'vecates-pagasts'],
            ['id' => 466818, 'region_id' => 782867, 'country_code' => 'LV', 'name' => 'Ķoņu pagasts', 'active' => 1, 'slug' => 'konu-pagasts'],
            ['id' => 466819, 'region_id' => 782867, 'country_code' => 'LV', 'name' => 'Naukšēnu pagasts', 'active' => 1, 'slug' => 'nauksenu-pagasts'],
            ['id' => 466820, 'region_id' => 782868, 'country_code' => 'LV', 'name' => 'Ances pagasts', 'active' => 1, 'slug' => 'ances-pagasts'],
            ['id' => 466821, 'region_id' => 782868, 'country_code' => 'LV', 'name' => 'Jūrkalnes pagasts', 'active' => 1, 'slug' => 'jurkalnes-pagasts'],
            ['id' => 466822, 'region_id' => 782868, 'country_code' => 'LV', 'name' => 'Popes pagasts', 'active' => 1, 'slug' => 'popes-pagasts'],
            ['id' => 466823, 'region_id' => 782868, 'country_code' => 'LV', 'name' => 'Puzes pagasts', 'active' => 1, 'slug' => 'puzes-pagasts'],
            ['id' => 466824, 'region_id' => 782868, 'country_code' => 'LV', 'name' => 'Tārgales pagasts', 'active' => 1, 'slug' => 'targales-pagasts'],
            ['id' => 466825, 'region_id' => 782868, 'country_code' => 'LV', 'name' => 'Ugāles pagasts', 'active' => 1, 'slug' => 'ugales-pagasts'],
            ['id' => 466826, 'region_id' => 782868, 'country_code' => 'LV', 'name' => 'Usmas pagasts', 'active' => 1, 'slug' => 'usmas-pagasts'],
            ['id' => 466827, 'region_id' => 782868, 'country_code' => 'LV', 'name' => 'Užavas pagasts', 'active' => 1, 'slug' => 'uzavas-pagasts'],
            ['id' => 466828, 'region_id' => 782868, 'country_code' => 'LV', 'name' => 'Vārves pagasts', 'active' => 1, 'slug' => 'varves-pagasts'],
            ['id' => 466829, 'region_id' => 782868, 'country_code' => 'LV', 'name' => 'Ziru pagasts', 'active' => 1, 'slug' => 'ziru-pagasts'],
            ['id' => 466830, 'region_id' => 782868, 'country_code' => 'LV', 'name' => 'Zlēku pagasts', 'active' => 1, 'slug' => 'zleku-pagasts']
    	];
    }
}
