<?php

namespace Gerardojbaez\GeoData\Seeders;

use Illuminate\Database\Seeder;
use Gerardojbaez\GeoData\Models\Country;
use Gerardojbaez\GeoData\Models\Region;
use Gerardojbaez\GeoData\Models\City;

class LebanonSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Country::create($this->country());
        Region::insert($this->regions());

        if ($this->cities() > 4000)
        {
            foreach (array_chunk($this->cities(), 3500) as $chunk)
                City::insert($chunk);
        }
        else
        {
            City::insert($this->cities());
        }
    }

        /**
     * Get country.
     *
     * @return array
     */
    public function country()
    {
    	return ['code' => 'LB', 'name' => 'Lebanon', 'slug' => 'lebanon'];
    }

    /**
     * Get country regions.
     *
     * @return array
     */
    public function regions()
    {
    	return [
            ['id' => 783324, 'country_code' => 'LB', 'name' => 'Greater Beirut', 'active' => 1, 'slug' => 'greater-beirut'],
            ['id' => 783325, 'country_code' => 'LB', 'name' => 'Beqaa', 'active' => 1, 'slug' => 'beqaa'],
            ['id' => 783326, 'country_code' => 'LB', 'name' => 'Zahle', 'active' => 1, 'slug' => 'zahle'],
            ['id' => 783327, 'country_code' => 'LB', 'name' => 'North Lebanon', 'active' => 1, 'slug' => 'north-lebanon'],
            ['id' => 783328, 'country_code' => 'LB', 'name' => 'South Lebanon', 'active' => 1, 'slug' => 'south-lebanon'],
            ['id' => 783329, 'country_code' => 'LB', 'name' => 'Nabatieh', 'active' => 1, 'slug' => 'nabatieh'],
            ['id' => 783330, 'country_code' => 'LB', 'name' => 'Chouf', 'active' => 1, 'slug' => 'chouf'],
            ['id' => 783331, 'country_code' => 'LB', 'name' => 'Mount Liban', 'active' => 1, 'slug' => 'mount-liban']
    	];
    }

    /**
     * Get region cities.
     *
     * @return array
     */
    public function cities()
    {
    	return [
            ['id' => 511820, 'region_id' => 783324, 'country_code' => 'LB', 'name' => 'Achrafieh', 'active' => 1, 'slug' => 'achrafieh'],
            ['id' => 511821, 'region_id' => 783324, 'country_code' => 'LB', 'name' => 'Beirut', 'active' => 1, 'slug' => 'beirut'],
            ['id' => 511822, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Baalbek', 'active' => 1, 'slug' => 'baalbek'],
            ['id' => 511823, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Ain', 'active' => 1, 'slug' => 'ain'],
            ['id' => 511824, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Ainata', 'active' => 1, 'slug' => 'ainata'],
            ['id' => 511825, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Barka', 'active' => 1, 'slug' => 'barka'],
            ['id' => 511826, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Bednayel', 'active' => 1, 'slug' => 'bednayel'],
            ['id' => 511827, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Bechwat', 'active' => 1, 'slug' => 'bechwat'],
            ['id' => 511828, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Brital', 'active' => 1, 'slug' => 'brital'],
            ['id' => 511829, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Btadhi', 'active' => 1, 'slug' => 'btadhi'],
            ['id' => 511830, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Buday', 'active' => 1, 'slug' => 'buday'],
            ['id' => 511831, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Chaat', 'active' => 1, 'slug' => 'chaat'],
            ['id' => 511832, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Chlifa', 'active' => 1, 'slug' => 'chlifa'],
            ['id' => 511833, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Chmestar - Gharbi Baalbeck', 'active' => 1, 'slug' => 'chmestar-gharbi-baalbeck'],
            ['id' => 511834, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Deir el Ahmar', 'active' => 1, 'slug' => 'deir-el-ahmar'],
            ['id' => 511835, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Douriss', 'active' => 1, 'slug' => 'douriss'],
            ['id' => 511836, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Ersal', 'active' => 1, 'slug' => 'ersal'],
            ['id' => 511837, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Fakiha - Jdeydeh', 'active' => 1, 'slug' => 'fakiha-jdeydeh'],
            ['id' => 511838, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Fleweh', 'active' => 1, 'slug' => 'fleweh'],
            ['id' => 511839, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Hadath Baalbek', 'active' => 1, 'slug' => 'hadath-baalbek'],
            ['id' => 511840, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Halbata', 'active' => 1, 'slug' => 'halbata'],
            ['id' => 511841, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Hazin', 'active' => 1, 'slug' => 'hazin'],
            ['id' => 511842, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Hosh Barada', 'active' => 1, 'slug' => 'hosh-barada'],
            ['id' => 511843, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Hosh el Rafika', 'active' => 1, 'slug' => 'hosh-el-rafika'],
            ['id' => 511844, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Hosh Snid', 'active' => 1, 'slug' => 'hosh-snid'],
            ['id' => 511845, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Hosh Tal Safiya', 'active' => 1, 'slug' => 'hosh-tal-safiya'],
            ['id' => 511846, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Hrebta', 'active' => 1, 'slug' => 'hrebta'],
            ['id' => 511847, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Jabbouleh', 'active' => 1, 'slug' => 'jabbouleh'],
            ['id' => 511848, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Janta', 'active' => 1, 'slug' => 'janta'],
            ['id' => 511849, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Kah', 'active' => 1, 'slug' => 'kah'],
            ['id' => 511850, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Karha', 'active' => 1, 'slug' => 'karha'],
            ['id' => 511851, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Khodr', 'active' => 1, 'slug' => 'khodr'],
            ['id' => 511852, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Khraibeh', 'active' => 1, 'slug' => 'khraibeh'],
            ['id' => 511853, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Kasarnaba', 'active' => 1, 'slug' => 'kasarnaba'],
            ['id' => 511854, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Laat', 'active' => 1, 'slug' => 'laat'],
            ['id' => 511855, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Labweh', 'active' => 1, 'slug' => 'labweh'],
            ['id' => 511856, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Majdloun', 'active' => 1, 'slug' => 'majdloun'],
            ['id' => 511857, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Mikna', 'active' => 1, 'slug' => 'mikna'],
            ['id' => 511858, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Nabi Chit', 'active' => 1, 'slug' => 'nabi-chit'],
            ['id' => 511859, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Nabi Othman', 'active' => 1, 'slug' => 'nabi-othman'],
            ['id' => 511860, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Ram - Jbenniyeh', 'active' => 1, 'slug' => 'ram-jbenniyeh'],
            ['id' => 511861, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Ras Baalbek', 'active' => 1, 'slug' => 'ras-baalbek'],
            ['id' => 511862, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Ras el Hadis', 'active' => 1, 'slug' => 'ras-el-hadis'],
            ['id' => 511863, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Saayde', 'active' => 1, 'slug' => 'saayde'],
            ['id' => 511864, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Seriine el Fawka', 'active' => 1, 'slug' => 'seriine-el-fawka'],
            ['id' => 511865, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Seriine el Tahta', 'active' => 1, 'slug' => 'seriine-el-tahta'],
            ['id' => 511866, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Talya', 'active' => 1, 'slug' => 'talya'],
            ['id' => 511867, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Taraya', 'active' => 1, 'slug' => 'taraya'],
            ['id' => 511868, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Tayba', 'active' => 1, 'slug' => 'tayba'],
            ['id' => 511869, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Temnin el Fawka', 'active' => 1, 'slug' => 'temnin-el-fawka'],
            ['id' => 511870, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Temnin el Tahta', 'active' => 1, 'slug' => 'temnin-el-tahta'],
            ['id' => 511871, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Wadi Faara', 'active' => 1, 'slug' => 'wadi-faara'],
            ['id' => 511872, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Yammouneh', 'active' => 1, 'slug' => 'yammouneh'],
            ['id' => 511873, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Younine', 'active' => 1, 'slug' => 'younine'],
            ['id' => 511874, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Chawaghir el Fawka', 'active' => 1, 'slug' => 'chawaghir-el-fawka'],
            ['id' => 511875, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Chawaghir el Tahta', 'active' => 1, 'slug' => 'chawaghir-el-tahta'],
            ['id' => 511876, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Hermel', 'active' => 1, 'slug' => 'hermel'],
            ['id' => 511877, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Jouar el Hachich', 'active' => 1, 'slug' => 'jouar-el-hachich'],
            ['id' => 511878, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Kasser - Fisane', 'active' => 1, 'slug' => 'kasser-fisane'],
            ['id' => 511879, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Kouakh', 'active' => 1, 'slug' => 'kouakh'],
            ['id' => 511880, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Ain Arab', 'active' => 1, 'slug' => 'ain-arab'],
            ['id' => 511881, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Ain Ata', 'active' => 1, 'slug' => 'ain-ata'],
            ['id' => 511882, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Ain Harcha', 'active' => 1, 'slug' => 'ain-harcha'],
            ['id' => 511883, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Akabeh', 'active' => 1, 'slug' => 'akabeh'],
            ['id' => 511884, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Ayha', 'active' => 1, 'slug' => 'ayha'],
            ['id' => 511885, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Ayta el Fekhar', 'active' => 1, 'slug' => 'ayta-el-fekhar'],
            ['id' => 511886, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Bakifa', 'active' => 1, 'slug' => 'bakifa'],
            ['id' => 511887, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Bakka', 'active' => 1, 'slug' => 'bakka'],
            ['id' => 511888, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Beit Lahia', 'active' => 1, 'slug' => 'beit-lahia'],
            ['id' => 511889, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Bireh', 'active' => 1, 'slug' => 'bireh'],
            ['id' => 511890, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Daher el Ahmar', 'active' => 1, 'slug' => 'daher-el-ahmar'],
            ['id' => 511891, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Deir El Aachayer', 'active' => 1, 'slug' => 'deir-el-aachayer'],
            ['id' => 511892, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Helwa', 'active' => 1, 'slug' => 'helwa'],
            ['id' => 511893, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Hoch', 'active' => 1, 'slug' => 'hoch'],
            ['id' => 511894, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Kaukaba', 'active' => 1, 'slug' => 'kaukaba'],
            ['id' => 511895, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Kfardaniss', 'active' => 1, 'slug' => 'kfardaniss'],
            ['id' => 511896, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Kfarfouk', 'active' => 1, 'slug' => 'kfarfouk'],
            ['id' => 511897, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Kfarmechki', 'active' => 1, 'slug' => 'kfarmechki'],
            ['id' => 511898, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Kherbet Rouha', 'active' => 1, 'slug' => 'kherbet-rouha'],
            ['id' => 511899, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Majdel Balhiss', 'active' => 1, 'slug' => 'majdel-balhiss'],
            ['id' => 511900, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Mdoukha', 'active' => 1, 'slug' => 'mdoukha'],
            ['id' => 511901, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Mhaydseh', 'active' => 1, 'slug' => 'mhaydseh'],
            ['id' => 511902, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Rashaya', 'active' => 1, 'slug' => 'rashaya'],
            ['id' => 511903, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Al-Rafid', 'active' => 1, 'slug' => 'al-rafid'],
            ['id' => 511904, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Tannoura', 'active' => 1, 'slug' => 'tannoura'],
            ['id' => 511905, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Yanta', 'active' => 1, 'slug' => 'yanta'],
            ['id' => 511906, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Ain el Tineh', 'active' => 1, 'slug' => 'ain-el-tineh'],
            ['id' => 511907, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Ain Zebdeh', 'active' => 1, 'slug' => 'ain-zebdeh'],
            ['id' => 511908, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Ammik', 'active' => 1, 'slug' => 'ammik'],
            ['id' => 511909, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Ana', 'active' => 1, 'slug' => 'ana'],
            ['id' => 511910, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Aitanite', 'active' => 1, 'slug' => 'aitanite'],
            ['id' => 511911, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Baaloul', 'active' => 1, 'slug' => 'baaloul'],
            ['id' => 511912, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Bab Mareh', 'active' => 1, 'slug' => 'bab-mareh'],
            ['id' => 511913, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Ghaza', 'active' => 1, 'slug' => 'ghaza'],
            ['id' => 511914, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Hoch Harimeh', 'active' => 1, 'slug' => 'hoch-harimeh'],
            ['id' => 511915, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Jeb Jennine', 'active' => 1, 'slug' => 'jeb-jennine'],
            ['id' => 511916, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Kamed el Laouz', 'active' => 1, 'slug' => 'kamed-el-laouz'],
            ['id' => 511917, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Karaoun', 'active' => 1, 'slug' => 'karaoun'],
            ['id' => 511918, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Kefraya', 'active' => 1, 'slug' => 'kefraya'],
            ['id' => 511919, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Kelya', 'active' => 1, 'slug' => 'kelya'],
            ['id' => 511920, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Kherbet Kanafar', 'active' => 1, 'slug' => 'kherbet-kanafar'],
            ['id' => 511921, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Lala', 'active' => 1, 'slug' => 'lala'],
            ['id' => 511922, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Lebbaya', 'active' => 1, 'slug' => 'lebbaya'],
            ['id' => 511923, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Machghara', 'active' => 1, 'slug' => 'machghara'],
            ['id' => 511924, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Manara', 'active' => 1, 'slug' => 'manara'],
            ['id' => 511925, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Mansoura', 'active' => 1, 'slug' => 'mansoura'],
            ['id' => 511926, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Marej', 'active' => 1, 'slug' => 'marej'],
            ['id' => 511927, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Maydoun', 'active' => 1, 'slug' => 'maydoun'],
            ['id' => 511928, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Saghbine', 'active' => 1, 'slug' => 'saghbine'],
            ['id' => 511929, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Sohmor', 'active' => 1, 'slug' => 'sohmor'],
            ['id' => 511930, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Sawiri', 'active' => 1, 'slug' => 'sawiri'],
            ['id' => 511931, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Sultan Yaakoub', 'active' => 1, 'slug' => 'sultan-yaakoub'],
            ['id' => 511932, 'region_id' => 783325, 'country_code' => 'LB', 'name' => 'Yehmor', 'active' => 1, 'slug' => 'yehmor'],
            ['id' => 511933, 'region_id' => 783326, 'country_code' => 'LB', 'name' => 'Ablah', 'active' => 1, 'slug' => 'ablah'],
            ['id' => 511934, 'region_id' => 783326, 'country_code' => 'LB', 'name' => 'Ain Kfarzabad', 'active' => 1, 'slug' => 'ain-kfarzabad'],
            ['id' => 511935, 'region_id' => 783326, 'country_code' => 'LB', 'name' => 'Ali el Nahri', 'active' => 1, 'slug' => 'ali-el-nahri'],
            ['id' => 511936, 'region_id' => 783326, 'country_code' => 'LB', 'name' => 'BarElias', 'active' => 1, 'slug' => 'barelias'],
            ['id' => 511937, 'region_id' => 783326, 'country_code' => 'LB', 'name' => 'Bouarej', 'active' => 1, 'slug' => 'bouarej'],
            ['id' => 511938, 'region_id' => 783326, 'country_code' => 'LB', 'name' => 'Chtaura', 'active' => 1, 'slug' => 'chtaura'],
            ['id' => 511939, 'region_id' => 783326, 'country_code' => 'LB', 'name' => 'Deir el Ghazal', 'active' => 1, 'slug' => 'deir-el-ghazal'],
            ['id' => 511940, 'region_id' => 783326, 'country_code' => 'LB', 'name' => 'Ferzol', 'active' => 1, 'slug' => 'ferzol'],
            ['id' => 511941, 'region_id' => 783326, 'country_code' => 'LB', 'name' => 'Hay el Fikany', 'active' => 1, 'slug' => 'hay-el-fikany'],
            ['id' => 511942, 'region_id' => 783326, 'country_code' => 'LB', 'name' => 'Hezerta', 'active' => 1, 'slug' => 'hezerta'],
            ['id' => 511943, 'region_id' => 783326, 'country_code' => 'LB', 'name' => 'Hoch Moussa - Anjar', 'active' => 1, 'slug' => 'hoch-moussa-anjar'],
            ['id' => 511944, 'region_id' => 783326, 'country_code' => 'LB', 'name' => 'Jdita', 'active' => 1, 'slug' => 'jdita'],
            ['id' => 511945, 'region_id' => 783326, 'country_code' => 'LB', 'name' => 'Kaah el Rim', 'active' => 1, 'slug' => 'kaah-el-rim'],
            ['id' => 511946, 'region_id' => 783326, 'country_code' => 'LB', 'name' => 'Kab Elias - Wadi el Deloum', 'active' => 1, 'slug' => 'kab-elias-wadi-el-deloum'],
            ['id' => 511947, 'region_id' => 783326, 'country_code' => 'LB', 'name' => 'Kfarzabad', 'active' => 1, 'slug' => 'kfarzabad'],
            ['id' => 511948, 'region_id' => 783326, 'country_code' => 'LB', 'name' => 'Kousaya', 'active' => 1, 'slug' => 'kousaya'],
            ['id' => 511949, 'region_id' => 783326, 'country_code' => 'LB', 'name' => 'Majdel Anjar', 'active' => 1, 'slug' => 'majdel-anjar'],
            ['id' => 511950, 'region_id' => 783326, 'country_code' => 'LB', 'name' => 'Massa', 'active' => 1, 'slug' => 'massa'],
            ['id' => 511951, 'region_id' => 783326, 'country_code' => 'LB', 'name' => 'Mekssi', 'active' => 1, 'slug' => 'mekssi'],
            ['id' => 511952, 'region_id' => 783326, 'country_code' => 'LB', 'name' => 'Mrayjat', 'active' => 1, 'slug' => 'mrayjat'],
            ['id' => 511953, 'region_id' => 783326, 'country_code' => 'LB', 'name' => 'Nabi Ayla', 'active' => 1, 'slug' => 'nabi-ayla'],
            ['id' => 511954, 'region_id' => 783326, 'country_code' => 'LB', 'name' => 'Niha', 'active' => 1, 'slug' => 'niha'],
            ['id' => 511955, 'region_id' => 783326, 'country_code' => 'LB', 'name' => 'Rhit', 'active' => 1, 'slug' => 'rhit'],
            ['id' => 511956, 'region_id' => 783326, 'country_code' => 'LB', 'name' => 'Riyak - Hoch Hala', 'active' => 1, 'slug' => 'riyak-hoch-hala'],
            ['id' => 511957, 'region_id' => 783326, 'country_code' => 'LB', 'name' => 'Saadnayel', 'active' => 1, 'slug' => 'saadnayel'],
            ['id' => 511958, 'region_id' => 783326, 'country_code' => 'LB', 'name' => 'Taalbeya', 'active' => 1, 'slug' => 'taalbeya'],
            ['id' => 511959, 'region_id' => 783326, 'country_code' => 'LB', 'name' => 'Taanayel', 'active' => 1, 'slug' => 'taanayel'],
            ['id' => 511960, 'region_id' => 783326, 'country_code' => 'LB', 'name' => 'Terbol', 'active' => 1, 'slug' => 'terbol'],
            ['id' => 511961, 'region_id' => 783326, 'country_code' => 'LB', 'name' => 'Zahlé - Maalaka', 'active' => 1, 'slug' => 'zahle-maalaka'],
            ['id' => 511962, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Arqa', 'active' => 1, 'slug' => 'arqa'],
            ['id' => 511963, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Bebnin', 'active' => 1, 'slug' => 'bebnin'],
            ['id' => 511964, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Beino', 'active' => 1, 'slug' => 'beino'],
            ['id' => 511965, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Cheikh Mohammad', 'active' => 1, 'slug' => 'cheikh-mohammad'],
            ['id' => 511966, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Halba', 'active' => 1, 'slug' => 'halba'],
            ['id' => 511967, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Hisah', 'active' => 1, 'slug' => 'hisah'],
            ['id' => 511968, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Kobayat', 'active' => 1, 'slug' => 'kobayat'],
            ['id' => 511969, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Massoudieh', 'active' => 1, 'slug' => 'massoudieh'],
            ['id' => 511970, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Miniara', 'active' => 1, 'slug' => 'miniara'],
            ['id' => 511971, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Mish Mish', 'active' => 1, 'slug' => 'mish-mish'],
            ['id' => 511972, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Akkar', 'active' => 1, 'slug' => 'akkar'],
            ['id' => 511973, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Ajdabra', 'active' => 1, 'slug' => 'ajdabra'],
            ['id' => 511974, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Assia', 'active' => 1, 'slug' => 'assia'],
            ['id' => 511975, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Batroun', 'active' => 1, 'slug' => 'batroun'],
            ['id' => 511976, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Bcheeleh', 'active' => 1, 'slug' => 'bcheeleh'],
            ['id' => 511977, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Bkesmaya', 'active' => 1, 'slug' => 'bkesmaya'],
            ['id' => 511978, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Chebtine', 'active' => 1, 'slug' => 'chebtine'],
            ['id' => 511979, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Chekka', 'active' => 1, 'slug' => 'chekka'],
            ['id' => 511980, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Douma, Lebanon', 'active' => 1, 'slug' => 'douma-lebanon'],
            ['id' => 511981, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Eddeh', 'active' => 1, 'slug' => 'eddeh'],
            ['id' => 511982, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Hery', 'active' => 1, 'slug' => 'hery'],
            ['id' => 511983, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Hamat', 'active' => 1, 'slug' => 'hamat'],
            ['id' => 511984, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Hardine - Beit Kassab', 'active' => 1, 'slug' => 'hardine-beit-kassab'],
            ['id' => 511985, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Ibrine', 'active' => 1, 'slug' => 'ibrine'],
            ['id' => 511986, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'vKfar Abida', 'active' => 1, 'slug' => 'vkfar-abida'],
            ['id' => 511987, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Kfour el Arabi', 'active' => 1, 'slug' => 'kfour-el-arabi'],
            ['id' => 511988, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Kobba', 'active' => 1, 'slug' => 'kobba'],
            ['id' => 511989, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Ram', 'active' => 1, 'slug' => 'ram'],
            ['id' => 511990, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Ras Nahhache', 'active' => 1, 'slug' => 'ras-nahhache'],
            ['id' => 511991, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Selaata', 'active' => 1, 'slug' => 'selaata'],
            ['id' => 511992, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Tannourine', 'active' => 1, 'slug' => 'tannourine'],
            ['id' => 511993, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Zan', 'active' => 1, 'slug' => 'zan'],
            ['id' => 511994, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Abdine', 'active' => 1, 'slug' => 'abdine'],
            ['id' => 511995, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Barhelyoun', 'active' => 1, 'slug' => 'barhelyoun'],
            ['id' => 511996, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Bazooun', 'active' => 1, 'slug' => 'bazooun'],
            ['id' => 511997, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Beit Mounzer', 'active' => 1, 'slug' => 'beit-mounzer'],
            ['id' => 511998, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Bcharre', 'active' => 1, 'slug' => 'bcharre'],
            ['id' => 511999, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Bkerkacha', 'active' => 1, 'slug' => 'bkerkacha'],
            ['id' => 512000, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Bkaakafra', 'active' => 1, 'slug' => 'bkaakafra'],
            ['id' => 512001, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Blawza', 'active' => 1, 'slug' => 'blawza'],
            ['id' => 512002, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Braissat', 'active' => 1, 'slug' => 'braissat'],
            ['id' => 512003, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Dimane', 'active' => 1, 'slug' => 'dimane'],
            ['id' => 512004, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Hadath El Jebbeh', 'active' => 1, 'slug' => 'hadath-el-jebbeh'],
            ['id' => 512005, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Hadchit', 'active' => 1, 'slug' => 'hadchit'],
            ['id' => 512006, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Hasroun', 'active' => 1, 'slug' => 'hasroun'],
            ['id' => 512007, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Kanat', 'active' => 1, 'slug' => 'kanat'],
            ['id' => 512008, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Tourza', 'active' => 1, 'slug' => 'tourza'],
            ['id' => 512009, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Aaba', 'active' => 1, 'slug' => 'aaba'],
            ['id' => 512010, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Afsaddik', 'active' => 1, 'slug' => 'afsaddik'],
            ['id' => 512011, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Ain Ekrine', 'active' => 1, 'slug' => 'ain-ekrine'],
            ['id' => 512012, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Ajed Ibrine', 'active' => 1, 'slug' => 'ajed-ibrine'],
            ['id' => 512013, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Amioun', 'active' => 1, 'slug' => 'amioun'],
            ['id' => 512014, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Anfeh', 'active' => 1, 'slug' => 'anfeh'],
            ['id' => 512015, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Barsa', 'active' => 1, 'slug' => 'barsa'],
            ['id' => 512016, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Batroumine', 'active' => 1, 'slug' => 'batroumine'],
            ['id' => 512017, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Bdebba', 'active' => 1, 'slug' => 'bdebba'],
            ['id' => 512018, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Bechmezzine', 'active' => 1, 'slug' => 'bechmezzine'],
            ['id' => 512019, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Bednayel', 'active' => 1, 'slug' => 'bednayel'],
            ['id' => 512020, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Bkeftine', 'active' => 1, 'slug' => 'bkeftine'],
            ['id' => 512021, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Bsarma', 'active' => 1, 'slug' => 'bsarma'],
            ['id' => 512022, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Bterram', 'active' => 1, 'slug' => 'bterram'],
            ['id' => 512023, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Btouratij', 'active' => 1, 'slug' => 'btouratij'],
            ['id' => 512024, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Bziza', 'active' => 1, 'slug' => 'bziza'],
            ['id' => 512025, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Dar Beechtar', 'active' => 1, 'slug' => 'dar-beechtar'],
            ['id' => 512026, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Dar Chmezzine', 'active' => 1, 'slug' => 'dar-chmezzine'],
            ['id' => 512027, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Deddeh', 'active' => 1, 'slug' => 'deddeh'],
            ['id' => 512028, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Fih', 'active' => 1, 'slug' => 'fih'],
            ['id' => 512029, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Kaftoun', 'active' => 1, 'slug' => 'kaftoun'],
            ['id' => 512030, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Kalhat', 'active' => 1, 'slug' => 'kalhat'],
            ['id' => 512031, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Kefraya', 'active' => 1, 'slug' => 'kefraya'],
            ['id' => 512032, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Kfarakka', 'active' => 1, 'slug' => 'kfarakka'],
            ['id' => 512033, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Kfarhata', 'active' => 1, 'slug' => 'kfarhata'],
            ['id' => 512034, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Kfarhazir', 'active' => 1, 'slug' => 'kfarhazir'],
            ['id' => 512035, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Kfarkahel', 'active' => 1, 'slug' => 'kfarkahel'],
            ['id' => 512036, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Kfarsaroun', 'active' => 1, 'slug' => 'kfarsaroun'],
            ['id' => 512037, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Kosba', 'active' => 1, 'slug' => 'kosba'],
            ['id' => 512038, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Mejdel - Zakzouk - Wata Fares', 'active' => 1, 'slug' => 'mejdel-zakzouk-wata-fares'],
            ['id' => 512039, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Metrite', 'active' => 1, 'slug' => 'metrite'],
            ['id' => 512040, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Nakhleh', 'active' => 1, 'slug' => 'nakhleh'],
            ['id' => 512041, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Rasmaska', 'active' => 1, 'slug' => 'rasmaska'],
            ['id' => 512042, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Rechdebbine', 'active' => 1, 'slug' => 'rechdebbine'],
            ['id' => 512043, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Koura', 'active' => 1, 'slug' => 'koura'],
            ['id' => 512044, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Asoun', 'active' => 1, 'slug' => 'asoun'],
            ['id' => 512045, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Bakhoun', 'active' => 1, 'slug' => 'bakhoun'],
            ['id' => 512046, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Beddawi - Wadi Nahleh', 'active' => 1, 'slug' => 'beddawi-wadi-nahleh'],
            ['id' => 512047, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Beit el Fokss', 'active' => 1, 'slug' => 'beit-el-fokss'],
            ['id' => 512048, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Bekaasafrine', 'active' => 1, 'slug' => 'bekaasafrine'],
            ['id' => 512049, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Bhannine & Artousa', 'active' => 1, 'slug' => 'bhannine-artousa'],
            ['id' => 512050, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Bkarsouna - Kattine', 'active' => 1, 'slug' => 'bkarsouna-kattine'],
            ['id' => 512051, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Btermaz', 'active' => 1, 'slug' => 'btermaz'],
            ['id' => 512052, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Deir Ammar', 'active' => 1, 'slug' => 'deir-ammar'],
            ['id' => 512053, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Deir Nbouh', 'active' => 1, 'slug' => 'deir-nbouh'],
            ['id' => 512054, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Haql El Aazime', 'active' => 1, 'slug' => 'haql-el-aazime'],
            ['id' => 512055, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Karm el Moher', 'active' => 1, 'slug' => 'karm-el-moher'],
            ['id' => 512056, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Kfarchalane', 'active' => 1, 'slug' => 'kfarchalane'],
            ['id' => 512057, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Kfarhabou', 'active' => 1, 'slug' => 'kfarhabou'],
            ['id' => 512058, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Minyeh', 'active' => 1, 'slug' => 'minyeh'],
            ['id' => 512059, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Mrah Sraj', 'active' => 1, 'slug' => 'mrah-sraj'],
            ['id' => 512060, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Nemrine & Bkaouza', 'active' => 1, 'slug' => 'nemrine-bkaouza'],
            ['id' => 512061, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Sfireh', 'active' => 1, 'slug' => 'sfireh'],
            ['id' => 512062, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Sir', 'active' => 1, 'slug' => 'sir'],
            ['id' => 512063, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Tarane', 'active' => 1, 'slug' => 'tarane'],
            ['id' => 512064, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Miniyeh-Danniyeh', 'active' => 1, 'slug' => 'miniyeh-danniyeh'],
            ['id' => 512065, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Tripoli', 'active' => 1, 'slug' => 'tripoli'],
            ['id' => 512066, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Al-Qalamoun', 'active' => 1, 'slug' => 'al-qalamoun'],
            ['id' => 512067, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Mina', 'active' => 1, 'slug' => 'mina'],
            ['id' => 512068, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Achache', 'active' => 1, 'slug' => 'achache'],
            ['id' => 512069, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Aintourine', 'active' => 1, 'slug' => 'aintourine'],
            ['id' => 512070, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Alma', 'active' => 1, 'slug' => 'alma'],
            ['id' => 512071, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Arbet Kozhaya', 'active' => 1, 'slug' => 'arbet-kozhaya'],
            ['id' => 512072, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Ardeh', 'active' => 1, 'slug' => 'ardeh'],
            ['id' => 512073, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Aarjes', 'active' => 1, 'slug' => 'aarjes'],
            ['id' => 512074, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Aitou', 'active' => 1, 'slug' => 'aitou'],
            ['id' => 512075, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Basloukit', 'active' => 1, 'slug' => 'basloukit'],
            ['id' => 512076, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Bhairet Toula', 'active' => 1, 'slug' => 'bhairet-toula'],
            ['id' => 512077, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Bnachii', 'active' => 1, 'slug' => 'bnachii'],
            ['id' => 512078, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Daraya - Bchennine', 'active' => 1, 'slug' => 'daraya-bchennine'],
            ['id' => 512079, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Ejbeh', 'active' => 1, 'slug' => 'ejbeh'],
            ['id' => 512080, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Haret Al Fawar', 'active' => 1, 'slug' => 'haret-al-fawar'],
            ['id' => 512081, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Iaal', 'active' => 1, 'slug' => 'iaal'],
            ['id' => 512082, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Karmsaddeh', 'active' => 1, 'slug' => 'karmsaddeh'],
            ['id' => 512083, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Kfardlakos', 'active' => 1, 'slug' => 'kfardlakos'],
            ['id' => 512084, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Kfarsghab- Morh Kfarsghab', 'active' => 1, 'slug' => 'kfarsghab-morh-kfarsghab'],
            ['id' => 512085, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Kfarshakhna', 'active' => 1, 'slug' => 'kfarshakhna'],
            ['id' => 512086, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Kfarfou', 'active' => 1, 'slug' => 'kfarfou'],
            ['id' => 512087, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Kfaryachit - Besbeel', 'active' => 1, 'slug' => 'kfaryachit-besbeel'],
            ['id' => 512088, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Kfarzeina', 'active' => 1, 'slug' => 'kfarzeina'],
            ['id' => 512089, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Karahbache', 'active' => 1, 'slug' => 'karahbache'],
            ['id' => 512090, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Mazraat Al Toufah', 'active' => 1, 'slug' => 'mazraat-al-toufah'],
            ['id' => 512091, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Mejdlaya', 'active' => 1, 'slug' => 'mejdlaya'],
            ['id' => 512092, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Mizyara - Haref - Hmayss - Sakhra', 'active' => 1, 'slug' => 'mizyara-haref-hmayss-sakhra'],
            ['id' => 512093, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Miriata - Kadrieh', 'active' => 1, 'slug' => 'miriata-kadrieh'],
            ['id' => 512094, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Rachiine', 'active' => 1, 'slug' => 'rachiine'],
            ['id' => 512095, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Raskifa', 'active' => 1, 'slug' => 'raskifa'],
            ['id' => 512096, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Sebhel', 'active' => 1, 'slug' => 'sebhel'],
            ['id' => 512097, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Serhel', 'active' => 1, 'slug' => 'serhel'],
            ['id' => 512098, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Toula - Aslout', 'active' => 1, 'slug' => 'toula-aslout'],
            ['id' => 512099, 'region_id' => 783327, 'country_code' => 'LB', 'name' => 'Zgharta - Ehden', 'active' => 1, 'slug' => 'zgharta-ehden'],
            ['id' => 512100, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Jezzine', 'active' => 1, 'slug' => 'jezzine'],
            ['id' => 512101, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Kfarhouna', 'active' => 1, 'slug' => 'kfarhouna'],
            ['id' => 512102, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Aramta', 'active' => 1, 'slug' => 'aramta'],
            ['id' => 512103, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Mlikh', 'active' => 1, 'slug' => 'mlikh'],
            ['id' => 512104, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Aitouleh', 'active' => 1, 'slug' => 'aitouleh'],
            ['id' => 512105, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Al Rihan', 'active' => 1, 'slug' => 'al-rihan'],
            ['id' => 512106, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Aray', 'active' => 1, 'slug' => 'aray'],
            ['id' => 512107, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Azour', 'active' => 1, 'slug' => 'azour'],
            ['id' => 512108, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Benweteh', 'active' => 1, 'slug' => 'benweteh'],
            ['id' => 512109, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Haytoura', 'active' => 1, 'slug' => 'haytoura'],
            ['id' => 512110, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Homsiyeh', 'active' => 1, 'slug' => 'homsiyeh'],
            ['id' => 512111, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Kfarfalous', 'active' => 1, 'slug' => 'kfarfalous'],
            ['id' => 512112, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Maknounieh', 'active' => 1, 'slug' => 'maknounieh'],
            ['id' => 512113, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Sfaray', 'active' => 1, 'slug' => 'sfaray'],
            ['id' => 512114, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Snaya', 'active' => 1, 'slug' => 'snaya'],
            ['id' => 512115, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Boslaya', 'active' => 1, 'slug' => 'boslaya'],
            ['id' => 512116, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Kfarjarrah', 'active' => 1, 'slug' => 'kfarjarrah'],
            ['id' => 512117, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Kattine - Hidab', 'active' => 1, 'slug' => 'kattine-hidab'],
            ['id' => 512118, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Midane', 'active' => 1, 'slug' => 'midane'],
            ['id' => 512119, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Mjeydel', 'active' => 1, 'slug' => 'mjeydel'],
            ['id' => 512120, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Jarmak', 'active' => 1, 'slug' => 'jarmak'],
            ['id' => 512121, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Rimat - Chkadif', 'active' => 1, 'slug' => 'rimat-chkadif'],
            ['id' => 512122, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Saydoun', 'active' => 1, 'slug' => 'saydoun'],
            ['id' => 512123, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Louaizeh', 'active' => 1, 'slug' => 'louaizeh'],
            ['id' => 512124, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Jernaya', 'active' => 1, 'slug' => 'jernaya'],
            ['id' => 512125, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Roum', 'active' => 1, 'slug' => 'roum'],
            ['id' => 512126, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Zhalta', 'active' => 1, 'slug' => 'zhalta'],
            ['id' => 512127, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Sojod', 'active' => 1, 'slug' => 'sojod'],
            ['id' => 512128, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Karkha', 'active' => 1, 'slug' => 'karkha'],
            ['id' => 512129, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Bteddine el Lekech', 'active' => 1, 'slug' => 'bteddine-el-lekech'],
            ['id' => 512130, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Bkassine', 'active' => 1, 'slug' => 'bkassine'],
            ['id' => 512131, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Sabbah', 'active' => 1, 'slug' => 'sabbah'],
            ['id' => 512132, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Aychieh', 'active' => 1, 'slug' => 'aychieh'],
            ['id' => 512133, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Lebaa', 'active' => 1, 'slug' => 'lebaa'],
            ['id' => 512134, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Machmouche', 'active' => 1, 'slug' => 'machmouche'],
            ['id' => 512135, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Wadi Jezzine', 'active' => 1, 'slug' => 'wadi-jezzine'],
            ['id' => 512136, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Abra', 'active' => 1, 'slug' => 'abra'],
            ['id' => 512137, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Adloun', 'active' => 1, 'slug' => 'adloun'],
            ['id' => 512138, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Adousieh', 'active' => 1, 'slug' => 'adousieh'],
            ['id' => 512139, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Ain el Delb', 'active' => 1, 'slug' => 'ain-el-delb'],
            ['id' => 512140, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Ankoun', 'active' => 1, 'slug' => 'ankoun'],
            ['id' => 512141, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Bablieh', 'active' => 1, 'slug' => 'bablieh'],
            ['id' => 512142, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Barty', 'active' => 1, 'slug' => 'barty'],
            ['id' => 512143, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Bayssarieh', 'active' => 1, 'slug' => 'bayssarieh'],
            ['id' => 512144, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Bkosta', 'active' => 1, 'slug' => 'bkosta'],
            ['id' => 512145, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Bnaafoul', 'active' => 1, 'slug' => 'bnaafoul'],
            ['id' => 512146, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Bramieh', 'active' => 1, 'slug' => 'bramieh'],
            ['id' => 512147, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Dareb el Sim', 'active' => 1, 'slug' => 'dareb-el-sim'],
            ['id' => 512148, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Erkay', 'active' => 1, 'slug' => 'erkay'],
            ['id' => 512149, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Ghazieh', 'active' => 1, 'slug' => 'ghazieh'],
            ['id' => 512150, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Ghessanieh', 'active' => 1, 'slug' => 'ghessanieh'],
            ['id' => 512151, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Haret Saida', 'active' => 1, 'slug' => 'haret-saida'],
            ['id' => 512152, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Hlalyeh', 'active' => 1, 'slug' => 'hlalyeh'],
            ['id' => 512153, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Insariat', 'active' => 1, 'slug' => 'insariat'],
            ['id' => 512154, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Irzay', 'active' => 1, 'slug' => 'irzay'],
            ['id' => 512155, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Kaakaiyat el Snaoubar', 'active' => 1, 'slug' => 'kaakaiyat-el-snaoubar'],
            ['id' => 512156, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Kawthariyet el Siyyad', 'active' => 1, 'slug' => 'kawthariyet-el-siyyad'],
            ['id' => 512157, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Kfarhatta', 'active' => 1, 'slug' => 'kfarhatta'],
            ['id' => 512158, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Kfarmilke', 'active' => 1, 'slug' => 'kfarmilke'],
            ['id' => 512159, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Khartoum', 'active' => 1, 'slug' => 'khartoum'],
            ['id' => 512160, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Khrayeb', 'active' => 1, 'slug' => 'khrayeb'],
            ['id' => 512161, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Knarite', 'active' => 1, 'slug' => 'knarite'],
            ['id' => 512162, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Krayeh', 'active' => 1, 'slug' => 'krayeh'],
            ['id' => 512163, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Loubieh', 'active' => 1, 'slug' => 'loubieh'],
            ['id' => 512164, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Maghdouche', 'active' => 1, 'slug' => 'maghdouche'],
            ['id' => 512165, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Majdelyoun', 'active' => 1, 'slug' => 'majdelyoun'],
            ['id' => 512166, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Meemarieh', 'active' => 1, 'slug' => 'meemarieh'],
            ['id' => 512167, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Merwanieh', 'active' => 1, 'slug' => 'merwanieh'],
            ['id' => 512168, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Miye ou Miye', 'active' => 1, 'slug' => 'miye-ou-miye'],
            ['id' => 512169, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Najjarieh', 'active' => 1, 'slug' => 'najjarieh'],
            ['id' => 512170, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Sidon', 'active' => 1, 'slug' => 'sidon'],
            ['id' => 512171, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Saksakieh', 'active' => 1, 'slug' => 'saksakieh'],
            ['id' => 512172, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Salhieh', 'active' => 1, 'slug' => 'salhieh'],
            ['id' => 512173, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Sarafand', 'active' => 1, 'slug' => 'sarafand'],
            ['id' => 512174, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Tafahta', 'active' => 1, 'slug' => 'tafahta'],
            ['id' => 512175, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Tanbourit', 'active' => 1, 'slug' => 'tanbourit'],
            ['id' => 512176, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Zeita', 'active' => 1, 'slug' => 'zeita'],
            ['id' => 512177, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Zrariyeh', 'active' => 1, 'slug' => 'zrariyeh'],
            ['id' => 512178, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Aaytit', 'active' => 1, 'slug' => 'aaytit'],
            ['id' => 512179, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Abbassieh', 'active' => 1, 'slug' => 'abbassieh'],
            ['id' => 512180, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Ain Baal', 'active' => 1, 'slug' => 'ain-baal'],
            ['id' => 512181, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Alma el Chaab', 'active' => 1, 'slug' => 'alma-el-chaab'],
            ['id' => 512182, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Arzoun', 'active' => 1, 'slug' => 'arzoun'],
            ['id' => 512183, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Baflaya', 'active' => 1, 'slug' => 'baflaya'],
            ['id' => 512184, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Barich', 'active' => 1, 'slug' => 'barich'],
            ['id' => 512185, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Batoulieh', 'active' => 1, 'slug' => 'batoulieh'],
            ['id' => 512186, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Bayyad', 'active' => 1, 'slug' => 'bayyad'],
            ['id' => 512187, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Bazourieh', 'active' => 1, 'slug' => 'bazourieh'],
            ['id' => 512188, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Bedyass', 'active' => 1, 'slug' => 'bedyass'],
            ['id' => 512189, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Borj el Chamali', 'active' => 1, 'slug' => 'borj-el-chamali'],
            ['id' => 512190, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Borj Rahal', 'active' => 1, 'slug' => 'borj-rahal'],
            ['id' => 512191, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Bourghlieh', 'active' => 1, 'slug' => 'bourghlieh'],
            ['id' => 512192, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Boustane', 'active' => 1, 'slug' => 'boustane'],
            ['id' => 512193, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Chameh', 'active' => 1, 'slug' => 'chameh'],
            ['id' => 512194, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Chehabie', 'active' => 1, 'slug' => 'chehabie'],
            ['id' => 512195, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Chehour', 'active' => 1, 'slug' => 'chehour'],
            ['id' => 512196, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Chihine', 'active' => 1, 'slug' => 'chihine'],
            ['id' => 512197, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Debaal', 'active' => 1, 'slug' => 'debaal'],
            ['id' => 512198, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Deir Amess', 'active' => 1, 'slug' => 'deir-amess'],
            ['id' => 512199, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Deir Kanoun - Ras el Ain', 'active' => 1, 'slug' => 'deir-kanoun-ras-el-ain'],
            ['id' => 512200, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Deir Kanoun Naher', 'active' => 1, 'slug' => 'deir-kanoun-naher'],
            ['id' => 512201, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Derdghaya', 'active' => 1, 'slug' => 'derdghaya'],
            ['id' => 512202, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Halloussieh', 'active' => 1, 'slug' => 'halloussieh'],
            ['id' => 512203, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Hanawey', 'active' => 1, 'slug' => 'hanawey'],
            ['id' => 512204, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Henniye', 'active' => 1, 'slug' => 'henniye'],
            ['id' => 512205, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Hmayri', 'active' => 1, 'slug' => 'hmayri'],
            ['id' => 512206, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Jebal El Botom', 'active' => 1, 'slug' => 'jebal-el-botom'],
            ['id' => 512207, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Jebbine', 'active' => 1, 'slug' => 'jebbine'],
            ['id' => 512208, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Jouaya', 'active' => 1, 'slug' => 'jouaya'],
            ['id' => 512209, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Kana', 'active' => 1, 'slug' => 'kana'],
            ['id' => 512210, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Kolayleh', 'active' => 1, 'slug' => 'kolayleh'],
            ['id' => 512211, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Maarake', 'active' => 1, 'slug' => 'maarake'],
            ['id' => 512212, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Maaroub', 'active' => 1, 'slug' => 'maaroub'],
            ['id' => 512213, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Mahroune', 'active' => 1, 'slug' => 'mahroune'],
            ['id' => 512214, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Majadel', 'active' => 1, 'slug' => 'majadel'],
            ['id' => 512215, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Majdalzoun', 'active' => 1, 'slug' => 'majdalzoun'],
            ['id' => 512216, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Mansouri', 'active' => 1, 'slug' => 'mansouri'],
            ['id' => 512217, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Marwahine', 'active' => 1, 'slug' => 'marwahine'],
            ['id' => 512218, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Mazraat Mechref', 'active' => 1, 'slug' => 'mazraat-mechref'],
            ['id' => 512219, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Nakoura', 'active' => 1, 'slug' => 'nakoura'],
            ['id' => 512220, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Ramadiye', 'active' => 1, 'slug' => 'ramadiye'],
            ['id' => 512221, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Rechknanay', 'active' => 1, 'slug' => 'rechknanay'],
            ['id' => 512222, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Selha', 'active' => 1, 'slug' => 'selha'],
            ['id' => 512223, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Siddikine', 'active' => 1, 'slug' => 'siddikine'],
            ['id' => 512224, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Srifa', 'active' => 1, 'slug' => 'srifa'],
            ['id' => 512225, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Tayrdebba', 'active' => 1, 'slug' => 'tayrdebba'],
            ['id' => 512226, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Tayrfelsay', 'active' => 1, 'slug' => 'tayrfelsay'],
            ['id' => 512227, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Tayrharfa', 'active' => 1, 'slug' => 'tayrharfa'],
            ['id' => 512228, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Toura', 'active' => 1, 'slug' => 'toura'],
            ['id' => 512229, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Tyre', 'active' => 1, 'slug' => 'tyre'],
            ['id' => 512230, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Yanouh', 'active' => 1, 'slug' => 'yanouh'],
            ['id' => 512231, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Yarine', 'active' => 1, 'slug' => 'yarine'],
            ['id' => 512232, 'region_id' => 783328, 'country_code' => 'LB', 'name' => 'Zibkin', 'active' => 1, 'slug' => 'zibkin'],
            ['id' => 512233, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Ain Ebel', 'active' => 1, 'slug' => 'ain-ebel'],
            ['id' => 512234, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Aynata', 'active' => 1, 'slug' => 'aynata'],
            ['id' => 512235, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Ayta el Chaeb', 'active' => 1, 'slug' => 'ayta-el-chaeb'],
            ['id' => 512236, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Ayta el Jabal', 'active' => 1, 'slug' => 'ayta-el-jabal'],
            ['id' => 512237, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Aytaroun', 'active' => 1, 'slug' => 'aytaroun'],
            ['id' => 512238, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Beit Lif', 'active' => 1, 'slug' => 'beit-lif'],
            ['id' => 512239, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Beit Yahoun', 'active' => 1, 'slug' => 'beit-yahoun'],
            ['id' => 512240, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Bint Jbeil', 'active' => 1, 'slug' => 'bint-jbeil'],
            ['id' => 512241, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Borj Kalaway', 'active' => 1, 'slug' => 'borj-kalaway'],
            ['id' => 512242, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Braachit', 'active' => 1, 'slug' => 'braachit'],
            ['id' => 512243, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Chakra wa Doubeih', 'active' => 1, 'slug' => 'chakra-wa-doubeih'],
            ['id' => 512244, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Debel', 'active' => 1, 'slug' => 'debel'],
            ['id' => 512245, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Deir Antar', 'active' => 1, 'slug' => 'deir-antar'],
            ['id' => 512246, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Froun', 'active' => 1, 'slug' => 'froun'],
            ['id' => 512247, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Ghandouriyeh', 'active' => 1, 'slug' => 'ghandouriyeh'],
            ['id' => 512248, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Hanine', 'active' => 1, 'slug' => 'hanine'],
            ['id' => 512249, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Hariss', 'active' => 1, 'slug' => 'hariss'],
            ['id' => 512250, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Hdatha', 'active' => 1, 'slug' => 'hdatha'],
            ['id' => 512251, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Jmeyjmeh', 'active' => 1, 'slug' => 'jmeyjmeh'],
            ['id' => 512252, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Kafra', 'active' => 1, 'slug' => 'kafra'],
            ['id' => 512253, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Kalaway', 'active' => 1, 'slug' => 'kalaway'],
            ['id' => 512254, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Kawzah', 'active' => 1, 'slug' => 'kawzah'],
            ['id' => 512255, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Kfardounine', 'active' => 1, 'slug' => 'kfardounine'],
            ['id' => 512256, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Khirbet Selm', 'active' => 1, 'slug' => 'khirbet-selm'],
            ['id' => 512257, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Kounine', 'active' => 1, 'slug' => 'kounine'],
            ['id' => 512258, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Maroun el Ras', 'active' => 1, 'slug' => 'maroun-el-ras'],
            ['id' => 512259, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Rchaf', 'active' => 1, 'slug' => 'rchaf'],
            ['id' => 512260, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Rmeich', 'active' => 1, 'slug' => 'rmeich'],
            ['id' => 512261, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Serbine', 'active' => 1, 'slug' => 'serbine'],
            ['id' => 512262, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Sultanieh', 'active' => 1, 'slug' => 'sultanieh'],
            ['id' => 512263, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Tebnine', 'active' => 1, 'slug' => 'tebnine'],
            ['id' => 512264, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Tiri', 'active' => 1, 'slug' => 'tiri'],
            ['id' => 512265, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Yater', 'active' => 1, 'slug' => 'yater'],
            ['id' => 512266, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Ain Kanya', 'active' => 1, 'slug' => 'ain-kanya'],
            ['id' => 512267, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Shebaa', 'active' => 1, 'slug' => 'shebaa'],
            ['id' => 512268, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Chwayya', 'active' => 1, 'slug' => 'chwayya'],
            ['id' => 512269, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Fardiss', 'active' => 1, 'slug' => 'fardiss'],
            ['id' => 512270, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Hasbaya', 'active' => 1, 'slug' => 'hasbaya'],
            ['id' => 512271, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Hbariyeh', 'active' => 1, 'slug' => 'hbariyeh'],
            ['id' => 512272, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Kawkaba', 'active' => 1, 'slug' => 'kawkaba'],
            ['id' => 512273, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Kfarhamam', 'active' => 1, 'slug' => 'kfarhamam'],
            ['id' => 512274, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Kfarchouba', 'active' => 1, 'slug' => 'kfarchouba'],
            ['id' => 512275, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Kfeir', 'active' => 1, 'slug' => 'kfeir'],
            ['id' => 512276, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Khalwat', 'active' => 1, 'slug' => 'khalwat'],
            ['id' => 512277, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Marj el Zhour', 'active' => 1, 'slug' => 'marj-el-zhour'],
            ['id' => 512278, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Mari', 'active' => 1, 'slug' => 'mari'],
            ['id' => 512279, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Mimass', 'active' => 1, 'slug' => 'mimass'],
            ['id' => 512280, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Rachaya el Fokhar', 'active' => 1, 'slug' => 'rachaya-el-fokhar'],
            ['id' => 512281, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Adayseh', 'active' => 1, 'slug' => 'adayseh'],
            ['id' => 512282, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Adchit', 'active' => 1, 'slug' => 'adchit'],
            ['id' => 512283, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Bani Hayann', 'active' => 1, 'slug' => 'bani-hayann'],
            ['id' => 512284, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Blatt', 'active' => 1, 'slug' => 'blatt'],
            ['id' => 512285, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Blida', 'active' => 1, 'slug' => 'blida'],
            ['id' => 512286, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Debbine', 'active' => 1, 'slug' => 'debbine'],
            ['id' => 512287, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Deir Mimass', 'active' => 1, 'slug' => 'deir-mimass'],
            ['id' => 512288, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Deir Syriane', 'active' => 1, 'slug' => 'deir-syriane'],
            ['id' => 512289, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Ebel el Saky', 'active' => 1, 'slug' => 'ebel-el-saky'],
            ['id' => 512290, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Houla', 'active' => 1, 'slug' => 'houla'],
            ['id' => 512291, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Jdeidet Marjeeyoun', 'active' => 1, 'slug' => 'jdeidet-marjeeyoun'],
            ['id' => 512292, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Kabrikha', 'active' => 1, 'slug' => 'kabrikha'],
            ['id' => 512293, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Kantara', 'active' => 1, 'slug' => 'kantara'],
            ['id' => 512294, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Kfarkila', 'active' => 1, 'slug' => 'kfarkila'],
            ['id' => 512295, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Khiam', 'active' => 1, 'slug' => 'khiam'],
            ['id' => 512296, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Klayaa', 'active' => 1, 'slug' => 'klayaa'],
            ['id' => 512297, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Majdel Selem', 'active' => 1, 'slug' => 'majdel-selem'],
            ['id' => 512298, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Markaba', 'active' => 1, 'slug' => 'markaba'],
            ['id' => 512299, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Mays el Jabal', 'active' => 1, 'slug' => 'mays-el-jabal'],
            ['id' => 512300, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Rab Thalathine', 'active' => 1, 'slug' => 'rab-thalathine'],
            ['id' => 512301, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Sawaneh', 'active' => 1, 'slug' => 'sawaneh'],
            ['id' => 512302, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Tallousseh', 'active' => 1, 'slug' => 'tallousseh'],
            ['id' => 512303, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Taybeh', 'active' => 1, 'slug' => 'taybeh'],
            ['id' => 512304, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Wazzany', 'active' => 1, 'slug' => 'wazzany'],
            ['id' => 512305, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Marjeyoun', 'active' => 1, 'slug' => 'marjeyoun'],
            ['id' => 512306, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Houmin el Tahta', 'active' => 1, 'slug' => 'houmin-el-tahta'],
            ['id' => 512307, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Ain Qana', 'active' => 1, 'slug' => 'ain-qana'],
            ['id' => 512308, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Ansar', 'active' => 1, 'slug' => 'ansar'],
            ['id' => 512309, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Arabsalim', 'active' => 1, 'slug' => 'arabsalim'],
            ['id' => 512310, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Arnoun', 'active' => 1, 'slug' => 'arnoun'],
            ['id' => 512311, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Breykaah', 'active' => 1, 'slug' => 'breykaah'],
            ['id' => 512312, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Charkiyeh', 'active' => 1, 'slug' => 'charkiyeh'],
            ['id' => 512313, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Choukine', 'active' => 1, 'slug' => 'choukine'],
            ['id' => 512314, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Deir el Zahrani', 'active' => 1, 'slug' => 'deir-el-zahrani'],
            ['id' => 512315, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Doueir', 'active' => 1, 'slug' => 'doueir'],
            ['id' => 512316, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Ebba', 'active' => 1, 'slug' => 'ebba'],
            ['id' => 512317, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Habbouch', 'active' => 1, 'slug' => 'habbouch'],
            ['id' => 512318, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Harouf', 'active' => 1, 'slug' => 'harouf'],
            ['id' => 512319, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Houmin el Fawka', 'active' => 1, 'slug' => 'houmin-el-fawka'],
            ['id' => 512320, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Jarjouh', 'active' => 1, 'slug' => 'jarjouh'],
            ['id' => 512321, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Jbaa - Ain Bouswar', 'active' => 1, 'slug' => 'jbaa-ain-bouswar'],
            ['id' => 512322, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Jebchit', 'active' => 1, 'slug' => 'jebchit'],
            ['id' => 512323, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Kaakaiyet el Jisr', 'active' => 1, 'slug' => 'kaakaiyet-el-jisr'],
            ['id' => 512324, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Kfarfila', 'active' => 1, 'slug' => 'kfarfila'],
            ['id' => 512325, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Kfarremane', 'active' => 1, 'slug' => 'kfarremane'],
            ['id' => 512326, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Kfarsir', 'active' => 1, 'slug' => 'kfarsir'],
            ['id' => 512327, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Kfartebnit', 'active' => 1, 'slug' => 'kfartebnit'],
            ['id' => 512328, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Kfour', 'active' => 1, 'slug' => 'kfour'],
            ['id' => 512329, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Kossaybeh', 'active' => 1, 'slug' => 'kossaybeh'],
            ['id' => 512330, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Mayfadoun', 'active' => 1, 'slug' => 'mayfadoun'],
            ['id' => 512331, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Nabatieh el Fawka', 'active' => 1, 'slug' => 'nabatiehel-fawka'],
            ['id' => 512332, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Nabatieh el Tahta', 'active' => 1, 'slug' => 'nabatiehel-tahta'],
            ['id' => 512333, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Namiriyeh', 'active' => 1, 'slug' => 'namiriyeh'],
            ['id' => 512334, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Roumine', 'active' => 1, 'slug' => 'roumine'],
            ['id' => 512335, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Sarba', 'active' => 1, 'slug' => 'sarba'],
            ['id' => 512336, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Siney', 'active' => 1, 'slug' => 'siney'],
            ['id' => 512337, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Sir el Gharbiyeh', 'active' => 1, 'slug' => 'sir-el-gharbiyeh'],
            ['id' => 512338, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Yehmor el Chekif', 'active' => 1, 'slug' => 'yehmor-el-chekif'],
            ['id' => 512339, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Zawtar el Charkiyeh', 'active' => 1, 'slug' => 'zawtar-el-charkiyeh'],
            ['id' => 512340, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Zawtar el Gharbiyeh', 'active' => 1, 'slug' => 'zawtar-el-gharbiyeh'],
            ['id' => 512341, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Zebdine', 'active' => 1, 'slug' => 'zebdine'],
            ['id' => 512342, 'region_id' => 783329, 'country_code' => 'LB', 'name' => 'Zefta', 'active' => 1, 'slug' => 'zefta'],
            ['id' => 512343, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Ainbal', 'active' => 1, 'slug' => 'ainbal'],
            ['id' => 512344, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Ain Kani', 'active' => 1, 'slug' => 'ain-kani'],
            ['id' => 512345, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Ain Wzein', 'active' => 1, 'slug' => 'ain-wzein'],
            ['id' => 512346, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Ain Zhalta', 'active' => 1, 'slug' => 'ain-zhalta'],
            ['id' => 512347, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Amatour', 'active' => 1, 'slug' => 'amatour'],
            ['id' => 512348, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Ammik', 'active' => 1, 'slug' => 'ammik'],
            ['id' => 512349, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Anout', 'active' => 1, 'slug' => 'anout'],
            ['id' => 512350, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Atrine', 'active' => 1, 'slug' => 'atrine'],
            ['id' => 512351, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Baakline', 'active' => 1, 'slug' => 'baakline'],
            ['id' => 512352, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Baasir', 'active' => 1, 'slug' => 'baasir'],
            ['id' => 512353, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Baatharan', 'active' => 1, 'slug' => 'baatharan'],
            ['id' => 512354, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Barja', 'active' => 1, 'slug' => 'barja'],
            ['id' => 512355, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Barouk - Freydiss', 'active' => 1, 'slug' => 'barouk-freydiss'],
            ['id' => 512356, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Bater', 'active' => 1, 'slug' => 'bater'],
            ['id' => 512357, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Batloun', 'active' => 1, 'slug' => 'batloun'],
            ['id' => 512358, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Bchetfine', 'active' => 1, 'slug' => 'bchetfine'],
            ['id' => 512359, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Beiteddine', 'active' => 1, 'slug' => 'beiteddine'],
            ['id' => 512360, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Berjein & Mreyjat', 'active' => 1, 'slug' => 'berjein-mreyjat'],
            ['id' => 512361, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Bireh', 'active' => 1, 'slug' => 'bireh'],
            ['id' => 512362, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Botme', 'active' => 1, 'slug' => 'botme'],
            ['id' => 512363, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Bsaba El Chouf', 'active' => 1, 'slug' => 'bsaba-el-chouf'],
            ['id' => 512364, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Chehim', 'active' => 1, 'slug' => 'chehim'],
            ['id' => 512365, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Daher el Mghara', 'active' => 1, 'slug' => 'daher-el-mghara'],
            ['id' => 512366, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Dalhoun', 'active' => 1, 'slug' => 'dalhoun'],
            ['id' => 512367, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Damour', 'active' => 1, 'slug' => 'damour'],
            ['id' => 512368, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Daraya', 'active' => 1, 'slug' => 'daraya'],
            ['id' => 512369, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Debbieh', 'active' => 1, 'slug' => 'debbieh'],
            ['id' => 512370, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Deir Dourit', 'active' => 1, 'slug' => 'deir-dourit'],
            ['id' => 512371, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Deir el Qamar', 'active' => 1, 'slug' => 'deir-el-qamar'],
            ['id' => 512372, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Deir Kouche', 'active' => 1, 'slug' => 'deir-kouche'],
            ['id' => 512373, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Dmit', 'active' => 1, 'slug' => 'dmit'],
            ['id' => 512374, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Fouara', 'active' => 1, 'slug' => 'fouara'],
            ['id' => 512375, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Gharife', 'active' => 1, 'slug' => 'gharife'],
            ['id' => 512376, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Haret Jandal', 'active' => 1, 'slug' => 'haret-jandal'],
            ['id' => 512377, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Hasrout', 'active' => 1, 'slug' => 'hasrout'],
            ['id' => 512378, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Khraybeh', 'active' => 1, 'slug' => 'khraybeh'],
            ['id' => 512379, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Jadra', 'active' => 1, 'slug' => 'jadra'],
            ['id' => 512380, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Jahlieh', 'active' => 1, 'slug' => 'jahlieh'],
            ['id' => 512381, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Jbeih', 'active' => 1, 'slug' => 'jbeih'],
            ['id' => 512382, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Jdeidet el Chouf', 'active' => 1, 'slug' => 'jdeidet-el-chouf'],
            ['id' => 512383, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Jiyeh', 'active' => 1, 'slug' => 'jiyeh'],
            ['id' => 512384, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Joun', 'active' => 1, 'slug' => 'joun'],
            ['id' => 512385, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Kahlounie', 'active' => 1, 'slug' => 'kahlounie'],
            ['id' => 512386, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Ketermaya', 'active' => 1, 'slug' => 'ketermaya'],
            ['id' => 512387, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Kfarfakoud', 'active' => 1, 'slug' => 'kfarfakoud'],
            ['id' => 512388, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Kfarhim', 'active' => 1, 'slug' => 'kfarhim'],
            ['id' => 512389, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Kfarkatra', 'active' => 1, 'slug' => 'kfarkatra'],
            ['id' => 512390, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Kfarnabrakh', 'active' => 1, 'slug' => 'kfarnabrakh'],
            ['id' => 512391, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Kfarniss', 'active' => 1, 'slug' => 'kfarniss'],
            ['id' => 512392, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Knayse', 'active' => 1, 'slug' => 'knayse'],
            ['id' => 512393, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Maasser Beiteddine', 'active' => 1, 'slug' => 'maasser-beiteddine'],
            ['id' => 512394, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Maasser el Chouf', 'active' => 1, 'slug' => 'maasser-el-chouf'],
            ['id' => 512395, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Majdel Meouch', 'active' => 1, 'slug' => 'majdel-meouch'],
            ['id' => 512396, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Mazboud', 'active' => 1, 'slug' => 'mazboud'],
            ['id' => 512397, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Mazraat el Chouf', 'active' => 1, 'slug' => 'mazraat-el-chouf'],
            ['id' => 512398, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Mazraat el Daher', 'active' => 1, 'slug' => 'mazraat-el-daher'],
            ['id' => 512399, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Mechref', 'active' => 1, 'slug' => 'mechref'],
            ['id' => 512400, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Mghayrie', 'active' => 1, 'slug' => 'mghayrie'],
            ['id' => 512401, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Moukhtara', 'active' => 1, 'slug' => 'moukhtara'],
            ['id' => 512402, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Mristeh', 'active' => 1, 'slug' => 'mristeh'],
            ['id' => 512403, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Naameh', 'active' => 1, 'slug' => 'naameh'],
            ['id' => 512404, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Niha', 'active' => 1, 'slug' => 'niha'],
            ['id' => 512405, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Rmayle', 'active' => 1, 'slug' => 'rmayle'],
            ['id' => 512406, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Sebline', 'active' => 1, 'slug' => 'sebline'],
            ['id' => 512407, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Semkanieh', 'active' => 1, 'slug' => 'semkanieh'],
            ['id' => 512408, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Serjbeil', 'active' => 1, 'slug' => 'serjbeil'],
            ['id' => 512409, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Wadi Sit', 'active' => 1, 'slug' => 'wadi-sit'],
            ['id' => 512410, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Warhanieh', 'active' => 1, 'slug' => 'warhanieh'],
            ['id' => 512411, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Werdanieh', 'active' => 1, 'slug' => 'werdanieh'],
            ['id' => 512412, 'region_id' => 783330, 'country_code' => 'LB', 'name' => 'Zaarouriye', 'active' => 1, 'slug' => 'zaarouriye'],
            ['id' => 512413, 'region_id' => 783331, 'country_code' => 'LB', 'name' => 'Baabda', 'active' => 1, 'slug' => 'baabda'],
            ['id' => 512414, 'region_id' => 783331, 'country_code' => 'LB', 'name' => 'Borj el Brajneh', 'active' => 1, 'slug' => 'borj-el-brajneh'],
            ['id' => 512415, 'region_id' => 783331, 'country_code' => 'LB', 'name' => 'Hazmieh', 'active' => 1, 'slug' => 'hazmieh'],
            ['id' => 512416, 'region_id' => 783331, 'country_code' => 'LB', 'name' => 'Hadath', 'active' => 1, 'slug' => 'hadath'],
            ['id' => 512417, 'region_id' => 783331, 'country_code' => 'LB', 'name' => 'Hammana', 'active' => 1, 'slug' => 'hammana'],
            ['id' => 512418, 'region_id' => 783331, 'country_code' => 'LB', 'name' => 'Ras el Matn', 'active' => 1, 'slug' => 'ras-el-matn'],
            ['id' => 512419, 'region_id' => 783331, 'country_code' => 'LB', 'name' => 'Chiyah', 'active' => 1, 'slug' => 'chiyah'],
            ['id' => 512420, 'region_id' => 783331, 'country_code' => 'LB', 'name' => 'Ghbeireh', 'active' => 1, 'slug' => 'ghbeireh'],
            ['id' => 512421, 'region_id' => 783331, 'country_code' => 'LB', 'name' => 'Falougha', 'active' => 1, 'slug' => 'falougha'],
            ['id' => 512422, 'region_id' => 783331, 'country_code' => 'LB', 'name' => 'Furn el Chebbak', 'active' => 1, 'slug' => 'furn-el-chebbak'],
            ['id' => 512423, 'region_id' => 783331, 'country_code' => 'LB', 'name' => 'Kornayel', 'active' => 1, 'slug' => 'kornayel'],
            ['id' => 512424, 'region_id' => 783331, 'country_code' => 'LB', 'name' => 'Kfarchima', 'active' => 1, 'slug' => 'kfarchima'],
            ['id' => 512425, 'region_id' => 783331, 'country_code' => 'LB', 'name' => 'Wadi Chahrour', 'active' => 1, 'slug' => 'wadi-chahrour'],
            ['id' => 512426, 'region_id' => 783331, 'country_code' => 'LB', 'name' => 'Abadiyeh', 'active' => 1, 'slug' => 'abadiyeh'],
            ['id' => 512427, 'region_id' => 783331, 'country_code' => 'LB', 'name' => 'Salima', 'active' => 1, 'slug' => 'salima'],
            ['id' => 512428, 'region_id' => 783331, 'country_code' => 'LB', 'name' => 'Jdeideh', 'active' => 1, 'slug' => 'jdeideh'],
            ['id' => 512429, 'region_id' => 783331, 'country_code' => 'LB', 'name' => 'Bourj Hammoud', 'active' => 1, 'slug' => 'bourj-hammoud'],
            ['id' => 512430, 'region_id' => 783331, 'country_code' => 'LB', 'name' => 'Bauchrieh', 'active' => 1, 'slug' => 'bauchrieh'],
            ['id' => 512431, 'region_id' => 783331, 'country_code' => 'LB', 'name' => 'Antelias', 'active' => 1, 'slug' => 'antelias'],
            ['id' => 512432, 'region_id' => 783331, 'country_code' => 'LB', 'name' => 'Brummana', 'active' => 1, 'slug' => 'brummana'],
            ['id' => 512433, 'region_id' => 783331, 'country_code' => 'LB', 'name' => 'Baabdat', 'active' => 1, 'slug' => 'baabdat'],
            ['id' => 512434, 'region_id' => 783331, 'country_code' => 'LB', 'name' => 'Bikfaya', 'active' => 1, 'slug' => 'bikfaya'],
            ['id' => 512435, 'region_id' => 783331, 'country_code' => 'LB', 'name' => 'Beit Chabab', 'active' => 1, 'slug' => 'beit-chabab'],
            ['id' => 512436, 'region_id' => 783331, 'country_code' => 'LB', 'name' => 'Beit Mery', 'active' => 1, 'slug' => 'beit-mery'],
            ['id' => 512437, 'region_id' => 783331, 'country_code' => 'LB', 'name' => 'Chewyeh', 'active' => 1, 'slug' => 'chewyeh'],
            ['id' => 512438, 'region_id' => 783331, 'country_code' => 'LB', 'name' => 'Jal el Dib', 'active' => 1, 'slug' => 'jal-el-dib'],
            ['id' => 512439, 'region_id' => 783331, 'country_code' => 'LB', 'name' => 'Dekwaneh', 'active' => 1, 'slug' => 'dekwaneh'],
            ['id' => 512440, 'region_id' => 783331, 'country_code' => 'LB', 'name' => 'Zalka', 'active' => 1, 'slug' => 'zalka'],
            ['id' => 512441, 'region_id' => 783331, 'country_code' => 'LB', 'name' => 'Sin el Fil', 'active' => 1, 'slug' => 'sin-el-fil'],
            ['id' => 512442, 'region_id' => 783331, 'country_code' => 'LB', 'name' => 'Dbayeh', 'active' => 1, 'slug' => 'dbayeh'],
            ['id' => 512443, 'region_id' => 783331, 'country_code' => 'LB', 'name' => 'Kornet Chehwan', 'active' => 1, 'slug' => 'kornet-chehwan'],
            ['id' => 512444, 'region_id' => 783331, 'country_code' => 'LB', 'name' => 'Aintoura', 'active' => 1, 'slug' => 'aintoura'],
            ['id' => 512445, 'region_id' => 783331, 'country_code' => 'LB', 'name' => 'Choueir', 'active' => 1, 'slug' => 'choueir'],
            ['id' => 512446, 'region_id' => 783331, 'country_code' => 'LB', 'name' => 'Khenchara', 'active' => 1, 'slug' => 'khenchara'],
            ['id' => 512447, 'region_id' => 783331, 'country_code' => 'LB', 'name' => 'Bteghrine', 'active' => 1, 'slug' => 'bteghrine'],
            ['id' => 512448, 'region_id' => 783331, 'country_code' => 'LB', 'name' => 'Baskinta', 'active' => 1, 'slug' => 'baskinta']
    	];
    }
}
