<?php

namespace Gerardojbaez\GeoData\Seeders;

use Illuminate\Database\Seeder;
use Gerardojbaez\GeoData\Models\Country;
use Gerardojbaez\GeoData\Models\Region;
use Gerardojbaez\GeoData\Models\City;

class MalaysiaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Country::create($this->country());
        Region::insert($this->regions());

        if ($this->cities() > 4000)
        {
            foreach (array_chunk($this->cities(), 3500) as $chunk)
                City::insert($chunk);
        }
        else
        {
            City::insert($this->cities());
        }
    }

        /**
     * Get country.
     *
     * @return array
     */
    public function country()
    {
    	return ['code' => 'MY', 'name' => 'Malaysia', 'slug' => 'malaysia'];
    }

    /**
     * Get country regions.
     *
     * @return array
     */
    public function regions()
    {
    	return [
            ['id' => 782219, 'country_code' => 'MY', 'name' => 'Johor', 'active' => 1, 'slug' => 'johor'],
            ['id' => 782220, 'country_code' => 'MY', 'name' => 'Kedah', 'active' => 1, 'slug' => 'kedah'],
            ['id' => 782221, 'country_code' => 'MY', 'name' => 'Kelantan', 'active' => 1, 'slug' => 'kelantan'],
            ['id' => 782222, 'country_code' => 'MY', 'name' => 'Kuala Lumpur', 'active' => 1, 'slug' => 'kuala-lumpur'],
            ['id' => 782223, 'country_code' => 'MY', 'name' => 'Melaka', 'active' => 1, 'slug' => 'melaka'],
            ['id' => 782224, 'country_code' => 'MY', 'name' => 'Negeri Sembilan', 'active' => 1, 'slug' => 'negeri-sembilan'],
            ['id' => 782225, 'country_code' => 'MY', 'name' => 'Pahang', 'active' => 1, 'slug' => 'pahang'],
            ['id' => 782226, 'country_code' => 'MY', 'name' => 'Penang', 'active' => 1, 'slug' => 'penang'],
            ['id' => 782227, 'country_code' => 'MY', 'name' => 'Perak', 'active' => 1, 'slug' => 'perak'],
            ['id' => 782228, 'country_code' => 'MY', 'name' => 'Perlis', 'active' => 1, 'slug' => 'perlis'],
            ['id' => 782229, 'country_code' => 'MY', 'name' => 'Putrajaya', 'active' => 1, 'slug' => 'putrajaya'],
            ['id' => 782230, 'country_code' => 'MY', 'name' => 'Sabah', 'active' => 1, 'slug' => 'sabah'],
            ['id' => 782231, 'country_code' => 'MY', 'name' => 'Sarawak', 'active' => 1, 'slug' => 'sarawak'],
            ['id' => 782232, 'country_code' => 'MY', 'name' => 'Selangor', 'active' => 1, 'slug' => 'selangor'],
            ['id' => 782233, 'country_code' => 'MY', 'name' => 'Terengganu', 'active' => 1, 'slug' => 'terengganu']
    	];
    }

    /**
     * Get region cities.
     *
     * @return array
     */
    public function cities()
    {
    	return [
            ['id' => 350647, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Ayer Baloi', 'active' => 1, 'slug' => 'ayer-baloi'],
            ['id' => 350648, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Ayer Hitam', 'active' => 1, 'slug' => 'ayer-hitam'],
            ['id' => 350649, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Batu Anam', 'active' => 1, 'slug' => 'batu-anam'],
            ['id' => 350650, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Bekok', 'active' => 1, 'slug' => 'bekok'],
            ['id' => 350651, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Benut', 'active' => 1, 'slug' => 'benut'],
            ['id' => 350652, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Bukit Gambir', 'active' => 1, 'slug' => 'bukit-gambir'],
            ['id' => 350653, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Bukit Pasir', 'active' => 1, 'slug' => 'bukit-pasir'],
            ['id' => 350654, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Endau', 'active' => 1, 'slug' => 'endau'],
            ['id' => 350655, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Gelang Patah', 'active' => 1, 'slug' => 'gelang-patah'],
            ['id' => 350656, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Gerisek', 'active' => 1, 'slug' => 'gerisek'],
            ['id' => 350657, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Gugusan Taib Andak', 'active' => 1, 'slug' => 'gugusan-taib-andak'],
            ['id' => 350658, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Jementah', 'active' => 1, 'slug' => 'jementah'],
            ['id' => 350659, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Kahang', 'active' => 1, 'slug' => 'kahang'],
            ['id' => 350660, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Kampung Kenangan Tun Dr Ismail', 'active' => 1, 'slug' => 'kampung-kenangan-tun-dr-ismail'],
            ['id' => 350661, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Kukup', 'active' => 1, 'slug' => 'kukup'],
            ['id' => 350662, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Layang Layang', 'active' => 1, 'slug' => 'layang-layang'],
            ['id' => 350663, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Masai', 'active' => 1, 'slug' => 'masai'],
            ['id' => 350664, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Pagoh', 'active' => 1, 'slug' => 'pagoh'],
            ['id' => 350665, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Paloh', 'active' => 1, 'slug' => 'paloh'],
            ['id' => 350666, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Panchor', 'active' => 1, 'slug' => 'panchor'],
            ['id' => 350667, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Parit Jawa', 'active' => 1, 'slug' => 'parit-jawa'],
            ['id' => 350668, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Parit Sulong', 'active' => 1, 'slug' => 'parit-sulong'],
            ['id' => 350669, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Pasir Gudang', 'active' => 1, 'slug' => 'pasir-gudang'],
            ['id' => 350670, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Pengerang', 'active' => 1, 'slug' => 'pengerang'],
            ['id' => 350671, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Plentong', 'active' => 1, 'slug' => 'plentong'],
            ['id' => 350672, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Rengam', 'active' => 1, 'slug' => 'rengam'],
            ['id' => 350673, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Rengit', 'active' => 1, 'slug' => 'rengit'],
            ['id' => 350674, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Semerah', 'active' => 1, 'slug' => 'semerah'],
            ['id' => 350675, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Senggarang', 'active' => 1, 'slug' => 'senggarang'],
            ['id' => 350676, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Seri Gadang', 'active' => 1, 'slug' => 'seri-gadang'],
            ['id' => 350677, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Simpang Rengam', 'active' => 1, 'slug' => 'simpang-rengam'],
            ['id' => 350678, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Sungai Mati', 'active' => 1, 'slug' => 'sungai-mati'],
            ['id' => 350679, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Tampoi', 'active' => 1, 'slug' => 'tampoi'],
            ['id' => 350680, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Chaah', 'active' => 1, 'slug' => 'chaah'],
            ['id' => 350681, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Parit Raja', 'active' => 1, 'slug' => 'parit-raja'],
            ['id' => 350682, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Labis', 'active' => 1, 'slug' => 'labis'],
            ['id' => 350683, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Mersing', 'active' => 1, 'slug' => 'mersing'],
            ['id' => 350684, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Pekan Nanas', 'active' => 1, 'slug' => 'pekan-nanas'],
            ['id' => 350685, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Yong Peng', 'active' => 1, 'slug' => 'yong-peng'],
            ['id' => 350686, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Bakri', 'active' => 1, 'slug' => 'bakri'],
            ['id' => 350687, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Tangkak', 'active' => 1, 'slug' => 'tangkak'],
            ['id' => 350688, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Pontian', 'active' => 1, 'slug' => 'pontian'],
            ['id' => 350689, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Kota Tinggi', 'active' => 1, 'slug' => 'kota-tinggi'],
            ['id' => 350690, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Kulai', 'active' => 1, 'slug' => 'kulai'],
            ['id' => 350691, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Segamat', 'active' => 1, 'slug' => 'segamat'],
            ['id' => 350692, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Senai', 'active' => 1, 'slug' => 'senai'],
            ['id' => 350693, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Ulu Tiram', 'active' => 1, 'slug' => 'ulu-tiram'],
            ['id' => 350694, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Muar', 'active' => 1, 'slug' => 'muar'],
            ['id' => 350695, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Batu Pahat', 'active' => 1, 'slug' => 'batu-pahat'],
            ['id' => 350696, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Skudai', 'active' => 1, 'slug' => 'skudai'],
            ['id' => 350697, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Kluang', 'active' => 1, 'slug' => 'kluang'],
            ['id' => 350698, 'region_id' => 782219, 'country_code' => 'MY', 'name' => 'Johor Bahru', 'active' => 1, 'slug' => 'johor-bahru'],
            ['id' => 350699, 'region_id' => 782220, 'country_code' => 'MY', 'name' => 'Ayer Hitam', 'active' => 1, 'slug' => 'ayer-hitam'],
            ['id' => 350700, 'region_id' => 782220, 'country_code' => 'MY', 'name' => 'Baling', 'active' => 1, 'slug' => 'baling'],
            ['id' => 350701, 'region_id' => 782220, 'country_code' => 'MY', 'name' => 'Bandar Baharu', 'active' => 1, 'slug' => 'bandar-baharu'],
            ['id' => 350702, 'region_id' => 782220, 'country_code' => 'MY', 'name' => 'Bedong', 'active' => 1, 'slug' => 'bedong'],
            ['id' => 350703, 'region_id' => 782220, 'country_code' => 'MY', 'name' => 'Bukit Kayu Hitam', 'active' => 1, 'slug' => 'bukit-kayu-hitam'],
            ['id' => 350704, 'region_id' => 782220, 'country_code' => 'MY', 'name' => 'Guar Chempedak', 'active' => 1, 'slug' => 'guar-chempedak'],
            ['id' => 350705, 'region_id' => 782220, 'country_code' => 'MY', 'name' => 'Karangan', 'active' => 1, 'slug' => 'karangan'],
            ['id' => 350706, 'region_id' => 782220, 'country_code' => 'MY', 'name' => 'Kepala Batas', 'active' => 1, 'slug' => 'kepala-batas'],
            ['id' => 350707, 'region_id' => 782220, 'country_code' => 'MY', 'name' => 'Kodiang', 'active' => 1, 'slug' => 'kodiang'],
            ['id' => 350708, 'region_id' => 782220, 'country_code' => 'MY', 'name' => 'Kota Sarang Semut', 'active' => 1, 'slug' => 'kota-sarang-semut'],
            ['id' => 350709, 'region_id' => 782220, 'country_code' => 'MY', 'name' => 'Kuala Kedah', 'active' => 1, 'slug' => 'kuala-kedah'],
            ['id' => 350710, 'region_id' => 782220, 'country_code' => 'MY', 'name' => 'Kuala Ketil', 'active' => 1, 'slug' => 'kuala-ketil'],
            ['id' => 350711, 'region_id' => 782220, 'country_code' => 'MY', 'name' => 'Kuala Muda', 'active' => 1, 'slug' => 'kuala-muda'],
            ['id' => 350712, 'region_id' => 782220, 'country_code' => 'MY', 'name' => 'Kuala Nerang', 'active' => 1, 'slug' => 'kuala-nerang'],
            ['id' => 350713, 'region_id' => 782220, 'country_code' => 'MY', 'name' => 'Kubang Pasu', 'active' => 1, 'slug' => 'kubang-pasu'],
            ['id' => 350714, 'region_id' => 782220, 'country_code' => 'MY', 'name' => 'Kupang', 'active' => 1, 'slug' => 'kupang'],
            ['id' => 350715, 'region_id' => 782220, 'country_code' => 'MY', 'name' => 'Langgar', 'active' => 1, 'slug' => 'langgar'],
            ['id' => 350716, 'region_id' => 782220, 'country_code' => 'MY', 'name' => 'Lunas', 'active' => 1, 'slug' => 'lunas'],
            ['id' => 350717, 'region_id' => 782220, 'country_code' => 'MY', 'name' => 'Merbok', 'active' => 1, 'slug' => 'merbok'],
            ['id' => 350718, 'region_id' => 782220, 'country_code' => 'MY', 'name' => 'Padang Serai', 'active' => 1, 'slug' => 'padang-serai'],
            ['id' => 350719, 'region_id' => 782220, 'country_code' => 'MY', 'name' => 'Padang Terap', 'active' => 1, 'slug' => 'padang-terap'],
            ['id' => 350720, 'region_id' => 782220, 'country_code' => 'MY', 'name' => 'Pendang', 'active' => 1, 'slug' => 'pendang'],
            ['id' => 350721, 'region_id' => 782220, 'country_code' => 'MY', 'name' => 'Pokok Sena', 'active' => 1, 'slug' => 'pokok-sena'],
            ['id' => 350722, 'region_id' => 782220, 'country_code' => 'MY', 'name' => 'Pulau Langkawi', 'active' => 1, 'slug' => 'pulau-langkawi'],
            ['id' => 350723, 'region_id' => 782220, 'country_code' => 'MY', 'name' => 'Serdang', 'active' => 1, 'slug' => 'serdang'],
            ['id' => 350724, 'region_id' => 782220, 'country_code' => 'MY', 'name' => 'Sik', 'active' => 1, 'slug' => 'sik'],
            ['id' => 350725, 'region_id' => 782220, 'country_code' => 'MY', 'name' => 'Simpang Empat', 'active' => 1, 'slug' => 'simpang-empat'],
            ['id' => 350726, 'region_id' => 782220, 'country_code' => 'MY', 'name' => 'Univesity Utara', 'active' => 1, 'slug' => 'univesity-utara'],
            ['id' => 350727, 'region_id' => 782220, 'country_code' => 'MY', 'name' => 'Yan', 'active' => 1, 'slug' => 'yan'],
            ['id' => 350728, 'region_id' => 782220, 'country_code' => 'MY', 'name' => 'Gurun', 'active' => 1, 'slug' => 'gurun'],
            ['id' => 350729, 'region_id' => 782220, 'country_code' => 'MY', 'name' => 'Langkawi', 'active' => 1, 'slug' => 'langkawi'],
            ['id' => 350730, 'region_id' => 782220, 'country_code' => 'MY', 'name' => 'Jitra', 'active' => 1, 'slug' => 'jitra'],
            ['id' => 350731, 'region_id' => 782220, 'country_code' => 'MY', 'name' => 'Kulim', 'active' => 1, 'slug' => 'kulim'],
            ['id' => 350732, 'region_id' => 782220, 'country_code' => 'MY', 'name' => 'Alor Setar', 'active' => 1, 'slug' => 'alor-setar'],
            ['id' => 350733, 'region_id' => 782220, 'country_code' => 'MY', 'name' => 'Sungai Petani', 'active' => 1, 'slug' => 'sungai-petani'],
            ['id' => 350734, 'region_id' => 782221, 'country_code' => 'MY', 'name' => 'Ayer Lanas', 'active' => 1, 'slug' => 'ayer-lanas'],
            ['id' => 350735, 'region_id' => 782221, 'country_code' => 'MY', 'name' => 'Bachok', 'active' => 1, 'slug' => 'bachok'],
            ['id' => 350736, 'region_id' => 782221, 'country_code' => 'MY', 'name' => 'Cherang Ruku', 'active' => 1, 'slug' => 'cherang-ruku'],
            ['id' => 350737, 'region_id' => 782221, 'country_code' => 'MY', 'name' => 'Dabong', 'active' => 1, 'slug' => 'dabong'],
            ['id' => 350738, 'region_id' => 782221, 'country_code' => 'MY', 'name' => 'Jeli', 'active' => 1, 'slug' => 'jeli'],
            ['id' => 350739, 'region_id' => 782221, 'country_code' => 'MY', 'name' => 'Kem Desa Pahwalan', 'active' => 1, 'slug' => 'kem-desa-pahwalan'],
            ['id' => 350740, 'region_id' => 782221, 'country_code' => 'MY', 'name' => 'Ketereh', 'active' => 1, 'slug' => 'ketereh'],
            ['id' => 350741, 'region_id' => 782221, 'country_code' => 'MY', 'name' => 'Kota Bharu', 'active' => 1, 'slug' => 'kota-bharu'],
            ['id' => 350742, 'region_id' => 782221, 'country_code' => 'MY', 'name' => 'Kuala Balah', 'active' => 1, 'slug' => 'kuala-balah'],
            ['id' => 350743, 'region_id' => 782221, 'country_code' => 'MY', 'name' => 'Kuala Kerai', 'active' => 1, 'slug' => 'kuala-kerai'],
            ['id' => 350744, 'region_id' => 782221, 'country_code' => 'MY', 'name' => 'Machang', 'active' => 1, 'slug' => 'machang'],
            ['id' => 350745, 'region_id' => 782221, 'country_code' => 'MY', 'name' => 'Melor', 'active' => 1, 'slug' => 'melor'],
            ['id' => 350746, 'region_id' => 782221, 'country_code' => 'MY', 'name' => 'Pasir Mas', 'active' => 1, 'slug' => 'pasir-mas'],
            ['id' => 350747, 'region_id' => 782221, 'country_code' => 'MY', 'name' => 'Pasir Puteh', 'active' => 1, 'slug' => 'pasir-puteh'],
            ['id' => 350748, 'region_id' => 782221, 'country_code' => 'MY', 'name' => 'Pulai Chondong', 'active' => 1, 'slug' => 'pulai-chondong'],
            ['id' => 350749, 'region_id' => 782221, 'country_code' => 'MY', 'name' => 'Rantau Panjang', 'active' => 1, 'slug' => 'rantau-panjang'],
            ['id' => 350750, 'region_id' => 782221, 'country_code' => 'MY', 'name' => 'Selising', 'active' => 1, 'slug' => 'selising'],
            ['id' => 350751, 'region_id' => 782221, 'country_code' => 'MY', 'name' => 'Tanah Merah', 'active' => 1, 'slug' => 'tanah-merah'],
            ['id' => 350752, 'region_id' => 782221, 'country_code' => 'MY', 'name' => 'Tawang', 'active' => 1, 'slug' => 'tawang'],
            ['id' => 350753, 'region_id' => 782221, 'country_code' => 'MY', 'name' => 'Temangan', 'active' => 1, 'slug' => 'temangan'],
            ['id' => 350754, 'region_id' => 782221, 'country_code' => 'MY', 'name' => 'Tumpat', 'active' => 1, 'slug' => 'tumpat'],
            ['id' => 350755, 'region_id' => 782221, 'country_code' => 'MY', 'name' => 'Wakaf Baru', 'active' => 1, 'slug' => 'wakaf-baru'],
            ['id' => 350756, 'region_id' => 782221, 'country_code' => 'MY', 'name' => 'Gua Musang', 'active' => 1, 'slug' => 'gua-musang'],
            ['id' => 350757, 'region_id' => 782222, 'country_code' => 'MY', 'name' => 'Kuala Lumpur', 'active' => 1, 'slug' => 'kuala-lumpur'],
            ['id' => 350758, 'region_id' => 782223, 'country_code' => 'MY', 'name' => 'Asahan', 'active' => 1, 'slug' => 'asahan'],
            ['id' => 350759, 'region_id' => 782223, 'country_code' => 'MY', 'name' => 'Bandar Hilir', 'active' => 1, 'slug' => 'bandar-hilir'],
            ['id' => 350760, 'region_id' => 782223, 'country_code' => 'MY', 'name' => 'Bukit Beruam', 'active' => 1, 'slug' => 'bukit-beruam'],
            ['id' => 350761, 'region_id' => 782223, 'country_code' => 'MY', 'name' => 'Durian Tunggal', 'active' => 1, 'slug' => 'durian-tunggal'],
            ['id' => 350762, 'region_id' => 782223, 'country_code' => 'MY', 'name' => 'Jasin', 'active' => 1, 'slug' => 'jasin'],
            ['id' => 350763, 'region_id' => 782223, 'country_code' => 'MY', 'name' => 'Kuala Linggi', 'active' => 1, 'slug' => 'kuala-linggi'],
            ['id' => 350764, 'region_id' => 782223, 'country_code' => 'MY', 'name' => 'Kuala Sungai Baru', 'active' => 1, 'slug' => 'kuala-sungai-baru'],
            ['id' => 350765, 'region_id' => 782223, 'country_code' => 'MY', 'name' => 'Lubok China', 'active' => 1, 'slug' => 'lubok-china'],
            ['id' => 350766, 'region_id' => 782223, 'country_code' => 'MY', 'name' => 'Masjid Tanah', 'active' => 1, 'slug' => 'masjid-tanah'],
            ['id' => 350767, 'region_id' => 782223, 'country_code' => 'MY', 'name' => 'Melaka Tengah', 'active' => 1, 'slug' => 'melaka-tengah'],
            ['id' => 350768, 'region_id' => 782223, 'country_code' => 'MY', 'name' => 'Merlimau', 'active' => 1, 'slug' => 'merlimau'],
            ['id' => 350769, 'region_id' => 782223, 'country_code' => 'MY', 'name' => 'Selandar', 'active' => 1, 'slug' => 'selandar'],
            ['id' => 350770, 'region_id' => 782223, 'country_code' => 'MY', 'name' => 'Sungai Rambai', 'active' => 1, 'slug' => 'sungai-rambai'],
            ['id' => 350771, 'region_id' => 782223, 'country_code' => 'MY', 'name' => 'Tanjong Kling', 'active' => 1, 'slug' => 'tanjong-kling'],
            ['id' => 350772, 'region_id' => 782223, 'country_code' => 'MY', 'name' => 'Ujong Pasir', 'active' => 1, 'slug' => 'ujong-pasir'],
            ['id' => 350773, 'region_id' => 782223, 'country_code' => 'MY', 'name' => 'Bemban', 'active' => 1, 'slug' => 'bemban'],
            ['id' => 350774, 'region_id' => 782223, 'country_code' => 'MY', 'name' => 'Alor Gajah', 'active' => 1, 'slug' => 'alor-gajah'],
            ['id' => 350775, 'region_id' => 782223, 'country_code' => 'MY', 'name' => 'Batu Berendam', 'active' => 1, 'slug' => 'batu-berendam'],
            ['id' => 350776, 'region_id' => 782223, 'country_code' => 'MY', 'name' => 'Sungai Udang', 'active' => 1, 'slug' => 'sungai-udang'],
            ['id' => 350777, 'region_id' => 782223, 'country_code' => 'MY', 'name' => 'Ayer Keroh', 'active' => 1, 'slug' => 'ayer-keroh'],
            ['id' => 350778, 'region_id' => 782224, 'country_code' => 'MY', 'name' => 'Bandar Baru Serting', 'active' => 1, 'slug' => 'bandar-baru-serting'],
            ['id' => 350779, 'region_id' => 782224, 'country_code' => 'MY', 'name' => 'Batang Melaka', 'active' => 1, 'slug' => 'batang-melaka'],
            ['id' => 350780, 'region_id' => 782224, 'country_code' => 'MY', 'name' => 'Batu Kikir', 'active' => 1, 'slug' => 'batu-kikir'],
            ['id' => 350781, 'region_id' => 782224, 'country_code' => 'MY', 'name' => 'Gemas', 'active' => 1, 'slug' => 'gemas'],
            ['id' => 350782, 'region_id' => 782224, 'country_code' => 'MY', 'name' => 'Gemencheh', 'active' => 1, 'slug' => 'gemencheh'],
            ['id' => 350783, 'region_id' => 782224, 'country_code' => 'MY', 'name' => 'Jelebu', 'active' => 1, 'slug' => 'jelebu'],
            ['id' => 350784, 'region_id' => 782224, 'country_code' => 'MY', 'name' => 'Jempol', 'active' => 1, 'slug' => 'jempol'],
            ['id' => 350785, 'region_id' => 782224, 'country_code' => 'MY', 'name' => 'Johol', 'active' => 1, 'slug' => 'johol'],
            ['id' => 350786, 'region_id' => 782224, 'country_code' => 'MY', 'name' => 'Juasseh', 'active' => 1, 'slug' => 'juasseh'],
            ['id' => 350787, 'region_id' => 782224, 'country_code' => 'MY', 'name' => 'Kota', 'active' => 1, 'slug' => 'kota'],
            ['id' => 350788, 'region_id' => 782224, 'country_code' => 'MY', 'name' => 'Kuala Klawang', 'active' => 1, 'slug' => 'kuala-klawang'],
            ['id' => 350789, 'region_id' => 782224, 'country_code' => 'MY', 'name' => 'Labu', 'active' => 1, 'slug' => 'labu'],
            ['id' => 350790, 'region_id' => 782224, 'country_code' => 'MY', 'name' => 'Lenggeng', 'active' => 1, 'slug' => 'lenggeng'],
            ['id' => 350791, 'region_id' => 782224, 'country_code' => 'MY', 'name' => 'Linggi', 'active' => 1, 'slug' => 'linggi'],
            ['id' => 350792, 'region_id' => 782224, 'country_code' => 'MY', 'name' => 'Mantin', 'active' => 1, 'slug' => 'mantin'],
            ['id' => 350793, 'region_id' => 782224, 'country_code' => 'MY', 'name' => 'Nilai', 'active' => 1, 'slug' => 'nilai'],
            ['id' => 350794, 'region_id' => 782224, 'country_code' => 'MY', 'name' => 'Pasir Panjang', 'active' => 1, 'slug' => 'pasir-panjang'],
            ['id' => 350795, 'region_id' => 782224, 'country_code' => 'MY', 'name' => 'Pedas', 'active' => 1, 'slug' => 'pedas'],
            ['id' => 350796, 'region_id' => 782224, 'country_code' => 'MY', 'name' => 'Rantau', 'active' => 1, 'slug' => 'rantau'],
            ['id' => 350797, 'region_id' => 782224, 'country_code' => 'MY', 'name' => 'Rembau', 'active' => 1, 'slug' => 'rembau'],
            ['id' => 350798, 'region_id' => 782224, 'country_code' => 'MY', 'name' => 'Rompin', 'active' => 1, 'slug' => 'rompin'],
            ['id' => 350799, 'region_id' => 782224, 'country_code' => 'MY', 'name' => 'Senawang', 'active' => 1, 'slug' => 'senawang'],
            ['id' => 350800, 'region_id' => 782224, 'country_code' => 'MY', 'name' => 'Siliau', 'active' => 1, 'slug' => 'siliau'],
            ['id' => 350801, 'region_id' => 782224, 'country_code' => 'MY', 'name' => 'Simpang Durian', 'active' => 1, 'slug' => 'simpang-durian'],
            ['id' => 350802, 'region_id' => 782224, 'country_code' => 'MY', 'name' => 'Simpang Pertang', 'active' => 1, 'slug' => 'simpang-pertang'],
            ['id' => 350803, 'region_id' => 782224, 'country_code' => 'MY', 'name' => 'Sri Menanti', 'active' => 1, 'slug' => 'sri-menanti'],
            ['id' => 350804, 'region_id' => 782224, 'country_code' => 'MY', 'name' => 'Sri Rusa', 'active' => 1, 'slug' => 'sri-rusa'],
            ['id' => 350805, 'region_id' => 782224, 'country_code' => 'MY', 'name' => 'Tampin', 'active' => 1, 'slug' => 'tampin'],
            ['id' => 350806, 'region_id' => 782224, 'country_code' => 'MY', 'name' => 'Tanjong Ipoh', 'active' => 1, 'slug' => 'tanjong-ipoh'],
            ['id' => 350807, 'region_id' => 782224, 'country_code' => 'MY', 'name' => 'Kuala Pilah', 'active' => 1, 'slug' => 'kuala-pilah'],
            ['id' => 350808, 'region_id' => 782224, 'country_code' => 'MY', 'name' => 'Bahau', 'active' => 1, 'slug' => 'bahau'],
            ['id' => 350809, 'region_id' => 782224, 'country_code' => 'MY', 'name' => 'Port Dickson', 'active' => 1, 'slug' => 'port-dickson'],
            ['id' => 350810, 'region_id' => 782224, 'country_code' => 'MY', 'name' => 'Seremban', 'active' => 1, 'slug' => 'seremban'],
            ['id' => 350811, 'region_id' => 782225, 'country_code' => 'MY', 'name' => 'Balok', 'active' => 1, 'slug' => 'balok'],
            ['id' => 350812, 'region_id' => 782225, 'country_code' => 'MY', 'name' => 'Bandar Pusat Jengka', 'active' => 1, 'slug' => 'bandar-pusat-jengka'],
            ['id' => 350813, 'region_id' => 782225, 'country_code' => 'MY', 'name' => 'Bandar Tun Abdul Razak', 'active' => 1, 'slug' => 'bandar-tun-abdul-razak'],
            ['id' => 350814, 'region_id' => 782225, 'country_code' => 'MY', 'name' => 'Benta', 'active' => 1, 'slug' => 'benta'],
            ['id' => 350815, 'region_id' => 782225, 'country_code' => 'MY', 'name' => 'Bentong', 'active' => 1, 'slug' => 'bentong'],
            ['id' => 350816, 'region_id' => 782225, 'country_code' => 'MY', 'name' => 'Bera', 'active' => 1, 'slug' => 'bera'],
            ['id' => 350817, 'region_id' => 782225, 'country_code' => 'MY', 'name' => 'Brinchang', 'active' => 1, 'slug' => 'brinchang'],
            ['id' => 350818, 'region_id' => 782225, 'country_code' => 'MY', 'name' => 'Bukit Fraser', 'active' => 1, 'slug' => 'bukit-fraser'],
            ['id' => 350819, 'region_id' => 782225, 'country_code' => 'MY', 'name' => 'Cameron Highlands', 'active' => 1, 'slug' => 'cameron-highlands'],
            ['id' => 350820, 'region_id' => 782225, 'country_code' => 'MY', 'name' => 'Chenor', 'active' => 1, 'slug' => 'chenor'],
            ['id' => 350821, 'region_id' => 782225, 'country_code' => 'MY', 'name' => 'Daerah Rompin', 'active' => 1, 'slug' => 'daerah-rompin'],
            ['id' => 350822, 'region_id' => 782225, 'country_code' => 'MY', 'name' => 'Damak', 'active' => 1, 'slug' => 'damak'],
            ['id' => 350823, 'region_id' => 782225, 'country_code' => 'MY', 'name' => 'Dong', 'active' => 1, 'slug' => 'dong'],
            ['id' => 350824, 'region_id' => 782225, 'country_code' => 'MY', 'name' => 'Genting Highlands', 'active' => 1, 'slug' => 'genting-highlands'],
            ['id' => 350825, 'region_id' => 782225, 'country_code' => 'MY', 'name' => 'Karak', 'active' => 1, 'slug' => 'karak'],
            ['id' => 350826, 'region_id' => 782225, 'country_code' => 'MY', 'name' => 'Kuala Rompin', 'active' => 1, 'slug' => 'kuala-rompin'],
            ['id' => 350827, 'region_id' => 782225, 'country_code' => 'MY', 'name' => 'Lanchang', 'active' => 1, 'slug' => 'lanchang'],
            ['id' => 350828, 'region_id' => 782225, 'country_code' => 'MY', 'name' => 'Lurah Bilut', 'active' => 1, 'slug' => 'lurah-bilut'],
            ['id' => 350829, 'region_id' => 782225, 'country_code' => 'MY', 'name' => 'Maran', 'active' => 1, 'slug' => 'maran'],
            ['id' => 350830, 'region_id' => 782225, 'country_code' => 'MY', 'name' => 'Mengkarak', 'active' => 1, 'slug' => 'mengkarak'],
            ['id' => 350831, 'region_id' => 782225, 'country_code' => 'MY', 'name' => 'Muadzam Shah', 'active' => 1, 'slug' => 'muadzam-shah'],
            ['id' => 350832, 'region_id' => 782225, 'country_code' => 'MY', 'name' => 'Padang Tengku', 'active' => 1, 'slug' => 'padang-tengku'],
            ['id' => 350833, 'region_id' => 782225, 'country_code' => 'MY', 'name' => 'Ringlet', 'active' => 1, 'slug' => 'ringlet'],
            ['id' => 350834, 'region_id' => 782225, 'country_code' => 'MY', 'name' => 'Rompin', 'active' => 1, 'slug' => 'rompin'],
            ['id' => 350835, 'region_id' => 782225, 'country_code' => 'MY', 'name' => 'Sega', 'active' => 1, 'slug' => 'sega'],
            ['id' => 350836, 'region_id' => 782225, 'country_code' => 'MY', 'name' => 'Sungai Koyan', 'active' => 1, 'slug' => 'sungai-koyan'],
            ['id' => 350837, 'region_id' => 782225, 'country_code' => 'MY', 'name' => 'Sungai Lembing', 'active' => 1, 'slug' => 'sungai-lembing'],
            ['id' => 350838, 'region_id' => 782225, 'country_code' => 'MY', 'name' => 'Sungai Ruan', 'active' => 1, 'slug' => 'sungai-ruan'],
            ['id' => 350839, 'region_id' => 782225, 'country_code' => 'MY', 'name' => 'Triang', 'active' => 1, 'slug' => 'triang'],
            ['id' => 350840, 'region_id' => 782225, 'country_code' => 'MY', 'name' => 'Tanah Rata', 'active' => 1, 'slug' => 'tanah-rata'],
            ['id' => 350841, 'region_id' => 782225, 'country_code' => 'MY', 'name' => 'Kuala Lipis', 'active' => 1, 'slug' => 'kuala-lipis'],
            ['id' => 350842, 'region_id' => 782225, 'country_code' => 'MY', 'name' => 'Pekan', 'active' => 1, 'slug' => 'pekan'],
            ['id' => 350843, 'region_id' => 782225, 'country_code' => 'MY', 'name' => 'Jerantut', 'active' => 1, 'slug' => 'jerantut'],
            ['id' => 350844, 'region_id' => 782225, 'country_code' => 'MY', 'name' => 'Raub', 'active' => 1, 'slug' => 'raub'],
            ['id' => 350845, 'region_id' => 782225, 'country_code' => 'MY', 'name' => 'Mentakab', 'active' => 1, 'slug' => 'mentakab'],
            ['id' => 350846, 'region_id' => 782225, 'country_code' => 'MY', 'name' => 'Temerloh', 'active' => 1, 'slug' => 'temerloh'],
            ['id' => 350847, 'region_id' => 782225, 'country_code' => 'MY', 'name' => 'Kuantan', 'active' => 1, 'slug' => 'kuantan'],
            ['id' => 350848, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Air Tawar', 'active' => 1, 'slug' => 'air-tawar'],
            ['id' => 350849, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Alma', 'active' => 1, 'slug' => 'alma'],
            ['id' => 350850, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Ayer Itam', 'active' => 1, 'slug' => 'ayer-itam'],
            ['id' => 350851, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Bagan Ajam', 'active' => 1, 'slug' => 'bagan-ajam'],
            ['id' => 350852, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Bagan Jermal', 'active' => 1, 'slug' => 'bagan-jermal'],
            ['id' => 350853, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Bagan Lallang', 'active' => 1, 'slug' => 'bagan-lallang'],
            ['id' => 350854, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Balik Pulau', 'active' => 1, 'slug' => 'balik-pulau'],
            ['id' => 350855, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Bandar Perda', 'active' => 1, 'slug' => 'bandar-perda'],
            ['id' => 350856, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Batu Feringgi', 'active' => 1, 'slug' => 'batu-feringgi'],
            ['id' => 350857, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Batu Kawan', 'active' => 1, 'slug' => 'batu-kawan'],
            ['id' => 350858, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Batu Maung', 'active' => 1, 'slug' => 'batu-maung'],
            ['id' => 350859, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Batu Uban', 'active' => 1, 'slug' => 'batu-uban'],
            ['id' => 350860, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Bayan Baru', 'active' => 1, 'slug' => 'bayan-baru'],
            ['id' => 350861, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Bayan Lepas', 'active' => 1, 'slug' => 'bayan-lepas'],
            ['id' => 350862, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Berapit', 'active' => 1, 'slug' => 'berapit'],
            ['id' => 350863, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Bertam', 'active' => 1, 'slug' => 'bertam'],
            ['id' => 350864, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Bukit Dumbar', 'active' => 1, 'slug' => 'bukit-dumbar'],
            ['id' => 350865, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Bukit Jambul', 'active' => 1, 'slug' => 'bukit-jambul'],
            ['id' => 350866, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Bukit Minyak', 'active' => 1, 'slug' => 'bukit-minyak'],
            ['id' => 350867, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Bukit Tambun', 'active' => 1, 'slug' => 'bukit-tambun'],
            ['id' => 350868, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Bukit Tengah', 'active' => 1, 'slug' => 'bukit-tengah'],
            ['id' => 350869, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Gelugor', 'active' => 1, 'slug' => 'gelugor'],
            ['id' => 350870, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Gertak Sangul', 'active' => 1, 'slug' => 'gertak-sangul'],
            ['id' => 350871, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Greenlane', 'active' => 1, 'slug' => 'greenlane'],
            ['id' => 350872, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Jawi', 'active' => 1, 'slug' => 'jawi'],
            ['id' => 350873, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Jelutong', 'active' => 1, 'slug' => 'jelutong'],
            ['id' => 350874, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Kepala Batas', 'active' => 1, 'slug' => 'kepala-batas'],
            ['id' => 350875, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Kubang Semang', 'active' => 1, 'slug' => 'kubang-semang'],
            ['id' => 350876, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Mak Mandin', 'active' => 1, 'slug' => 'mak-mandin'],
            ['id' => 350877, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Minden Heights', 'active' => 1, 'slug' => 'minden-heights'],
            ['id' => 350878, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Pauh Jaya', 'active' => 1, 'slug' => 'pauh-jaya'],
            ['id' => 350879, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Paya Terubong', 'active' => 1, 'slug' => 'paya-terubong'],
            ['id' => 350880, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Penaga', 'active' => 1, 'slug' => 'penaga'],
            ['id' => 350881, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Penang Hill', 'active' => 1, 'slug' => 'penang-hill'],
            ['id' => 350882, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Penanti', 'active' => 1, 'slug' => 'penanti'],
            ['id' => 350883, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Perai', 'active' => 1, 'slug' => 'perai'],
            ['id' => 350884, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Permatang Pauh', 'active' => 1, 'slug' => 'permatang-pauh'],
            ['id' => 350885, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Permatang Tinggi', 'active' => 1, 'slug' => 'permatang-tinggi'],
            ['id' => 350886, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Persiaran Gurney', 'active' => 1, 'slug' => 'persiaran-gurney'],
            ['id' => 350887, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Prai', 'active' => 1, 'slug' => 'prai'],
            ['id' => 350888, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Pulau Betong', 'active' => 1, 'slug' => 'pulau-betong'],
            ['id' => 350889, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Pulau Tikus', 'active' => 1, 'slug' => 'pulau-tikus'],
            ['id' => 350890, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Raja Uda', 'active' => 1, 'slug' => 'raja-uda'],
            ['id' => 350891, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Relau', 'active' => 1, 'slug' => 'relau'],
            ['id' => 350892, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Scotland', 'active' => 1, 'slug' => 'scotland'],
            ['id' => 350893, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Seberang Jaya', 'active' => 1, 'slug' => 'seberang-jaya'],
            ['id' => 350894, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Seberang Perai', 'active' => 1, 'slug' => 'seberang-perai'],
            ['id' => 350895, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Serdang', 'active' => 1, 'slug' => 'serdang'],
            ['id' => 350896, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Simpang Ampat', 'active' => 1, 'slug' => 'simpang-ampat'],
            ['id' => 350897, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Sungai Ara', 'active' => 1, 'slug' => 'sungai-ara'],
            ['id' => 350898, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Sungai Bakap', 'active' => 1, 'slug' => 'sungai-bakap'],
            ['id' => 350899, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Sungai Dua', 'active' => 1, 'slug' => 'sungai-dua'],
            ['id' => 350900, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Sungai Jawi', 'active' => 1, 'slug' => 'sungai-jawi'],
            ['id' => 350901, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Sungai Nibong', 'active' => 1, 'slug' => 'sungai-nibong'],
            ['id' => 350902, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Sungai Pinang', 'active' => 1, 'slug' => 'sungai-pinang'],
            ['id' => 350903, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Tanjung Bungah', 'active' => 1, 'slug' => 'tanjung-bungah'],
            ['id' => 350904, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Teluk Bahang', 'active' => 1, 'slug' => 'teluk-bahang'],
            ['id' => 350905, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Teluk Kumbar', 'active' => 1, 'slug' => 'teluk-kumbar'],
            ['id' => 350906, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'USM', 'active' => 1, 'slug' => 'usm'],
            ['id' => 350907, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Valdor', 'active' => 1, 'slug' => 'valdor'],
            ['id' => 350908, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Juru', 'active' => 1, 'slug' => 'juru'],
            ['id' => 350909, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Tanjong Tokong', 'active' => 1, 'slug' => 'tanjong-tokong'],
            ['id' => 350910, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Permatang Kuching', 'active' => 1, 'slug' => 'permatang-kuching'],
            ['id' => 350911, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Nibong Tebal', 'active' => 1, 'slug' => 'nibong-tebal'],
            ['id' => 350912, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Butterworth', 'active' => 1, 'slug' => 'butterworth'],
            ['id' => 350913, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Tasek Gelugor', 'active' => 1, 'slug' => 'tasek-gelugor'],
            ['id' => 350914, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Bukit Mertajam', 'active' => 1, 'slug' => 'bukit-mertajam'],
            ['id' => 350915, 'region_id' => 782226, 'country_code' => 'MY', 'name' => 'Georgetown', 'active' => 1, 'slug' => 'georgetown'],
            ['id' => 350916, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Ayer Tawar', 'active' => 1, 'slug' => 'ayer-tawar'],
            ['id' => 350917, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Bagan Datoh', 'active' => 1, 'slug' => 'bagan-datoh'],
            ['id' => 350918, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Bagan Serai', 'active' => 1, 'slug' => 'bagan-serai'],
            ['id' => 350919, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Batu Kurau', 'active' => 1, 'slug' => 'batu-kurau'],
            ['id' => 350920, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Behrang Stesen', 'active' => 1, 'slug' => 'behrang-stesen'],
            ['id' => 350921, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Beruas', 'active' => 1, 'slug' => 'beruas'],
            ['id' => 350922, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Bota', 'active' => 1, 'slug' => 'bota'],
            ['id' => 350923, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Changkat Jering', 'active' => 1, 'slug' => 'changkat-jering'],
            ['id' => 350924, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Changkat Keruing', 'active' => 1, 'slug' => 'changkat-keruing'],
            ['id' => 350925, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Chemor', 'active' => 1, 'slug' => 'chemor'],
            ['id' => 350926, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Chenderiang', 'active' => 1, 'slug' => 'chenderiang'],
            ['id' => 350927, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Chenderong Balai', 'active' => 1, 'slug' => 'chenderong-balai'],
            ['id' => 350928, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Chikus', 'active' => 1, 'slug' => 'chikus'],
            ['id' => 350929, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Enggor', 'active' => 1, 'slug' => 'enggor'],
            ['id' => 350930, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Gerik', 'active' => 1, 'slug' => 'gerik'],
            ['id' => 350931, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Gopeng', 'active' => 1, 'slug' => 'gopeng'],
            ['id' => 350932, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Hutan Melintang', 'active' => 1, 'slug' => 'hutan-melintang'],
            ['id' => 350933, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Intan', 'active' => 1, 'slug' => 'intan'],
            ['id' => 350934, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Ipoh', 'active' => 1, 'slug' => 'ipoh'],
            ['id' => 350935, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Jeram', 'active' => 1, 'slug' => 'jeram'],
            ['id' => 350936, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Kampong Gajah', 'active' => 1, 'slug' => 'kampong-gajah'],
            ['id' => 350937, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Kampong Kepayang', 'active' => 1, 'slug' => 'kampong-kepayang'],
            ['id' => 350938, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Kamunting', 'active' => 1, 'slug' => 'kamunting'],
            ['id' => 350939, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Kuala Kurau', 'active' => 1, 'slug' => 'kuala-kurau'],
            ['id' => 350940, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Kuala Sepetang', 'active' => 1, 'slug' => 'kuala-sepetang'],
            ['id' => 350941, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Lahat', 'active' => 1, 'slug' => 'lahat'],
            ['id' => 350942, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Lambor Kanan', 'active' => 1, 'slug' => 'lambor-kanan'],
            ['id' => 350943, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Langkap', 'active' => 1, 'slug' => 'langkap'],
            ['id' => 350944, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Lenggong', 'active' => 1, 'slug' => 'lenggong'],
            ['id' => 350945, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Lumut', 'active' => 1, 'slug' => 'lumut'],
            ['id' => 350946, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Malim Nawar', 'active' => 1, 'slug' => 'malim-nawar'],
            ['id' => 350947, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Mambang Diawan', 'active' => 1, 'slug' => 'mambang-diawan'],
            ['id' => 350948, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Manong', 'active' => 1, 'slug' => 'manong'],
            ['id' => 350949, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Matang', 'active' => 1, 'slug' => 'matang'],
            ['id' => 350950, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Menglembu', 'active' => 1, 'slug' => 'menglembu'],
            ['id' => 350951, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Padang Rengas', 'active' => 1, 'slug' => 'padang-rengas'],
            ['id' => 350952, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Pangkor', 'active' => 1, 'slug' => 'pangkor'],
            ['id' => 350953, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Parit', 'active' => 1, 'slug' => 'parit'],
            ['id' => 350954, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Pengkalan Hulu', 'active' => 1, 'slug' => 'pengkalan-hulu'],
            ['id' => 350955, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Pusing', 'active' => 1, 'slug' => 'pusing'],
            ['id' => 350956, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Rantau Panjang', 'active' => 1, 'slug' => 'rantau-panjang'],
            ['id' => 350957, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Sauk', 'active' => 1, 'slug' => 'sauk'],
            ['id' => 350958, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Selama', 'active' => 1, 'slug' => 'selama'],
            ['id' => 350959, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Selekoh', 'active' => 1, 'slug' => 'selekoh'],
            ['id' => 350960, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Selinsing', 'active' => 1, 'slug' => 'selinsing'],
            ['id' => 350961, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Seri Manjong', 'active' => 1, 'slug' => 'seri-manjong'],
            ['id' => 350962, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Simpang', 'active' => 1, 'slug' => 'simpang'],
            ['id' => 350963, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Sitiawan', 'active' => 1, 'slug' => 'sitiawan'],
            ['id' => 350964, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Slim River', 'active' => 1, 'slug' => 'slim-river'],
            ['id' => 350965, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Sungai Siput', 'active' => 1, 'slug' => 'sungai-siput'],
            ['id' => 350966, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Sungai Sumun', 'active' => 1, 'slug' => 'sungai-sumun'],
            ['id' => 350967, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Sungkai', 'active' => 1, 'slug' => 'sungkai'],
            ['id' => 350968, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Tanjong Piandang', 'active' => 1, 'slug' => 'tanjong-piandang'],
            ['id' => 350969, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Tanjong Rambutan', 'active' => 1, 'slug' => 'tanjong-rambutan'],
            ['id' => 350970, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Tanjong Tualang', 'active' => 1, 'slug' => 'tanjong-tualang'],
            ['id' => 350971, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Tanjung Malim', 'active' => 1, 'slug' => 'tanjung-malim'],
            ['id' => 350972, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Tapah', 'active' => 1, 'slug' => 'tapah'],
            ['id' => 350973, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Temoh', 'active' => 1, 'slug' => 'temoh'],
            ['id' => 350974, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'TLDM Lumut', 'active' => 1, 'slug' => 'tldm-lumut'],
            ['id' => 350975, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Trolak', 'active' => 1, 'slug' => 'trolak'],
            ['id' => 350976, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Trong', 'active' => 1, 'slug' => 'trong'],
            ['id' => 350977, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Tronoh', 'active' => 1, 'slug' => 'tronoh'],
            ['id' => 350978, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Ulu Bernam', 'active' => 1, 'slug' => 'ulu-bernam'],
            ['id' => 350979, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Ulu Kinta', 'active' => 1, 'slug' => 'ulu-kinta'],
            ['id' => 350980, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Pantai Remis', 'active' => 1, 'slug' => 'pantai-remis'],
            ['id' => 350981, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Kampar', 'active' => 1, 'slug' => 'kampar'],
            ['id' => 350982, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Parit Buntar', 'active' => 1, 'slug' => 'parit-buntar'],
            ['id' => 350983, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Bidor', 'active' => 1, 'slug' => 'bidor'],
            ['id' => 350984, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Kuala Kangsar', 'active' => 1, 'slug' => 'kuala-kangsar'],
            ['id' => 350985, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Batu Gajah', 'active' => 1, 'slug' => 'batu-gajah'],
            ['id' => 350986, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Semanggol', 'active' => 1, 'slug' => 'semanggol'],
            ['id' => 350987, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Teluk Intan', 'active' => 1, 'slug' => 'teluk-intan'],
            ['id' => 350988, 'region_id' => 782227, 'country_code' => 'MY', 'name' => 'Taiping', 'active' => 1, 'slug' => 'taiping'],
            ['id' => 350989, 'region_id' => 782228, 'country_code' => 'MY', 'name' => 'Arau', 'active' => 1, 'slug' => 'arau'],
            ['id' => 350990, 'region_id' => 782228, 'country_code' => 'MY', 'name' => 'Kaki Bukit', 'active' => 1, 'slug' => 'kaki-bukit'],
            ['id' => 350991, 'region_id' => 782228, 'country_code' => 'MY', 'name' => 'Padang Besar', 'active' => 1, 'slug' => 'padang-besar'],
            ['id' => 350992, 'region_id' => 782228, 'country_code' => 'MY', 'name' => 'Pauh', 'active' => 1, 'slug' => 'pauh'],
            ['id' => 350993, 'region_id' => 782228, 'country_code' => 'MY', 'name' => 'Simpang Ampat', 'active' => 1, 'slug' => 'simpang-ampat'],
            ['id' => 350994, 'region_id' => 782228, 'country_code' => 'MY', 'name' => 'Kuala Perlis', 'active' => 1, 'slug' => 'kuala-perlis'],
            ['id' => 350995, 'region_id' => 782228, 'country_code' => 'MY', 'name' => 'Kangar', 'active' => 1, 'slug' => 'kangar'],
            ['id' => 350996, 'region_id' => 782229, 'country_code' => 'MY', 'name' => 'Cyberjaya', 'active' => 1, 'slug' => 'cyberjaya'],
            ['id' => 350997, 'region_id' => 782229, 'country_code' => 'MY', 'name' => 'Putrajaya', 'active' => 1, 'slug' => 'putrajaya'],
            ['id' => 350998, 'region_id' => 782230, 'country_code' => 'MY', 'name' => 'Beluran', 'active' => 1, 'slug' => 'beluran'],
            ['id' => 350999, 'region_id' => 782230, 'country_code' => 'MY', 'name' => 'Bongawan', 'active' => 1, 'slug' => 'bongawan'],
            ['id' => 351000, 'region_id' => 782230, 'country_code' => 'MY', 'name' => 'Kota Kinabatangan', 'active' => 1, 'slug' => 'kota-kinabatangan'],
            ['id' => 351001, 'region_id' => 782230, 'country_code' => 'MY', 'name' => 'Kota Marudu', 'active' => 1, 'slug' => 'kota-marudu'],
            ['id' => 351002, 'region_id' => 782230, 'country_code' => 'MY', 'name' => 'Kuala Penyu', 'active' => 1, 'slug' => 'kuala-penyu'],
            ['id' => 351003, 'region_id' => 782230, 'country_code' => 'MY', 'name' => 'Kunak', 'active' => 1, 'slug' => 'kunak'],
            ['id' => 351004, 'region_id' => 782230, 'country_code' => 'MY', 'name' => 'Likas', 'active' => 1, 'slug' => 'likas'],
            ['id' => 351005, 'region_id' => 782230, 'country_code' => 'MY', 'name' => 'Membakut', 'active' => 1, 'slug' => 'membakut'],
            ['id' => 351006, 'region_id' => 782230, 'country_code' => 'MY', 'name' => 'Menumbok', 'active' => 1, 'slug' => 'menumbok'],
            ['id' => 351007, 'region_id' => 782230, 'country_code' => 'MY', 'name' => 'Nabawan', 'active' => 1, 'slug' => 'nabawan'],
            ['id' => 351008, 'region_id' => 782230, 'country_code' => 'MY', 'name' => 'Pamol', 'active' => 1, 'slug' => 'pamol'],
            ['id' => 351009, 'region_id' => 782230, 'country_code' => 'MY', 'name' => 'Penampang', 'active' => 1, 'slug' => 'penampang'],
            ['id' => 351010, 'region_id' => 782230, 'country_code' => 'MY', 'name' => 'Pitas', 'active' => 1, 'slug' => 'pitas'],
            ['id' => 351011, 'region_id' => 782230, 'country_code' => 'MY', 'name' => 'Pulatan', 'active' => 1, 'slug' => 'pulatan'],
            ['id' => 351012, 'region_id' => 782230, 'country_code' => 'MY', 'name' => 'Sipitang', 'active' => 1, 'slug' => 'sipitang'],
            ['id' => 351013, 'region_id' => 782230, 'country_code' => 'MY', 'name' => 'Tambunan', 'active' => 1, 'slug' => 'tambunan'],
            ['id' => 351014, 'region_id' => 782230, 'country_code' => 'MY', 'name' => 'Tamparuli', 'active' => 1, 'slug' => 'tamparuli'],
            ['id' => 351015, 'region_id' => 782230, 'country_code' => 'MY', 'name' => 'Tawau', 'active' => 1, 'slug' => 'tawau'],
            ['id' => 351016, 'region_id' => 782230, 'country_code' => 'MY', 'name' => 'Tenom', 'active' => 1, 'slug' => 'tenom'],
            ['id' => 351017, 'region_id' => 782230, 'country_code' => 'MY', 'name' => 'Tuaran', 'active' => 1, 'slug' => 'tuaran'],
            ['id' => 351018, 'region_id' => 782230, 'country_code' => 'MY', 'name' => 'Kota Belud', 'active' => 1, 'slug' => 'kota-belud'],
            ['id' => 351019, 'region_id' => 782230, 'country_code' => 'MY', 'name' => 'Beaufort', 'active' => 1, 'slug' => 'beaufort'],
            ['id' => 351020, 'region_id' => 782230, 'country_code' => 'MY', 'name' => 'Papar', 'active' => 1, 'slug' => 'papar'],
            ['id' => 351021, 'region_id' => 782230, 'country_code' => 'MY', 'name' => 'Ranau', 'active' => 1, 'slug' => 'ranau'],
            ['id' => 351022, 'region_id' => 782230, 'country_code' => 'MY', 'name' => 'Kudat', 'active' => 1, 'slug' => 'kudat'],
            ['id' => 351023, 'region_id' => 782230, 'country_code' => 'MY', 'name' => 'Semporna', 'active' => 1, 'slug' => 'semporna'],
            ['id' => 351024, 'region_id' => 782230, 'country_code' => 'MY', 'name' => 'Keningau', 'active' => 1, 'slug' => 'keningau'],
            ['id' => 351025, 'region_id' => 782230, 'country_code' => 'MY', 'name' => 'Lahad Datu', 'active' => 1, 'slug' => 'lahad-datu'],
            ['id' => 351026, 'region_id' => 782230, 'country_code' => 'MY', 'name' => 'Sandakan', 'active' => 1, 'slug' => 'sandakan'],
            ['id' => 351027, 'region_id' => 782230, 'country_code' => 'MY', 'name' => 'Kota Kinabalu', 'active' => 1, 'slug' => 'kota-kinabalu'],
            ['id' => 351028, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Asajaya', 'active' => 1, 'slug' => 'asajaya'],
            ['id' => 351029, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Balingian', 'active' => 1, 'slug' => 'balingian'],
            ['id' => 351030, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Baram', 'active' => 1, 'slug' => 'baram'],
            ['id' => 351031, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Bau', 'active' => 1, 'slug' => 'bau'],
            ['id' => 351032, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Bekenu', 'active' => 1, 'slug' => 'bekenu'],
            ['id' => 351033, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Belaga', 'active' => 1, 'slug' => 'belaga'],
            ['id' => 351034, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Belawai', 'active' => 1, 'slug' => 'belawai'],
            ['id' => 351035, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Betong', 'active' => 1, 'slug' => 'betong'],
            ['id' => 351036, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Bintagor', 'active' => 1, 'slug' => 'bintagor'],
            ['id' => 351037, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Dalat', 'active' => 1, 'slug' => 'dalat'],
            ['id' => 351038, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Daro', 'active' => 1, 'slug' => 'daro'],
            ['id' => 351039, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Debak', 'active' => 1, 'slug' => 'debak'],
            ['id' => 351040, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Engkilili', 'active' => 1, 'slug' => 'engkilili'],
            ['id' => 351041, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Julau', 'active' => 1, 'slug' => 'julau'],
            ['id' => 351042, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Kabong', 'active' => 1, 'slug' => 'kabong'],
            ['id' => 351043, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Kanowit', 'active' => 1, 'slug' => 'kanowit'],
            ['id' => 351044, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Kota Samarahan', 'active' => 1, 'slug' => 'kota-samarahan'],
            ['id' => 351045, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Kuching', 'active' => 1, 'slug' => 'kuching'],
            ['id' => 351046, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Lawas', 'active' => 1, 'slug' => 'lawas'],
            ['id' => 351047, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Lingga', 'active' => 1, 'slug' => 'lingga'],
            ['id' => 351048, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Long Lama', 'active' => 1, 'slug' => 'long-lama'],
            ['id' => 351049, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Lubok Antu', 'active' => 1, 'slug' => 'lubok-antu'],
            ['id' => 351050, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Lundu', 'active' => 1, 'slug' => 'lundu'],
            ['id' => 351051, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Lutong', 'active' => 1, 'slug' => 'lutong'],
            ['id' => 351052, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Maradong', 'active' => 1, 'slug' => 'maradong'],
            ['id' => 351053, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Marudi', 'active' => 1, 'slug' => 'marudi'],
            ['id' => 351054, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Matu', 'active' => 1, 'slug' => 'matu'],
            ['id' => 351055, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Mukah', 'active' => 1, 'slug' => 'mukah'],
            ['id' => 351056, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Nanga Medamit', 'active' => 1, 'slug' => 'nanga-medamit'],
            ['id' => 351057, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Niah', 'active' => 1, 'slug' => 'niah'],
            ['id' => 351058, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Pusa', 'active' => 1, 'slug' => 'pusa'],
            ['id' => 351059, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Roban', 'active' => 1, 'slug' => 'roban'],
            ['id' => 351060, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Saratok', 'active' => 1, 'slug' => 'saratok'],
            ['id' => 351061, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Sebauh', 'active' => 1, 'slug' => 'sebauh'],
            ['id' => 351062, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Sebuyau', 'active' => 1, 'slug' => 'sebuyau'],
            ['id' => 351063, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Serian', 'active' => 1, 'slug' => 'serian'],
            ['id' => 351064, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Simunjan', 'active' => 1, 'slug' => 'simunjan'],
            ['id' => 351065, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Song', 'active' => 1, 'slug' => 'song'],
            ['id' => 351066, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Spaoh', 'active' => 1, 'slug' => 'spaoh'],
            ['id' => 351067, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Sundar', 'active' => 1, 'slug' => 'sundar'],
            ['id' => 351068, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Tanjung Kidurong', 'active' => 1, 'slug' => 'tanjung-kidurong'],
            ['id' => 351069, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Tatau', 'active' => 1, 'slug' => 'tatau'],
            ['id' => 351070, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Kapit', 'active' => 1, 'slug' => 'kapit'],
            ['id' => 351071, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Limbang', 'active' => 1, 'slug' => 'limbang'],
            ['id' => 351072, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Sri Aman', 'active' => 1, 'slug' => 'sri-aman'],
            ['id' => 351073, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Sarikei', 'active' => 1, 'slug' => 'sarikei'],
            ['id' => 351074, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Bintulu', 'active' => 1, 'slug' => 'bintulu'],
            ['id' => 351075, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Sibu', 'active' => 1, 'slug' => 'sibu'],
            ['id' => 351076, 'region_id' => 782231, 'country_code' => 'MY', 'name' => 'Miri', 'active' => 1, 'slug' => 'miri'],
            ['id' => 351077, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Ampang', 'active' => 1, 'slug' => 'ampang'],
            ['id' => 351078, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Ara Damansara', 'active' => 1, 'slug' => 'ara-damansara'],
            ['id' => 351079, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Balakong', 'active' => 1, 'slug' => 'balakong'],
            ['id' => 351080, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Bandar Bukit Raja', 'active' => 1, 'slug' => 'bandar-bukit-raja'],
            ['id' => 351081, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Bandar Kinrara', 'active' => 1, 'slug' => 'bandar-kinrara'],
            ['id' => 351082, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Bandar Puteri', 'active' => 1, 'slug' => 'bandar-puteri'],
            ['id' => 351083, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Bandar Sunway', 'active' => 1, 'slug' => 'bandar-sunway'],
            ['id' => 351084, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Bandar Utama', 'active' => 1, 'slug' => 'bandar-utama'],
            ['id' => 351085, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Bangi', 'active' => 1, 'slug' => 'bangi'],
            ['id' => 351086, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Banting', 'active' => 1, 'slug' => 'banting'],
            ['id' => 351087, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Batang Kali', 'active' => 1, 'slug' => 'batang-kali'],
            ['id' => 351088, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Batu Caves', 'active' => 1, 'slug' => 'batu-caves'],
            ['id' => 351089, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Bukit Rotan', 'active' => 1, 'slug' => 'bukit-rotan'],
            ['id' => 351090, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Cheras', 'active' => 1, 'slug' => 'cheras'],
            ['id' => 351091, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Country Heights', 'active' => 1, 'slug' => 'country-heights'],
            ['id' => 351092, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Cyberjaya', 'active' => 1, 'slug' => 'cyberjaya'],
            ['id' => 351093, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Damansara Damai', 'active' => 1, 'slug' => 'damansara-damai'],
            ['id' => 351094, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Damansara Intan', 'active' => 1, 'slug' => 'damansara-intan'],
            ['id' => 351095, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Damansara Jaya', 'active' => 1, 'slug' => 'damansara-jaya'],
            ['id' => 351096, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Damansara Kim', 'active' => 1, 'slug' => 'damansara-kim'],
            ['id' => 351097, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Damansara Perdana', 'active' => 1, 'slug' => 'damansara-perdana'],
            ['id' => 351098, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Damansara Utama', 'active' => 1, 'slug' => 'damansara-utama'],
            ['id' => 351099, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Dengkil', 'active' => 1, 'slug' => 'dengkil'],
            ['id' => 351100, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Glenmarie', 'active' => 1, 'slug' => 'glenmarie'],
            ['id' => 351101, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Hulu Langat', 'active' => 1, 'slug' => 'hulu-langat'],
            ['id' => 351102, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Hulu Selangor', 'active' => 1, 'slug' => 'hulu-selangor'],
            ['id' => 351103, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Kajang', 'active' => 1, 'slug' => 'kajang'],
            ['id' => 351104, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Kapar', 'active' => 1, 'slug' => 'kapar'],
            ['id' => 351105, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Kayu Ara', 'active' => 1, 'slug' => 'kayu-ara'],
            ['id' => 351106, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Kelana Jaya', 'active' => 1, 'slug' => 'kelana-jaya'],
            ['id' => 351107, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Kerling', 'active' => 1, 'slug' => 'kerling'],
            ['id' => 351108, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Kota Damansara', 'active' => 1, 'slug' => 'kota-damansara'],
            ['id' => 351109, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Kota Kemuning', 'active' => 1, 'slug' => 'kota-kemuning'],
            ['id' => 351110, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Kuala Kubu Baru', 'active' => 1, 'slug' => 'kuala-kubu-baru'],
            ['id' => 351111, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Kuala Langat', 'active' => 1, 'slug' => 'kuala-langat'],
            ['id' => 351112, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Mutiara Damansara', 'active' => 1, 'slug' => 'mutiara-damansara'],
            ['id' => 351113, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Nilai', 'active' => 1, 'slug' => 'nilai'],
            ['id' => 351114, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Port Klang', 'active' => 1, 'slug' => 'port-klang'],
            ['id' => 351115, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Puchong', 'active' => 1, 'slug' => 'puchong'],
            ['id' => 351116, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Pulau  Indah ( Pulau Lumut)', 'active' => 1, 'slug' => 'pulau-indah-pulau-lumut'],
            ['id' => 351117, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Pulau Carey', 'active' => 1, 'slug' => 'pulau-carey'],
            ['id' => 351118, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Pulau Ketam', 'active' => 1, 'slug' => 'pulau-ketam'],
            ['id' => 351119, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Puncak Jalil', 'active' => 1, 'slug' => 'puncak-jalil'],
            ['id' => 351120, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Putra Heights', 'active' => 1, 'slug' => 'putra-heights'],
            ['id' => 351121, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Putrajaya', 'active' => 1, 'slug' => 'putrajaya'],
            ['id' => 351122, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Rasa', 'active' => 1, 'slug' => 'rasa'],
            ['id' => 351123, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Saujana', 'active' => 1, 'slug' => 'saujana'],
            ['id' => 351124, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Sekinchan', 'active' => 1, 'slug' => 'sekinchan'],
            ['id' => 351125, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Selayang', 'active' => 1, 'slug' => 'selayang'],
            ['id' => 351126, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Sepang', 'active' => 1, 'slug' => 'sepang'],
            ['id' => 351127, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Serdang', 'active' => 1, 'slug' => 'serdang'],
            ['id' => 351128, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Seri Kembangan', 'active' => 1, 'slug' => 'seri-kembangan'],
            ['id' => 351129, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Setia Alam', 'active' => 1, 'slug' => 'setia-alam'],
            ['id' => 351130, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Setia Eco Park', 'active' => 1, 'slug' => 'setia-eco-park'],
            ['id' => 351131, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'SierraMas', 'active' => 1, 'slug' => 'sierramas'],
            ['id' => 351132, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Sri Damansara', 'active' => 1, 'slug' => 'sri-damansara'],
            ['id' => 351133, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'SS2', 'active' => 1, 'slug' => 'ss2'],
            ['id' => 351134, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Subang Heights', 'active' => 1, 'slug' => 'subang-heights'],
            ['id' => 351135, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Subang Jaya', 'active' => 1, 'slug' => 'subang-jaya'],
            ['id' => 351136, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Sungai Ayer Tawar', 'active' => 1, 'slug' => 'sungai-ayer-tawar'],
            ['id' => 351137, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Sungai Buloh', 'active' => 1, 'slug' => 'sungai-buloh'],
            ['id' => 351138, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Sungai Pelek', 'active' => 1, 'slug' => 'sungai-pelek'],
            ['id' => 351139, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Telok Panglima Garang', 'active' => 1, 'slug' => 'telok-panglima-garang'],
            ['id' => 351140, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Tropicana', 'active' => 1, 'slug' => 'tropicana'],
            ['id' => 351141, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Ulu Klang', 'active' => 1, 'slug' => 'ulu-klang'],
            ['id' => 351142, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'USJ', 'active' => 1, 'slug' => 'usj'],
            ['id' => 351143, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Valencia', 'active' => 1, 'slug' => 'valencia'],
            ['id' => 351144, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Beranang', 'active' => 1, 'slug' => 'beranang'],
            ['id' => 351145, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Tanjong Karang', 'active' => 1, 'slug' => 'tanjong-karang'],
            ['id' => 351146, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Sabak Bernam', 'active' => 1, 'slug' => 'sabak-bernam'],
            ['id' => 351147, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Batang Berjuntai', 'active' => 1, 'slug' => 'batang-berjuntai'],
            ['id' => 351148, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Kuang', 'active' => 1, 'slug' => 'kuang'],
            ['id' => 351149, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Tanjong Sepat', 'active' => 1, 'slug' => 'tanjong-sepat'],
            ['id' => 351150, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Batu Arang', 'active' => 1, 'slug' => 'batu-arang'],
            ['id' => 351151, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Jenjarom', 'active' => 1, 'slug' => 'jenjarom'],
            ['id' => 351152, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Sungai Besar', 'active' => 1, 'slug' => 'sungai-besar'],
            ['id' => 351153, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Serendah', 'active' => 1, 'slug' => 'serendah'],
            ['id' => 351154, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Kuala Selangor', 'active' => 1, 'slug' => 'kuala-selangor'],
            ['id' => 351155, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Semenyih', 'active' => 1, 'slug' => 'semenyih'],
            ['id' => 351156, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Rawang', 'active' => 1, 'slug' => 'rawang'],
            ['id' => 351157, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Shah Alam', 'active' => 1, 'slug' => 'shah-alam'],
            ['id' => 351158, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Petaling Jaya', 'active' => 1, 'slug' => 'petaling-jaya'],
            ['id' => 351159, 'region_id' => 782232, 'country_code' => 'MY', 'name' => 'Klang', 'active' => 1, 'slug' => 'klang'],
            ['id' => 351160, 'region_id' => 782233, 'country_code' => 'MY', 'name' => 'Besut', 'active' => 1, 'slug' => 'besut'],
            ['id' => 351161, 'region_id' => 782233, 'country_code' => 'MY', 'name' => 'Dungun', 'active' => 1, 'slug' => 'dungun'],
            ['id' => 351162, 'region_id' => 782233, 'country_code' => 'MY', 'name' => 'Hulu Terengganu', 'active' => 1, 'slug' => 'hulu-terengganu'],
            ['id' => 351163, 'region_id' => 782233, 'country_code' => 'MY', 'name' => 'Kemaman', 'active' => 1, 'slug' => 'kemaman'],
            ['id' => 351164, 'region_id' => 782233, 'country_code' => 'MY', 'name' => 'Marang', 'active' => 1, 'slug' => 'marang'],
            ['id' => 351165, 'region_id' => 782233, 'country_code' => 'MY', 'name' => 'Setiu', 'active' => 1, 'slug' => 'setiu'],
            ['id' => 351166, 'region_id' => 782233, 'country_code' => 'MY', 'name' => 'Kuala Terengganu', 'active' => 1, 'slug' => 'kuala-terengganu']
    	];
    }
}
