<?php

namespace Gerardojbaez\GeoData\Seeders;

use Illuminate\Database\Seeder;
use Gerardojbaez\GeoData\Models\Country;
use Gerardojbaez\GeoData\Models\Region;
use Gerardojbaez\GeoData\Models\City;

class MoroccoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Country::create($this->country());
        Region::insert($this->regions());

        if ($this->cities() > 4000)
        {
            foreach (array_chunk($this->cities(), 3500) as $chunk)
                City::insert($chunk);
        }
        else
        {
            City::insert($this->cities());
        }
    }

        /**
     * Get country.
     *
     * @return array
     */
    public function country()
    {
    	return ['code' => 'MA', 'name' => 'Morocco', 'slug' => 'morocco'];
    }

    /**
     * Get country regions.
     *
     * @return array
     */
    public function regions()
    {
    	return [
            ['id' => 783332, 'country_code' => 'MA', 'name' => 'Grand Casablanca', 'active' => 1, 'slug' => 'grand-casablanca'],
            ['id' => 783333, 'country_code' => 'MA', 'name' => 'Chaouia-Ouardigha', 'active' => 1, 'slug' => 'chaouia-ouardigha'],
            ['id' => 783334, 'country_code' => 'MA', 'name' => 'Doukkala-Abda', 'active' => 1, 'slug' => 'doukkala-abda'],
            ['id' => 783335, 'country_code' => 'MA', 'name' => 'Fès-Boulemane', 'active' => 1, 'slug' => 'fes-boulemane'],
            ['id' => 783336, 'country_code' => 'MA', 'name' => 'Gharb-Chrarda-Beni Hssen', 'active' => 1, 'slug' => 'gharb-chrarda-beni-hssen'],
            ['id' => 783337, 'country_code' => 'MA', 'name' => 'Guelmim-Es Semara', 'active' => 1, 'slug' => 'guelmim-es-semara'],
            ['id' => 783338, 'country_code' => 'MA', 'name' => 'Marrakech-Tensift-Al Haouz', 'active' => 1, 'slug' => 'marrakech-tensift-al-haouz'],
            ['id' => 783339, 'country_code' => 'MA', 'name' => 'Meknès-Tafilalet', 'active' => 1, 'slug' => 'meknes-tafilalet'],
            ['id' => 783340, 'country_code' => 'MA', 'name' => 'l\'Oriental', 'active' => 1, 'slug' => 'loriental'],
            ['id' => 783341, 'country_code' => 'MA', 'name' => 'Rabat-Salé-Zemmour-Zaër', 'active' => 1, 'slug' => 'rabat-sale-zemmour-zaer'],
            ['id' => 783342, 'country_code' => 'MA', 'name' => 'Souss-Massa-Draâ', 'active' => 1, 'slug' => 'souss-massa-draa'],
            ['id' => 783343, 'country_code' => 'MA', 'name' => 'Tadla-Azilal', 'active' => 1, 'slug' => 'tadla-azilal'],
            ['id' => 783344, 'country_code' => 'MA', 'name' => 'Tanger-Tétouan', 'active' => 1, 'slug' => 'tanger-tetouan'],
            ['id' => 783345, 'country_code' => 'MA', 'name' => 'Taza-Al Hoceïma-Taounate', 'active' => 1, 'slug' => 'taza-al-hoceima-taounate'],
            ['id' => 783346, 'country_code' => 'MA', 'name' => 'Laayoune-Boujdour-Sakia-Hamra', 'active' => 1, 'slug' => 'laayoune-boujdour-sakia-hamra'],
            ['id' => 783347, 'country_code' => 'MA', 'name' => 'Oued-Eddahab-Lagouira', 'active' => 1, 'slug' => 'oued-eddahab-lagouira']
    	];
    }

    /**
     * Get region cities.
     *
     * @return array
     */
    public function cities()
    {
    	return [
            ['id' => 512449, 'region_id' => 783332, 'country_code' => 'MA', 'name' => 'Aïn Harrouda', 'active' => 1, 'slug' => 'ain-harrouda'],
            ['id' => 512450, 'region_id' => 783332, 'country_code' => 'MA', 'name' => 'Ben Yakhlef', 'active' => 1, 'slug' => 'ben-yakhlef'],
            ['id' => 512451, 'region_id' => 783332, 'country_code' => 'MA', 'name' => 'Bouskoura', 'active' => 1, 'slug' => 'bouskoura'],
            ['id' => 512452, 'region_id' => 783332, 'country_code' => 'MA', 'name' => 'Casablanca', 'active' => 1, 'slug' => 'casablanca'],
            ['id' => 512453, 'region_id' => 783332, 'country_code' => 'MA', 'name' => 'Médiouna', 'active' => 1, 'slug' => 'mediouna'],
            ['id' => 512454, 'region_id' => 783332, 'country_code' => 'MA', 'name' => 'Mohammédia', 'active' => 1, 'slug' => 'mohammedia'],
            ['id' => 512455, 'region_id' => 783332, 'country_code' => 'MA', 'name' => 'Tit Mellil', 'active' => 1, 'slug' => 'tit-mellil'],
            ['id' => 512456, 'region_id' => 783333, 'country_code' => 'MA', 'name' => 'Ben Yakhlef', 'active' => 1, 'slug' => 'ben-yakhlef'],
            ['id' => 512457, 'region_id' => 783333, 'country_code' => 'MA', 'name' => 'Bejaâd', 'active' => 1, 'slug' => 'bejaad'],
            ['id' => 512458, 'region_id' => 783333, 'country_code' => 'MA', 'name' => 'Ben Ahmed', 'active' => 1, 'slug' => 'ben-ahmed'],
            ['id' => 512459, 'region_id' => 783333, 'country_code' => 'MA', 'name' => 'Benslimane', 'active' => 1, 'slug' => 'benslimane'],
            ['id' => 512460, 'region_id' => 783333, 'country_code' => 'MA', 'name' => 'Berrechid', 'active' => 1, 'slug' => 'berrechid'],
            ['id' => 512461, 'region_id' => 783333, 'country_code' => 'MA', 'name' => 'Boujniba', 'active' => 1, 'slug' => 'boujniba'],
            ['id' => 512462, 'region_id' => 783333, 'country_code' => 'MA', 'name' => 'Boulanouare', 'active' => 1, 'slug' => 'boulanouare'],
            ['id' => 512463, 'region_id' => 783333, 'country_code' => 'MA', 'name' => 'Bouznika', 'active' => 1, 'slug' => 'bouznika'],
            ['id' => 512464, 'region_id' => 783333, 'country_code' => 'MA', 'name' => 'Deroua', 'active' => 1, 'slug' => 'deroua'],
            ['id' => 512465, 'region_id' => 783333, 'country_code' => 'MA', 'name' => 'El Borouj', 'active' => 1, 'slug' => 'el-borouj'],
            ['id' => 512466, 'region_id' => 783333, 'country_code' => 'MA', 'name' => 'El Gara', 'active' => 1, 'slug' => 'el-gara'],
            ['id' => 512467, 'region_id' => 783333, 'country_code' => 'MA', 'name' => 'Guisser', 'active' => 1, 'slug' => 'guisser'],
            ['id' => 512468, 'region_id' => 783333, 'country_code' => 'MA', 'name' => 'Hattane', 'active' => 1, 'slug' => 'hattane'],
            ['id' => 512469, 'region_id' => 783333, 'country_code' => 'MA', 'name' => 'Khouribga', 'active' => 1, 'slug' => 'khouribga'],
            ['id' => 512470, 'region_id' => 783333, 'country_code' => 'MA', 'name' => 'Loulad', 'active' => 1, 'slug' => 'loulad'],
            ['id' => 512471, 'region_id' => 783333, 'country_code' => 'MA', 'name' => 'Oued Zem', 'active' => 1, 'slug' => 'oued-zem'],
            ['id' => 512472, 'region_id' => 783333, 'country_code' => 'MA', 'name' => 'Oulad Abbou', 'active' => 1, 'slug' => 'oulad-abbou'],
            ['id' => 512473, 'region_id' => 783333, 'country_code' => 'MA', 'name' => 'Oulad H\'Riz Sahel', 'active' => 1, 'slug' => 'oulad-hriz-sahel'],
            ['id' => 512474, 'region_id' => 783333, 'country_code' => 'MA', 'name' => 'Oulad M\'rah', 'active' => 1, 'slug' => 'oulad-mrah'],
            ['id' => 512475, 'region_id' => 783333, 'country_code' => 'MA', 'name' => 'Oulad Saïd', 'active' => 1, 'slug' => 'oulad-said'],
            ['id' => 512476, 'region_id' => 783333, 'country_code' => 'MA', 'name' => 'Oulad Sidi Ben Daoud', 'active' => 1, 'slug' => 'oulad-sidi-ben-daoud'],
            ['id' => 512477, 'region_id' => 783333, 'country_code' => 'MA', 'name' => 'Ras El Aïn', 'active' => 1, 'slug' => 'ras-el-ain'],
            ['id' => 512478, 'region_id' => 783333, 'country_code' => 'MA', 'name' => 'Settat', 'active' => 1, 'slug' => 'settat'],
            ['id' => 512479, 'region_id' => 783333, 'country_code' => 'MA', 'name' => 'Sidi Rahhal Chataï', 'active' => 1, 'slug' => 'sidi-rahhal-chatai'],
            ['id' => 512480, 'region_id' => 783333, 'country_code' => 'MA', 'name' => 'Soualem', 'active' => 1, 'slug' => 'soualem'],
            ['id' => 512481, 'region_id' => 783334, 'country_code' => 'MA', 'name' => 'Azemmour', 'active' => 1, 'slug' => 'azemmour'],
            ['id' => 512482, 'region_id' => 783334, 'country_code' => 'MA', 'name' => 'Bir Jdid', 'active' => 1, 'slug' => 'bir-jdid'],
            ['id' => 512483, 'region_id' => 783334, 'country_code' => 'MA', 'name' => 'Bouguedra', 'active' => 1, 'slug' => 'bouguedra'],
            ['id' => 512484, 'region_id' => 783334, 'country_code' => 'MA', 'name' => 'Echemmaia', 'active' => 1, 'slug' => 'echemmaia'],
            ['id' => 512485, 'region_id' => 783334, 'country_code' => 'MA', 'name' => 'El Jadida', 'active' => 1, 'slug' => 'el-jadida'],
            ['id' => 512486, 'region_id' => 783334, 'country_code' => 'MA', 'name' => 'Hrara', 'active' => 1, 'slug' => 'hrara'],
            ['id' => 512487, 'region_id' => 783334, 'country_code' => 'MA', 'name' => 'Ighoud', 'active' => 1, 'slug' => 'ighoud'],
            ['id' => 512488, 'region_id' => 783334, 'country_code' => 'MA', 'name' => 'Jamâat Shaim', 'active' => 1, 'slug' => 'jamaat-shaim'],
            ['id' => 512489, 'region_id' => 783334, 'country_code' => 'MA', 'name' => 'Jorf Lasfar', 'active' => 1, 'slug' => 'jorf-lasfar'],
            ['id' => 512490, 'region_id' => 783334, 'country_code' => 'MA', 'name' => 'Khemis Zemamra', 'active' => 1, 'slug' => 'khemis-zemamra'],
            ['id' => 512491, 'region_id' => 783334, 'country_code' => 'MA', 'name' => 'Laaounate', 'active' => 1, 'slug' => 'laaounate'],
            ['id' => 512492, 'region_id' => 783334, 'country_code' => 'MA', 'name' => 'Moulay Abdallah', 'active' => 1, 'slug' => 'moulay-abdallah'],
            ['id' => 512493, 'region_id' => 783334, 'country_code' => 'MA', 'name' => 'Oualidia', 'active' => 1, 'slug' => 'oualidia'],
            ['id' => 512494, 'region_id' => 783334, 'country_code' => 'MA', 'name' => 'Oulad Amrane', 'active' => 1, 'slug' => 'oulad-amrane'],
            ['id' => 512495, 'region_id' => 783334, 'country_code' => 'MA', 'name' => 'Oulad Frej', 'active' => 1, 'slug' => 'oulad-frej'],
            ['id' => 512496, 'region_id' => 783334, 'country_code' => 'MA', 'name' => 'Oulad Ghadbane', 'active' => 1, 'slug' => 'oulad-ghadbane'],
            ['id' => 512497, 'region_id' => 783334, 'country_code' => 'MA', 'name' => 'Safi', 'active' => 1, 'slug' => 'safi'],
            ['id' => 512498, 'region_id' => 783334, 'country_code' => 'MA', 'name' => 'Sebt El Maârif', 'active' => 1, 'slug' => 'sebt-el-maarif'],
            ['id' => 512499, 'region_id' => 783334, 'country_code' => 'MA', 'name' => 'Sebt Gzoula', 'active' => 1, 'slug' => 'sebt-gzoula'],
            ['id' => 512500, 'region_id' => 783334, 'country_code' => 'MA', 'name' => 'Sidi Ahmed', 'active' => 1, 'slug' => 'sidi-ahmed'],
            ['id' => 512501, 'region_id' => 783334, 'country_code' => 'MA', 'name' => 'Sidi Ali Ban Hamdouche', 'active' => 1, 'slug' => 'sidi-ali-ban-hamdouche'],
            ['id' => 512502, 'region_id' => 783334, 'country_code' => 'MA', 'name' => 'Sidi Bennour', 'active' => 1, 'slug' => 'sidi-bennour'],
            ['id' => 512503, 'region_id' => 783334, 'country_code' => 'MA', 'name' => 'Sidi Bouzid', 'active' => 1, 'slug' => 'sidi-bouzid'],
            ['id' => 512504, 'region_id' => 783334, 'country_code' => 'MA', 'name' => 'Sidi Smaïl', 'active' => 1, 'slug' => 'sidi-smail'],
            ['id' => 512505, 'region_id' => 783334, 'country_code' => 'MA', 'name' => 'Youssoufia', 'active' => 1, 'slug' => 'youssoufia'],
            ['id' => 512506, 'region_id' => 783335, 'country_code' => 'MA', 'name' => 'Fès', 'active' => 1, 'slug' => 'fes'],
            ['id' => 512507, 'region_id' => 783335, 'country_code' => 'MA', 'name' => 'Aïn Cheggag', 'active' => 1, 'slug' => 'ain-cheggag'],
            ['id' => 512508, 'region_id' => 783335, 'country_code' => 'MA', 'name' => 'Bhalil', 'active' => 1, 'slug' => 'bhalil'],
            ['id' => 512509, 'region_id' => 783335, 'country_code' => 'MA', 'name' => 'Boulemane', 'active' => 1, 'slug' => 'boulemane'],
            ['id' => 512510, 'region_id' => 783335, 'country_code' => 'MA', 'name' => 'El Menzel', 'active' => 1, 'slug' => 'el-menzel'],
            ['id' => 512511, 'region_id' => 783335, 'country_code' => 'MA', 'name' => 'Guigou', 'active' => 1, 'slug' => 'guigou'],
            ['id' => 512512, 'region_id' => 783335, 'country_code' => 'MA', 'name' => 'Imouzzer Kandar', 'active' => 1, 'slug' => 'imouzzer-kandar'],
            ['id' => 512513, 'region_id' => 783335, 'country_code' => 'MA', 'name' => 'Imouzzer Marmoucha', 'active' => 1, 'slug' => 'imouzzer-marmoucha'],
            ['id' => 512514, 'region_id' => 783335, 'country_code' => 'MA', 'name' => 'Missour', 'active' => 1, 'slug' => 'missour'],
            ['id' => 512515, 'region_id' => 783335, 'country_code' => 'MA', 'name' => 'Moulay Yaâcoub', 'active' => 1, 'slug' => 'moulay-yaacoub'],
            ['id' => 512516, 'region_id' => 783335, 'country_code' => 'MA', 'name' => 'Ouled Tayeb', 'active' => 1, 'slug' => 'ouled-tayeb'],
            ['id' => 512517, 'region_id' => 783335, 'country_code' => 'MA', 'name' => 'Outat El Haj', 'active' => 1, 'slug' => 'outat-el-haj'],
            ['id' => 512518, 'region_id' => 783335, 'country_code' => 'MA', 'name' => 'Ribate El Kheir', 'active' => 1, 'slug' => 'ribate-el-kheir'],
            ['id' => 512519, 'region_id' => 783335, 'country_code' => 'MA', 'name' => 'Séfrou', 'active' => 1, 'slug' => 'sefrou'],
            ['id' => 512520, 'region_id' => 783335, 'country_code' => 'MA', 'name' => 'Skhinate', 'active' => 1, 'slug' => 'skhinate'],
            ['id' => 512521, 'region_id' => 783335, 'country_code' => 'MA', 'name' => 'Tafajight', 'active' => 1, 'slug' => 'tafajight'],
            ['id' => 512522, 'region_id' => 783336, 'country_code' => 'MA', 'name' => 'Arbaoua', 'active' => 1, 'slug' => 'arbaoua'],
            ['id' => 512523, 'region_id' => 783336, 'country_code' => 'MA', 'name' => 'Aïn Dorij', 'active' => 1, 'slug' => 'ain-dorij'],
            ['id' => 512524, 'region_id' => 783336, 'country_code' => 'MA', 'name' => 'Dar Gueddari', 'active' => 1, 'slug' => 'dar-gueddari'],
            ['id' => 512525, 'region_id' => 783336, 'country_code' => 'MA', 'name' => 'Had Kourt', 'active' => 1, 'slug' => 'had-kourt'],
            ['id' => 512526, 'region_id' => 783336, 'country_code' => 'MA', 'name' => 'Jorf El Melha', 'active' => 1, 'slug' => 'jorf-el-melha'],
            ['id' => 512527, 'region_id' => 783336, 'country_code' => 'MA', 'name' => 'Kénitra', 'active' => 1, 'slug' => 'kenitra'],
            ['id' => 512528, 'region_id' => 783336, 'country_code' => 'MA', 'name' => 'Khenichet', 'active' => 1, 'slug' => 'khenichet'],
            ['id' => 512529, 'region_id' => 783336, 'country_code' => 'MA', 'name' => 'Lalla Mimouna', 'active' => 1, 'slug' => 'lalla-mimouna'],
            ['id' => 512530, 'region_id' => 783336, 'country_code' => 'MA', 'name' => 'Mechra Bel Ksiri', 'active' => 1, 'slug' => 'mechra-bel-ksiri'],
            ['id' => 512531, 'region_id' => 783336, 'country_code' => 'MA', 'name' => 'Mehdia', 'active' => 1, 'slug' => 'mehdia'],
            ['id' => 512532, 'region_id' => 783336, 'country_code' => 'MA', 'name' => 'Moulay Bousselham', 'active' => 1, 'slug' => 'moulay-bousselham'],
            ['id' => 512533, 'region_id' => 783336, 'country_code' => 'MA', 'name' => 'Sidi Allal Tazi', 'active' => 1, 'slug' => 'sidi-allal-tazi'],
            ['id' => 512534, 'region_id' => 783336, 'country_code' => 'MA', 'name' => 'Sidi Kacem', 'active' => 1, 'slug' => 'sidi-kacem'],
            ['id' => 512535, 'region_id' => 783336, 'country_code' => 'MA', 'name' => 'Sidi Slimane', 'active' => 1, 'slug' => 'sidi-slimane'],
            ['id' => 512536, 'region_id' => 783336, 'country_code' => 'MA', 'name' => 'Sidi Taibi', 'active' => 1, 'slug' => 'sidi-taibi'],
            ['id' => 512537, 'region_id' => 783336, 'country_code' => 'MA', 'name' => 'Sidi Yahya El Gharb', 'active' => 1, 'slug' => 'sidi-yahya-el-gharb'],
            ['id' => 512538, 'region_id' => 783336, 'country_code' => 'MA', 'name' => 'Souk El Arbaa', 'active' => 1, 'slug' => 'souk-el-arbaa'],
            ['id' => 512539, 'region_id' => 783337, 'country_code' => 'MA', 'name' => 'Akka', 'active' => 1, 'slug' => 'akka'],
            ['id' => 512540, 'region_id' => 783337, 'country_code' => 'MA', 'name' => 'Assa', 'active' => 1, 'slug' => 'assa'],
            ['id' => 512541, 'region_id' => 783337, 'country_code' => 'MA', 'name' => 'Bouizakarne', 'active' => 1, 'slug' => 'bouizakarne'],
            ['id' => 512542, 'region_id' => 783337, 'country_code' => 'MA', 'name' => 'El Ouatia', 'active' => 1, 'slug' => 'el-ouatia'],
            ['id' => 512543, 'region_id' => 783337, 'country_code' => 'MA', 'name' => 'Es-Semara', 'active' => 1, 'slug' => 'es-semara'],
            ['id' => 512544, 'region_id' => 783337, 'country_code' => 'MA', 'name' => 'Fam El Hisn', 'active' => 1, 'slug' => 'fam-el-hisn'],
            ['id' => 512545, 'region_id' => 783337, 'country_code' => 'MA', 'name' => 'Foum Zguid', 'active' => 1, 'slug' => 'foum-zguid'],
            ['id' => 512546, 'region_id' => 783337, 'country_code' => 'MA', 'name' => 'Guelmim', 'active' => 1, 'slug' => 'guelmim'],
            ['id' => 512547, 'region_id' => 783337, 'country_code' => 'MA', 'name' => 'Taghjijt', 'active' => 1, 'slug' => 'taghjijt'],
            ['id' => 512548, 'region_id' => 783337, 'country_code' => 'MA', 'name' => 'Tan-Tan', 'active' => 1, 'slug' => 'tan-tan'],
            ['id' => 512549, 'region_id' => 783337, 'country_code' => 'MA', 'name' => 'Tata', 'active' => 1, 'slug' => 'tata'],
            ['id' => 512550, 'region_id' => 783337, 'country_code' => 'MA', 'name' => 'Zag', 'active' => 1, 'slug' => 'zag'],
            ['id' => 512551, 'region_id' => 783338, 'country_code' => 'MA', 'name' => 'Marrakech', 'active' => 1, 'slug' => 'marrakech'],
            ['id' => 512552, 'region_id' => 783338, 'country_code' => 'MA', 'name' => 'Ait Daoud', 'active' => 1, 'slug' => 'ait-daoud'],
            ['id' => 512553, 'region_id' => 783338, 'country_code' => 'MA', 'name' => 'Amizmiz', 'active' => 1, 'slug' => 'amizmiz'],
            ['id' => 512554, 'region_id' => 783338, 'country_code' => 'MA', 'name' => 'Assahrij', 'active' => 1, 'slug' => 'assahrij'],
            ['id' => 512555, 'region_id' => 783338, 'country_code' => 'MA', 'name' => 'Aït Ourir', 'active' => 1, 'slug' => 'ait-ourir'],
            ['id' => 512556, 'region_id' => 783338, 'country_code' => 'MA', 'name' => 'Ben Guerir', 'active' => 1, 'slug' => 'ben-guerir'],
            ['id' => 512557, 'region_id' => 783338, 'country_code' => 'MA', 'name' => 'Chichaoua', 'active' => 1, 'slug' => 'chichaoua'],
            ['id' => 512558, 'region_id' => 783338, 'country_code' => 'MA', 'name' => 'El Hanchane', 'active' => 1, 'slug' => 'el-hanchane'],
            ['id' => 512559, 'region_id' => 783338, 'country_code' => 'MA', 'name' => 'El Kelaâ des Sraghna', 'active' => 1, 'slug' => 'el-kelaa-des-sraghna'],
            ['id' => 512560, 'region_id' => 783338, 'country_code' => 'MA', 'name' => 'Essaouira', 'active' => 1, 'slug' => 'essaouira'],
            ['id' => 512561, 'region_id' => 783338, 'country_code' => 'MA', 'name' => 'Fraïta', 'active' => 1, 'slug' => 'fraita'],
            ['id' => 512562, 'region_id' => 783338, 'country_code' => 'MA', 'name' => 'Ghmate', 'active' => 1, 'slug' => 'ghmate'],
            ['id' => 512563, 'region_id' => 783338, 'country_code' => 'MA', 'name' => 'Ighounane', 'active' => 1, 'slug' => 'ighounane'],
            ['id' => 512564, 'region_id' => 783338, 'country_code' => 'MA', 'name' => 'Imintanoute', 'active' => 1, 'slug' => 'imintanoute'],
            ['id' => 512565, 'region_id' => 783338, 'country_code' => 'MA', 'name' => 'Kattara', 'active' => 1, 'slug' => 'kattara'],
            ['id' => 512566, 'region_id' => 783338, 'country_code' => 'MA', 'name' => 'Lalla Takerkoust', 'active' => 1, 'slug' => 'lalla-takerkoust'],
            ['id' => 512567, 'region_id' => 783338, 'country_code' => 'MA', 'name' => 'Loudaya', 'active' => 1, 'slug' => 'loudaya'],
            ['id' => 512568, 'region_id' => 783338, 'country_code' => 'MA', 'name' => 'Lâattaouia', 'active' => 1, 'slug' => 'laattaouia'],
            ['id' => 512569, 'region_id' => 783338, 'country_code' => 'MA', 'name' => 'Moulay Brahim', 'active' => 1, 'slug' => 'moulay-brahim'],
            ['id' => 512570, 'region_id' => 783338, 'country_code' => 'MA', 'name' => 'Mzouda', 'active' => 1, 'slug' => 'mzouda'],
            ['id' => 512571, 'region_id' => 783338, 'country_code' => 'MA', 'name' => 'Ounagha', 'active' => 1, 'slug' => 'ounagha'],
            ['id' => 512572, 'region_id' => 783338, 'country_code' => 'MA', 'name' => 'Sid L\'Mokhtar', 'active' => 1, 'slug' => 'sid-lmokhtar'],
            ['id' => 512573, 'region_id' => 783338, 'country_code' => 'MA', 'name' => 'Sid Zouin', 'active' => 1, 'slug' => 'sid-zouin'],
            ['id' => 512574, 'region_id' => 783338, 'country_code' => 'MA', 'name' => 'Sidi Abdallah Ghiat', 'active' => 1, 'slug' => 'sidi-abdallah-ghiat'],
            ['id' => 512575, 'region_id' => 783338, 'country_code' => 'MA', 'name' => 'Sidi Bou Othmane', 'active' => 1, 'slug' => 'sidi-bou-othmane'],
            ['id' => 512576, 'region_id' => 783338, 'country_code' => 'MA', 'name' => 'Sidi Rahhal', 'active' => 1, 'slug' => 'sidi-rahhal'],
            ['id' => 512577, 'region_id' => 783338, 'country_code' => 'MA', 'name' => 'Skhour Rehamna', 'active' => 1, 'slug' => 'skhour-rehamna'],
            ['id' => 512578, 'region_id' => 783338, 'country_code' => 'MA', 'name' => 'Smimou', 'active' => 1, 'slug' => 'smimou'],
            ['id' => 512579, 'region_id' => 783338, 'country_code' => 'MA', 'name' => 'Tafetachte', 'active' => 1, 'slug' => 'tafetachte'],
            ['id' => 512580, 'region_id' => 783338, 'country_code' => 'MA', 'name' => 'Tahannaout', 'active' => 1, 'slug' => 'tahannaout'],
            ['id' => 512581, 'region_id' => 783338, 'country_code' => 'MA', 'name' => 'Talmest', 'active' => 1, 'slug' => 'talmest'],
            ['id' => 512582, 'region_id' => 783338, 'country_code' => 'MA', 'name' => 'Tamallalt', 'active' => 1, 'slug' => 'tamallalt'],
            ['id' => 512583, 'region_id' => 783338, 'country_code' => 'MA', 'name' => 'Tamanar', 'active' => 1, 'slug' => 'tamanar'],
            ['id' => 512584, 'region_id' => 783338, 'country_code' => 'MA', 'name' => 'Tamansourt', 'active' => 1, 'slug' => 'tamansourt'],
            ['id' => 512585, 'region_id' => 783338, 'country_code' => 'MA', 'name' => 'Tameslouht', 'active' => 1, 'slug' => 'tameslouht'],
            ['id' => 512586, 'region_id' => 783338, 'country_code' => 'MA', 'name' => 'Tanalt', 'active' => 1, 'slug' => 'tanalt'],
            ['id' => 512587, 'region_id' => 783338, 'country_code' => 'MA', 'name' => 'Zeubelemok', 'active' => 1, 'slug' => 'zeubelemok'],
            ['id' => 512588, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Meknès‎', 'active' => 1, 'slug' => 'meknes'],
            ['id' => 512589, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Khénifra', 'active' => 1, 'slug' => 'khenifra'],
            ['id' => 512590, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Agourai', 'active' => 1, 'slug' => 'agourai'],
            ['id' => 512591, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Ain Taoujdate', 'active' => 1, 'slug' => 'ain-taoujdate'],
            ['id' => 512592, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'MyAliCherif', 'active' => 1, 'slug' => 'myalicherif'],
            ['id' => 512593, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Rissani', 'active' => 1, 'slug' => 'rissani'],
            ['id' => 512594, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Amalou Ighriben', 'active' => 1, 'slug' => 'amalou-ighriben'],
            ['id' => 512595, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Aoufous', 'active' => 1, 'slug' => 'aoufous'],
            ['id' => 512596, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Arfoud', 'active' => 1, 'slug' => 'arfoud'],
            ['id' => 512597, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Azrou', 'active' => 1, 'slug' => 'azrou'],
            ['id' => 512598, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Aïn Jemaa', 'active' => 1, 'slug' => 'ain-jemaa'],
            ['id' => 512599, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Aïn Karma', 'active' => 1, 'slug' => 'ain-karma'],
            ['id' => 512600, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Aïn Leuh', 'active' => 1, 'slug' => 'ain-leuh'],
            ['id' => 512601, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Aït Boubidmane', 'active' => 1, 'slug' => 'ait-boubidmane'],
            ['id' => 512602, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Aït Ishaq', 'active' => 1, 'slug' => 'ait-ishaq'],
            ['id' => 512603, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Boudnib', 'active' => 1, 'slug' => 'boudnib'],
            ['id' => 512604, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Boufakrane', 'active' => 1, 'slug' => 'boufakrane'],
            ['id' => 512605, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Boumia', 'active' => 1, 'slug' => 'boumia'],
            ['id' => 512606, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'El Hajeb', 'active' => 1, 'slug' => 'el-hajeb'],
            ['id' => 512607, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Elkbab', 'active' => 1, 'slug' => 'elkbab'],
            ['id' => 512608, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Er-Rich', 'active' => 1, 'slug' => 'er-rich'],
            ['id' => 512609, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Errachidia', 'active' => 1, 'slug' => 'errachidia'],
            ['id' => 512610, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Gardmit', 'active' => 1, 'slug' => 'gardmit'],
            ['id' => 512611, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Goulmima', 'active' => 1, 'slug' => 'goulmima'],
            ['id' => 512612, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Gourrama', 'active' => 1, 'slug' => 'gourrama'],
            ['id' => 512613, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Had Bouhssoussen', 'active' => 1, 'slug' => 'had-bouhssoussen'],
            ['id' => 512614, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Haj Kaddour', 'active' => 1, 'slug' => 'haj-kaddour'],
            ['id' => 512615, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Ifrane', 'active' => 1, 'slug' => 'ifrane'],
            ['id' => 512616, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Itzer', 'active' => 1, 'slug' => 'itzer'],
            ['id' => 512617, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Jorf', 'active' => 1, 'slug' => 'jorf'],
            ['id' => 512618, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Kehf Nsour', 'active' => 1, 'slug' => 'kehf-nsour'],
            ['id' => 512619, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Kerrouchen', 'active' => 1, 'slug' => 'kerrouchen'],
            ['id' => 512620, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'M\'haya', 'active' => 1, 'slug' => 'mhaya'],
            ['id' => 512621, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'M\'rirt', 'active' => 1, 'slug' => 'mrirt'],
            ['id' => 512622, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Midelt', 'active' => 1, 'slug' => 'midelt'],
            ['id' => 512623, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Moulay Ali Cherif', 'active' => 1, 'slug' => 'moulay-ali-cherif'],
            ['id' => 512624, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Moulay Bouazza', 'active' => 1, 'slug' => 'moulay-bouazza'],
            ['id' => 512625, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Moulay Idriss Zerhoun', 'active' => 1, 'slug' => 'moulay-idriss-zerhoun'],
            ['id' => 512626, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Moussaoua', 'active' => 1, 'slug' => 'moussaoua'],
            ['id' => 512627, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'N\'Zalat Bni Amar', 'active' => 1, 'slug' => 'nzalat-bni-amar'],
            ['id' => 512628, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Ouaoumana', 'active' => 1, 'slug' => 'ouaoumana'],
            ['id' => 512629, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Oued Ifrane', 'active' => 1, 'slug' => 'oued-ifrane'],
            ['id' => 512630, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Sabaa Aiyoun', 'active' => 1, 'slug' => 'sabaa-aiyoun'],
            ['id' => 512631, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Sebt Jahjouh', 'active' => 1, 'slug' => 'sebt-jahjouh'],
            ['id' => 512632, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Sidi Addi', 'active' => 1, 'slug' => 'sidi-addi'],
            ['id' => 512633, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Tichoute', 'active' => 1, 'slug' => 'tichoute'],
            ['id' => 512634, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Tighassaline', 'active' => 1, 'slug' => 'tighassaline'],
            ['id' => 512635, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Tighza', 'active' => 1, 'slug' => 'tighza'],
            ['id' => 512636, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Timahdite', 'active' => 1, 'slug' => 'timahdite'],
            ['id' => 512637, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Tinejdad', 'active' => 1, 'slug' => 'tinejdad'],
            ['id' => 512638, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Tizguite', 'active' => 1, 'slug' => 'tizguite'],
            ['id' => 512639, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Toulal', 'active' => 1, 'slug' => 'toulal'],
            ['id' => 512640, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Tounfite', 'active' => 1, 'slug' => 'tounfite'],
            ['id' => 512641, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Zaouia d\'Ifrane', 'active' => 1, 'slug' => 'zaouia-difrane'],
            ['id' => 512642, 'region_id' => 783339, 'country_code' => 'MA', 'name' => 'Zaïda', 'active' => 1, 'slug' => 'zaida'],
            ['id' => 512643, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Ahfir', 'active' => 1, 'slug' => 'ahfir'],
            ['id' => 512644, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Aklim', 'active' => 1, 'slug' => 'aklim'],
            ['id' => 512645, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Al Aroui', 'active' => 1, 'slug' => 'al-aroui'],
            ['id' => 512646, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Aïn Bni Mathar', 'active' => 1, 'slug' => 'ain-bni-mathar'],
            ['id' => 512647, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Aïn Erreggada', 'active' => 1, 'slug' => 'ain-erreggada'],
            ['id' => 512648, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Ben Taïeb', 'active' => 1, 'slug' => 'ben-taieb'],
            ['id' => 512649, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Berkane', 'active' => 1, 'slug' => 'berkane'],
            ['id' => 512650, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Bni Ansar', 'active' => 1, 'slug' => 'bni-ansar'],
            ['id' => 512651, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Bni Chiker', 'active' => 1, 'slug' => 'bni-chiker'],
            ['id' => 512652, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Bni Drar', 'active' => 1, 'slug' => 'bni-drar'],
            ['id' => 512653, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Bni Tadjite', 'active' => 1, 'slug' => 'bni-tadjite'],
            ['id' => 512654, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Bouanane', 'active' => 1, 'slug' => 'bouanane'],
            ['id' => 512655, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Bouarfa', 'active' => 1, 'slug' => 'bouarfa'],
            ['id' => 512656, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Bouhdila', 'active' => 1, 'slug' => 'bouhdila'],
            ['id' => 512657, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Dar El Kebdani', 'active' => 1, 'slug' => 'dar-el-kebdani'],
            ['id' => 512658, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Debdou', 'active' => 1, 'slug' => 'debdou'],
            ['id' => 512659, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Douar Kannine', 'active' => 1, 'slug' => 'douar-kannine'],
            ['id' => 512660, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Driouch', 'active' => 1, 'slug' => 'driouch'],
            ['id' => 512661, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'El Aïoun Sidi Mellouk', 'active' => 1, 'slug' => 'el-aioun-sidi-mellouk'],
            ['id' => 512662, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Farkhana', 'active' => 1, 'slug' => 'farkhana'],
            ['id' => 512663, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Figuig', 'active' => 1, 'slug' => 'figuig'],
            ['id' => 512664, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Ihddaden', 'active' => 1, 'slug' => 'ihddaden'],
            ['id' => 512665, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Jaâdar', 'active' => 1, 'slug' => 'jaadar'],
            ['id' => 512666, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Jerada', 'active' => 1, 'slug' => 'jerada'],
            ['id' => 512667, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Kariat Arekmane', 'active' => 1, 'slug' => 'kariat-arekmane'],
            ['id' => 512668, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Kassita', 'active' => 1, 'slug' => 'kassita'],
            ['id' => 512669, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Kerouna', 'active' => 1, 'slug' => 'kerouna'],
            ['id' => 512670, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Laâtamna', 'active' => 1, 'slug' => 'laatamna'],
            ['id' => 512671, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Madagh', 'active' => 1, 'slug' => 'madagh'],
            ['id' => 512672, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Midar', 'active' => 1, 'slug' => 'midar'],
            ['id' => 512673, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Nador', 'active' => 1, 'slug' => 'nador'],
            ['id' => 512674, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Naima', 'active' => 1, 'slug' => 'naima'],
            ['id' => 512675, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Oued Heimer', 'active' => 1, 'slug' => 'oued-heimer'],
            ['id' => 512676, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Oujda', 'active' => 1, 'slug' => 'oujda'],
            ['id' => 512677, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Ras El Ma', 'active' => 1, 'slug' => 'ras-el-ma'],
            ['id' => 512678, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Saïdia', 'active' => 1, 'slug' => 'saidia'],
            ['id' => 512679, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Selouane', 'active' => 1, 'slug' => 'selouane'],
            ['id' => 512680, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Sidi Boubker', 'active' => 1, 'slug' => 'sidi-boubker'],
            ['id' => 512681, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Sidi Slimane Echcharaa', 'active' => 1, 'slug' => 'sidi-slimane-echcharaa'],
            ['id' => 512682, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Talsint', 'active' => 1, 'slug' => 'talsint'],
            ['id' => 512683, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Taourirt', 'active' => 1, 'slug' => 'taourirt'],
            ['id' => 512684, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Tendrara', 'active' => 1, 'slug' => 'tendrara'],
            ['id' => 512685, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Tiztoutine', 'active' => 1, 'slug' => 'tiztoutine'],
            ['id' => 512686, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Touima', 'active' => 1, 'slug' => 'touima'],
            ['id' => 512687, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Touissit', 'active' => 1, 'slug' => 'touissit'],
            ['id' => 512688, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Zaïo', 'active' => 1, 'slug' => 'zaio'],
            ['id' => 512689, 'region_id' => 783340, 'country_code' => 'MA', 'name' => 'Zeghanghane', 'active' => 1, 'slug' => 'zeghanghane'],
            ['id' => 512690, 'region_id' => 783341, 'country_code' => 'MA', 'name' => 'Rabat', 'active' => 1, 'slug' => 'rabat'],
            ['id' => 512691, 'region_id' => 783341, 'country_code' => 'MA', 'name' => 'Salé', 'active' => 1, 'slug' => 'sale'],
            ['id' => 512692, 'region_id' => 783341, 'country_code' => 'MA', 'name' => 'Ain El Aouda', 'active' => 1, 'slug' => 'ain-el-aouda'],
            ['id' => 512693, 'region_id' => 783341, 'country_code' => 'MA', 'name' => 'Harhoura', 'active' => 1, 'slug' => 'harhoura'],
            ['id' => 512694, 'region_id' => 783341, 'country_code' => 'MA', 'name' => 'Khémisset', 'active' => 1, 'slug' => 'khemisset'],
            ['id' => 512695, 'region_id' => 783341, 'country_code' => 'MA', 'name' => 'Oulmès', 'active' => 1, 'slug' => 'oulmes'],
            ['id' => 512696, 'region_id' => 783341, 'country_code' => 'MA', 'name' => 'Rommani', 'active' => 1, 'slug' => 'rommani'],
            ['id' => 512697, 'region_id' => 783341, 'country_code' => 'MA', 'name' => 'Sidi Allal El Bahraoui', 'active' => 1, 'slug' => 'sidi-allal-el-bahraoui'],
            ['id' => 512698, 'region_id' => 783341, 'country_code' => 'MA', 'name' => 'Sidi Bouknadel', 'active' => 1, 'slug' => 'sidi-bouknadel'],
            ['id' => 512699, 'region_id' => 783341, 'country_code' => 'MA', 'name' => 'Skhirat', 'active' => 1, 'slug' => 'skhirat'],
            ['id' => 512700, 'region_id' => 783341, 'country_code' => 'MA', 'name' => 'Tamesna', 'active' => 1, 'slug' => 'tamesna'],
            ['id' => 512701, 'region_id' => 783341, 'country_code' => 'MA', 'name' => 'Témara', 'active' => 1, 'slug' => 'temara'],
            ['id' => 512702, 'region_id' => 783341, 'country_code' => 'MA', 'name' => 'Tiddas', 'active' => 1, 'slug' => 'tiddas'],
            ['id' => 512703, 'region_id' => 783341, 'country_code' => 'MA', 'name' => 'Tiflet', 'active' => 1, 'slug' => 'tiflet'],
            ['id' => 512704, 'region_id' => 783341, 'country_code' => 'MA', 'name' => 'Touarga', 'active' => 1, 'slug' => 'touarga'],
            ['id' => 512705, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Agadir', 'active' => 1, 'slug' => 'agadir'],
            ['id' => 512706, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Agdz', 'active' => 1, 'slug' => 'agdz'],
            ['id' => 512707, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Agni Izimmer', 'active' => 1, 'slug' => 'agni-izimmer'],
            ['id' => 512708, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Aït Melloul', 'active' => 1, 'slug' => 'ait-melloul'],
            ['id' => 512709, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Alnif', 'active' => 1, 'slug' => 'alnif'],
            ['id' => 512710, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Anzi', 'active' => 1, 'slug' => 'anzi'],
            ['id' => 512711, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Aoulouz', 'active' => 1, 'slug' => 'aoulouz'],
            ['id' => 512712, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Aourir', 'active' => 1, 'slug' => 'aourir'],
            ['id' => 512713, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Arazane', 'active' => 1, 'slug' => 'arazane'],
            ['id' => 512714, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Aït Baha', 'active' => 1, 'slug' => 'ait-baha'],
            ['id' => 512715, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Aït Iaâza', 'active' => 1, 'slug' => 'ait-iaaza'],
            ['id' => 512716, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Aït Yalla', 'active' => 1, 'slug' => 'ait-yalla'],
            ['id' => 512717, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Ben Sergao', 'active' => 1, 'slug' => 'ben-sergao'],
            ['id' => 512718, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Biougra', 'active' => 1, 'slug' => 'biougra'],
            ['id' => 512719, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Boumalne-Dadès', 'active' => 1, 'slug' => 'boumalne-dades'],
            ['id' => 512720, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Dcheira El Jihadia', 'active' => 1, 'slug' => 'dcheira-el-jihadia'],
            ['id' => 512721, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Drargua', 'active' => 1, 'slug' => 'drargua'],
            ['id' => 512722, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'El Guerdane', 'active' => 1, 'slug' => 'el-guerdane'],
            ['id' => 512723, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Harte Lyamine', 'active' => 1, 'slug' => 'harte-lyamine'],
            ['id' => 512724, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Ida Ougnidif', 'active' => 1, 'slug' => 'ida-ougnidif'],
            ['id' => 512725, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Ifri', 'active' => 1, 'slug' => 'ifri'],
            ['id' => 512726, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Igdamen', 'active' => 1, 'slug' => 'igdamen'],
            ['id' => 512727, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Ighil n\'Oumgoun', 'active' => 1, 'slug' => 'ighil-noumgoun'],
            ['id' => 512728, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Imassine', 'active' => 1, 'slug' => 'imassine'],
            ['id' => 512729, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Inezgane', 'active' => 1, 'slug' => 'inezgane'],
            ['id' => 512730, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Irherm', 'active' => 1, 'slug' => 'irherm'],
            ['id' => 512731, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Kelaat-M\'Gouna', 'active' => 1, 'slug' => 'kelaat-mgouna'],
            ['id' => 512732, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Lakhsas', 'active' => 1, 'slug' => 'lakhsas'],
            ['id' => 512733, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Lakhsass', 'active' => 1, 'slug' => 'lakhsass'],
            ['id' => 512734, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Lqliâa', 'active' => 1, 'slug' => 'lqliaa'],
            ['id' => 512735, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'M\'semrir', 'active' => 1, 'slug' => 'msemrir'],
            ['id' => 512736, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Massa (Maroc)', 'active' => 1, 'slug' => 'massa-maroc'],
            ['id' => 512737, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Megousse', 'active' => 1, 'slug' => 'megousse'],
            ['id' => 512738, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Ouarzazate', 'active' => 1, 'slug' => 'ouarzazate'],
            ['id' => 512739, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Oulad Berhil', 'active' => 1, 'slug' => 'oulad-berhil'],
            ['id' => 512740, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Oulad Teïma', 'active' => 1, 'slug' => 'oulad-teima'],
            ['id' => 512741, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Sarghine', 'active' => 1, 'slug' => 'sarghine'],
            ['id' => 512742, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Sidi Ifni', 'active' => 1, 'slug' => 'sidi-ifni'],
            ['id' => 512743, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Skoura', 'active' => 1, 'slug' => 'skoura'],
            ['id' => 512744, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Tabounte', 'active' => 1, 'slug' => 'tabounte'],
            ['id' => 512745, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Tafraout', 'active' => 1, 'slug' => 'tafraout'],
            ['id' => 512746, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Taghzout', 'active' => 1, 'slug' => 'taghzout'],
            ['id' => 512747, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Tagzen', 'active' => 1, 'slug' => 'tagzen'],
            ['id' => 512748, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Taliouine', 'active' => 1, 'slug' => 'taliouine'],
            ['id' => 512749, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Tamegroute', 'active' => 1, 'slug' => 'tamegroute'],
            ['id' => 512750, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Tamraght', 'active' => 1, 'slug' => 'tamraght'],
            ['id' => 512751, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Tanoumrite Nkob Zagora', 'active' => 1, 'slug' => 'tanoumrite-nkob-zagora'],
            ['id' => 512752, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Taourirt ait zaghar', 'active' => 1, 'slug' => 'taourirt-ait-zaghar'],
            ['id' => 512753, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Taroudant', 'active' => 1, 'slug' => 'taroudant'],
            ['id' => 512754, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Temsia', 'active' => 1, 'slug' => 'temsia'],
            ['id' => 512755, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Tifnit', 'active' => 1, 'slug' => 'tifnit'],
            ['id' => 512756, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Tisgdal', 'active' => 1, 'slug' => 'tisgdal'],
            ['id' => 512757, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Tiznit', 'active' => 1, 'slug' => 'tiznit'],
            ['id' => 512758, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Toundoute', 'active' => 1, 'slug' => 'toundoute'],
            ['id' => 512759, 'region_id' => 783342, 'country_code' => 'MA', 'name' => 'Zagora', 'active' => 1, 'slug' => 'zagora'],
            ['id' => 512760, 'region_id' => 783343, 'country_code' => 'MA', 'name' => 'Afourar', 'active' => 1, 'slug' => 'afourar'],
            ['id' => 512761, 'region_id' => 783343, 'country_code' => 'MA', 'name' => 'Aghbala', 'active' => 1, 'slug' => 'aghbala'],
            ['id' => 512762, 'region_id' => 783343, 'country_code' => 'MA', 'name' => 'Azilal', 'active' => 1, 'slug' => 'azilal'],
            ['id' => 512763, 'region_id' => 783343, 'country_code' => 'MA', 'name' => 'Aït Majden', 'active' => 1, 'slug' => 'ait-majden'],
            ['id' => 512764, 'region_id' => 783343, 'country_code' => 'MA', 'name' => 'Beni Ayat', 'active' => 1, 'slug' => 'beni-ayat'],
            ['id' => 512765, 'region_id' => 783343, 'country_code' => 'MA', 'name' => 'Béni Mellal', 'active' => 1, 'slug' => 'beni-mellal'],
            ['id' => 512766, 'region_id' => 783343, 'country_code' => 'MA', 'name' => 'Bin elouidane', 'active' => 1, 'slug' => 'bin-elouidane'],
            ['id' => 512767, 'region_id' => 783343, 'country_code' => 'MA', 'name' => 'Bradia', 'active' => 1, 'slug' => 'bradia'],
            ['id' => 512768, 'region_id' => 783343, 'country_code' => 'MA', 'name' => 'Bzou', 'active' => 1, 'slug' => 'bzou'],
            ['id' => 512769, 'region_id' => 783343, 'country_code' => 'MA', 'name' => 'Dar Oulad Zidouh', 'active' => 1, 'slug' => 'dar-oulad-zidouh'],
            ['id' => 512770, 'region_id' => 783343, 'country_code' => 'MA', 'name' => 'Demnate', 'active' => 1, 'slug' => 'demnate'],
            ['id' => 512771, 'region_id' => 783343, 'country_code' => 'MA', 'name' => 'Dra\'a', 'active' => 1, 'slug' => 'draa'],
            ['id' => 512772, 'region_id' => 783343, 'country_code' => 'MA', 'name' => 'El Ksiba', 'active' => 1, 'slug' => 'el-ksiba'],
            ['id' => 512773, 'region_id' => 783343, 'country_code' => 'MA', 'name' => 'Foum Jamaa', 'active' => 1, 'slug' => 'foum-jamaa'],
            ['id' => 512774, 'region_id' => 783343, 'country_code' => 'MA', 'name' => 'Fquih Ben Salah', 'active' => 1, 'slug' => 'fquih-ben-salah'],
            ['id' => 512775, 'region_id' => 783343, 'country_code' => 'MA', 'name' => 'Kasba Tadla', 'active' => 1, 'slug' => 'kasba-tadla'],
            ['id' => 512776, 'region_id' => 783343, 'country_code' => 'MA', 'name' => 'Ouaouizeght', 'active' => 1, 'slug' => 'ouaouizeght'],
            ['id' => 512777, 'region_id' => 783343, 'country_code' => 'MA', 'name' => 'Oulad Ayad', 'active' => 1, 'slug' => 'oulad-ayad'],
            ['id' => 512778, 'region_id' => 783343, 'country_code' => 'MA', 'name' => 'Oulad M\'Barek', 'active' => 1, 'slug' => 'oulad-mbarek'],
            ['id' => 512779, 'region_id' => 783343, 'country_code' => 'MA', 'name' => 'Oulad Yaich', 'active' => 1, 'slug' => 'oulad-yaich'],
            ['id' => 512780, 'region_id' => 783343, 'country_code' => 'MA', 'name' => 'Sidi Jaber', 'active' => 1, 'slug' => 'sidi-jaber'],
            ['id' => 512781, 'region_id' => 783343, 'country_code' => 'MA', 'name' => 'Souk Sebt Oulad Nemma', 'active' => 1, 'slug' => 'souk-sebt-oulad-nemma'],
            ['id' => 512782, 'region_id' => 783343, 'country_code' => 'MA', 'name' => 'Zaouïat Cheikh', 'active' => 1, 'slug' => 'zaouiat-cheikh'],
            ['id' => 512783, 'region_id' => 783344, 'country_code' => 'MA', 'name' => 'Tanger‎', 'active' => 1, 'slug' => 'tanger'],
            ['id' => 512784, 'region_id' => 783344, 'country_code' => 'MA', 'name' => 'Tétouan‎', 'active' => 1, 'slug' => 'tetouan'],
            ['id' => 512785, 'region_id' => 783344, 'country_code' => 'MA', 'name' => 'Akchour', 'active' => 1, 'slug' => 'akchour'],
            ['id' => 512786, 'region_id' => 783344, 'country_code' => 'MA', 'name' => 'Assilah', 'active' => 1, 'slug' => 'assilah'],
            ['id' => 512787, 'region_id' => 783344, 'country_code' => 'MA', 'name' => 'Bab Berred', 'active' => 1, 'slug' => 'bab-berred'],
            ['id' => 512788, 'region_id' => 783344, 'country_code' => 'MA', 'name' => 'Bab Taza', 'active' => 1, 'slug' => 'bab-taza'],
            ['id' => 512789, 'region_id' => 783344, 'country_code' => 'MA', 'name' => 'Brikcha', 'active' => 1, 'slug' => 'brikcha'],
            ['id' => 512790, 'region_id' => 783344, 'country_code' => 'MA', 'name' => 'Chefchaouen', 'active' => 1, 'slug' => 'chefchaouen'],
            ['id' => 512791, 'region_id' => 783344, 'country_code' => 'MA', 'name' => 'Dar Bni Karrich', 'active' => 1, 'slug' => 'dar-bni-karrich'],
            ['id' => 512792, 'region_id' => 783344, 'country_code' => 'MA', 'name' => 'Dar Chaoui', 'active' => 1, 'slug' => 'dar-chaoui'],
            ['id' => 512793, 'region_id' => 783344, 'country_code' => 'MA', 'name' => 'Fnideq', 'active' => 1, 'slug' => 'fnideq'],
            ['id' => 512794, 'region_id' => 783344, 'country_code' => 'MA', 'name' => 'Gueznaia', 'active' => 1, 'slug' => 'gueznaia'],
            ['id' => 512795, 'region_id' => 783344, 'country_code' => 'MA', 'name' => 'Jebha', 'active' => 1, 'slug' => 'jebha'],
            ['id' => 512796, 'region_id' => 783344, 'country_code' => 'MA', 'name' => 'Karia', 'active' => 1, 'slug' => 'karia'],
            ['id' => 512797, 'region_id' => 783344, 'country_code' => 'MA', 'name' => 'Khémis Sahel', 'active' => 1, 'slug' => 'khemis-sahel'],
            ['id' => 512798, 'region_id' => 783344, 'country_code' => 'MA', 'name' => 'Ksar El Kébir', 'active' => 1, 'slug' => 'ksar-el-kebir'],
            ['id' => 512799, 'region_id' => 783344, 'country_code' => 'MA', 'name' => 'Larache', 'active' => 1, 'slug' => 'larache'],
            ['id' => 512800, 'region_id' => 783344, 'country_code' => 'MA', 'name' => 'M\'diq', 'active' => 1, 'slug' => 'mdiq'],
            ['id' => 512801, 'region_id' => 783344, 'country_code' => 'MA', 'name' => 'Martil', 'active' => 1, 'slug' => 'martil'],
            ['id' => 512802, 'region_id' => 783344, 'country_code' => 'MA', 'name' => 'Moqrisset', 'active' => 1, 'slug' => 'moqrisset'],
            ['id' => 512803, 'region_id' => 783344, 'country_code' => 'MA', 'name' => 'Oued Laou', 'active' => 1, 'slug' => 'oued-laou'],
            ['id' => 512804, 'region_id' => 783344, 'country_code' => 'MA', 'name' => 'Oued Rmel', 'active' => 1, 'slug' => 'oued-rmel'],
            ['id' => 512805, 'region_id' => 783344, 'country_code' => 'MA', 'name' => 'Ouezzane', 'active' => 1, 'slug' => 'ouezzane'],
            ['id' => 512806, 'region_id' => 783344, 'country_code' => 'MA', 'name' => 'Point Cires', 'active' => 1, 'slug' => 'point-cires'],
            ['id' => 512807, 'region_id' => 783344, 'country_code' => 'MA', 'name' => 'Sidi Lyamani', 'active' => 1, 'slug' => 'sidi-lyamani'],
            ['id' => 512808, 'region_id' => 783344, 'country_code' => 'MA', 'name' => 'Sidi Mohamed ben Abdallah el-Raisuni', 'active' => 1, 'slug' => 'sidi-mohamed-ben-abdallah-el-raisuni'],
            ['id' => 512809, 'region_id' => 783344, 'country_code' => 'MA', 'name' => 'Zinat', 'active' => 1, 'slug' => 'zinat'],
            ['id' => 512810, 'region_id' => 783345, 'country_code' => 'MA', 'name' => 'Ajdir‎', 'active' => 1, 'slug' => 'ajdir'],
            ['id' => 512811, 'region_id' => 783345, 'country_code' => 'MA', 'name' => 'Aknoul‎', 'active' => 1, 'slug' => 'aknoul'],
            ['id' => 512812, 'region_id' => 783345, 'country_code' => 'MA', 'name' => 'Al Hoceïma‎', 'active' => 1, 'slug' => 'al-hoceima'],
            ['id' => 512813, 'region_id' => 783345, 'country_code' => 'MA', 'name' => 'Aït Hichem‎', 'active' => 1, 'slug' => 'ait-hichem'],
            ['id' => 512814, 'region_id' => 783345, 'country_code' => 'MA', 'name' => 'Bni Bouayach‎', 'active' => 1, 'slug' => 'bni-bouayach'],
            ['id' => 512815, 'region_id' => 783345, 'country_code' => 'MA', 'name' => 'Bni Hadifa‎', 'active' => 1, 'slug' => 'bni-hadifa'],
            ['id' => 512816, 'region_id' => 783345, 'country_code' => 'MA', 'name' => 'Ghafsai‎', 'active' => 1, 'slug' => 'ghafsai'],
            ['id' => 512817, 'region_id' => 783345, 'country_code' => 'MA', 'name' => 'Guercif‎', 'active' => 1, 'slug' => 'guercif'],
            ['id' => 512818, 'region_id' => 783345, 'country_code' => 'MA', 'name' => 'Imzouren‎', 'active' => 1, 'slug' => 'imzouren'],
            ['id' => 512819, 'region_id' => 783345, 'country_code' => 'MA', 'name' => 'Inahnahen‎', 'active' => 1, 'slug' => 'inahnahen'],
            ['id' => 512820, 'region_id' => 783345, 'country_code' => 'MA', 'name' => 'Issaguen (Ketama)‎', 'active' => 1, 'slug' => 'issaguen-ketama'],
            ['id' => 512821, 'region_id' => 783345, 'country_code' => 'MA', 'name' => 'Karia (El Jadida)‎', 'active' => 1, 'slug' => 'karia-el-jadida'],
            ['id' => 512822, 'region_id' => 783345, 'country_code' => 'MA', 'name' => 'Karia Ba Mohamed‎', 'active' => 1, 'slug' => 'karia-ba-mohamed'],
            ['id' => 512823, 'region_id' => 783345, 'country_code' => 'MA', 'name' => 'Oued Amlil‎', 'active' => 1, 'slug' => 'oued-amlil'],
            ['id' => 512824, 'region_id' => 783345, 'country_code' => 'MA', 'name' => 'Oulad Zbair‎', 'active' => 1, 'slug' => 'oulad-zbair'],
            ['id' => 512825, 'region_id' => 783345, 'country_code' => 'MA', 'name' => 'Tahla‎', 'active' => 1, 'slug' => 'tahla'],
            ['id' => 512826, 'region_id' => 783345, 'country_code' => 'MA', 'name' => 'Tala Tazegwaght‎', 'active' => 1, 'slug' => 'tala-tazegwaght'],
            ['id' => 512827, 'region_id' => 783345, 'country_code' => 'MA', 'name' => 'Tamassint‎', 'active' => 1, 'slug' => 'tamassint'],
            ['id' => 512828, 'region_id' => 783345, 'country_code' => 'MA', 'name' => 'Taounate‎', 'active' => 1, 'slug' => 'taounate'],
            ['id' => 512829, 'region_id' => 783345, 'country_code' => 'MA', 'name' => 'Targuist‎', 'active' => 1, 'slug' => 'targuist'],
            ['id' => 512830, 'region_id' => 783345, 'country_code' => 'MA', 'name' => 'Taza‎', 'active' => 1, 'slug' => 'taza'],
            ['id' => 512831, 'region_id' => 783345, 'country_code' => 'MA', 'name' => 'Taïnaste‎', 'active' => 1, 'slug' => 'tainaste'],
            ['id' => 512832, 'region_id' => 783345, 'country_code' => 'MA', 'name' => 'Thar Es-Souk‎', 'active' => 1, 'slug' => 'thar-es-souk'],
            ['id' => 512833, 'region_id' => 783345, 'country_code' => 'MA', 'name' => 'Tissa‎', 'active' => 1, 'slug' => 'tissa'],
            ['id' => 512834, 'region_id' => 783345, 'country_code' => 'MA', 'name' => 'Tizi Ouasli‎', 'active' => 1, 'slug' => 'tizi-ouasli'],
            ['id' => 512835, 'region_id' => 783346, 'country_code' => 'MA', 'name' => 'Laayoune‎', 'active' => 1, 'slug' => 'laayoune'],
            ['id' => 512836, 'region_id' => 783346, 'country_code' => 'MA', 'name' => 'El Marsa‎', 'active' => 1, 'slug' => 'el-marsa'],
            ['id' => 512837, 'region_id' => 783346, 'country_code' => 'MA', 'name' => 'Tarfaya‎', 'active' => 1, 'slug' => 'tarfaya'],
            ['id' => 512838, 'region_id' => 783346, 'country_code' => 'MA', 'name' => 'Boujdour‎', 'active' => 1, 'slug' => 'boujdour'],
            ['id' => 512839, 'region_id' => 783347, 'country_code' => 'MA', 'name' => 'Awsard', 'active' => 1, 'slug' => 'awsard'],
            ['id' => 512840, 'region_id' => 783347, 'country_code' => 'MA', 'name' => 'Oued-Eddahab ', 'active' => 1, 'slug' => 'oued-eddahab']
    	];
    }
}
