<?php

namespace Gerardojbaez\GeoData\Seeders;

use Illuminate\Database\Seeder;
use Gerardojbaez\GeoData\Models\Country;
use Gerardojbaez\GeoData\Models\Region;
use Gerardojbaez\GeoData\Models\City;

class NorwaySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Country::create($this->country());
        Region::insert($this->regions());

        if ($this->cities() > 4000)
        {
            foreach (array_chunk($this->cities(), 3500) as $chunk)
                City::insert($chunk);
        }
        else
        {
            City::insert($this->cities());
        }
    }

        /**
     * Get country.
     *
     * @return array
     */
    public function country()
    {
    	return ['code' => 'NO', 'name' => 'Norway', 'slug' => 'norway'];
    }

    /**
     * Get country regions.
     *
     * @return array
     */
    public function regions()
    {
    	return [
            ['id' => 780462, 'country_code' => 'NO', 'name' => 'Akershus', 'active' => 1, 'slug' => 'akershus'],
            ['id' => 780485, 'country_code' => 'NO', 'name' => 'Aust-agder', 'active' => 1, 'slug' => 'aust-agder'],
            ['id' => 780501, 'country_code' => 'NO', 'name' => 'Buskerud', 'active' => 1, 'slug' => 'buskerud'],
            ['id' => 780523, 'country_code' => 'NO', 'name' => 'Finnmark', 'active' => 1, 'slug' => 'finnmark'],
            ['id' => 780545, 'country_code' => 'NO', 'name' => 'Hedmark', 'active' => 1, 'slug' => 'hedmark'],
            ['id' => 780568, 'country_code' => 'NO', 'name' => 'Hordaland', 'active' => 1, 'slug' => 'hordaland'],
            ['id' => 780602, 'country_code' => 'NO', 'name' => 'Møre Og Romsdal', 'active' => 1, 'slug' => 'm%c3%b8re-og-romsdal'],
            ['id' => 780641, 'country_code' => 'NO', 'name' => 'Nordland', 'active' => 1, 'slug' => 'nordland'],
            ['id' => 780686, 'country_code' => 'NO', 'name' => 'Nord-trøndelag', 'active' => 1, 'slug' => 'nord-tr%c3%b8ndelag'],
            ['id' => 780711, 'country_code' => 'NO', 'name' => 'Oppland', 'active' => 1, 'slug' => 'oppland'],
            ['id' => 780739, 'country_code' => 'NO', 'name' => 'Oslo', 'active' => 1, 'slug' => 'oslo'],
            ['id' => 780765, 'country_code' => 'NO', 'name' => 'Østfold', 'active' => 1, 'slug' => '%c3%98stfold'],
            ['id' => 780784, 'country_code' => 'NO', 'name' => 'Rogaland', 'active' => 1, 'slug' => 'rogaland'],
            ['id' => 780811, 'country_code' => 'NO', 'name' => 'Sogn Og Fjordane', 'active' => 1, 'slug' => 'sogn-og-fjordane'],
            ['id' => 780838, 'country_code' => 'NO', 'name' => 'Sør-trøndelag', 'active' => 1, 'slug' => 's%c3%b8r-tr%c3%b8ndelag'],
            ['id' => 780864, 'country_code' => 'NO', 'name' => 'Telemark', 'active' => 1, 'slug' => 'telemark'],
            ['id' => 780883, 'country_code' => 'NO', 'name' => 'Troms', 'active' => 1, 'slug' => 'troms'],
            ['id' => 780909, 'country_code' => 'NO', 'name' => 'Vest-agder', 'active' => 1, 'slug' => 'vest-agder'],
            ['id' => 780925, 'country_code' => 'NO', 'name' => 'Vestfold', 'active' => 1, 'slug' => 'vestfold']
    	];
    }

    /**
     * Get region cities.
     *
     * @return array
     */
    public function cities()
    {
    	return [
            ['id' => 43836, 'region_id' => 780462, 'country_code' => 'NO', 'name' => 'Asker', 'active' => 1, 'slug' => 'asker'],
            ['id' => 43837, 'region_id' => 780462, 'country_code' => 'NO', 'name' => 'Aurskog-høland', 'active' => 1, 'slug' => 'aurskog-h%c3%b8land'],
            ['id' => 43838, 'region_id' => 780462, 'country_code' => 'NO', 'name' => 'Bærum', 'active' => 1, 'slug' => 'b%c3%a6rum'],
            ['id' => 43839, 'region_id' => 780462, 'country_code' => 'NO', 'name' => 'Eidsvoll', 'active' => 1, 'slug' => 'eidsvoll'],
            ['id' => 43840, 'region_id' => 780462, 'country_code' => 'NO', 'name' => 'Enebakk', 'active' => 1, 'slug' => 'enebakk'],
            ['id' => 43841, 'region_id' => 780462, 'country_code' => 'NO', 'name' => 'Fet', 'active' => 1, 'slug' => 'fet'],
            ['id' => 43842, 'region_id' => 780462, 'country_code' => 'NO', 'name' => 'Frogn', 'active' => 1, 'slug' => 'frogn'],
            ['id' => 43843, 'region_id' => 780462, 'country_code' => 'NO', 'name' => 'Gjerdrum', 'active' => 1, 'slug' => 'gjerdrum'],
            ['id' => 43844, 'region_id' => 780462, 'country_code' => 'NO', 'name' => 'Hurdal', 'active' => 1, 'slug' => 'hurdal'],
            ['id' => 43845, 'region_id' => 780462, 'country_code' => 'NO', 'name' => 'Lørenskog', 'active' => 1, 'slug' => 'l%c3%b8renskog'],
            ['id' => 43846, 'region_id' => 780462, 'country_code' => 'NO', 'name' => 'Nannestad', 'active' => 1, 'slug' => 'nannestad'],
            ['id' => 43847, 'region_id' => 780462, 'country_code' => 'NO', 'name' => 'Nes', 'active' => 1, 'slug' => 'nes'],
            ['id' => 43848, 'region_id' => 780462, 'country_code' => 'NO', 'name' => 'Nesodden', 'active' => 1, 'slug' => 'nesodden'],
            ['id' => 43849, 'region_id' => 780462, 'country_code' => 'NO', 'name' => 'Nittedal', 'active' => 1, 'slug' => 'nittedal'],
            ['id' => 43850, 'region_id' => 780462, 'country_code' => 'NO', 'name' => 'Oppegård', 'active' => 1, 'slug' => 'oppegard'],
            ['id' => 43851, 'region_id' => 780462, 'country_code' => 'NO', 'name' => 'Rælingen', 'active' => 1, 'slug' => 'r%c3%a6lingen'],
            ['id' => 43852, 'region_id' => 780462, 'country_code' => 'NO', 'name' => 'Skedsmo', 'active' => 1, 'slug' => 'skedsmo'],
            ['id' => 43853, 'region_id' => 780462, 'country_code' => 'NO', 'name' => 'Ski', 'active' => 1, 'slug' => 'ski'],
            ['id' => 43854, 'region_id' => 780462, 'country_code' => 'NO', 'name' => 'Sørum', 'active' => 1, 'slug' => 's%c3%b8rum'],
            ['id' => 43855, 'region_id' => 780462, 'country_code' => 'NO', 'name' => 'Ullensaker', 'active' => 1, 'slug' => 'ullensaker'],
            ['id' => 43856, 'region_id' => 780462, 'country_code' => 'NO', 'name' => 'Vestby', 'active' => 1, 'slug' => 'vestby'],
            ['id' => 43857, 'region_id' => 780462, 'country_code' => 'NO', 'name' => 'Ås', 'active' => 1, 'slug' => 'as'],
            ['id' => 43858, 'region_id' => 780485, 'country_code' => 'NO', 'name' => 'Åmli', 'active' => 1, 'slug' => 'amli'],
            ['id' => 43859, 'region_id' => 780485, 'country_code' => 'NO', 'name' => 'Arendal', 'active' => 1, 'slug' => 'arendal'],
            ['id' => 43860, 'region_id' => 780485, 'country_code' => 'NO', 'name' => 'Birkenes', 'active' => 1, 'slug' => 'birkenes'],
            ['id' => 43861, 'region_id' => 780485, 'country_code' => 'NO', 'name' => 'Bygland', 'active' => 1, 'slug' => 'bygland'],
            ['id' => 43862, 'region_id' => 780485, 'country_code' => 'NO', 'name' => 'Bykle', 'active' => 1, 'slug' => 'bykle'],
            ['id' => 43863, 'region_id' => 780485, 'country_code' => 'NO', 'name' => 'Evje Og Hornnes', 'active' => 1, 'slug' => 'evje-og-hornnes'],
            ['id' => 43864, 'region_id' => 780485, 'country_code' => 'NO', 'name' => 'Froland', 'active' => 1, 'slug' => 'froland'],
            ['id' => 43865, 'region_id' => 780485, 'country_code' => 'NO', 'name' => 'Gjerstad', 'active' => 1, 'slug' => 'gjerstad'],
            ['id' => 43866, 'region_id' => 780485, 'country_code' => 'NO', 'name' => 'Grimstad', 'active' => 1, 'slug' => 'grimstad'],
            ['id' => 43867, 'region_id' => 780485, 'country_code' => 'NO', 'name' => 'Iveland', 'active' => 1, 'slug' => 'iveland'],
            ['id' => 43868, 'region_id' => 780485, 'country_code' => 'NO', 'name' => 'Lillesand', 'active' => 1, 'slug' => 'lillesand'],
            ['id' => 43869, 'region_id' => 780485, 'country_code' => 'NO', 'name' => 'Risør', 'active' => 1, 'slug' => 'ris%c3%b8r'],
            ['id' => 43870, 'region_id' => 780485, 'country_code' => 'NO', 'name' => 'Tvedestrand', 'active' => 1, 'slug' => 'tvedestrand'],
            ['id' => 43871, 'region_id' => 780485, 'country_code' => 'NO', 'name' => 'Valle', 'active' => 1, 'slug' => 'valle'],
            ['id' => 43872, 'region_id' => 780485, 'country_code' => 'NO', 'name' => 'Vegårshei', 'active' => 1, 'slug' => 'vegarshei'],
            ['id' => 43873, 'region_id' => 780501, 'country_code' => 'NO', 'name' => 'Ål', 'active' => 1, 'slug' => 'al'],
            ['id' => 43874, 'region_id' => 780501, 'country_code' => 'NO', 'name' => 'Drammen', 'active' => 1, 'slug' => 'drammen'],
            ['id' => 43875, 'region_id' => 780501, 'country_code' => 'NO', 'name' => 'Flesberg', 'active' => 1, 'slug' => 'flesberg'],
            ['id' => 43876, 'region_id' => 780501, 'country_code' => 'NO', 'name' => 'Flå', 'active' => 1, 'slug' => 'fla'],
            ['id' => 43877, 'region_id' => 780501, 'country_code' => 'NO', 'name' => 'Gol', 'active' => 1, 'slug' => 'gol'],
            ['id' => 43878, 'region_id' => 780501, 'country_code' => 'NO', 'name' => 'Hemsedal', 'active' => 1, 'slug' => 'hemsedal'],
            ['id' => 43879, 'region_id' => 780501, 'country_code' => 'NO', 'name' => 'Hol', 'active' => 1, 'slug' => 'hol'],
            ['id' => 43880, 'region_id' => 780501, 'country_code' => 'NO', 'name' => 'Hole', 'active' => 1, 'slug' => 'hole'],
            ['id' => 43881, 'region_id' => 780501, 'country_code' => 'NO', 'name' => 'Hurum', 'active' => 1, 'slug' => 'hurum'],
            ['id' => 43882, 'region_id' => 780501, 'country_code' => 'NO', 'name' => 'Kongsberg', 'active' => 1, 'slug' => 'kongsberg'],
            ['id' => 43883, 'region_id' => 780501, 'country_code' => 'NO', 'name' => 'Krødsherad', 'active' => 1, 'slug' => 'kr%c3%b8dsherad'],
            ['id' => 43884, 'region_id' => 780501, 'country_code' => 'NO', 'name' => 'Lier', 'active' => 1, 'slug' => 'lier'],
            ['id' => 43885, 'region_id' => 780501, 'country_code' => 'NO', 'name' => 'Modum', 'active' => 1, 'slug' => 'modum'],
            ['id' => 43886, 'region_id' => 780501, 'country_code' => 'NO', 'name' => 'Nedre Eiker', 'active' => 1, 'slug' => 'nedre-eiker'],
            ['id' => 43887, 'region_id' => 780501, 'country_code' => 'NO', 'name' => 'Nes', 'active' => 1, 'slug' => 'nes'],
            ['id' => 43888, 'region_id' => 780501, 'country_code' => 'NO', 'name' => 'Nore Og Uvdal', 'active' => 1, 'slug' => 'nore-og-uvdal'],
            ['id' => 43889, 'region_id' => 780501, 'country_code' => 'NO', 'name' => 'Øvre Eiker', 'active' => 1, 'slug' => '%c3%98vre-eiker'],
            ['id' => 43890, 'region_id' => 780501, 'country_code' => 'NO', 'name' => 'Ringerike', 'active' => 1, 'slug' => 'ringerike'],
            ['id' => 43891, 'region_id' => 780501, 'country_code' => 'NO', 'name' => 'Rollag', 'active' => 1, 'slug' => 'rollag'],
            ['id' => 43892, 'region_id' => 780501, 'country_code' => 'NO', 'name' => 'Røyken', 'active' => 1, 'slug' => 'r%c3%b8yken'],
            ['id' => 43893, 'region_id' => 780501, 'country_code' => 'NO', 'name' => 'Sigdal', 'active' => 1, 'slug' => 'sigdal'],
            ['id' => 43894, 'region_id' => 780523, 'country_code' => 'NO', 'name' => 'Alta', 'active' => 1, 'slug' => 'alta'],
            ['id' => 43895, 'region_id' => 780523, 'country_code' => 'NO', 'name' => 'Batsfjord', 'active' => 1, 'slug' => 'batsfjord'],
            ['id' => 43896, 'region_id' => 780523, 'country_code' => 'NO', 'name' => 'Berlevag', 'active' => 1, 'slug' => 'berlevag'],
            ['id' => 43897, 'region_id' => 780523, 'country_code' => 'NO', 'name' => 'Hammerfest', 'active' => 1, 'slug' => 'hammerfest'],
            ['id' => 43898, 'region_id' => 780523, 'country_code' => 'NO', 'name' => 'Hasvik', 'active' => 1, 'slug' => 'hasvik'],
            ['id' => 43899, 'region_id' => 780523, 'country_code' => 'NO', 'name' => 'Havoysund', 'active' => 1, 'slug' => 'havoysund'],
            ['id' => 43900, 'region_id' => 780523, 'country_code' => 'NO', 'name' => 'Honningsvag', 'active' => 1, 'slug' => 'honningsvag'],
            ['id' => 43901, 'region_id' => 780523, 'country_code' => 'NO', 'name' => 'Kamoyvaer', 'active' => 1, 'slug' => 'kamoyvaer'],
            ['id' => 43902, 'region_id' => 780523, 'country_code' => 'NO', 'name' => 'Karasjok', 'active' => 1, 'slug' => 'karasjok'],
            ['id' => 43903, 'region_id' => 780523, 'country_code' => 'NO', 'name' => 'Kautokeino', 'active' => 1, 'slug' => 'kautokeino'],
            ['id' => 43904, 'region_id' => 780523, 'country_code' => 'NO', 'name' => 'Kirkenes', 'active' => 1, 'slug' => 'kirkenes'],
            ['id' => 43905, 'region_id' => 780523, 'country_code' => 'NO', 'name' => 'Lakselv', 'active' => 1, 'slug' => 'lakselv'],
            ['id' => 43906, 'region_id' => 780523, 'country_code' => 'NO', 'name' => 'Mehamn', 'active' => 1, 'slug' => 'mehamn'],
            ['id' => 43907, 'region_id' => 780523, 'country_code' => 'NO', 'name' => 'North Cape', 'active' => 1, 'slug' => 'north-cape'],
            ['id' => 43908, 'region_id' => 780523, 'country_code' => 'NO', 'name' => 'Oksfjord', 'active' => 1, 'slug' => 'oksfjord'],
            ['id' => 43909, 'region_id' => 780523, 'country_code' => 'NO', 'name' => 'Repvag', 'active' => 1, 'slug' => 'repvag'],
            ['id' => 43910, 'region_id' => 780523, 'country_code' => 'NO', 'name' => 'Skarsvag', 'active' => 1, 'slug' => 'skarsvag'],
            ['id' => 43911, 'region_id' => 780523, 'country_code' => 'NO', 'name' => 'Talvik', 'active' => 1, 'slug' => 'talvik'],
            ['id' => 43912, 'region_id' => 780523, 'country_code' => 'NO', 'name' => 'Tana', 'active' => 1, 'slug' => 'tana'],
            ['id' => 43913, 'region_id' => 780523, 'country_code' => 'NO', 'name' => 'Vadso', 'active' => 1, 'slug' => 'vadso'],
            ['id' => 43914, 'region_id' => 780523, 'country_code' => 'NO', 'name' => 'Vardo', 'active' => 1, 'slug' => 'vardo'],
            ['id' => 43915, 'region_id' => 780545, 'country_code' => 'NO', 'name' => 'Alvdal', 'active' => 1, 'slug' => 'alvdal'],
            ['id' => 43916, 'region_id' => 780545, 'country_code' => 'NO', 'name' => 'Eidskog', 'active' => 1, 'slug' => 'eidskog'],
            ['id' => 43917, 'region_id' => 780545, 'country_code' => 'NO', 'name' => 'Elverum', 'active' => 1, 'slug' => 'elverum'],
            ['id' => 43918, 'region_id' => 780545, 'country_code' => 'NO', 'name' => 'Engerdal', 'active' => 1, 'slug' => 'engerdal'],
            ['id' => 43919, 'region_id' => 780545, 'country_code' => 'NO', 'name' => 'Folldal', 'active' => 1, 'slug' => 'folldal'],
            ['id' => 43920, 'region_id' => 780545, 'country_code' => 'NO', 'name' => 'Grue', 'active' => 1, 'slug' => 'grue'],
            ['id' => 43921, 'region_id' => 780545, 'country_code' => 'NO', 'name' => 'Hamar', 'active' => 1, 'slug' => 'hamar'],
            ['id' => 43922, 'region_id' => 780545, 'country_code' => 'NO', 'name' => 'Kongsvinger', 'active' => 1, 'slug' => 'kongsvinger'],
            ['id' => 43923, 'region_id' => 780545, 'country_code' => 'NO', 'name' => 'Løten', 'active' => 1, 'slug' => 'l%c3%b8ten'],
            ['id' => 43924, 'region_id' => 780545, 'country_code' => 'NO', 'name' => 'Nord-odal', 'active' => 1, 'slug' => 'nord-odal'],
            ['id' => 43925, 'region_id' => 780545, 'country_code' => 'NO', 'name' => 'Os', 'active' => 1, 'slug' => 'os'],
            ['id' => 43926, 'region_id' => 780545, 'country_code' => 'NO', 'name' => 'Rendalen', 'active' => 1, 'slug' => 'rendalen'],
            ['id' => 43927, 'region_id' => 780545, 'country_code' => 'NO', 'name' => 'Ringsaker', 'active' => 1, 'slug' => 'ringsaker'],
            ['id' => 43928, 'region_id' => 780545, 'country_code' => 'NO', 'name' => 'Stange', 'active' => 1, 'slug' => 'stange'],
            ['id' => 43929, 'region_id' => 780545, 'country_code' => 'NO', 'name' => 'Stor-elvdal', 'active' => 1, 'slug' => 'stor-elvdal'],
            ['id' => 43930, 'region_id' => 780545, 'country_code' => 'NO', 'name' => 'Sør-odal', 'active' => 1, 'slug' => 's%c3%b8r-odal'],
            ['id' => 43931, 'region_id' => 780545, 'country_code' => 'NO', 'name' => 'Tolga', 'active' => 1, 'slug' => 'tolga'],
            ['id' => 43932, 'region_id' => 780545, 'country_code' => 'NO', 'name' => 'Trysil', 'active' => 1, 'slug' => 'trysil'],
            ['id' => 43933, 'region_id' => 780545, 'country_code' => 'NO', 'name' => 'Tynset', 'active' => 1, 'slug' => 'tynset'],
            ['id' => 43934, 'region_id' => 780545, 'country_code' => 'NO', 'name' => 'Våler', 'active' => 1, 'slug' => 'valer'],
            ['id' => 43935, 'region_id' => 780545, 'country_code' => 'NO', 'name' => 'Åmot', 'active' => 1, 'slug' => 'amot'],
            ['id' => 43936, 'region_id' => 780545, 'country_code' => 'NO', 'name' => 'Åsnes', 'active' => 1, 'slug' => 'asnes'],
            ['id' => 43937, 'region_id' => 780568, 'country_code' => 'NO', 'name' => 'Askøy', 'active' => 1, 'slug' => 'ask%c3%b8y'],
            ['id' => 43938, 'region_id' => 780568, 'country_code' => 'NO', 'name' => 'Austevoll', 'active' => 1, 'slug' => 'austevoll'],
            ['id' => 43939, 'region_id' => 780568, 'country_code' => 'NO', 'name' => 'Austrheim', 'active' => 1, 'slug' => 'austrheim'],
            ['id' => 43940, 'region_id' => 780568, 'country_code' => 'NO', 'name' => 'Bergen', 'active' => 1, 'slug' => 'bergen'],
            ['id' => 43941, 'region_id' => 780568, 'country_code' => 'NO', 'name' => 'Bømlo', 'active' => 1, 'slug' => 'b%c3%b8mlo'],
            ['id' => 43942, 'region_id' => 780568, 'country_code' => 'NO', 'name' => 'Eidfjord', 'active' => 1, 'slug' => 'eidfjord'],
            ['id' => 43943, 'region_id' => 780568, 'country_code' => 'NO', 'name' => 'Etne', 'active' => 1, 'slug' => 'etne'],
            ['id' => 43944, 'region_id' => 780568, 'country_code' => 'NO', 'name' => 'Fedje', 'active' => 1, 'slug' => 'fedje'],
            ['id' => 43945, 'region_id' => 780568, 'country_code' => 'NO', 'name' => 'Fitjar', 'active' => 1, 'slug' => 'fitjar'],
            ['id' => 43946, 'region_id' => 780568, 'country_code' => 'NO', 'name' => 'Fjell', 'active' => 1, 'slug' => 'fjell'],
            ['id' => 43947, 'region_id' => 780568, 'country_code' => 'NO', 'name' => 'Fusa', 'active' => 1, 'slug' => 'fusa'],
            ['id' => 43948, 'region_id' => 780568, 'country_code' => 'NO', 'name' => 'Granvin', 'active' => 1, 'slug' => 'granvin'],
            ['id' => 43949, 'region_id' => 780568, 'country_code' => 'NO', 'name' => 'Jondal', 'active' => 1, 'slug' => 'jondal'],
            ['id' => 43950, 'region_id' => 780568, 'country_code' => 'NO', 'name' => 'Kvam', 'active' => 1, 'slug' => 'kvam'],
            ['id' => 43951, 'region_id' => 780568, 'country_code' => 'NO', 'name' => 'Kvinnherad', 'active' => 1, 'slug' => 'kvinnherad'],
            ['id' => 43952, 'region_id' => 780568, 'country_code' => 'NO', 'name' => 'Lindås', 'active' => 1, 'slug' => 'lindas'],
            ['id' => 43953, 'region_id' => 780568, 'country_code' => 'NO', 'name' => 'Masfjorden', 'active' => 1, 'slug' => 'masfjorden'],
            ['id' => 43954, 'region_id' => 780568, 'country_code' => 'NO', 'name' => 'Meland', 'active' => 1, 'slug' => 'meland'],
            ['id' => 43955, 'region_id' => 780568, 'country_code' => 'NO', 'name' => 'Modalen', 'active' => 1, 'slug' => 'modalen'],
            ['id' => 43956, 'region_id' => 780568, 'country_code' => 'NO', 'name' => 'Odda', 'active' => 1, 'slug' => 'odda'],
            ['id' => 43957, 'region_id' => 780568, 'country_code' => 'NO', 'name' => 'Os', 'active' => 1, 'slug' => 'os'],
            ['id' => 43958, 'region_id' => 780568, 'country_code' => 'NO', 'name' => 'Osterøy', 'active' => 1, 'slug' => 'oster%c3%b8y'],
            ['id' => 43959, 'region_id' => 780568, 'country_code' => 'NO', 'name' => 'Øygarden', 'active' => 1, 'slug' => '%c3%98ygarden'],
            ['id' => 43960, 'region_id' => 780568, 'country_code' => 'NO', 'name' => 'Radøy', 'active' => 1, 'slug' => 'rad%c3%b8y'],
            ['id' => 43961, 'region_id' => 780568, 'country_code' => 'NO', 'name' => 'Samnanger', 'active' => 1, 'slug' => 'samnanger'],
            ['id' => 43962, 'region_id' => 780568, 'country_code' => 'NO', 'name' => 'Stord', 'active' => 1, 'slug' => 'stord'],
            ['id' => 43963, 'region_id' => 780568, 'country_code' => 'NO', 'name' => 'Sund', 'active' => 1, 'slug' => 'sund'],
            ['id' => 43964, 'region_id' => 780568, 'country_code' => 'NO', 'name' => 'Sveio', 'active' => 1, 'slug' => 'sveio'],
            ['id' => 43965, 'region_id' => 780568, 'country_code' => 'NO', 'name' => 'Tysnes', 'active' => 1, 'slug' => 'tysnes'],
            ['id' => 43966, 'region_id' => 780568, 'country_code' => 'NO', 'name' => 'Ullensvang', 'active' => 1, 'slug' => 'ullensvang'],
            ['id' => 43967, 'region_id' => 780568, 'country_code' => 'NO', 'name' => 'Ulvik', 'active' => 1, 'slug' => 'ulvik'],
            ['id' => 43968, 'region_id' => 780568, 'country_code' => 'NO', 'name' => 'Vaksdal', 'active' => 1, 'slug' => 'vaksdal'],
            ['id' => 43969, 'region_id' => 780568, 'country_code' => 'NO', 'name' => 'Voss', 'active' => 1, 'slug' => 'voss'],
            ['id' => 43970, 'region_id' => 780602, 'country_code' => 'NO', 'name' => 'Ålesund', 'active' => 1, 'slug' => 'alesund'],
            ['id' => 43971, 'region_id' => 780602, 'country_code' => 'NO', 'name' => 'Aukra', 'active' => 1, 'slug' => 'aukra'],
            ['id' => 43972, 'region_id' => 780602, 'country_code' => 'NO', 'name' => 'Aure', 'active' => 1, 'slug' => 'aure'],
            ['id' => 43973, 'region_id' => 780602, 'country_code' => 'NO', 'name' => 'Averøy', 'active' => 1, 'slug' => 'aver%c3%b8y'],
            ['id' => 43974, 'region_id' => 780602, 'country_code' => 'NO', 'name' => 'Eide', 'active' => 1, 'slug' => 'eide'],
            ['id' => 43975, 'region_id' => 780602, 'country_code' => 'NO', 'name' => 'Fræna', 'active' => 1, 'slug' => 'fr%c3%a6na'],
            ['id' => 43976, 'region_id' => 780602, 'country_code' => 'NO', 'name' => 'Frei', 'active' => 1, 'slug' => 'frei'],
            ['id' => 43977, 'region_id' => 780602, 'country_code' => 'NO', 'name' => 'Giske', 'active' => 1, 'slug' => 'giske'],
            ['id' => 43978, 'region_id' => 780602, 'country_code' => 'NO', 'name' => 'Gjemnes', 'active' => 1, 'slug' => 'gjemnes'],
            ['id' => 43979, 'region_id' => 780602, 'country_code' => 'NO', 'name' => 'Halsa', 'active' => 1, 'slug' => 'halsa'],
            ['id' => 43980, 'region_id' => 780602, 'country_code' => 'NO', 'name' => 'Haram', 'active' => 1, 'slug' => 'haram'],
            ['id' => 43981, 'region_id' => 780602, 'country_code' => 'NO', 'name' => 'Hareid', 'active' => 1, 'slug' => 'hareid'],
            ['id' => 43982, 'region_id' => 780602, 'country_code' => 'NO', 'name' => 'Herøy', 'active' => 1, 'slug' => 'her%c3%b8y'],
            ['id' => 43983, 'region_id' => 780602, 'country_code' => 'NO', 'name' => 'Kristiansund', 'active' => 1, 'slug' => 'kristiansund'],
            ['id' => 43984, 'region_id' => 780602, 'country_code' => 'NO', 'name' => 'Midsund', 'active' => 1, 'slug' => 'midsund'],
            ['id' => 43985, 'region_id' => 780602, 'country_code' => 'NO', 'name' => 'Molde', 'active' => 1, 'slug' => 'molde'],
            ['id' => 43986, 'region_id' => 780602, 'country_code' => 'NO', 'name' => 'Nesset', 'active' => 1, 'slug' => 'nesset'],
            ['id' => 43987, 'region_id' => 780602, 'country_code' => 'NO', 'name' => 'Norddal', 'active' => 1, 'slug' => 'norddal'],
            ['id' => 43988, 'region_id' => 780602, 'country_code' => 'NO', 'name' => 'Ørskog', 'active' => 1, 'slug' => '%c3%98rskog'],
            ['id' => 43989, 'region_id' => 780602, 'country_code' => 'NO', 'name' => 'Ørsta', 'active' => 1, 'slug' => '%c3%98rsta'],
            ['id' => 43990, 'region_id' => 780602, 'country_code' => 'NO', 'name' => 'Rauma', 'active' => 1, 'slug' => 'rauma'],
            ['id' => 43991, 'region_id' => 780602, 'country_code' => 'NO', 'name' => 'Rindal', 'active' => 1, 'slug' => 'rindal'],
            ['id' => 43992, 'region_id' => 780602, 'country_code' => 'NO', 'name' => 'Sande', 'active' => 1, 'slug' => 'sande'],
            ['id' => 43993, 'region_id' => 780602, 'country_code' => 'NO', 'name' => 'Sandøy', 'active' => 1, 'slug' => 'sand%c3%b8y'],
            ['id' => 43994, 'region_id' => 780602, 'country_code' => 'NO', 'name' => 'Skodje', 'active' => 1, 'slug' => 'skodje'],
            ['id' => 43995, 'region_id' => 780602, 'country_code' => 'NO', 'name' => 'Smøla', 'active' => 1, 'slug' => 'sm%c3%b8la'],
            ['id' => 43996, 'region_id' => 780602, 'country_code' => 'NO', 'name' => 'Stordal', 'active' => 1, 'slug' => 'stordal'],
            ['id' => 43997, 'region_id' => 780602, 'country_code' => 'NO', 'name' => 'Stranda', 'active' => 1, 'slug' => 'stranda'],
            ['id' => 43998, 'region_id' => 780602, 'country_code' => 'NO', 'name' => 'Sula', 'active' => 1, 'slug' => 'sula'],
            ['id' => 43999, 'region_id' => 780602, 'country_code' => 'NO', 'name' => 'Sunndal', 'active' => 1, 'slug' => 'sunndal'],
            ['id' => 44000, 'region_id' => 780602, 'country_code' => 'NO', 'name' => 'Surnadal', 'active' => 1, 'slug' => 'surnadal'],
            ['id' => 44001, 'region_id' => 780602, 'country_code' => 'NO', 'name' => 'Sykkylven', 'active' => 1, 'slug' => 'sykkylven'],
            ['id' => 44002, 'region_id' => 780602, 'country_code' => 'NO', 'name' => 'Tingvoll', 'active' => 1, 'slug' => 'tingvoll'],
            ['id' => 44003, 'region_id' => 780602, 'country_code' => 'NO', 'name' => 'Tustna', 'active' => 1, 'slug' => 'tustna'],
            ['id' => 44004, 'region_id' => 780602, 'country_code' => 'NO', 'name' => 'Ulstein', 'active' => 1, 'slug' => 'ulstein'],
            ['id' => 44005, 'region_id' => 780602, 'country_code' => 'NO', 'name' => 'Vanylven', 'active' => 1, 'slug' => 'vanylven'],
            ['id' => 44006, 'region_id' => 780602, 'country_code' => 'NO', 'name' => 'Vestnes', 'active' => 1, 'slug' => 'vestnes'],
            ['id' => 44007, 'region_id' => 780602, 'country_code' => 'NO', 'name' => 'Volda', 'active' => 1, 'slug' => 'volda'],
            ['id' => 44008, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Alstahaug', 'active' => 1, 'slug' => 'alstahaug'],
            ['id' => 44009, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Andøy', 'active' => 1, 'slug' => 'and%c3%b8y'],
            ['id' => 44010, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Ballangen', 'active' => 1, 'slug' => 'ballangen'],
            ['id' => 44011, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Beiarn', 'active' => 1, 'slug' => 'beiarn'],
            ['id' => 44012, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Bindal', 'active' => 1, 'slug' => 'bindal'],
            ['id' => 44013, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Bø', 'active' => 1, 'slug' => 'b%c3%b8'],
            ['id' => 44014, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Bodø', 'active' => 1, 'slug' => 'bod%c3%b8'],
            ['id' => 44015, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Brønnøy', 'active' => 1, 'slug' => 'br%c3%b8nn%c3%b8y'],
            ['id' => 44016, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Dønna', 'active' => 1, 'slug' => 'd%c3%b8nna'],
            ['id' => 44017, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Evenes', 'active' => 1, 'slug' => 'evenes'],
            ['id' => 44018, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Fauske', 'active' => 1, 'slug' => 'fauske'],
            ['id' => 44019, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Flakstad', 'active' => 1, 'slug' => 'flakstad'],
            ['id' => 44020, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Gildeskål', 'active' => 1, 'slug' => 'gildeskal'],
            ['id' => 44021, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Grane', 'active' => 1, 'slug' => 'grane'],
            ['id' => 44022, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Hadsel', 'active' => 1, 'slug' => 'hadsel'],
            ['id' => 44023, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Hamarøy', 'active' => 1, 'slug' => 'hamar%c3%b8y'],
            ['id' => 44024, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Hattfjelldal', 'active' => 1, 'slug' => 'hattfjelldal'],
            ['id' => 44025, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Hemnes', 'active' => 1, 'slug' => 'hemnes'],
            ['id' => 44026, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Herøy', 'active' => 1, 'slug' => 'her%c3%b8y'],
            ['id' => 44027, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Leirfjord', 'active' => 1, 'slug' => 'leirfjord'],
            ['id' => 44028, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Lødingen', 'active' => 1, 'slug' => 'l%c3%b8dingen'],
            ['id' => 44029, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Lurøy', 'active' => 1, 'slug' => 'lur%c3%b8y'],
            ['id' => 44030, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Meløy', 'active' => 1, 'slug' => 'mel%c3%b8y'],
            ['id' => 44031, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Moskenes', 'active' => 1, 'slug' => 'moskenes'],
            ['id' => 44032, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Narvik', 'active' => 1, 'slug' => 'narvik'],
            ['id' => 44033, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Nesna', 'active' => 1, 'slug' => 'nesna'],
            ['id' => 44034, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Øksnes', 'active' => 1, 'slug' => '%c3%98ksnes'],
            ['id' => 44035, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Rana', 'active' => 1, 'slug' => 'rana'],
            ['id' => 44036, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Rødøy', 'active' => 1, 'slug' => 'r%c3%b8d%c3%b8y'],
            ['id' => 44037, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Røst', 'active' => 1, 'slug' => 'r%c3%b8st'],
            ['id' => 44038, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Saltdal', 'active' => 1, 'slug' => 'saltdal'],
            ['id' => 44039, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Sømna', 'active' => 1, 'slug' => 's%c3%b8mna'],
            ['id' => 44040, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Sørfold', 'active' => 1, 'slug' => 's%c3%b8rfold'],
            ['id' => 44041, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Sortland', 'active' => 1, 'slug' => 'sortland'],
            ['id' => 44042, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Steigen', 'active' => 1, 'slug' => 'steigen'],
            ['id' => 44043, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Tjeldsund', 'active' => 1, 'slug' => 'tjeldsund'],
            ['id' => 44044, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Træna', 'active' => 1, 'slug' => 'tr%c3%a6na'],
            ['id' => 44045, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Tysfjord', 'active' => 1, 'slug' => 'tysfjord'],
            ['id' => 44046, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Værøy', 'active' => 1, 'slug' => 'v%c3%a6r%c3%b8y'],
            ['id' => 44047, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Vågan', 'active' => 1, 'slug' => 'vagan'],
            ['id' => 44048, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Vefsn', 'active' => 1, 'slug' => 'vefsn'],
            ['id' => 44049, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Vega', 'active' => 1, 'slug' => 'vega'],
            ['id' => 44050, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Vestvågøy', 'active' => 1, 'slug' => 'vestvag%c3%b8y'],
            ['id' => 44051, 'region_id' => 780641, 'country_code' => 'NO', 'name' => 'Vevelstad', 'active' => 1, 'slug' => 'vevelstad'],
            ['id' => 44052, 'region_id' => 780686, 'country_code' => 'NO', 'name' => 'Flatanger', 'active' => 1, 'slug' => 'flatanger'],
            ['id' => 44053, 'region_id' => 780686, 'country_code' => 'NO', 'name' => 'Fosnes', 'active' => 1, 'slug' => 'fosnes'],
            ['id' => 44054, 'region_id' => 780686, 'country_code' => 'NO', 'name' => 'Frosta', 'active' => 1, 'slug' => 'frosta'],
            ['id' => 44055, 'region_id' => 780686, 'country_code' => 'NO', 'name' => 'Grong', 'active' => 1, 'slug' => 'grong'],
            ['id' => 44056, 'region_id' => 780686, 'country_code' => 'NO', 'name' => 'Høylandet', 'active' => 1, 'slug' => 'h%c3%b8ylandet'],
            ['id' => 44057, 'region_id' => 780686, 'country_code' => 'NO', 'name' => 'Inderøy', 'active' => 1, 'slug' => 'inder%c3%b8y'],
            ['id' => 44058, 'region_id' => 780686, 'country_code' => 'NO', 'name' => 'Leka', 'active' => 1, 'slug' => 'leka'],
            ['id' => 44059, 'region_id' => 780686, 'country_code' => 'NO', 'name' => 'Leksvik', 'active' => 1, 'slug' => 'leksvik'],
            ['id' => 44060, 'region_id' => 780686, 'country_code' => 'NO', 'name' => 'Levanger', 'active' => 1, 'slug' => 'levanger'],
            ['id' => 44061, 'region_id' => 780686, 'country_code' => 'NO', 'name' => 'Lierne', 'active' => 1, 'slug' => 'lierne'],
            ['id' => 44062, 'region_id' => 780686, 'country_code' => 'NO', 'name' => 'Meråker', 'active' => 1, 'slug' => 'meraker'],
            ['id' => 44063, 'region_id' => 780686, 'country_code' => 'NO', 'name' => 'Mosvik', 'active' => 1, 'slug' => 'mosvik'],
            ['id' => 44064, 'region_id' => 780686, 'country_code' => 'NO', 'name' => 'Nærøy', 'active' => 1, 'slug' => 'n%c3%a6r%c3%b8y'],
            ['id' => 44065, 'region_id' => 780686, 'country_code' => 'NO', 'name' => 'Namdalseid', 'active' => 1, 'slug' => 'namdalseid'],
            ['id' => 44066, 'region_id' => 780686, 'country_code' => 'NO', 'name' => 'Namsos', 'active' => 1, 'slug' => 'namsos'],
            ['id' => 44067, 'region_id' => 780686, 'country_code' => 'NO', 'name' => 'Namsskogan', 'active' => 1, 'slug' => 'namsskogan'],
            ['id' => 44068, 'region_id' => 780686, 'country_code' => 'NO', 'name' => 'Overhalla', 'active' => 1, 'slug' => 'overhalla'],
            ['id' => 44069, 'region_id' => 780686, 'country_code' => 'NO', 'name' => 'Røyrvik', 'active' => 1, 'slug' => 'r%c3%b8yrvik'],
            ['id' => 44070, 'region_id' => 780686, 'country_code' => 'NO', 'name' => 'Snåsa', 'active' => 1, 'slug' => 'snasa'],
            ['id' => 44071, 'region_id' => 780686, 'country_code' => 'NO', 'name' => 'Steinkjer', 'active' => 1, 'slug' => 'steinkjer'],
            ['id' => 44072, 'region_id' => 780686, 'country_code' => 'NO', 'name' => 'Stjørdal', 'active' => 1, 'slug' => 'stj%c3%b8rdal'],
            ['id' => 44073, 'region_id' => 780686, 'country_code' => 'NO', 'name' => 'Verdal', 'active' => 1, 'slug' => 'verdal'],
            ['id' => 44074, 'region_id' => 780686, 'country_code' => 'NO', 'name' => 'Verran', 'active' => 1, 'slug' => 'verran'],
            ['id' => 44075, 'region_id' => 780686, 'country_code' => 'NO', 'name' => 'Vikna', 'active' => 1, 'slug' => 'vikna'],
            ['id' => 44076, 'region_id' => 780711, 'country_code' => 'NO', 'name' => 'Dovre', 'active' => 1, 'slug' => 'dovre'],
            ['id' => 44077, 'region_id' => 780711, 'country_code' => 'NO', 'name' => 'Etnedal', 'active' => 1, 'slug' => 'etnedal'],
            ['id' => 44078, 'region_id' => 780711, 'country_code' => 'NO', 'name' => 'Gausdal', 'active' => 1, 'slug' => 'gausdal'],
            ['id' => 44079, 'region_id' => 780711, 'country_code' => 'NO', 'name' => 'Gjøvik', 'active' => 1, 'slug' => 'gj%c3%b8vik'],
            ['id' => 44080, 'region_id' => 780711, 'country_code' => 'NO', 'name' => 'Gran', 'active' => 1, 'slug' => 'gran'],
            ['id' => 44081, 'region_id' => 780711, 'country_code' => 'NO', 'name' => 'Jevnaker', 'active' => 1, 'slug' => 'jevnaker'],
            ['id' => 44082, 'region_id' => 780711, 'country_code' => 'NO', 'name' => 'Lesja', 'active' => 1, 'slug' => 'lesja'],
            ['id' => 44083, 'region_id' => 780711, 'country_code' => 'NO', 'name' => 'Lillehammer', 'active' => 1, 'slug' => 'lillehammer'],
            ['id' => 44084, 'region_id' => 780711, 'country_code' => 'NO', 'name' => 'Lom', 'active' => 1, 'slug' => 'lom'],
            ['id' => 44085, 'region_id' => 780711, 'country_code' => 'NO', 'name' => 'Lunner', 'active' => 1, 'slug' => 'lunner'],
            ['id' => 44086, 'region_id' => 780711, 'country_code' => 'NO', 'name' => 'Nord-aurdal', 'active' => 1, 'slug' => 'nord-aurdal'],
            ['id' => 44087, 'region_id' => 780711, 'country_code' => 'NO', 'name' => 'Nord-fron', 'active' => 1, 'slug' => 'nord-fron'],
            ['id' => 44088, 'region_id' => 780711, 'country_code' => 'NO', 'name' => 'Nordre Land', 'active' => 1, 'slug' => 'nordre-land'],
            ['id' => 44089, 'region_id' => 780711, 'country_code' => 'NO', 'name' => 'Østre Toten', 'active' => 1, 'slug' => '%c3%98stre-toten'],
            ['id' => 44090, 'region_id' => 780711, 'country_code' => 'NO', 'name' => 'Øyer', 'active' => 1, 'slug' => '%c3%98yer'],
            ['id' => 44091, 'region_id' => 780711, 'country_code' => 'NO', 'name' => 'Øystre Slidre', 'active' => 1, 'slug' => '%c3%98ystre-slidre'],
            ['id' => 44092, 'region_id' => 780711, 'country_code' => 'NO', 'name' => 'Ringebu', 'active' => 1, 'slug' => 'ringebu'],
            ['id' => 44093, 'region_id' => 780711, 'country_code' => 'NO', 'name' => 'Sel', 'active' => 1, 'slug' => 'sel'],
            ['id' => 44094, 'region_id' => 780711, 'country_code' => 'NO', 'name' => 'Skjåk', 'active' => 1, 'slug' => 'skjak'],
            ['id' => 44095, 'region_id' => 780711, 'country_code' => 'NO', 'name' => 'Søndre Land', 'active' => 1, 'slug' => 's%c3%b8ndre-land'],
            ['id' => 44096, 'region_id' => 780711, 'country_code' => 'NO', 'name' => 'Sør-aurdal', 'active' => 1, 'slug' => 's%c3%b8r-aurdal'],
            ['id' => 44097, 'region_id' => 780711, 'country_code' => 'NO', 'name' => 'Sør-fron', 'active' => 1, 'slug' => 's%c3%b8r-fron'],
            ['id' => 44098, 'region_id' => 780711, 'country_code' => 'NO', 'name' => 'Vågå', 'active' => 1, 'slug' => 'vaga'],
            ['id' => 44099, 'region_id' => 780711, 'country_code' => 'NO', 'name' => 'Vang', 'active' => 1, 'slug' => 'vang'],
            ['id' => 44100, 'region_id' => 780711, 'country_code' => 'NO', 'name' => 'Vestre Slidre', 'active' => 1, 'slug' => 'vestre-slidre'],
            ['id' => 44101, 'region_id' => 780711, 'country_code' => 'NO', 'name' => 'Vestre Toten', 'active' => 1, 'slug' => 'vestre-toten'],
            ['id' => 44102, 'region_id' => 780739, 'country_code' => 'NO', 'name' => 'Bjerke', 'active' => 1, 'slug' => 'bjerke'],
            ['id' => 44103, 'region_id' => 780739, 'country_code' => 'NO', 'name' => 'Bygdøy-frogner', 'active' => 1, 'slug' => 'bygd%c3%b8y-frogner'],
            ['id' => 44104, 'region_id' => 780739, 'country_code' => 'NO', 'name' => 'Bøler', 'active' => 1, 'slug' => 'b%c3%b8ler'],
            ['id' => 44105, 'region_id' => 780739, 'country_code' => 'NO', 'name' => 'Ekeberg-bekkelaget', 'active' => 1, 'slug' => 'ekeberg-bekkelaget'],
            ['id' => 44106, 'region_id' => 780739, 'country_code' => 'NO', 'name' => 'Furuset', 'active' => 1, 'slug' => 'furuset'],
            ['id' => 44107, 'region_id' => 780739, 'country_code' => 'NO', 'name' => 'Gamle Oslo', 'active' => 1, 'slug' => 'gamle-oslo'],
            ['id' => 44108, 'region_id' => 780739, 'country_code' => 'NO', 'name' => 'Grefsen-kjelsås', 'active' => 1, 'slug' => 'grefsen-kjelsas'],
            ['id' => 44109, 'region_id' => 780739, 'country_code' => 'NO', 'name' => 'Grorud', 'active' => 1, 'slug' => 'grorud'],
            ['id' => 44110, 'region_id' => 780739, 'country_code' => 'NO', 'name' => 'Grünerløkka-sofienberg', 'active' => 1, 'slug' => 'grunerl%c3%b8kka-sofienberg'],
            ['id' => 44111, 'region_id' => 780739, 'country_code' => 'NO', 'name' => 'Hellerud', 'active' => 1, 'slug' => 'hellerud'],
            ['id' => 44112, 'region_id' => 780739, 'country_code' => 'NO', 'name' => 'Helsfyr-sinsen', 'active' => 1, 'slug' => 'helsfyr-sinsen'],
            ['id' => 44113, 'region_id' => 780739, 'country_code' => 'NO', 'name' => 'Lambertseter', 'active' => 1, 'slug' => 'lambertseter'],
            ['id' => 44114, 'region_id' => 780739, 'country_code' => 'NO', 'name' => 'Manglerud', 'active' => 1, 'slug' => 'manglerud'],
            ['id' => 44115, 'region_id' => 780739, 'country_code' => 'NO', 'name' => 'Nordstrand', 'active' => 1, 'slug' => 'nordstrand'],
            ['id' => 44116, 'region_id' => 780739, 'country_code' => 'NO', 'name' => 'Romsås', 'active' => 1, 'slug' => 'romsas'],
            ['id' => 44117, 'region_id' => 780739, 'country_code' => 'NO', 'name' => 'Røa', 'active' => 1, 'slug' => 'r%c3%b8a'],
            ['id' => 44118, 'region_id' => 780739, 'country_code' => 'NO', 'name' => 'Sagene-torshov', 'active' => 1, 'slug' => 'sagene-torshov'],
            ['id' => 44119, 'region_id' => 780739, 'country_code' => 'NO', 'name' => 'Sogn', 'active' => 1, 'slug' => 'sogn'],
            ['id' => 44120, 'region_id' => 780739, 'country_code' => 'NO', 'name' => 'St. Hanshaugen-ullevål', 'active' => 1, 'slug' => 'st-hanshaugen-ulleval'],
            ['id' => 44121, 'region_id' => 780739, 'country_code' => 'NO', 'name' => 'Stovner', 'active' => 1, 'slug' => 'stovner'],
            ['id' => 44122, 'region_id' => 780739, 'country_code' => 'NO', 'name' => 'Søndre Nordstrand', 'active' => 1, 'slug' => 's%c3%b8ndre-nordstrand'],
            ['id' => 44123, 'region_id' => 780739, 'country_code' => 'NO', 'name' => 'Ullern', 'active' => 1, 'slug' => 'ullern'],
            ['id' => 44124, 'region_id' => 780739, 'country_code' => 'NO', 'name' => 'Uranienborg-majorstuen', 'active' => 1, 'slug' => 'uranienborg-majorstuen'],
            ['id' => 44125, 'region_id' => 780739, 'country_code' => 'NO', 'name' => 'Vinderen', 'active' => 1, 'slug' => 'vinderen'],
            ['id' => 44126, 'region_id' => 780739, 'country_code' => 'NO', 'name' => 'Østensjø', 'active' => 1, 'slug' => '%c3%98stensj%c3%b8'],
            ['id' => 44127, 'region_id' => 780765, 'country_code' => 'NO', 'name' => 'Aremark', 'active' => 1, 'slug' => 'aremark'],
            ['id' => 44128, 'region_id' => 780765, 'country_code' => 'NO', 'name' => 'Askim', 'active' => 1, 'slug' => 'askim'],
            ['id' => 44129, 'region_id' => 780765, 'country_code' => 'NO', 'name' => 'Eidsberg', 'active' => 1, 'slug' => 'eidsberg'],
            ['id' => 44130, 'region_id' => 780765, 'country_code' => 'NO', 'name' => 'Fredrikstad', 'active' => 1, 'slug' => 'fredrikstad'],
            ['id' => 44131, 'region_id' => 780765, 'country_code' => 'NO', 'name' => 'Halden', 'active' => 1, 'slug' => 'halden'],
            ['id' => 44132, 'region_id' => 780765, 'country_code' => 'NO', 'name' => 'Hobøl', 'active' => 1, 'slug' => 'hob%c3%b8l'],
            ['id' => 44133, 'region_id' => 780765, 'country_code' => 'NO', 'name' => 'Hvaler', 'active' => 1, 'slug' => 'hvaler'],
            ['id' => 44134, 'region_id' => 780765, 'country_code' => 'NO', 'name' => 'Marker', 'active' => 1, 'slug' => 'marker'],
            ['id' => 44135, 'region_id' => 780765, 'country_code' => 'NO', 'name' => 'Moss', 'active' => 1, 'slug' => 'moss'],
            ['id' => 44136, 'region_id' => 780765, 'country_code' => 'NO', 'name' => 'Rakkestad', 'active' => 1, 'slug' => 'rakkestad'],
            ['id' => 44137, 'region_id' => 780765, 'country_code' => 'NO', 'name' => 'Rygge', 'active' => 1, 'slug' => 'rygge'],
            ['id' => 44138, 'region_id' => 780765, 'country_code' => 'NO', 'name' => 'Rømskog', 'active' => 1, 'slug' => 'r%c3%b8mskog'],
            ['id' => 44139, 'region_id' => 780765, 'country_code' => 'NO', 'name' => 'Råde', 'active' => 1, 'slug' => 'rade'],
            ['id' => 44140, 'region_id' => 780765, 'country_code' => 'NO', 'name' => 'Sarpsborg', 'active' => 1, 'slug' => 'sarpsborg'],
            ['id' => 44141, 'region_id' => 780765, 'country_code' => 'NO', 'name' => 'Skiptvet', 'active' => 1, 'slug' => 'skiptvet'],
            ['id' => 44142, 'region_id' => 780765, 'country_code' => 'NO', 'name' => 'Spydeberg', 'active' => 1, 'slug' => 'spydeberg'],
            ['id' => 44143, 'region_id' => 780765, 'country_code' => 'NO', 'name' => 'Trøgstad', 'active' => 1, 'slug' => 'tr%c3%b8gstad'],
            ['id' => 44144, 'region_id' => 780765, 'country_code' => 'NO', 'name' => 'Våler', 'active' => 1, 'slug' => 'valer'],
            ['id' => 44145, 'region_id' => 780784, 'country_code' => 'NO', 'name' => 'Bjerkreim', 'active' => 1, 'slug' => 'bjerkreim'],
            ['id' => 44146, 'region_id' => 780784, 'country_code' => 'NO', 'name' => 'Bokn', 'active' => 1, 'slug' => 'bokn'],
            ['id' => 44147, 'region_id' => 780784, 'country_code' => 'NO', 'name' => 'Eigersund', 'active' => 1, 'slug' => 'eigersund'],
            ['id' => 44148, 'region_id' => 780784, 'country_code' => 'NO', 'name' => 'Finnøy', 'active' => 1, 'slug' => 'finn%c3%b8y'],
            ['id' => 44149, 'region_id' => 780784, 'country_code' => 'NO', 'name' => 'Forsand', 'active' => 1, 'slug' => 'forsand'],
            ['id' => 44150, 'region_id' => 780784, 'country_code' => 'NO', 'name' => 'Gjesdal', 'active' => 1, 'slug' => 'gjesdal'],
            ['id' => 44151, 'region_id' => 780784, 'country_code' => 'NO', 'name' => 'Haugesund', 'active' => 1, 'slug' => 'haugesund'],
            ['id' => 44152, 'region_id' => 780784, 'country_code' => 'NO', 'name' => 'Hjelmeland', 'active' => 1, 'slug' => 'hjelmeland'],
            ['id' => 44153, 'region_id' => 780784, 'country_code' => 'NO', 'name' => 'Hå', 'active' => 1, 'slug' => 'ha'],
            ['id' => 44154, 'region_id' => 780784, 'country_code' => 'NO', 'name' => 'Karmøy', 'active' => 1, 'slug' => 'karm%c3%b8y'],
            ['id' => 44155, 'region_id' => 780784, 'country_code' => 'NO', 'name' => 'Klepp', 'active' => 1, 'slug' => 'klepp'],
            ['id' => 44156, 'region_id' => 780784, 'country_code' => 'NO', 'name' => 'Kvitsøy', 'active' => 1, 'slug' => 'kvits%c3%b8y'],
            ['id' => 44157, 'region_id' => 780784, 'country_code' => 'NO', 'name' => 'Lund', 'active' => 1, 'slug' => 'lund'],
            ['id' => 44158, 'region_id' => 780784, 'country_code' => 'NO', 'name' => 'Randaberg', 'active' => 1, 'slug' => 'randaberg'],
            ['id' => 44159, 'region_id' => 780784, 'country_code' => 'NO', 'name' => 'Rennesøy', 'active' => 1, 'slug' => 'rennes%c3%b8y'],
            ['id' => 44160, 'region_id' => 780784, 'country_code' => 'NO', 'name' => 'Sandnes', 'active' => 1, 'slug' => 'sandnes'],
            ['id' => 44161, 'region_id' => 780784, 'country_code' => 'NO', 'name' => 'Sauda', 'active' => 1, 'slug' => 'sauda'],
            ['id' => 44162, 'region_id' => 780784, 'country_code' => 'NO', 'name' => 'Sokndal', 'active' => 1, 'slug' => 'sokndal'],
            ['id' => 44163, 'region_id' => 780784, 'country_code' => 'NO', 'name' => 'Sola', 'active' => 1, 'slug' => 'sola'],
            ['id' => 44164, 'region_id' => 780784, 'country_code' => 'NO', 'name' => 'Stavanger', 'active' => 1, 'slug' => 'stavanger'],
            ['id' => 44165, 'region_id' => 780784, 'country_code' => 'NO', 'name' => 'Strand', 'active' => 1, 'slug' => 'strand'],
            ['id' => 44166, 'region_id' => 780784, 'country_code' => 'NO', 'name' => 'Suldal', 'active' => 1, 'slug' => 'suldal'],
            ['id' => 44167, 'region_id' => 780784, 'country_code' => 'NO', 'name' => 'Time', 'active' => 1, 'slug' => 'time'],
            ['id' => 44168, 'region_id' => 780784, 'country_code' => 'NO', 'name' => 'Tysvær', 'active' => 1, 'slug' => 'tysv%c3%a6r'],
            ['id' => 44169, 'region_id' => 780784, 'country_code' => 'NO', 'name' => 'Utsira', 'active' => 1, 'slug' => 'utsira'],
            ['id' => 44170, 'region_id' => 780784, 'country_code' => 'NO', 'name' => 'Vindafjord', 'active' => 1, 'slug' => 'vindafjord'],
            ['id' => 44171, 'region_id' => 780811, 'country_code' => 'NO', 'name' => 'Årdal', 'active' => 1, 'slug' => 'ardal'],
            ['id' => 44172, 'region_id' => 780811, 'country_code' => 'NO', 'name' => 'Askvoll', 'active' => 1, 'slug' => 'askvoll'],
            ['id' => 44173, 'region_id' => 780811, 'country_code' => 'NO', 'name' => 'Aurland', 'active' => 1, 'slug' => 'aurland'],
            ['id' => 44174, 'region_id' => 780811, 'country_code' => 'NO', 'name' => 'Balestrand', 'active' => 1, 'slug' => 'balestrand'],
            ['id' => 44175, 'region_id' => 780811, 'country_code' => 'NO', 'name' => 'Bremanger', 'active' => 1, 'slug' => 'bremanger'],
            ['id' => 44176, 'region_id' => 780811, 'country_code' => 'NO', 'name' => 'Eid', 'active' => 1, 'slug' => 'eid'],
            ['id' => 44177, 'region_id' => 780811, 'country_code' => 'NO', 'name' => 'Fjaler', 'active' => 1, 'slug' => 'fjaler'],
            ['id' => 44178, 'region_id' => 780811, 'country_code' => 'NO', 'name' => 'Flora', 'active' => 1, 'slug' => 'flora'],
            ['id' => 44179, 'region_id' => 780811, 'country_code' => 'NO', 'name' => 'Førde', 'active' => 1, 'slug' => 'f%c3%b8rde'],
            ['id' => 44180, 'region_id' => 780811, 'country_code' => 'NO', 'name' => 'Gaular', 'active' => 1, 'slug' => 'gaular'],
            ['id' => 44181, 'region_id' => 780811, 'country_code' => 'NO', 'name' => 'Gloppen', 'active' => 1, 'slug' => 'gloppen'],
            ['id' => 44182, 'region_id' => 780811, 'country_code' => 'NO', 'name' => 'Gulen', 'active' => 1, 'slug' => 'gulen'],
            ['id' => 44183, 'region_id' => 780811, 'country_code' => 'NO', 'name' => 'Hornindal', 'active' => 1, 'slug' => 'hornindal'],
            ['id' => 44184, 'region_id' => 780811, 'country_code' => 'NO', 'name' => 'Høyanger', 'active' => 1, 'slug' => 'h%c3%b8yanger'],
            ['id' => 44185, 'region_id' => 780811, 'country_code' => 'NO', 'name' => 'Hyllestad', 'active' => 1, 'slug' => 'hyllestad'],
            ['id' => 44186, 'region_id' => 780811, 'country_code' => 'NO', 'name' => 'Jølster', 'active' => 1, 'slug' => 'j%c3%b8lster'],
            ['id' => 44187, 'region_id' => 780811, 'country_code' => 'NO', 'name' => 'Lærdal', 'active' => 1, 'slug' => 'l%c3%a6rdal'],
            ['id' => 44188, 'region_id' => 780811, 'country_code' => 'NO', 'name' => 'Leikanger', 'active' => 1, 'slug' => 'leikanger'],
            ['id' => 44189, 'region_id' => 780811, 'country_code' => 'NO', 'name' => 'Luster', 'active' => 1, 'slug' => 'luster'],
            ['id' => 44190, 'region_id' => 780811, 'country_code' => 'NO', 'name' => 'Naustdal', 'active' => 1, 'slug' => 'naustdal'],
            ['id' => 44191, 'region_id' => 780811, 'country_code' => 'NO', 'name' => 'Selje', 'active' => 1, 'slug' => 'selje'],
            ['id' => 44192, 'region_id' => 780811, 'country_code' => 'NO', 'name' => 'Sogndal', 'active' => 1, 'slug' => 'sogndal'],
            ['id' => 44193, 'region_id' => 780811, 'country_code' => 'NO', 'name' => 'Solund', 'active' => 1, 'slug' => 'solund'],
            ['id' => 44194, 'region_id' => 780811, 'country_code' => 'NO', 'name' => 'Stryn', 'active' => 1, 'slug' => 'stryn'],
            ['id' => 44195, 'region_id' => 780811, 'country_code' => 'NO', 'name' => 'Vågsøy', 'active' => 1, 'slug' => 'vags%c3%b8y'],
            ['id' => 44196, 'region_id' => 780811, 'country_code' => 'NO', 'name' => 'Vik', 'active' => 1, 'slug' => 'vik'],
            ['id' => 44197, 'region_id' => 780838, 'country_code' => 'NO', 'name' => 'Åfjord', 'active' => 1, 'slug' => 'afjord'],
            ['id' => 44198, 'region_id' => 780838, 'country_code' => 'NO', 'name' => 'Agdenes', 'active' => 1, 'slug' => 'agdenes'],
            ['id' => 44199, 'region_id' => 780838, 'country_code' => 'NO', 'name' => 'Bjugn', 'active' => 1, 'slug' => 'bjugn'],
            ['id' => 44200, 'region_id' => 780838, 'country_code' => 'NO', 'name' => 'Frøya', 'active' => 1, 'slug' => 'fr%c3%b8ya'],
            ['id' => 44201, 'region_id' => 780838, 'country_code' => 'NO', 'name' => 'Hemne', 'active' => 1, 'slug' => 'hemne'],
            ['id' => 44202, 'region_id' => 780838, 'country_code' => 'NO', 'name' => 'Hitra', 'active' => 1, 'slug' => 'hitra'],
            ['id' => 44203, 'region_id' => 780838, 'country_code' => 'NO', 'name' => 'Holtålen', 'active' => 1, 'slug' => 'holtalen'],
            ['id' => 44204, 'region_id' => 780838, 'country_code' => 'NO', 'name' => 'Klæbu', 'active' => 1, 'slug' => 'kl%c3%a6bu'],
            ['id' => 44205, 'region_id' => 780838, 'country_code' => 'NO', 'name' => 'Malvik', 'active' => 1, 'slug' => 'malvik'],
            ['id' => 44206, 'region_id' => 780838, 'country_code' => 'NO', 'name' => 'Meldal', 'active' => 1, 'slug' => 'meldal'],
            ['id' => 44207, 'region_id' => 780838, 'country_code' => 'NO', 'name' => 'Melhus', 'active' => 1, 'slug' => 'melhus'],
            ['id' => 44208, 'region_id' => 780838, 'country_code' => 'NO', 'name' => 'Midtre Gauldal', 'active' => 1, 'slug' => 'midtre-gauldal'],
            ['id' => 44209, 'region_id' => 780838, 'country_code' => 'NO', 'name' => 'Oppdal', 'active' => 1, 'slug' => 'oppdal'],
            ['id' => 44210, 'region_id' => 780838, 'country_code' => 'NO', 'name' => 'Orkdal', 'active' => 1, 'slug' => 'orkdal'],
            ['id' => 44211, 'region_id' => 780838, 'country_code' => 'NO', 'name' => 'Ørland', 'active' => 1, 'slug' => '%c3%98rland'],
            ['id' => 44212, 'region_id' => 780838, 'country_code' => 'NO', 'name' => 'Osen', 'active' => 1, 'slug' => 'osen'],
            ['id' => 44213, 'region_id' => 780838, 'country_code' => 'NO', 'name' => 'Rennebu', 'active' => 1, 'slug' => 'rennebu'],
            ['id' => 44214, 'region_id' => 780838, 'country_code' => 'NO', 'name' => 'Rissa', 'active' => 1, 'slug' => 'rissa'],
            ['id' => 44215, 'region_id' => 780838, 'country_code' => 'NO', 'name' => 'Roan', 'active' => 1, 'slug' => 'roan'],
            ['id' => 44216, 'region_id' => 780838, 'country_code' => 'NO', 'name' => 'Røros', 'active' => 1, 'slug' => 'r%c3%b8ros'],
            ['id' => 44217, 'region_id' => 780838, 'country_code' => 'NO', 'name' => 'Selbu', 'active' => 1, 'slug' => 'selbu'],
            ['id' => 44218, 'region_id' => 780838, 'country_code' => 'NO', 'name' => 'Skaun', 'active' => 1, 'slug' => 'skaun'],
            ['id' => 44219, 'region_id' => 780838, 'country_code' => 'NO', 'name' => 'Snillfjord', 'active' => 1, 'slug' => 'snillfjord'],
            ['id' => 44220, 'region_id' => 780838, 'country_code' => 'NO', 'name' => 'Trondheim', 'active' => 1, 'slug' => 'trondheim'],
            ['id' => 44221, 'region_id' => 780838, 'country_code' => 'NO', 'name' => 'Tydal', 'active' => 1, 'slug' => 'tydal'],
            ['id' => 44222, 'region_id' => 780864, 'country_code' => 'NO', 'name' => 'Bamble', 'active' => 1, 'slug' => 'bamble'],
            ['id' => 44223, 'region_id' => 780864, 'country_code' => 'NO', 'name' => 'Bø', 'active' => 1, 'slug' => 'b%c3%b8'],
            ['id' => 44224, 'region_id' => 780864, 'country_code' => 'NO', 'name' => 'Drangedal', 'active' => 1, 'slug' => 'drangedal'],
            ['id' => 44225, 'region_id' => 780864, 'country_code' => 'NO', 'name' => 'Fyresdal', 'active' => 1, 'slug' => 'fyresdal'],
            ['id' => 44226, 'region_id' => 780864, 'country_code' => 'NO', 'name' => 'Hjartdal', 'active' => 1, 'slug' => 'hjartdal'],
            ['id' => 44227, 'region_id' => 780864, 'country_code' => 'NO', 'name' => 'Kragerø', 'active' => 1, 'slug' => 'krager%c3%b8'],
            ['id' => 44228, 'region_id' => 780864, 'country_code' => 'NO', 'name' => 'Kviteseid', 'active' => 1, 'slug' => 'kviteseid'],
            ['id' => 44229, 'region_id' => 780864, 'country_code' => 'NO', 'name' => 'Nissedal', 'active' => 1, 'slug' => 'nissedal'],
            ['id' => 44230, 'region_id' => 780864, 'country_code' => 'NO', 'name' => 'Nome', 'active' => 1, 'slug' => 'nome'],
            ['id' => 44231, 'region_id' => 780864, 'country_code' => 'NO', 'name' => 'Notodden', 'active' => 1, 'slug' => 'notodden'],
            ['id' => 44232, 'region_id' => 780864, 'country_code' => 'NO', 'name' => 'Porsgrunn', 'active' => 1, 'slug' => 'porsgrunn'],
            ['id' => 44233, 'region_id' => 780864, 'country_code' => 'NO', 'name' => 'Sauherad', 'active' => 1, 'slug' => 'sauherad'],
            ['id' => 44234, 'region_id' => 780864, 'country_code' => 'NO', 'name' => 'Seljord', 'active' => 1, 'slug' => 'seljord'],
            ['id' => 44235, 'region_id' => 780864, 'country_code' => 'NO', 'name' => 'Siljan', 'active' => 1, 'slug' => 'siljan'],
            ['id' => 44236, 'region_id' => 780864, 'country_code' => 'NO', 'name' => 'Skien', 'active' => 1, 'slug' => 'skien'],
            ['id' => 44237, 'region_id' => 780864, 'country_code' => 'NO', 'name' => 'Tinn', 'active' => 1, 'slug' => 'tinn'],
            ['id' => 44238, 'region_id' => 780864, 'country_code' => 'NO', 'name' => 'Tokke', 'active' => 1, 'slug' => 'tokke'],
            ['id' => 44239, 'region_id' => 780864, 'country_code' => 'NO', 'name' => 'Vinje', 'active' => 1, 'slug' => 'vinje'],
            ['id' => 44240, 'region_id' => 780883, 'country_code' => 'NO', 'name' => 'Balsfjord', 'active' => 1, 'slug' => 'balsfjord'],
            ['id' => 44241, 'region_id' => 780883, 'country_code' => 'NO', 'name' => 'Bardu', 'active' => 1, 'slug' => 'bardu'],
            ['id' => 44242, 'region_id' => 780883, 'country_code' => 'NO', 'name' => 'Berg', 'active' => 1, 'slug' => 'berg'],
            ['id' => 44243, 'region_id' => 780883, 'country_code' => 'NO', 'name' => 'Bjarkøy', 'active' => 1, 'slug' => 'bjark%c3%b8y'],
            ['id' => 44244, 'region_id' => 780883, 'country_code' => 'NO', 'name' => 'Dyrøy', 'active' => 1, 'slug' => 'dyr%c3%b8y'],
            ['id' => 44245, 'region_id' => 780883, 'country_code' => 'NO', 'name' => 'Gratangen', 'active' => 1, 'slug' => 'gratangen'],
            ['id' => 44246, 'region_id' => 780883, 'country_code' => 'NO', 'name' => 'Harstad', 'active' => 1, 'slug' => 'harstad'],
            ['id' => 44247, 'region_id' => 780883, 'country_code' => 'NO', 'name' => 'Ibestad', 'active' => 1, 'slug' => 'ibestad'],
            ['id' => 44248, 'region_id' => 780883, 'country_code' => 'NO', 'name' => 'Kåfjord', 'active' => 1, 'slug' => 'kafjord'],
            ['id' => 44249, 'region_id' => 780883, 'country_code' => 'NO', 'name' => 'Karlsøy', 'active' => 1, 'slug' => 'karls%c3%b8y'],
            ['id' => 44250, 'region_id' => 780883, 'country_code' => 'NO', 'name' => 'Kvæfjord', 'active' => 1, 'slug' => 'kv%c3%a6fjord'],
            ['id' => 44251, 'region_id' => 780883, 'country_code' => 'NO', 'name' => 'Kvænangen', 'active' => 1, 'slug' => 'kv%c3%a6nangen'],
            ['id' => 44252, 'region_id' => 780883, 'country_code' => 'NO', 'name' => 'Lavangen', 'active' => 1, 'slug' => 'lavangen'],
            ['id' => 44253, 'region_id' => 780883, 'country_code' => 'NO', 'name' => 'Lenvik', 'active' => 1, 'slug' => 'lenvik'],
            ['id' => 44254, 'region_id' => 780883, 'country_code' => 'NO', 'name' => 'Lyngen', 'active' => 1, 'slug' => 'lyngen'],
            ['id' => 44255, 'region_id' => 780883, 'country_code' => 'NO', 'name' => 'Målselv', 'active' => 1, 'slug' => 'malselv'],
            ['id' => 44256, 'region_id' => 780883, 'country_code' => 'NO', 'name' => 'Nordreisa', 'active' => 1, 'slug' => 'nordreisa'],
            ['id' => 44257, 'region_id' => 780883, 'country_code' => 'NO', 'name' => 'Salangen', 'active' => 1, 'slug' => 'salangen'],
            ['id' => 44258, 'region_id' => 780883, 'country_code' => 'NO', 'name' => 'Skånland', 'active' => 1, 'slug' => 'skanland'],
            ['id' => 44259, 'region_id' => 780883, 'country_code' => 'NO', 'name' => 'Skjervøy', 'active' => 1, 'slug' => 'skjerv%c3%b8y'],
            ['id' => 44260, 'region_id' => 780883, 'country_code' => 'NO', 'name' => 'Sørreisa', 'active' => 1, 'slug' => 's%c3%b8rreisa'],
            ['id' => 44261, 'region_id' => 780883, 'country_code' => 'NO', 'name' => 'Storfjord', 'active' => 1, 'slug' => 'storfjord'],
            ['id' => 44262, 'region_id' => 780883, 'country_code' => 'NO', 'name' => 'Torsken', 'active' => 1, 'slug' => 'torsken'],
            ['id' => 44263, 'region_id' => 780883, 'country_code' => 'NO', 'name' => 'Tranøy', 'active' => 1, 'slug' => 'tran%c3%b8y'],
            ['id' => 44264, 'region_id' => 780883, 'country_code' => 'NO', 'name' => 'Tromsø', 'active' => 1, 'slug' => 'troms%c3%b8'],
            ['id' => 44265, 'region_id' => 780909, 'country_code' => 'NO', 'name' => 'Åseral', 'active' => 1, 'slug' => 'aseral'],
            ['id' => 44266, 'region_id' => 780909, 'country_code' => 'NO', 'name' => 'Audnedal', 'active' => 1, 'slug' => 'audnedal'],
            ['id' => 44267, 'region_id' => 780909, 'country_code' => 'NO', 'name' => 'Farsund', 'active' => 1, 'slug' => 'farsund'],
            ['id' => 44268, 'region_id' => 780909, 'country_code' => 'NO', 'name' => 'Flekkefjord', 'active' => 1, 'slug' => 'flekkefjord'],
            ['id' => 44269, 'region_id' => 780909, 'country_code' => 'NO', 'name' => 'Hægebostad', 'active' => 1, 'slug' => 'h%c3%a6gebostad'],
            ['id' => 44270, 'region_id' => 780909, 'country_code' => 'NO', 'name' => 'Kristiansand', 'active' => 1, 'slug' => 'kristiansand'],
            ['id' => 44271, 'region_id' => 780909, 'country_code' => 'NO', 'name' => 'Kvinesdal', 'active' => 1, 'slug' => 'kvinesdal'],
            ['id' => 44272, 'region_id' => 780909, 'country_code' => 'NO', 'name' => 'Lindesnes', 'active' => 1, 'slug' => 'lindesnes'],
            ['id' => 44273, 'region_id' => 780909, 'country_code' => 'NO', 'name' => 'Lyngdal', 'active' => 1, 'slug' => 'lyngdal'],
            ['id' => 44274, 'region_id' => 780909, 'country_code' => 'NO', 'name' => 'Mandal', 'active' => 1, 'slug' => 'mandal'],
            ['id' => 44275, 'region_id' => 780909, 'country_code' => 'NO', 'name' => 'Marnardal', 'active' => 1, 'slug' => 'marnardal'],
            ['id' => 44276, 'region_id' => 780909, 'country_code' => 'NO', 'name' => 'Sirdal', 'active' => 1, 'slug' => 'sirdal'],
            ['id' => 44277, 'region_id' => 780909, 'country_code' => 'NO', 'name' => 'Songdalen', 'active' => 1, 'slug' => 'songdalen'],
            ['id' => 44278, 'region_id' => 780909, 'country_code' => 'NO', 'name' => 'Søgne', 'active' => 1, 'slug' => 's%c3%b8gne'],
            ['id' => 44279, 'region_id' => 780909, 'country_code' => 'NO', 'name' => 'Vennesla', 'active' => 1, 'slug' => 'vennesla'],
            ['id' => 44280, 'region_id' => 780925, 'country_code' => 'NO', 'name' => 'Andebu', 'active' => 1, 'slug' => 'andebu'],
            ['id' => 44281, 'region_id' => 780925, 'country_code' => 'NO', 'name' => 'Hof', 'active' => 1, 'slug' => 'hof'],
            ['id' => 44282, 'region_id' => 780925, 'country_code' => 'NO', 'name' => 'Holmestrand', 'active' => 1, 'slug' => 'holmestrand'],
            ['id' => 44283, 'region_id' => 780925, 'country_code' => 'NO', 'name' => 'Horten', 'active' => 1, 'slug' => 'horten'],
            ['id' => 44284, 'region_id' => 780925, 'country_code' => 'NO', 'name' => 'Lardal', 'active' => 1, 'slug' => 'lardal'],
            ['id' => 44285, 'region_id' => 780925, 'country_code' => 'NO', 'name' => 'Larvik', 'active' => 1, 'slug' => 'larvik'],
            ['id' => 44286, 'region_id' => 780925, 'country_code' => 'NO', 'name' => 'Nøtterøy', 'active' => 1, 'slug' => 'n%c3%b8tter%c3%b8y'],
            ['id' => 44287, 'region_id' => 780925, 'country_code' => 'NO', 'name' => 'Re', 'active' => 1, 'slug' => 're'],
            ['id' => 44288, 'region_id' => 780925, 'country_code' => 'NO', 'name' => 'Sande', 'active' => 1, 'slug' => 'sande'],
            ['id' => 44289, 'region_id' => 780925, 'country_code' => 'NO', 'name' => 'Sandefjord', 'active' => 1, 'slug' => 'sandefjord'],
            ['id' => 44290, 'region_id' => 780925, 'country_code' => 'NO', 'name' => 'Stokke', 'active' => 1, 'slug' => 'stokke'],
            ['id' => 44291, 'region_id' => 780925, 'country_code' => 'NO', 'name' => 'Svelvik', 'active' => 1, 'slug' => 'svelvik'],
            ['id' => 44292, 'region_id' => 780925, 'country_code' => 'NO', 'name' => 'Tjøme', 'active' => 1, 'slug' => 'tj%c3%b8me'],
            ['id' => 44293, 'region_id' => 780925, 'country_code' => 'NO', 'name' => 'Tønsberg', 'active' => 1, 'slug' => 't%c3%b8nsberg']
    	];
    }
}
