<?php

namespace Gerardojbaez\GeoData\Seeders;

use Illuminate\Database\Seeder;
use Gerardojbaez\GeoData\Models\Country;
use Gerardojbaez\GeoData\Models\Region;
use Gerardojbaez\GeoData\Models\City;

class PanamaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Country::create($this->country());
        Region::insert($this->regions());

        if ($this->cities() > 4000)
        {
            foreach (array_chunk($this->cities(), 3500) as $chunk)
                City::insert($chunk);
        }
        else
        {
            City::insert($this->cities());
        }
    }

        /**
     * Get country.
     *
     * @return array
     */
    public function country()
    {
    	return ['code' => 'PA', 'name' => 'Panama', 'slug' => 'panama'];
    }

    /**
     * Get country regions.
     *
     * @return array
     */
    public function regions()
    {
    	return [
            ['id' => 710290, 'country_code' => 'PA', 'name' => 'Boca Del Toro', 'active' => 1, 'slug' => 'boca-del-toro'],
            ['id' => 710306, 'country_code' => 'PA', 'name' => 'Coclé', 'active' => 1, 'slug' => 'cocle'],
            ['id' => 710347, 'country_code' => 'PA', 'name' => 'Colón', 'active' => 1, 'slug' => 'colon'],
            ['id' => 710382, 'country_code' => 'PA', 'name' => 'Chiriquí', 'active' => 1, 'slug' => 'chiriqui'],
            ['id' => 710475, 'country_code' => 'PA', 'name' => 'Darién', 'active' => 1, 'slug' => 'darien'],
            ['id' => 710500, 'country_code' => 'PA', 'name' => 'Herrera', 'active' => 1, 'slug' => 'herrera'],
            ['id' => 710545, 'country_code' => 'PA', 'name' => 'Los Santos', 'active' => 1, 'slug' => 'los-santos'],
            ['id' => 710607, 'country_code' => 'PA', 'name' => 'Panamá City', 'active' => 1, 'slug' => 'panama-city'],
            ['id' => 710712, 'country_code' => 'PA', 'name' => 'Veraguas', 'active' => 1, 'slug' => 'veraguas'],
            ['id' => 710796, 'country_code' => 'PA', 'name' => 'San Blas', 'active' => 1, 'slug' => 'san-blas']
    	];
    }

    /**
     * Get region cities.
     *
     * @return array
     */
    public function cities()
    {
    	return [
            ['id' => 24352, 'region_id' => 710290, 'country_code' => 'PA', 'name' => 'Almirante', 'active' => 1, 'slug' => 'almirante'],
            ['id' => 24353, 'region_id' => 710290, 'country_code' => 'PA', 'name' => 'Bastimentos', 'active' => 1, 'slug' => 'bastimentos'],
            ['id' => 24354, 'region_id' => 710290, 'country_code' => 'PA', 'name' => 'Bocas Del Toro', 'active' => 1, 'slug' => 'bocas-del-toro'],
            ['id' => 24355, 'region_id' => 710290, 'country_code' => 'PA', 'name' => 'Cauchero', 'active' => 1, 'slug' => 'cauchero'],
            ['id' => 24356, 'region_id' => 710290, 'country_code' => 'PA', 'name' => 'Changuinola', 'active' => 1, 'slug' => 'changuinola'],
            ['id' => 24357, 'region_id' => 710290, 'country_code' => 'PA', 'name' => 'Chiriqui Grande', 'active' => 1, 'slug' => 'chiriqui-grande'],
            ['id' => 24358, 'region_id' => 710290, 'country_code' => 'PA', 'name' => 'Guabito', 'active' => 1, 'slug' => 'guabito'],
            ['id' => 24359, 'region_id' => 710290, 'country_code' => 'PA', 'name' => 'Miramar', 'active' => 1, 'slug' => 'miramar'],
            ['id' => 24360, 'region_id' => 710290, 'country_code' => 'PA', 'name' => 'Punta Laurel', 'active' => 1, 'slug' => 'punta-laurel'],
            ['id' => 24361, 'region_id' => 710290, 'country_code' => 'PA', 'name' => 'Punta Peña', 'active' => 1, 'slug' => 'punta-pena'],
            ['id' => 24362, 'region_id' => 710290, 'country_code' => 'PA', 'name' => 'Punta Robalo', 'active' => 1, 'slug' => 'punta-robalo'],
            ['id' => 24363, 'region_id' => 710290, 'country_code' => 'PA', 'name' => 'Rambala', 'active' => 1, 'slug' => 'rambala'],
            ['id' => 24364, 'region_id' => 710290, 'country_code' => 'PA', 'name' => 'Teribe', 'active' => 1, 'slug' => 'teribe'],
            ['id' => 24365, 'region_id' => 710290, 'country_code' => 'PA', 'name' => 'Tierra Oscura', 'active' => 1, 'slug' => 'tierra-oscura'],
            ['id' => 24366, 'region_id' => 710290, 'country_code' => 'PA', 'name' => 'Valle Del Risco', 'active' => 1, 'slug' => 'valle-del-risco'],
            ['id' => 24367, 'region_id' => 710306, 'country_code' => 'PA', 'name' => 'Aguadulce', 'active' => 1, 'slug' => 'aguadulce'],
            ['id' => 24368, 'region_id' => 710306, 'country_code' => 'PA', 'name' => 'Antón', 'active' => 1, 'slug' => 'anton'],
            ['id' => 24369, 'region_id' => 710306, 'country_code' => 'PA', 'name' => 'Barrios Unidos', 'active' => 1, 'slug' => 'barrios-unidos'],
            ['id' => 24370, 'region_id' => 710306, 'country_code' => 'PA', 'name' => 'Caballero', 'active' => 1, 'slug' => 'caballero'],
            ['id' => 24371, 'region_id' => 710306, 'country_code' => 'PA', 'name' => 'Cabuya', 'active' => 1, 'slug' => 'cabuya'],
            ['id' => 24372, 'region_id' => 710306, 'country_code' => 'PA', 'name' => 'Cañaveral', 'active' => 1, 'slug' => 'canaveral'],
            ['id' => 24373, 'region_id' => 710306, 'country_code' => 'PA', 'name' => 'Capellanía', 'active' => 1, 'slug' => 'capellania'],
            ['id' => 24374, 'region_id' => 710306, 'country_code' => 'PA', 'name' => 'Chiguirí Arriba', 'active' => 1, 'slug' => 'chiguiri-arriba'],
            ['id' => 24375, 'region_id' => 710306, 'country_code' => 'PA', 'name' => 'Coclé', 'active' => 1, 'slug' => 'cocle'],
            ['id' => 24376, 'region_id' => 710306, 'country_code' => 'PA', 'name' => 'El Caño', 'active' => 1, 'slug' => 'el-cano'],
            ['id' => 24377, 'region_id' => 710306, 'country_code' => 'PA', 'name' => 'El Chirú', 'active' => 1, 'slug' => 'el-chiru'],
            ['id' => 24378, 'region_id' => 710306, 'country_code' => 'PA', 'name' => 'El Coco', 'active' => 1, 'slug' => 'el-coco'],
            ['id' => 24379, 'region_id' => 710306, 'country_code' => 'PA', 'name' => 'El Copé', 'active' => 1, 'slug' => 'el-cope'],
            ['id' => 24380, 'region_id' => 710306, 'country_code' => 'PA', 'name' => 'El Cristo', 'active' => 1, 'slug' => 'el-cristo'],
            ['id' => 24381, 'region_id' => 710306, 'country_code' => 'PA', 'name' => 'El Harino', 'active' => 1, 'slug' => 'el-harino'],
            ['id' => 24382, 'region_id' => 710306, 'country_code' => 'PA', 'name' => 'El Palmar', 'active' => 1, 'slug' => 'el-palmar'],
            ['id' => 24383, 'region_id' => 710306, 'country_code' => 'PA', 'name' => 'El Picacho', 'active' => 1, 'slug' => 'el-picacho'],
            ['id' => 24384, 'region_id' => 710306, 'country_code' => 'PA', 'name' => 'El Potrero', 'active' => 1, 'slug' => 'el-potrero'],
            ['id' => 24385, 'region_id' => 710306, 'country_code' => 'PA', 'name' => 'El Retiro', 'active' => 1, 'slug' => 'el-retiro'],
            ['id' => 24386, 'region_id' => 710306, 'country_code' => 'PA', 'name' => 'El Roble', 'active' => 1, 'slug' => 'el-roble'],
            ['id' => 24387, 'region_id' => 710306, 'country_code' => 'PA', 'name' => 'El Valle', 'active' => 1, 'slug' => 'el-valle'],
            ['id' => 24388, 'region_id' => 710306, 'country_code' => 'PA', 'name' => 'Guzmán', 'active' => 1, 'slug' => 'guzman'],
            ['id' => 24389, 'region_id' => 710306, 'country_code' => 'PA', 'name' => 'Juan Díaz', 'active' => 1, 'slug' => 'juan-diaz'],
            ['id' => 24390, 'region_id' => 710306, 'country_code' => 'PA', 'name' => 'La Pava', 'active' => 1, 'slug' => 'la-pava'],
            ['id' => 24391, 'region_id' => 710306, 'country_code' => 'PA', 'name' => 'La Pintada', 'active' => 1, 'slug' => 'la-pintada'],
            ['id' => 24392, 'region_id' => 710306, 'country_code' => 'PA', 'name' => 'Llano Grande', 'active' => 1, 'slug' => 'llano-grande'],
            ['id' => 24393, 'region_id' => 710306, 'country_code' => 'PA', 'name' => 'Natá', 'active' => 1, 'slug' => 'nata'],
            ['id' => 24394, 'region_id' => 710306, 'country_code' => 'PA', 'name' => 'Olá', 'active' => 1, 'slug' => 'ola'],
            ['id' => 24395, 'region_id' => 710306, 'country_code' => 'PA', 'name' => 'Pajonal', 'active' => 1, 'slug' => 'pajonal'],
            ['id' => 24396, 'region_id' => 710306, 'country_code' => 'PA', 'name' => 'Penonomé', 'active' => 1, 'slug' => 'penonome'],
            ['id' => 24397, 'region_id' => 710306, 'country_code' => 'PA', 'name' => 'Piedras Gordas', 'active' => 1, 'slug' => 'piedras-gordas'],
            ['id' => 24398, 'region_id' => 710306, 'country_code' => 'PA', 'name' => 'Pocrí', 'active' => 1, 'slug' => 'pocri'],
            ['id' => 24399, 'region_id' => 710306, 'country_code' => 'PA', 'name' => 'Río Grande', 'active' => 1, 'slug' => 'rio-grande'],
            ['id' => 24400, 'region_id' => 710306, 'country_code' => 'PA', 'name' => 'Río Hato', 'active' => 1, 'slug' => 'rio-hato'],
            ['id' => 24401, 'region_id' => 710306, 'country_code' => 'PA', 'name' => 'Río Indio', 'active' => 1, 'slug' => 'rio-indio'],
            ['id' => 24402, 'region_id' => 710306, 'country_code' => 'PA', 'name' => 'San Juan de Dios', 'active' => 1, 'slug' => 'san-juan-de-dios'],
            ['id' => 24403, 'region_id' => 710306, 'country_code' => 'PA', 'name' => 'Santa Rita', 'active' => 1, 'slug' => 'santa-rita'],
            ['id' => 24404, 'region_id' => 710306, 'country_code' => 'PA', 'name' => 'Toabré', 'active' => 1, 'slug' => 'toabre'],
            ['id' => 24405, 'region_id' => 710306, 'country_code' => 'PA', 'name' => 'Toza', 'active' => 1, 'slug' => 'toza'],
            ['id' => 24406, 'region_id' => 710306, 'country_code' => 'PA', 'name' => 'Tulú', 'active' => 1, 'slug' => 'tulu'],
            ['id' => 24407, 'region_id' => 710347, 'country_code' => 'PA', 'name' => 'Escobal', 'active' => 1, 'slug' => 'escobal'],
            ['id' => 24408, 'region_id' => 710347, 'country_code' => 'PA', 'name' => 'Garrote', 'active' => 1, 'slug' => 'garrote'],
            ['id' => 24409, 'region_id' => 710347, 'country_code' => 'PA', 'name' => 'Gobea', 'active' => 1, 'slug' => 'gobea'],
            ['id' => 24410, 'region_id' => 710347, 'country_code' => 'PA', 'name' => 'Iriona', 'active' => 1, 'slug' => 'iriona'],
            ['id' => 24411, 'region_id' => 710347, 'country_code' => 'PA', 'name' => 'Isla Grande', 'active' => 1, 'slug' => 'isla-grande'],
            ['id' => 24412, 'region_id' => 710347, 'country_code' => 'PA', 'name' => 'La Encantada', 'active' => 1, 'slug' => 'la-encantada'],
            ['id' => 24413, 'region_id' => 710347, 'country_code' => 'PA', 'name' => 'Limón', 'active' => 1, 'slug' => 'limon'],
            ['id' => 24414, 'region_id' => 710347, 'country_code' => 'PA', 'name' => 'María Chiquita', 'active' => 1, 'slug' => 'maria-chiquita'],
            ['id' => 24415, 'region_id' => 710347, 'country_code' => 'PA', 'name' => 'Miguel de la Borda', 'active' => 1, 'slug' => 'miguel-de-la-borda'],
            ['id' => 24416, 'region_id' => 710347, 'country_code' => 'PA', 'name' => 'Miramar', 'active' => 1, 'slug' => 'miramar'],
            ['id' => 24417, 'region_id' => 710347, 'country_code' => 'PA', 'name' => 'Nombre de Dios', 'active' => 1, 'slug' => 'nombre-de-dios'],
            ['id' => 24418, 'region_id' => 710347, 'country_code' => 'PA', 'name' => 'Nueva Providencia', 'active' => 1, 'slug' => 'nueva-providencia'],
            ['id' => 24419, 'region_id' => 710347, 'country_code' => 'PA', 'name' => 'Palenque', 'active' => 1, 'slug' => 'palenque'],
            ['id' => 24420, 'region_id' => 710347, 'country_code' => 'PA', 'name' => 'Palmas Bellas', 'active' => 1, 'slug' => 'palmas-bellas'],
            ['id' => 24421, 'region_id' => 710347, 'country_code' => 'PA', 'name' => 'Palmira', 'active' => 1, 'slug' => 'palmira'],
            ['id' => 24422, 'region_id' => 710347, 'country_code' => 'PA', 'name' => 'Piña', 'active' => 1, 'slug' => 'pina'],
            ['id' => 24423, 'region_id' => 710347, 'country_code' => 'PA', 'name' => 'Playa Chiquita', 'active' => 1, 'slug' => 'playa-chiquita'],
            ['id' => 24424, 'region_id' => 710347, 'country_code' => 'PA', 'name' => 'Portobelo', 'active' => 1, 'slug' => 'portobelo'],
            ['id' => 24425, 'region_id' => 710347, 'country_code' => 'PA', 'name' => 'Puerto Pilón', 'active' => 1, 'slug' => 'puerto-pilon'],
            ['id' => 24426, 'region_id' => 710347, 'country_code' => 'PA', 'name' => 'Río Indio', 'active' => 1, 'slug' => 'rio-indio'],
            ['id' => 24427, 'region_id' => 710347, 'country_code' => 'PA', 'name' => 'Saba', 'active' => 1, 'slug' => 'saba'],
            ['id' => 24428, 'region_id' => 710347, 'country_code' => 'PA', 'name' => 'Sabanitas', 'active' => 1, 'slug' => 'sabanitas'],
            ['id' => 24429, 'region_id' => 710347, 'country_code' => 'PA', 'name' => 'Salamanca', 'active' => 1, 'slug' => 'salamanca'],
            ['id' => 24430, 'region_id' => 710347, 'country_code' => 'PA', 'name' => 'Salud', 'active' => 1, 'slug' => 'salud'],
            ['id' => 24431, 'region_id' => 710347, 'country_code' => 'PA', 'name' => 'San José Del General', 'active' => 1, 'slug' => 'san-jose-del-general'],
            ['id' => 24432, 'region_id' => 710347, 'country_code' => 'PA', 'name' => 'San Juan', 'active' => 1, 'slug' => 'san-juan'],
            ['id' => 24433, 'region_id' => 710347, 'country_code' => 'PA', 'name' => 'Santa Fe', 'active' => 1, 'slug' => 'santa-fe'],
            ['id' => 24434, 'region_id' => 710347, 'country_code' => 'PA', 'name' => 'Santa Isabel', 'active' => 1, 'slug' => 'santa-isabel'],
            ['id' => 24435, 'region_id' => 710347, 'country_code' => 'PA', 'name' => 'Santa Rosa de Aguan', 'active' => 1, 'slug' => 'santa-rosa-de-aguan'],
            ['id' => 24436, 'region_id' => 710347, 'country_code' => 'PA', 'name' => 'Sonaguera', 'active' => 1, 'slug' => 'sonaguera'],
            ['id' => 24437, 'region_id' => 710347, 'country_code' => 'PA', 'name' => 'Tocoa', 'active' => 1, 'slug' => 'tocoa'],
            ['id' => 24438, 'region_id' => 710347, 'country_code' => 'PA', 'name' => 'Trujillo', 'active' => 1, 'slug' => 'trujillo'],
            ['id' => 24439, 'region_id' => 710347, 'country_code' => 'PA', 'name' => 'Viento Frío', 'active' => 1, 'slug' => 'viento-frio'],
            ['id' => 24440, 'region_id' => 710347, 'country_code' => 'PA', 'name' => 'Zona Libre', 'active' => 1, 'slug' => 'zona-libre'],
            ['id' => 24441, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Alanje', 'active' => 1, 'slug' => 'alanje'],
            ['id' => 24442, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Alto Boquete', 'active' => 1, 'slug' => 'alto-boquete'],
            ['id' => 24443, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Aserrío de Gariché', 'active' => 1, 'slug' => 'aserrio-de-gariche'],
            ['id' => 24444, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Baco', 'active' => 1, 'slug' => 'baco'],
            ['id' => 24445, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Bágala', 'active' => 1, 'slug' => 'bagala'],
            ['id' => 24446, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Bajo Boquete', 'active' => 1, 'slug' => 'bajo-boquete'],
            ['id' => 24447, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Barú', 'active' => 1, 'slug' => 'baru'],
            ['id' => 24448, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Bella Vista', 'active' => 1, 'slug' => 'bella-vista'],
            ['id' => 24449, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Bijagual', 'active' => 1, 'slug' => 'bijagual'],
            ['id' => 24450, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Boca Chica', 'active' => 1, 'slug' => 'boca-chica'],
            ['id' => 24451, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Boca Del Monte', 'active' => 1, 'slug' => 'boca-del-monte'],
            ['id' => 24452, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Boquerón', 'active' => 1, 'slug' => 'boqueron'],
            ['id' => 24453, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Boquete', 'active' => 1, 'slug' => 'boquete'],
            ['id' => 24454, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Breñon', 'active' => 1, 'slug' => 'brenon'],
            ['id' => 24455, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Bugaba', 'active' => 1, 'slug' => 'bugaba'],
            ['id' => 24456, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Caldera', 'active' => 1, 'slug' => 'caldera'],
            ['id' => 24457, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Cañas Gordas', 'active' => 1, 'slug' => 'canas-gordas'],
            ['id' => 24458, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Cerro Punta', 'active' => 1, 'slug' => 'cerro-punta'],
            ['id' => 24459, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Cerro Viejo', 'active' => 1, 'slug' => 'cerro-viejo'],
            ['id' => 24460, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Chiriquí', 'active' => 1, 'slug' => 'chiriqui'],
            ['id' => 24461, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Cochea', 'active' => 1, 'slug' => 'cochea'],
            ['id' => 24462, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Cordillera', 'active' => 1, 'slug' => 'cordillera'],
            ['id' => 24463, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'David', 'active' => 1, 'slug' => 'david'],
            ['id' => 24464, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Divalá', 'active' => 1, 'slug' => 'divala'],
            ['id' => 24465, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Dolega', 'active' => 1, 'slug' => 'dolega'],
            ['id' => 24466, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Dos Ríos', 'active' => 1, 'slug' => 'dos-rios'],
            ['id' => 24467, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'El Bongo', 'active' => 1, 'slug' => 'el-bongo'],
            ['id' => 24468, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'El Cristo', 'active' => 1, 'slug' => 'el-cristo'],
            ['id' => 24469, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'El Nancito', 'active' => 1, 'slug' => 'el-nancito'],
            ['id' => 24470, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'El Porvenir', 'active' => 1, 'slug' => 'el-porvenir'],
            ['id' => 24471, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'El Puerto', 'active' => 1, 'slug' => 'el-puerto'],
            ['id' => 24472, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'El Tejar', 'active' => 1, 'slug' => 'el-tejar'],
            ['id' => 24473, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Gómez', 'active' => 1, 'slug' => 'gomez'],
            ['id' => 24474, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Guabal', 'active' => 1, 'slug' => 'guabal'],
            ['id' => 24475, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Guacá', 'active' => 1, 'slug' => 'guaca'],
            ['id' => 24476, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Gualaca', 'active' => 1, 'slug' => 'gualaca'],
            ['id' => 24477, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Guayabal', 'active' => 1, 'slug' => 'guayabal'],
            ['id' => 24478, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Horconcitos', 'active' => 1, 'slug' => 'horconcitos'],
            ['id' => 24479, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Hornito', 'active' => 1, 'slug' => 'hornito'],
            ['id' => 24480, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Jaramillo', 'active' => 1, 'slug' => 'jaramillo'],
            ['id' => 24481, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Juay', 'active' => 1, 'slug' => 'juay'],
            ['id' => 24482, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Justo Fidel Palacios', 'active' => 1, 'slug' => 'justo-fidel-palacios'],
            ['id' => 24483, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'La Concepción', 'active' => 1, 'slug' => 'la-concepcion'],
            ['id' => 24484, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'La Estrella', 'active' => 1, 'slug' => 'la-estrella'],
            ['id' => 24485, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Lajas Adentro', 'active' => 1, 'slug' => 'lajas-adentro'],
            ['id' => 24486, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Lajas de Tolé', 'active' => 1, 'slug' => 'lajas-de-tole'],
            ['id' => 24487, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Las Lajas', 'active' => 1, 'slug' => 'las-lajas'],
            ['id' => 24488, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Las Lomas', 'active' => 1, 'slug' => 'las-lomas'],
            ['id' => 24489, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Limones', 'active' => 1, 'slug' => 'limones'],
            ['id' => 24490, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Los Anastacios', 'active' => 1, 'slug' => 'los-anastacios'],
            ['id' => 24491, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Los Angeles', 'active' => 1, 'slug' => 'los-angeles'],
            ['id' => 24492, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Los Naranjos', 'active' => 1, 'slug' => 'los-naranjos'],
            ['id' => 24493, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Monte Lirio', 'active' => 1, 'slug' => 'monte-lirio'],
            ['id' => 24494, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Paja de Sombrero', 'active' => 1, 'slug' => 'paja-de-sombrero'],
            ['id' => 24495, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Palmira', 'active' => 1, 'slug' => 'palmira'],
            ['id' => 24496, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Palo Grande', 'active' => 1, 'slug' => 'palo-grande'],
            ['id' => 24497, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Paraíso', 'active' => 1, 'slug' => 'paraiso'],
            ['id' => 24498, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Pedregal', 'active' => 1, 'slug' => 'pedregal'],
            ['id' => 24499, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Plaza Caisán', 'active' => 1, 'slug' => 'plaza-caisan'],
            ['id' => 24500, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Potrerillos', 'active' => 1, 'slug' => 'potrerillos'],
            ['id' => 24501, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Potrerillos Abajo', 'active' => 1, 'slug' => 'potrerillos-abajo'],
            ['id' => 24502, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Potrero de Caña', 'active' => 1, 'slug' => 'potrero-de-cana'],
            ['id' => 24503, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Progreso', 'active' => 1, 'slug' => 'progreso'],
            ['id' => 24504, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Puerto Armuelles', 'active' => 1, 'slug' => 'puerto-armuelles'],
            ['id' => 24505, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Quebrada de Piedra', 'active' => 1, 'slug' => 'quebrada-de-piedra'],
            ['id' => 24506, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Querévalo', 'active' => 1, 'slug' => 'querevalo'],
            ['id' => 24507, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Remedios', 'active' => 1, 'slug' => 'remedios'],
            ['id' => 24508, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Renacimiento', 'active' => 1, 'slug' => 'renacimiento'],
            ['id' => 24509, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Rincón', 'active' => 1, 'slug' => 'rincon'],
            ['id' => 24510, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Río Sereno', 'active' => 1, 'slug' => 'rio-sereno'],
            ['id' => 24511, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Rodolfo Aguilar', 'active' => 1, 'slug' => 'rodolfo-aguilar'],
            ['id' => 24512, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Rovira', 'active' => 1, 'slug' => 'rovira'],
            ['id' => 24513, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'San Andrés', 'active' => 1, 'slug' => 'san-andres'],
            ['id' => 24514, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'San Carlos', 'active' => 1, 'slug' => 'san-carlos'],
            ['id' => 24515, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'San Felix', 'active' => 1, 'slug' => 'san-felix'],
            ['id' => 24516, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'San Juan', 'active' => 1, 'slug' => 'san-juan'],
            ['id' => 24517, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'San Lorenzo', 'active' => 1, 'slug' => 'san-lorenzo'],
            ['id' => 24518, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'San Pablo Nuevo', 'active' => 1, 'slug' => 'san-pablo-nuevo'],
            ['id' => 24519, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'San Pablo Viejo', 'active' => 1, 'slug' => 'san-pablo-viejo'],
            ['id' => 24520, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Santa Cruz', 'active' => 1, 'slug' => 'santa-cruz'],
            ['id' => 24521, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Santa Lucia', 'active' => 1, 'slug' => 'santa-lucia'],
            ['id' => 24522, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Santa Marta', 'active' => 1, 'slug' => 'santa-marta'],
            ['id' => 24523, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Santa Rosa', 'active' => 1, 'slug' => 'santa-rosa'],
            ['id' => 24524, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Santo Domingo', 'active' => 1, 'slug' => 'santo-domingo'],
            ['id' => 24525, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Santo Tomás', 'active' => 1, 'slug' => 'santo-tomas'],
            ['id' => 24526, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Sortová', 'active' => 1, 'slug' => 'sortova'],
            ['id' => 24527, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Tijeras', 'active' => 1, 'slug' => 'tijeras'],
            ['id' => 24528, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Tinajas', 'active' => 1, 'slug' => 'tinajas'],
            ['id' => 24529, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Tolé', 'active' => 1, 'slug' => 'tole'],
            ['id' => 24530, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Veladero', 'active' => 1, 'slug' => 'veladero'],
            ['id' => 24531, 'region_id' => 710382, 'country_code' => 'PA', 'name' => 'Volcán', 'active' => 1, 'slug' => 'volcan'],
            ['id' => 24532, 'region_id' => 710475, 'country_code' => 'PA', 'name' => 'Agua Fría', 'active' => 1, 'slug' => 'agua-fria'],
            ['id' => 24533, 'region_id' => 710475, 'country_code' => 'PA', 'name' => 'Boca de Cupé', 'active' => 1, 'slug' => 'boca-de-cupe'],
            ['id' => 24534, 'region_id' => 710475, 'country_code' => 'PA', 'name' => 'Camogantí', 'active' => 1, 'slug' => 'camoganti'],
            ['id' => 24535, 'region_id' => 710475, 'country_code' => 'PA', 'name' => 'Chepigana', 'active' => 1, 'slug' => 'chepigana'],
            ['id' => 24536, 'region_id' => 710475, 'country_code' => 'PA', 'name' => 'Cucunatí', 'active' => 1, 'slug' => 'cucunati'],
            ['id' => 24537, 'region_id' => 710475, 'country_code' => 'PA', 'name' => 'El Real de Santa María', 'active' => 1, 'slug' => 'el-real-de-santa-maria'],
            ['id' => 24538, 'region_id' => 710475, 'country_code' => 'PA', 'name' => 'Garachiné', 'active' => 1, 'slug' => 'garachine'],
            ['id' => 24539, 'region_id' => 710475, 'country_code' => 'PA', 'name' => 'La Palma', 'active' => 1, 'slug' => 'la-palma'],
            ['id' => 24540, 'region_id' => 710475, 'country_code' => 'PA', 'name' => 'Metetí', 'active' => 1, 'slug' => 'meteti'],
            ['id' => 24541, 'region_id' => 710475, 'country_code' => 'PA', 'name' => 'Paya', 'active' => 1, 'slug' => 'paya'],
            ['id' => 24542, 'region_id' => 710475, 'country_code' => 'PA', 'name' => 'Pinogana', 'active' => 1, 'slug' => 'pinogana'],
            ['id' => 24543, 'region_id' => 710475, 'country_code' => 'PA', 'name' => 'Púcuro', 'active' => 1, 'slug' => 'pucuro'],
            ['id' => 24544, 'region_id' => 710475, 'country_code' => 'PA', 'name' => 'Puerto Piña', 'active' => 1, 'slug' => 'puerto-pina'],
            ['id' => 24545, 'region_id' => 710475, 'country_code' => 'PA', 'name' => 'Río Congo', 'active' => 1, 'slug' => 'rio-congo'],
            ['id' => 24546, 'region_id' => 710475, 'country_code' => 'PA', 'name' => 'Río Congo Arriba', 'active' => 1, 'slug' => 'rio-congo-arriba'],
            ['id' => 24547, 'region_id' => 710475, 'country_code' => 'PA', 'name' => 'Río Iglesias', 'active' => 1, 'slug' => 'rio-iglesias'],
            ['id' => 24548, 'region_id' => 710475, 'country_code' => 'PA', 'name' => 'Sambú', 'active' => 1, 'slug' => 'sambu'],
            ['id' => 24549, 'region_id' => 710475, 'country_code' => 'PA', 'name' => 'Santa Fé', 'active' => 1, 'slug' => 'santa-fe'],
            ['id' => 24550, 'region_id' => 710475, 'country_code' => 'PA', 'name' => 'Setegantí', 'active' => 1, 'slug' => 'seteganti'],
            ['id' => 24551, 'region_id' => 710475, 'country_code' => 'PA', 'name' => 'Taimatí', 'active' => 1, 'slug' => 'taimati'],
            ['id' => 24552, 'region_id' => 710475, 'country_code' => 'PA', 'name' => 'Tucutí', 'active' => 1, 'slug' => 'tucuti'],
            ['id' => 24553, 'region_id' => 710475, 'country_code' => 'PA', 'name' => 'Ape', 'active' => 1, 'slug' => 'ape'],
            ['id' => 24554, 'region_id' => 710475, 'country_code' => 'PA', 'name' => 'Yaviza', 'active' => 1, 'slug' => 'yaviza'],
            ['id' => 24555, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'Cabuya', 'active' => 1, 'slug' => 'cabuya'],
            ['id' => 24556, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'Capurí', 'active' => 1, 'slug' => 'capuri'],
            ['id' => 24557, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'Cerro Largo', 'active' => 1, 'slug' => 'cerro-largo'],
            ['id' => 24558, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'Chepo', 'active' => 1, 'slug' => 'chepo'],
            ['id' => 24559, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'Chitré', 'active' => 1, 'slug' => 'chitre'],
            ['id' => 24560, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'Chumical', 'active' => 1, 'slug' => 'chumical'],
            ['id' => 24561, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'Chupampa', 'active' => 1, 'slug' => 'chupampa'],
            ['id' => 24562, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'El Barrero', 'active' => 1, 'slug' => 'el-barrero'],
            ['id' => 24563, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'El Calabacito', 'active' => 1, 'slug' => 'el-calabacito'],
            ['id' => 24564, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'El Cedro', 'active' => 1, 'slug' => 'el-cedro'],
            ['id' => 24565, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'El Ciruelo', 'active' => 1, 'slug' => 'el-ciruelo'],
            ['id' => 24566, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'El Limón', 'active' => 1, 'slug' => 'el-limon'],
            ['id' => 24567, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'El Pájaro', 'active' => 1, 'slug' => 'el-pajaro'],
            ['id' => 24568, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'El Pedregoso', 'active' => 1, 'slug' => 'el-pedregoso'],
            ['id' => 24569, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'El Rincón', 'active' => 1, 'slug' => 'el-rincon'],
            ['id' => 24570, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'El Tijera', 'active' => 1, 'slug' => 'el-tijera'],
            ['id' => 24571, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'El Toro', 'active' => 1, 'slug' => 'el-toro'],
            ['id' => 24572, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'La Arena', 'active' => 1, 'slug' => 'la-arena'],
            ['id' => 24573, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'La Pitaloza', 'active' => 1, 'slug' => 'la-pitaloza'],
            ['id' => 24574, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'Lano Bonito', 'active' => 1, 'slug' => 'lano-bonito'],
            ['id' => 24575, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'Las Cabras', 'active' => 1, 'slug' => 'las-cabras'],
            ['id' => 24576, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'Las Minas', 'active' => 1, 'slug' => 'las-minas'],
            ['id' => 24577, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'Leones', 'active' => 1, 'slug' => 'leones'],
            ['id' => 24578, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'Llano de la Cruz', 'active' => 1, 'slug' => 'llano-de-la-cruz'],
            ['id' => 24579, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'Llano Grande', 'active' => 1, 'slug' => 'llano-grande'],
            ['id' => 24580, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'Los Canelos', 'active' => 1, 'slug' => 'los-canelos'],
            ['id' => 24581, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'Los Castillos', 'active' => 1, 'slug' => 'los-castillos'],
            ['id' => 24582, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'Los Cerritos', 'active' => 1, 'slug' => 'los-cerritos'],
            ['id' => 24583, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'Los Cerros de Paja Ocú', 'active' => 1, 'slug' => 'los-cerros-de-paja-ocu'],
            ['id' => 24584, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'Los Llanos', 'active' => 1, 'slug' => 'los-llanos'],
            ['id' => 24585, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'Los Pozos', 'active' => 1, 'slug' => 'los-pozos'],
            ['id' => 24586, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'Monagrillo', 'active' => 1, 'slug' => 'monagrillo'],
            ['id' => 24587, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'Ocú', 'active' => 1, 'slug' => 'ocu'],
            ['id' => 24588, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'París', 'active' => 1, 'slug' => 'paris'],
            ['id' => 24589, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'Parita', 'active' => 1, 'slug' => 'parita'],
            ['id' => 24590, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'Peñas Chatas', 'active' => 1, 'slug' => 'penas-chatas'],
            ['id' => 24591, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'Pesé', 'active' => 1, 'slug' => 'pese'],
            ['id' => 24592, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'Portobelillo', 'active' => 1, 'slug' => 'portobelillo'],
            ['id' => 24593, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'Potuga', 'active' => 1, 'slug' => 'potuga'],
            ['id' => 24594, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'Quebrada Del Rosario', 'active' => 1, 'slug' => 'quebrada-del-rosario'],
            ['id' => 24595, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'Rincón Hondo', 'active' => 1, 'slug' => 'rincon-hondo'],
            ['id' => 24596, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'Sabanagrande', 'active' => 1, 'slug' => 'sabanagrande'],
            ['id' => 24597, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'San Juan Bautista', 'active' => 1, 'slug' => 'san-juan-bautista'],
            ['id' => 24598, 'region_id' => 710500, 'country_code' => 'PA', 'name' => 'Santa María', 'active' => 1, 'slug' => 'santa-maria'],
            ['id' => 24599, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'Agua Buena', 'active' => 1, 'slug' => 'agua-buena'],
            ['id' => 24600, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'Bahía Honda', 'active' => 1, 'slug' => 'bahia-honda'],
            ['id' => 24601, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'Bajo Corral', 'active' => 1, 'slug' => 'bajo-corral'],
            ['id' => 24602, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'Bajos de Güera', 'active' => 1, 'slug' => 'bajos-de-guera'],
            ['id' => 24603, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'Bayano', 'active' => 1, 'slug' => 'bayano'],
            ['id' => 24604, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'Chupá', 'active' => 1, 'slug' => 'chupa'],
            ['id' => 24605, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'Corozal', 'active' => 1, 'slug' => 'corozal'],
            ['id' => 24606, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'El Carate', 'active' => 1, 'slug' => 'el-carate'],
            ['id' => 24607, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'El Cedro', 'active' => 1, 'slug' => 'el-cedro'],
            ['id' => 24608, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'El Cocal', 'active' => 1, 'slug' => 'el-cocal'],
            ['id' => 24609, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'El Espinal', 'active' => 1, 'slug' => 'el-espinal'],
            ['id' => 24610, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'El Guásimo', 'active' => 1, 'slug' => 'el-guasimo'],
            ['id' => 24611, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'El H', 'active' => 1, 'slug' => 'el-h'],
            ['id' => 24612, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'El Manantial', 'active' => 1, 'slug' => 'el-manantial'],
            ['id' => 24613, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'El Muñoz', 'active' => 1, 'slug' => 'el-munoz'],
            ['id' => 24614, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'El Pedregoso', 'active' => 1, 'slug' => 'el-pedregoso'],
            ['id' => 24615, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'Espino Amarillo', 'active' => 1, 'slug' => 'espino-amarillo'],
            ['id' => 24616, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'Guararé', 'active' => 1, 'slug' => 'guarare'],
            ['id' => 24617, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'Guararé Arriba', 'active' => 1, 'slug' => 'guarare-arriba'],
            ['id' => 24618, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'La Colorada', 'active' => 1, 'slug' => 'la-colorada'],
            ['id' => 24619, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'La Enea', 'active' => 1, 'slug' => 'la-enea'],
            ['id' => 24620, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'La Espigadilla', 'active' => 1, 'slug' => 'la-espigadilla'],
            ['id' => 24621, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'La Laja', 'active' => 1, 'slug' => 'la-laja'],
            ['id' => 24622, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'La Mesa', 'active' => 1, 'slug' => 'la-mesa'],
            ['id' => 24623, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'La Miel', 'active' => 1, 'slug' => 'la-miel'],
            ['id' => 24624, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'La Palma', 'active' => 1, 'slug' => 'la-palma'],
            ['id' => 24625, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'La Pasera', 'active' => 1, 'slug' => 'la-pasera'],
            ['id' => 24626, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'La Tiza', 'active' => 1, 'slug' => 'la-tiza'],
            ['id' => 24627, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'La Villa de los Santos', 'active' => 1, 'slug' => 'la-villa-de-los-santos'],
            ['id' => 24628, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'Las Cruces', 'active' => 1, 'slug' => 'las-cruces'],
            ['id' => 24629, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'Las Guabas', 'active' => 1, 'slug' => 'las-guabas'],
            ['id' => 24630, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'Las Palmas', 'active' => 1, 'slug' => 'las-palmas'],
            ['id' => 24631, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'Las Palmitas', 'active' => 1, 'slug' => 'las-palmitas'],
            ['id' => 24632, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'Las Tablas', 'active' => 1, 'slug' => 'las-tablas'],
            ['id' => 24633, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'Las Tablas Abajo', 'active' => 1, 'slug' => 'las-tablas-abajo'],
            ['id' => 24634, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'Las Trancas', 'active' => 1, 'slug' => 'las-trancas'],
            ['id' => 24635, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'Llano Abajo', 'active' => 1, 'slug' => 'llano-abajo'],
            ['id' => 24636, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'Llano de Piedra', 'active' => 1, 'slug' => 'llano-de-piedra'],
            ['id' => 24637, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'Llano Largo', 'active' => 1, 'slug' => 'llano-largo'],
            ['id' => 24638, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'Los Angeles', 'active' => 1, 'slug' => 'los-angeles'],
            ['id' => 24639, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'Los Olivos', 'active' => 1, 'slug' => 'los-olivos'],
            ['id' => 24640, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'Los Santos', 'active' => 1, 'slug' => 'los-santos'],
            ['id' => 24641, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'Macaracas', 'active' => 1, 'slug' => 'macaracas'],
            ['id' => 24642, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'Nuario', 'active' => 1, 'slug' => 'nuario'],
            ['id' => 24643, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'Palmira', 'active' => 1, 'slug' => 'palmira'],
            ['id' => 24644, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'Pedasi', 'active' => 1, 'slug' => 'pedasi'],
            ['id' => 24645, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'Peña Blanca', 'active' => 1, 'slug' => 'pena-blanca'],
            ['id' => 24646, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'Perales', 'active' => 1, 'slug' => 'perales'],
            ['id' => 24647, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'Pocri', 'active' => 1, 'slug' => 'pocri'],
            ['id' => 24648, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'Río Hondo', 'active' => 1, 'slug' => 'rio-hondo'],
            ['id' => 24649, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'Sabanagrande', 'active' => 1, 'slug' => 'sabanagrande'],
            ['id' => 24650, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'San José', 'active' => 1, 'slug' => 'san-jose'],
            ['id' => 24651, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'San Miguel', 'active' => 1, 'slug' => 'san-miguel'],
            ['id' => 24652, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'Santa Ana', 'active' => 1, 'slug' => 'santa-ana'],
            ['id' => 24653, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'Santo Domingo', 'active' => 1, 'slug' => 'santo-domingo'],
            ['id' => 24654, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'Sesteadero', 'active' => 1, 'slug' => 'sesteadero'],
            ['id' => 24655, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'Tonosi', 'active' => 1, 'slug' => 'tonosi'],
            ['id' => 24656, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'Tres Quebradas', 'active' => 1, 'slug' => 'tres-quebradas'],
            ['id' => 24657, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'Valle Rico', 'active' => 1, 'slug' => 'valle-rico'],
            ['id' => 24658, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'Vallerriquito', 'active' => 1, 'slug' => 'vallerriquito'],
            ['id' => 24659, 'region_id' => 710545, 'country_code' => 'PA', 'name' => 'Villa Lourdes', 'active' => 1, 'slug' => 'villa-lourdes'],
            ['id' => 24660, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Amelia Denis de Icaza', 'active' => 1, 'slug' => 'amelia-denis-de-icaza'],
            ['id' => 24661, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Ancón', 'active' => 1, 'slug' => 'ancon'],
            ['id' => 24662, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Araiján', 'active' => 1, 'slug' => 'araijan'],
            ['id' => 24663, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Arosemena', 'active' => 1, 'slug' => 'arosemena'],
            ['id' => 24664, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Balboa', 'active' => 1, 'slug' => 'balboa'],
            ['id' => 24665, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Barrio Balboa', 'active' => 1, 'slug' => 'barrio-balboa'],
            ['id' => 24666, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Barrio Colón', 'active' => 1, 'slug' => 'barrio-colon'],
            ['id' => 24667, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Bejuco', 'active' => 1, 'slug' => 'bejuco'],
            ['id' => 24668, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Belisario Porras', 'active' => 1, 'slug' => 'belisario-porras'],
            ['id' => 24669, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Bella Vista', 'active' => 1, 'slug' => 'bella-vista'],
            ['id' => 24670, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Betania', 'active' => 1, 'slug' => 'betania'],
            ['id' => 24671, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Bruja', 'active' => 1, 'slug' => 'bruja'],
            ['id' => 24672, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Buenos Aires', 'active' => 1, 'slug' => 'buenos-aires'],
            ['id' => 24673, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Cabuya', 'active' => 1, 'slug' => 'cabuya'],
            ['id' => 24674, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Caimito', 'active' => 1, 'slug' => 'caimito'],
            ['id' => 24675, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Campana', 'active' => 1, 'slug' => 'campana'],
            ['id' => 24676, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Cañita', 'active' => 1, 'slug' => 'canita'],
            ['id' => 24677, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Capira', 'active' => 1, 'slug' => 'capira'],
            ['id' => 24678, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Cermeño', 'active' => 1, 'slug' => 'cermeno'],
            ['id' => 24679, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Chame', 'active' => 1, 'slug' => 'chame'],
            ['id' => 24680, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Chepillo', 'active' => 1, 'slug' => 'chepillo'],
            ['id' => 24681, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Chepo', 'active' => 1, 'slug' => 'chepo'],
            ['id' => 24682, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Chicá', 'active' => 1, 'slug' => 'chica'],
            ['id' => 24683, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Chilibre', 'active' => 1, 'slug' => 'chilibre'],
            ['id' => 24684, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Chimán', 'active' => 1, 'slug' => 'chiman'],
            ['id' => 24685, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Cirí de los Sotos', 'active' => 1, 'slug' => 'ciri-de-los-sotos'],
            ['id' => 24686, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Cirí Grande', 'active' => 1, 'slug' => 'ciri-grande'],
            ['id' => 24687, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Curundú', 'active' => 1, 'slug' => 'curundu'],
            ['id' => 24688, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'El Arado', 'active' => 1, 'slug' => 'el-arado'],
            ['id' => 24689, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'El Cacao', 'active' => 1, 'slug' => 'el-cacao'],
            ['id' => 24690, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'El Chorrillo', 'active' => 1, 'slug' => 'el-chorrillo'],
            ['id' => 24691, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'El Coco', 'active' => 1, 'slug' => 'el-coco'],
            ['id' => 24692, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'El Espino', 'active' => 1, 'slug' => 'el-espino'],
            ['id' => 24693, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'El Higo', 'active' => 1, 'slug' => 'el-higo'],
            ['id' => 24694, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'El Líbano', 'active' => 1, 'slug' => 'el-libano'],
            ['id' => 24695, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'El Llano', 'active' => 1, 'slug' => 'el-llano'],
            ['id' => 24696, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Feuillet', 'active' => 1, 'slug' => 'feuillet'],
            ['id' => 24697, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Gonzalo Vásquez', 'active' => 1, 'slug' => 'gonzalo-vasquez'],
            ['id' => 24698, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Guadalupe', 'active' => 1, 'slug' => 'guadalupe'],
            ['id' => 24699, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Guayabito', 'active' => 1, 'slug' => 'guayabito'],
            ['id' => 24700, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Herrera', 'active' => 1, 'slug' => 'herrera'],
            ['id' => 24701, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Hurtado', 'active' => 1, 'slug' => 'hurtado'],
            ['id' => 24702, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Iturralde', 'active' => 1, 'slug' => 'iturralde'],
            ['id' => 24703, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'José Domingo Espinar', 'active' => 1, 'slug' => 'jose-domingo-espinar'],
            ['id' => 24704, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Juan Demóstenes', 'active' => 1, 'slug' => 'juan-demostenes'],
            ['id' => 24705, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Juan Díaz', 'active' => 1, 'slug' => 'juan-diaz'],
            ['id' => 24706, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'La Chorrera', 'active' => 1, 'slug' => 'la-chorrera'],
            ['id' => 24707, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'La Ensenada', 'active' => 1, 'slug' => 'la-ensenada'],
            ['id' => 24708, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'La Ermita', 'active' => 1, 'slug' => 'la-ermita'],
            ['id' => 24709, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'La Esmeralda', 'active' => 1, 'slug' => 'la-esmeralda'],
            ['id' => 24710, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'La Guinea', 'active' => 1, 'slug' => 'la-guinea'],
            ['id' => 24711, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'La Laguna', 'active' => 1, 'slug' => 'la-laguna'],
            ['id' => 24712, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'La Represa', 'active' => 1, 'slug' => 'la-represa'],
            ['id' => 24713, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'La Trinidad', 'active' => 1, 'slug' => 'la-trinidad'],
            ['id' => 24714, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Las Cumbres', 'active' => 1, 'slug' => 'las-cumbres'],
            ['id' => 24715, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Las Lajas', 'active' => 1, 'slug' => 'las-lajas'],
            ['id' => 24716, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Las Margaritas', 'active' => 1, 'slug' => 'las-margaritas'],
            ['id' => 24717, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Las Ollas Arriba', 'active' => 1, 'slug' => 'las-ollas-arriba'],
            ['id' => 24718, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Las Uvas', 'active' => 1, 'slug' => 'las-uvas'],
            ['id' => 24719, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Lídice', 'active' => 1, 'slug' => 'lidice'],
            ['id' => 24720, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Los Díaz', 'active' => 1, 'slug' => 'los-diaz'],
            ['id' => 24721, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Los Llanitos', 'active' => 1, 'slug' => 'los-llanitos'],
            ['id' => 24722, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Mateo Iturralde', 'active' => 1, 'slug' => 'mateo-iturralde'],
            ['id' => 24723, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Mendoza', 'active' => 1, 'slug' => 'mendoza'],
            ['id' => 24724, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Nueva Gorgona', 'active' => 1, 'slug' => 'nueva-gorgona'],
            ['id' => 24725, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Nuevo Emperador', 'active' => 1, 'slug' => 'nuevo-emperador'],
            ['id' => 24726, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Obaldía', 'active' => 1, 'slug' => 'obaldia'],
            ['id' => 24727, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Otoque Occidente', 'active' => 1, 'slug' => 'otoque-occidente'],
            ['id' => 24728, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Otoque Oriente', 'active' => 1, 'slug' => 'otoque-oriente'],
            ['id' => 24729, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Pacora', 'active' => 1, 'slug' => 'pacora'],
            ['id' => 24730, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Panamá', 'active' => 1, 'slug' => 'panama'],
            ['id' => 24731, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Parque Lefevre', 'active' => 1, 'slug' => 'parque-lefevre'],
            ['id' => 24732, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Pásiga', 'active' => 1, 'slug' => 'pasiga'],
            ['id' => 24733, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Pedregal', 'active' => 1, 'slug' => 'pedregal'],
            ['id' => 24734, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Pedro González', 'active' => 1, 'slug' => 'pedro-gonzalez'],
            ['id' => 24735, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Playa Leona', 'active' => 1, 'slug' => 'playa-leona'],
            ['id' => 24736, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Pueblo Nuevo', 'active' => 1, 'slug' => 'pueblo-nuevo'],
            ['id' => 24737, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Puerto Caimito', 'active' => 1, 'slug' => 'puerto-caimito'],
            ['id' => 24738, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Punta Chame', 'active' => 1, 'slug' => 'punta-chame'],
            ['id' => 24739, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Río Abajo', 'active' => 1, 'slug' => 'rio-abajo'],
            ['id' => 24740, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Saboga', 'active' => 1, 'slug' => 'saboga'],
            ['id' => 24741, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Sajalices', 'active' => 1, 'slug' => 'sajalices'],
            ['id' => 24742, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'San Carlos', 'active' => 1, 'slug' => 'san-carlos'],
            ['id' => 24743, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'San Felipe', 'active' => 1, 'slug' => 'san-felipe'],
            ['id' => 24744, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'San Francisco', 'active' => 1, 'slug' => 'san-francisco'],
            ['id' => 24745, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'San José', 'active' => 1, 'slug' => 'san-jose'],
            ['id' => 24746, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'San Martín', 'active' => 1, 'slug' => 'san-martin'],
            ['id' => 24747, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'San Miguel', 'active' => 1, 'slug' => 'san-miguel'],
            ['id' => 24748, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'San Miguelito', 'active' => 1, 'slug' => 'san-miguelito'],
            ['id' => 24749, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Santa Ana', 'active' => 1, 'slug' => 'santa-ana'],
            ['id' => 24750, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Santa Clara', 'active' => 1, 'slug' => 'santa-clara'],
            ['id' => 24751, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Santa Cruz de Chinina', 'active' => 1, 'slug' => 'santa-cruz-de-chinina'],
            ['id' => 24752, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Santa Rita', 'active' => 1, 'slug' => 'santa-rita'],
            ['id' => 24753, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Santa Rosa', 'active' => 1, 'slug' => 'santa-rosa'],
            ['id' => 24754, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Sorá', 'active' => 1, 'slug' => 'sora'],
            ['id' => 24755, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Taboga', 'active' => 1, 'slug' => 'taboga'],
            ['id' => 24756, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Tocumen', 'active' => 1, 'slug' => 'tocumen'],
            ['id' => 24757, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Tortí', 'active' => 1, 'slug' => 'torti'],
            ['id' => 24758, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Unión Santeña', 'active' => 1, 'slug' => 'union-santena'],
            ['id' => 24759, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Veracruz', 'active' => 1, 'slug' => 'veracruz'],
            ['id' => 24760, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Victoriano Lorenzo', 'active' => 1, 'slug' => 'victoriano-lorenzo'],
            ['id' => 24761, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Villa Carmen', 'active' => 1, 'slug' => 'villa-carmen'],
            ['id' => 24762, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Villa Rosario', 'active' => 1, 'slug' => 'villa-rosario'],
            ['id' => 24763, 'region_id' => 710607, 'country_code' => 'PA', 'name' => 'Vista Alegre', 'active' => 1, 'slug' => 'vista-alegre'],
            ['id' => 24764, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Arenas', 'active' => 1, 'slug' => 'arenas'],
            ['id' => 24765, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Atalaya', 'active' => 1, 'slug' => 'atalaya'],
            ['id' => 24766, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Bahía Honda', 'active' => 1, 'slug' => 'bahia-honda'],
            ['id' => 24767, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Barnizal', 'active' => 1, 'slug' => 'barnizal'],
            ['id' => 24768, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Bisvalles', 'active' => 1, 'slug' => 'bisvalles'],
            ['id' => 24769, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Boró', 'active' => 1, 'slug' => 'boro'],
            ['id' => 24770, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Calidonia', 'active' => 1, 'slug' => 'calidonia'],
            ['id' => 24771, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Calobre', 'active' => 1, 'slug' => 'calobre'],
            ['id' => 24772, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Calovébora', 'active' => 1, 'slug' => 'calovebora'],
            ['id' => 24773, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Cañazas', 'active' => 1, 'slug' => 'canazas'],
            ['id' => 24774, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Canto Del Llano', 'active' => 1, 'slug' => 'canto-del-llano'],
            ['id' => 24775, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Cativé', 'active' => 1, 'slug' => 'cative'],
            ['id' => 24776, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Catorce de Noviembre', 'active' => 1, 'slug' => 'catorce-de-noviembre'],
            ['id' => 24777, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Cerro de Casa', 'active' => 1, 'slug' => 'cerro-de-casa'],
            ['id' => 24778, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Cerro de Plata', 'active' => 1, 'slug' => 'cerro-de-plata'],
            ['id' => 24779, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Chitra', 'active' => 1, 'slug' => 'chitra'],
            ['id' => 24780, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Corozal', 'active' => 1, 'slug' => 'corozal'],
            ['id' => 24781, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Corral Falso', 'active' => 1, 'slug' => 'corral-falso'],
            ['id' => 24782, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'El Alt', 'active' => 1, 'slug' => 'el-alt'],
            ['id' => 24783, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'El Barrito', 'active' => 1, 'slug' => 'el-barrito'],
            ['id' => 24784, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'El Cocla', 'active' => 1, 'slug' => 'el-cocla'],
            ['id' => 24785, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'El Cuay', 'active' => 1, 'slug' => 'el-cuay'],
            ['id' => 24786, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'El Marañón', 'active' => 1, 'slug' => 'el-maranon'],
            ['id' => 24787, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'El María', 'active' => 1, 'slug' => 'el-maria'],
            ['id' => 24788, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'El Pantano', 'active' => 1, 'slug' => 'el-pantano'],
            ['id' => 24789, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'El Picador', 'active' => 1, 'slug' => 'el-picador'],
            ['id' => 24790, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'El Potrero', 'active' => 1, 'slug' => 'el-potrero'],
            ['id' => 24791, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'El Prado', 'active' => 1, 'slug' => 'el-prado'],
            ['id' => 24792, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'El Rincón', 'active' => 1, 'slug' => 'el-rincon'],
            ['id' => 24793, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Gatú', 'active' => 1, 'slug' => 'gatu'],
            ['id' => 24794, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Gobernadora', 'active' => 1, 'slug' => 'gobernadora'],
            ['id' => 24795, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Guarumal', 'active' => 1, 'slug' => 'guarumal'],
            ['id' => 24796, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'La Carrillo', 'active' => 1, 'slug' => 'la-carrillo'],
            ['id' => 24797, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'La Colorada', 'active' => 1, 'slug' => 'la-colorada'],
            ['id' => 24798, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'La Garceana', 'active' => 1, 'slug' => 'la-garceana'],
            ['id' => 24799, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'La Laguna', 'active' => 1, 'slug' => 'la-laguna'],
            ['id' => 24800, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'La Mesa', 'active' => 1, 'slug' => 'la-mesa'],
            ['id' => 24801, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'La Montañuela', 'active' => 1, 'slug' => 'la-montanuela'],
            ['id' => 24802, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'La Peña', 'active' => 1, 'slug' => 'la-pena'],
            ['id' => 24803, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'La Raya de Calobre', 'active' => 1, 'slug' => 'la-raya-de-calobre'],
            ['id' => 24804, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'La Raya de Santa María', 'active' => 1, 'slug' => 'la-raya-de-santa-maria'],
            ['id' => 24805, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'La Soledad', 'active' => 1, 'slug' => 'la-soledad'],
            ['id' => 24806, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'La Tetilla', 'active' => 1, 'slug' => 'la-tetilla'],
            ['id' => 24807, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'La Yeguada', 'active' => 1, 'slug' => 'la-yeguada'],
            ['id' => 24808, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Las Guías', 'active' => 1, 'slug' => 'las-guias'],
            ['id' => 24809, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Las Huacas', 'active' => 1, 'slug' => 'las-huacas'],
            ['id' => 24810, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Las Palmas', 'active' => 1, 'slug' => 'las-palmas'],
            ['id' => 24811, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Leones', 'active' => 1, 'slug' => 'leones'],
            ['id' => 24812, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Llano de Catival', 'active' => 1, 'slug' => 'llano-de-catival'],
            ['id' => 24813, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Llano Grande', 'active' => 1, 'slug' => 'llano-grande'],
            ['id' => 24814, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Lolá', 'active' => 1, 'slug' => 'lola'],
            ['id' => 24815, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Los Algarrobos', 'active' => 1, 'slug' => 'los-algarrobos'],
            ['id' => 24816, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Los Castillos', 'active' => 1, 'slug' => 'los-castillos'],
            ['id' => 24817, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Los Hatillos', 'active' => 1, 'slug' => 'los-hatillos'],
            ['id' => 24818, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Los Valles', 'active' => 1, 'slug' => 'los-valles'],
            ['id' => 24819, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Monjarás', 'active' => 1, 'slug' => 'monjaras'],
            ['id' => 24820, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Montijo', 'active' => 1, 'slug' => 'montijo'],
            ['id' => 24821, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Pilón', 'active' => 1, 'slug' => 'pilon'],
            ['id' => 24822, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Pixvae', 'active' => 1, 'slug' => 'pixvae'],
            ['id' => 24823, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Ponuga', 'active' => 1, 'slug' => 'ponuga'],
            ['id' => 24824, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Puerto Vidal', 'active' => 1, 'slug' => 'puerto-vidal'],
            ['id' => 24825, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Quebrada de Oro', 'active' => 1, 'slug' => 'quebrada-de-oro'],
            ['id' => 24826, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Quebro', 'active' => 1, 'slug' => 'quebro'],
            ['id' => 24827, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Remance', 'active' => 1, 'slug' => 'remance'],
            ['id' => 24828, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Río de Jesús', 'active' => 1, 'slug' => 'rio-de-jesus'],
            ['id' => 24829, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Río Grande', 'active' => 1, 'slug' => 'rio-grande'],
            ['id' => 24830, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Río Luis', 'active' => 1, 'slug' => 'rio-luis'],
            ['id' => 24831, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Rodeo Viejo', 'active' => 1, 'slug' => 'rodeo-viejo'],
            ['id' => 24832, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'San Antonio', 'active' => 1, 'slug' => 'san-antonio'],
            ['id' => 24833, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'San Bartolo', 'active' => 1, 'slug' => 'san-bartolo'],
            ['id' => 24834, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'San Francisco', 'active' => 1, 'slug' => 'san-francisco'],
            ['id' => 24835, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'San José', 'active' => 1, 'slug' => 'san-jose'],
            ['id' => 24836, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'San Juan', 'active' => 1, 'slug' => 'san-juan'],
            ['id' => 24837, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'San Marcelo', 'active' => 1, 'slug' => 'san-marcelo'],
            ['id' => 24838, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'San Martín de Porres', 'active' => 1, 'slug' => 'san-martin-de-porres'],
            ['id' => 24839, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'San Pedro Del Espino', 'active' => 1, 'slug' => 'san-pedro-del-espino'],
            ['id' => 24840, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Santa Fe', 'active' => 1, 'slug' => 'santa-fe'],
            ['id' => 24841, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Santiago', 'active' => 1, 'slug' => 'santiago'],
            ['id' => 24842, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Soná', 'active' => 1, 'slug' => 'sona'],
            ['id' => 24843, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Tebario', 'active' => 1, 'slug' => 'tebario'],
            ['id' => 24844, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Utira', 'active' => 1, 'slug' => 'utira'],
            ['id' => 24845, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Viguí', 'active' => 1, 'slug' => 'vigui'],
            ['id' => 24846, 'region_id' => 710712, 'country_code' => 'PA', 'name' => 'Zapotillo', 'active' => 1, 'slug' => 'zapotillo'],
            ['id' => 24847, 'region_id' => 710796, 'country_code' => 'PA', 'name' => 'Besiko', 'active' => 1, 'slug' => 'besiko'],
            ['id' => 24848, 'region_id' => 710796, 'country_code' => 'PA', 'name' => 'Kankintu', 'active' => 1, 'slug' => 'kankintu'],
            ['id' => 24849, 'region_id' => 710796, 'country_code' => 'PA', 'name' => 'Kusapin', 'active' => 1, 'slug' => 'kusapin'],
            ['id' => 24850, 'region_id' => 710796, 'country_code' => 'PA', 'name' => 'Mirono', 'active' => 1, 'slug' => 'mirono'],
            ['id' => 24851, 'region_id' => 710796, 'country_code' => 'PA', 'name' => 'Muna', 'active' => 1, 'slug' => 'muna'],
            ['id' => 24852, 'region_id' => 710796, 'country_code' => 'PA', 'name' => 'Nole Duima', 'active' => 1, 'slug' => 'nole-duima'],
            ['id' => 24853, 'region_id' => 710796, 'country_code' => 'PA', 'name' => 'Ñurun', 'active' => 1, 'slug' => 'nurun']
    	];
    }
}
