<?php

namespace Gerardojbaez\GeoData\Seeders;

use Illuminate\Database\Seeder;
use Gerardojbaez\GeoData\Models\Country;
use Gerardojbaez\GeoData\Models\Region;
use Gerardojbaez\GeoData\Models\City;

class SwedenSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Country::create($this->country());
        Region::insert($this->regions());

        if ($this->cities() > 4000)
        {
            foreach (array_chunk($this->cities(), 3500) as $chunk)
                City::insert($chunk);
        }
        else
        {
            City::insert($this->cities());
        }
    }

        /**
     * Get country.
     *
     * @return array
     */
    public function country()
    {
    	return ['code' => 'SE', 'name' => 'Sweden', 'slug' => 'sweden'];
    }

    /**
     * Get country regions.
     *
     * @return array
     */
    public function regions()
    {
    	return [
            ['id' => 782481, 'country_code' => 'SE', 'name' => 'Blekinge', 'active' => 1, 'slug' => 'blekinge'],
            ['id' => 782482, 'country_code' => 'SE', 'name' => 'Dalarnas', 'active' => 1, 'slug' => 'dalarnas'],
            ['id' => 782483, 'country_code' => 'SE', 'name' => 'Gävleborgs', 'active' => 1, 'slug' => 'gavleborgs'],
            ['id' => 782484, 'country_code' => 'SE', 'name' => 'Gotlands', 'active' => 1, 'slug' => 'gotlands'],
            ['id' => 782485, 'country_code' => 'SE', 'name' => 'Hallands', 'active' => 1, 'slug' => 'hallands'],
            ['id' => 782486, 'country_code' => 'SE', 'name' => 'Jämtlands', 'active' => 1, 'slug' => 'jamtlands'],
            ['id' => 782487, 'country_code' => 'SE', 'name' => 'Jönköpings', 'active' => 1, 'slug' => 'jonkopings'],
            ['id' => 782488, 'country_code' => 'SE', 'name' => 'Kalmar', 'active' => 1, 'slug' => 'kalmar'],
            ['id' => 782489, 'country_code' => 'SE', 'name' => 'Kronobergs', 'active' => 1, 'slug' => 'kronobergs'],
            ['id' => 782490, 'country_code' => 'SE', 'name' => 'Norrbottens', 'active' => 1, 'slug' => 'norrbottens'],
            ['id' => 782491, 'country_code' => 'SE', 'name' => 'Örebro', 'active' => 1, 'slug' => 'orebro'],
            ['id' => 782492, 'country_code' => 'SE', 'name' => 'Östergötlands', 'active' => 1, 'slug' => 'ostergotlands'],
            ['id' => 782493, 'country_code' => 'SE', 'name' => 'Skåne', 'active' => 1, 'slug' => 'skane'],
            ['id' => 782494, 'country_code' => 'SE', 'name' => 'Södermanlands', 'active' => 1, 'slug' => 'sodermanlands'],
            ['id' => 782495, 'country_code' => 'SE', 'name' => 'Stockholms', 'active' => 1, 'slug' => 'stockholms'],
            ['id' => 782496, 'country_code' => 'SE', 'name' => 'Uppsala', 'active' => 1, 'slug' => 'uppsala'],
            ['id' => 782497, 'country_code' => 'SE', 'name' => 'Värmlands', 'active' => 1, 'slug' => 'varmlands'],
            ['id' => 782498, 'country_code' => 'SE', 'name' => 'Västerbottens', 'active' => 1, 'slug' => 'vasterbottens'],
            ['id' => 782499, 'country_code' => 'SE', 'name' => 'Västernorrlands', 'active' => 1, 'slug' => 'vasternorrlands'],
            ['id' => 782500, 'country_code' => 'SE', 'name' => 'Västmanlands', 'active' => 1, 'slug' => 'vastmanlands'],
            ['id' => 782501, 'country_code' => 'SE', 'name' => 'Västra Götalands', 'active' => 1, 'slug' => 'vastra-gotalands']
    	];
    }

    /**
     * Get region cities.
     *
     * @return array
     */
    public function cities()
    {
    	return [
            ['id' => 409753, 'region_id' => 782481, 'country_code' => 'SE', 'name' => 'Karlshamn', 'active' => 1, 'slug' => 'karlshamn'],
            ['id' => 409754, 'region_id' => 782481, 'country_code' => 'SE', 'name' => 'Olofström', 'active' => 1, 'slug' => 'olofstrom'],
            ['id' => 409755, 'region_id' => 782481, 'country_code' => 'SE', 'name' => 'Sölvesborg', 'active' => 1, 'slug' => 'solvesborg'],
            ['id' => 409756, 'region_id' => 782481, 'country_code' => 'SE', 'name' => 'Ronneby', 'active' => 1, 'slug' => 'ronneby'],
            ['id' => 409757, 'region_id' => 782481, 'country_code' => 'SE', 'name' => 'Karlskrona', 'active' => 1, 'slug' => 'karlskrona'],
            ['id' => 409758, 'region_id' => 782482, 'country_code' => 'SE', 'name' => 'Mora', 'active' => 1, 'slug' => 'mora'],
            ['id' => 409759, 'region_id' => 782482, 'country_code' => 'SE', 'name' => 'Säter', 'active' => 1, 'slug' => 'sater'],
            ['id' => 409760, 'region_id' => 782482, 'country_code' => 'SE', 'name' => 'Gagnef', 'active' => 1, 'slug' => 'gagnef'],
            ['id' => 409761, 'region_id' => 782482, 'country_code' => 'SE', 'name' => 'Älvdalen', 'active' => 1, 'slug' => 'alvdalen'],
            ['id' => 409762, 'region_id' => 782482, 'country_code' => 'SE', 'name' => 'Vansbro', 'active' => 1, 'slug' => 'vansbro'],
            ['id' => 409763, 'region_id' => 782482, 'country_code' => 'SE', 'name' => 'Rättvik', 'active' => 1, 'slug' => 'rattvik'],
            ['id' => 409764, 'region_id' => 782482, 'country_code' => 'SE', 'name' => 'Smedjebacken', 'active' => 1, 'slug' => 'smedjebacken'],
            ['id' => 409765, 'region_id' => 782482, 'country_code' => 'SE', 'name' => 'Malung', 'active' => 1, 'slug' => 'malung'],
            ['id' => 409766, 'region_id' => 782482, 'country_code' => 'SE', 'name' => 'Orsa', 'active' => 1, 'slug' => 'orsa'],
            ['id' => 409767, 'region_id' => 782482, 'country_code' => 'SE', 'name' => 'Leksand', 'active' => 1, 'slug' => 'leksand'],
            ['id' => 409768, 'region_id' => 782482, 'country_code' => 'SE', 'name' => 'Hedemora', 'active' => 1, 'slug' => 'hedemora'],
            ['id' => 409769, 'region_id' => 782482, 'country_code' => 'SE', 'name' => 'Ludvika', 'active' => 1, 'slug' => 'ludvika'],
            ['id' => 409770, 'region_id' => 782482, 'country_code' => 'SE', 'name' => 'Avesta', 'active' => 1, 'slug' => 'avesta'],
            ['id' => 409771, 'region_id' => 782482, 'country_code' => 'SE', 'name' => 'Falun', 'active' => 1, 'slug' => 'falun'],
            ['id' => 409772, 'region_id' => 782482, 'country_code' => 'SE', 'name' => 'Borlänge', 'active' => 1, 'slug' => 'borlange'],
            ['id' => 409773, 'region_id' => 782483, 'country_code' => 'SE', 'name' => 'Ljusdal', 'active' => 1, 'slug' => 'ljusdal'],
            ['id' => 409774, 'region_id' => 782483, 'country_code' => 'SE', 'name' => 'Nordanstig', 'active' => 1, 'slug' => 'nordanstig'],
            ['id' => 409775, 'region_id' => 782483, 'country_code' => 'SE', 'name' => 'Ovanåker', 'active' => 1, 'slug' => 'ovanaker'],
            ['id' => 409776, 'region_id' => 782483, 'country_code' => 'SE', 'name' => 'Sandviken', 'active' => 1, 'slug' => 'sandviken'],
            ['id' => 409777, 'region_id' => 782483, 'country_code' => 'SE', 'name' => 'Söderhamn', 'active' => 1, 'slug' => 'soderhamn'],
            ['id' => 409778, 'region_id' => 782483, 'country_code' => 'SE', 'name' => 'Ockelbo', 'active' => 1, 'slug' => 'ockelbo'],
            ['id' => 409779, 'region_id' => 782483, 'country_code' => 'SE', 'name' => 'Hofors', 'active' => 1, 'slug' => 'hofors'],
            ['id' => 409780, 'region_id' => 782483, 'country_code' => 'SE', 'name' => 'Bollnäs', 'active' => 1, 'slug' => 'bollnas'],
            ['id' => 409781, 'region_id' => 782483, 'country_code' => 'SE', 'name' => 'Hudiksvall', 'active' => 1, 'slug' => 'hudiksvall'],
            ['id' => 409782, 'region_id' => 782483, 'country_code' => 'SE', 'name' => 'Gävle', 'active' => 1, 'slug' => 'gavle'],
            ['id' => 409783, 'region_id' => 782484, 'country_code' => 'SE', 'name' => 'Gotland', 'active' => 1, 'slug' => 'gotland'],
            ['id' => 409784, 'region_id' => 782485, 'country_code' => 'SE', 'name' => 'Halmstad', 'active' => 1, 'slug' => 'halmstad'],
            ['id' => 409785, 'region_id' => 782485, 'country_code' => 'SE', 'name' => 'Hylte', 'active' => 1, 'slug' => 'hylte'],
            ['id' => 409786, 'region_id' => 782485, 'country_code' => 'SE', 'name' => 'Laholm', 'active' => 1, 'slug' => 'laholm'],
            ['id' => 409787, 'region_id' => 782485, 'country_code' => 'SE', 'name' => 'Falkenberg', 'active' => 1, 'slug' => 'falkenberg'],
            ['id' => 409788, 'region_id' => 782485, 'country_code' => 'SE', 'name' => 'Kungsbacka', 'active' => 1, 'slug' => 'kungsbacka'],
            ['id' => 409789, 'region_id' => 782485, 'country_code' => 'SE', 'name' => 'Varberg', 'active' => 1, 'slug' => 'varberg'],
            ['id' => 409790, 'region_id' => 782486, 'country_code' => 'SE', 'name' => 'Berg', 'active' => 1, 'slug' => 'berg'],
            ['id' => 409791, 'region_id' => 782486, 'country_code' => 'SE', 'name' => 'Bräcke', 'active' => 1, 'slug' => 'bracke'],
            ['id' => 409792, 'region_id' => 782486, 'country_code' => 'SE', 'name' => 'Härjedalen', 'active' => 1, 'slug' => 'harjedalen'],
            ['id' => 409793, 'region_id' => 782486, 'country_code' => 'SE', 'name' => 'Ragunda', 'active' => 1, 'slug' => 'ragunda'],
            ['id' => 409794, 'region_id' => 782486, 'country_code' => 'SE', 'name' => 'Strömsund', 'active' => 1, 'slug' => 'stromsund'],
            ['id' => 409795, 'region_id' => 782486, 'country_code' => 'SE', 'name' => 'Åre', 'active' => 1, 'slug' => 'are'],
            ['id' => 409796, 'region_id' => 782486, 'country_code' => 'SE', 'name' => 'Krokom', 'active' => 1, 'slug' => 'krokom'],
            ['id' => 409797, 'region_id' => 782486, 'country_code' => 'SE', 'name' => 'Östersund', 'active' => 1, 'slug' => 'ostersund'],
            ['id' => 409798, 'region_id' => 782487, 'country_code' => 'SE', 'name' => 'Habo', 'active' => 1, 'slug' => 'habo'],
            ['id' => 409799, 'region_id' => 782487, 'country_code' => 'SE', 'name' => 'Sävsjö', 'active' => 1, 'slug' => 'savsjo'],
            ['id' => 409800, 'region_id' => 782487, 'country_code' => 'SE', 'name' => 'Tranås', 'active' => 1, 'slug' => 'tranas'],
            ['id' => 409801, 'region_id' => 782487, 'country_code' => 'SE', 'name' => 'Aneby', 'active' => 1, 'slug' => 'aneby'],
            ['id' => 409802, 'region_id' => 782487, 'country_code' => 'SE', 'name' => 'Gnosjö', 'active' => 1, 'slug' => 'gnosjo'],
            ['id' => 409803, 'region_id' => 782487, 'country_code' => 'SE', 'name' => 'Vaggeryd', 'active' => 1, 'slug' => 'vaggeryd'],
            ['id' => 409804, 'region_id' => 782487, 'country_code' => 'SE', 'name' => 'Mullsjö', 'active' => 1, 'slug' => 'mullsjo'],
            ['id' => 409805, 'region_id' => 782487, 'country_code' => 'SE', 'name' => 'Eksjö', 'active' => 1, 'slug' => 'eksjo'],
            ['id' => 409806, 'region_id' => 782487, 'country_code' => 'SE', 'name' => 'Gislaved', 'active' => 1, 'slug' => 'gislaved'],
            ['id' => 409807, 'region_id' => 782487, 'country_code' => 'SE', 'name' => 'Vetlanda', 'active' => 1, 'slug' => 'vetlanda'],
            ['id' => 409808, 'region_id' => 782487, 'country_code' => 'SE', 'name' => 'Nässjö', 'active' => 1, 'slug' => 'nassjo'],
            ['id' => 409809, 'region_id' => 782487, 'country_code' => 'SE', 'name' => 'Jönköping', 'active' => 1, 'slug' => 'jonkoping'],
            ['id' => 409810, 'region_id' => 782488, 'country_code' => 'SE', 'name' => 'Nybro', 'active' => 1, 'slug' => 'nybro'],
            ['id' => 409811, 'region_id' => 782488, 'country_code' => 'SE', 'name' => 'Oskarshamn', 'active' => 1, 'slug' => 'oskarshamn'],
            ['id' => 409812, 'region_id' => 782488, 'country_code' => 'SE', 'name' => 'Västervik', 'active' => 1, 'slug' => 'vastervik'],
            ['id' => 409813, 'region_id' => 782488, 'country_code' => 'SE', 'name' => 'Mörbylånga', 'active' => 1, 'slug' => 'morbylanga'],
            ['id' => 409814, 'region_id' => 782488, 'country_code' => 'SE', 'name' => 'Torsås', 'active' => 1, 'slug' => 'torsas'],
            ['id' => 409815, 'region_id' => 782488, 'country_code' => 'SE', 'name' => 'Högsby', 'active' => 1, 'slug' => 'hogsby'],
            ['id' => 409816, 'region_id' => 782488, 'country_code' => 'SE', 'name' => 'Borgholm', 'active' => 1, 'slug' => 'borgholm'],
            ['id' => 409817, 'region_id' => 782488, 'country_code' => 'SE', 'name' => 'Mönsterås', 'active' => 1, 'slug' => 'monsteras'],
            ['id' => 409818, 'region_id' => 782488, 'country_code' => 'SE', 'name' => 'Emmaboda', 'active' => 1, 'slug' => 'emmaboda'],
            ['id' => 409819, 'region_id' => 782488, 'country_code' => 'SE', 'name' => 'Hultsfred', 'active' => 1, 'slug' => 'hultsfred'],
            ['id' => 409820, 'region_id' => 782488, 'country_code' => 'SE', 'name' => 'Vimmerby', 'active' => 1, 'slug' => 'vimmerby'],
            ['id' => 409821, 'region_id' => 782488, 'country_code' => 'SE', 'name' => 'Värnamo', 'active' => 1, 'slug' => 'varnamo'],
            ['id' => 409822, 'region_id' => 782488, 'country_code' => 'SE', 'name' => 'Kalmar', 'active' => 1, 'slug' => 'kalmar'],
            ['id' => 409823, 'region_id' => 782489, 'country_code' => 'SE', 'name' => 'Ljungby', 'active' => 1, 'slug' => 'ljungby'],
            ['id' => 409824, 'region_id' => 782489, 'country_code' => 'SE', 'name' => 'Uppvidinge', 'active' => 1, 'slug' => 'uppvidinge'],
            ['id' => 409825, 'region_id' => 782489, 'country_code' => 'SE', 'name' => 'Älmhult', 'active' => 1, 'slug' => 'almhult'],
            ['id' => 409826, 'region_id' => 782489, 'country_code' => 'SE', 'name' => 'Lessebo', 'active' => 1, 'slug' => 'lessebo'],
            ['id' => 409827, 'region_id' => 782489, 'country_code' => 'SE', 'name' => 'Tingsryd', 'active' => 1, 'slug' => 'tingsryd'],
            ['id' => 409828, 'region_id' => 782489, 'country_code' => 'SE', 'name' => 'Markaryd', 'active' => 1, 'slug' => 'markaryd'],
            ['id' => 409829, 'region_id' => 782489, 'country_code' => 'SE', 'name' => 'Alvesta', 'active' => 1, 'slug' => 'alvesta'],
            ['id' => 409830, 'region_id' => 782489, 'country_code' => 'SE', 'name' => 'Växjö', 'active' => 1, 'slug' => 'vaxjo'],
            ['id' => 409831, 'region_id' => 782490, 'country_code' => 'SE', 'name' => 'Överkalix', 'active' => 1, 'slug' => 'overkalix'],
            ['id' => 409832, 'region_id' => 782490, 'country_code' => 'SE', 'name' => 'Arjeplog', 'active' => 1, 'slug' => 'arjeplog'],
            ['id' => 409833, 'region_id' => 782490, 'country_code' => 'SE', 'name' => 'Övertorneå', 'active' => 1, 'slug' => 'overtornea'],
            ['id' => 409834, 'region_id' => 782490, 'country_code' => 'SE', 'name' => 'Pajala', 'active' => 1, 'slug' => 'pajala'],
            ['id' => 409835, 'region_id' => 782490, 'country_code' => 'SE', 'name' => 'Jokkmokk', 'active' => 1, 'slug' => 'jokkmokk'],
            ['id' => 409836, 'region_id' => 782490, 'country_code' => 'SE', 'name' => 'Arvidsjaur', 'active' => 1, 'slug' => 'arvidsjaur'],
            ['id' => 409837, 'region_id' => 782490, 'country_code' => 'SE', 'name' => 'Haparanda', 'active' => 1, 'slug' => 'haparanda'],
            ['id' => 409838, 'region_id' => 782490, 'country_code' => 'SE', 'name' => 'Älvsbyn', 'active' => 1, 'slug' => 'alvsbyn'],
            ['id' => 409839, 'region_id' => 782490, 'country_code' => 'SE', 'name' => 'Kalix', 'active' => 1, 'slug' => 'kalix'],
            ['id' => 409840, 'region_id' => 782490, 'country_code' => 'SE', 'name' => 'Gällivare', 'active' => 1, 'slug' => 'gallivare'],
            ['id' => 409841, 'region_id' => 782490, 'country_code' => 'SE', 'name' => 'Kiruna', 'active' => 1, 'slug' => 'kiruna'],
            ['id' => 409842, 'region_id' => 782490, 'country_code' => 'SE', 'name' => 'Boden', 'active' => 1, 'slug' => 'boden'],
            ['id' => 409843, 'region_id' => 782490, 'country_code' => 'SE', 'name' => 'Luleå', 'active' => 1, 'slug' => 'lulea'],
            ['id' => 409844, 'region_id' => 782491, 'country_code' => 'SE', 'name' => 'Kumla', 'active' => 1, 'slug' => 'kumla'],
            ['id' => 409845, 'region_id' => 782491, 'country_code' => 'SE', 'name' => 'Lekeberg', 'active' => 1, 'slug' => 'lekeberg'],
            ['id' => 409846, 'region_id' => 782491, 'country_code' => 'SE', 'name' => 'Lindesberg', 'active' => 1, 'slug' => 'lindesberg'],
            ['id' => 409847, 'region_id' => 782491, 'country_code' => 'SE', 'name' => 'Ljusnarsberg', 'active' => 1, 'slug' => 'ljusnarsberg'],
            ['id' => 409848, 'region_id' => 782491, 'country_code' => 'SE', 'name' => 'Nora', 'active' => 1, 'slug' => 'nora'],
            ['id' => 409849, 'region_id' => 782491, 'country_code' => 'SE', 'name' => 'Laxå', 'active' => 1, 'slug' => 'laxa'],
            ['id' => 409850, 'region_id' => 782491, 'country_code' => 'SE', 'name' => 'Örebro', 'active' => 1, 'slug' => 'orebro'],
            ['id' => 409851, 'region_id' => 782492, 'country_code' => 'SE', 'name' => 'Vadstena', 'active' => 1, 'slug' => 'vadstena'],
            ['id' => 409852, 'region_id' => 782492, 'country_code' => 'SE', 'name' => 'Ydre', 'active' => 1, 'slug' => 'ydre'],
            ['id' => 409853, 'region_id' => 782492, 'country_code' => 'SE', 'name' => 'Ödeshög', 'active' => 1, 'slug' => 'odeshog'],
            ['id' => 409854, 'region_id' => 782492, 'country_code' => 'SE', 'name' => 'Valdemarsvik', 'active' => 1, 'slug' => 'valdemarsvik'],
            ['id' => 409855, 'region_id' => 782492, 'country_code' => 'SE', 'name' => 'Åtvidaberg', 'active' => 1, 'slug' => 'atvidaberg'],
            ['id' => 409856, 'region_id' => 782492, 'country_code' => 'SE', 'name' => 'Söderköping', 'active' => 1, 'slug' => 'soderkoping'],
            ['id' => 409857, 'region_id' => 782492, 'country_code' => 'SE', 'name' => 'Motala', 'active' => 1, 'slug' => 'motala'],
            ['id' => 409858, 'region_id' => 782492, 'country_code' => 'SE', 'name' => 'Norrköping', 'active' => 1, 'slug' => 'norrkoping'],
            ['id' => 409859, 'region_id' => 782492, 'country_code' => 'SE', 'name' => 'Linköping', 'active' => 1, 'slug' => 'linkoping'],
            ['id' => 409860, 'region_id' => 782493, 'country_code' => 'SE', 'name' => 'Burlöv', 'active' => 1, 'slug' => 'burlov'],
            ['id' => 409861, 'region_id' => 782493, 'country_code' => 'SE', 'name' => 'Klippan', 'active' => 1, 'slug' => 'klippan'],
            ['id' => 409862, 'region_id' => 782493, 'country_code' => 'SE', 'name' => 'Lund', 'active' => 1, 'slug' => 'lund'],
            ['id' => 409863, 'region_id' => 782493, 'country_code' => 'SE', 'name' => 'Perstorp', 'active' => 1, 'slug' => 'perstorp'],
            ['id' => 409864, 'region_id' => 782493, 'country_code' => 'SE', 'name' => 'Tomelillla', 'active' => 1, 'slug' => 'tomelillla'],
            ['id' => 409865, 'region_id' => 782493, 'country_code' => 'SE', 'name' => 'Östra Göinge', 'active' => 1, 'slug' => 'ostra-goinge'],
            ['id' => 409866, 'region_id' => 782493, 'country_code' => 'SE', 'name' => 'Svalöv', 'active' => 1, 'slug' => 'svalov'],
            ['id' => 409867, 'region_id' => 782493, 'country_code' => 'SE', 'name' => 'Örkelljunga', 'active' => 1, 'slug' => 'orkelljunga'],
            ['id' => 409868, 'region_id' => 782493, 'country_code' => 'SE', 'name' => 'Båstad', 'active' => 1, 'slug' => 'bastad'],
            ['id' => 409869, 'region_id' => 782493, 'country_code' => 'SE', 'name' => 'Vellinge', 'active' => 1, 'slug' => 'vellinge'],
            ['id' => 409870, 'region_id' => 782493, 'country_code' => 'SE', 'name' => 'Bjuv', 'active' => 1, 'slug' => 'bjuv'],
            ['id' => 409871, 'region_id' => 782493, 'country_code' => 'SE', 'name' => 'Sjöbo', 'active' => 1, 'slug' => 'sjobo'],
            ['id' => 409872, 'region_id' => 782493, 'country_code' => 'SE', 'name' => 'Simrishamn', 'active' => 1, 'slug' => 'simrishamn'],
            ['id' => 409873, 'region_id' => 782493, 'country_code' => 'SE', 'name' => 'Hörby', 'active' => 1, 'slug' => 'horby'],
            ['id' => 409874, 'region_id' => 782493, 'country_code' => 'SE', 'name' => 'Osby', 'active' => 1, 'slug' => 'osby'],
            ['id' => 409875, 'region_id' => 782493, 'country_code' => 'SE', 'name' => 'Skurup', 'active' => 1, 'slug' => 'skurup'],
            ['id' => 409876, 'region_id' => 782493, 'country_code' => 'SE', 'name' => 'Höör', 'active' => 1, 'slug' => 'hoor'],
            ['id' => 409877, 'region_id' => 782493, 'country_code' => 'SE', 'name' => 'Bromölla', 'active' => 1, 'slug' => 'bromolla'],
            ['id' => 409878, 'region_id' => 782493, 'country_code' => 'SE', 'name' => 'Åstorp', 'active' => 1, 'slug' => 'astorp'],
            ['id' => 409879, 'region_id' => 782493, 'country_code' => 'SE', 'name' => 'Lomma', 'active' => 1, 'slug' => 'lomma'],
            ['id' => 409880, 'region_id' => 782493, 'country_code' => 'SE', 'name' => 'Svedala', 'active' => 1, 'slug' => 'svedala'],
            ['id' => 409881, 'region_id' => 782493, 'country_code' => 'SE', 'name' => 'Höganäs', 'active' => 1, 'slug' => 'hoganas'],
            ['id' => 409882, 'region_id' => 782493, 'country_code' => 'SE', 'name' => 'Kävlinge', 'active' => 1, 'slug' => 'kavlinge'],
            ['id' => 409883, 'region_id' => 782493, 'country_code' => 'SE', 'name' => 'Staffanstorp', 'active' => 1, 'slug' => 'staffanstorp'],
            ['id' => 409884, 'region_id' => 782493, 'country_code' => 'SE', 'name' => 'Eslöv', 'active' => 1, 'slug' => 'eslov'],
            ['id' => 409885, 'region_id' => 782493, 'country_code' => 'SE', 'name' => 'Hässleholm', 'active' => 1, 'slug' => 'hassleholm'],
            ['id' => 409886, 'region_id' => 782493, 'country_code' => 'SE', 'name' => 'Ystad', 'active' => 1, 'slug' => 'ystad'],
            ['id' => 409887, 'region_id' => 782493, 'country_code' => 'SE', 'name' => 'Ängelholm', 'active' => 1, 'slug' => 'angelholm'],
            ['id' => 409888, 'region_id' => 782493, 'country_code' => 'SE', 'name' => 'Trelleborg', 'active' => 1, 'slug' => 'trelleborg'],
            ['id' => 409889, 'region_id' => 782493, 'country_code' => 'SE', 'name' => 'Landskrona', 'active' => 1, 'slug' => 'landskrona'],
            ['id' => 409890, 'region_id' => 782493, 'country_code' => 'SE', 'name' => 'Kristianstad', 'active' => 1, 'slug' => 'kristianstad'],
            ['id' => 409891, 'region_id' => 782493, 'country_code' => 'SE', 'name' => 'Helsingborg', 'active' => 1, 'slug' => 'helsingborg'],
            ['id' => 409892, 'region_id' => 782493, 'country_code' => 'SE', 'name' => 'Malmö', 'active' => 1, 'slug' => 'malmo'],
            ['id' => 409893, 'region_id' => 782494, 'country_code' => 'SE', 'name' => 'Katrineholm', 'active' => 1, 'slug' => 'katrineholm'],
            ['id' => 409894, 'region_id' => 782494, 'country_code' => 'SE', 'name' => 'Vingåker', 'active' => 1, 'slug' => 'vingaker'],
            ['id' => 409895, 'region_id' => 782494, 'country_code' => 'SE', 'name' => 'Trosa', 'active' => 1, 'slug' => 'trosa'],
            ['id' => 409896, 'region_id' => 782494, 'country_code' => 'SE', 'name' => 'Gnesta', 'active' => 1, 'slug' => 'gnesta'],
            ['id' => 409897, 'region_id' => 782494, 'country_code' => 'SE', 'name' => 'Flen', 'active' => 1, 'slug' => 'flen'],
            ['id' => 409898, 'region_id' => 782494, 'country_code' => 'SE', 'name' => 'Oxelösund', 'active' => 1, 'slug' => 'oxelosund'],
            ['id' => 409899, 'region_id' => 782494, 'country_code' => 'SE', 'name' => 'Strängnäs', 'active' => 1, 'slug' => 'strangnas'],
            ['id' => 409900, 'region_id' => 782494, 'country_code' => 'SE', 'name' => 'Nyköping', 'active' => 1, 'slug' => 'nykoping'],
            ['id' => 409901, 'region_id' => 782494, 'country_code' => 'SE', 'name' => 'Eskilstuna', 'active' => 1, 'slug' => 'eskilstuna'],
            ['id' => 409902, 'region_id' => 782495, 'country_code' => 'SE', 'name' => 'Botkyrka', 'active' => 1, 'slug' => 'botkyrka'],
            ['id' => 409903, 'region_id' => 782495, 'country_code' => 'SE', 'name' => 'Danderyd', 'active' => 1, 'slug' => 'danderyd'],
            ['id' => 409904, 'region_id' => 782495, 'country_code' => 'SE', 'name' => 'Järfälla', 'active' => 1, 'slug' => 'jarfalla'],
            ['id' => 409905, 'region_id' => 782495, 'country_code' => 'SE', 'name' => 'Nacka', 'active' => 1, 'slug' => 'nacka'],
            ['id' => 409906, 'region_id' => 782495, 'country_code' => 'SE', 'name' => 'Nykvarn', 'active' => 1, 'slug' => 'nykvarn'],
            ['id' => 409907, 'region_id' => 782495, 'country_code' => 'SE', 'name' => 'Stockholm', 'active' => 1, 'slug' => 'stockholm'],
            ['id' => 409908, 'region_id' => 782495, 'country_code' => 'SE', 'name' => 'Bromma', 'active' => 1, 'slug' => 'bromma'],
            ['id' => 409909, 'region_id' => 782495, 'country_code' => 'SE', 'name' => 'Enskede', 'active' => 1, 'slug' => 'enskede'],
            ['id' => 409910, 'region_id' => 782495, 'country_code' => 'SE', 'name' => 'Farsta', 'active' => 1, 'slug' => 'farsta'],
            ['id' => 409911, 'region_id' => 782495, 'country_code' => 'SE', 'name' => 'Hägersten', 'active' => 1, 'slug' => 'hagersten'],
            ['id' => 409912, 'region_id' => 782495, 'country_code' => 'SE', 'name' => 'Hässelby-Vällingby', 'active' => 1, 'slug' => 'hasselby-vallingby'],
            ['id' => 409913, 'region_id' => 782495, 'country_code' => 'SE', 'name' => 'Katarina-Sofia', 'active' => 1, 'slug' => 'katarina-sofia'],
            ['id' => 409914, 'region_id' => 782495, 'country_code' => 'SE', 'name' => 'Kungsholmen', 'active' => 1, 'slug' => 'kungsholmen'],
            ['id' => 409915, 'region_id' => 782495, 'country_code' => 'SE', 'name' => 'Maria-Gamla stan', 'active' => 1, 'slug' => 'maria-gamla-stan'],
            ['id' => 409916, 'region_id' => 782495, 'country_code' => 'SE', 'name' => 'Norrmalm', 'active' => 1, 'slug' => 'norrmalm'],
            ['id' => 409917, 'region_id' => 782495, 'country_code' => 'SE', 'name' => 'Skarpnäck', 'active' => 1, 'slug' => 'skarpnack'],
            ['id' => 409918, 'region_id' => 782495, 'country_code' => 'SE', 'name' => 'Skärholmen', 'active' => 1, 'slug' => 'skarholmen'],
            ['id' => 409919, 'region_id' => 782495, 'country_code' => 'SE', 'name' => 'Spånga', 'active' => 1, 'slug' => 'spanga'],
            ['id' => 409920, 'region_id' => 782495, 'country_code' => 'SE', 'name' => 'Södermalm', 'active' => 1, 'slug' => 'sodermalm'],
            ['id' => 409921, 'region_id' => 782495, 'country_code' => 'SE', 'name' => 'Vantör', 'active' => 1, 'slug' => 'vantor'],
            ['id' => 409922, 'region_id' => 782495, 'country_code' => 'SE', 'name' => 'Älvsjö', 'active' => 1, 'slug' => 'alvsjo'],
            ['id' => 409923, 'region_id' => 782495, 'country_code' => 'SE', 'name' => 'Östermalm', 'active' => 1, 'slug' => 'ostermalm'],
            ['id' => 409924, 'region_id' => 782495, 'country_code' => 'SE', 'name' => 'Tyresö', 'active' => 1, 'slug' => 'tyreso'],
            ['id' => 409925, 'region_id' => 782495, 'country_code' => 'SE', 'name' => 'Täby', 'active' => 1, 'slug' => 'taby'],
            ['id' => 409926, 'region_id' => 782495, 'country_code' => 'SE', 'name' => 'Upplands Bro', 'active' => 1, 'slug' => 'upplands-bro'],
            ['id' => 409927, 'region_id' => 782495, 'country_code' => 'SE', 'name' => 'Värmdö', 'active' => 1, 'slug' => 'varmdo'],
            ['id' => 409928, 'region_id' => 782495, 'country_code' => 'SE', 'name' => 'Österåker', 'active' => 1, 'slug' => 'osteraker'],
            ['id' => 409929, 'region_id' => 782495, 'country_code' => 'SE', 'name' => 'Vaxholm', 'active' => 1, 'slug' => 'vaxholm'],
            ['id' => 409930, 'region_id' => 782495, 'country_code' => 'SE', 'name' => 'Sigtuna', 'active' => 1, 'slug' => 'sigtuna'],
            ['id' => 409931, 'region_id' => 782495, 'country_code' => 'SE', 'name' => 'Ekerö', 'active' => 1, 'slug' => 'ekero'],
            ['id' => 409932, 'region_id' => 782495, 'country_code' => 'SE', 'name' => 'Salem', 'active' => 1, 'slug' => 'salem'],
            ['id' => 409933, 'region_id' => 782495, 'country_code' => 'SE', 'name' => 'Nynäshamn', 'active' => 1, 'slug' => 'nynashamn'],
            ['id' => 409934, 'region_id' => 782495, 'country_code' => 'SE', 'name' => 'Norrtälje', 'active' => 1, 'slug' => 'norrtalje'],
            ['id' => 409935, 'region_id' => 782495, 'country_code' => 'SE', 'name' => 'Vallentuna', 'active' => 1, 'slug' => 'vallentuna'],
            ['id' => 409936, 'region_id' => 782495, 'country_code' => 'SE', 'name' => 'Sundbyberg', 'active' => 1, 'slug' => 'sundbyberg'],
            ['id' => 409937, 'region_id' => 782495, 'country_code' => 'SE', 'name' => 'Upplands Väsby', 'active' => 1, 'slug' => 'upplands-vasby'],
            ['id' => 409938, 'region_id' => 782495, 'country_code' => 'SE', 'name' => 'Lidingö', 'active' => 1, 'slug' => 'lidingo'],
            ['id' => 409939, 'region_id' => 782495, 'country_code' => 'SE', 'name' => 'Sollentuna', 'active' => 1, 'slug' => 'sollentuna'],
            ['id' => 409940, 'region_id' => 782495, 'country_code' => 'SE', 'name' => 'Södertälje', 'active' => 1, 'slug' => 'sodertalje'],
            ['id' => 409941, 'region_id' => 782495, 'country_code' => 'SE', 'name' => 'Solna', 'active' => 1, 'slug' => 'solna'],
            ['id' => 409942, 'region_id' => 782495, 'country_code' => 'SE', 'name' => 'Haninge', 'active' => 1, 'slug' => 'haninge'],
            ['id' => 409943, 'region_id' => 782495, 'country_code' => 'SE', 'name' => 'Huddinge', 'active' => 1, 'slug' => 'huddinge'],
            ['id' => 409944, 'region_id' => 782495, 'country_code' => 'SE', 'name' => 'Kista', 'active' => 1, 'slug' => 'kista'],
            ['id' => 409945, 'region_id' => 782496, 'country_code' => 'SE', 'name' => 'Håbo', 'active' => 1, 'slug' => 'habo'],
            ['id' => 409946, 'region_id' => 782496, 'country_code' => 'SE', 'name' => 'Uppsala', 'active' => 1, 'slug' => 'uppsala'],
            ['id' => 409947, 'region_id' => 782496, 'country_code' => 'SE', 'name' => 'Älvkarleby', 'active' => 1, 'slug' => 'alvkarleby'],
            ['id' => 409948, 'region_id' => 782496, 'country_code' => 'SE', 'name' => 'Östhammar', 'active' => 1, 'slug' => 'osthammar'],
            ['id' => 409949, 'region_id' => 782496, 'country_code' => 'SE', 'name' => 'Tierp', 'active' => 1, 'slug' => 'tierp'],
            ['id' => 409950, 'region_id' => 782496, 'country_code' => 'SE', 'name' => 'Knivsta', 'active' => 1, 'slug' => 'knivsta'],
            ['id' => 409951, 'region_id' => 782496, 'country_code' => 'SE', 'name' => 'Enköping', 'active' => 1, 'slug' => 'enkoping'],
            ['id' => 409952, 'region_id' => 782497, 'country_code' => 'SE', 'name' => 'Hammarö', 'active' => 1, 'slug' => 'hammaro'],
            ['id' => 409953, 'region_id' => 782497, 'country_code' => 'SE', 'name' => 'Kil', 'active' => 1, 'slug' => 'kil'],
            ['id' => 409954, 'region_id' => 782497, 'country_code' => 'SE', 'name' => 'Kristineholm', 'active' => 1, 'slug' => 'kristineholm'],
            ['id' => 409955, 'region_id' => 782497, 'country_code' => 'SE', 'name' => 'Torsby', 'active' => 1, 'slug' => 'torsby'],
            ['id' => 409956, 'region_id' => 782497, 'country_code' => 'SE', 'name' => 'Eda', 'active' => 1, 'slug' => 'eda'],
            ['id' => 409957, 'region_id' => 782497, 'country_code' => 'SE', 'name' => 'Storfors', 'active' => 1, 'slug' => 'storfors'],
            ['id' => 409958, 'region_id' => 782497, 'country_code' => 'SE', 'name' => 'Årjäng', 'active' => 1, 'slug' => 'arjang'],
            ['id' => 409959, 'region_id' => 782497, 'country_code' => 'SE', 'name' => 'Munkfors', 'active' => 1, 'slug' => 'munkfors'],
            ['id' => 409960, 'region_id' => 782497, 'country_code' => 'SE', 'name' => 'Sunne', 'active' => 1, 'slug' => 'sunne'],
            ['id' => 409961, 'region_id' => 782497, 'country_code' => 'SE', 'name' => 'Grums', 'active' => 1, 'slug' => 'grums'],
            ['id' => 409962, 'region_id' => 782497, 'country_code' => 'SE', 'name' => 'Hagfors', 'active' => 1, 'slug' => 'hagfors'],
            ['id' => 409963, 'region_id' => 782497, 'country_code' => 'SE', 'name' => 'Filipstad', 'active' => 1, 'slug' => 'filipstad'],
            ['id' => 409964, 'region_id' => 782497, 'country_code' => 'SE', 'name' => 'Forshaga', 'active' => 1, 'slug' => 'forshaga'],
            ['id' => 409965, 'region_id' => 782497, 'country_code' => 'SE', 'name' => 'Säffle', 'active' => 1, 'slug' => 'saffle'],
            ['id' => 409966, 'region_id' => 782497, 'country_code' => 'SE', 'name' => 'Arvika', 'active' => 1, 'slug' => 'arvika'],
            ['id' => 409967, 'region_id' => 782497, 'country_code' => 'SE', 'name' => 'Karlstad', 'active' => 1, 'slug' => 'karlstad'],
            ['id' => 409968, 'region_id' => 782498, 'country_code' => 'SE', 'name' => 'Norsjö', 'active' => 1, 'slug' => 'norsjo'],
            ['id' => 409969, 'region_id' => 782498, 'country_code' => 'SE', 'name' => 'Malå', 'active' => 1, 'slug' => 'mala'],
            ['id' => 409970, 'region_id' => 782498, 'country_code' => 'SE', 'name' => 'Bjurholm', 'active' => 1, 'slug' => 'bjurholm'],
            ['id' => 409971, 'region_id' => 782498, 'country_code' => 'SE', 'name' => 'Sorsele', 'active' => 1, 'slug' => 'sorsele'],
            ['id' => 409972, 'region_id' => 782498, 'country_code' => 'SE', 'name' => 'Dorotea', 'active' => 1, 'slug' => 'dorotea'],
            ['id' => 409973, 'region_id' => 782498, 'country_code' => 'SE', 'name' => 'Åsele', 'active' => 1, 'slug' => 'asele'],
            ['id' => 409974, 'region_id' => 782498, 'country_code' => 'SE', 'name' => 'Robertsfors', 'active' => 1, 'slug' => 'robertsfors'],
            ['id' => 409975, 'region_id' => 782498, 'country_code' => 'SE', 'name' => 'Storuman', 'active' => 1, 'slug' => 'storuman'],
            ['id' => 409976, 'region_id' => 782498, 'country_code' => 'SE', 'name' => 'Vindeln', 'active' => 1, 'slug' => 'vindeln'],
            ['id' => 409977, 'region_id' => 782498, 'country_code' => 'SE', 'name' => 'Nordmaling', 'active' => 1, 'slug' => 'nordmaling'],
            ['id' => 409978, 'region_id' => 782498, 'country_code' => 'SE', 'name' => 'Vilhelmina', 'active' => 1, 'slug' => 'vilhelmina'],
            ['id' => 409979, 'region_id' => 782498, 'country_code' => 'SE', 'name' => 'Vännäs', 'active' => 1, 'slug' => 'vannas'],
            ['id' => 409980, 'region_id' => 782498, 'country_code' => 'SE', 'name' => 'Lycksele', 'active' => 1, 'slug' => 'lycksele'],
            ['id' => 409981, 'region_id' => 782498, 'country_code' => 'SE', 'name' => 'Skellefteå', 'active' => 1, 'slug' => 'skelleftea'],
            ['id' => 409982, 'region_id' => 782498, 'country_code' => 'SE', 'name' => 'Umeå', 'active' => 1, 'slug' => 'umea'],
            ['id' => 409983, 'region_id' => 782499, 'country_code' => 'SE', 'name' => 'Ånge', 'active' => 1, 'slug' => 'ange'],
            ['id' => 409984, 'region_id' => 782499, 'country_code' => 'SE', 'name' => 'Kramfors', 'active' => 1, 'slug' => 'kramfors'],
            ['id' => 409985, 'region_id' => 782499, 'country_code' => 'SE', 'name' => 'Sollefteå', 'active' => 1, 'slug' => 'solleftea'],
            ['id' => 409986, 'region_id' => 782499, 'country_code' => 'SE', 'name' => 'Timrå', 'active' => 1, 'slug' => 'timra'],
            ['id' => 409987, 'region_id' => 782499, 'country_code' => 'SE', 'name' => 'Härnösand', 'active' => 1, 'slug' => 'harnosand'],
            ['id' => 409988, 'region_id' => 782499, 'country_code' => 'SE', 'name' => 'Örnsköldsvik', 'active' => 1, 'slug' => 'ornskoldsvik'],
            ['id' => 409989, 'region_id' => 782499, 'country_code' => 'SE', 'name' => 'Sundsvall', 'active' => 1, 'slug' => 'sundsvall'],
            ['id' => 409990, 'region_id' => 782500, 'country_code' => 'SE', 'name' => 'Heby', 'active' => 1, 'slug' => 'heby'],
            ['id' => 409991, 'region_id' => 782500, 'country_code' => 'SE', 'name' => 'Köping', 'active' => 1, 'slug' => 'koping'],
            ['id' => 409992, 'region_id' => 782500, 'country_code' => 'SE', 'name' => 'Skinnskatteberg', 'active' => 1, 'slug' => 'skinnskatteberg'],
            ['id' => 409993, 'region_id' => 782500, 'country_code' => 'SE', 'name' => 'Norberg', 'active' => 1, 'slug' => 'norberg'],
            ['id' => 409994, 'region_id' => 782500, 'country_code' => 'SE', 'name' => 'Kungsör', 'active' => 1, 'slug' => 'kungsor'],
            ['id' => 409995, 'region_id' => 782500, 'country_code' => 'SE', 'name' => 'Surahammar', 'active' => 1, 'slug' => 'surahammar'],
            ['id' => 409996, 'region_id' => 782500, 'country_code' => 'SE', 'name' => 'Hallstahammar', 'active' => 1, 'slug' => 'hallstahammar'],
            ['id' => 409997, 'region_id' => 782500, 'country_code' => 'SE', 'name' => 'Arboga', 'active' => 1, 'slug' => 'arboga'],
            ['id' => 409998, 'region_id' => 782500, 'country_code' => 'SE', 'name' => 'Fagersta', 'active' => 1, 'slug' => 'fagersta'],
            ['id' => 409999, 'region_id' => 782500, 'country_code' => 'SE', 'name' => 'Sala', 'active' => 1, 'slug' => 'sala'],
            ['id' => 410000, 'region_id' => 782500, 'country_code' => 'SE', 'name' => 'Västerås', 'active' => 1, 'slug' => 'vasteras'],
            ['id' => 410001, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Dals-Ed', 'active' => 1, 'slug' => 'dals-ed'],
            ['id' => 410002, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Karlsborg', 'active' => 1, 'slug' => 'karlsborg'],
            ['id' => 410003, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Mark', 'active' => 1, 'slug' => 'mark'],
            ['id' => 410004, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Orust', 'active' => 1, 'slug' => 'orust'],
            ['id' => 410005, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Skara', 'active' => 1, 'slug' => 'skara'],
            ['id' => 410006, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Sotenäs', 'active' => 1, 'slug' => 'sotenas'],
            ['id' => 410007, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Stegungsund', 'active' => 1, 'slug' => 'stegungsund'],
            ['id' => 410008, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Tanum', 'active' => 1, 'slug' => 'tanum'],
            ['id' => 410009, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Tjörn', 'active' => 1, 'slug' => 'tjorn'],
            ['id' => 410010, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Essunga', 'active' => 1, 'slug' => 'essunga'],
            ['id' => 410011, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Härryda', 'active' => 1, 'slug' => 'harryda'],
            ['id' => 410012, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Gullspång', 'active' => 1, 'slug' => 'gullspang'],
            ['id' => 410013, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Färgelanda', 'active' => 1, 'slug' => 'fargelanda'],
            ['id' => 410014, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Grästorp', 'active' => 1, 'slug' => 'grastorp'],
            ['id' => 410015, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Tranemo', 'active' => 1, 'slug' => 'tranemo'],
            ['id' => 410016, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Öckerö', 'active' => 1, 'slug' => 'ockero'],
            ['id' => 410017, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Svenljunga', 'active' => 1, 'slug' => 'svenljunga'],
            ['id' => 410018, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Munkedal', 'active' => 1, 'slug' => 'munkedal'],
            ['id' => 410019, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Herrljunga', 'active' => 1, 'slug' => 'herrljunga'],
            ['id' => 410020, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Vara', 'active' => 1, 'slug' => 'vara'],
            ['id' => 410021, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Mellerud', 'active' => 1, 'slug' => 'mellerud'],
            ['id' => 410022, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Töreboda', 'active' => 1, 'slug' => 'toreboda'],
            ['id' => 410023, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Götene', 'active' => 1, 'slug' => 'gotene'],
            ['id' => 410024, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Lilla Edet', 'active' => 1, 'slug' => 'lilla-edet'],
            ['id' => 410025, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Vårgårda', 'active' => 1, 'slug' => 'vargarda'],
            ['id' => 410026, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Hjo', 'active' => 1, 'slug' => 'hjo'],
            ['id' => 410027, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Strömstad', 'active' => 1, 'slug' => 'stromstad'],
            ['id' => 410028, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Lysekil', 'active' => 1, 'slug' => 'lysekil'],
            ['id' => 410029, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Tidaholm', 'active' => 1, 'slug' => 'tidaholm'],
            ['id' => 410030, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Tibro', 'active' => 1, 'slug' => 'tibro'],
            ['id' => 410031, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Ulricehamn', 'active' => 1, 'slug' => 'ulricehamn'],
            ['id' => 410032, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Åmål', 'active' => 1, 'slug' => 'amal'],
            ['id' => 410033, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Mariestad', 'active' => 1, 'slug' => 'mariestad'],
            ['id' => 410034, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Falköping', 'active' => 1, 'slug' => 'falkoping'],
            ['id' => 410035, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Lerum', 'active' => 1, 'slug' => 'lerum'],
            ['id' => 410036, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Kungälv', 'active' => 1, 'slug' => 'kungalv'],
            ['id' => 410037, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Vänersborg', 'active' => 1, 'slug' => 'vanersborg'],
            ['id' => 410038, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Lidköping', 'active' => 1, 'slug' => 'lidkoping'],
            ['id' => 410039, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Partille', 'active' => 1, 'slug' => 'partille'],
            ['id' => 410040, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Uddevalla', 'active' => 1, 'slug' => 'uddevalla'],
            ['id' => 410041, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Skövde', 'active' => 1, 'slug' => 'skovde'],
            ['id' => 410042, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Trollhättan', 'active' => 1, 'slug' => 'trollhattan'],
            ['id' => 410043, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Mölndal', 'active' => 1, 'slug' => 'molndal'],
            ['id' => 410044, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Borås', 'active' => 1, 'slug' => 'boras'],
            ['id' => 410045, 'region_id' => 782501, 'country_code' => 'SE', 'name' => 'Göteborg', 'active' => 1, 'slug' => 'goteborg']
    	];
    }
}
