<?php

namespace Gerardojbaez\GeoData\Seeders;

use Illuminate\Database\Seeder;
use Gerardojbaez\GeoData\Models\Country;
use Gerardojbaez\GeoData\Models\Region;
use Gerardojbaez\GeoData\Models\City;

class UruguaySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Country::create($this->country());
        Region::insert($this->regions());

        if ($this->cities() > 4000)
        {
            foreach (array_chunk($this->cities(), 3500) as $chunk)
                City::insert($chunk);
        }
        else
        {
            City::insert($this->cities());
        }
    }

        /**
     * Get country.
     *
     * @return array
     */
    public function country()
    {
    	return ['code' => 'UY', 'name' => 'Uruguay', 'slug' => 'uruguay'];
    }

    /**
     * Get country regions.
     *
     * @return array
     */
    public function regions()
    {
    	return [
            ['id' => 867, 'country_code' => 'UY', 'name' => 'Montevideo', 'active' => 1, 'slug' => 'montevideo'],
            ['id' => 707596, 'country_code' => 'UY', 'name' => 'Artigas', 'active' => 1, 'slug' => 'artigas'],
            ['id' => 707612, 'country_code' => 'UY', 'name' => 'Canelones', 'active' => 1, 'slug' => 'canelones'],
            ['id' => 707686, 'country_code' => 'UY', 'name' => 'Cerro Largo', 'active' => 1, 'slug' => 'cerro-largo'],
            ['id' => 707697, 'country_code' => 'UY', 'name' => 'Colonia', 'active' => 1, 'slug' => 'colonia'],
            ['id' => 707721, 'country_code' => 'UY', 'name' => 'Durazno', 'active' => 1, 'slug' => 'durazno'],
            ['id' => 707730, 'country_code' => 'UY', 'name' => 'Flores', 'active' => 1, 'slug' => 'flores'],
            ['id' => 707735, 'country_code' => 'UY', 'name' => 'Florida', 'active' => 1, 'slug' => 'florida'],
            ['id' => 707756, 'country_code' => 'UY', 'name' => 'Lavalleja', 'active' => 1, 'slug' => 'lavalleja'],
            ['id' => 707771, 'country_code' => 'UY', 'name' => 'Maldonado', 'active' => 1, 'slug' => 'maldonado'],
            ['id' => 707826, 'country_code' => 'UY', 'name' => 'Paysandú', 'active' => 1, 'slug' => 'paysandu'],
            ['id' => 707842, 'country_code' => 'UY', 'name' => 'Río Negro', 'active' => 1, 'slug' => 'rio-negro'],
            ['id' => 707853, 'country_code' => 'UY', 'name' => 'Rivera', 'active' => 1, 'slug' => 'rivera'],
            ['id' => 707860, 'country_code' => 'UY', 'name' => 'Rocha', 'active' => 1, 'slug' => 'rocha'],
            ['id' => 707878, 'country_code' => 'UY', 'name' => 'Salto', 'active' => 1, 'slug' => 'salto'],
            ['id' => 707890, 'country_code' => 'UY', 'name' => 'San José', 'active' => 1, 'slug' => 'san-jose'],
            ['id' => 707907, 'country_code' => 'UY', 'name' => 'Soriano', 'active' => 1, 'slug' => 'soriano'],
            ['id' => 707923, 'country_code' => 'UY', 'name' => 'Tacuarembó', 'active' => 1, 'slug' => 'tacuarembo'],
            ['id' => 707941, 'country_code' => 'UY', 'name' => 'Treinta y Tres', 'active' => 1, 'slug' => 'treinta-y-tres']
    	];
    }

    /**
     * Get region cities.
     *
     * @return array
     */
    public function cities()
    {
    	return [
            ['id' => 23331, 'region_id' => 867, 'country_code' => 'UY', 'name' => 'Aguada', 'active' => 1, 'slug' => 'aguada'],
            ['id' => 23332, 'region_id' => 867, 'country_code' => 'UY', 'name' => 'Aires Puros', 'active' => 1, 'slug' => 'aires-puros'],
            ['id' => 23333, 'region_id' => 867, 'country_code' => 'UY', 'name' => 'Bella Vista', 'active' => 1, 'slug' => 'bella-vista'],
            ['id' => 23334, 'region_id' => 867, 'country_code' => 'UY', 'name' => 'Belvedere', 'active' => 1, 'slug' => 'belvedere'],
            ['id' => 23335, 'region_id' => 867, 'country_code' => 'UY', 'name' => 'Buceo', 'active' => 1, 'slug' => 'buceo'],
            ['id' => 23336, 'region_id' => 867, 'country_code' => 'UY', 'name' => 'Capurro', 'active' => 1, 'slug' => 'capurro'],
            ['id' => 23337, 'region_id' => 867, 'country_code' => 'UY', 'name' => 'Carrasco', 'active' => 1, 'slug' => 'carrasco'],
            ['id' => 23338, 'region_id' => 867, 'country_code' => 'UY', 'name' => 'Centro', 'active' => 1, 'slug' => 'centro'],
            ['id' => 23339, 'region_id' => 867, 'country_code' => 'UY', 'name' => 'Cerro', 'active' => 1, 'slug' => 'cerro'],
            ['id' => 23340, 'region_id' => 867, 'country_code' => 'UY', 'name' => 'Ciudad Vieja', 'active' => 1, 'slug' => 'ciudad-vieja'],
            ['id' => 23341, 'region_id' => 867, 'country_code' => 'UY', 'name' => 'Colón', 'active' => 1, 'slug' => 'colon'],
            ['id' => 23342, 'region_id' => 867, 'country_code' => 'UY', 'name' => 'Cordón', 'active' => 1, 'slug' => 'cordon'],
            ['id' => 23343, 'region_id' => 867, 'country_code' => 'UY', 'name' => 'Goes', 'active' => 1, 'slug' => 'goes'],
            ['id' => 23344, 'region_id' => 867, 'country_code' => 'UY', 'name' => 'La Blanqueada', 'active' => 1, 'slug' => 'la-blanqueada'],
            ['id' => 23345, 'region_id' => 867, 'country_code' => 'UY', 'name' => 'La Comercial', 'active' => 1, 'slug' => 'la-comercial'],
            ['id' => 23346, 'region_id' => 867, 'country_code' => 'UY', 'name' => 'La Cruz', 'active' => 1, 'slug' => 'la-cruz'],
            ['id' => 23347, 'region_id' => 867, 'country_code' => 'UY', 'name' => 'La Teja', 'active' => 1, 'slug' => 'la-teja'],
            ['id' => 23348, 'region_id' => 867, 'country_code' => 'UY', 'name' => 'Lezica', 'active' => 1, 'slug' => 'lezica'],
            ['id' => 23349, 'region_id' => 867, 'country_code' => 'UY', 'name' => 'Malvín', 'active' => 1, 'slug' => 'malvin'],
            ['id' => 23350, 'region_id' => 867, 'country_code' => 'UY', 'name' => 'Maroñas', 'active' => 1, 'slug' => 'maronas'],
            ['id' => 23351, 'region_id' => 867, 'country_code' => 'UY', 'name' => 'Nuevo París', 'active' => 1, 'slug' => 'nuevo-paris'],
            ['id' => 23352, 'region_id' => 867, 'country_code' => 'UY', 'name' => 'Palermo', 'active' => 1, 'slug' => 'palermo'],
            ['id' => 23353, 'region_id' => 867, 'country_code' => 'UY', 'name' => 'Parque Battle', 'active' => 1, 'slug' => 'parque-battle'],
            ['id' => 23354, 'region_id' => 867, 'country_code' => 'UY', 'name' => 'Parque Rodó', 'active' => 1, 'slug' => 'parque-rodo'],
            ['id' => 23355, 'region_id' => 867, 'country_code' => 'UY', 'name' => 'Paso de la Arena', 'active' => 1, 'slug' => 'paso-de-la-arena'],
            ['id' => 23356, 'region_id' => 867, 'country_code' => 'UY', 'name' => 'Paso Molino', 'active' => 1, 'slug' => 'paso-molino'],
            ['id' => 23357, 'region_id' => 867, 'country_code' => 'UY', 'name' => 'Peñarol', 'active' => 1, 'slug' => 'penarol'],
            ['id' => 23358, 'region_id' => 867, 'country_code' => 'UY', 'name' => 'Piedras Blancas', 'active' => 1, 'slug' => 'piedras-blancas'],
            ['id' => 23359, 'region_id' => 867, 'country_code' => 'UY', 'name' => 'Pocitos', 'active' => 1, 'slug' => 'pocitos'],
            ['id' => 23360, 'region_id' => 867, 'country_code' => 'UY', 'name' => 'Prado', 'active' => 1, 'slug' => 'prado'],
            ['id' => 23361, 'region_id' => 867, 'country_code' => 'UY', 'name' => 'Punta Carretas', 'active' => 1, 'slug' => 'punta-carretas'],
            ['id' => 23362, 'region_id' => 867, 'country_code' => 'UY', 'name' => 'Punta Gorda', 'active' => 1, 'slug' => 'punta-gorda'],
            ['id' => 23363, 'region_id' => 867, 'country_code' => 'UY', 'name' => 'Reducto', 'active' => 1, 'slug' => 'reducto'],
            ['id' => 23364, 'region_id' => 867, 'country_code' => 'UY', 'name' => 'Sayago', 'active' => 1, 'slug' => 'sayago'],
            ['id' => 23365, 'region_id' => 867, 'country_code' => 'UY', 'name' => 'Sur', 'active' => 1, 'slug' => 'sur'],
            ['id' => 23366, 'region_id' => 867, 'country_code' => 'UY', 'name' => 'Tres Cruces', 'active' => 1, 'slug' => 'tres-cruces'],
            ['id' => 23367, 'region_id' => 867, 'country_code' => 'UY', 'name' => 'Unión', 'active' => 1, 'slug' => 'union'],
            ['id' => 23148, 'region_id' => 707596, 'country_code' => 'UY', 'name' => 'Artigas', 'active' => 1, 'slug' => 'artigas'],
            ['id' => 23149, 'region_id' => 707596, 'country_code' => 'UY', 'name' => 'Baltasar Brum', 'active' => 1, 'slug' => 'baltasar-brum'],
            ['id' => 23150, 'region_id' => 707596, 'country_code' => 'UY', 'name' => 'Bella Unión', 'active' => 1, 'slug' => 'bella-union'],
            ['id' => 23151, 'region_id' => 707596, 'country_code' => 'UY', 'name' => 'Bernabe Rivera', 'active' => 1, 'slug' => 'bernabe-rivera'],
            ['id' => 23152, 'region_id' => 707596, 'country_code' => 'UY', 'name' => 'Calpica Itacumbú', 'active' => 1, 'slug' => 'calpica-itacumbu'],
            ['id' => 23153, 'region_id' => 707596, 'country_code' => 'UY', 'name' => 'Catalán Grande', 'active' => 1, 'slug' => 'catalan-grande'],
            ['id' => 23154, 'region_id' => 707596, 'country_code' => 'UY', 'name' => 'Cerro Amarillo', 'active' => 1, 'slug' => 'cerro-amarillo'],
            ['id' => 23155, 'region_id' => 707596, 'country_code' => 'UY', 'name' => 'Colonia Palma', 'active' => 1, 'slug' => 'colonia-palma'],
            ['id' => 23156, 'region_id' => 707596, 'country_code' => 'UY', 'name' => 'Cuaró', 'active' => 1, 'slug' => 'cuaro'],
            ['id' => 23157, 'region_id' => 707596, 'country_code' => 'UY', 'name' => 'Javier de Viana', 'active' => 1, 'slug' => 'javier-de-viana'],
            ['id' => 23158, 'region_id' => 707596, 'country_code' => 'UY', 'name' => 'Paso Campamento', 'active' => 1, 'slug' => 'paso-campamento'],
            ['id' => 23159, 'region_id' => 707596, 'country_code' => 'UY', 'name' => 'Paso Farías', 'active' => 1, 'slug' => 'paso-farias'],
            ['id' => 23160, 'region_id' => 707596, 'country_code' => 'UY', 'name' => 'Pintado Grande', 'active' => 1, 'slug' => 'pintado-grande'],
            ['id' => 23161, 'region_id' => 707596, 'country_code' => 'UY', 'name' => 'Sequeira', 'active' => 1, 'slug' => 'sequeira'],
            ['id' => 23162, 'region_id' => 707596, 'country_code' => 'UY', 'name' => 'Tomas Gomensoro', 'active' => 1, 'slug' => 'tomas-gomensoro'],
            ['id' => 23163, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Aeropuerto', 'active' => 1, 'slug' => 'aeropuerto'],
            ['id' => 23164, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Aguas Corrientes', 'active' => 1, 'slug' => 'aguas-corrientes'],
            ['id' => 23165, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Araminda', 'active' => 1, 'slug' => 'araminda'],
            ['id' => 23166, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Atlántida', 'active' => 1, 'slug' => 'atlantida'],
            ['id' => 23167, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Barra de Carrasco', 'active' => 1, 'slug' => 'barra-de-carrasco'],
            ['id' => 23168, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Barros Blancos', 'active' => 1, 'slug' => 'barros-blancos'],
            ['id' => 23169, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Bello Horizonte', 'active' => 1, 'slug' => 'bello-horizonte'],
            ['id' => 23170, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Biarritz', 'active' => 1, 'slug' => 'biarritz'],
            ['id' => 23171, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Bolívar', 'active' => 1, 'slug' => 'bolivar'],
            ['id' => 23172, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Canelón Grande Represa', 'active' => 1, 'slug' => 'canelon-grande-represa'],
            ['id' => 23173, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Canelones', 'active' => 1, 'slug' => 'canelones'],
            ['id' => 23174, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Castellanos', 'active' => 1, 'slug' => 'castellanos'],
            ['id' => 23175, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Chamizo', 'active' => 1, 'slug' => 'chamizo'],
            ['id' => 23176, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Colonia Nicolich', 'active' => 1, 'slug' => 'colonia-nicolich'],
            ['id' => 23177, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Colonia Treinta y Tres Orientales', 'active' => 1, 'slug' => 'colonia-treinta-y-tres-orientales'],
            ['id' => 23178, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Costa Azul', 'active' => 1, 'slug' => 'costa-azul'],
            ['id' => 23179, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Cuchilla Alta', 'active' => 1, 'slug' => 'cuchilla-alta'],
            ['id' => 23180, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'El Bosque', 'active' => 1, 'slug' => 'el-bosque'],
            ['id' => 23181, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'El Dorado', 'active' => 1, 'slug' => 'el-dorado'],
            ['id' => 23182, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'El Fortín de Santa Rosa', 'active' => 1, 'slug' => 'el-fortin-de-santa-rosa'],
            ['id' => 23183, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'El Pinar', 'active' => 1, 'slug' => 'el-pinar'],
            ['id' => 23184, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Empalme Olmos', 'active' => 1, 'slug' => 'empalme-olmos'],
            ['id' => 23185, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Estación Migues', 'active' => 1, 'slug' => 'estacion-migues'],
            ['id' => 23186, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Estación Pedrera', 'active' => 1, 'slug' => 'estacion-pedrera'],
            ['id' => 23187, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Estación Tapia', 'active' => 1, 'slug' => 'estacion-tapia'],
            ['id' => 23188, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Fray Marcos', 'active' => 1, 'slug' => 'fray-marcos'],
            ['id' => 23189, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Guazuvirá', 'active' => 1, 'slug' => 'guazuvira'],
            ['id' => 23190, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Jaureguiberry', 'active' => 1, 'slug' => 'jaureguiberry'],
            ['id' => 23191, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Joanicó', 'active' => 1, 'slug' => 'joanico'],
            ['id' => 23192, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Joaquín Suárez', 'active' => 1, 'slug' => 'joaquin-suarez'],
            ['id' => 23193, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'La Escobilla', 'active' => 1, 'slug' => 'la-escobilla'],
            ['id' => 23194, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'La Floresta', 'active' => 1, 'slug' => 'la-floresta'],
            ['id' => 23195, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'La Paz', 'active' => 1, 'slug' => 'la-paz'],
            ['id' => 23196, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Lagomar', 'active' => 1, 'slug' => 'lagomar'],
            ['id' => 23197, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Las Piedras', 'active' => 1, 'slug' => 'las-piedras'],
            ['id' => 23198, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Las Toscas', 'active' => 1, 'slug' => 'las-toscas'],
            ['id' => 23199, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Las Vegas', 'active' => 1, 'slug' => 'las-vegas'],
            ['id' => 23200, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Lomas de Solymar', 'active' => 1, 'slug' => 'lomas-de-solymar'],
            ['id' => 23201, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Los Cerrillos', 'active' => 1, 'slug' => 'los-cerrillos'],
            ['id' => 23202, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Los Titanes', 'active' => 1, 'slug' => 'los-titanes'],
            ['id' => 23203, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Marindia', 'active' => 1, 'slug' => 'marindia'],
            ['id' => 23204, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Médanos de Solymar', 'active' => 1, 'slug' => 'medanos-de-solymar'],
            ['id' => 23205, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Migues', 'active' => 1, 'slug' => 'migues'],
            ['id' => 23206, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Montes', 'active' => 1, 'slug' => 'montes'],
            ['id' => 23207, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Neptunia', 'active' => 1, 'slug' => 'neptunia'],
            ['id' => 23208, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Pando', 'active' => 1, 'slug' => 'pando'],
            ['id' => 23209, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Paraje San Juan', 'active' => 1, 'slug' => 'paraje-san-juan'],
            ['id' => 23210, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Parque Carrasco', 'active' => 1, 'slug' => 'parque-carrasco'],
            ['id' => 23211, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Parque Del Plata', 'active' => 1, 'slug' => 'parque-del-plata'],
            ['id' => 23212, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Paso de Carrasco', 'active' => 1, 'slug' => 'paso-de-carrasco'],
            ['id' => 23213, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Paso de Pache', 'active' => 1, 'slug' => 'paso-de-pache'],
            ['id' => 23214, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Paso Del Bote', 'active' => 1, 'slug' => 'paso-del-bote'],
            ['id' => 23215, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Piedras de Afilar', 'active' => 1, 'slug' => 'piedras-de-afilar'],
            ['id' => 23216, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Pinamar', 'active' => 1, 'slug' => 'pinamar'],
            ['id' => 23217, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Progreso', 'active' => 1, 'slug' => 'progreso'],
            ['id' => 23218, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Salinas', 'active' => 1, 'slug' => 'salinas'],
            ['id' => 23219, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'San Antonio', 'active' => 1, 'slug' => 'san-antonio'],
            ['id' => 23220, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'San Bautista', 'active' => 1, 'slug' => 'san-bautista'],
            ['id' => 23221, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'San Jacinto', 'active' => 1, 'slug' => 'san-jacinto'],
            ['id' => 23222, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'San José de Carrasco', 'active' => 1, 'slug' => 'san-jose-de-carrasco'],
            ['id' => 23223, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'San Luis', 'active' => 1, 'slug' => 'san-luis'],
            ['id' => 23224, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'San Ramón', 'active' => 1, 'slug' => 'san-ramon'],
            ['id' => 23225, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Santa Ana', 'active' => 1, 'slug' => 'santa-ana'],
            ['id' => 23226, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Santa Lucía', 'active' => 1, 'slug' => 'santa-lucia'],
            ['id' => 23227, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Santa Lucía Del Este', 'active' => 1, 'slug' => 'santa-lucia-del-este'],
            ['id' => 23228, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Santa Rosa', 'active' => 1, 'slug' => 'santa-rosa'],
            ['id' => 23229, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Sauce', 'active' => 1, 'slug' => 'sauce'],
            ['id' => 23230, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Shangrila', 'active' => 1, 'slug' => 'shangrila'],
            ['id' => 23231, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Soca', 'active' => 1, 'slug' => 'soca'],
            ['id' => 23232, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Solymar', 'active' => 1, 'slug' => 'solymar'],
            ['id' => 23233, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Tala', 'active' => 1, 'slug' => 'tala'],
            ['id' => 23234, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Toledo', 'active' => 1, 'slug' => 'toledo'],
            ['id' => 23235, 'region_id' => 707612, 'country_code' => 'UY', 'name' => 'Villa Argentina', 'active' => 1, 'slug' => 'villa-argentina'],
            ['id' => 23236, 'region_id' => 707686, 'country_code' => 'UY', 'name' => 'Aceguá', 'active' => 1, 'slug' => 'acegua'],
            ['id' => 23237, 'region_id' => 707686, 'country_code' => 'UY', 'name' => 'Bañado de Medina', 'active' => 1, 'slug' => 'banado-de-medina'],
            ['id' => 23238, 'region_id' => 707686, 'country_code' => 'UY', 'name' => 'Cerro de las Cuentas', 'active' => 1, 'slug' => 'cerro-de-las-cuentas'],
            ['id' => 23239, 'region_id' => 707686, 'country_code' => 'UY', 'name' => 'Cerro Largo', 'active' => 1, 'slug' => 'cerro-largo'],
            ['id' => 23240, 'region_id' => 707686, 'country_code' => 'UY', 'name' => 'Fraile Muerto', 'active' => 1, 'slug' => 'fraile-muerto'],
            ['id' => 23241, 'region_id' => 707686, 'country_code' => 'UY', 'name' => 'Isidoro Noblía', 'active' => 1, 'slug' => 'isidoro-noblia'],
            ['id' => 23242, 'region_id' => 707686, 'country_code' => 'UY', 'name' => 'Melo', 'active' => 1, 'slug' => 'melo'],
            ['id' => 23243, 'region_id' => 707686, 'country_code' => 'UY', 'name' => 'Plácido Rosas', 'active' => 1, 'slug' => 'placido-rosas'],
            ['id' => 23244, 'region_id' => 707686, 'country_code' => 'UY', 'name' => 'Río Branco', 'active' => 1, 'slug' => 'rio-branco'],
            ['id' => 23245, 'region_id' => 707686, 'country_code' => 'UY', 'name' => 'Tupambaé', 'active' => 1, 'slug' => 'tupambae'],
            ['id' => 23246, 'region_id' => 707697, 'country_code' => 'UY', 'name' => 'Agraciada', 'active' => 1, 'slug' => 'agraciada'],
            ['id' => 23247, 'region_id' => 707697, 'country_code' => 'UY', 'name' => 'Barker', 'active' => 1, 'slug' => 'barker'],
            ['id' => 23248, 'region_id' => 707697, 'country_code' => 'UY', 'name' => 'Campana', 'active' => 1, 'slug' => 'campana'],
            ['id' => 23249, 'region_id' => 707697, 'country_code' => 'UY', 'name' => 'Carmelo', 'active' => 1, 'slug' => 'carmelo'],
            ['id' => 23250, 'region_id' => 707697, 'country_code' => 'UY', 'name' => 'Colonia', 'active' => 1, 'slug' => 'colonia'],
            ['id' => 23251, 'region_id' => 707697, 'country_code' => 'UY', 'name' => 'Colonia Valdense', 'active' => 1, 'slug' => 'colonia-valdense'],
            ['id' => 23252, 'region_id' => 707697, 'country_code' => 'UY', 'name' => 'Conchillas', 'active' => 1, 'slug' => 'conchillas'],
            ['id' => 23253, 'region_id' => 707697, 'country_code' => 'UY', 'name' => 'Cufré', 'active' => 1, 'slug' => 'cufre'],
            ['id' => 23254, 'region_id' => 707697, 'country_code' => 'UY', 'name' => 'Florencio Sánchez', 'active' => 1, 'slug' => 'florencio-sanchez'],
            ['id' => 23255, 'region_id' => 707697, 'country_code' => 'UY', 'name' => 'Juan Lacaze', 'active' => 1, 'slug' => 'juan-lacaze'],
            ['id' => 23256, 'region_id' => 707697, 'country_code' => 'UY', 'name' => 'La Estanzuela', 'active' => 1, 'slug' => 'la-estanzuela'],
            ['id' => 23257, 'region_id' => 707697, 'country_code' => 'UY', 'name' => 'La Paz', 'active' => 1, 'slug' => 'la-paz'],
            ['id' => 23258, 'region_id' => 707697, 'country_code' => 'UY', 'name' => 'Los Pinos', 'active' => 1, 'slug' => 'los-pinos'],
            ['id' => 23259, 'region_id' => 707697, 'country_code' => 'UY', 'name' => 'Miguelete', 'active' => 1, 'slug' => 'miguelete'],
            ['id' => 23260, 'region_id' => 707697, 'country_code' => 'UY', 'name' => 'Minuano', 'active' => 1, 'slug' => 'minuano'],
            ['id' => 23261, 'region_id' => 707697, 'country_code' => 'UY', 'name' => 'Nueva Helvecia', 'active' => 1, 'slug' => 'nueva-helvecia'],
            ['id' => 23262, 'region_id' => 707697, 'country_code' => 'UY', 'name' => 'Nueva Palmira', 'active' => 1, 'slug' => 'nueva-palmira'],
            ['id' => 23263, 'region_id' => 707697, 'country_code' => 'UY', 'name' => 'Ombúes de Lavalle', 'active' => 1, 'slug' => 'ombues-de-lavalle'],
            ['id' => 23264, 'region_id' => 707697, 'country_code' => 'UY', 'name' => 'Playa Fomento', 'active' => 1, 'slug' => 'playa-fomento'],
            ['id' => 23265, 'region_id' => 707697, 'country_code' => 'UY', 'name' => 'Riachuelo', 'active' => 1, 'slug' => 'riachuelo'],
            ['id' => 23266, 'region_id' => 707697, 'country_code' => 'UY', 'name' => 'Rosario', 'active' => 1, 'slug' => 'rosario'],
            ['id' => 23267, 'region_id' => 707697, 'country_code' => 'UY', 'name' => 'Santa Ana', 'active' => 1, 'slug' => 'santa-ana'],
            ['id' => 23268, 'region_id' => 707697, 'country_code' => 'UY', 'name' => 'Tarariras', 'active' => 1, 'slug' => 'tarariras'],
            ['id' => 23269, 'region_id' => 707721, 'country_code' => 'UY', 'name' => 'Blanquillo', 'active' => 1, 'slug' => 'blanquillo'],
            ['id' => 23270, 'region_id' => 707721, 'country_code' => 'UY', 'name' => 'Carlos Reyles', 'active' => 1, 'slug' => 'carlos-reyles'],
            ['id' => 23271, 'region_id' => 707721, 'country_code' => 'UY', 'name' => 'Centenario', 'active' => 1, 'slug' => 'centenario'],
            ['id' => 23272, 'region_id' => 707721, 'country_code' => 'UY', 'name' => 'Durazno', 'active' => 1, 'slug' => 'durazno'],
            ['id' => 23273, 'region_id' => 707721, 'country_code' => 'UY', 'name' => 'Feliciano', 'active' => 1, 'slug' => 'feliciano'],
            ['id' => 23274, 'region_id' => 707721, 'country_code' => 'UY', 'name' => 'La Paloma', 'active' => 1, 'slug' => 'la-paloma'],
            ['id' => 23275, 'region_id' => 707721, 'country_code' => 'UY', 'name' => 'Santa Bernardina', 'active' => 1, 'slug' => 'santa-bernardina'],
            ['id' => 23276, 'region_id' => 707721, 'country_code' => 'UY', 'name' => 'Sarandí del Yí', 'active' => 1, 'slug' => 'sarandi-del-yi'],
            ['id' => 23277, 'region_id' => 707730, 'country_code' => 'UY', 'name' => 'Andresito', 'active' => 1, 'slug' => 'andresito'],
            ['id' => 23278, 'region_id' => 707730, 'country_code' => 'UY', 'name' => 'Flores', 'active' => 1, 'slug' => 'flores'],
            ['id' => 23279, 'region_id' => 707730, 'country_code' => 'UY', 'name' => 'Ismael Cortinas', 'active' => 1, 'slug' => 'ismael-cortinas'],
            ['id' => 23280, 'region_id' => 707730, 'country_code' => 'UY', 'name' => 'Trinidad', 'active' => 1, 'slug' => 'trinidad'],
            ['id' => 23281, 'region_id' => 707735, 'country_code' => 'UY', 'name' => '25 de Agosto', 'active' => 1, 'slug' => '25-de-agosto'],
            ['id' => 23282, 'region_id' => 707735, 'country_code' => 'UY', 'name' => '25 de Mayo', 'active' => 1, 'slug' => '25-de-mayo'],
            ['id' => 23283, 'region_id' => 707735, 'country_code' => 'UY', 'name' => 'Capilla Del Sauce', 'active' => 1, 'slug' => 'capilla-del-sauce'],
            ['id' => 23284, 'region_id' => 707735, 'country_code' => 'UY', 'name' => 'Cardal', 'active' => 1, 'slug' => 'cardal'],
            ['id' => 23285, 'region_id' => 707735, 'country_code' => 'UY', 'name' => 'Casupá', 'active' => 1, 'slug' => 'casupa'],
            ['id' => 23286, 'region_id' => 707735, 'country_code' => 'UY', 'name' => 'Cerro Colorado', 'active' => 1, 'slug' => 'cerro-colorado'],
            ['id' => 23287, 'region_id' => 707735, 'country_code' => 'UY', 'name' => 'Chamizo', 'active' => 1, 'slug' => 'chamizo'],
            ['id' => 23288, 'region_id' => 707735, 'country_code' => 'UY', 'name' => 'Florida', 'active' => 1, 'slug' => 'florida'],
            ['id' => 23289, 'region_id' => 707735, 'country_code' => 'UY', 'name' => 'Fray Marcos', 'active' => 1, 'slug' => 'fray-marcos'],
            ['id' => 23290, 'region_id' => 707735, 'country_code' => 'UY', 'name' => 'Goñi', 'active' => 1, 'slug' => 'goni'],
            ['id' => 23291, 'region_id' => 707735, 'country_code' => 'UY', 'name' => 'Independencia', 'active' => 1, 'slug' => 'independencia'],
            ['id' => 23292, 'region_id' => 707735, 'country_code' => 'UY', 'name' => 'La Cruz', 'active' => 1, 'slug' => 'la-cruz'],
            ['id' => 23293, 'region_id' => 707735, 'country_code' => 'UY', 'name' => 'Mendoza Chico', 'active' => 1, 'slug' => 'mendoza-chico'],
            ['id' => 23294, 'region_id' => 707735, 'country_code' => 'UY', 'name' => 'Mendoza Grande', 'active' => 1, 'slug' => 'mendoza-grande'],
            ['id' => 23295, 'region_id' => 707735, 'country_code' => 'UY', 'name' => 'Monte Coral', 'active' => 1, 'slug' => 'monte-coral'],
            ['id' => 23296, 'region_id' => 707735, 'country_code' => 'UY', 'name' => 'Pintado', 'active' => 1, 'slug' => 'pintado'],
            ['id' => 23297, 'region_id' => 707735, 'country_code' => 'UY', 'name' => 'Polanco del Yí', 'active' => 1, 'slug' => 'polanco-del-yi'],
            ['id' => 23298, 'region_id' => 707735, 'country_code' => 'UY', 'name' => 'Puntas de Maciel', 'active' => 1, 'slug' => 'puntas-de-maciel'],
            ['id' => 23299, 'region_id' => 707735, 'country_code' => 'UY', 'name' => 'Reboledo', 'active' => 1, 'slug' => 'reboledo'],
            ['id' => 23300, 'region_id' => 707735, 'country_code' => 'UY', 'name' => 'Sarandí Grande', 'active' => 1, 'slug' => 'sarandi-grande'],
            ['id' => 23301, 'region_id' => 707756, 'country_code' => 'UY', 'name' => 'Colon', 'active' => 1, 'slug' => 'colon'],
            ['id' => 23302, 'region_id' => 707756, 'country_code' => 'UY', 'name' => 'Estación Solís', 'active' => 1, 'slug' => 'estacion-solis'],
            ['id' => 23303, 'region_id' => 707756, 'country_code' => 'UY', 'name' => 'Illescas', 'active' => 1, 'slug' => 'illescas'],
            ['id' => 23304, 'region_id' => 707756, 'country_code' => 'UY', 'name' => 'Jose Batlle y Ordoñez', 'active' => 1, 'slug' => 'jose-batlle-y-ordonez'],
            ['id' => 23305, 'region_id' => 707756, 'country_code' => 'UY', 'name' => 'Jose Pedro Varela', 'active' => 1, 'slug' => 'jose-pedro-varela'],
            ['id' => 23306, 'region_id' => 707756, 'country_code' => 'UY', 'name' => 'Lavalleja', 'active' => 1, 'slug' => 'lavalleja'],
            ['id' => 23307, 'region_id' => 707756, 'country_code' => 'UY', 'name' => 'Mariscala', 'active' => 1, 'slug' => 'mariscala'],
            ['id' => 23308, 'region_id' => 707756, 'country_code' => 'UY', 'name' => 'Minas', 'active' => 1, 'slug' => 'minas'],
            ['id' => 23309, 'region_id' => 707756, 'country_code' => 'UY', 'name' => 'Nico Pérez', 'active' => 1, 'slug' => 'nico-perez'],
            ['id' => 23310, 'region_id' => 707756, 'country_code' => 'UY', 'name' => 'Piraraja', 'active' => 1, 'slug' => 'piraraja'],
            ['id' => 23311, 'region_id' => 707756, 'country_code' => 'UY', 'name' => 'Polanco Norte', 'active' => 1, 'slug' => 'polanco-norte'],
            ['id' => 23312, 'region_id' => 707756, 'country_code' => 'UY', 'name' => 'Solis de Mataojo', 'active' => 1, 'slug' => 'solis-de-mataojo'],
            ['id' => 23313, 'region_id' => 707756, 'country_code' => 'UY', 'name' => 'Valentines', 'active' => 1, 'slug' => 'valentines'],
            ['id' => 23314, 'region_id' => 707756, 'country_code' => 'UY', 'name' => 'Zapican', 'active' => 1, 'slug' => 'zapican'],
            ['id' => 23315, 'region_id' => 707771, 'country_code' => 'UY', 'name' => 'Aiguá', 'active' => 1, 'slug' => 'aigua'],
            ['id' => 23316, 'region_id' => 707771, 'country_code' => 'UY', 'name' => 'Garzón', 'active' => 1, 'slug' => 'garzon'],
            ['id' => 23317, 'region_id' => 707771, 'country_code' => 'UY', 'name' => 'La Barra', 'active' => 1, 'slug' => 'la-barra'],
            ['id' => 23318, 'region_id' => 707771, 'country_code' => 'UY', 'name' => 'Las Flores', 'active' => 1, 'slug' => 'las-flores'],
            ['id' => 23319, 'region_id' => 707771, 'country_code' => 'UY', 'name' => 'Maldonado', 'active' => 1, 'slug' => 'maldonado'],
            ['id' => 23320, 'region_id' => 707771, 'country_code' => 'UY', 'name' => 'Manantiales', 'active' => 1, 'slug' => 'manantiales'],
            ['id' => 23321, 'region_id' => 707771, 'country_code' => 'UY', 'name' => 'Pan de Azúcar', 'active' => 1, 'slug' => 'pan-de-azucar'],
            ['id' => 23322, 'region_id' => 707771, 'country_code' => 'UY', 'name' => 'Pinares', 'active' => 1, 'slug' => 'pinares'],
            ['id' => 23323, 'region_id' => 707771, 'country_code' => 'UY', 'name' => 'Piriápolis', 'active' => 1, 'slug' => 'piriapolis'],
            ['id' => 23324, 'region_id' => 707771, 'country_code' => 'UY', 'name' => 'Playa Verde', 'active' => 1, 'slug' => 'playa-verde'],
            ['id' => 23325, 'region_id' => 707771, 'country_code' => 'UY', 'name' => 'Punta Ballena', 'active' => 1, 'slug' => 'punta-ballena'],
            ['id' => 23326, 'region_id' => 707771, 'country_code' => 'UY', 'name' => 'Punta Del Este', 'active' => 1, 'slug' => 'punta-del-este'],
            ['id' => 23327, 'region_id' => 707771, 'country_code' => 'UY', 'name' => 'San Carlos', 'active' => 1, 'slug' => 'san-carlos'],
            ['id' => 23328, 'region_id' => 707771, 'country_code' => 'UY', 'name' => 'San Rafael', 'active' => 1, 'slug' => 'san-rafael'],
            ['id' => 23329, 'region_id' => 707771, 'country_code' => 'UY', 'name' => 'Sauce de Portezuelo', 'active' => 1, 'slug' => 'sauce-de-portezuelo'],
            ['id' => 23330, 'region_id' => 707771, 'country_code' => 'UY', 'name' => 'Solís', 'active' => 1, 'slug' => 'solis'],
            ['id' => 23368, 'region_id' => 707826, 'country_code' => 'UY', 'name' => 'Algorta', 'active' => 1, 'slug' => 'algorta'],
            ['id' => 23369, 'region_id' => 707826, 'country_code' => 'UY', 'name' => 'Beisso', 'active' => 1, 'slug' => 'beisso'],
            ['id' => 23370, 'region_id' => 707826, 'country_code' => 'UY', 'name' => 'Cerro Chato', 'active' => 1, 'slug' => 'cerro-chato'],
            ['id' => 23371, 'region_id' => 707826, 'country_code' => 'UY', 'name' => 'Chapicuy', 'active' => 1, 'slug' => 'chapicuy'],
            ['id' => 23372, 'region_id' => 707826, 'country_code' => 'UY', 'name' => 'Eucaliptus', 'active' => 1, 'slug' => 'eucaliptus'],
            ['id' => 23373, 'region_id' => 707826, 'country_code' => 'UY', 'name' => 'Gallinal', 'active' => 1, 'slug' => 'gallinal'],
            ['id' => 23374, 'region_id' => 707826, 'country_code' => 'UY', 'name' => 'Guichón', 'active' => 1, 'slug' => 'guichon'],
            ['id' => 23375, 'region_id' => 707826, 'country_code' => 'UY', 'name' => 'Lorenzo Geyres', 'active' => 1, 'slug' => 'lorenzo-geyres'],
            ['id' => 23376, 'region_id' => 707826, 'country_code' => 'UY', 'name' => 'Merinos', 'active' => 1, 'slug' => 'merinos'],
            ['id' => 23377, 'region_id' => 707826, 'country_code' => 'UY', 'name' => 'Paysandú', 'active' => 1, 'slug' => 'paysandu'],
            ['id' => 23378, 'region_id' => 707826, 'country_code' => 'UY', 'name' => 'Piedras Coloradas', 'active' => 1, 'slug' => 'piedras-coloradas'],
            ['id' => 23379, 'region_id' => 707826, 'country_code' => 'UY', 'name' => 'Piñera', 'active' => 1, 'slug' => 'pinera'],
            ['id' => 23380, 'region_id' => 707826, 'country_code' => 'UY', 'name' => 'Porvenir', 'active' => 1, 'slug' => 'porvenir'],
            ['id' => 23381, 'region_id' => 707826, 'country_code' => 'UY', 'name' => 'Quebracho', 'active' => 1, 'slug' => 'quebracho'],
            ['id' => 23382, 'region_id' => 707826, 'country_code' => 'UY', 'name' => 'San Javier', 'active' => 1, 'slug' => 'san-javier'],
            ['id' => 23383, 'region_id' => 707842, 'country_code' => 'UY', 'name' => 'Algorta', 'active' => 1, 'slug' => 'algorta'],
            ['id' => 23384, 'region_id' => 707842, 'country_code' => 'UY', 'name' => 'Bellaco', 'active' => 1, 'slug' => 'bellaco'],
            ['id' => 23385, 'region_id' => 707842, 'country_code' => 'UY', 'name' => 'Fray Bentos', 'active' => 1, 'slug' => 'fray-bentos'],
            ['id' => 23386, 'region_id' => 707842, 'country_code' => 'UY', 'name' => 'Menafra', 'active' => 1, 'slug' => 'menafra'],
            ['id' => 23387, 'region_id' => 707842, 'country_code' => 'UY', 'name' => 'Nuevo Berlín', 'active' => 1, 'slug' => 'nuevo-berlin'],
            ['id' => 23388, 'region_id' => 707842, 'country_code' => 'UY', 'name' => 'Paso de los Mellizos', 'active' => 1, 'slug' => 'paso-de-los-mellizos'],
            ['id' => 23389, 'region_id' => 707842, 'country_code' => 'UY', 'name' => 'Rio Negro', 'active' => 1, 'slug' => 'rio-negro'],
            ['id' => 23390, 'region_id' => 707842, 'country_code' => 'UY', 'name' => 'San Javier', 'active' => 1, 'slug' => 'san-javier'],
            ['id' => 23391, 'region_id' => 707842, 'country_code' => 'UY', 'name' => 'Sarandí de Navarro', 'active' => 1, 'slug' => 'sarandi-de-navarro'],
            ['id' => 23392, 'region_id' => 707842, 'country_code' => 'UY', 'name' => 'Young', 'active' => 1, 'slug' => 'young'],
            ['id' => 23393, 'region_id' => 707853, 'country_code' => 'UY', 'name' => 'Lapuente', 'active' => 1, 'slug' => 'lapuente'],
            ['id' => 23394, 'region_id' => 707853, 'country_code' => 'UY', 'name' => 'Masoller', 'active' => 1, 'slug' => 'masoller'],
            ['id' => 23395, 'region_id' => 707853, 'country_code' => 'UY', 'name' => 'Minas de Corrales', 'active' => 1, 'slug' => 'minas-de-corrales'],
            ['id' => 23396, 'region_id' => 707853, 'country_code' => 'UY', 'name' => 'Rivera', 'active' => 1, 'slug' => 'rivera'],
            ['id' => 23397, 'region_id' => 707853, 'country_code' => 'UY', 'name' => 'Tranqueras', 'active' => 1, 'slug' => 'tranqueras'],
            ['id' => 23398, 'region_id' => 707853, 'country_code' => 'UY', 'name' => 'Vichadero', 'active' => 1, 'slug' => 'vichadero'],
            ['id' => 23399, 'region_id' => 707860, 'country_code' => 'UY', 'name' => '18 de Julio', 'active' => 1, 'slug' => '18-de-julio'],
            ['id' => 23400, 'region_id' => 707860, 'country_code' => 'UY', 'name' => '19 de Abril', 'active' => 1, 'slug' => '19-de-abril'],
            ['id' => 23401, 'region_id' => 707860, 'country_code' => 'UY', 'name' => 'Aguas Dulces', 'active' => 1, 'slug' => 'aguas-dulces'],
            ['id' => 23402, 'region_id' => 707860, 'country_code' => 'UY', 'name' => 'Arachania', 'active' => 1, 'slug' => 'arachania'],
            ['id' => 23403, 'region_id' => 707860, 'country_code' => 'UY', 'name' => 'Barra Del Chuy', 'active' => 1, 'slug' => 'barra-del-chuy'],
            ['id' => 23404, 'region_id' => 707860, 'country_code' => 'UY', 'name' => 'Castillos', 'active' => 1, 'slug' => 'castillos'],
            ['id' => 23405, 'region_id' => 707860, 'country_code' => 'UY', 'name' => 'Cebollatí', 'active' => 1, 'slug' => 'cebollati'],
            ['id' => 23406, 'region_id' => 707860, 'country_code' => 'UY', 'name' => 'Chuy', 'active' => 1, 'slug' => 'chuy'],
            ['id' => 23407, 'region_id' => 707860, 'country_code' => 'UY', 'name' => 'La Aguada', 'active' => 1, 'slug' => 'la-aguada'],
            ['id' => 23408, 'region_id' => 707860, 'country_code' => 'UY', 'name' => 'La Coronilla', 'active' => 1, 'slug' => 'la-coronilla'],
            ['id' => 23409, 'region_id' => 707860, 'country_code' => 'UY', 'name' => 'La Paloma', 'active' => 1, 'slug' => 'la-paloma'],
            ['id' => 23410, 'region_id' => 707860, 'country_code' => 'UY', 'name' => 'La Pedrera', 'active' => 1, 'slug' => 'la-pedrera'],
            ['id' => 23411, 'region_id' => 707860, 'country_code' => 'UY', 'name' => 'Lascano', 'active' => 1, 'slug' => 'lascano'],
            ['id' => 23412, 'region_id' => 707860, 'country_code' => 'UY', 'name' => 'Punta Del Diablo', 'active' => 1, 'slug' => 'punta-del-diablo'],
            ['id' => 23413, 'region_id' => 707860, 'country_code' => 'UY', 'name' => 'Rocha', 'active' => 1, 'slug' => 'rocha'],
            ['id' => 23414, 'region_id' => 707860, 'country_code' => 'UY', 'name' => 'San Luis Al Medio', 'active' => 1, 'slug' => 'san-luis-al-medio'],
            ['id' => 23415, 'region_id' => 707860, 'country_code' => 'UY', 'name' => 'Velázquez', 'active' => 1, 'slug' => 'velazquez'],
            ['id' => 23416, 'region_id' => 707878, 'country_code' => 'UY', 'name' => 'Belén', 'active' => 1, 'slug' => 'belen'],
            ['id' => 23417, 'region_id' => 707878, 'country_code' => 'UY', 'name' => 'Biassini', 'active' => 1, 'slug' => 'biassini'],
            ['id' => 23418, 'region_id' => 707878, 'country_code' => 'UY', 'name' => 'Cerro de Vera', 'active' => 1, 'slug' => 'cerro-de-vera'],
            ['id' => 23419, 'region_id' => 707878, 'country_code' => 'UY', 'name' => 'Colonia Itapebí', 'active' => 1, 'slug' => 'colonia-itapebi'],
            ['id' => 23420, 'region_id' => 707878, 'country_code' => 'UY', 'name' => 'Constitución', 'active' => 1, 'slug' => 'constitucion'],
            ['id' => 23421, 'region_id' => 707878, 'country_code' => 'UY', 'name' => 'Palomas', 'active' => 1, 'slug' => 'palomas'],
            ['id' => 23422, 'region_id' => 707878, 'country_code' => 'UY', 'name' => 'Puntas de Valentín', 'active' => 1, 'slug' => 'puntas-de-valentin'],
            ['id' => 23423, 'region_id' => 707878, 'country_code' => 'UY', 'name' => 'Salto', 'active' => 1, 'slug' => 'salto'],
            ['id' => 23424, 'region_id' => 707878, 'country_code' => 'UY', 'name' => 'San Antonio', 'active' => 1, 'slug' => 'san-antonio'],
            ['id' => 23425, 'region_id' => 707878, 'country_code' => 'UY', 'name' => 'Sarandí Del Arapey', 'active' => 1, 'slug' => 'sarandi-del-arapey'],
            ['id' => 23426, 'region_id' => 707878, 'country_code' => 'UY', 'name' => 'Saucedo', 'active' => 1, 'slug' => 'saucedo'],
            ['id' => 23427, 'region_id' => 707890, 'country_code' => 'UY', 'name' => 'Capurro', 'active' => 1, 'slug' => 'capurro'],
            ['id' => 23428, 'region_id' => 707890, 'country_code' => 'UY', 'name' => 'Delta Del Tigre', 'active' => 1, 'slug' => 'delta-del-tigre'],
            ['id' => 23429, 'region_id' => 707890, 'country_code' => 'UY', 'name' => 'Ecilda Paullier', 'active' => 1, 'slug' => 'ecilda-paullier'],
            ['id' => 23430, 'region_id' => 707890, 'country_code' => 'UY', 'name' => 'Ituzaingó', 'active' => 1, 'slug' => 'ituzaingo'],
            ['id' => 23431, 'region_id' => 707890, 'country_code' => 'UY', 'name' => 'Juan Soler', 'active' => 1, 'slug' => 'juan-soler'],
            ['id' => 23432, 'region_id' => 707890, 'country_code' => 'UY', 'name' => 'Kiyú - Ordeig', 'active' => 1, 'slug' => 'kiyu-ordeig'],
            ['id' => 23433, 'region_id' => 707890, 'country_code' => 'UY', 'name' => 'Libertad', 'active' => 1, 'slug' => 'libertad'],
            ['id' => 23434, 'region_id' => 707890, 'country_code' => 'UY', 'name' => 'Mal Abrigo', 'active' => 1, 'slug' => 'mal-abrigo'],
            ['id' => 23435, 'region_id' => 707890, 'country_code' => 'UY', 'name' => 'Playa Pascual', 'active' => 1, 'slug' => 'playa-pascual'],
            ['id' => 23436, 'region_id' => 707890, 'country_code' => 'UY', 'name' => 'Puntas de Valdés', 'active' => 1, 'slug' => 'puntas-de-valdes'],
            ['id' => 23437, 'region_id' => 707890, 'country_code' => 'UY', 'name' => 'Rafael Perazza', 'active' => 1, 'slug' => 'rafael-perazza'],
            ['id' => 23438, 'region_id' => 707890, 'country_code' => 'UY', 'name' => 'Rincón de la Bolsa', 'active' => 1, 'slug' => 'rincon-de-la-bolsa'],
            ['id' => 23439, 'region_id' => 707890, 'country_code' => 'UY', 'name' => 'San José', 'active' => 1, 'slug' => 'san-jose'],
            ['id' => 23440, 'region_id' => 707890, 'country_code' => 'UY', 'name' => 'San José de Mayo', 'active' => 1, 'slug' => 'san-jose-de-mayo'],
            ['id' => 23441, 'region_id' => 707890, 'country_code' => 'UY', 'name' => 'Villa María', 'active' => 1, 'slug' => 'villa-maria'],
            ['id' => 23442, 'region_id' => 707890, 'country_code' => 'UY', 'name' => 'Villa Rodriguez', 'active' => 1, 'slug' => 'villa-rodriguez'],
            ['id' => 23443, 'region_id' => 707907, 'country_code' => 'UY', 'name' => 'Cañada Nieto', 'active' => 1, 'slug' => 'canada-nieto'],
            ['id' => 23444, 'region_id' => 707907, 'country_code' => 'UY', 'name' => 'Cardona', 'active' => 1, 'slug' => 'cardona'],
            ['id' => 23445, 'region_id' => 707907, 'country_code' => 'UY', 'name' => 'Cuchilla Del Perdido', 'active' => 1, 'slug' => 'cuchilla-del-perdido'],
            ['id' => 23446, 'region_id' => 707907, 'country_code' => 'UY', 'name' => 'Dolores', 'active' => 1, 'slug' => 'dolores'],
            ['id' => 23447, 'region_id' => 707907, 'country_code' => 'UY', 'name' => 'Egaña', 'active' => 1, 'slug' => 'egana'],
            ['id' => 23448, 'region_id' => 707907, 'country_code' => 'UY', 'name' => 'José Enrique Rodó', 'active' => 1, 'slug' => 'jose-enrique-rodo'],
            ['id' => 23449, 'region_id' => 707907, 'country_code' => 'UY', 'name' => 'Mercedes', 'active' => 1, 'slug' => 'mercedes'],
            ['id' => 23450, 'region_id' => 707907, 'country_code' => 'UY', 'name' => 'Palmar', 'active' => 1, 'slug' => 'palmar'],
            ['id' => 23451, 'region_id' => 707907, 'country_code' => 'UY', 'name' => 'Palmitas', 'active' => 1, 'slug' => 'palmitas'],
            ['id' => 23452, 'region_id' => 707907, 'country_code' => 'UY', 'name' => 'Palo Solo', 'active' => 1, 'slug' => 'palo-solo'],
            ['id' => 23453, 'region_id' => 707907, 'country_code' => 'UY', 'name' => 'Risso', 'active' => 1, 'slug' => 'risso'],
            ['id' => 23454, 'region_id' => 707907, 'country_code' => 'UY', 'name' => 'Santa Catalina', 'active' => 1, 'slug' => 'santa-catalina'],
            ['id' => 23455, 'region_id' => 707907, 'country_code' => 'UY', 'name' => 'Soriano', 'active' => 1, 'slug' => 'soriano'],
            ['id' => 23456, 'region_id' => 707907, 'country_code' => 'UY', 'name' => 'Villa Darwin', 'active' => 1, 'slug' => 'villa-darwin'],
            ['id' => 23457, 'region_id' => 707907, 'country_code' => 'UY', 'name' => 'Villa de Soriano', 'active' => 1, 'slug' => 'villa-de-soriano'],
            ['id' => 23458, 'region_id' => 707923, 'country_code' => 'UY', 'name' => 'Achar', 'active' => 1, 'slug' => 'achar'],
            ['id' => 23459, 'region_id' => 707923, 'country_code' => 'UY', 'name' => 'Ansina', 'active' => 1, 'slug' => 'ansina'],
            ['id' => 23460, 'region_id' => 707923, 'country_code' => 'UY', 'name' => 'Cardoso', 'active' => 1, 'slug' => 'cardoso'],
            ['id' => 23461, 'region_id' => 707923, 'country_code' => 'UY', 'name' => 'Chamberlain', 'active' => 1, 'slug' => 'chamberlain'],
            ['id' => 23462, 'region_id' => 707923, 'country_code' => 'UY', 'name' => 'Cuchilla de Peralta', 'active' => 1, 'slug' => 'cuchilla-de-peralta'],
            ['id' => 23463, 'region_id' => 707923, 'country_code' => 'UY', 'name' => 'Curtina', 'active' => 1, 'slug' => 'curtina'],
            ['id' => 23464, 'region_id' => 707923, 'country_code' => 'UY', 'name' => 'La Pedrera', 'active' => 1, 'slug' => 'la-pedrera'],
            ['id' => 23465, 'region_id' => 707923, 'country_code' => 'UY', 'name' => 'Las Toscas', 'active' => 1, 'slug' => 'las-toscas'],
            ['id' => 23466, 'region_id' => 707923, 'country_code' => 'UY', 'name' => 'Laureles', 'active' => 1, 'slug' => 'laureles'],
            ['id' => 23467, 'region_id' => 707923, 'country_code' => 'UY', 'name' => 'Paso Bonilla', 'active' => 1, 'slug' => 'paso-bonilla'],
            ['id' => 23468, 'region_id' => 707923, 'country_code' => 'UY', 'name' => 'Paso de los Toros', 'active' => 1, 'slug' => 'paso-de-los-toros'],
            ['id' => 23469, 'region_id' => 707923, 'country_code' => 'UY', 'name' => 'Paso Del Cerro', 'active' => 1, 'slug' => 'paso-del-cerro'],
            ['id' => 23470, 'region_id' => 707923, 'country_code' => 'UY', 'name' => 'Piedra Sola', 'active' => 1, 'slug' => 'piedra-sola'],
            ['id' => 23471, 'region_id' => 707923, 'country_code' => 'UY', 'name' => 'San Gregorio de Polanco', 'active' => 1, 'slug' => 'san-gregorio-de-polanco'],
            ['id' => 23472, 'region_id' => 707923, 'country_code' => 'UY', 'name' => 'Tacuarembó', 'active' => 1, 'slug' => 'tacuarembo'],
            ['id' => 23473, 'region_id' => 707923, 'country_code' => 'UY', 'name' => 'Tambores', 'active' => 1, 'slug' => 'tambores'],
            ['id' => 23474, 'region_id' => 707923, 'country_code' => 'UY', 'name' => 'Valle Edén', 'active' => 1, 'slug' => 'valle-eden'],
            ['id' => 23475, 'region_id' => 707941, 'country_code' => 'UY', 'name' => 'Cerro Chato', 'active' => 1, 'slug' => 'cerro-chato'],
            ['id' => 23476, 'region_id' => 707941, 'country_code' => 'UY', 'name' => 'Isla Patrulla', 'active' => 1, 'slug' => 'isla-patrulla'],
            ['id' => 23477, 'region_id' => 707941, 'country_code' => 'UY', 'name' => 'María Albina', 'active' => 1, 'slug' => 'maria-albina'],
            ['id' => 23478, 'region_id' => 707941, 'country_code' => 'UY', 'name' => 'Santa Clara de Olimar', 'active' => 1, 'slug' => 'santa-clara-de-olimar'],
            ['id' => 23479, 'region_id' => 707941, 'country_code' => 'UY', 'name' => 'Treinta y Tres', 'active' => 1, 'slug' => 'treinta-y-tres'],
            ['id' => 23480, 'region_id' => 707941, 'country_code' => 'UY', 'name' => 'Valentines', 'active' => 1, 'slug' => 'valentines'],
            ['id' => 23481, 'region_id' => 707941, 'country_code' => 'UY', 'name' => 'Vergara', 'active' => 1, 'slug' => 'vergara']
    	];
    }
}
